### ISSUE TITLE
HTTP/HTTPS infinite loop in WordPress 4.4.1

### ISSUE THREAD

**Issue by kraftbj** [woothemes/woocommerce#10029]
When a site has a home/site URL set to https and both the `Force secure checkout` and `Force HTTP when leaving the checkout` are checked, it creates an infinite loop redirecting between http/https for all pages (other than the checkout page).

**Comment by kraftbj** [comment]
Possibly caused by https://core.trac.wordpress.org/changeset/36129 and a related report to https://core.trac.wordpress.org/ticket/35344.

**Comment by claudiosmweb** [comment]
Just activate both options and was not able to reproduce this behavior...
What more do you set up on your site?
Give more details.

**Comment by Ipstenu** [comment]
In order to explain this to end users: https://cloudup.com/cm2EtBJvOzn

Regardless of if this is a bug (which ... yeah) it's actually something you guys can prevent with a quick logic check. Check home/site URLs. If https, then the ability to "force http when leaving checkout" should be killed with extreme prejucide.

I was able to reproduce this as follows

1. Home and site URLs set to https
2. Checkout has "Force secure checkout" checked
3. Checkout has "Force HTTP when leaving the checkout" checked

As soon as I uncheck "Force HTTP when leaving the checkout" and flush browser caches, it's all happy again.

**Comment by claudiosmweb** [comment]
"Home and site URLs set to https" + "Checkout has "Force HTTP when leaving the checkout" checked".

Problem does not seem to WordPress 4.4.1 then... Since if you use HTTPS in all pages it's at least strange turn on an option to redirect people to HTTP...

**Comment by Ipstenu** [comment]
It's with 4.4.1 due to how the cannonicals were changed (see https://core.trac.wordpress.org/ticket/35344 ). Doesn't happen on 4.4 as far as I was able to see.

However I can give you a great example to how this would happen :)

I make my site and initially only have SSL on checkout pages, in order to use caching and make my site faster. When they checkout, I want them to kick back to http in order to send 'em back to caching. Then I realize I'm stupid and it's https everywhere, so I change my home/site URLs and search/replace the whole DB to make it all https.... and oops. I forgot that setting I checked a year ago.

Head desk.

**Comment by claudiosmweb** [comment]
Still don't make sense someone redirect by apache/nginx all urls to use HTTPS and then turn on an option to redirect to HTTP... But yeah, we need to prevent people of doing crazy things...

**Comment by Ipstenu** [comment]
Think of it the other way.

It's understandable to forget you checked an option to redirect to http when you change things to use https :)

**Comment by mikejolley** [comment]
Derp confirmed.
