### ISSUE TITLE
Incorrect argument passed to validate_FIELDID_field?

### ISSUE THREAD

**Issue by allendav** [woothemes/woocommerce#10032]
At https://github.com/woothemes/woocommerce/blob/ebfe703d62b3be1bf5af284d1e38dc7d8146fd23/includes/abstracts/abstract-wc-settings-api.php#L750

`$key` is passed to `$this->{'validate_' . $key . '_field'}` if that function exists, and then the value returned by that function replaces the value for that key in `$this->sanitized_fields`

but wouldn't it be more appropriate to pass the value from POST?

I guess since this ship has sailed, the best we could do would be to pass both now?

**Comment by mikejolley** [comment]
$key can be used to look up the field, but yes, passing both would be better.

**Comment by dangoodman** [comment]
Guys, why do you always break backward compatibility? That's very frustrating. Every other Woocommerce release I get tons of complaints from my users about warning and notices in my plugins since woocommerce update. This 2.6 release broken one of my plugin entirely, not just warnings/notices.

validate_xxx_field() methods is a public API. It's a no good to just blatantly change their signature and functioning.

**Comment by mikejolley** [comment]
If you'd told us this would become an issue in advance this might have been handled differently, or could have been handled in your codebase. Alas, it's too late now.

**Comment by dangoodman** [comment]
Didn't you think that breaks backward compatibility?

**Comment by mikejolley** [comment]
At the time I was fixing an issue, so perhaps it slipped through. Or perhaps no internal extensions were affected by the change. Sorry, I cannot test every single custom plugin out there - thats why there has been a beta since April.

**Comment by mikejolley** [comment]
Please ensure you test your extension with the next major update prior to launch to help avoid this, and/or document changes if needed. Just like we have to with major WP updates.
