### ISSUE TITLE
Selected shipping method is not remembered after updating the cart

### ISSUE THREAD

**Issue by thomasandersen** [woothemes/woocommerce#10052]
Make sure 2 or more shipping methods are activated.
Make sure 'Enable the shipping calculator on the cart page' is enabled.

1. Navigate to the cart
2. Select a shipping method
3. Click calculate shipping
4. From the calculate shipping dialog, click the update totals button

Expected result: 
The selected shipping method (step 2) should be selected.

Actual result:
The default shipping method is selected.

**Comment by mikejolley** [comment]
After the 'calculate shipping' event, methods are reset/recalculated and all choices lost on purpose. Otherwise a cheaper or default method with higher priority which the user *becomes* eligible for would not be chosen. This is the expected behavior.

**Comment by lifelightweb** [comment]
Twice in a row today, my customer had customer complaints regarding this "by design" functionality.  Customer had address entered already, picked shipping, changed mind on address.  Shipping then auto-changed to first one in list and it was WAY more expensive.  They didn't notice and checked out.    Isn't it possible for a scenario in code that if person is has already entered address and has already chosen shipping method and then changes address and new address qualifies for a set # of shipping options that if the old one picked is still in there, then keep it selected, otherwise throw an error that a new selection needs to be made?

**Comment by mikejolley** [comment]
I don't think we can satisfy both user sets tbh. There are filters in place to handle the selected method so a developer could customise this for you if it continues to be a problem. Since shipping is the last thing on the page, as well as order and shipping costs, I don't know how common it would be to miss it. Perhaps those are not visible enough on your checkout?

**Comment by mikejolley** [comment]
Sorry, I didn't check before responding.

This is where the reset occurs: https://github.com/woocommerce/woocommerce/blob/6b1d8fbb57d74a4afd4326db68a53862e4ce8c1a/includes/wc-cart-functions.php#L398-L424

See this filter https://github.com/woocommerce/woocommerce/blob/6b1d8fbb57d74a4afd4326db68a53862e4ce8c1a/includes/wc-cart-functions.php#L450

You can swap out the new default for the existing chosen method all available through that filter.

**Comment by GlennPresentsofMind** [comment]
Hi, I have the same issue but it is not clear how you fixed it.  In my situation, a customer selects a Local Pickup option and then enters their billing address resulting in their selection being lost.  How did you get your system to remembered the customer's shipping selection?

**Comment by adampatterson** [comment]
@GlennPresentsofMind This might help you.

When the address was updated, the selected shipping method was reverted back to local pickup.

I tried pulling the data from the session, but it seemed like it was already modified or possibly not yet set 🤷‍♂️

```php
// Prevent shipping methods from resetting when the address ups updated.
add_filter('woocommerce_shipping_chosen_method', function ($default, $rates, $package) {
    $customerChosenMethod = maybe_unserialize(WC()->session->get_session_data()['chosen_shipping_methods']) ?? false;

    if (is_array($customerChosenMethod)) {
        return $customerChosenMethod[0];
    }

    return $default;
}, 10, 3);
```
