### ISSUE TITLE
Setting WP General times to city based timezones creates issues with WC & WC Subscriptions

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#10179]
# Notes:
- Server Timezone: UTC
- WP Timezone: America/Chicago
- My Timezone: Central
- WP Version: 4.4.1
- WC Version: 2.5.1
- WCS Version: 2.0.8

# What happens
## System Status menu
- Server not set to UTC

## Subscriptions
- At Checkout: Subscription Start Date must be before current date
 - Source: `wcs-functions.php:126`

### Work Around
- Set general options timezone to `UTC-6` (would need to update this at/after daylight savings time)
 - This also fixes the System Status Timezone to a checkmark instead of an error
- Change line `wcs-functions.php:125` to include UTC ([solution found here](http://stackoverflow.com/a/33308791/661179))
 - This solution products an issue where the subscription doesn't actually start for 6 hours from purchase time (not a valid solution for me)

### For Real Resolution
- Allow WooCommerce to play nicely with City Based Timezone settings since it plays nicely with UTC Offsets to allow for Daylight Savings Time. And/Or discover the Offset for that timezone and use it.

**Comment by mikejolley** [comment]
This shouldn't be reported in the core github, but pinging @thenbrent anyway. I believe they have an issue logged around timezones https://github.com/Prospress/woocommerce-subscriptions/pull/1102

**Comment by majemedia** [comment]
There is a core WC issue in here as well.

A timezone based on a city (`America/Chicago`) will prompt an error in the WooCommerce system status screen.

A timezone based on a UTC offset (`UTC-6`) will not prompt the same error.

**Comment by thenbrent** [comment]
> At Checkout: Subscription Start Date must be before current date

@majemedia if you are getting that notice, you almost certainly have code somewhere calling `date_default_timezone_set()` and setting PHP's timezone to something other than UTC. This is bad and needs to be fixed. It will cause lots of issues with everything on your site, like post dates, order dates etc.

My suspicion that this is the issue is confirmed by [this patch fixing the issue](http://stackoverflow.com/questions/33262711/subscription-must-start-before-current-day-where-can-i-set-the-time/33308791#33308791). That suggested patch is simply appending `.' UTC'` to a timestamp to tell `strtotime()` to treat the timestamp as being in UTC instead of being in the _default PHP timezone_, but the _default PHP timezone_ on a WordPress installation should be UTC.

WordPress calls `date_default_timezone_set()` to set the PHP timezone to be UTC and then expects the rest of the application to run with UTC as PHP's timezone. WooCommerce, Subscriptions and really any other plugin using custom post types of WordPress APIs inherit this expectation.

If you are 100% sure this is not the case, please [open a support ticket](http://woothemes.com/my-account/create-a-ticket/) and provide FTP credentials to the site so we can investigate further. But of the 5-6 cases where we've seen that notice appear, all had custom code calling `date_default_timezone_set()`.

**Comment by majemedia** [comment]
@thenbrent as you suggested... there are definitely plugins calling `date_default_timezone_set()` in all my problem installations:

- Contact Form 7
- Yoast SEO

**Comment by lizettevanboom** [comment]
@majemedia what did you do to fix this problem? I'm having the same issue and can't seem to figure it out.

**Comment by majemedia** [comment]
@lizettevanboom Turns out it was some random other plugin installed on the site that was setting the timezone of PHP and not setting it back to UTC. I think it was AJAX Calendar (but it's been months...).

I promptly uninstalled that plugin since it turns out it wasn't used anyways.

**Comment by thenbrent** [comment]
@lizettevanboom try searching  your entire `/wp-content/` folder for instances of `date_default_timezone_set(` and see what turns up. Once you find a plugin which sets it to something other than UTC, but doesn't restore it to UTC, you've found the culprit. You can then follow up with that plugin's developers to get it fixed. 😄

**Comment by lizettevanboom** [comment]
Thanks for the tip, that worked! Turns out the Rich Reviews plugin was setting
the timezone to MST, which seems like a very bad idea. I disabled it since it
wasn't absolutely necessary.

On Apr 19 2016, at 2:22 am, Brent Shepherd &lt;notifications@github.com&gt;
wrote:  

> [@lizettevanboom](https://github.com/lizettevanboom) try searching your
entire `/wp-content/` folder for instances of `date_default_timezone_set(` and
see what turns up. Once you find a plugin which sets it to something other
than UTC, but doesn't restore it to UTC, you've found the culprit. You can
then follow up with that plugin's developers to get it fixed. 😄

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/woothem
es/woocommerce/issues/10179#issuecomment-211646728)![](https://github.com/noti
fications/beacon/AJNTNaWfq1Kc9g6V9iynNV1P781vv7VGks5p5CA0gaJpZM4HMxGk.gif)
