### ISSUE TITLE
no backorder check in shopping cart (anymore) on iPhone and iPad

### ISSUE THREAD

**Issue by alterview** [woothemes/woocommerce#10269]
We are having a weird problem with our shop. If we try to order an item that is nearly out of stock, we are able to order more then we have in stock. This issue only occurs on iPad and iPhone (using safari) and we can only do this from the shopping cart page. We run on the Storefront theme but I tried to isolate the problem using a different theme (Elegant Theme's Divi and Twenty Fifteen), but I can still order more then we have in stock, so it looks like a WooCommerce issue.

For example: Last night someone ordered 8 items of the same product, while we only had 1 in stock. Backorders are disabled in both the global settings as well as with the products.

It looks like the stock/backorder check which is used in the newer WooCommerce versions doesn't work on iPad and iPhone...

FYI: We are running on WordPress 4.4.2, WooCommerce 2.5.2 and Storefront 1.6.1

Note: I also tried if the issue arrises with a different shop I've built, but is still running an older version of all the software: WordPress 4.4.2, WooCommerce 2.4.6 and Elegant Theme's Divi 2.3.1. Everything is working fine there!! :) So something must have been changed...

**Comment by mikejolley** [comment]
The only explanation would be backorders or a plugin breaking the logic.

Why? Because browser makes no difference to the code we run on the server. The validation is all PHP based and shows this:

https://dl.dropboxusercontent.com/s/q4myhx1cywxvz84/2016-02-04%20at%2016.55.png?dl=0

Even if you force more stock in cart by editing markup, you get the above error and checkout is not permitted. This is testing on 2.5.2 and Twenty Twelve theme.
