### ISSUE TITLE
Out of stock products still show in WP search when 'Hide out of stock items from the catalog' set

### ISSUE THREAD

**Issue by stevemarksmonii** [woothemes/woocommerce#10265]
If i go to settings and tick '_Hide out of stock items from the catalog_', then set a product to out of stock, this product still appears when I do a standard WordPress search (i.e. http://mysite.com/?s=pants).

Do we think that's correct? To me, if you hide items from the catalog you technically want to hide from everywhere on the site.

**Comment by mikejolley** [comment]
It wouldn't be possible to correct his - if you do a standard search, it doesn't use the 'store' template files, so our logic to hide the product does not run. _This archive is not the catalog_

http://mysite.com/?s=pants&post_type=product however would hide them because it uses the shop template files.
