### ISSUE TITLE
Product Category Widget incorrectly counting hidden products

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/woocommerce#10279]
Customer reports that with the WC 2.5+, the Product Category Widget is incorrectly counting hidden products.

The end results is that the widget is show ```Product Category Title (0)``` even when the **Hide empty categories** checkbox is selected.

-- Screenshots:

* Widget Setup: http://cld.wthms.co/1lrFo/37aCi1S3
* Frontend Display: http://cld.wthms.co/1dSiq/3ZXRlHdn

I was able to replicate this on local with WC 2.5.2.

**Comment by reigelgallarde** [comment]
`$args` here [class-product-cat-dropdown-walker.php#L95](https://github.com/woothemes/woocommerce/blob/9dea16ab6cc07b0ce3871fd95cfcb4151a85e8dd/includes/walkers/class-product-cat-dropdown-walker.php#L95) and here
[class-product-cat-list-walker.php#L141](https://github.com/woothemes/woocommerce/blob/9dea16ab6cc07b0ce3871fd95cfcb4151a85e8dd/includes/walkers/class-product-cat-list-walker.php#L141) is a multidimensional array and should have been `$args[0]['hide_empty']` instead of `$args['hide_empty']`.
