### ISSUE TITLE
wrong API signature in v3

### ISSUE THREAD

**Issue by codingChris** [woothemes/woocommerce#10303]
There shouldn't be an ampersand after the consumer secret [in line 267 of class-wc-api-authentication.php](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L267).

Although the [documentation](http://woothemes.github.io/woocommerce-rest-api-docs/#authentication) states that each parameter should be joined with an ampersand, it doesn't say, that there should be one after the last parameter. API versions one and two also don't have this last ampersand.

If a user switches from v2 to v3 without modifing their client code he/she gets a 401 error.

**Comment by maxrice** [comment]
this is intentional in the v3 API, as prior versions did not conform to the OAuth 1.0a spec, where the use of the consumer secret must be joined to the consumer token (an optional part of the OAuth 1.0a spec) with an ampersand. Since v1/v2 versions of the API did not include that ampersand, they didn't work properly with most general OAuth libraries out there, which is why it was corrected in v3. @claudiosmweb can update the documentation to reflect the authentication difference between them :smile_cat:

**Comment by justinshreve** [comment]
See #8415

**Comment by codingChris** [comment]
Ok, thank you for clearing this up @maxrice and @justinshreve. The description of #8415 was really informative.

Should I close this issue now or should I leave it open as for the documentation update?

**Comment by claudiosmweb** [comment]
We have a note about it in our documentation:

http://woothemes.github.io/woocommerce-rest-api-docs/#version

![screenshot from 2016-02-10 11-30-42](https://cloud.githubusercontent.com/assets/1264099/12948523/bcd31a96-cfe9-11e5-93f2-eb8b8b0a861a.png)

If you are using our wrapper will not have this problem: http://woothemes.github.io/woocommerce-rest-api-docs/#official-libraries
