### ISSUE TITLE
Article number

### ISSUE THREAD

**Issue by gastonsaavedra** [woothemes/woocommerce#10326]
Hey, I've worked a bit with the REST API in woocommerce but can not find where or how to save the article ID in woocomerce from a json file with all my products. can anyone help me or guide me how to do. Everything else can I store in the database, but i cant find how I do with Article ID.

Thank you all

**Comment by mikejolley** [comment]
What is article ID?

**Comment by gastonsaavedra** [comment]
the article number id from a product. i can store the product name, the images, the description but i do not find where to put a the product article number id.

https://woothemes.github.io/woocommerce-rest-api-docs/?php#introduction

**Comment by mikejolley** [comment]
Are you talking about SKU? There is nothing called 'article number' in core.

**Comment by gastonsaavedra** [comment]
so i cant store a product with the article number. Because in woocomerce i can put the price and then a unique article number. and now a have a list with all my product in a json file that i want to import to woocommerce inclusive the unique article number.

**Comment by gastonsaavedra** [comment]
https://woothemes.github.io/woocommerce-rest-api-docs/?php#create-a-product

**Comment by mikejolley** [comment]
The properties available in the API are listed here:

https://woothemes.github.io/woocommerce-rest-api-docs/?php#products-properties

Core has no field called 'Article Number'. If thats added via a plugin, it would need to register and handle this property in the API, because the API will not pick it up automatically.

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L214

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L331

**Comment by gastonsaavedra** [comment]
Yes its the sku! :octocat: i had my page in Swedish but i change it to english and yes it was the sku, Sorry.
