### ISSUE TITLE
Coupon error not showing

### ISSUE THREAD

**Issue by esucces** [woothemes/woocommerce#10337]
FYI

I noticed that the woocommerce coupon error message does not show when both Yoast SEO and WP-SpamShield was activated. With only one of them activated, there was no problem.

Reported to WP-SpamShield aswell.

**Comment by mikejolley** [comment]
I am not sure of the relation between spam shield and yoast, but it appears the issue is Yoast SEO is rendering the content/shortcodes/error message when generating the 'meta description', and then when the real page content is rendered later on, the notice has already been cleared (notices display once before being cleared from the session).

I presume Yoast have some kind of logic in place to prevent this occurring under normal circumstances that spam shield is preventing.

To see this happening, post coupon and view page source. Look at meta description and twitter tags, with WP SPAMSHIELD and Yoast enabled. Pinging @CarolineGeven (not sure who's responsible over there).
