### ISSUE TITLE
Revise how Session Keys and IDs are created to avoid errors.

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#10389]
Explanation here: https://wordpress.org/support/topic/error-database-duplicate-entry-in-woocommerce_sessions?replies=3

@kloon also experienced the issue.

**Comment by kloon** [comment]
Im thinking this is related to master/slave db setups. We are seeing this occasionally as well and have my suspicion it might be to the fact that the session is written directly to master and in that time it takes for the slaves to update you might get a non existing result as the slaves have not updated yet and then it tries to write to session key again causing the duplicate warnings.

**Comment by silicondales** [comment]
I think its a master/master db in the linked WP support query. This feels likely to be a quite-intermittent db replication issue.

**Comment by nminkov** [comment]
I am the original reported of the bug. I thought initially that it's a master/master replication issue, but it can't be, otherwise the MySql server replication would have stopped because of the conflict. That is, if server A can't execute the query already executed on server B, replication halts and user intervention is required to sort it out.

I think is just 2 concurrent "session creation" calls generate the same ID, check that it does not exist (both get negative result), both try to insert the session ID in the DB, but only one will succeed. Its probably enough for store to has lots new visitors. 

Busier the store is, bigger the risk of conflict is. I just hope that when it happens, there is a reiteration of session creation, otherwise its probably lost customers to the store because they will probably note be able to add articles to the basket.

In worst case, this issue can crash a master/master server a replication!

**Comment by mikejolley** [comment]
@nminkov IDs are unique https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-session-handler.php#L117-L125

**Comment by nminkov** [comment]
Thanks, will check the code

**Comment by kloon** [comment]
I just pushed a fix live which fixes this, using wpdb->replace instead of doing a select and then choosing to do a insert or update. PR is on the way.

**Comment by nminkov** [comment]
Thanks kloon. Code is much simpler.
