### ISSUE TITLE
REST API: Product categories

### ISSUE THREAD

**Issue by owl1n** [woothemes/woocommerce#10386]
Hello, guys. 
I think you know what your methods for work with categories working very bad.
If adding new category, request return RANDOM category in system. Its fine? 
Or, why i dont can get category by NAME, if i dont know id of our category? I think its seriously bugs, u know it

**Comment by justinshreve** [comment]
Thanks for taking the time to report, but I'm not sure what you mean by a random category being returned and just calling things bad doesn't help us narrow down problems.  If you are experiencing issues, please post some details to help us track it down - things like WC Version, code examples, etc. The issue template should have asked for some of this.

When I create a new category via the REST API, the ONLY category returned is the one I just made so I don't think this a bug.

Having said that - @claudiosmweb what do you think of us supporting something like `GET /wc-api/v3/products/categories/slug:$slug` to retrieve categories (and we can do tags) by ID? I do agree that it would be useful since they are unique, easer to remember (example: I want to display the 'clothing' category and items, I might not know I need ID 9 to do it). WP.com's API also supports it and it is a useful addition.

**Comment by claudiosmweb** [comment]
@justinshreve I fixed it here: https://github.com/woothemes/woocommerce/commit/f6698006ce79be3db2ae3e02c9d6a4c55fbada98
