### ISSUE TITLE
Woocommerce status - not able to update status to cancelled, but able to update to processing, on-hold and completed

### ISSUE THREAD

**Issue by niels-tame** [woothemes/woocommerce#10392]
from the "high level" overview of orders I am able to change status of the order, but when I dive into the order and try to change status there, I select cancelled, click save/update, the page updates and says saved and in the small "activity log" it says "cancelled email sent", but when I head back to the "high level" overview the status of the order hasn't changed and the email is never received and all other types of emails is send as well only everything about cancelled status that is broken.

**Comment by WPprodigy** [comment]
Hi @niels-tame,

Typically issues like this are caused by either a conflict with your theme or with another plugin. Try temporarily switch back to the WordPress Twenty Twelve Theme, or [Storefront](http://www.woothemes.com/storefront/), and disable all plugins except for WooCommerce. If that resolves the issue, then slowly re-enable features until you find the one that's causing the conflict.

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by mikejolley** [comment]
Sounds like you're using the resend mail box, not changing the status in the status drop down...
