### ISSUE TITLE
Add action hook to custom inline data for woocommerce

### ISSUE THREAD

**Issue by mensmaximus** [woothemes/woocommerce#10470]
Working with customs fields in quickedit for products would be much easier if one could add custom data to the "Custom inline data for woocommerce" block in function render_product_columns() located in /woocommerce/includes/admin/class-wc-admin-post-types.php. 

An action hook like do_action( 'add_woocommerce_custom_inline_data', $post ) right before the closing div would be a great enhancement.

Patch file:
[class-wc-admin-post-types.txt](https://github.com/woothemes/woocommerce/files/157650/class-wc-admin-post-types.txt)

**Comment by mikejolley** [comment]
You can append data to this column using:

`
manage_product_posts_custom_column
`

Which if the hook we're using to add column content. That should be enough to add any extra data you need.

I don't feel it's worth adding a dedicated filter to WooCommerce for this, simply because adding data there doesn't also add the fields and handling of said fields. All of that requires custom javascript which WooCommerce will not handle for you.

Hope that helps.
