### ISSUE TITLE
Add to cart and Add to Wishlist Button not showing in Variable products section

### ISSUE THREAD

**Issue by geekysihag** [woothemes/woocommerce#10496]
Hey i have searched everywhere on internet but could not find a solution to this issue, my Add to cart and Add to Wishlist Button's are not showing in Variable products section. I have searched everywhere on the internet, all the posts were 2-3 years old and they did not fixed my issue..

I have tried every code to fix this issue, also tried the Js fixing plugin and all the fields are filled in my variable prroducts section, still no luck !

this is the link to my variable products http://www.groot.in/shop/taktik-360-extreme-iphone-6-plus/

Some guy closed my thread on github saying that We do not have a Wishlist plugin .... Please focus on the Add to Cart button !!!! That's the main thing .....
can anyone please help me ? It's really very urgent

**Comment by claudiosmweb** [comment]
> We do not have a Wishlist plugin

Wrong information, we don't have Wishlist on WooCommerce core. If you are talking about Woocommere Wishlist, it need to be reported on woothemes.com/support and not here. That's why I'm closing it again.

And please, read this before you open an issue: https://github.com/woothemes/woocommerce/blob/master/.github/ISSUE_TEMPLATE.md

Especially this part:

> I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).
