### ISSUE TITLE
Link between shipping_lines and line_items

### ISSUE THREAD

**Issue by CharlesP** [woothemes/woocommerce#10572]
Currently when an order includes multiple shipment methods there is no way to determine via the API which of the shipping_lines is for which line_item (item in the order).

It would be very useful if there is a link between line_items and shipping_lines in the Orders API so that we could determine which line_item is using which shipping_line.

Label: Enhancement
Label: API

**Comment by mikejolley** [comment]
This one isn't possible right now because the shipping system in general is not per-line, its per-order. WooCommerce also doesn't know or track what a plugin does with 'packages' when using multiple methods, so there is no way to determine what amount or % of a shipping cost is for what item(s). Does that make any sense?

We are introducing shipping meta data in 2.6 - once this hits, this could be used to list items in the shipping lines package, and thus would be exposed in the orders API for shipping lines. This will likely be in the new version of the API once @claudiosmweb is done since we're [currently reworking the spec](https://github.com/woothemes/woocommerce/pull/10259).

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/10574
