### ISSUE TITLE
Issue with the post object of the main shop page when it is set as a static WP front page

### ISSUE THREAD

**Issue by gnotaras** [woothemes/woocommerce#10609]
Hello all,

When the main WooCommerce shop page (slug _shop_ by default) is used as a static front page in WordPress, then the `$post` object, as returned by the `get_queried_object()` WP API function on the front page, is not a `WP_Post` object. It lacks some attributes such as `$post->post_content` or `$post->post_date`.

Is this intentional or is there a bug somewhere?

The expected behavior would to be `get_queried_object()` to return the `WP_Post` object of the WP Page that has been set as the static front page.

Thanks in advance for looking into this.

Kind Regards,
George

**Comment by mikejolley** [comment]
Party both. The shop page is not a real 'page' - its a custom post type archive. 

https://codex.wordpress.org/Function_Reference/is_post_type_archive

WooCommerce only uses the page as a placeholder object so it pulls the title and page ID when needed only.

Adding to the front page causes more issue because its not technically support by WP - we handle that in https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-query.php#L205

See https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-query.php#L267-L271 where we set the needed data, but not all and not a full WP_POST object. Setting this to the page itself causes notices we cannot prevent/control.

**Comment by gnotaras** [comment]
Hi @mikejolley 

I see. Thank you for your detailed reply!

George
