### ISSUE TITLE
Related products per_page inconsistency

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10676]
The related products don't consistently show up with the same per page number. Here is a quick screencast example: http://cld.wthms.co/1hSqT/5c93wFlM. Every once in a while, it will only display two rather than the default three. (Varies if you filter the per page argument, but it isn't consistent).

This happens if one of the related products isn't visible, so it fails the is_visible() check here: https://github.com/woothemes/woocommerce/blob/release/2.5/templates/content-product.php#L35

We need to exclude non-visible products from the `wc_related_*` transient I think. Maybe an extra set of IDs to exclude here: https://github.com/woothemes/woocommerce/blob/cb0f70308643f9d6bcdc11928ae6eb90d3020028/includes/abstracts/abstract-wc-product.php#L1337

**Comment by claudiosmweb** [comment]
@WPprodigy we need to check, but not a great idea exclude by ID, since we try fetch only visible products here: https://github.com/woothemes/woocommerce/blob/cb0f70308643f9d6bcdc11928ae6eb90d3020028/includes/abstracts/abstract-wc-product.php#L1616

But we save the results on transients in: https://github.com/woothemes/woocommerce/blob/cb0f70308643f9d6bcdc11928ae6eb90d3020028/includes/abstracts/abstract-wc-product.php#L1346

So maybe you just need to clear the transients.

**Comment by WPprodigy** [comment]
Yea, I've tried that: http://cld.wthms.co/fXbP/1ozgQMyq. ¯\\\_(ツ)\_/¯

**Comment by mikejolley** [comment]
This is fixed in master; there was a JOIN bug.
