### ISSUE TITLE
Add option to generate quarterly reports to help with sales tax filing

### ISSUE THREAD

**Issue by edgr-sanchez** [woothemes/woocommerce#10742]
When filing sales taxes for a small online store, they are sometimes generated quarterly.

Currently, you have to enter the date range manually. It would make sense to be able to choose Q1, Q2, Q3, or Q4. This could be shown beside the Year, Last Month, This Month, and 7 Days existing options. Maybe as a menu.

**Comment by mikejolley** [comment]
This wouldn't be very clear or flexible;

- What quarters would show if you're half way through the year?
- What happens if you do your taxes in say Q2 2016 for 2015?
- How do you know what Q year you're looking at?

Also, this sounds very country specific. Our tax year for example is April 4th to April 5th, so it is not a catch all solution and the 'custom' range works universally.
