### ISSUE TITLE
[2.6] Tax rates error with ranges

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#10765]
If you accidentally have a typo when setting up a range for tax zip codes, like `61111-611120`, when meaning  `61111-61120`- the page takes a long time to save. This is understandable, since it is trying to create a list of all the possible zip codes.

But with an accidental typo, you could cause a very long wait time, and if the customer refreshes, the tax page then appears to be blank. I presume this is because the data is trying to be loaded in. This causes all of the other tax rate pages to error out as well.  Eventually, the settings pages will come back - but it takes a while and is an awkward experience.

I wasn't able to replicate this locally, but I could on Pressable: http://cld.wthms.co/1c2gc/2oW89bfu. So I'm thinking there could be problems with a lot of other hosts as well.

**Comment by mikejolley** [comment]
Although there is potential for this to lock up the server, this isn't something you can add reasonable logic to because we cannot anticipate what users will want to generate, nor the upper limits of what may be wanted.

Instead I've worked on a PR for handling ranges instead of expanding them.. PR to follow.
