### ISSUE TITLE
Error when low in stock?

### ISSUE THREAD

**Issue by shawaj** [woothemes/woocommerce#10814]
We are facing an issue whereby if there is 1 unit of something in stock, the customer adds it to the cart and then is given the following message:

"Sorry, we do not have enough "XXX" in stock to fulfill your order right now. Please try again in 10 minutes or edit your cart and try again. We apologise for any inconvenience caused."

Is this a known issue? Any idea why it is happening?

**Comment by mikejolley** [comment]
Because you have a pending order with said item placed already. Thats why we have the option to cancel unpaid orders, so that stock is freed up asap. Gateways like paypal create pending orders before payment is confirmed.

Can you put support questions like this on the forum rather than the bug tracker in future please?
