### ISSUE TITLE
wc-cart-fragments keeps on refreshing

### ISSUE THREAD

**Issue by danyj** [woothemes/woocommerce#10875]
I tried everything , clearing cache , deleting cart items , published/unpublished  cart widget. it simply wont stop and it runs no matter on what page I am ,  as you can see it in this video  http://screencast.com/t/YpwsUmq6vN

the response is 
`
{"fragments":{"div.widget_shopping_cart_content":"<div class=\"widget_shopping_cart_content\">\n\n<ul class=\"cart_list product_list_widget \">\n\n\t\n\t\t<li class=\"empty\">No products in the cart.<\/li>\n\n\t\n<\/ul>\n\n\n<\/div>"},"cart_hash":""}`

I have no caching plugins ,  using Unsyon framework https://github.com/ThemeFuse/Unyson  to build a theme  ( tested with unsyon disabled ) , no extra WC modifications or hooks , everything is disabled ,  also tested on twentyfifteen  

Latest Chrome , 
WP 4.5.1 
WC 2.5.5

I browsed forums , git and only thing that can stop this is 

    wp_dequeue_script( 'wc-cart-fragments' );

which I rather not do but find the exact issue.

**Comment by mikejolley** [comment]
Need a URL to the site or this report is useless. I cannot replicate locally. It loads once and gets cached to local storage on subsequent loads.

**Comment by danyj** [comment]
I thought so ,  working locally on new theme so cant provide any links for now , 
what I did notice just now is that if I have any other WC theme hsop opened it starts to bug ,  
I had , jupiter shop and betheme shop opened , + my local WC  , when I closed theirs it stopped. 

Il close this for now until I can nail the issue.

**Comment by andrearosen1** [comment]
Had this happen too. it is due to this on the url: ?wc-ajax=get_refreshed_fragments. Site isn't live, but here is the url: https://wooc.nanps.org/online-plant-sale/. When you add to cart (which appears at the top of the page), then hit update, code appears. 

If you use this link you will see it: Alternatively, click this link to see the problem. Many thanks if anyone can help with this:

https://wooc.nanps.org/online-plant-sale/?wc-ajax=get_refreshed_fragments
