### ISSUE TITLE
Navigation Improvments

### ISSUE THREAD

**Issue by JoeHana** [woothemes/woocommerce#11010]
How are chances to get an improved account menu to properly position custom menu items. The current approach seems a bit not flexible enough I guess. The example code [()](https://woocommerce.wordpress.com/2016/04/21/tabbed-my-account-pages-in-2-6/) basically first removes the logout link, adds a new custom link and then re-adds the logout link again, but what if a custom page should appear more on top within the hierarchy? Removing all links and re-adding them afterwars again seems a little bit off to me. Is there any chance to get an improvment here still with the coming 2.6 release?

**Comment by claudiosmweb** [comment]
This is all about knowing how to work correctly with arrays, it's just an array... it's not a secret...

> but what if a custom page should appear more on top within the hierarchy?

You can insert links after any item using `array_splice()`, see http://php.net/manual/en/function.array-splice.php

Here an example for you my friend:

Let's add a new item after "Orders"... We know that "Orders" is the second item (in this case, position `1`, since in arrays the position starts in `0`), so we need to insert our custom item in the position number `2`:

```php
function my_new_menu_items( $items ) {
	$new_items = array();
	$new_items['custom-endpoint'] = __( 'My Custom Endpoint', 'woocommerce' );

	array_splice( $items, 2, 0, $new_items );

	return $items;
}

add_filter( 'woocommerce_account_menu_items', 'my_new_menu_items' );
```

But if you don't know the order, you can use `array_search()` and find the position, like this example:

```php
function my_new_menu_items( $items ) {
	$new_items = array();
	$new_items['custom-endpoint'] = __( 'My Custom Endpoint', 'woocommerce' );

	$position = array_search( 'orders', array_keys( $items ) );
	array_splice( $items, $position + 1, 0, $new_items );

	return $items;
}

add_filter( 'woocommerce_account_menu_items', 'my_new_menu_items' );
```

See that we use `array_search()` searching only in the keys for `$items` and after we use `$position + 1`, since we want to insert after "Orders", in the position `2` of the array.
