### ISSUE TITLE
Woocommerce and GTID

### ISSUE THREAD

**Issue by DuckDagobert** [woothemes/woocommerce#11096]
Woocommerce place order breaks when using MySQL GTID (https://dev.mysql.com/doc/refman/5.6/en/replication-gtids-concepts.html) 

Woocommerce will report a 402/525 error via woocommerce-error message on checkout when clicking place order.

This if from the logs:
"PHP message: WordPress database error When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables. for query INSERT INTO `myprefixwoocommerce_order_items` (`order_item_name`, `order_item_type`, `order_id`) VALUES ('NewVarCheckout', 'line_item', 17657) made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->create_order, WC_Abstract_Order->add_product, wc_add_order_item, QM_DB->query" while reading response header from upstream, client:

**Comment by mikejolley** [comment]
Something similar with master/slave has come up before and although we could not see a way to make this fully compatible, we did introduce a constant to disable transactions.

https://github.com/woothemes/woocommerce/blob/fe9b53e49a4b090543ee2dfe2d6a053a7640be32/includes/wc-core-functions.php#L1102

I believe it happens because during the transaction, after inserting the order, we also retrieve the order. Some master/slave setups cannot deal with this.

Use the constant and see if it solves the error on your server.

**Comment by DuckDagobert** [comment]
Fixed it today. The problem was that we had one staging site which had some MyISAM tables left (instead of InnoDB) which caused this 525 issue (bc MyISAM not transactional).
Also apparently some change between 2.3.5 and 2.5.2 was done, which fixes an other issue related to this, not sure what was changed (bc in 2.3.5 there would be a 402, in 2.5.2 it works).
GTID is fully supported now.
