### ISSUE TITLE
[API] Cannot view API response

### ISSUE THREAD

**Issue by amjad0** [woothemes/woocommerce#11120]
Using the latest version 2.6 with WP 4.4. I am authenticating using Basic Auth using WP admin account.

with HTTP

http://example.com/wp-json/wc/v1/orders

```
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
```

with HTTPS

https://example.com/wp-json/wc/v1/orders

```
{
  "code": "woocommerce_rest_authentication_error",
  "message": "Consumer Key is invalid.",
  "data": {
    "status": 401
  }
}
```

**Comment by claudiosmweb** [comment]
> with HTTP

You don't have permissions to kist the resourcers using your API Keys.

> with HTTPS

You are using a invalid consumer key.

**Comment by amjad0** [comment]
@claudiosmweb I thought the new API was integrated with WP API and we no longer needed to use WC API keys to use the WC rest api? I am not sending the API keys, I am sending the admin username and password.

**Comment by claudiosmweb** [comment]
@amjad0 and you installed any of the authentication methods from http://v2.wp-api.org/guide/authentication/ ?

**Comment by claudiosmweb** [comment]
@amjad0 do you that WP core don't have any authentication method by default to use the WP REST API with admin userame and password, right?

**Comment by claudiosmweb** [comment]
@amjad0 and since you did not read our docs, I'll send you it:

![screenshot from 2016-06-14 15-00-01](https://cloud.githubusercontent.com/assets/1264099/16053826/b93df4fa-3240-11e6-9184-f275fce4dce6.png)

**Comment by amjad0** [comment]
I did read the documentation but I guess I misinterpreted what I was reading! Thanks for clearing it out.

**Comment by amjad0** [comment]
@claudiosmweb I did read the documentation but I guess I misinterpreted what I was reading! Thanks for clearing it out.

**Comment by memerance** [comment]
@claudiosmweb I am having this issue, I cannot figure it out, I have gone through everything from how composer is installed to deleting the entire project and putting in a simple get request for orders, I am just repeatedly getting this error;

Via HTTP
Error: Invalid Signature - provided signature does not match. [woocommerce rest authentication_error]

If i try via HTTPS I get Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]

I have revoked keys, tried read only, read/write, I have created new users, added www
To give you context I have built an admin panel for multiple woocommerce stores combined. All was working perfectly, then all of a sudden this starts happening. I have tried turning off all other plugins, theme change etc.
Its just crazy!
Can you suggest anything?
Thanks

**Comment by RoohBear** [comment]
I'm also going crazy trying to get this to work and I've spent DAYS on this. Would actually pay someone to fix this and show me what's wrong. I'm getting the "{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}" response when I curl http://myFancyWebSite.wpengine.com/wp-json/wc/v1/products.  I get a giant response of "curl http://myFancyWebSite.wpengine.com/wp-json/wc/v1" so I think the WP API and the WC API are working and enabled. 

Am I supposed to add the keys to the end of the URL like this?:  "curl http://pantysalad.wpengine.com/wp-json/wc/v1/products -u ck_18a4f049f24fceaf7ee0837fd4867f8527c1a634:cs_ff6c83d47d4291375676652a5975850896ebb38d"  It doesn't seem to make a difference... I still get the "you cannot list resources" error.

**Comment by memerance** [comment]
I am trying with a nice bit of simple PHP with no mistakes, I had this working perfectly 24 hours ago, and now even with these few lines of code and only the PHP wrapper made by Woocommerce it still won't show me anything.

I have been reading further on the errors I listed earlier, some are saying it could be to do with CA certificates, or something along those lines. This is actually frustrating as f*@k because I haven't changed a thing to get this error.

So any input from anyone would be greatly appreciated. 

`require($_SERVER["DOCUMENT_ROOT"] . "/vendor/autoload.php");
use Automattic\WooCommerce\Client;
$woocommerce = new Client(
    'https://example.com', 
    'ck_*************************************', 
    'cs_*************************************',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]
);
/***************	TODAY SALES	**************/
print_r($woocommerce->get('orders'));


`

**Comment by memerance** [comment]
So I just managed to get a normal response when putting the call URL directly in to a browser.
It started working, so now I am narrowing it down to CURL not working as it should.
I am thinking that something wrong with the CA certificate cacert.pem could be the cause!
I'll keep you posted!

**Comment by benheutmaker** [comment]
Any progress on this? I have been stuck on this for weeks. Networking layer is lacking at the moment...

**Comment by RoohBear** [comment]
I can tell you that one thing I did was rip out some of the OAuth stuff in my version of WooCommerce (because it’s open source and we can do that kind of thing).  I probably made a giant security hole but don’t really care at the moment… I have to get some results then I can patch it up again when done.

-greg-

**Comment by RoohBear** [comment]
No because I’ve had other priorities lately.  My WooCommerce is my #2 or #3 priority right now.  I only get a chance to work on this during weekends and evenings but hopefully in the next few days I can revisit this again.

-greg-

**Comment by claudiosanches** [comment]
@bryceadams is it the same server problem that you reported to me?

**Comment by benheutmaker** [comment]
I ended up just authenticating with http basic auth over **_https_** with the key/secret added to the url as additional parameters

from the docs:
> Occasionally some servers may not parse the Authorization header correctly (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters instead.

> curl https://www.example.com/wp-json/wc/v1/orders?consumer_key=123&consumer_secret=abc

However I am calling this API from an iOS app via the [Alamofire](https://github.com/Alamofire/Alamofire) framework, not using curl... so it could be equivalent to calling it from a browser

**Comment by bryceadams** [comment]
@claudiosanches similar, but i never found a direct reason. instead i try all the different ways to authenticate automatically and choose the one that works - like if server isn't accepting headers, i'll add to the url like @benheutmaker did. in the end i can always connect, so people shouldn't have a problem authenticating if they try all of the options.

**Comment by stoneshower** [comment]
You can get the response of the all the products with this source (at least on my side).
But I'm struggling with how to list all the products with "/wp-json/wc/v1/products/" as is on http://woocommerce.github.io/woocommerce-rest-api-docs/?php#retrieve-a-product

```
<?php
    require_once( 'lib/woocommerce-api.php' );
    $consumer_key = 'ck_***';
    $consumer_secret = 'cs_***';

    $options = array(
        'ssl_verify'      => false,
        'debug'           => false,
    );
    try {

        $client = new WC_API_Client( 'http://***/', $consumer_key, $consumer_secret, $options );
        $product_data = $client->products->get( null, 
            array(
                'filter[limit]'   =>  -1 
            )
        );
        $product_data_json = json_encode($product_data);
        echo $product_data_json;

    } catch ( WC_API_Client_Exception $e ) {

        echo $e->getMessage() . PHP_EOL;
        echo $e->getCode() . PHP_EOL;

        if ( $e instanceof WC_API_Client_HTTP_Exception ) {

            print_r( $e->get_request() );
            print_r( $e->get_response() );
        }
    }
?>
```

**Comment by amjad0** [comment]
Yeah they changed how filters and meta data works which SUCKS. The legacy v3 API allowed this and it was simply great and easy. The new API has a lot of limitations. I have read a lot of complaints from WooCommerce API users. 

@mikejolley

**Comment by heemu9** [comment]
Hello

I am getting this error can some one help me in this issue.

{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by sissingclay** [comment]
```
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}
```
Hi,
I'm getting this error as well! Been new to wordpress I'm not sure where to add the following snippet below. I've added it to the root index.php file is this correct?

```
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://example.com', 
    'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
    'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    [
       'wp_api' => true, // Enable the WP REST API integration
        'version' => 'wc/v1', // WooCommerce WP REST API version
        'query_string_auth' => true,
	'verify_ssl' => false
    ]
);
```

**Comment by judgej** [comment]
"Read the docs before you try anything" is now a 404.

**Comment by amjad** [comment]
The new v2 is good. It allows meta fields access.

**Comment by judgej** [comment]
Yes, just noticed that. I wrote a plugin to add the custom metafields to product details for the earlier APIs, and it stopped working for [non-legacy] v2. Just looking into whether my plugin is really needed now (hopefully not). Just trying it now, the meta fields it returns seems to be a bit random - some of the user-editable custom fields, but not all, and some of the hidden underscore-prefixed meta fields, but not all. Going to need some work trying to see what is going on here.

But all that is OT, so I'll leave it there. I actually came to this issue due to the original authorisation error. My solution was to put the key and secret into GET parameters rather than using BASIC auth. Where-ever WC is getting these basic auth details from, they are being lost on my FastCGI server, and so not available for authorisation.

**Comment by Storeship** [comment]
I had this problem with a customers website we were trying to integrate, the problem was that the API user set up in Woocommerce was not marked as an Administrator, they must be an Administrator for it to work.
Unfortunately the response codes etc are not much help in pinpointing problems.
I am now getting the same response for another customer, works fine in the browser with results so it is getting muddled when sending the data behind the scenes, will post any findings.

**Comment by rickbeacham** [comment]
I'm having the same problem with  WooCOmmerce Rest API.  I'm not sure if its the Firewall,  Web Server, or Wordpress.  Is there a place to debug the problem? As Storeship and judgej said, it seems the CK and CS are getting lost somewhere in-between.   Not sure where to go from here.  A third party SAAS service needs API Rest access to WooCommerce but they seem to be clueless what the issue it.  

`https://www.somesite.com/wp-json/wc/v2/orders?oauth_consumer_key=ck_00000&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1504243603&oauth_nonce=IxoTDA&oauth_version=1.0&oauth_signature=00000`

`{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}'

This method works : 
https://www.somesite.com/wp-json/wc/v2/orders?consumer_key=ck_0000&consumer_secret=cs_000

Response:
'[
    {
        "id": 6250,
        "parent_id": 0,
        "number": "106250",
        "order_key": "wc_order_59a8c180c9575",
        "created_via": "",
        "version": "3.0.8",
        "status": "completed",
        "currency": "USD",
        "date_created": "2017-09-01T02:08:00",
        "date_created_gmt": "2017-09-01T02:08:00",
        "date_modified": "2017-09-01T02:11:02",
        "date_modified_gmt": "2017-09-01T02:11:02",
        "discount_total": "0.00",'

**Comment by U1timatePeter** [comment]
Trying to help others:
I was struggling with the 401 response while trying to CURL, and also with VBA trying to request as content-type "application/json"
However, I was able to pull a valid response by just entering this in my browser address bar:
https://mywebsite.com/wp-json/wc/v2/products?consumer_key=ck_blahblah&consumer_secret=cs_blahblah

Following this line of thought, I went back to my VBA app and changed the content type to "application/text" and was able to pull a valid response text with response code 200. 
Hope this helps someone.

**Comment by doekenorg** [comment]
I just wanted to drop this, in the hope it wil help others. I got the same error for weeks, and could figure it out. I wanted to update a product using the API. The code was working on local environment, but kept giving this error in production. And the most frustrating part: It DID connect, because ADDING a product DID work, and also Woocommerce told me in the keys section ;-)

After finding out I could **add** a product, I tried all sorts of connections. `GET`, `POST` and `PUT`. There I found out the problem was with `PUT`. 

Turns out my apache (2.4) configuration didn't allow for `PUT` connections (and therefore probably defaulted to `POST`, which is why the Woocommerce API is correct to give a 401 error 
 on `products/<id>`). So if you get this error, try a `GET` connection to the "orders". 

```php
$result = $api->get("orders");
var_dump($result);
```
If that works, your configuration is (probably) ok, but your httpd.conf may be off. 

```bash
#httpd.conf
...
<Limit GET POST OPTIONS PROPFIND PUT DELETE>
	Order allow,deny
	Allow from all
</Limit>
<LimitExcept GET POST OPTIONS PROPFIND PUT DELETE>
	Order deny,allow
	Deny from all
</LimitExcept>
...
```

Make sure PUT (maybe even PATCH and DELETE) are in there. (and restart apache if it wasn't). 

Hope this helps someone!

**Comment by gatisdukurs** [comment]
This was giving me headaches too for several hours.

**Comment by dlm423** [comment]
Setting 'query_string_auth' to true seems to work for most sites but not all.  I'm not sure why but some sites will return the 401 error for PUT/POST requests unless you include an additional header in your request like this:

`Authorization: Basic {base64_encode(c_key: c_secret)}`
