### ISSUE TITLE
Backorders allowed doesn't let customer order on front end when product Out Of Stock

### ISSUE THREAD

**Issue by jkohlbach** [woothemes/woocommerce#11187]
Latest version of WordPress + WooCommerce 2.6.1 + Stock theme – no other plugins enabled.

The backorders setting on the product doesn't appear to have any effect when a product is marked "Out Of Stock". Setting to Allowed or Allowed but notify doesn't allow the customer to order the product when it should.

STEPS TO REPRODUCE THE ISSUE

1. Install fresh WP + Woo 2.6.x
2. Create a Simple product, give it a price
3. Goto Inventory tab, Enable stock management, set stock to 0, set Stock status as "Out Of Stock" (important as it appears backordering works fine when product is marked "In Stock" but stock is 0), change the Backorder setting to "Allow, but notify customer" or "Allow"
4. Try to add to cart on the front end. It says out of stock instead of available on backorder.

Previous behaviour pre-2.6.0 was that items with Allow Backorder will be available for ordering regardless of the Stock Status setting.

To verify, I compared two installations with the same settings as above:
In 2.6, on the front end it says we CANNOT do a backorder it reports "Out Of Stock"
In 2.5, on the front end it says we CAN do a backorder it reports "Available On Backorder"

Not sure why this changed but its going to negatively effect a lot of stores as this subtle behaviour change is hard to detect.

**Comment by mikejolley** [comment]
> Not sure why this changed but its going to negatively effect a lot of stores as this subtle behaviour change is hard to detect.

I don't know if that is or is not the case, but there is a reason this was changed.

_History lesson:_

In the docs, status change handlers etc, enabling backorders has always prevented the stock status going "out of stock".

As an example, if the stock of a backorderable product hit 0, stock status has always remained as "in stock".

Essentially, when ever anyone has asked about this the answer has been that items on backorder are considered "in stock" by core.

_Missing use case:_

The missing use case was however that if you wanted to stop selling a product on backorder (maybe there is a backorder limit?) setting out of stock did not affect if the product can be purchased or not. This was considered a bug. 

See commit https://github.com/woothemes/woocommerce/commit/4c59fb3908fe4a1372435ac93503e01681281309

So now, manual changes to "out of stock" are honored. This won't affect users unless they manually set the stock status, since core would keep backorders in stock as mentioned above.

cc @claudiosmweb

**Comment by jkohlbach** [comment]
No worries Mike, makes sense.

So just wanted to confirm one final behaviour surrounding this...

If I have a product that is "In Stock" with 0 qty and backorders is marked as "Allowed", but then I re-save the product changing the backorders setting to "Do Not Allowed", it seems to automatically change the Stock Status to "Out Of Stock".

Is that correct?

Seems a bit confusing now given your comments above about the new behaviour. I don't think it really needs to automatically move the stock status anymore since that stock status setting's sole purpose is literally now only for manually putting a product out of stock.

The reason I'm asking is we have a solution which overrides the backorder setting to allow certain users to always be able to backorder. But now with the new behaviour, having the stock status as "Out Of Stock" basically means thats not possible anymore unless the product is "In Stock".

**Comment by klocki** [comment]
Hello, 
The new behaviour for backorders doesn´t make sense - and it is not working well together with the logic of ERP Connectors. 

If quantity is 0 the product should be out of stock and if you allow backorders for the product the product should be still out of stock but the user should be able to order it. It is NOT the same as if the product would be "in stock" because for backorders we display a different time for delivery than for items which are on stock. 

This is how the logic should work:

- Available: 10 Backorder: no - display: "on stock"  enable add to cart
- Available: 0 Backorder: no - display: "out of stock"  disable add to cart
- Available: 10 Backorder: yes - display: "on stock"  enable add to cart
- Available: 0 Backorder: yes - display: "delivery time  X - Y days"  enable add to cart

I think this makes much more sense than the logic that is implemented right now.

Kind regards, 
Alex

**Comment by merchantweb** [comment]
I'm with you Alex! I was using the backorder and stock setting functionality as you described above by changing the backorder message to say "Usually Ships in 1 Day" rather than In Stock because in our situation a product in stock was something we physically had in store and could ship the same day. I was also able to use the instock class to add an icon after products in the list to signify they were available for purchase in store. All other products that we do not have in stock are also available for backorder. 

So this update is messing with our configuration and I'm currently creating a workaround for our situation. I'm thinking of creating an in-store category but I don't have a way to automatically add products with stock to a specific category. I liked having the css class definition to play with for user experience purposes. Now everything has the class instock because we make all our skus available on backorder if not physically available in store, therefore, I cannot show a visual icon on only in store (in stock) items.

> The missing use case was however that if you wanted to stop selling a product on backorder (maybe there is a backorder limit?) setting out of stock did not affect if the product can be purchased or not. This was considered a bug.

> 

If you want to stop selling something on backorder, then turn off allow backorder for that product. Is it that hard? Not a bug... it was right.

**Comment by nconstant** [comment]
I am also having this problem. It would be good if the Add to Cart button was enabled if "allow backorders" is enabled and inventory is Out of Stock.

**Comment by svenm73** [comment]
Same here - just porting a b2b shop from shopware and actually thought the behaviour it would be a bug - as it really does not make sense. We have an ERP System in the background which does have a different logic when it comes to backorders. For us this leads to a lot of manual word a round. And also our retailers would hardly understand that logic either ... The previous behavior is correct - it would be really great if that would be changed again. kind regards, Sven

**Comment by mikejolley** [comment]
No point commenting on this old thread, see https://github.com/woocommerce/woocommerce/issues/11259
