### ISSUE TITLE
stock status showing even when stock management is off

### ISSUE THREAD

**Issue by chrismccoy** [woothemes/woocommerce#11181]
On previous versions of woocommerce, if you have stock management turned off, nothing would show on the product page.

Now "In Stock" shows regardless, i don't know if this was overlooked or a bug.

This happens in version 2.6

To disable it from showing i had to use a filter

    add_filter( 'woocommerce_get_availability', '__return_false');

**Comment by WillBrubaker** [comment]
> i don't know if this was overlooked or a bug.

Not a bug:

See https://github.com/woothemes/woocommerce/issues/11171

**Comment by claudiosmweb** [comment]
@chrismccoy BAD, BAD, BAD idea! Well, not a bad idea if your intension is to kill your site!
Since this will broke a lot of things in your site and hide the message when is "Out of stock".

Here how to hide ONLY the "In stock" message: https://claudiosmweb.com/en/woocommerce-en/woocommerce-2-6-hide-the-in-stock-message-on-product-page/

**Comment by claudiosmweb** [comment]
@chrismccoy https://www.youtube.com/watch?v=umDr0mPuyQc

**Comment by claudiosmweb** [comment]
@chrisnharvey you can return only a empty string using:

```php
add_filter( 'woocommerce_stock_html', '__return_empty_string' );
```

This controls only the "html", but NEVER broke the `woocommerce_get_availability`.

**Comment by chrismccoy** [comment]
thanks for that, wasnt aware of that filter

**Comment by chrisnharvey** [comment]
Erm...... Why am I tagged in this?
