### ISSUE TITLE
Handle admin access restriction more flexibly

### ISSUE THREAD

**Issue by scottsb** [woothemes/woocommerce#11198]
Currently in the function `prevent_admin_access()` WooCommerce blocks admin login if you don't have either the `manage_woocommerce` or `edit_posts` capabilities granted to your role. This means that it is impossible to create a role that can manage the catalog or orders without also granting them access to manage content or configuration settings. The web is littered with users running into this problem with proposed solutions running from hacking the extension files directly to overriding the functionality in a `woocommerce_prevent_admin_access` filter. The need to be able to grant only non-configuration e-commerce access is incredibly common, so it is quite surprising for it not to be possible without custom code.

I propose that instead of considering `manage_woocommerce` in `prevent_admin_access()` you either:
* Create a new capability `view_woocommerce` (or similar) that prevents redirecting away from admin but doesn't itself grant permission to view/edit anything specifically.
* Create new individual `manage_` capabilities for products, orders and possibly other types of entities, and consider all of these rather than the overarching `manage_woocommerce`.

**Comment by mikejolley** [comment]
You do understand this filter/restriction grants no capabilities other than the ability to ACCESS the WP dashboard? 

Generally, on an eCommerce site, customers should not be able to see the dashboard. It should be locked down. Allowing customer access to a WP dashboard does not seem like a common requirement? I'd argue it's more common to want that than to prevent it, since membership sites are a minority, than allow access.

Yes we see the odd request, but it's simple to remove the filter...

```
add_filter( 'woocommerce_prevent_admin_access', '__return_false' );
```

Thats it. 1 line. More advanced access restriction to the dashboard itself should not be facilitated by WooCommerce. If you need that, then add your own custom logic?

I think additional capabilities will just complicate matters. Capabilities themselves are not easy to work with, so if you're delving into that system it won't be a massive stretch to code your own filter and use a simple https://codex.wordpress.org/Function_Reference/current_user_can function.

I vote no to this issue.

cc @claudiosmweb @mattyza @BFTrick

**Comment by scottsb** [comment]
@mikejolley, there's a misunderstanding. I understand this is in regard to the admin. I'm not talking about allowing customers to be able to get past this filter restriction: I'm talking about store employees who you want to be able to manage catalog items or orders without having permission to change overall store configuration (like payment methods, shipping parameters, etc.). For example, a marketing intern may need to edit product descriptions, or a warehouse employee may need to view order information, but neither should be able to change store settings.

**Comment by claudiosmweb** [comment]
Do not seems to be a good idea, since the filter is more flexible and no need to change any user role.

> For example, a marketing intern may need to edit product descriptions, or a warehouse employee may need to view order information, but neither should be able to change store settings.

Easy to do with the filter :)

**Comment by mikejolley** [comment]
An editor has edit_posts capability. Surely they would have this cap?

**Comment by scottsb** [comment]
@claudiosmweb, yes, for a developer it is trivial. It's probably even easy for a non-developer since it can be easily copy-and-pasted (though I think it's poor practice to encourage editing code files you don't understand). Any given business may have unusual requirements that will require custom coding to adapt permissions, but separating configuration from catalog/order management is fundamental. You can make a fairly strong case it's even required by PCI DSS:

> 7.1.2. Restrict access to privileged user IDs to least privileges necessary to perform job responsibilities.
>
> When assigning privileged IDs, it is important to assign individuals only the privileges they need to perform their job (the “least privileges”). ... Assigning least privileges helps prevent users without sufficient knowledge about the application from incorrectly or accidentally changing application configuration or altering its security settings. Enforcing least privilege also helps to minimize the scope of damage if an unauthorized person gains access to a user ID.

Not that WooCommerce desires to be like "other platforms," but for what it's worth, I am not aware of a single other e-commerce platform that groups store configuration in the same access role as basic store operation out of the box.

@mikejolley, not necessarily. Merchandising and content management can be separate responsibilities, though you're right that they often overlap. The more clear case (and the one that immediately led to this request) is that of the fulfillment center employee only needing to see orders and nothing else.

**Comment by claudiosmweb** [comment]
> though I think it's poor practice to encourage editing code files you don't understand

What? Edit code files?
I believe you do not understand anything what I said...
This filter allows you to do exactly what you want, you can use to allow any type of user role and no need to "edit" anything, you can [write a new plugin for it](https://codex.wordpress.org/Writing_a_Plugin), only 3 or 5 lines of code and it's done.
It's more hard create a new capability and assign to users than use this filter.

> This means that it is impossible to create a role that can manage the catalog or orders without also granting them access to manage content or configuration settings.

Ok, a user than can manage the catalog or orders will usually need `edit_posts` too...
https://codex.wordpress.org/Roles_and_Capabilities#edit_posts

**Comment by scottsb** [comment]
> What? Edit code files? I believe you do not understand anything what I said...

I do understand what you are saying. The simplest way to add a filter (and what would typically be recommended to a non-developer, as I started that sentence) would be to add it to your `functions.php`. A separate plugin would be cleaner, sure, but a non-developer is not likely to attempt that. Lest you question the fact that dropping the filter into `functions.php` is what's recommended, see:
https://wordpress.org/support/topic/custom-role-woocommerce

Please understand that I am not pleading an inability to add a filter myself. If you check out my GitHub profile you will see I am very competent PHP developer. I'm arguing that adding this functionality will be better for the many users of WooCommerce who do not have my level of experience.

> It's more hard create a new capability and assign to users than use this filter.

Yes, it's (somewhat) harder, but if you do it as part of the base WooCommerce software as I'm suggesting here, then you save many, many of your users from having to do it manually.

> Ok, a user than can manage the catalog or orders will usually need edit_posts too...

No, not necessarily. Now I don't believe you're understanding what *I'm* saying. :-) Any business larger than a few people will have a separation of responsibilities, and somebody working in the warehouse for fulfillment should not be able to go update the website content.

**Comment by claudiosmweb** [comment]
@scottsb 

> A separate plugin would be cleaner, sure, but a non-developer is not likely to attempt that.

A non-developer that wants to "create a role that can manage the catalog or orders"... Well really seems hard...  And if you are trying to create this kind of roles, means that you have employees, will be nice hire a developer to do this kind of customization...

> Any business larger than a few people will have a separation of responsibilities, and somebody working in the warehouse for fulfillment should not be able to go update the website content.

Ok, another case here seems nice have a developer in the team.

As we said, you can allow anyone to access the admin dashboard with only line of code... But still you need to be a developer to create new roles for people that will only edit the "catalog", "orders" or "reports", since you'll need to allow some kinds of capabilities... Like for products, you may need `edit_product` and `edit_others_products`, but this don't allow to manage any categories, tags and other products taxonomies.

**Comment by claudiosmweb** [comment]
Now let's discuss what is important in this topic, since it is clear that you need a developer for this sort of thing.

> Create new individual `manage_` capabilities for products, orders and possibly other types of entities, and consider all of these rather than the overarching `manage_woocommerce`.

No need of it, since by default all objects already have caps for it.

For example you can create a new role only for manage orders:

```php
add_role(
	'orders_manager',
	__( 'Orders manager' ),
	array(
		'read' => true,
		'edit_posts' => true,
		'delete_posts' => false,
		'read_product' => true,
		'edit_shop_order' => true,
		'read_shop_order' => true,
		'delete_shop_order' => true,
		'edit_shop_orders' => true,
		'edit_others_shop_orders' => true,
		'publish_shop_orders' => true,
		'read_private_shop_orders' => true,
		'delete_shop_orders' => true,
		'delete_private_shop_orders' => true,
		'delete_published_shop_orders' => true,
		'delete_others_shop_orders' => true,
		'edit_private_shop_orders' => true,
		'edit_published_shop_orders' => true,
	)
);
```

Or for only read reports:

```php
add_role(
	'view_reports',
	__( 'View reports' ),
	array(
		'read' => true,
		'edit_posts' => true,
		'delete_posts' => false,
		'view_woocommerce_reports' => true
	)
);
```

> Create a new capability `view_woocommerce` (or similar) that prevents redirecting away from admin but doesn't itself grant permission to view/edit anything specifically.

This one is fine (need to improve the name of course, since it's the WordPress dashboard), since you don't want allow people submit posts for moderation, no need to add by default to all existing user rules too, but we can test it while applying the `woocommerce_prevent_admin_access` filter.
Still the filter is more flexible than this capability.
