### ISSUE TITLE
Allow registration without immediate authorization after checkout

### ISSUE THREAD

**Issue by cclass** [woothemes/woocommerce#11201]
There is already a filter added to prevent immediate authorisation after registration from #6707 but this filter doesn't apply to the registration auth cookie set during checkout. I propose adding the same filter in the checkout class so that developers can prevent automatic login.

I believe there are some other changes that will need to be made as the checkout class performs some actions after logging the user in (e.g. reloading checkout, recalculating totals).

```
if ( apply_filters( 'woocommerce_registration_auth_new_customer', true, $new_customer ) ) {
    wc_set_customer_auth_cookie( $new_customer );
}
```

**Comment by mikejolley** [comment]
This doesn't seem like a good idea. If the user is not logged in, the user account will not be linked to the order itself.

**Comment by cclass** [comment]
Right, OK definitely not then. 

The use case for this is to delay a user's membership start date until they log in (in conjunction with WooCommerce Memberships).

Currently, a user's membership starts immediately upon checkout (when they are automatically logged in). However, some users may sign up for a membership (more specifically, a 'trial' membership that only lasts a shorter period of time than a normal membership) and then leave the site only to come back at a later date and find that their membership started immediately and it has now expired.

A possible solution would be to start the membership when the user first logs in (hence this issue/PR) however this isn't currently possible as the user is automatically logged in after registering during checkout.

Apologies if this should be raised with WooCommerce Memberships and not here and thanks for the reply.

**Comment by mikejolley** [comment]
I think a better way to tackle it would be to a) only allow access to the thing they are joining if they have a complete order, or b) a certain role (beyond customer). Most sites have multiple ways to get accounts.

**Comment by cclass** [comment]
Thanks for the suggestions though I don't think it solves the problem.

When a user completes checkout for a free product for example, their order is automatically completed and their access is granted – the start date being set to the moment this happens. Being able to delay the start date to when they first log in (logging in starts their access period) may not be the only way to do this but it seems the most straightforward and would make sense to the user.

I will keep looking for another solution.

Thanks again

**Comment by mikejolley** [comment]
Yes but if you had protected content you wouldn't just give this to members without a certain privileged role would you?

**Comment by cclass** [comment]
This is more about when their access to the protected content starts.

A user signs up for a 1 day trial and their access starts right away. Perhaps the user signed up without the intention to start exploring the protected content immediately. 2 days later they come back and log in only to find their access has been revoked because their trial membership expired. 

Sites with trial memberships typically don't allow a user to sign up for another trial using the same email address. This might put some potential customers off from paying for a full membership.

Instead, what if the user signs up for the limited length trial membership (in my example it is 1 day, but same goes for typical 14 and 30 day trial memberships) and is able to come back to the site when they'd like and, having already signed up, log in with their account which would start access to the protected content from time they logged in plus 1 day (or any other length).

**Comment by mikejolley** [comment]
Ok, I kinda understand your reasoning, however I don't understand why you'd sign up for a trial if you have no intention of trailing it after signup.

**Comment by cclass** [comment]
Perhaps this use case is too unique to our organisation (although there might be other reasons it would be useful to be able to filter automatic login) but I don't find it all that unusual – I know that I sign up to multiple trials regularly and don't often have the time to explore in detail what the service offers within the trial period and I find myself having to re-sign up with another email. Perhaps a user is signing up for a trial in anticipation of using the membership in the near future but not immediately after signing up.

Trials which allow access to content are usually shorter than other types of services to avoid users scraping as much content as they can before the trial ends.

**Comment by bekarice** [comment]
Hey @cclass, noticed this note: 

> The use case for this is to delay a user's membership start date until they log in (in conjunction with WooCommerce Memberships).

Specifically here:

> Currently, a user's membership starts immediately upon checkout (when they are automatically logged in). 

This is because the membership is hooked into the order being marked processing or completed with the `grant_membership_access()` function. You could remove these actions so that Membership doesn't automatically grant access from the purchase. However, granting access your own way is going to be a bit more challenging since you want it decoupled from the order.

I'd recommend checking into these approaches:

1. Remove the current access-granting actions. Add a function that works similar to `grant_membership_access()` to check the order for eligible membership items. Instead of creating the user membership, add usermeta that indicates a membership is "pending creation". Hook into `wp_login` and check for that usermeta; if found, delete it and create the new membership then. 

2. Let the membership be created when the order is processed, but pause it immediately (perhaps even add some postmeta to the new user membership CPT). On `wp_login`, check for both the paused status and this meta, then make the membership active on login / delete the meta so that it "begins" with the first login.

Probably takes some tinkering, but I agree with Mike that this isn't core territory for WooCommerce or for Memberships since I've not seen any other requests / feedback in this vein. Happy to add hooks if you find places you'd need them in Memberships as you go, just get in touch via the Woo Zendesk 😸

**Comment by cclass** [comment]
@bekarice @mikejolley thanks for the feedback. will look into your suggestion, @bekarice and will update this once i find a solution in case anyone else might find it useful

**Comment by HaileyKay** [comment]
Any news on what logic ended up helping this ? I'm looking to do a similar process! only authroize user on first login and not auto login on checkout

**Comment by cclass** [comment]
@HaileyKay IIRC, unfortunately we never found or implemented a solution that we were happy with and just kept it as is – the use case was very specific to the organisation I was with at the time. @bekarice's proposed solution is probably the best way to go about it.
