### ISSUE TITLE
Cached Shipping causing Error Messages

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#11226]
When a customer changes shipping methods or destinations during checkout, existing error messages aren't removed. As an example:

[On the customer site here](https://blueskylingerie.com/), shipping isn't available to Alaska or Hawaii. They're using Conditional Shipping but that plugin relies on the default WooCommerce error messages.

When I try to check out with Alaska as my selected state:

![http://cld.wthms.co/1bxWS/3mGbh6L6](http://cld.wthms.co/1bxWS/3mGbh6L6+) 

When I change that state to Ohio:

![http://cld.wthms.co/1kpcA/3CE55zkN](http://cld.wthms.co/1kpcA/3CE55zkN+) 

We need some sort of call to remove that error message when the issue has been fixed.

-----
Related Ticket: #432550

**Comment by franticpsyx** [comment]
For some extra clarity, I am adding some more details from 432550:

WC core displays (adds) notices (https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-ajax.php#L410) in response to ajax updates of the checkout page (for instance when a different shipping method is selected). However, there is no logic or API for removing notices in response to a successful ajax refresh (that contains to notices to display).

Here's an example:

http://cl.ly/0z3M20121R1m

Note that when a notice is returned with an `update_order_review` response, it is not appended to any existing ones - it "deletes" them. As reported here, the added notice persists until the form is submitted.

The resulting UX is a bit messy without some logic to "remove" notices added by `update_order_review` responses. If some 3rd party code adds a notice during an `update_order_review` refresh, I guess it would be safe to assume that if the same notice is not present after a subsequent refresh, then it can safely be removed. However that would require a way to identify notices in a unique manner.

Also, I'm not entirely certain it's a good idea to remove all existing errors/notices when an `update_order_review` response has errors to display (see example).

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/tree/group-notices-11226

**Comment by franticpsyx** [comment]
@mikejolley Definitely an improvement over the current state. I think I'm OK with the removal of all notices on `failure`, since that prevents dupes - but I wouldn't hearing some more opinions on this - @jameskoster ?

As we discussed, an alternative option would be to leave any existing messages there on `failure`, and only add/remove any messages returned with `update_order_review` requests in a separate (top) group.

Alternative 1: http://cl.ly/1Q082S3U3G3A
Alternative 2: http://cl.ly/2H341g0L200c

I think I prefer (2) over (1) - Leave existing messages, even with the risk of showing dupes. Having 2 groups makes it clear to the user that the bottom group is messages added on page load, which will be staying there until the form is re-submitted.

**Comment by mikejolley** [comment]
I prefer 1 actually. You've already seen the submit notices.

**Comment by mikejolley** [comment]
jay agreed too, merged  :)
