### ISSUE TITLE
tabs.php template hasn't got its version updated

### ISSUE THREAD

**Issue by vmasto** [woothemes/woocommerce#11235]
## EXPLANATION OF THE ISSUE

The file `templates/single-product/tabs/tabs.php` hasn't got a version bump although it was changed here: https://github.com/woothemes/woocommerce/commit/c5c94b6bbd031491ef5145d3e0bc5e6a73c83980 adding the new class format

This is the second template we catch not being version updated (the first one was fixed in 2.6.1).

Is there some guideline as to when you're going to bump the version number in template files or should we just diff line by line any time WC releases a new version?

One would assume that the best practice of *any kind of change should be bumped* would be followed. Not just when breaking or subjectively major changes happen.

**Comment by mikejolley** [comment]
Tends to be breaking changes only to avoid panic. Lots of theme authors override ALL templates, even though they don't mod them. Which is bad practice.

**Comment by claudiosmweb** [comment]
No need for update the version, since you still have the old classes there.

**Comment by anastis** [comment]
Some new code (outside the templates) might reference those classes though on a later version, i.e. via JS. The problem is, the template will not get a version bump (since it wasn't a breaking change), although the JS code will reference them (breaking change for those that don't have the new classes) and of course, since it's a JS change, the templates will not be version bumped (unless you remember that you didn't do it in the first place).
Sure, it's a bit far fetched. However it's a possibility, a workflow bug if you will, that could have been avoided.
