### ISSUE TITLE
Free Shipping amount is based off of subtotal before coupons are applied

### ISSUE THREAD

**Issue by mikkamp** [woothemes/woocommerce#11232]
When using free shipping with a minimum order amount the calculation if this free shipping is applied is calculated *before* any coupons are applied. In WooCommerce < 2.6 this used to be applied *after* the coupon amount was applied.

I setup the following scenario for testing:

* Create discount coupon which reduces order by 10
* Setup free shipping with minimum order amount of 50
* Setup flat rate shipping at 10
* Add products to cart with total of 50
* Apply discount coupon which reduces order total to 40

In WooCommerce 2.5.5 this results in:

![WC 2.5.5](https://cloudup.com/cG9MMgT9lL6+)

With both WooCommerce 2.6.1 and the latest version from the repository this results in:

![WC 2.6.1](https://cloudup.com/cSZ9SmicGCF+)

**Comment by erickgarciadefreitas** [comment]
Hey mikkamp, could you tell me what you've used to enable Free Shipping based on subtotal? I'm in need of this exact solution, thanks!

**Comment by mikkamp** [comment]
That's included with the default Free Shipping and setting it to a minimum order amount:
https://docs.woocommerce.com/document/free-shipping/#section-1

Github is not intended for support questions, if you need help with WooCommerce I'd suggest to post your question here: https://wordpress.org/support/plugin/woocommerce

**Comment by lasselehtinen** [comment]
Seems like this bug is back on WooCommerce 3.1.2. I am having the exact same issue. Seems like the free shipping check is done from the subtotal before the coupon discount has been applied. I've created a free shipping rate with a minimum sub total of 50 €. Everything works as expected before I apply the coupon.

Free shipping not available:
![image](https://user-images.githubusercontent.com/1290186/30598833-871af5c4-9d63-11e7-8363-15bb7b9141e1.png)

Without coupon:
![image](https://user-images.githubusercontent.com/1290186/30598638-fab0f8fe-9d62-11e7-814d-f3cea2934e9e.png)

With coupon:
![image](https://user-images.githubusercontent.com/1290186/30598688-1b08578c-9d63-11e7-831b-3d397d5f9edc.png)

**Comment by JaapWeijland** [comment]
I'm having this issue as well. Please add an option to calculate discount after shipping or don't determine shipping before discount.

**Comment by mgason** [comment]
In different situations both applying coupon to shipping or or not is desirable. It would be great to have a simple option when creating coupons to say applies to shipping or does not.
For a 10% discount I may not want it to apply to shipping.
A flat $100 and I may want the user to be able to use it for shipping as it works like a gift cert
