### ISSUE TITLE
Multiple Shipping Method is not available for same country

### ISSUE THREAD

**Issue by jacksperrow1988** [woothemes/woocommerce#11248]
@mikejolley , @claudiosan 

I want to apply multiple shipping method on same country . For that I have created two zone with country 'India' and created two flat rate shipping method for that. but only one shipping method is enable.

Please see the video

http://www.screencast.com/t/NfBK2V2Rxb

Thanks

**Comment by theleemon** [comment]
You can add multiple shipping methods in a single shipping zone. No need to create two shipping zones with the same country,

**Comment by claudiosmweb** [comment]
I should not be answering, after all you wanted another Claudio response...
But you don't have two zones, you have only one. There is nothing differing from one another. That's why only one appears in the checkout.
Here the docs for you: https://docs.woothemes.com/document/setting-up-shipping-zones/
