### ISSUE TITLE
New WooCommerce > Templates > My Accounts > downloads.php conflicts with custom page template of same name

### ISSUE THREAD

**Issue by mklappen** [woothemes/woocommerce#11255]
## EXPLANATION OF THE ISSUE

I have had a custom page template for my site called "downloads-template.php" that is a child of another page. The page permalink format appears like this: [http://mysite.com/parent-page/downloads/](url)

When updating to 2.6.0 I have found that there is a new "downloads.php" in woocommerce > templates > myaccounts folder that appears to be conflicting. When I have 2.6.0 activated my "downloads" page is somehow redirected to pull in the content of its parent page. 

Rolling back to 2.5.5 or deactivating 2.6.0 and then re-saving permalinks fixes the issue and the content from my downloads-template.php shows up for my /downloads/ permalinks. 

## STEPS TO REPRODUCE THE ISSUE
-Update to WooCommerce 2.6.0
-Activated WooCOmmerce 2.6.0
-Have custom page template downloads-template.php in WP Theme. (in my case my downloads template pages all have parent pages)
-Navigate to the /downloads/ page - the downloads-template.php is not called, instead it routes to the parent page template/content. 

## SYSTEM STATUS REPORT

```

Name: Gauge Child
Version: 1.0
Author URL: http://www.ghostpool.com
Child Theme: ✔
Parent Theme Name: Gauge
Parent Theme Version: 6.10.1
Parent Theme Author URL: http://www.ghostpool.com
WooCommerce Support: ✔

### Templates ###

Overrides: gauge/woocommerce/single-product/price.php
`
```

**Comment by claudiosmweb** [comment]
Already fixed: https://github.com/woothemes/woocommerce/commit/67b2b26c8e703d258a4bfed82727f52e77e4d1f5

**Comment by 61pixels** [comment]
I don't believe this is fixed. I have been struggling for over 2 hours today with this issue, and narrowed it down to WooCommerce since when I deactivated it, things were fine.. I just found this on a whim from a google search and it is 100% my issue.. I have a page called Resources /resources/ and a sub page underneath it called Downloads /resources/downloads with a custom page template assigned /theme/page-templates/template-downloads.php and this is the exact problem I'm having. WooCommerce is overwriting my template and instead injecting it's own.. 

Pretty big issue in my opinion since I have a downloads page on many of my sites.
