### ISSUE TITLE
When calculating shipping methods, the tax is rounded up too early

### ISSUE THREAD

**Issue by natewoodbridge** [woothemes/woocommerce#11347]
## EXPLANATION OF THE ISSUE

I have found that shipping methods are rounded up too early, so the final shipping amount inclusive of VAT is £0.01 off either way depending on how I adjust the original value, because the value is rounded up twice by WooCommerce.

I have resolved the issue by adding an extra decimal point to abstract-wc-shipping-method.php:
https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L252
This ensures the value does not get rounded up before the tax is added.

Happening in latest version: 2.6.2.

## STEPS TO REPRODUCE THE ISSUE

1. If I enter £4.125 (exc tax), and have Standard UK Tax set for shipping (20%), I get £4.96.
2. If I reduce it to £4.12 (exc tax), I get £4.94.
3. I want to get £4.95.

**Comment by mikejolley** [comment]
This is a known issue we shouldn't solve by removing rounding, since this would create issues in other places as we've seen with prices excl. tax. e.g. passing the prices to a gateway and having the totals mismatch

This needs to wait for https://trello.com/c/cjHijcxy/19-shipping-inc-tax-prices-4425 to have proper support for tax inclusive based pricing.

**Comment by robskup** [comment]
Hi, I have exactly the same problem with the website I'm working on. I can't get the shipping price with tax to be £4.95. Has there been a solution for this?
Cheers, Rob
