### ISSUE TITLE
Case Sensitive coupons are not working

### ISSUE THREAD

**Issue by chandra-patel** [woothemes/woocommerce#11357]
## EXPLANATION OF THE ISSUE

I created two coupons with same name but they are case sensitive. For example, `lifepics` and `LIFEPICS`.

When I applied coupon `lifepics` then `LIFEPICS` coupon always applied because this coupon first created. 

I found problem with SQL query in this function `get_coupon_id_from_code()` in `WC_Coupon` class.

Both coupon should work independently.

**Comment by MattyLB** [comment]
To my knowledge, coupon codes are not case sensitive. They never have been for me in the past, anyway. The problem I do see here is that you should not be allowed to create another coupon with the same "code" - no matter what case is used.

This should also be checked against inactive coupons with the same "code" - because a warning that the code already exists with options to manage the existing code or create a new one would be the best solution - in my humble opinion.

**Comment by claudiosmweb** [comment]
As @MattyLB said:

> coupon codes are not case sensitive

It's not a problem, this not should never case sensitive.

**Comment by chandra-patel** [comment]
Thanks @MattyLB. I got your point.
