### ISSUE TITLE
Create customer on the fly

### ISSUE THREAD

**Issue by bizzthemes** [woothemes/woocommerce#11510]
## EXPLANATION OF THE ISSUE

Adding order manually in admin currently requires you to create customer/user account before you even attempt to create an order for a customer. This should be a core functionality.

**Comment by mikejolley** [comment]
There is no requirement to create a customer. Orders can be submitted for 'guests' which may be desirable for some users (so this shouldn't be forced).

**Comment by bizzthemes** [comment]
I'm aware of the 'Guest' option, no issues there, great. But if you want to create an order for a customer (with name, email, ...), it's not possible without creating a customer/user account first. I wasn't implying it should be forced, it would be great if you could create an account inside the order screen. Similar to what [this plugin](https://codecanyon.net/item/create-customer-on-order-for-woocommerce/6395319) does.

**Comment by mikejolley** [comment]
cc @jameskoster maybe one for s9n

**Comment by bizzthemes** [comment]
As a quick fix, when you search for a customer and there isn't one in the DB, you'd get a result with a link to 'user-new.php' page, like: 'No customers found, [create one](#)?'.

**Comment by jameskoster** [comment]
cc @tiagonoronha

**Comment by bizzthemes** [comment]
Closed? Or at least [this fix](https://github.com/woothemes/woocommerce/issues/11510#issuecomment-234518386)?

**Comment by mikejolley** [comment]
Seems pointless, add new user screen is also one click away... Best to do it properly.

**Comment by bizzthemes** [comment]
If there was a dedicated place for WooCommerce customers, it would be pointless, but customers are inside Users page and it's not immediately clear to a novice WC or WP user how to create one, when creating order manually. Right now, my customers create manual orders by going through the front-end checkout process as regular users do, just to avoid messing with admin headaches. Not sure what's wrong with this simple fix that got a "thumbs up": 
> As a quick fix, when you search for a customer and there isn't one in the DB, you'd get a result with a link to 'user-new.php' page, like: 'No customers found, create one?'.
Unfortunately, going nowhere here, I rest my case.

**Comment by mikejolley** [comment]
I see no thumbs up for that request. 

I get your point, and I've said we can build that properly into the UI in the future. A link is a lazy solution and like I said, if the user knows users == customers, the link is 1 click away in the sidebar.

**Comment by bizzthemes** [comment]
Was refering to the conversation above: [https://github.com/woothemes/woocommerce/issues/11510#issuecomment-234524073](https://github.com/woothemes/woocommerce/issues/11510#issuecomment-234524073)

**Comment by mikejolley** [comment]
Yeah, I think thats a thumbs up to doing it in s9n :) Thats are new UI project (not yet released details on this).

**Comment by bizzthemes** [comment]
I suppose that's 3.0, looking forward to it.

**Comment by johannesmutter** [comment]
**Currently it's three steps instead of one eg for a phone order:**
1. Create guest order. Remember order ID
2. Create customer/ user (with too many input fields in the way, obstructing the registration process/ only those defined on front end checkout should appear)
3.  Assign customer to order (manually send order receipt, etc.)

For manual orders (phone/ instant messaging) customers will first tell staff what they want and then tell their details. So the current sequence is complicated and requires too many steps (switching between pages takes too long in such a mission critical situation, which becomes especially stressful with impatient customers). 

**A solution** I could imagine would involve a "_create customer button/ icon_" next to the customer select input. Also when searching for a customer that doesn't exist yet, the already entered name or email address could be auto filled into a popup that opens ones the create customer icon or the "no results"-message in search get's clicked. 

Would be great if you could consider this for future releases. Thanks!

**Comment by marcomarsala** [comment]
JUst want to point out there is a plugin on CodeCanyon doing that
