### ISSUE TITLE
Changing the version of product transients doesn't invalidate the cached prices of a variable product

### ISSUE THREAD

**Issue by daigo75** [woothemes/woocommerce#11520]
Some time ago, I was looking for a solution to clear all product transients in one go (or, at least, all price transients). At the time, the discussed solution was to use `WC_Cache_Helper::get_transient_version( 'product', true )`, so that the transient version would change and new transients would be generated and used. This seemed to work, but I spotted an issue related to variable products: transient **wc_var_prices_** is not affected by that call, and it returns previous (and incorrect) values. 

Based on my analysis, the issue is that the transient hash doesn't take into account the version. 

**Example**
1. Hash for `wc_var_prices_` is generated, e.g. ABCDE.
2. Current version of product cache is **123**. 
2. Transient is loaded as `get_transient('ABCDE')` (original content).
3. The prices array of variable product X is populated as
`$prices_array['version'] = 123;`
`$prices_array['ABCDE'] = get_transient('ABCDE');`
4. Cache is invalidated with `WC_Cache_Helper::get_transient_version( 'product', true )`.
5. Hash for `wc_var_prices_` is generated, again, as **ABCDE** (exactly as in point 1).
6. Current version of product cache is **456**. 
7. Transient is loaded as `get_transient('ABCDE')` (again the original content, the version is not affecting this).
8. The prices array of variable product X is populated as
`$prices_array['version'] = 456; // New version, correct`
`$prices_array['ABCDE'] = get_transient('ABCDE'); // Old content, incorrect`

In this scenario, ABCDE is the transient that should be used with product cache version 123. When the version changes, that transient should be discarded, and replaced with an updated one. 

The issue doesn't occur if a product is saved from the Edit Product page, because a product's transients are explicitly deleted when that happens (therefore, the version becomes irrelevant at that stage, as the transients are generated from scratch). However, a "phisically delete all transients for all products" operation would not be possible, as it would be too heavy, and we need to rely on the version to invalidate the old transient.

Proposed solution
--
In `WC_Product_Variable::get_variation_prices()`, add the transient version to the prices hash. That is:
~~~
// Add transient version to prices hash. When the version changes, the hash
// will change as it should
$price_hash[] = WC_Cache_Helper::get_transient_version( 'product' );
$price_hash = md5( json_encode( apply_filters( 'woocommerce_get_variation_prices_hash', $price_hash, $this, $display ) ) );
~~~

**Comment by mikejolley** [comment]
This one is tricky because we need to balance transient count and size here. Your proposal technically would work, however, the size of that transient would grow every time you cleared the cache. Eventually it would lead to performance issues until deleted.

I'll add this change, but for 2.7 so it can be tested further.

**Comment by javorszky** [comment]
I've run into this problem. What I find weird is this bit:

```
// If the product version has changed, reset cache
if ( empty( $prices_array['version'] ) || $prices_array['version'] !== WC_Cache_Helper::get_transient_version( 'product' ) ) {
	$this->prices_array = array( 'version' => WC_Cache_Helper::get_transient_version( 'product' ) );
}
```

We're comparing the version on the prices array which comes from the transient, and we're putting the version information on the property, which is never saved to the transient, so that comparison is guaranteed to fail if code execution comes here.

I wonder if `$this->prices_array` is supposed to be `$prices_array`. That way the prices for that hash (not dependent yet on the version) would also include the version they belong to; that `if` statement could actually work, and if a new version were found, the prices would be thrown away, the version would be updated, and the new prices would be calculated, and they'd all go through the filters.

That would also solve the issue of the ever-growing soft cache price transient problem.

@mikejolley what was the reason that was `$this->prices_array`, but the rest were changed to local variable `$prices_array`?

**Comment by franticpsyx** [comment]
>@mikejolley what was the reason that was $this->prices_array, but the rest were changed to local variable $prices_array?

@javorszky https://github.com/woothemes/woocommerce/pull/10984

**Comment by javorszky** [comment]
Hm, right, that doesn't answer the other question I had.

I've copied some of the current code with unnecessary things omitted. The question I have is with cache invalidation with the product version. Steps below code.

```
if ( empty( $this->prices_array[ $price_hash ] ) ) {

	// Get value of transient
	$prices_array = array_filter( (array) json_decode( strval( get_transient( $transient_name ) ), true ) );

	// If the product version has changed, reset cache
	if ( empty( $prices_array['version'] ) || $prices_array['version'] !== WC_Cache_Helper::get_transient_version( 'product' ) ) {
		$this->prices_array = array( 'version' => WC_Cache_Helper::get_transient_version( 'product' ) );
	}

	// If the prices are not stored for this hash, generate them
	if ( empty( $prices_array[ $price_hash ] ) ) {
		// get stuff
		set_transient( $transient_name, json_encode( $prices_array ), DAY_IN_SECONDS * 30 );
	}

	$this->prices_array[ $price_hash ] = apply_filters( 'woocommerce_variation_prices', $prices_array[ $price_hash ], $this, $display );	
}
```

1. we're checking whether we already have the prices in the property. Let's assume we don't
2. we're fetching the stored prices from the transient, and storing it in a local variable `$prices_array`. Because of what happens later in `set_transient`, `$prices_array` does NOT have a `version` key / value.
3. we're checking the existence / value of the `version` in the local variable `$prices_array`. Because of 2., it is guaranteed to fail
4. because of this, we're fetching the current product version, and storing it on the `$this->prices_array` property, but NOT the local variable `$prices_array`. This also overwrites anything in `$this->prices_array`, though because we've checked whether it's empty, there's nothing to overwrite on the property. The local variable `$prices_array` still has the fetched price array though, unchanged by the version.
5. we then check the local variable `$prices_array` whether the price hash key is empty. Because we haven't done anything to clear the local variable, it will not be empty, unless the transient didn't have anything about it in the first place. For the sake of argument let's suppose there are no prices here
6. Then it's fetching the actual prices, and stores them in the local variable `$prices_array`, and then that gets saved to the transient. Note that `version` is not on the variable, so that will NOT be saved alongside the array, which causes the check in 2. to be unnecessary

## What I think should happen

In step 4 above the version should be fetched to local variable `$prices_array`. That way it would be saved into the transient in step 6, and the comparison with the current version vs stored version in step 3 would actually make sense. Then later in step 4 if the version changed, the assignment would immediately clear any `price_hash` keys on the `$prices_array`, forcing the rest of the method to re-fetch new, and updated prices.

On top of that, `$this->prices_array['version']` isn't even used anywhere else in that method, and is definitely not being returned to the caller.

It looks like it's an oversight / typo / error, but I want to double check whether I'm missing something.
