### ISSUE TITLE
Products/Posts Permalinks Issue

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#11570]
A certain product permalink structure is interferring with post permalinks: https://wordpress.org/support/topic/woocommerce-custom-product-permalinks-break-post-permalinks

To replicate, set `/%product_cat%` as the product permalink base: http://cld.wthms.co/1aO1x/41zawP4E, and `/%postname%/` as the post base: http://cld.wthms.co/1jLpR/1XmSq8wo

Viewing a product will work, but then posts will 404. Switch the products permalink back to something else, and all is good.

(Update, after doing the above, the default product permalink structure won't work at all.)

**Comment by mikejolley** [comment]
Not a supported structure due to conflicts. There is supposed to be logic in place to prevent this being set, but that was broken. Fixed the replacement.

**Comment by jibranb** [comment]
Hi @mikejolley (or anyone): I'm a little late to the party, but what do you mean by "Fixed the replacement"?

I ask because I am able to save`/%product_cat%/product-line/` as a `Custom base` and it doesn't get replaced. And it 404s all my pages (I have no posts). Is this expected behavior?

Running latest: WC 3.1.0 and WP 4.8. Thanks.

<img width="708" alt="screenshot 2017-07-03 22 24 03" src="https://user-images.githubusercontent.com/3483543/27816124-689b1780-603e-11e7-8c70-23689d52d1d1.png">
