### ISSUE TITLE
WooCommerce and AdBlocker interference

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#11580]
https://twitter.com/modemlooper/status/743806334051594243

It looks like AdBlocker and WooCommerce are interfering with one another - seems to be based on JavaScript files with "cookie" in the filename. Looks like `jquery.cookie.js` is the only affected file I can see in our codebase.

@mikejolley

**Comment by mikejolley** [comment]
This is a similar issue to https://docs.woocommerce.com/document/jquery-cookie-fails-to-load/ and the only solution would be to rename the scripts which tbh is a bad workaround since this will; be highly dependent on the environment, other scripts, and the adblock script itself. Clearly its a false positive.

Worth noting, admin doesn't use cookie.js but frontend does. So this may have been a combination of plugins anyway.

Also, I installed https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom/related and this didn't affect cart nor block our cookie.js.

No action should be needed.
