### ISSUE TITLE
Free shipping does not allow to choose shipping method

### ISSUE THREAD

**Issue by bhouszka** [woothemes/woocommerce#11600]
## EXPLANATION OF THE ISSUE

I offer 2 totally different shipping methods. I also offer free shipping when cart value is over $50, When a user has cart value over $50 he sees only one shipping method "Free delivery" and user cannot choose which shipping method of the 2 I offer user wants.

The desired solution would be that when user has cart value over $50 he or she sees the two shipping methods I offer both priced "$0" or "Free", so user can choose whichever shipping method he or she wants.

**Comment by mikejolley** [comment]
> I offer 2 totally different shipping methods. I also offer free shipping when cart value is over $50, When a user has cart value over $50 he sees only one shipping method "Free delivery" and user cannot choose which shipping method of the 2 I offer user wants.

Users can choose whatever methods are available in the zone. If it's missing, [you may be using a snippet](https://docs.woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/).

**Comment by lasselehtinen** [comment]
I have the similar issue and the snippet does not really help. So let's assume I have these two shipping methods:

1. UPS (6€)
2. DHL (4€)

What I would like to happen when the "Free shipping" criteria is met, that user could still choose from these existing shipping methods, which would now have a price of 0€. And additionally, the "Free shipping" option should be actually hidden, since the user has to choose from these two. Is this doable?
