### ISSUE TITLE
Add reply-to to admin emails

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#11630]
To email the customer back.

**Comment by nishitlangaliya** [comment]
Hello Team,

I have fixes Add reply-to to admin emails issue. Kindly check pull request for the same.

https://github.com/woothemes/woocommerce/pull/11698

Thanks,

**Comment by nishitlangaliya** [comment]
@mikejolley ,

Hi Mike I have clone of woocommerce which has  version 2.5.0-dev. Now I want to take latest updated clone which has version 2.7.0-dev how can I do that would you please guide me so that I can contribute to latest development branch.

Thanks,

**Comment by nishitlangaliya** [comment]
Hello Team,

I have fixes Add reply-to to admin emails issue. Kindly check pull request for the same.

https://github.com/woothemes/woocommerce/pull/11723/commits/7505f16893100ada31e20d12593d424f0bb3c790

Thanks,

**Comment by nishitlangaliya** [comment]
Hello @mikejolley , @claudiosmweb,

Sorry for inconvenience, Actually, I am very excited to more contribute in WooCommerce. But I am facing below two issues. 

1) I can't get latest woocommerce repository while fork woocommerce. I have clone of woocommerce which has version 2.5.0-dev. Now I want to take latest updated clone which has version 2.7.0-dev how can I do that would you please guide me so that I can contribute to latest development branch.

2) When I do pull request then my old file change will also come along with new request so I can't able to do pull request. Please find attached screen shot for the same. Please guide me so I can do more contribute.

Thanks,
![pull-request](https://cloud.githubusercontent.com/assets/11435772/17849825/32bf8114-6878-11e6-8adf-00f23b6643bb.png)

**Comment by claudiosmweb** [comment]
@nishitlangaliya just keep your fork synced and create new branchs when submit Pull Request, check this: https://help.github.com/articles/syncing-a-fork/

**Comment by nishitlangaliya** [comment]
Hello @claudiosmweb ,

Thank you for your help. I have fixes Add reply-to to admin emails issue. Kindly check pull request for the same.

https://github.com/woothemes/woocommerce/pull/11750

Thanks,
