### ISSUE TITLE
Shipping is showing on checkout page before an address has been entered

### ISSUE THREAD

**Issue by mrbm** [woothemes/woocommerce#11650]
## EXPLANATION OF THE ISSUE

Storefront theme, Mystile, Wordpress Multi-site, Woo-commerce Version 2.6.4, stripe gateway Version 3.0.2, 
Using table rate flat shipping per area.

Have 3 zones: 48 stats continental, usa non 48 states, and anything else

Customer ads item to cart and goes to check out. The shipping information should not show up until and address state country has been entered. However it is showing 1 shipping costs, in my scenario it shows the anything else category. 

## STEPS TO REPRODUCE THE ISSUE

Woo commerce shipping settings:

3 Zones with 3 different prices

Shipping options: 
Hide shipping costs until an address is entered, Default to customer shipping address

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.mappeddomain.com
Site URL: http://networkname.com/subblog
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: ❌ 5.5.9-1ubuntu4.14 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 18 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 2.12.0
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4
Domain Mapping: by WPMU DEV – 4.4.2.3
Admin Footer Text: by S H Mohanjith (Incsub)
Andrew Billits (Incsub) – 1.0.9

Admin Help Content: by Andrew Billits
Ulrich Sossou (Incsub)
Ve Bailovity (Incsub) – 2.0.1

Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.2
Contact Form 7: by Takayuki Miyoshi – 4.5
Custom Content Dashboard Widget: by S H Mohanjith (Incsub)
Andrew Billits (Incsub) – 1.6.3.1

Default Theme: by WPMU DEV – 1.0.4
Easy Blogging: by WPMU DEV – 3.3.4
Easy Google Fonts: by Titanium Themes – 1.4.1
FitVids for WordPress: by  – 2.1
Footer Content: by S H Mohanjith (Incsub)
Andrew Billits (Incsub) – 1.0.2.5

GearFoundation Quotas: by Ben M – v 1.0
MailChimp Multi Newsletter Signup: by MailChimp – 0.1
MailChimp Sync: by WPMU DEV – 1.8.1
Multisite Theme Manager: by WPMU DEV – 1.1.3
New Blog Templates: by WPMU DEV – 2.8.2
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove Email Verification: by WPMU DEV – 2.4.1
Set Password on Multisite Blog Creation: by WPMU DEV – 1.1.2.3
Signup TOS: by WPMU DEV – 1.4
Simple Custom CSS: by John Regan
Danny Van Kooten – 3.3

Snapshot: by WPMU DEV – 2.5.0.1
Soliloquy: by Thomas Griffin – 2.3.9.6
Support System: by WPMU DEV – 2.1.9.1
Toggle wpautop: by Linchpin – 1.2.2
Ultimate Branding: by WPMU DEV – 1.8.2
Video Thumbnails: by Sutherland Boswell – 2.12.1
WooThemes Helper: by WooThemes – 1.6.2
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WP Offload S3 Lite: by Delicious Brains – 1.0.4
Amazon Web Services: by Delicious Brains – 0.3.6
Pro Sites: by WPMU DEV – 3.5.5-beta1
GearFoundation Upfront Fancy Gallery Compatibility and Customize Menu fixes: by Ben M – v 1.0
WPMU DEV Dashboard: by WPMU DEV – 4.1.1
WP Smush Pro: by WPMU DEV – 2.4.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1463 - /shop/
Cart: #1464 - /cart/
Checkout: #1465 - http://networkname.com/subblog/checkout/
My Account: #1466 - http://networkname.com/subblog/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Mystile
Version: 1.3.12 – 1.3.13 is available
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Option: "Hide shipping costs until an address is entered" needs to be on.

This won't affect a logged in user or if you've already been to the cart/checkout page. At that point you have an address (it may not be a full address, but you have a country/state).

To test you need a new session in a new browser. Shipping will be hidden until you start adding details to the checkout or use the calculator. Tested and working.

**Comment by mrbm** [comment]
> Option: "Hide shipping costs until an address is entered" needs to be on.

I definitely have this option on.

Did a new session/cookie get added to the mix for woo-commerce that would some how effect this setting in more recent updates? I was doing some "tricks" for https and domain mapping to carry the cart from one domain to another https domain for check out.

Thanks Mike for all your work!

**Comment by mikejolley** [comment]
Don't think so, but the criteria for having an address changed.

**Comment by mrbm** [comment]
I'm going to send you a private message so you can see the issue happening in real life

**Comment by jas8522** [comment]
We're seeing this issue too. I think either the "Hide shipping costs until an address is entered" option needs to be clarified, or the behaviour should change.

I've got "Hide shipping costs until an address is entered" checked just like mrbm. This works perfectly until you've also got multiple countries configured as shipping zones. In this particular configuration previously there was *only* inner-US shipping options enabled (ie: for the one country). With this configuration, the "Hide shipping costs until an address is entered" setting worked perfectly -- no shipping costs were shown until after a state was selected.

After adding a new "International" shipping zone, the geographical 'level' at which shipping costs are calculated / shown changes from the state (and/or zip) to the country, which is one of the first parameters to be selected during an order.

This means that, despite having the hide shipping rates option checked, immediately after selecting a country (without having entered any other address information), WooCommerce shows me the international shipping rate. This happens even if I select United States as the country, which isn't part of the International rate -- it's configured as "Rest of the World".

I think that one of a few things should change to make this more clear:

1. "Hide shipping costs until an address is entered" could be renamed to "Hide shipping costs until a shipping zone match is found"

Note that this is a complicated solution because for that to be accurate, selecting "United States" should *not* show "Rest of the World" shipping zone options...

2. Even if the shipping zones are configured at the Country level, it might be better to simply continue to hide the shipping rates (when that option is enabled) until a full address is entered. This is what that option sounds like it should mean.

3. There could, of course, be both options:

a) "Hide shipping costs until a shipping zone match is found"
b) "Hide shipping costs until a complete address is entered"

Thanks for any consideration that goes into managing this setting / process in a more clear manner!

-Jordan

**Comment by claudiosanches** [comment]
@jas8522 the checkout process is already being reformulated and should change in the next versions. https://github.com/woocommerce/woocommerce/issues/10672
