### ISSUE TITLE
FEATURE REQUEST: Trash for categories

### ISSUE THREAD

**Issue by WarButter** [woothemes/woocommerce#11726]
## EXPLANATION OF THE FEATURE REQUEST

 

(using W.C. version 2.6.4)
### Feature request
One of our admin users accidentally deleted some important product categories, only to find out that there is no 'trash' (like posts and pages have a trash category where you can restore removed items).

## STEPS TO REPRODUCE THE ISSUE

1. Create a product category.
2. Delete the product category we created in **step 1**.
3. Undo **step 2**.

## SYSTEM STATUS REPORT

```
N/A
```

**Comment by claudiosmweb** [comment]
Not even WordPress categories uses "Trash", since categories don't have status...
So this make difficult.
If you want, you can submit a Pull Request with this feature, making work and removing categories from products when is only in Trash and hiding categories archives too.
But I don't see this happening.
