### ISSUE TITLE
"Select All" checkbox header is missing from "Orders" admin panel page

### ISSUE THREAD

**Issue by raspberrysmile** [woothemes/woocommerce#11764]
Hi,
I'm currently using version 2.6.4. 
As mentioned in the subject, the "Select All" checkbox header is missing from the table, thus causing a layout shift. Upon inspecting element, I realise that there's a ".hidden" class added to the cell. Is there any setting I can use to show the checkbox?
Here's the generated HTML that I see on the "Orders" page of my woocommerce admin panel:
`<td id="cb" class="manage-column column-cb hidden check-column"><label class="screen-reader-text" for="cb-select-all-1">Select All</label><input id="cb-select-all-1" type="checkbox"></td>`

**Comment by mikejolley** [comment]
Check for extension conflicts; we don't hide this column since we use it for bulk edit.

This is mine working as intended https://dl.dropboxusercontent.com/s/2ccjnio3rpm2136/2016-08-25%20at%2010.59.png?dl=0

**Comment by Latoweb** [comment]
Hi, i have the same problem. I try to disable all the other plugin but doesn't work

**Comment by raspberrysmile** [comment]
Hi,
I've tried disabling all plugins except for woocommerce and the issue still persists.

**Comment by 0oWeZo0** [comment]
I Have the same issue with all other plugins disabled. even uninstalled woocommerce and re-installed woocommerce. 

Please help.

**Comment by 0oWeZo0** [comment]
I searched everywhere for a reason and came up with nothing. . . I decided I would rather remove the item checkbox (which then removes the hidden checkbox header and have my table align . . .  place this in functions.php :

/**
 * Remove multi checkbox column from WooCommerce order details page
 */

    add_filter('manage_edit-shop_order_columns', 'woo_add_shop_order_columns', 20);
    function woo_add_shop_order_columns( $existing_columns ) {
        global $woocommerce;

        if ( empty( $existing_columns ) && ! is_array( $existing_columns ) )
                $existing_columns = array();

       //remove column
        unset($existing_columns['cb']);

        return $existing_columns; 
    }

**Comment by MrBike** [comment]
**[SOLUTION - SOLVED IT]**
I created an account to share my solution with you. After searching for about five hours I found a solution.

**[TL;DR]**
1. Go into your database
2. Find wp_usermeta
3. Search in the meta_key column for "manageedit-shop_ordercolumnshidden". Check the user ID in the column left to it. If you're having problems with your admin account, the user ID will be 1. Otherwise you should look further for the right user ID with "manageedit-shop_ordercolumnshidden".
4. Click on the left on Edit and change it's value to `a:0:{}`
5. Reload your order dashboard and you're check-all checkbox should be there.

**Complete information**
I saw this line of code in one of the WooCommerce files on github. This helped me a bit further:

```
// If first time editing, disable columns by default.
		if ( false === get_user_option( 'manageedit-shop_ordercolumnshidden' ) ) {
			$user = wp_get_current_user();
			update_user_option( $user->ID, 'manageedit-shop_ordercolumnshidden', array( 0 => 'billing_address' ), true );
		}
```

Apparently it stores the columns which have to be hidden in "manageedit-shop_ordercolumnshidden" which can be found in your database under "wp_usermeta". Here is the meta information for each account stored. Look for "manageedit-shop_ordercolumnshidden" in the meta_key column. Find the right one (corresponding with the user ID you have issues with). Click on edit on the left an paste this: `a:0:{}`
That simply tells WooCommerce to display all columns, including the check-all checkbox. You're original value was probably something including this: `i:0;s:2:"cb"` which makes the cb (checkbox) hidden.

Please let me know if it worked.

**Comment by raspberrysmile** [comment]
Thanks @MrBike ! Really appreciate your help in solving this.

**Comment by stedjo** [comment]
There is actually one more way of submitting this value, without having to hack into database.

You can actually change the value of one the check boxes from screen options menu at top of the orders page. Just pick any random check box(to make it easier for yourself pick the one that is not checked already), run inspect on an element and change the value of the "value" attribute for that check box to "id" value of table column which wraps bulk action check box(the one that is hidden), in my case the id was "cb" so I've used that as a new value for the previously mentioned change. Once this is set just click on the check box you have altered(just like you would normally do in order to display any screen option).

That's it.
Hope this helps.

Please note that this solves the issue but it doesn't prevent the cause.

**Comment by phlegx** [comment]
I have the same problem with the latest WooCommerce version 3.0.5 and Wordpress 4.7.4.

**Comment by sergiopmigoya** [comment]
@stedjo , your a genius! Easy and usefull, thanks!

**Comment by vijaykumarim** [comment]
Thank you so much for the solution... I raised the issue several times on Github but no one able to solve this... But you did . Thanks again.

**Comment by daviddunnington** [comment]
Great solution thanks for posting this.... Nice easy fix that worked perfectly

**Comment by DwennK** [comment]
> **[SOLUTION - SOLVED IT]** I created an account to share my solution with you. After searching for about five hours I found a solution.
> 
> **[TL;DR]**
> 
> 1. Go into your database
> 2. Find wp_usermeta
> 3. Search in the meta_key column for "manageedit-shop_ordercolumnshidden". Check the user ID in the column left to it. If you're having problems with your admin account, the user ID will be 1. Otherwise you should look further for the right user ID with "manageedit-shop_ordercolumnshidden".
> 4. Click on the left on Edit and change it's value to `a:0:{}`
> 5. Reload your order dashboard and you're check-all checkbox should be there.
> 
> **Complete information** I saw this line of code in one of the WooCommerce files on github. This helped me a bit further:
> 
> ```
> // If first time editing, disable columns by default.
> 		if ( false === get_user_option( 'manageedit-shop_ordercolumnshidden' ) ) {
> 			$user = wp_get_current_user();
> 			update_user_option( $user->ID, 'manageedit-shop_ordercolumnshidden', array( 0 => 'billing_address' ), true );
> 		}
> ```
> 
> Apparently it stores the columns which have to be hidden in "manageedit-shop_ordercolumnshidden" which can be found in your database under "wp_usermeta". Here is the meta information for each account stored. Look for "manageedit-shop_ordercolumnshidden" in the meta_key column. Find the right one (corresponding with the user ID you have issues with). Click on edit on the left an paste this: `a:0:{}` That simply tells WooCommerce to display all columns, including the check-all checkbox. You're original value was probably something including this: `i:0;s:2:"cb"` which makes the cb (checkbox) hidden.
> 
> Please let me know if it worked.

Thank you, it worked. Only solution I found that worked, I searched for hours. You're my hero.
