### ISSUE TITLE
Product by Product variation order

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#11773]
## The problem

This is what I'm trying to achieve:

- I want to arrange the variations on **product A**: `Burnt Red`, `Dusty Yellow`, `Salmon Pink`, `Deep Blue`
- I want to arrange the variation on **product B**: `Dusty Yellow`, `Deep Blue`, `Night Black`, `Burnt Red`

Currently, The only method of ordering the attributes are to laboriously drag / drop. But this means all products are created equally in terms of variation order.

Is there a way ordering by variation order of the product? I saw there's a filter for the order, but thats ajax admin order, not front end.

**Comment by mikejolley** [comment]
For global attributes, no. The attributes are global; they have 1 sort order stored alongside their data. So when a product pulls in these attributes, it uses that same global order.

If you need per-product control you can use product-level text based attributes so each product has it's own set.

This is being looked at in the refactor for v3 UI anyhow. There will not be a workaround added in the meantime.

> Product by Product variation order

Just to mention, you're not ordering variations. You're ordering attributes. Variations are made up (or can be made up) of multiple attributes, which is why it's not simply a case of sorting variations in the backend.
