### ISSUE TITLE
Hight load taxonomi in wc-post-types.php

### ISSUE THREAD

**Issue by worteepz** [woothemes/woocommerce#11793]
class-wc-post-types.php
Начиная со строки 167

Вот тут файлик: https://github.com/worteepz/wooo/blob/master/class-wc-post-types.php
Вот тут тема, писал про проблему: https://wordpress.org/support/topic/problem-with-load-websait?replies=13#post-8791731

У нас 20.000 товаров, в каждом товаре по 25 атрибутов, около 500.000 атрибутов - woo грузит их всех из базы данных при переходе на каждую страницу. Идет большая нагрузка на cpu сервера при обработке запросов регистрации.

register_taxonomy( $name, apply_filters( "woocommerce_taxonomy_objects_{$name}", array( 'product' ) ), apply_filters( "woocommerce_taxonomy_args_{$name}", $taxonomy_data ) );

Самая тяжелая функция...

Помогите упростить, чтобы он вызывал лишь те атрибуты, которые нужны товаруу

```

class-wc-post-types.php
Starting with the line 167

Here I've found: https://github.com/worteepz/wooo/blob/master/class-wc-post-types.php
Here the theme, wrote about the problem: https://wordpress.org/support/topic/problem-with-load-websait?replies=13#post-8791731

We have 20,000 products in each product by 25 attributes, attributes about 500,000 - woo ship them all from the database when you go to each page. There is a big load on the server cpu in the processing of registration requests.

register_taxonomy ($ name, apply_filters ( "woocommerce_taxonomy_objects _ {$ name}", array ( 'product')), apply_filters ( "woocommerce_taxonomy_args _ {$ name}", $ taxonomy_data));

The worst feature ...

Help simplify that it calls only those attributes that are needed tovaruu
```

**Comment by mikejolley** [comment]
Attributes are taxonomies. We cannot determine where they "need" to be available... they can be used in widgets, for queries, backend (admin) etc and generally need to be registered on all pages.

Using https://codex.wordpress.org/Function_Reference/register_taxonomy does not however load all of the terms. It merely makes the taxonomy available for use.

Reading your thread, even if your taxonomy issue is related, it's not going to be the register part at fault, and removing it is not a viable option. Therefore this issue is invalid.

I suggest you look into what parts of your site/what specific queries are causing slowdown and act on them instead of the above which is not an option.
