### ISSUE TITLE
[Rest API] All the parameters such as filter, fields and meta of v3 not working in new rest api v1

### ISSUE THREAD

**Issue by fangj99** [woothemes/woocommerce#11953]
Hi there: we are using woocommerce rest api v3 a lot, now we try upgrade to 2.6, but new rest api 2.6's v1 missing a lot of "parameters" in v3,  such as **filter, fields, meta** which are all not working. 

**new 2.6's v1 with "fields=id" will return everything, not just id like 2.5's v3 did**
http://xxx.xxx.com/wp-json/wc/v1/products?fields=id  

**new 2.6's v1 with "filter[meta]=true" will not return the product_meta data**
http://xxx.xxx.com/wp-json/wc/v1/products/276?filter[meta]=true 

Just wonder if I am in the wrong way or these are not implemented in 2.6, if not implemented, then we can keep the 2.5 for a while.

Thanks a lot!

**Comment by claudiosmweb** [comment]
Yep, because are two different REST APIs. That's why.
You can check the docs on https://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by fangj99** [comment]
Hi claudiosmweb: So if I want to get product_meta, is there any way to do it in the new rest api v1?  In old version, I just need add "filter[meta]=true", in the new version's doc, I can not find anything about this.

thanks a lot!

thanks a lot!

**Comment by DrBGM** [comment]
@fangj99 : Did you find a solution for your answer ?

**Comment by fangj99** [comment]
I still using 2.5, will not upgrade to 2.6 until they fixed it or jump to other boat.

**Comment by mikejolley** [comment]
It's not something to fix, it's a different incarnation of the API.

**Comment by DrBGM** [comment]
Our workaround:

(1)

We managed to find out: since October 07, 2016: WordPress REST API (Version 2)

https://de.wordpress.org/plugins/rest-api/changelog/

2.0 Beta 15.0 (October 07, 2016)

**Introduce support for Post Meta, Term Meta, User Meta, and Comment Meta in their parent endpoints.**

For your meta fields to be exposed in the REST API, you need to register them. WordPress includes a register_meta() function which is not usually required to get/set fields, but is required for API support.

To register your field, simply call register_meta and set the show_in_rest flag to true. Note: register_meta must be called separately for each meta key.

**Introduce Settings endpoint.**

Expose options to the REST API with the register_setting() function, by passing $args = array( 'show_in_rest' => true ). Note: WordPress 4.7 is required. See changeset [38635][https://core.trac.wordpress.org/changeset/38635].

(2) Access Control Headers:
https://joshpress.net/access-control-headers-for-the-wordpress-rest-api/ 

to get : 

Access-Control-Allow-Methods:POST, GET, OPTIONS, PUT, DELETE
allow: GET, POST, PUT, PATCH

at least this helped us...

**Comment by fangj99** [comment]
Great, thanks, will try this out later. @DrBGM

**Comment by vajohn** [comment]
Hi I have been trying to filer on the new api but it returns everything whether its fields or just the filter
![untitled](https://user-images.githubusercontent.com/24270878/42756801-febba278-88fd-11e8-852e-1fc7fc89ffbf.png)
