### ISSUE TITLE
product filter in wp not work correctly

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#30449]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Hello
I had a problem with woocommerce filter products in dashboard and when search about it i was find it's a bug. please help me to solve this.
I have 5903 products in 296 pages, and in each page will be show 20 products.
![1](https://user-images.githubusercontent.com/55229689/128592007-254b80c1-30ea-4387-8207-4c06d2b6add3.jpg)

1- whene i open products link, all products show and it's true and even click on page by page and can view all products.

2- but when i click on filter a category, products not show complete! and pagination is gone!
![2](https://user-images.githubusercontent.com/55229689/128591996-128455fc-8aa1-4335-bbfc-5605c9ad7a54.jpg)

3- this problem also happen when i use custom number page! and again removed half all of products.
![3](https://user-images.githubusercontent.com/55229689/128592095-44210624-3de3-484a-a5ce-4fa904539bb3.jpg)

Thank you for your help

**Comment by juliaamosova** [comment]
Hi @saeedmodarresi,

Thank you for raising the issue. However, based on the little information you provided, I don't fully understand what the issue is and how to replicate it. I did a quick test using WooCommerce 5.5.2 and everything seems to be working as expected on my end - please see screencast below:

https://user-images.githubusercontent.com/19143190/129410452-f535bf57-06bb-4a0e-be55-135f35cc1c61.mov

Please provide us with the following information so that we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ghost** [comment]
Hi  @juliaamosova
thanks for your response. the typical page navigation is normal, but when i use a filter for products, this problem shown. it seems some of products not show in wp dashboard. please check this screencast:


https://user-images.githubusercontent.com/55229689/129575933-fc367df6-d1d8-4080-9f9f-2bfb53011d70.mp4




Steps:
1. Go to products
2. Select a number for product_per_page from page setting. (for example: 20).
2. Select a category filter.
3. Now navigate the pages.
4. Count of products that show in front of the each category is not match with count of products in all of the pages.
5. 
* I'm using wordpress v5.8 and woocommerce v5.7

**Comment by AashikP** [comment]
Hello @saeedmodarresi 

Thank you for getting back to us with the screencast. I can't replicate the behavior on my test site as well, though: https://d.pr/i/AhE0Lk

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
