### ISSUE TITLE
Use Paid  GeoIP2 Country Database instead of free version

### ISSUE THREAD

**Issue by ashhitch** [woothemes/woocommerce#30452]
I see in the class `WC_Integration_MaxMind_Database_Service` there is a filter to update the path to the file but the file name `GeoLite2-Country` is fixed is a const.

https://woocommerce.github.io/code-reference/files/woocommerce-includes-integrations-maxmind-geolocation-class-wc-integration-maxmind-database-service.html

**Describe the solution you'd like**
Would be great to add a filter to allow this to be updated so it will automatically download the paid version instead of the lite version.

**Comment by juliaamosova** [comment]
Hi @ashhitch,

Thank you for taking the time to share this idea, we really appreciate your help. 

It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
> I see in the class WC_Integration_MaxMind_Database_Service there is a filter to update the path to the file but the file name GeoLite2-Country is fixed is a const.

It sounds like you've already found the [`woocommerce_maxmind_geolocation_database_path`](https://github.com/woocommerce/woocommerce/blob/5.6.0/includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-database-service.php#L78) filter—which should be a suitable way of modifying the filename (which is after all just the final component of the path).

With that in mind we'll go ahead and close this issue, but if there is a reason that won't work for you do feel free to update this with more information.
