### ISSUE TITLE
Existing customers are not matching the default shipping zone

### ISSUE THREAD

**Issue by johannesvonniederhaeusern** [woothemes/woocommerce#30477]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
We encountered an issue in our shop after we updated from Woocommerce 5.2.3 to 5.5.1. Since we’ve skipped several versions during the update, so we've done the updates step by step on a development environment and noticed that the issue already occurs when updating from 5.2.3 to 5.3.1.

This is the issue: When an existing customer logs in and has no country/region stored in the account for his billing and shipping address, he does not see any shipping methods in the shopping cart and during checkout. This seems to be because he is not assigned to the default shipping zone.
Previously, customers who had not stored a country/region in der billing or shipping address were also assigned to the default shipping zone. Now this no longer seems to be the case.

This also becomes visible if we compare the results of the shipping debug mode of a customer who has no country/region set in his account:
- Woocommerce 5.2.3: Customer matched zone “Switzerland” (which is the default zone in our case).
- Woocommerce 5.3.1: Customer matched zone “Locations not covered by your other zones”.

I wonder if this change in behaviour is related to the following fix introduced in Woocommerce 5.3.0? [Fix #29605](https://github.com/woocommerce/woocommerce/pull/29605/commits/f0c164d2d49dfe13088bb0744f3a1c357c4a9204).

**Expected behavior**
A registered customer with a billing and a shipping address, but without a set country/region, still matches the default shipping zone (as he did in Woocommerce 5.2.3).

**Actual behavior**
A registered customer with a billing and a shipping address, but without a set country/region, does not match any shipping zone.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

1. Set up a shop running on Woocommerce 5.2.3
2. Set up the shipping options and shipping zones as seen in the screenshots below
3. Create a customer account, that has a billing and a shipping address, but both without setting a country/region
4. Login as the newly created customer and add a product to the cart.
5. Add a product and go to the cart page. There you see that the default shipping zone is selected
6. Update to Woocommerce 5.3.1 or higher
7. Repeat steps 3. & 4.
8. Add a product and go to the cart page. There you see, that the customer does not match any shipping zone. 

**Screenshots**
Shipping settings:
https://snipboard.io/vGjmBf.jpg
https://snipboard.io/j0ab7f.jpg
https://snipboard.io/yXo9zU.jpg

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woocommerce.diktum.website
Site address (URL): https://woocommerce.diktum.website
WC Version: 5.3.1
REST API Version: ✔ 5.3.1
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.22
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 200000
cURL Version: 7.76.1
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.1
WC Database Prefix: wp_
Total Database Size: 4.45MB
Database Data Size: 3.04MB
Database Index Size: 1.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.3.1 (update to version 5.5.2 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /warenkorb/
Checkout: #9 - /kasse/
My account: #10 - /mein-konto/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-08-09 12:12:13 +0200
Newest: 2021-08-09 12:12:13 +0200


### Status report information ###

Generated at: 2021-08-11 10:39:36 +02:00
`
```
</details>

**Comment by tammullen** [comment]
Hi @johannesvonniederhaeusern 

Thank you for taking the time to report this issue, we really appreciate your help. I can reproduce what you are seeing on my end. 

I set up a shop with the same settings as you used, selling and shipping only to the same country as the shop's base location, and Default customer location set to Shop base address
![Screenshot 2021-08-20 at 16 29 28](https://user-images.githubusercontent.com/24649833/130261651-c7a12440-943f-4f9d-82ef-94b7c15e68ba.png)
![Screenshot 2021-08-20 at 16 30 50](https://user-images.githubusercontent.com/24649833/130261657-595284d9-b2aa-418c-b945-a3cc6cfb619f.png)
![Screenshot 2021-08-20 at 16 57 30](https://user-images.githubusercontent.com/24649833/130261673-3705937f-3d8f-40f3-bcc8-a3a367aa2480.png)

I then created a customer account from WP Admin > Users, that has a billing and a shipping address, but both without setting a country/region. 
**Note: setting an address without setting a country/region can only be done manually from WP Admin > Users > Edit User as a customer registering on the shop itself will automatically have the country/region set with the shop settings you are using. Even with other shop location settings country/region would still be a required field so the customer would have to set a country/region when adding an address** 
![Screenshot 2021-08-20 at 16 57 07](https://user-images.githubusercontent.com/24649833/130262487-ae868fb6-4957-47c8-938f-25500ed285aa.png)

I then tried going to Cart with this customer in WooCommerce 5.2.3 and the customer matched the Switzerland zone
![Screenshot 2021-08-20 at 16 59 04](https://user-images.githubusercontent.com/24649833/130262942-53ca112d-6ef8-49b6-b1d3-80a7291589a4.png)

I then tried with WooCommerce 5.6.0 and the customer matched the zone "Locations not covered by your other zones" 
![Screenshot 2021-08-20 at 17 01 18](https://user-images.githubusercontent.com/24649833/130263387-0e123e3a-39a8-4409-bec2-f5815f5a458f.png)

I then tried as a guest customer in 5.2.3 and 5.6.0 and the guest customer matched the Switzerland zone
![Screenshot 2021-08-20 at 17 22 28](https://user-images.githubusercontent.com/24649833/130264132-e7bab985-47eb-4ca1-9f03-af65bd613f26.png)


I believe the guest customer behaviour is correct as it is matching for Switzerland which should happen as our `Default customer location` setting is set to Shop base address which is Switzerland.

So the question is if the existing customer account that has a billing and a shipping address, but both **without a country/region** should match against Switzerland zone or Locations not covered by your other zones. 
I believe matching Locations not covered by your other zones is the correct expected behaviour as by setting manually some of the address details for this customer but not the country/region we are essentially explicitly saying this customer should have no country/region not even a default so it makes sense they should match Locations not covered by your other zones. 

However I am adding the `needs developer feedback` label to this issue so that the Core team could take a look and give a second opinion on if this is expected behaviour or if it is a bug. 
​
Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for the report and discussion!

> I believe matching Locations not covered by your other zones is the correct expected behaviour as by setting manually some of the address details for this customer but not the country/region we are essentially explicitly saying this customer should have no country/region not even a default so it makes sense they should match Locations not covered by your other zones.

This was discussed today and we're in agreement—and, to that end, we'll close this issue.
