### ISSUE TITLE
Programmatically added weights has a strange behaviour.

### ISSUE THREAD

**Issue by ignitebhdeveloper** [woothemes/woocommerce#30476]
Programmatically added weights using the hook woocommerce_before_calculate_totals are no longer working.
The issue is not reproducible on versions below 5.1.
The issue is not reproducible when shipping debug mode is enabled, because it would go through [this](https://github.com/woocommerce/woocommerce/blob/63ff7c800e2f8002404bc282d9cf558799303b13/includes/class-wc-shipping.php#L335) check 

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

Steps to reproduce the bug:
1. Create a simple product with some price and publish it, please don't add any weight value in the shipping.
2. Apply the code mentioned below in your theme function.php 
3. Add product to cart and then go to the cart
4. Click on Calculate Shipping and the price will appear
5. Prodeed to check out and the shipping will show at random either [this](https://github.com/woocommerce/woocommerce/blob/63ff7c800e2f8002404bc282d9cf558799303b13/templates/cart/cart-shipping.php#L64) or [this](https://github.com/woocommerce/woocommerce/blob/63ff7c800e2f8002404bc282d9cf558799303b13/templates/cart/cart-shipping.php#L67) message

- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Snippet:

```
add_action( 'woocommerce_before_calculate_totals',
	function ( $cart ) {
		$pmo_user = wp_get_current_user();
		if ( is_admin() && ! defined( 'DOING_AJAX' ) )
			 return; 
		
		if ( did_action( 'woocommerce_before_calculate_totals' ) >= 2 )
			return; 

		foreach ( $cart->get_cart() as $cart_item ) {
			// Replace product ID with yours
			if ($cart_item['product_id'] == 8224) {
				$cart_item['data']->set_weight( 0.1 );
			}

		}
	}
, 10, 1 );
```

<details>

```
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) PHP/7.4.19
PHP Version: 7.4.19
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.77.0
(SecureTransport) OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.25
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Active Plugins (1) ###
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.31

### Theme ###

Name: Pro – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: Pro
Parent Theme Version: 4.3.3
Parent Theme Author URL: https://theme.co
WooCommerce Support: ✔

### Status report information ###
Generated at: 2021-08-11 09:42:54 +03:00
```

</details>

**Comment by juliaamosova** [comment]
Hi @ignitebhdeveloper,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
@ignitebhdeveloper—we may need some more detail in order to replicate this. Can you provide some specifics about your shipping rules and any shipping extensions you are using?

In my own testing, I add the snippet you provided (adjusting the product ID, of course) along with a simple product (weight: 0.1kg) and I use the [Table Rate Shipping](https://woocommerce.com/products/table-rate-shipping/) extension with a rule setup to charge $1/kg.

When I add the item to the cart, and then view the cart, I see that it has successfully charged $0.10 in shipping costs—as expected given the snippet sets the weight to 0.1kg. If I increase the quantity to two products, the costs become $0.20. This all seems expected and suggests the snippet you shared is valid. I'm not sure, however, why you are seeing different results (hence my interest in your current shipping setup).

Do let me know if you have any more feedback, but right now this seems more like a custom dev question than either a bug or feature request—and so we may be limited in terms of how much assistance we can provide.
