### ISSUE TITLE
Page translation to Finnish doesnt work properly

### ISSUE THREAD

**Issue by Jyrisal** [woothemes/woocommerce#30516]
**Describe the bug**

Part of the texts appear in English instead of Finnish

**Expected behavior**
I expected all the texts to appear in Finnish.

**Actual behavior**
Part of the texts appear in English.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Settings → General in your WordPress dashboard.
2. Find the Site Language drop-down.
3. Select the language into which you want to change your WooCommerce store.
4. Save your changes.
5. Install Loco Translate
6. Find words that are not translated into Finnish.
7. All the words appear in Finnish in Loco Translate

![woocommerce1](https://user-images.githubusercontent.com/89078739/129720109-781d2c6f-bc79-4663-bb49-986b088ce033.jpeg)
![woocommerce2](https://user-images.githubusercontent.com/89078739/129720115-090261a0-a626-4187-9c02-36a6ebc717c1.jpeg)
![woocommerce3](https://user-images.githubusercontent.com/89078739/129720143-7607ca23-e9b7-457e-b69c-cb84db451529.jpeg)

**Comment by tammullen** [comment]
Hi @Jyrisal 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Also note the Finnish language translation file is currently at time of writing at 83% translated strings https://translate.wordpress.org/locale/fi/default/wp-plugins/woocommerce/
This means as it is not a 100% translated you need to download it manually, see here for more details
https://docs.woocommerce.com/document/woocommerce-localization/#section-4
