### ISSUE TITLE
Documentation issue regarding currency symbols

### ISSUE THREAD

**Issue by shommey** [woothemes/woocommerce#30549]
**Issue:** Documentation on how to change currency symbol is not complete.

**Description:** Documentation [found here](https://docs.woocommerce.com/document/change-a-currency-symbol/ ) serves as an example on how to change currency symbol. In the given example dev doesn't have insight to all possible cases nor link towards that information is provided in the article. 

**Solution:** Add a link towards all possible cases for currencies or a code snippet which can be [found here](https://woocommerce.github.io/code-reference/files/woocommerce-includes-wc-core-functions.html#source-view.475)

**Comment by juliaamosova** [comment]
Hi @shommey,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Thanks for the suggestion, we added a document change request to the team, but it could take a while before they accept the request. Closing the issue for now.
