### ISSUE TITLE
Plugin Woocomerce é desinstalado e todos os produtos desaparecem quando tento atualizar para versão 5.6.0

### ISSUE THREAD

**Issue by glaucogfs** [woothemes/woocommerce#30554]
Tenho a versão do WordPress 5.8-pt_BR.
Quando tento atualizar a versão 5.5.1 instalada para a versão 5.6.0, entre em manutenção e depois simplesmente "desistala" o Woocomerce e todos os produtos.
Faço então o restore do meu Backup e volta ao normal, com a versão Woocomerce 5.5.1.
Grato,

**Comment by juliaamosova** [comment]
Hi @glaucogfs,

Thank you for submitting the issue!

Please note that we reply to bug reports in the English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

Title translation:

> Woocommerce plugin is uninstalled and all products disappear when I try to upgrade to version 5.6.0

Body of the issue translation:

> I have WordPress version 5.8-pt_BR.
When I try to update the installed version 5.5.1 to version 5.6.0, go into maintenance and then simply "uninstall" Woocomerce and all products.
I then restore my Backup and go back to normal, with Woocomerce 5.5.1 version.
Grateful,

Please provide us with more details about your issues so that we could try to replicate it. What hosting company do you use and what backup and restore method do you use on your site?
