### ISSUE TITLE
Discrepancies between two GH action workflows for building release zip files

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#30572]
![](https://d.pr/i/nokP74+)

During a release cycle, before the beta is release, a zip file GH action is manually triggered (Build release zip file). This is the one we link to the woo-core-releases channel.

When we cut a release on GH, there is a GH action that automatically runs (Build release asset). 

The problem is the end artifact created by each of these two actions do not match. One has more files than the other.

We need to investigate what is going on here.

**Comment by vedanshujain** [comment]
The first one is from automatic workflow, and the second one is from manually triggering the workflow.

This was discussed internally and the following flow was suggested:
1. Publish beta.1 on the day of code freeze itself on Github, no need to push this one to wordpress.org. Send the beta.1 package for testing.
2. If there are no issues, then push beta.1 on wordpress.org on tuesday.
3. If there are additional patches, publish a new beta.2 on Tuesday, push this patched version to wordpress.org instead of beta.1.

**Comment by peterfabian** [comment]
I don't see how @vedanshujain 's comment addresses the fact that there are 2 different packages bing created by our processes. Is there a reason they should differ? If it's all fine, can we close this issue?

**Comment by jonathansadowski** [comment]
Sorry, I forgot to link the RFC I created to address this issue in p7bje6-3sj-p2.

I think we can either close this issue, or put it on Atlas's plate, as we plan to recreate the release documentation and checklists as part of the 6.0 release, and we'd plan to tackle any difference that remains in that process.

**Comment by roykho** [comment]
I believe this is no longer relevant so closing. Feel free to re-open if that is not the case.
