### ISSUE TITLE
Output results from running e2e tests on external site to a comment on a PR

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#30615]
Once work on https://github.com/woocommerce/woocommerce/issues/30614 is completed, we want to look at how we can output the results into a comment on the PR.

**Comment by zhongruige** [comment]
This could be a good chance to revisit https://github.com/woocommerce/woocommerce/issues/29830 as a possible solution for this.

**Comment by MrJnrman** [comment]
While discussing this issue with @zhongruige, we started to wonder if the work is worth the value it adds. 

Since each push to a branch will have an associated build and results, how much value will it add if we post tests results as comments to the PR? 

Also, since we are the only ones with access to those sites (and by extension those workflow logs), it's not necessarily beneficial for anyone outside of our org that can't see the logs anyway.

I'd love to get some feedback before moving forward with this issue.

**Comment by zhongruige** [comment]
@rrennick [has a pull request](https://github.com/woocommerce/woocommerce/pull/31087) using the `run: smoke tests` label, so I'd be curious on if having the comment would have helped or if looking into the checks below was sufficient in watching the results.

**Comment by rrennick** [comment]
> so I'd be curious on if having the comment would have helped or if looking into the checks below was sufficient in watching the results.

I think this is the scenario we were thinking about where the comment would simplify confirming the smoke test. I don't see any value in doing this for the nightly tests since they aren't associated with a PR.
