### ISSUE TITLE
Rest API: on patch product attribute woocommerce resets properties to default

### ISSUE THREAD

**Issue by amustaine** [woothemes/woocommerce#30659]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
 - I set product attribute order_by as name_num via UI (admin)
 - I change an attribute name by REST API call `PATCH /wp-json/wc/v3/products/attributes/{attribute_id}`

**Expected behavior**
 - I should see a name_num ordering for the attribute as only name was changed

**Actual behavior**
 - I see in admin that attribute order_by was changed to default (menu_order)

Looks there is no way to patch attributes without resetting properties to defaults, isn't it?

Thank you :)

**Comment by tammullen** [comment]
Hi @amustaine ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
Hey, this is indeed a bug. We'll take a look at the linked pull request.
