### ISSUE TITLE
Bug in dashboard widgets

### ISSUE THREAD

**Issue by claudiosanches** [woothemes/woocommerce#30661]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A bug got introduced in https://github.com/woocommerce/woocommerce/pull/29149, by default dashboard widgets are only displayed now if WooCommerce Admin is disabled, but #29149 made WCA a requirement for those widgets, since it's now fetching data from WCA.

Reported by an user in https://wordpress.org/support/topic/warning-class-wc-admin-dashboard/#post-14851346

**Expected behavior**
No PHP errors in that widget, and make this widget functional, or maybe just remove it forever, since we don't plan to allow users to disable WCA anymore.

**Actual behavior**
A PHP error message is displayed, since no results is returned from `wp-json/wc-analytics/reports/revenue/stats` endpoint since WCA is disabled.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. In a fresh WooCommerce installation disable WCA.
2. Check the dashboard widgets.

**Comment by vedanshujain** [comment]
maybe related to #30347

**Comment by eason9487** [comment]
Tested with `add_filter( 'woocommerce_admin_disabled', '__return_true' );` and enabled/disabled WooCommerce Analytics feature, but found that this issue is no longer reproducible.

---

The only way I can get a similar PHP error is to:
1. Remove the `|| ! Features::is_enabled( 'analytics' )` condition from this line
   https://github.com/woocommerce/woocommerce/blob/9c58f198cfb7f1413bc83775fa2d9cc5bd5775fb/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php#L159
2. Disable **WooCommerce Analytics** in the *WooCommerce > Settings > Advanced > Features* page

![image](https://github.com/user-attachments/assets/4b83b3f8-ba9f-450f-b841-66eb31c872a8)

https://github.com/woocommerce/woocommerce/blob/9c58f198cfb7f1413bc83775fa2d9cc5bd5775fb/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php#L574

---

Closing this issue as it should have been fixed by #33816.
