### ISSUE TITLE
Write new API test: Orders > Can create an order

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#30670]

**Comment by rodelgc** [comment]
Hi @zhongruige. Just a heads-up that I'll be putting this, #30672, #30671, and the "Batch update order" tests in 1 PR because they're very closely related.

I'm planning to create a separate test file and data file for them, just like what we did in the [Products API: CRUD PR](https://app.zenhub.com/workspace/o/woocommerce/woocommerce/issues/31006).

I'm also thinking of waiting for [Jeff's PR](https://github.com/woocommerce/woocommerce/pull/31033) to be merged first before submitting a PR for this task, because there are some tests in his PR that I need to move over to here.

**Comment by zhongruige** [comment]
Thanks for the heads up @rodelgc!

> I'm planning to create a separate test file and data file for them, just like what we did in the Products API: CRUD PR.

> I'm also thinking of waiting for Jeff's PR to be merged first before submitting a PR for this task, because there are some tests in his PR that I need to move over to here.

That makes sense! I agree that it is worth waiting on to get Jeff's changes merged in.

**Comment by zhongruige** [comment]
Closed via https://github.com/woocommerce/woocommerce/pull/31052
