### ISSUE TITLE
Write new API test: Orders > Can search orders

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#30673]

**Comment by rodelgc** [comment]
Hi @zhongruige, I'm thinking of creating a separate test file for this one, like `order-search.test.js` instead of including it in the same file with create/retrieve/update/delete orders tests. As well as using `describe.each()` the same way we did in E2E.

It also seems that some search scenarios are already covered by [this PR](https://github.com/woocommerce/woocommerce/pull/31033). So I guess I'll be moving the search test there onto the PR here, and then expand it to include more search parameters.

**Comment by zhongruige** [comment]
Sounds good, I think that is a good approach to this @rodelgc!
