### ISSUE TITLE
Fallback for scrollTo not set correctly

### ISSUE THREAD

**Issue by shakethatweight-simon** [woothemes/woocommerce#30828]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Typo in element selector means fallback option will always fail.

**Expected behavior**
checkout.js/scroll_to_notices should fallback to `form.checkout` if no notices are found (according to the original commit for this change).

**Actual behavior**
the selector `.form.checkout` has been used instead of `form.checkout`, so scrollTo won't behave as originally expected.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I'm not sure exactly what situation would trigger this, it was originally added as a fallback incase there were no notices shown.

Commit: https://github.com/woocommerce/woocommerce/commit/aab1d688d1f96e8b55b7e83de2a8e4a0ed88f076 Line: 519

```js
scroll_to_notices: function() {
    var scrollElement           = $( '.woocommerce-NoticeGroup-updateOrderReview, .woocommerce-NoticeGroup-checkout' ),
        isSmoothScrollSupported = 'scrollBehavior' in document.documentElement.style;

    if ( ! scrollElement ) {
        scrollElement = $( '.form.checkout' ); // <--- this line
    }

    if ( scrollElement ) {
        if ( isSmoothScrollSupported ) {
            scrollElement[0].scrollIntoView({
                behavior: 'smooth',
            });
        } else {
            $( 'html, body' ).animate( {
                scrollTop: ( scrollElement.offset().top - 100 )
            }, 1000 );
        }
    }
}
```

**Comment by tammullen** [comment]
Hi @shakethatweight-simon 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the needs developer feedback label to this issue so that the Core team could take a look.

However to help them fully evaluate this issue can you please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site?

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

Please note it may take a few days for them to get to this issue. Thank you for your patience.
