### ISSUE TITLE
WooCommerce Update 5.6.0 recreates new Cart / Checkout / My Account Pages

### ISSUE THREAD

**Issue by BlutVampir** [woothemes/woocommerce#30821]
When installing 5.6.0 Update, the Plugin recreates pages for cart, checkout and my account, but they are there and correctly linked. Have this issue in all installations (6).
In the end, there are 2 pages for all the 3 things. Unformunatly, all the links get -2 at the end, as the URLs are already used.

Scripts or changes which hook to the URLs break (like special caching rules).

**Comment by pad52** [comment]
I confirm, is doing the same on my installation.

**Comment by tammullen** [comment]
Hi @BlutVampir ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/30532 and is fixed in 5.7.1. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
