### ISSUE TITLE
Problem importing product if category contains 'comma'

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#30827]
If in our CSV the product have category set to "Body Care > Perfume, Cologne & Fragrance > Unisex Perfume & Cologne"

Our final imported category will be set to: "& Fragrance > Unisex Perfume & Cologne"

**Comment by masteradhoc** [comment]
+1

**Comment by glaing** [comment]
I had this problem with our site's import. 

Turned out I just needed to add a backslash to escape the comma when I generated my CSV file and the importer handles it correctly.

I use a spreadsheet to generate my CSV, so I just added a SUBSTITUTE formula to the field that contains my category strings - it looks for `,` and replaces them with `\,`.

You need to be careful if you are trying to add the product to multiple categories as you will still need the commas without the escape slash to separate those strings.

Your final string would be:

`Body Care > Perfume\, Cologne & Fragrance > Unisex Perfume & Cologne`

**Comment by erikdemarco** [comment]
@glaing Nice find, the culprit is in this line:
https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php#L394

**Comment by swatipawarGS** [comment]
Hi @erikdemarco ,

Thank you for taking the time to report this bug, we really appreciate your help. I can't  reproduce it on my end using WooCommerce 5.9.0 version.

Here are the screenshots of the results :


Below are the screenshots documenting my experience :

 
![#30827(1)](https://user-images.githubusercontent.com/94531721/142637396-92c4054c-0004-4fce-a03b-bb9e20967aeb.jpg)



![#30827](https://user-images.githubusercontent.com/94531721/142637405-f7d046e2-66a0-499f-b7b9-e7ebcf701049.jpg)

**Comment by swatipawarGS** [comment]
Hi @erikdemarco ,


We retested this issue again and we are unable to reproduce this issue at our end using WooCommerce 5.9.0  version.


Please find below screenshots documenting for reference :

![#30827(1)](https://user-images.githubusercontent.com/94531721/143230820-a82e9595-3a9b-4729-9d09-b6d3f658c3d4.jpg)


![#30827](https://user-images.githubusercontent.com/94531721/143230827-ebd981bb-cb14-450c-a89d-67a601bd47dc.jpg)


Please provide us with more details and any additional steps required to repro this issue which may help us to evaluate it further.
