### ISSUE TITLE
Disable cart fragments AJAX request on first website visit to improve the performance

### ISSUE THREAD

**Issue by seriusokhatsky** [woothemes/woocommerce#30834]
Hello,

There is a "cart fragments" functionality in WooCommerce that makes AJAX requests when it is necessary to fetch the shopping cart widget and other fragments and update them on the frontend. And these AJAX always requests are always performed when you first visit the website even if the shopping cart is empty. And it is bad for performance so it would be great to avoid this request.

What could be done to avoid this in my opinion? There is a `cookie_hash` variable in `cart-fragments.js` and we prevent AJAX call when it is empty. Yes, the request is still needed since the frontend might be in cache and the shopping cart widget still should be updated with an empty one. We can create some JS function that will replace all cart fragments with empty placeholders (defined somehow via localizing script for example). 

![Code](https://i.gyazo.com/0076741c8d2f0fb72299083cc211dbef.png)

Let me know what do you think about it. I can develop this feature and create a pull request if my idea looks correct for you. 

Kind Regards

**Comment by tammullen** [comment]
Hi @seriusokhatsky ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @seriusokhatsky,

Thanks for flagging this.

> We can create some JS function that will replace all cart fragments with empty placeholders (defined somehow via localizing script for example).

That's a creative solution for sure, and I believe it would work in most cases. 

I do worry about backwards compatibility, though, because there may be merchants who depend on the existing behavior to tailor the empty cart template dynamically, based on various factors (date/time/geolocation/offer-of-the-day), which would not work with this approach since the default empty cart would itself have been cached.

I'm not suggesting that is common or even a good idea; only that it's an example of a way in which this change could introduce breakages.

Some options that come to mind:

- Implement your solution, but behind a toggle or feature flag (make it possible to opt in or out of this behavior).
- Add changes (new filters and/or events/triggers on the frontend) to make it easier to bring about the behavior you described as a customization.

What are your thoughts?

**Comment by jonathansadowski** [comment]
Not sure what happened with the labels here, but I'm closing this issue as stale. If we missed something, please comment again and we'll consider reopening it.
