### ISSUE TITLE
Investigate issue where E2E products created with @woocommerce/api are assigned uncategorized

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#30868]
While investigating another issue I noticed that all products created via the api in the E2E tests are only added to the default category regardless of the categories specified in the request.

**Comment by zhongruige** [comment]
Hi @rrennick!

Thanks for reporting this. I looked into this a bit (at least specifically in regards to the component `createSimpleProductWithCategory()`) and noticed the issue appears to be because we were adding the category by name--but instead we need to add it by ID. I opened the following PR, let me know if this helps address what you were seeing above:

https://github.com/woocommerce/woocommerce/pull/30988

Otherwise in the API package we will want to look into support for adding categories and getting the IDs.
