### ISSUE TITLE
Woocommerce 5.7.1 (PHP 8.0.10) login timeout           ....Since I upgraded to Woocommerce 5.7.1 I cannot access the Wordpress Dashboard untill the Woocommerce plugin exceeds the Maximum Execution Time of 120 seconds.   I have tried everything to fix it but nothing seems to work.   Everything was 100% prior to 5.7.1 ...All suggestions greatly appreciated.                                                                       

### ISSUE THREAD

**Issue by mhl4455** [woothemes/woocommerce#30904]
Please report issues for the following features directly to their respective repositories.

WooCommerce Admin: https://github.com/woocommerce/woocommerce-admin

WooCommerce Gutenberg Products Blocks: https://github.com/woocommerce/woocommerce-gutenberg-products-block

Action Scheduler: https://github.com/woocommerce/action-scheduler

WooCommerce REST API Docs: https://github.com/woocommerce/woocommerce-rest-api-docs

WooCommerce Code Reference: https://github.com/woocommerce/code-reference

**Comment by fat-potato** [comment]
Got same issue

**Comment by fat-potato** [comment]
Install this plugin to disable bloated features https://wordpress.org/plugins/disable-dashboard-for-woocommerce/

**Comment by juliaamosova** [comment]
Hi @mhl4455,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Are you able to isolate the issue to WooCommerce Core specifically?

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
