### ISSUE TITLE
Lack off href in word "Description"

### ISSUE THREAD

**Issue by pmatyjasik** [woothemes/woocommerce#30905]
In product i saw a problem. 
When we have enable reviews and description in product there is a bug with <a href=#tab-description>Description</a>.
When I'm on href #tab-reviews I can't click on whole world "Description", I have to click only on letter "D" to be 
transferred to href #tab-description.
![image](https://user-images.githubusercontent.com/73366069/136545221-d82dc7b8-7962-4a28-8bcf-3d47b2b1896d.png)

**Comment by kofimokome** [comment]
I'm using Woocommerce Version 5.9.0-dev and it works fine.
Looks like the issue is already addressed, and will be available in the next updates.

**Comment by juliaamosova** [comment]
Hi @pmatyjasik,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
