### ISSUE TITLE
Error in transient

### ISSUE THREAD

**Issue by k33n8nc** [woothemes/woocommerce#30914]
Update WooCommerce plugin to 5.7.1

Go to /wp-admin/plugins.php

Fatal error: Uncaught Error: Attempt to assign property "translations" on null

Line 81 in includes/admin/helper/class-wc-helper-updater.php
$transient->translations = array_merge( isset( $transient->translations ) ? $transient->translations : array(), $translations );

See screenshot attached

<img width="739" alt="Schermafbeelding 2021-10-10 om 01 41 20" src="https://user-images.githubusercontent.com/38896281/136676503-8bcf663d-2d5e-4a27-8f6f-edf867026f8f.png">

When i remove this line, the error is gone

Wordpress 5.8.1
MySQL 8.0.16
PHP Version 8.0.0
Webserver Apache

Kindly Robbert

**Comment by juliaamosova** [comment]
Hi @Baggio89,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Are you able to isolate this to just WooCommerce Core?

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by NachoGalardo** [comment]
> Update WooCommerce plugin to 5.7.1
> 
> Go to /wp-admin/plugins.php
> 
> Fatal error: Uncaught Error: Attempt to assign property "translations" on null
> 
> Line 81 in includes/admin/helper/class-wc-helper-updater.php $transient->translations = array_merge( isset( $transient->translations ) ? $transient->translations : array(), $translations );
> 
> See screenshot attached
> 
> <img alt="Schermafbeelding 2021-10-10 om 01 41 20" width="739" src="https://user-images.githubusercontent.com/38896281/136676503-8bcf663d-2d5e-4a27-8f6f-edf867026f8f.png">
> 
> When i remove this line, the error is gone
> 
> Wordpress 5.8.1 MySQL 8.0.16 PHP Version 8.0.0 Webserver Apache
> 
> Kindly Robbert

Hi Kindly, i m having this problem now and i proceed to do this. Do you think that make it, pobably create another error? I do it and i think the issue is fix it. Tell me about your experience doing it.

Thank you
