### ISSUE TITLE
WC Rest API bug

### ISSUE THREAD

**Issue by mmilosheski** [woothemes/woocommerce#30918]
Hi,

I've encountered the following bug:

it seems that when you're using Woo REST API endpoints, and probably somewhere in your code you have global $woocommerce or WC() or WC_Order() instanced, that will generate an error 500, in order to fix this issue permanently is to wrap the code in a check for rest API call:

```
if (strpos($_SERVER[ 'REQUEST_URI' ], '/wp-json/') !== false) {
    // Cool API stuff here
} else {
 // Booring WC+WP stuff here
}
```

Best,
Mile

**Comment by juliaamosova** [comment]
Hi @mmilosheski,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks, Mile!

Could you provide a little more information to help us replicate? 

The snippet you shared isn't quite enough for us to see the problem and, for instance, merely calling `wc()` from within the `init` action is not enough to break things during a WC REST API request.

**Comment by mmilosheski** [comment]
Hi @barryhughes I have a Menu Walker where I extend the menu with cool output, the problem occured while implementing  Klaviyo and Brava POS plugins, both are hitting woo rest api endpoints and both plugins were throwwing error 500 in the menu walker, so I have fix the issue by wrapping the output with the following condition:

```
$cart_output = '';
            if (strpos($_SERVER[ 'REQUEST_URI' ], '/wp-json/') !== false) {
                // Cool API stuff here
            } else {
                $output .= '
                <li class="site-header__nav-item paragraph-medium site-header__search">
                    <form class="site-header__search-form" role="search" method="get" action="' . esc_url(home_url('/')) . '">
                        <input class="site-header__search-input" type="search" name="s" placeholder="Search here..." value="' . get_search_query() . '">
                        <button class="d-flex justify-content-center align-items-center site-header__search-button search-submit">
                            ' . get_svg(["icon" => "search", "class" => "header-search-icon"]) . '
                        </button>
                        <input type="hidden" name="post_type" value="product">
                    </form>
                </li>';
                    }
                }
            }
```

I hope this helps with the solution

**Comment by barryhughes** [comment]
Thanks, though there still isn't quite enough for us to replicate the problem and assess if the issue is a bug in WooCommerce or not. Things we would need before we can take a second look:

- A set of steps to replicate
- The most minimal possible code snippet(s) required to see the problem

Otherwise, we are left guessing. It would also be useful to know the specific error that is being generated (the *500 Internal Server Error* likely maps to a much more specific PHP error that can be found in the logs).
