### ISSUE TITLE
wc_add_notice() doesn't work as expected on process_registration unless items are in cart 

### ISSUE THREAD

**Issue by sLippitt** [woothemes/woocommerce#30925]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Default process_registration notices not outputting on form-login.php template, unless customer has items in cart.  

**Expected behavior**
Customer should be presented with a message if registration is successful or a $validation_error occurs and these notices should not be reliant on items being in cart. 

**Actual behavior**
When adding custom registration validation into the register form using the  woocommerce_process_registration_errors filter, the errors are not outputting making it impossible for the user to know what's wrong. The notice also doesn't appear for when an account has been created.  However, as soon as you add an item into the cart, the notices output as expected.

**Comment by juliaamosova** [comment]
Hi @sLippitt,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @sLippitt,

I allowed registration from the My Account page and also put the following snippet in place:

```php
add_filter( 'woocommerce_process_registration_errors', function( WP_Error $errors, string $username, string $password, string $email ) {
	if ( false !== strpos( $email, 'disallow' ) ) {
		$errors->add( 999, "We don't like your email address, it is disallowed." );
	}

	return $errors;
}, 10, 4 );
```

Next, I tried to register a new account by supplying the email address `disallowed@local.dev`. Registration is halted and the expected error message displays. As you can see in the following screenshot, the cart is empty when I do this:

<img width="924" alt="custom-registration-logic" src="https://user-images.githubusercontent.com/3594411/146270326-3070638e-4b88-49fd-bfc0-37e42dd4ab55.png">

However, judging by the title of the ticket, it seems you might be using `wc_add_notice()` instead of adding an error as I did in my test? If that's correct, is there a particular reason you are doing things that way? If necessary, please also provide an example of the custom code you are using and any other steps needed to replicate.
