### ISSUE TITLE
Email not sending to vendor or customer when there is a new order created for COD

### ISSUE THREAD

**Issue by raaj5671** [woothemes/woocommerce#30953]
Hi,

This is my first time using woocommerce platform for my site. Currently, I am having a problem sending emails or notifications to the WCFM Store Manager app. This only happens when the customer creates a new order with the payment method as COD. Unless the customer made the payment then automatically it changes the status to processing order.

How can I send email or notification to both customer and vendor respectively so that they know there is a new order with COD payment?

For now, I want it to automatically change the order status to processing at least only for COD option. Can someone guide me on this.

**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Comment by rodelgc** [comment]
Hi @raaj5671,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
