### ISSUE TITLE
Dynamic pricing calculation issue

### ISSUE THREAD

**Issue by SteveGMelbourne** [woothemes/woocommerce#30954]
Hello there

After referring to help resources, we are still having trouble getting dynamic pricing to calculate our pricing structure. I have been getting some strange results while testing, so I'd like to determine if there is an issue or human error. 

Our product's single price is $1,320. When they buy two, they get that second one at half-price ($660). That same discount then applies from the third and so on. So each additional unit gets that 50% discount, but that first unit is always full price at $1,320.

I have included screencaps of two (of many) methods we have tried to achieve this along with the resulting calculation in the cart. I input 3 as the quantity so the desired price should be $2,640, rather it is showing $3,300. I have also attempted setting up a set price for each individual quantity with no luck.

Oddly, several times the cart would not show any result besides $3,300. I tested this by altering values in the dynamic pricing and clearing the cache, but I would have to close the browser in the end.

Thanks for your interest and assistance!

Cheers
Steve

![Capture](https://user-images.githubusercontent.com/74036595/137435860-a48b7a96-4638-43a9-a94f-28decdf7a6ae.PNG)
![Capture3](https://user-images.githubusercontent.com/74036595/137435864-29d1c889-e1dd-41c1-933c-d1f3204a5fc4.PNG)
![Capture2](https://user-images.githubusercontent.com/74036595/137435865-130aecf6-07b5-4d72-ac6e-c64c926337af.PNG)

**Comment by lkraav** [comment]
Commercial plugin, like Dynamic Pricing, support is only handled at https://woocommerce.com/my-account/create-a-ticket/

**Comment by rodelgc** [comment]
Hi @SteveGMelbourne ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the Dynamic Pricing plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
