### ISSUE TITLE
Unable to retrieve USPS shipping rates

### ISSUE THREAD

**Issue by sarun007** [woothemes/woocommerce#30980]
WooCommerce Shipping and Tax is failing at pulling the latest shipping rates from USPS. Due to this issue, USPS shipping option is not showing on the website.

10-19-2021 @ 01:44:45 - Error: Unexpected USPS Response:
80040B1AAuthorization failure. You are not authorized to connect to this server.USPSCOM::DoAuth (calculate_shipping)
10-19-2021 @ 03:54:01 - Error: Unexpected USPS Response:
80040B1AAuthorization failure. You are not authorized to connect to this server.USPSCOM::DoAuth (calculate_shipping)
10-19-2021 @ 03:55:47 - Error: Unexpected USPS Response:
80040B1AAuthorization failure. You are not authorized to connect to this server.USPSCOM::DoAuth (calculate_shipping)
10-19-2021 @ 03:55:47 - Error: Unexpected USPS Response:
80040B1AAuthorization failure. You are not authorized to connect to this server.USPSCOM::DoAuth (calculate_shipping)
10-19-2021 @ 03:57:02 - Error: Unexpected USPS Response:
80040B1AAuthorization failure. You are not authorized to connect to this server.USPSCOM::DoAuth (calculate_shipping

Please fix the issue asap

**Comment by rhofyi** [comment]
Go here: /wp-admin/admin.php?page=wc-settings&tab=shipping&section=usps

Check your USPS User ID.

I know some sites use a default value for the USPS User ID like: 150WOOTH2143

If your account is using that, or something like it, then perhaps changing it to an actual account might solve your issue.

Good luck!

**Comment by sarun007** [comment]
@rhofyi are you only applying that solution to this plugin, WooCommerce Shipping & Tax? Or is your solution with the same one I referenced above?

With this plugin, I cannot find where 150WOOTH2143 exists in the Dashboard's WooCommerce section.

**Comment by gregory-github** [comment]
I am having a similar issue and I am surprised that the USPS User ID is the same as mine, so creating an actual USPS account may fix this issue. I will pursue this potential solution and post my findings. 
https://wordpress.org/support/topic/cant-ship-to-anywhere-outside-local-shipping-zone/#post-14989437

**Comment by gregory-github** [comment]
Replacing 150WOOTH2143 (placeholder user id) with your own USPS account [here](https://www.usps.com/business/web-tools-apis/welcome.htm) fixes that auth issue and got my site to show USPS shipping prices again.

**Comment by juliaamosova** [comment]
Hi @sarun007,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [USPS Shipping Method](https://woocommerce.com/products/usps-shipping-method/) plugin (if this is what you are in fact using) which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.

**Comment by sarun007** [comment]
Hello @juagonala i am not talking about the USPS Shipping Method plugin i am talking about your[ WooCommerce Shipping & Tax](https://wordpress.org/plugins/woocommerce-services/) Plugin that plugin is used for USPS shipping method connected with jetpack

**Comment by juagonala** [comment]
Hi @sarun007, I think I've been mentioned on this issue by error. I submitted a few PRs in the past and my name maybe appeared as a GitHub suggestion, but I don't work for Automattic and your message might have not been notified to them. Regards.

**Comment by sarun007** [comment]
Hi @juagonala  sorry actually i was trying to mention @juliaamosova

**Comment by juliaamosova** [comment]
>i am not talking about the USPS Shipping Method plugin i am talking about your WooCommerce Shipping & Tax Plugin that plugin is used for USPS shipping method connected with jetpack

Thank you for additional details @sarun007. In the future, please fill out the issue template and provide all the necessary details including the plugins you are using on the site in order to avoid the back and force and identify what is causing the issue quicker. 

With that said, WooCommerce Shipping & Tax Plugin is being developed in another repository by another team: https://github.com/Automattic/woocommerce-services.

I see that you already opened the issue there: https://github.com/Automattic/woocommerce-services/issues/2488. 

I will keep this issue closed. Please continue discussing it in https://github.com/Automattic/woocommerce-services/issues/2488.
