### ISSUE TITLE
Display final Subtotal before taxes 

### ISSUE THREAD

**Issue by lenamtl** [woothemes/woocommerce#30998]
Hi,

This will be a good idea to have an option to display final subtotal before taxes in frontend and in backend.

Subtotal of items (actual)
Promo code when this is the case (actual)
Shipping (actual)
**Final subtotal** (I need this)
Taxes
Total

**Comment by juliaamosova** [comment]
Hi @lenamtl,

Thank you for opening the issue! 

However, I believe we already have the feature you are requesting available. 

If you set your tax settings for the prices to be entered exclusive of tax and displayed exclusive of tax as well, a subtotal order amount will be displayed before tax and total with tax included. Please see screenshots below:

![tax0](https://user-images.githubusercontent.com/19143190/138148217-fccaa793-cde8-40d0-84b5-48d6f9e32640.png)

![tax1](https://user-images.githubusercontent.com/19143190/138148238-07ff4273-fb11-4ff1-9c73-3a924c31e206.png)

![tax2](https://user-images.githubusercontent.com/19143190/138148254-f4ee231f-030b-4eec-8411-965f8dbd27e1.png)

Are you still missing any features in regards to displaying prices?

**Comment by lenamtl** [comment]
Hi,

Not exactly what I mean
I would like to have a final subtotal just before the taxes (including the shipping)

Subtotal of items (actual)
Promo code when this is the case (actual)
Shipping (actual)
**Final subtotal** (I need this)
Taxes
Total

**Comment by AashikP** [comment]
Hi there!

> I would like to have a final subtotal just before the taxes (including the shipping)

What you're looking to do isn't possible by default.

It requires further feedback from the WooCommerce Core team to clarify if this fits in with our current priorities for the project. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Thanks for the report, unfortunately, at this time we won't be able to add this feature since it's not requested much. If you really need this feature I would also recommend to look at [customizing WooCommerce](https://woocommerce.com/document/customizing-woocommerce-best-practices/) for your use case.

**Comment by lenamtl** [comment]
Hi,

Does the Final subtotal exists into the code and just not displayed or this value just not exist?
