### ISSUE TITLE
Woocommerce calculating the tax incorrectly

### ISSUE THREAD

**Issue by AliBorsan** [woothemes/woocommerce#30999]
Hello
On our live store we entered a standard tax : 15% Which in woocommerce : 15.0000
So when we have a product with Price of 100 inclusive tax  , the TAX should be 15 , but the woocommerce calculate it about 7,5 !
I tried on local host, and for a product of 100 inclusive tax  price and tax 15% , Woocommerce calculate it around 13% !
The only activated plugin on WP is Woocommerce, and the country is Saudi Arabia.
An example from the local host in the in the link:
https://ayanapets.com/wp-content/uploads/2019/05/wootax.png

Update:
According to this site it is calculated by woocommerce correctly:
https://vat-calculator.org/vat-saudiarabia.html
So it might be not a bug, and seems that i have no knowledge of accountancy.
So delete it please if i am wrong.
Sorry for inconvenience.

**Comment by juliaamosova** [comment]
Hi @AliBorsan,

Thank you for opening the issue! We can look at it further but we need more information from you in order to reproduce the issue. Specifically, tax settings you have in the `WooCommerce / Settings / Tax` section. We ideally need all the details listed below:

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by renatofrota** [comment]
> Update: According to this site it is calculated by woocommerce correctly: https://vat-calculator.org/vat-saudiarabia.html So it might be not a bug, and seems that i have no knowledge of accountancy. So delete it please if i am wrong. Sorry for inconvenience.

The base of tax is the order total before the VAT itself.

1.000,00 - 130,43 = 869,57 (this is the order net total - and base for VAT).

You can confirm by calculating 869,57 * 0,15 (15%) = 130,43.

The base of tax (amount excluding VAT) is usually obtained by doing this calculation:

1.000,00 / 1,15 = 869,57.

To find the VAT in 2 steps, you can calculate the above first and then subtract it from the order total: 1.000,00 - 869,57 = 130,43.

And a common way to calculate the tax starting by the order total (with tax included) is obtaining the multiplication factor for the tax rate first: 1-(1/(1+tax rate)) , i.e.: 1-(1/(1,15)) = 0,130434783 in the case of a 15% VAT.

So for an order of 1.000,00, you have: 1.000,00 * 0,130434783 = 130,43 VAT.

Finally, in a single step: 1.000,00 * (1-(1/(1,15))) = 130,43.

**Comment by AashikP** [comment]
Thank you for clarifying this, @renatofrota

@AliBorsan You can read more about how WooCommerce manages `Tax inclusive` prices here: [Prices Entered With Tax - Documentation](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/). What you're seeing, is expected behavior.

I'm closing this issue for now. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
