### ISSUE TITLE
Cart page doesn’t updating when removing or adding something

### ISSUE THREAD

**Issue by amine-amirech** [woothemes/woocommerce#31025]
Hello,

Since a few days, I can’t update nis to delete an item on my shopping cart. I have deactivated the cache and the problem is still there. These last days I added the CDN option. I already have this two lignes in woocommerce/cart/cart.php

```
<?php do_action(‘woocommerce_cart_actions’); ?> 
<?php wp_nonce_field(‘woocommerce-cart’, ‘woocommerce-cart-nonce’); ?
```

target url : https://etoile-musulmane.fr/mon-panier-achat/

I have already read the subjects of the same problem but no solution is proposed!

Can you bring me a solution?

Sincerely

**Comment by rodelgc** [comment]
Hi @amine-amirech,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jeffstieler** [comment]
Hello @amine-amirech,

I'm not completely understanding the issue you're having, but your mention of a template file leads me to believe it's due to a customization you've made and not WooCommerce core. If I'm mistaken, please either edit your comment or create a new issue using the [New Bug Template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=Cart%20page%20doesn%E2%80%99t%20updating%20when%20removing%20or%20adding%20something) (filled out completely).

If you're using a custom template for your Cart or Checkout, please note that we don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
Contact WooCommerce support by opening a ticket.
https://woocommerce.com/contact-us/ 

**For help with custom code**
WooCommerce Slack Community: https://woocommerce.com/community-slack/ in the `#developers` channel. 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The Official WooCommerce Facebook Group https://www.facebook.com/groups/advanced.woocommerce/
