### ISSUE TITLE
appearance the problem ERR_HTTP2_PROTOCOL_ERROR when i want edit some page with woocommerce install in Wordpress

### ISSUE THREAD

**Issue by Cleanisnice** [woothemes/woocommerce#31020]
I install the plugin woocommerce when I install it the Wordpress program is apparently normal I will visit home and edit page and I get this error -I cannot access this website It is possible that the website https://www.cleanisnice.com/wp -admin / post.php? post = 216 & action = edit is temporarily inactive or has been permanently moved to another address.
ERR_HTTP2_PROTOCOL_ERROR- uninstall the plugin and I can edit the pages in Wordpress normally, we thought it was the SSL certificate, but the domain has everything installed, we called the Domain support and they told us that it was with woocommercer directly that we had to report the problem, I hope a prompt reply

**Comment by rodelgc** [comment]
Hi @Cleanisnice,

Thank you for submitting the issue. However, I couldn't recreate the issue you're experiencing because the steps to recreate them are not clear. You didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
