### ISSUE TITLE
cannot use .webp images on wc api

### ISSUE THREAD

**Issue by ittca** [woothemes/woocommerce#31031]
I upload the webp image with wordpress api, all good, then i send the link in wc api and i receive an error and the image is not display in the product, if I use .jpg or .png all works good
Does wc api support webp, because wp api does and woocommerce only uses the path(link), if i do this manually directly on the dashboard all is working fine, however with wc API it is not.

**Comment by rodelgc** [comment]
Hi @ittca,

Thank you for reporting the issue. However, this issue seems to have been reported previously here: https://github.com/woocommerce/woocommerce/issues/28998. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

If you think that your issue is different from the one I mentioned, please feel free to leave a comment here, preferably outlining the exact steps to replicate your issue and maybe post the exact WC API request and response (feel free to delete any sensitive information in them). We'll take another look by then.
