### ISSUE TITLE
STOP sending passwords via e-mail Please

### ISSUE THREAD

**Issue by daveloodts** [woothemes/woocommerce#31035]
Every security specialist will tell this: never ever sent a password via mail.
In WooCommerce: when a buyer creates an account during checkout or straight from the registration form; the password is sent via e-mail.
So: a bad person can have the password and the e-mailadress....only those 2 things are needed to login.

This is seriously bad security practice.
In the text of the e-mail there is not even a mention of urgency to change the password. And if so, probably not many buyers will do that. And as we know, many people use the same password all over again. I know that's not safe. But they will point to the software that 'leaked' their password, in this cause WooCommerce.

When the mailbox of the buyer is hacked, a simple fraud can be done.
The fraudster get's the order e-mail, sets a trigger on that, immediately contacts the store owner to change the delivery point.... and bingo.
Or when it's a digital product, they can just download it. Bad for the store owner.

I know shop owners can activate 2 Factor Authentification, but it's not up to WooCommerce to expect that.
So, Please STOP sending passwords in plain text via mail.

**Comment by nandugachristine** [comment]
@daveloodts thank you for raising that issue its really a bad security practice which can result to losses to the store

**Comment by rodelgc** [comment]
Hi @daveloodts,

Thank you for taking the time to file this report. [As per our security policy](https://github.com/woocommerce/woocommerce/security/policy), please report any potential security issues via HackerOne. This allows us to handle them appropriately, as well as avoid accidental disclosure.

Although we won’t be able to tackle it in the upcoming weeks, we’re going to add it to our backlog where it will be considered for future releases.
﻿
Stay tuned for updates.

**Comment by juliaamosova** [comment]
Hi @daveloodts,

Thank you for raising the issue! 

>Thank you for taking the time to file this report. [As per our security policy](https://github.com/woocommerce/woocommerce/security/policy), please report any potential security issues via HackerOne. This allows us to handle them appropriately, as well as avoid accidental disclosure.

>Although we won’t be able to tackle it in the upcoming weeks, we’re going to add it to our backlog where it will be considered for future releases.
﻿
>Stay tuned for updates. 

Noting here that this issue had been originally evaluated as a security issue by mistake. Apologies for the confusion. It was moved into our private repository for discussion but later moved back here for further discussion in the open. 

We are currently marking it as an `enhancement` issue and adding a `votes needed` tag to collect feedback from others.

**Comment by daveloodts** [comment]
Thanks, i wil try to have more votes for this.

**Comment by daveloodts** [comment]
hi WooCommerce Support, we've got 25 votes. Compared to other Github tickets, that is a lot. A lot of votes! So it's time to clean this up, and to drop the password in the New Account mailing. 

By the way: this is not a rocket-science adjustment that we ask. 
Just remove the password in the New Account template; it's absolutely not needed as a buyer can always request a reset to change their password.

**Comment by juliaamosova** [comment]
Thanks for the further follow-up @daveloodts!

It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Thanks for opening the issue. I agree, it makes sense. Though I think it potentially adds some friction to the first sign-in process. We should check what WordPress does and perhaps make use of the same flow.

One thing to note, though:
> When the mailbox of the buyer is hacked, a simple fraud can be done.
The fraudster get's the order e-mail, sets a trigger on that, immediately contacts the store owner to change the delivery point.... and bingo.
Or when it's a digital product, they can just download it. Bad for the store owner.

When the mailbox of a buyer is hacked, then the attacker can easily reset the password on any store even if we don't send the password via email, as usually, the password reset link goes to the very same mailbox. Besides multi-factor authentication or some heuristics like detecting unusual locations or user agent string, there is really no way how to protect a person whose email was hacked and I think at that point, their order in some WooCommerce store will probably be the least of their worries.

(We keep enhancement requests closed until we start working on them actively, so I'm going to close this one now and we'll keep an eye on the [popularity of the request](https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3A%22votes+needed%22). Thanks for understanding.)

**Comment by ramonfincken** [comment]
Please note that not all shops have registration forced or enabled at all Peter.

I really think Woo should do as WP Core does. No emails should contain passwords. Ever.

**Comment by djprmf** [comment]
I go ahead and say that this could be a GDPR issue.
Create a user account is NOT a action that needs to send the password by email to the user, and is sensitive information that is being sent to the user without the need of it.

If it was a bad practice before, now is even more.

And @peterfabian , the explanation provided i think isn't entirely correct.
"When the mailbox of a buyer is hacked, then the attacker can easily reset the password on any store even if we don't send the password via email, as usually, the password reset link goes to the very same mailbox."

True, but the main password used in the account of the website is unknown to the attacker. Having the password in the email is a point for that specific password be used and marked for future attacks - many users still use the same password to multiple online accounts.

If the password was not send in first place, the attacker can reset the password for sure, but doesn't know the original one.
Also reseting is a extra step that, sometimes, can lead to more time to detect the attack and avoid it. Having the password in the email is "all the work done" for the hacker.

**Comment by ramonfincken** [comment]
agree with @djprmf one could also auto login the user if you want to right?

**Comment by daveloodts** [comment]
How popular do you want the request to be? 
29 votes now... so far.
Looking back in other tickets; that is a lot.

It's not a rocket science request, it is just editing the mail template.
This edit has no other impact on every other functionality inside WooCommerce or WordPress.

My example of a hacked mailbox is -i get it- not 100% waterproof. Even then a reset-mail can be received.
and @djprmf had a good reply on this.

But it's about the rule that software never ever sent password in text via mail. 
It shouldn't even be a discussion.

Cause it will turn back in your face...
Competitors can mis-use this.... create bad PR around it for WooCommerce. 
So, this is -for me- even more then a technical edit; it is to take away the stick where competitors can take a strike.

**Comment by lucprincen** [comment]
It's kind of strange that this discussion got closed and is being labelled an **enhancement**.
while yes, it's very hard to protect from hacked e-mail inboxes as a third party, we could -at the very least- try to mitigate mail-hijacking by not sending passwords in plain text. 

The default WordPress flow works fine in this case.

**Comment by KittyGiraudel** [comment]
> It's kind of strange that this discussion got closed and is being labelled an enhancement.

This. How exactly is fixing a rather serious security faux-pas an “enhancement”? We‘re playing fast and loose with the word “enhancement” here. Any security professional would raise that as a significant issue that should be resolved. The fact that WooCommerce expects the community to vote on that issue says a lot about the attention it brings to security-related issues.

I understand this is not a one-liner, and it will take a bit of time and effort to fix by core maintainers. Absolutely, that’s totally fair! Yet, this is clearly an important topic to address. Sending passwords in clear text is a terrible security practice, and one could hope a powerful and popular solution like WooCommerce would know better—or at the very least commit to address it, one way or another.

**Comment by gmazzap** [comment]
@peterfabian 

> Though I think it potentially adds some friction to the first sign-in process. 

If the word spread about this, the friction will be on using WooCommerce. Which is worse, no?

Note that WooCommerce could let the user login for the _current_ request (via a cookie) but if the buyer would need to access the account in another session would need to set the password using a link received via email. Or could request a new link via "reset password".
This makes the  sign-in process _easier_ and _also_ more secure.

> We should check what WordPress does and perhaps make use of the same flow.

WordPress sends a link to set a password, not the password itself.

Again, what WooCommerce could do is to create an user on the fly, set auth cookie, so the user is logged in for the current session without leaving the site.
At same time, send a "reset password" link in the email.
Both nicer and more secure experience.

> When the mailbox of a buyer is hacked, then the attacker can easily reset the password on any store even if we don't send the password via email, as usually, the password reset link goes to the very same mailbox. 

While this is true, the reason why sending credentials via email is **very bad** is that **many** emails providers does not implement TLS for emails. And **many** emails clients are configured to use "plain" POP3/SMTP instead of their encrypted counterpart, so chances are that **email data travels on the wire as plain text**.
To make a comparison, it is like you would let login people using http and not http**S**.  That is bad, and your browser already tells you that when you visit an HTTP site, but then if the site sends passwords via email, it means nothing that it has HTTPS.

Sending password via email is enough to be considered a [plaintext offender](https://plaintextoffenders.com/).

Sniffing plain text communications is at least one order of magnitute easier than hacking someone's email box. If you create an account on a Starbucks network, a malicious user could **extremely easily** grab your username/password if your email server/client are not using encrypted protocols.

The reason why send a reset link to the email is more secure than sending the password is that in the first case no password _travels_ network in plain text, even if the email server/client are not using any encryption.
And that is why "reset password" links should have a pretty short expiration and should only be usable once.

Sure thing, MFA is best, but outside the "nerds" bubble, the great majority of people have no idea what it is, letting aside use it.

**Comment by peterfabian** [comment]
Appreciate the responses and good discussion. Please understand I haven't closed this issue because I don't think it's important. I agree we should not send passwords in plaintext. I closed the issue because it's our workflow for improvements to not let them sit as open issues in the repository for eternity, but instead rather give users the opportunity to vote on the issues they find most relevant. (Perhaps our workflow is flawed since it's easy to misunderstand our intention). 
We're going to work on this in the next sprint, at which point we'd normally open the issue again. However, I'm opening the issue already now to make it apparent we're going to pick it up on Monday. 

> Please note that not all shops have registration forced or enabled at all Peter.

> I really think Woo should do as WP Core does. No emails should contain passwords. Ever.

I agree. WooCommerce also doesn't force registration of the customer (unless the store wants that). Lots of stores provide a link to the order (e.g. from Shopify) and having that link means you can make changes to the order, so it's similar to having a password. This discussion is not really consequential for the problem at hand, though, because I agree, we should stop sending emails with password in plaintext. 

> many users still use the same password to multiple online accounts.

True, but I would find it strange if people started using the WooCommerce/WordPress generated alphanumeric passwords with symbols anywhere else. I would be less surprised if the same password that the user used for their main email address was used for their accounts to stores. But again, that is irrelevant, because I agree, we should stop sending passwords in plaintext.

> If the word spread about this, the friction will be on using WooCommerce. Which is worse, no?

That's spot on!

**Comment by gmazzap** [comment]
> We're going to work on this in the next sprint, at which point we'd normally open the issue again. However, I'm opening the issue already now to make it apparent we're going to pick it up on Monday.

Thanks!

**Comment by tomjn** [comment]
I would clarify that I and others do not consider this a feature or enhancement, _this is a security breach and a major bug with legal, regulatory, compliance and security ramifications._ This feature on its own could invalidate many compliance requirements required for operating an Ecommerce store in many countries.

The correct thing to do, that WordPress itself does, is to send a reset link so that the user can choose their new password.

This is also what Amazon does:

https://www.amazon.co.uk/gp/help/customer/display.html?ref_=help_search_1-1&nodeId=GH3NM2YWEFEL2CQ4&qid=1637331365532&sr=1-1

This is what Ebay does:

https://www.ebay.co.uk/help/account/changing-account-settings/changing-password?id=4197&mkevt=1&mkcid=1&mkrid=710-53481-19255-0&campid=5336728181&customid=&toolid=10001

Both use a reset link in an email. What WooCommerce is doing is not the norm.

I would also note that this exposes their account details to employers, and any tools that scan their inboxes which can include 3rd parties.

**Comment by tomjn** [comment]
Should anybody be interested in fixing this

`retrieve_password` is used by WP to send a reset link:

https://developer.wordpress.org/reference/functions/retrieve_password/

Here's the AJAX endpoint that uses it to do that:

https://developer.wordpress.org/reference/functions/wp_ajax_send_password_reset/

```php
    // Send the password reset link.
    $user    = get_userdata( $user_id );
    $results = retrieve_password( $user->user_login );
 
    if ( true === $results ) {
        wp_send_json_success(
            /* translators: %s: User's display name. */
            sprintf( __( 'A password reset link was emailed to %s.' ), $user->display_name )
        );
    } else {
        wp_send_json_error( $results->get_error_message() );
    }
```

The line that generates the URL in the password reset email:

```php
    $message .= network_site_url( "wp-login.php?action=rp&key=$key&login=" . rawurlencode( $user_login ), 'login' ) . '&wp_lang=' . $locale . "\r\n\r\n";
```

And the key it uses:

```php
$key        = get_password_reset_key( $user_data );
```

The `reset_password` function does the actual resetting and firing the hooks:

https://developer.wordpress.org/reference/functions/reset_password/

`check_password_reset_key` validates a key + user login combination against the database

https://developer.wordpress.org/reference/functions/check_password_reset_key/

The action WP watches for in the URL is the `rp` action.

With this and a search for password in the dev hub, it should be possible to completely recreate the reset password functionality in custom emails with a custom frontend while still firing all of the needed hooks. Implementing it via `wp-login.php` should be trivial
