### ISSUE TITLE
Sometimes WC()->session loses value

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#31056]
I want to autofill custom field which user typed previously in checkout form. So I save user typed value in woocommerce session like:
WC()->session->set( 'my_custom_field', 'test' );

The weird thing is, After couple hours this value is gone. But value for native field (which woocommerce autofilled by default) like billing_phone, billing_address, etc still exist and autofiled.

**Comment by Ninos** [comment]
May similar problem:
Since latest update guests/customers sometimes loose cart items (empty cart) after < 1min. I think after new guest/customer is visiting/interacting with site.

PS: After deactivating apcu cache it seems working "fine" again. May a key name Problem using customer_id (0?) instead of session id..

**Comment by Ninos** [comment]
May related to this:
https://github.com/woocommerce/woocommerce/blob/ec5ab7cdb5155f7cebe194d318d3a790a79f0480/plugins/woocommerce/includes/class-wc-session-handler.php#L278

Is customer_id = 0 or the session_key in database?

**Comment by tammullen** [comment]
Hi @erikdemarco 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
@erikdemarco, could you create a minimal snippet that would allow us to replicate the problem? Otherwise we're left guessing as to how your code functions and when it runs (ie, which action it is hooked into). 

> The weird thing is, After couple hours this value is gone. But value for native field (which woocommerce autofilled by default) like billing_phone, billing_address, etc still exist and autofiled.

In my own testing, so long as a session exists (and creating it if it does not), the custom field is persisted along with the other usual fields and expires at the same time.
