### ISSUE TITLE
Display Variation image when product url contains matching variant attributes

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [woothemes/woocommerce#31069]
When viewing a product page using a direct link to a product variation, the main product image always display the set product featured image, even though a variation image is set in the product's variation settings.

The preselected variation is visible though.

Let's say the product variant link looks like this:

https://myshop.com/shop/category/my-variable-product-name/?attribute_pa_color=green

I access this link and would expect to see the variant image as product image instead of the main product image, because also the color green has been selected on first page view.
This however is not the case. Instead the color is preselected only on the variation attribute select field as desired attribute color. The product image gallery is however still displaying the main product's image.
I have to actively switch between colors, to get the product gallery to display my desired variation image.

I tested this in various shops and was wondering if this could be a feature, you guys could add somehow?

Systems I tested this on:
Latest WordPress
Latest WooCommerce
One random Default WP theme
no other plugins.

**Comment by tammullen** [comment]
Hi @s-a-s-k-i-a 

In order to do this you need to include all the variation attributes. 
For example `?attribute_pa_color=green&attribute_pa_size=small` 

There is an existing issue to discuss this reported previously here https://github.com/woocommerce/woocommerce/issues/29033. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
