### ISSUE TITLE
REST API /wp-json/wc/v3/products/ does not return all products. Yes /wp-json/wc/v2/products/

### ISSUE THREAD

**Issue by maxisosa** [woothemes/woocommerce#31106]
Ej v3: /wp-json/wc/v3/products/?sku=12345679

Result: []

Ej v2: /wp-json/wc/v2/products/?sku=12345679
Result: [
    {
        "id": 889,
        "name": "Lorem",
        "slug": "lorem",
        "permalink": "https://*******/products/category/lorem/",
        "date_created": "2021-06-07T11:20:05",
        "date_created_gmt": "2021-06-07T14:20:05",
        "date_modified": "2021-11-08T16:11:54",
        "date_modified_gmt": "2021-11-08T19:11:54",
        "type": "simple",
        "status": "publish",
        "featured": false,
        "catalog_visibility": "visible",
        "description": "",
        "short_description": "",
        "sku": "12345679",

**Comment by tammullen** [comment]
Hi @maxisosa 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using `wp-json/wc/v3/products/?sku=` (and also `wp-json/wc/v2/products/?sku=`)

You didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
