### ISSUE TITLE
Remove unnecessary is_ajax, since there is a WP native method

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#31112]
since WP 4.7.0 there is native `wp_doing_ajax` function which we use in WooCommerce's `is_ajax` already.
This override is unnecessary and we should directly use the WP native function.

**Comment by juliaamosova** [comment]
Hi @kkmuffme,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Sounds reasonable to me!

Note that we cannot immediately remove that function (it's public and may be depended upon by third party code, etc). So we'd need to correct/update our own calls to use `wp_doing_ajax()`, then mark this one as deprecated (and/or add a `_doing_it_wrong()` call).

**Comment by kkmuffme** [comment]
I did deprecate it. See includes/wc-deprecated-functions.php in this PR

**Comment by barryhughes** [comment]
Yes, my error: re-running some checks that failed (though it seems clear they were unrelated to this change), then we can probably go ahead and merge. Thanks!
