### ISSUE TITLE
WP Theme Provider - noticed an issue with "woocommerce-accepted-payment-methods" and "woosidebars" with PHP 8.0

### ISSUE THREAD

**Issue by simonjerermygill** [woothemes/woocommerce#31119]
**Prerequisites (mark completed items with an [x]):**
- [ x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Our Hosting Provider in South African - Xneelo (Hetzer SA) is upgrading all WP PHP Linux hosted sites to PHP 8.0 as their baseline.

- Website breaks after upgrade to version 8.0 PHP
- Four of our sites use the same template (Starbella version 1.0) built by Themplatemela.
- We have made contact with Themplatemela support team to help with the break in the code after moving to 8.0

**Themplatemela's response 2nd after checking through our site with full Admin access was, this :**

_Hi Simon,

- We check your issue, please downgrade the PHP version.
- Our theme support PHP 8.0 version.
- But, "woocommerce-accepted-payment-methods"and"woosidebars" plugin does not support PHP 8.0 version.
- So, please downgrade the PHP version. 
- Hope you understand.

Thank You
Best Regards,
Hitesh Chauhan_

**Comment by juliaamosova** [comment]
Hi @simonjerermygill,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

> But, "woocommerce-accepted-payment-methods"and"woosidebars" plugin does not support PHP 8.0 version.

The issues you are having are being caused by the following plugins:

- [WooCommerce Accepted Payment Methods](https://wordpress.org/plugins/woocommerce-accepted-payment-methods/) - this plugin had not been developed by WooCommerce. It was developed by James Koster. Please contact them for further support [here](https://wordpress.org/support/plugin/woocommerce-accepted-payment-methods/). 

- [WooSidebars ](https://wordpress.org/plugins/woosidebars/)- this plugin had been developed by WooCommerce but we haven't made any changes to it [since June 2018](https://github.com/woocommerce/woosidebars) - I believe it is on the road to be deprecated. We will get back to you regarding this in a few days.

**Comment by simonjerermygill** [comment]
Hi @juliaamosova,

Thank you for the prompt response. I'll take up these issues with the correct developers.

**Comment by rrennick** [comment]
Closing this as the reported issues were with extensions.
