### ISSUE TITLE
Shortcode Box Size Issue

### ISSUE THREAD

**Issue by lootlydeals** [woothemes/woocommerce#31128]
Recently I'm adding shortcode using woo commerce custom code areas. but when I'm adding that code the custom shortcode box length is small that's code excuted in next line which make that shortcode useless.

see image for much clear understand.  please fix this issue as soon as possible
![image](https://user-images.githubusercontent.com/93158587/141172105-a0d8aecf-3014-4553-a343-771ccc93909e.png)

**Comment by tammullen** [comment]
Hi @lootlydeals ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by a 3rd party plugin. I'm not certain which plugin but it might be related to rehub theme as the screenshot in this link looks similar to yours https://rehubdocs.wpsoul.com/docs/rehub-theme/shop-options-woo-edd/extended-custom-product-areas/

Please contact the author of the plugin directly for further help.
