### ISSUE TITLE
States for Panamá

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#31160]
**Is your feature request related to a problem? Please describe.**
The out of the box experience of woocommerce for the bigger countries is waaay different from the ones in the development world.
We need on latinamerican countries to have a better out of the box experience. And the only i humbly help is giving by default states for shipping.

As i described on https://github.com/woocommerce/woocommerce/issues/30375

**Describe the solution you'd like**
Add the different shipping states for the country, and change the 'state' label for the one corresponding to this country.
This country uses [Provincia](https://es.wikipedia.org/wiki/Anexo:Provincias_y_comarcas_ind%C3%ADgenas_de_Panam%C3%A1) as 'State'

**Describe alternatives you've considered**
I am chilean, but i can bet that on our sibling countries, they have the same problem. A lot of custom plugins that gives the geographical divisions for the country.

**Additional context**
I've talked to different friends around the continent to get a better idea, but because every country have different ways to set shipping costs around, this is a mild solution.
Like chile, we use Comunas (cities) rather than Regiones (states) for shipping. And how @masteradhoc pointed out, woo cannot have cities for calculating shipping costs. That will be the ultimate solution for everyone.

But at least, this will help latinamerican users to have a better platform experience with Woo, which i love <3.

**Comment by masteradhoc** [comment]
@avagp check pullrequest please :)

**Comment by juliaamosova** [comment]
Hi @avagp,

Thank you for submitting the issue. Since there is already a PR open by @masteradhoc, I will leave it to the PR reviewer to revive the change proposed further. 

Noting that in WooCommerce, we use the UNICODE CLDR standard for countries and regions naming and divisions. The recent UNICODE CLDR release 40 (released 18 days ago) showing current country/state names can be seen below:

https://github.com/unicode-org/cldr/blob/release-40/common/subdivisions/en.xml

Any proposed changes need to match the data available via UNICODE CLDR.

**Comment by TheRadicalDreamer** [comment]
The changes are ok @masteradhoc .

Even though the CLDR is not complete. It is missing some provincias.
![image](https://user-images.githubusercontent.com/11801254/141838874-06ec4f77-58e4-4b69-90f9-5ddcf777b775.png)
