### ISSUE TITLE
Clients tab with no data to display "No data to display" how to solve ?

### ISSUE THREAD

**Issue by GabrielLode** [woothemes/woocommerce#31204]
After updating woocommerce, customers disappeared from the customers tab, I've already done the uninstall and installation and the problem persists, could someone help me?
Thanks

**Comment by tammullen** [comment]
Hi @GabrielLode 
The number of details you provided is not enough for us to work with and identify what could be going on.

However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by GabrielLode** [comment]
Hello, Thanks for replying, I'm here to inform you that I was able to solve the problem, restoring the database on my hosting, this was the only method that worked.
