### ISSUE TITLE
Fallback to Redirect Downloads no longer working

### ISSUE THREAD

**Issue by streamworksaudio** [woothemes/woocommerce#31213]
The fallback to Redirect Downloads was added a few releases back to help with those that needed to use Redirect mode for downloads.  However with the release of 5.9.0 the fallback is no longer working - my customers were getting the 'File Not Found' error.  Setting downloads to Redirect work, but the automatic fallback no longer does.

**Comment by barryhughes** [comment]
@streamworksaudio, thanks for flagging this. 

The explicit redirect fallback still seems to work under 5.9.0, at least in my own local testing, so we'll need some more information in order to help you with this.

Checking our bases first of all, can you confirm that the _"Allow using redirect mode (insecure) as a last resort"_ setting found in **WooCommerce ▸ Settings ▸ Products ▸ Downloadable Products** is still enabled?

<img width="991" alt="optional-redirect-fallbacks" src="https://user-images.githubusercontent.com/3594411/142047555-4b8d2ad3-eca9-4256-a702-a6c6d6c7068e.png">

If it is, can you provide a few more details to help us understand the problem?

- What was the last version you used (where things still worked) before updating to 5.9.0?
- Can you give an example of one or more download filepaths that lead to this problem (or is it all filepaths)?
- Are you using any extensions that change where some or all downloads are stored (ie, Amazon S3) ... which extensions if so?

I appreciate you may prefer not to expose those filepaths here in the public issue tracker. It would be fine to obfuscate them a little, so long as they maintain the same structure (including scheme, port number etc, if those are things that the problematic filepaths/URLs happen to use).

**Comment by streamworksaudio** [comment]
Hi Barry,

Yes the option to Allow Redirect is checked.

> What was the last version you used (where things still worked) before updating to 5.9.0?

It was working in the last version before 5.9.0.

> Can you give an example of one or more download filepaths that lead to this problem (or is it all filepaths)?

See answer to next question

> Are you using any extensions that change where some or all downloads are stored (ie, Amazon S3) ... which extensions if so?

I am using my own custom code to handle downloads via a signed URL with AWS.  The URL for the download file points to a custom post type which then does a few checks, and if verified generates a temporary signed URL and then redirects to that URL (file URL).

When the redirect option was removed a few releases ago it resulted in the same error.  Once the fallback was added it was working, but the error is back in 5.9.0.  Setting the file download method to 'Redirect (Insecure)' does work.

Cheers

**Comment by barryhughes** [comment]
In 'normal' cases—using a range of regular download files and URLs—I can't seem to bring about the problem and the fallback works as expected. Would it be possible for you to share your custom code, or even better a distilled version that shows just the raw mechanics in their simplest form, to help us replicate the problem and understand what you're seeing?

...We'll need some sort of steps-to-replicate, in essence.

**Comment by streamworksaudio** [comment]
My code runs at the 'template_redirect' hook and simply checks if the post type is my custom post type.  If so then checks to see if the user has purchased a required product to access the download.  If that conditioned is met, then a temp. URL is generated by aws cli (which is ran using shell_exec) then redirect to that url with wp_redirect( $signedUrl , 301 );

I don't think it is my code - only because it works fine when the download method is set to redirect (insecure).  Only if I set the download method to anything other than Redirect (insecure) does it not work - just shows File Not Found Go to Shop.

**Comment by barryhughes** [comment]
The handler is designed to only fallback on redirect mode if the download URL is perceived as being 'remote'. That's been true for a long time: what changed recently is the logic that decides if a URL is remote or not.

In this case—given that your custom post types are being served by the very same WordPress site—I think it's fair to say we're not dealing with a remote URL and so, in a way, the anomaly was that, before now, that category of URL was incorrectly regarded as being remote. 

We can certainly review this, but I wonder if it may be better (and provide more stability) in your case to explicitly code an exception for these CPT URLs: you could for instance take advantage of the `woocommerce_file_download_method` hook by writing a filter function that sets `redirect` mode if the product ID or file path matches certain conditions. This would circumvent the force download logic entirely, for that class of download.
