### ISSUE TITLE
File(/dev/urandom) is not within the allowed path(s)

### ISSUE THREAD

**Issue by johnjullies** [woothemes/woocommerce#31226]
A client with a WooCommerce site are getting reports from bugsnag with the following error message: https://secure.webmedic.com/y2nZrs

The request URL is https://chuloves.com/product-category/colour/page/1/?per_row=3&amp;shop_view=grid&amp;add_to_wishlist=3011

Here's the complete error screenshot on bugsnag:

- https://secure.webmedic.com/Tq8b9z
- https://secure.webmedic.com/gOZASP

Here's another one https://secure.webmedic.com/b33oRg

Request URL: https://eyemuse.my/?kinsta-monitor

We reached out to Kinsta, they shared we need to get WooCommerce support to look into this issue https://secure.webmedic.com/R4mw1m

We don't know what the error is about or what is exactly causing it, just that bugsnag reported it coming from WooCommerce files as seen on the screenshots.

Please advise.

**Comment by DavidAnderson684** [comment]
The screenshots show that WooCommerce uses a core WordPress function to generate random bytes. The core WordPress function attempts to use the file `/dev/urandom`, and your PHP installation is set up to forbid this. The WordPress function is set up to silence any warnings when this occurs, but you have a debugging set up to log warnings even in that situation.

**Comment by tammullen** [comment]
Hi @johnjullies ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for the report—and thanks for the notes, @DavidAnderson684, not much more I can add to that :-) 

Since there doesn't seem to be a 'real' problem here (it's just that New Relic is surfacing an error that would otherwise be suppressed), I'd recommend silencing the error there if you can.

I'll go ahead and close this report as there isn't really anything for us to do on our end.
