### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by AdamDurzynski** [woothemes/woocommerce#31229]
In CART window (popup) a translation is missing (Polish): CART, CHECKOUT, TOTAL ...

**Comment by tammullen** [comment]
Hi @AdamDurzynski 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

If you find this is a translation issue please contact the translation team https://translate.wordpress.org/projects/wp-plugins/woocommerce/ for further help.
