### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by bnbc** [woothemes/woocommerce#31279]
On version 5.9.0, my product breadcrumb didn't show child categories, juste the first parent.
On version 5.6.0 it's ok

Did you make change on that recently ?

I don't know what to do to fix that...
Thks !

EDIT : i update 5.6.0 to 5.9.0 and breadcrumb is ok, so the only difference i see is php 7.4 for breadcrumb working and php 7.2 for crumb not working, maybe a cause?

**Comment by rodelgc** [comment]
Hi @bnbc,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for, especially the system status report. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
