### ISSUE TITLE
Currency not available in checkout page

### ISSUE THREAD

**Issue by edokh** [woothemes/woocommerce#31296]

**Comment by rodelgc** [comment]
Hi @EidoKh,

I see that [you already reached out](https://wordpress.org/support/topic/currency-not-available/) for assistance in our WordPress.org support forums. 

GitHub should be treated as a place to report WooCommerce bugs only. 
﻿
As mentioned in the support thread you submitted in WordPress.org, the issue you are having seems to be caused by the 3rd party plugin PayTabs. 
﻿
Please contact the author of the plugin directly for further help.
