### ISSUE TITLE
404 . After active the woocommerce, goto the setup page, click the continue, show the error info

### ISSUE THREAD

**Issue by bendeng** [woothemes/woocommerce#31322]
Error:  Failed to load resource: https://www.xxx.com/wp-json/wc-analytics/products/reviews?page=1&per_page=1&status=hold&_embed=1&_fields%5B0%5D=id&_locale=user
the server responded with a status of 404 ()

Wordpress 5.8.2 , woocommerce 5.9.0
<img width="584" alt="iShot2021-11-28 23 31 58" src="https://user-images.githubusercontent.com/7540995/143774711-b3636eac-4d54-4af8-b64f-889e43d48f9d.png">

**Comment by tammullen** [comment]
Hi @bendeng ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by bendeng** [comment]
> Hi @bendeng ,
> 
> Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
> 
> **Describe the bug** A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Isolating the problem (mark completed items with an [x]):**
> 
> * [ ]  I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> * [ ]  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
> * [ ]  I can reproduce this bug consistently using the steps above.
> 
> **WordPress Environment**

Sorry for late to reply, I hava resolved this issue just because I used other plugins such as start-template.
If I install astra theme first, and install start-template plugin, and then import whole site(it will install woocommerce), it will be ok!
