### ISSUE TITLE
Delete User , Delete Attachment of Product Not Product

### ISSUE THREAD

**Issue by AH72KING** [woothemes/woocommerce#31344]
I have faced a issue, in which we delete few users who did data entry of products in woocommerce, no post assign to them only product, 

Wordpress and Woocommerce do not show any content assign to them regarding post , product etc. 

So when we delete the users and do not keep content it not delete all products but delete all images of the products 

I suggest it should not delete the image or at least tell admin user what it will delete or what it will keep 

Currently its look like bug ,

**Comment by tammullen** [comment]
Hi @AH72KING ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
