### ISSUE TITLE
integrate this SEPA-QR plugin into Woocommerce core

### ISSUE THREAD

**Issue by Coernel82** [woothemes/woocommerce#31358]
As discussed in #27661 we need SEPA-QR-Codes for BACS-payments.
Here is the (hopefully) GDPR-comliant simpel plugin doing the job:

# Plug-and-play plugin for Woocommerce
https://github.com/Coernel82/SEPA-QR-for-Woocommerce

**Comment by designboxcom** [comment]
Thank you very much for your awesome work. I'll give it a try during the week. I also wish to see this function integrated into Woocommerce Core... :)

**Comment by juliaamosova** [comment]
Hi @Coernel82,

Thank you for your work on this issue. However, it is best not to open a separate issue for the existing issue as it is a duplicate. It is better to keep one issue open for the discussion to happen in order not to lose track. 

I'll keep this issue open for now. However, it requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Coernel82** [comment]
Hello @juliaamosova 
> it is best not to open a separate issue for the existing issue as it is a duplicate. It is better to keep one issue open for the discussion to happen in order not to lose track.

I generally agree on this however as the original thread was very long due to many pieces of information which were not really relevant any more I decided to open a new issue - also as this one is a milestone ahead. From creating the option for a SEPA-QR-Code to actually having a fully functional plugin which just needs to be integrated.

Closing the original thread and marking it as a duplicate of this new one seems for me the logical option.

**Comment by barryhughes** [comment]
Thanks, though I don't think any further feedback is really needed at this point. 

The [original issue](https://github.com/woocommerce/woocommerce/issues/27661) is already marked as an enhancement and it seems like a solid idea, though not necessarily a high priority. As to which issue should remain open, it doesn't make a massive difference on our end (plus, there may be useful information in there and the amount of interaction is a useful indication of how much demand there is), so I'll close this one and keep the pre-existing one (since it has been open longer).
