### ISSUE TITLE
WooCommerce admin, React/gutenberg and should a business tool really focus on what's the latest tech?

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#31387]
I just wanted to initiate a discussion about the splitting off of WooCommerce Admin into a separate plugin, which currently has scathing reviews https://wordpress.org/plugins/woocommerce-admin/#reviews with almost 40% being negative.

I get where it's coming from though:
- WordPress with Gutenberg: completely different target demographic though. People who use WP usually have a regular website to showcase their business, project or it's just a blog.
- competition (mainly: shopify), which offers a more modern/faceted UI: it's easier to get started (since you have the credit card gateway baked in, which WC lacks), but once you need to customize, it gets much, much more complicated and it's not as versatile as WC.

I fear, that by doing this, you are losing those people who actively use WC and its plugins, as they run an actual business. Unlike WP which is "just a website" for a company or private person, WC is at the core of their business for most of WC's users.

While being at the technological "edge" for the frontend certainly makes sense, it is, at least in my opinion, a completely misguided approach for the backend.

To put it bluntly: what is in it for the businesses that use WC? I don't see any benefit, except some shinier reports (which would also be doable with the old, non-React admin interface though)

- The new WooCommerce Admin is not only extremely buggy and can, according to reviews, in 40% of cases not be used for production.
- there are onboarding costs for new UI for all employees who use the interface
- there are onboarding and development costs for operational plugins and customizations that run with WooCommerce 

+ looks better

EDIT: I opened this issue here, and not in the woocommerce-admin repo, as this is not about the woocommerce-admin plugin but about WooCommerce and its relation to the admin interface.

**Comment by rodelgc** [comment]
Hi @kkmuffme,

Thank you for bringing this topic up! I am adding the `needs developer feedback` label to this issue so that the Core team could take a look and continue the discussion, or direct you to an appropriate forum. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by peterfabian** [comment]
Hi @kkmuffme
Thanks for your honest feedback, and apologies for the late response.

WC Admin currently provides an improved onboarding experience (which we can see in numbers---how many people actually set up their store and start selling) and more powerful reports.
In the near future, we're planning to build a new editing experience for products, orders, settings, etc. We see it as a stepping stone towards a more commerce-centric experience with WooCommerce overall. Thus, it doesn't really make sense to keep it as a plugin anymore. It currently not only serves as a delivery mechanism for the features I mentioned, but also gives a signal to our community of merchants and developers about the future of our product.

As you noted, it's much more difficult to find your way around WooCommerce as a new user---to set up the store in the beginning, create a product or fulfill an order takes a lot of steps, the UI is not really guiding users and isn't optimized for an e-commerce product. We'd like to provide a better experience to our users and believe that what we're building is actually better (and if it's not, we will change it, as we're talking to merchants and developers about their experience constantly).

You're right that there are costs associated with user training if we change WC user interface. Change is always hard. However, providing a better experience for the new users should mean that also experienced users would hopefully see the benefits once they get used to the new ways. We're also planning to introduce any changes gradually to make sure users have the time to adapt. 

It's also true that the reviews are not raving and WC Admin is evolving quickly which means it sometimes breaks, but we're really testing vigorously before each release and take all bugs seriously. If you check the reviews, some of the recent negative ones complain about the plugin 'not doing anything'. This is entirely on us, where we haven't communicated well that WC Admin has been part of WooCommerce core since 4.0, thus installing it now is mostly pointless. It's understandable that people get confused. There are also complains about crashes and slowness, both of which we're solving as soon as we can reproduce these problems. So if you want to help us, please continue providing us with constructive feedback and reliable reproduction instructions in case of problems.

In the worst case, you can always disable the additional features via filters, but we certainly hope things we build make sense for most e-commerce customers. If you have more specific feedback, I'm sure the product manager for WC Admin @pmcpinto would be happy to hear you out.
