### ISSUE TITLE
Issue with Yoast and WooCommerce

### ISSUE THREAD

**Issue by TecLub** [woothemes/woocommerce#31437]
1 of the Yoast columns is causes an error in my product overview in the backend. Looks like the column SEO-title isn't working like it's suppost to work. 

![image](https://user-images.githubusercontent.com/96126205/146012681-519b8b65-40db-4922-a913-23d07227072c.png)

**Comment by rodelgc** [comment]
Hi @TecLub ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

Here's the template that you should fill out when reporting issues in the repo:

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by TecLub** [comment]
Hi!

Turned out you can choise columns in the screenoptions. Turned of the column that caused it :)

**Comment by rodelgc** [comment]
Thanks for the prompt feedback @TecLub! I'm closing this issue now.
