### ISSUE TITLE
bad cumulation of fees

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#31440]
Hello, 
on Credit or debit card, there is an error : 
![image](https://user-images.githubusercontent.com/70097501/146037667-f1cc63bc-69b2-4f3a-8782-333083431bbc.png)
It's not 4.9% for total per transaction each time : only when the payment is made with a non european card AND in another currency than wich is used on website. So many times, total per transaction is only 1.4% + 0.25.

it's confused !

**Comment by rodelgc** [comment]
Hi @Cellophile,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ghost** [comment]
OK. 
**Describe the bug :**
It's not 4.9% for total per transaction each time : only when the payment is made with a non european card AND in another currency than wich is used on website. So many times, total per transaction is only 1.4% + 0.25.

**To Reproduce**
just go to woocommerce / settings / payments / and you can see my **sreenshot** ...

**Expected behavior**
replace 4,9% by "1,4% or more"
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or Storefront.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @Cellophile ,

Thank you for providing the steps to reproduce. However, the usual _WooCommerce > Settings > Payments_ page is very different from the one in your screenshot. It should look like the one in the WooCommerce Payments Settings documentation found here: https://woocommerce.com/document/configuring-woocommerce-settings/#section-16

And you haven't provided the system status report, which could have helped us replicate the environment and evaluate if the issue you're getting is caused by other plugins.

If you happen to be using third party plugins in your payment settings, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
﻿
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
