### ISSUE TITLE
Missing 6.0.0 GitHub tag/release

### ISSUE THREAD

**Issue by thejamescollins** [woothemes/woocommerce#31475]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is no tag for the [recent 6.0.0 release](https://developer.woocommerce.com/2021/12/15/woocommerce-6-0-released/).

cc @ObliviousHarmony 

### Expected behavior

A tag should exist for every WooCommerce release.

### Actual behavior

Tag is missing :)

### Steps to reproduce

1. Go to https://github.com/woocommerce/woocommerce/tags
2. Latest stable tag is 5.9.0

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @om4james thank you for bringing this up! Adding the `needs developer feedback` for now so @ObliviousHarmony could take a look.

**Comment by ObliviousHarmony** [comment]
Hello @om4james,

Thanks for raising this issue. I've gone ahead and [published a release here](https://github.com/woocommerce/woocommerce/releases/tag/6.0.0), but I should warn you that if you're using Composer, the package is entirely broken at the moment. Packagist only supports having a single package per repository, and since we've shifted towards a Monorepo, we're going to need to utilize a mirror repository to build WooCommerce releases. This is one of our tasks for the start of the new year.

**Comment by thejamescollins** [comment]
Thank you for adding @ObliviousHarmony , we're using the tags in CI via git clone, so we aren't relying on the packagist package :)
