### ISSUE TITLE
Dev environment setup docs are not discoverable and failing at NX The current directory isn't part of an Nx workspace.

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#31520]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1. The ["how to setup a dev environment"](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets) doc is hard to find. It needs to be linked from the `readme.md` and possibly also the main wiki page and the main developer.woocommerce.com page.

2. Following the instructions and running:
`pnpm nx composer-install woocommerce`

Results in 

> NX  The current directory isn't part of an Nx workspace.

I tried installing a "workspace" and that resulted in:

> NX   ERROR  Nx failed to create a workspace.

Seems like there is a step missing from the docu?

I would like to pull the latest and build the assets, but since introducing the mono-repo, it's gotten even _more_ complicated to run a functioning plugin from the repo. 

Additional suggestion: The dev environment should also mention Local WP as a simpler alternative to VVV. 

### Expected behavior

The script assets build so I can run the plugin

### Actual behavior

> NX  The current directory isn't part of an Nx workspace.

### Steps to reproduce

follow steps at https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets

### WordPress Environment

WSL 2 on Windows 11

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @helgatheviking,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by ObliviousHarmony** [comment]
Hello @helgatheviking,

I've added the link to the development environment to the readme, but I think that in general, we're going to need to do some work on this documentation. A lot has changed since it was first written, and I think separating the general tooling information from the environment-specific information could be useful to everyone.

As for the specific error you've encountered, I'll try it out on my own Windows machine, but it would be great to get a little more information from you about your configuration before moving forward. You've noted that you're using WSL2, but I'm wondering whether you've cloned to repo into the Windows filesystem or the Linux filesystem?
