### ISSUE TITLE
My products are not uploading to facebook

### ISSUE THREAD

**Issue by ser2gec** [woothemes/woocommerce#31527]
how can i update? My old products and missing items appear in my store.

**Comment by zhongruige** [comment]
Hi @ser2gec,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ser2gec** [comment]
My products are not equal to woocommerce as seen in the attachment

![image](https://user-images.githubusercontent.com/96865183/147805376-89771eed-1910-43d4-b652-8df4e184b2f5.png)


![image](https://user-images.githubusercontent.com/96865183/147805428-924bb123-3418-400e-b71e-4440f67f2426.png)

I did the update but still my products do not go to facebook

![image](https://user-images.githubusercontent.com/96865183/147805483-7e8cc658-397f-408c-9cbf-077fb38e270c.png)

I pressed the button many times but my products are not going to facebook

**Comment by ser2gec** [comment]
It doesn't show up in my sets.

![image](https://user-images.githubusercontent.com/96865183/147805681-912c7403-b8f2-484b-b316-78649d58dccc.png)


![image](https://user-images.githubusercontent.com/96865183/147805696-c97f6387-9267-4d14-aa39-0d40f28495da.png)

**Comment by zhongruige** [comment]
Hi @ser2gec,

Thank you for sharing those screenshots! Can you also please provide your System Status report so we can further investigate?

WordPress Environment

``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin. ``` 

Thank you in advance!
