### ISSUE TITLE
Duplicate Items in cart have a reduced price

### ISSUE THREAD

**Issue by homeandgardenbarrels** [woothemes/woocommerce#31697]
I'm using WooCommerce for my website.  I had a customer order 2 duplicate items recently.  When ordering on the shop page, it shows the price correctly, but when you go to the cart, the price drops significantly for each item.  When in the cart, i can reduce the quantity to 1 of the items, and the price is correct.  When bumping it back up to 2, the price drops back down.  How does this get fixed?

**Comment by ObliviousHarmony** [comment]
Hi @homeandgardenbarrels ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
