### ISSUE TITLE
Path cannot be empty [wc-template-functions.php]

### ISSUE THREAD

**Issue by 0free** [woothemes/woocommerce#31735]
https://github.com/woocommerce/woocommerce/blob/7395a4698bcc793f19d2ea680c7209ceea32a963/plugins/woocommerce/includes/wc-template-functions.php#L53

```
CRITICAL Uncaught ValueError: Path cannot be empty in /woocommerce/includes/wc-template-functions.php:53
Stack trace:
#0 /var/www/wordpress/wp-includes/class-wp-hook.php(307): wc_template_redirect()
#1 /var/www/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /var/www/wordpress/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /var/www/wordpress/wp-includes/template-loader.php(13): do_action()
#4 /var/www/wordpress/wp-blog-header.php(19): require_once('...')
#5 /var/www/wordpress/index.php(17): require('...')
#6 {main}
  thrown in /var/www/wordpress/plugins/woocommerce/includes/wc-template-functions.php on line 53
```

**Comment by 0free** [comment]
Also ` get_404_template()` is returning empty path.
Theme: Hello-Elementor + Elementor

**Comment by ObliviousHarmony** [comment]
Hi @SaifAlSubhi,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by 0free** [comment]
Hi there,

I think it may be caused by TranslatePress - Multilingual v2.1.9

see below the error it generates:

```
2022-02-03T09:27:55+00:00 CRITICAL #!trpst#trp-gettext data-trpgettextoriginal=5946#!trpen#Uncaught ValueError: Path cannot be empty in /plugins/woocommerce/includes/wc-template-functions.php:53
Stack trace:
#0 /wp-includes/class-wp-hook.php(307): wc_template_redirect()
#1 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /wp-includes/template-loader.php(13): do_action()
#4 /wp-blog-header.php(19): require_once('...')
#5 /index.php(17): require('...')
#6 {main}
```

**Comment by jonathansadowski** [comment]
Hi @SaifAlSubhi,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please fill out [this form](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and create a new issue so that we can further evaluate. I am closing this issue.

**Comment by DevWael** [comment]
Any news on this?

**Comment by JanWebofka** [comment]
Any updates 9.3.3 Woocommerce
