### ISSUE TITLE
[Enhancement]: disable the plain text "password change" notification sent upon account creation

### ISSUE THREAD

**Issue by solaceten** [woothemes/woocommerce#31827]
### Describe the solution you'd like

Greetings all and @peterfabian  @rodelgc @melek 

I think this is an improvement over sending plain text password, so good call!  

When I did a test account creation, I got the welcome email with the link that invited me to set a new password which was great - however, I also received a plain text "Password Changed" notification email along the lines of "This notice confirms that your password on [website] was recently changed.  If you did not change your password, please contact....." etc...

Is that the correct behaviour? Because it seems unnecessary to send it to a new user that has just registered.

At least give us a unique filter to turn this off?

This would work, however, it turns off ALL password reset notification.....
`add_filter(` 'send_password_change_email', '__return_false' );

Thanks

_Originally posted by @solaceten in https://github.com/woocommerce/woocommerce/issues/31257#issuecomment-1028439626_

[melek](https://github.com/melek) commented [1 hour ago](https://github.com/woocommerce/woocommerce/pull/31257#issuecomment-1029302694)

> The 'Password Changed' emails are part of WordPress. They can be disabled on your site with a filter, see this forum post for more details:
> 
> https://wordpress.org/support/topic/disable-password-changed-emails-2/
> 
> I agree with you that suppressing these emails when a new customer initially sets their password is worth considering :) If you want that functionality, I recommend [filing an issue](https://github.com/woocommerce/woocommerce/issues/new/choose) so it can be discussed.

**Comment by peterfabian** [comment]
Thanks for the idea, I think it's a good enhancement. Would you like to try and submit a PR for it?

**Comment by vedanshujain** [comment]
(came across this issue as part of reviewing old open issues). I think something like this might be possible:

1. Use the `woocommerce_update_customer_args` filter to add a flag that the update is being done by WooCommerce.
2. In `send_password_change_email` check existence of flag added in step 1, and if it exists, return false to prevent the mail.

Since the relevant code is in WP core, I don't think we can make changes directly. I am closing this for repo maintenance, but happy to reopen and discuss if there's feedback.
