### ISSUE TITLE
[Enhancement]: separate build tasks for CSS, JS, languages

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#31840]
### Describe the solution you'd like

I'd like to see separate node shortcuts for recompiling the CSS, JS, pot files. If I want to work on a CSS feature, it's slow and irrelevant to recompile the JS. For example, I am dabbling with the message/notice styles on the default themes.

**Comment by samueljseay** [comment]
Hi @helgatheviking because JS builds are cached if you don't change the JS it won't actually spend time rebuilding. 

If you are seeing them rebuild when not making changes to JS then that'd be a separate bug we certainly need to investigate.

**Comment by samueljseay** [comment]
I'm going to close this one for now, because as of right now caching is working and won't rebuild things you haven't asked to. And for most users they'll want to build everything at least once.

If they want to build specific packages they can navigate to the package and build it.

If you feel this is in error, please feel free to re-open. 🙇🏻
