### ISSUE TITLE
Problema na aba de Opções de Tela

### ISSUE THREAD

**Issue by vthamada** [woothemes/woocommerce#31871]
Fui alterar o número de itens por página de 20 para 645 e a página atualizou e não mostrou mais nenhum produto além de estar travada a aba opções de tela, não estou conseguindo alterar nada.

**Comment by vthamada** [comment]
alterar*

**Comment by ObliviousHarmony** [comment]
Hi @vthamada,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by vthamada** [comment]
Descrição do Bug: 
O problema ocorreu quando eu entrei na aba Todos os produtos do Woocommerce, entrei nas opções de tela e mudei o número de produto por página de 20 para 645 que é a quantidade de produtos que eu tenho. Assim ele atualizou a página e ficou toda em branco aparecendo só a aba Opções de Tela e a aba de ajuda, mas ambas com os botões travados, sem conseguir clicar.

Para reproduzir:
1- Vá na opções Todos os produtos do Woocommerce
2- Clique em Opções de Tela
3- Mude o produtos por página de 20 para 645

Comportamento esperado:
- Que mostrasse os produtos.
- Ou que eu conseguisse clicar nas Opções de Tela para conseguir mudar a quantidade de produtos por tela de volta para o padrão.

![image](https://user-images.githubusercontent.com/79325422/153663468-65a92308-99d3-4c0c-aac6-fef670cb7775.png)

**Comment by claudiosanches** [comment]
Olá @vthamada,

Pelo o que você esta reportando me parece que o servidor esta tendo dificuldades para carregar essa quantidade de produtos que foi configurada, por isso não é exibido nenhum produto, a página inclusive não termina de carregar adequadamente e por este motivo você não consegue mais clicar em "Opções de tela".
Você pode confirmar isso olhando o log de error do servidor, com certeza vai ter alguma mensagem dizendo `PHP Fatal error` ou algo similar, já que isso pode também causar problemas o servidor ficando sem memoria o suficiente para processar.

Isso é fácil de corrigir, esta opção da quantidade de itens a serem exibidos são salvas por usuário, então é possível arrumar isso pelo banco de dados, mas se você criar outro usuário administrador vai poder acessar normalmente já que vai carregar apenas 20 produtos.

Você pode atualizar pelo banco de dados, fica salvo na tabela `wp_usermeta` e o `meta_key` se chama `edit_product_per_page`. Também pode atualizar rodando o seguinte snippet apenas uma vez (remova isso depois):

```php
add_action(
    'admin_init',
    function() {
        $current_user = get_current_user_id();
        update_user_meta( $current_user, 'edit_product_per_page', 20 );
    }
);
```

Caso você precise de ajuda para rodar códigos no seu site, você pode usar o [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin para executar o código a cima.
Também é possível corrigir restaurando um backup do seu banco de dados, caso tenha algum de antes de ter feito essa alteração na quantidade de produtos.

Enfim, quanto mais produtos você for carregar, mais pesada vai ser a página pro servidor, talvez você vai precisar aumentar os recursos do seu servidor se isso for realmente necessário, além de implementar ferramentas de cache como o Redis.

Eu vou fechar este ticket já que não é um problema direto no WooCommerce. Obrigado.

---

English summary:

- User reported issues to load more than 600 products in the Product's list page in the admin after changing the "Number of items per page" option inside the "Screen Options" tab. By analyzing this reports and a screenshot provided by the user, seems evident that the server is unable to load the amount of data and the page isn't fully loaded, causing issues to interact with elements controlled by JS.
- This issue is easily fixed by changing the `edit_product_per_page` option, or by restoring a backup, or by creating a new user, since this options is saved per user, or even increasing server resources.
- This issue can happen with all other product types in WordPress, so I don't see it as an issue on WooCommerce.

I'm closing this issue for now, since it doesn't sounds like an issue on WooCommerce side.
Thanks!
