### ISSUE TITLE
Issue on product variation in Variable Product

### ISSUE THREAD

**Issue by PELLACANIS** [woothemes/woocommerce#31870]
I found out a problem adding one or more variations to a variable product.
 
I create variations using 4 different attributes: 2 Color Type, 18 ("" included) colors grouped as "Color 1" and 13 ("" included) colors grouped as "Color 2". One of the Color Type enables user to choose "Color 1" and "Color 2". The other Color Type enables only the choice of "Color 1".
 
 The issue occurs when i add one color to "Color 1". After the creation of the variations linked to the new color, i notice that colors shown in the Dropdown list in the Product page are not correct. In addtion to this, "Color 1" can be choose with every Color type.

Currently i have 30 variations the variable product. Before the amendments (addiction of a color to the attributes), the variations were 27.
 
Best regards,
Stefania Pellacani

**Comment by ObliviousHarmony** [comment]
Hi @PELLACANIS,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by th3c0r** [comment]
Hi @PELLACANIS ,
I understand your issue. I noticed the same issue a few months ago when we happened to have more than 30 variations on a variable product. However I think it is not so much a problem, but it is designed that way

The issue is that when we have a variable product with 30 or more variation and all the variation in this product of a specific term of the attribute(e.g. color black) are not enabled the term is still showing in the select input in the frontend page of the product.

To reproduce you must follow the steps bellow:

1. Create an attribute named Color and add ten terms to this(e.g. red, blue, yellow e.t.c.)
2. Create an attribute named Size and add 4 sizes(e.g. small, medium, large, xlarge)
3. Create a test product and set the type to "variable product"
4. Create variations with all the available compinations of the two attributes(color, size). In this example they will be 40 in total. 
5. Set all variations "in stock", set a positive value as stock, and set a valid  regular price so all of them will be purchasable.
6. All the 40 variations must be enabled
7. Visit the product in the frontend and you will see two dropdowns (one for each attribute) with all available compinations to select.
8. Now edit again the product, and set all the variations with a specific color for this case we assume the black as disabled(not check the enable checkbox)
9. Save the product
10. Visit the product in frontend again. 

Now although no variation with black as color is enabled, we still see the black in first dropdown(the select input for color attribute). This happens only we have 30 or more variations in the product.

In wc-template-functions file there is a function named woocommerce_variable_add_to_cart
https://github.com/woocommerce/woocommerce/blob/616b61348e244a25ced0b247ef3aaf922730ca94/plugins/woocommerce/includes/wc-template-functions.php#L1711-L1732

This function has a line of code to decide if will load all the variations from the database or not

`$get_variations = count( $product->get_children() ) <= apply_filters( 'woocommerce_ajax_variation_threshold', 30, $product )`;

Τhe decision is made based on the number of variation of the product, as we can see the default value of the threshold was 30. Maybe this threshold exists for performance reasons.

So @PELLACANIS if you want to change this threshold e.g. change to 40 you can add a filter in your **functions.php** file

`add_filter("woocommerce_ajax_variation_threshold", function($threshold){
	return 40;
}, 20, 1);`

Τhis change is likely to affect for example the loading time of the product page as more queries will be run. You can try this to see.
