### ISSUE TITLE
Copy button does nothing

### ISSUE THREAD

**Issue by PabloRodriguezSierra** [woothemes/woocommerce#31894]
Hello, for some reason, and for months now, after some update maybe, the copy the address button does not work. It does nothing.
Any clues?

**Comment by jonathansadowski** [comment]
Hi @PabloRodriguezSierra,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please fill out [this form](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and create a new issue so that we can further evaluate. I am closing this issue.
