### ISSUE TITLE
I cant change shipping zone to Germany

### ISSUE THREAD

**Issue by spacingcakelol** [woothemes/woocommerce#31904]
Hi, so I want to add a new zone but I can only see the 2 ones I already added a time ago. 

![Screenshot_40](https://user-images.githubusercontent.com/68335536/154273679-95c1fa0a-3dc9-4c80-8845-cfeb5895db05.png)

**Comment by jonathansadowski** [comment]
Hi @spacingcakelol,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please fill out [this form](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and create a new issue so that we can further evaluate. I am closing this issue.
