### ISSUE TITLE
icons appear in dashboard but it deosn't in frontend

### ISSUE THREAD

**Issue by mouadh-dev** [woothemes/woocommerce#31901]
![image](https://user-images.githubusercontent.com/62395675/154094593-85e967a6-cf62-40b5-8b1b-35777e042f16.png)
it appear as exclamation mark inside square

**Comment by jonathansadowski** [comment]
Hi @mouadh-dev,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please fill out [this form](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and create a new issue so that we can further evaluate. I am closing this issue.
