### ISSUE TITLE
[Enhancement]: Set the global $product variable during the checkout loop

### ISSUE THREAD

**Issue by FeelPeak** [woothemes/woocommerce#31912]
### Describe the solution you'd like

During the checkout loop, filters for custom product types are sometimes unable to access the product ID being looped over due to the lack of a globally accessible variable. Neither `get_post_ID` nor `get_queried_post_id` nor `wc_get_product()` nor `global $product` contain the product ID being looped over, thus giving the filter function no way to access that data.

We were able to come up with a workaround using the `woocommerce_cart_item_subtotal` filter, but it's not ideal since it requires using a second, mostly unrelated filter to do what the first filter should be able to achieve on its own.

With just a small modification to the relevant product loop in `\woocommerce\templates\checkout\review-order.php`, it should be possible to set one of these global values.

### Describe alternatives you've considered

Custom checkout page templates and the woocommerce_cart_item_subtotal filter both work, but require more code and allow for less code reuse compared to always being able to globally access the product that's being looped over like you can already do on most pages.

**Comment by rrennick** [comment]
@FeelPeak I apologize for the delay in responding. Could you provide a more concrete example where this is an issue? The `woocommerce_cart_item_product` filter passes the `$cart_item` before displaying the item from which you can use `$cart_item->get_product_id()` to get the product ID.

**Comment by ralucaStan** [comment]
@FeelPeak I was able to find a different approach suggested to you in the PR you submitted https://github.com/woocommerce/woocommerce/pull/31913.

`In the case of woocommerce_subscriptions_product_price_string, the $product is available directly (as a second argument). This seems like the cleaner way to do things; is there a reason those won't work for you?
`

I am going to close this issue because of the lack of activity.
