### ISSUE TITLE
wc_get_checkout_url() is not working all the time

### ISSUE THREAD

**Issue by wpmarmite** [woothemes/woocommerce#31910]
Hello,

As a french WooCommerce user, I didn't understand why this function wasn't working. While browsing the code, I noticed that it was checking the page with the `checkout` slug. However, it's not the same slug in french and in other languages.

Why not checking the Advanced setting page where the checkout page is defined?

Here's the code for reference:

```
function wc_get_checkout_url() {
	$checkout_url = wc_get_page_permalink( 'checkout' );
	if ( $checkout_url ) {
		// Force SSL if needed.
		if ( is_ssl() || 'yes' === get_option( 'woocommerce_force_ssl_checkout' ) ) {
			$checkout_url = str_replace( 'http:', 'https:', $checkout_url );
		}
	}

	return apply_filters( 'woocommerce_get_checkout_url', $checkout_url );
}
```
https://github.com/woocommerce/woocommerce/blob/5d7f6acbcb387f1d51d51305bf949d07fa3c4b08/includes/wc-core-functions.php#L1465

Thanks

**Comment by jonathansadowski** [comment]
Hello @wpmarmite,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please fill out [this form](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and create a new issue so that we can further evaluate. I am closing this issue.
