### ISSUE TITLE
The postcode field on the checkout page only accepts Latin numerals.

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#31914]
### Describe the solution you'd like

As mentioned in the title, the postcode field on the checkout page only accepts Latin numerals. Please fix this.
I enter Persian numbers for the postal code but it is not accepted.

thank you

**Comment by rrennick** [comment]
@79ho3ein Could you provide your System Status report and include the steps to reproduce this issue?

**Comment by ralucaStan** [comment]
Hey @rrennick, 
there aren't a lot of postal codes out there that have non alpha numeric characters;
I tested the 12345-1234 USA zip code and an Irish zip code containing the space character and they both worked fine.

I will close this ticket because of lack of activity; feel free to reopen if you have an example of a full address with zip code that does not work.
