### ISSUE TITLE
OAuth: /wc-auth/v1/authorize returns 'A valid URL was not provided'

### ISSUE THREAD

**Issue by ArvindhMangoleap** [woothemes/woocommerce#31959]
Here is my URL
`https://wooshop.gallabox.dev/wc-auth/v1/authorize?app_name=Gallabox&scope=read_write&user_id=eyJhY2NvdW50SWQiOiI2MDA2YjQxZGJlMGQyZTc1Mjg5YTI4Y2EiLCJ1c2VySWQiOiI2MDA2YjY3M2JlMGQyZTc1Mjg5YTI4Y2QiLCJwcm92aWRlcklkIjoiNjIxNGQ2NzNjMDVjYjZiY2EzMDRjMzc3Iiwic2hvcCI6Imh0dHBzOi8vd29vc2hvcC5nYWxsYWJveC5kZXYifQ%3D%3D&return_url=https%3A%2F%2Fapp.gallabox.dev%2Fintegration%2Fwoocommerce&callback_url=https%3A%2F%2F0d45-49-204-128-13.ngrok.io%2Fauth%2Fintegrations%2Fwoocommerce%2Fcallback`

My NodeJs code

```
        const endpoint = "/wc-auth/v1/authorize";
        const params: IWooCommerceAuth = {
            app_name: "Gallabox",
            scope: "read_write",
            user_id: stateString,
            return_url: `https://app.gallabox.dev/integration/woocommerce`,
            callback_url: `${process.env.HOST_URL}/auth/integrations/woocommerce/callback`,
        };
        const queryString = querystring
            .stringify((params as unknown) as querystring.ParsedUrlQueryInput)
            .replace(/%20/g, "+");
        const uri = `${storeUrl + endpoint}?${queryString}`;```

_Originally posted by @ArvindhMangoleap in https://github.com/woocommerce/woocommerce/issues/8898#issuecomment-1047806875_

**Comment by ArvindhMangoleap** [comment]
Request Payload
![image](https://user-images.githubusercontent.com/72745366/155144611-987fe0e4-aa32-4b05-9d84-f4f02d92d662.png)

Response from WooCommerce
![image](https://user-images.githubusercontent.com/72745366/155144792-6cefc75d-a208-4c70-93e1-917733883ccc.png)

**Comment by jonathansadowski** [comment]
Hi @ArvindhMangoleap,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
