### ISSUE TITLE
Options in rest api , webhooks diassapeared !!

### ISSUE THREAD

**Issue by leonp82** [woothemes/woocommerce#31957]
Hello to all, i tried before a while to create an api key for my store but i see no options when i press 'add key'. The same happens with webhooks.
I attach some printscreens from my installation and my system status.
I noticed that there is a css class ".settings-panel" with a display property set to 'none' if that is useful. When unclicked, settings are appearing.

![error1](https://user-images.githubusercontent.com/28864585/155139205-e7f165d1-e5c4-4800-ade0-e0795424f95c.jpg)
![error2](https://user-images.githubusercontent.com/28864585/155139208-f41e56a0-852c-4351-b2bd-343c62073945.jpg)
![error3](https://user-images.githubusercontent.com/28864585/155139210-e34c0db1-227c-4e17-b3d1-1db7fc6fedd8.jpg)
[system.TXT](https://github.com/woocommerce/woocommerce/files/8116893/system.TXT)

Best regards,
Leonidas

**Comment by jonathansadowski** [comment]
Hi @leonp82,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by leonp82** [comment]
Hello again,

With little research I found out that the problem was caused by caldera
forms plugin. I will replace it with another form plugin.

Thank you for your response,

Leonidas

Στις Τρί, 22 Φεβ 2022, 17:52 ο χρήστης jonathansadowski <
***@***.***> έγραψε:

**Comment by peterfabian** [comment]
Thanks for the update!
