### ISSUE TITLE
Download SEPA XML not possible

### ISSUE THREAD

**Issue by tperke** [woothemes/woocommerce#31984]
Hello all,

I want to do a download of all orders via Woocommerce -> Orders. But when I click on "Apply" nothing happens. No download and no error message. What can be the problem here and maybe there is a solution to this?
![Bildschirmfoto 2022-02-25 um 15 38 19](https://user-images.githubusercontent.com/51281059/155682939-361963df-0cc0-46d0-b0b4-7b556a4005f0.jpg)

**Comment by jonathansadowski** [comment]
Hi @tperke,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
