### ISSUE TITLE
Installation failed: Could not copy file

### ISSUE THREAD

**Issue by kid745** [woothemes/woocommerce#31992]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unable to install Woocommerce into Wordpress. I have tried downloading the Woocomerce.zip file from outside to install it manually but still no success.
![image](https://user-images.githubusercontent.com/100456616/155828205-58351223-3ed4-481d-8f8a-8cae55526453.png)

### Expected behavior

Woocommerce can be installed in Wordpress

### Actual behavior

I have tried the quick install in Wordpress site but no success. I have tried the manual installation but still no success.

### Steps to reproduce

...

### WordPress Environment

....

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hello @kid745,

> Unable to install Woocommerce into Wordpress. I have tried downloading the Woocomerce.zip file from outside to install it manually but still no success.

Generally, this can happen due to incorrect permissions for files and folders on your server for your WP installation. You can find full details about it in https://wordpress.org/support/article/changing-file-permissions/

> I have tried the quick install in Wordpress site but no success. I have tried the manual installation but still no success.

There's also another manual installation that you can try by uploading by FTP or using your hosting provider file manager, youn can read more about it in https://wordpress.org/support/article/managing-plugins/#manual-plugin-installation-1

Are you able to install other plugins?
I tried to install WooCommerce in a new WordPress installation and it works as expected, and that's why I think it could be related to permissions for files and folders on your server.

Please let me know if it helps and if you can share more details about this issue. Thanks!

**Comment by typoworx-de** [comment]
Had the same problem with fresh WP install trying to install WooCommerce.
