### ISSUE TITLE
Investigate why GitHub is running older versions of workflows

### ISSUE THREAD

**Issue by MrJnrman** [woothemes/woocommerce#32039]

**Comment by MrJnrman** [comment]
GitHub seems to be executing and [older version](https://github.com/woocommerce/woocommerce/actions/runs/1911374296) of `smoke-test-release.yml`. 

If you take a at the run above, you'll see that its not executing the steps outlined in the current version of [smoke-test-release.yml](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/smoke-test-release.yml). This shouldn't be the case.

**Comment by ObliviousHarmony** [comment]
As a note @MrJnrman, Actions run using the context of the current commit. Since this is happening in the release branch, it will only include the workflow files from when the code freeze happened. You would need to cherry-pick those changes into the release branch in order for it to run the workflow you expect it to be.

At a repository level, we can also enable a flag that requires pull requests to be rebased against the latest version of the branch. This makes sure that they're always running the latest workflows. This wouldn't help in the particular case we're discussing, but it's something I think we should enable in the near future.

**Comment by MrJnrman** [comment]
@ObliviousHarmony Thanks for the info...I had a good head scratch about why old workflows were running 😅.

> At a repository level, we can also enable a flag that requires pull requests to be rebased against the latest version of the branch.
Totally agree here. A habit of cherry-picking wouldn't be that great.

Closing this issue.
