### ISSUE TITLE
[Enhancement]: HTML <img> loading Attribute

### ISSUE THREAD

**Issue by stormit** [woothemes/woocommerce#32040]
### Describe the solution you'd like

Hi,

I recommend that we should add the **loading** attribute to the **img** tag [https://www.w3schools.com/tags/att_img_loading.asp](https://www.w3schools.com/tags/att_img_loading.asp). It will improve the speed of website.

**Comment by claudiosanches** [comment]
Hello @stormit,

Thanks for starting this conversation.

> I recommend that we should add the loading attribute to the img tag https://www.w3schools.com/tags/att_img_loading.asp. It will improve the speed of website.

Since WordPress 5.5 the `loading="lazy"` attribute is included by default when calling functions like [`wp_get_attachment_image()`](https://developer.wordpress.org/reference/functions/wp_get_attachment_image/).

I just made a test with WooCommerce 6.3.0 and WordPress 5.9.1 and `loading="lazy"` attribute is present in all images:

![Screenshot from 2022-03-10 16-31-38](https://user-images.githubusercontent.com/1264099/157740425-dba5d324-ead3-45b2-b894-dafdc232a61f.png)

Note that inside the product page it may not display the `loading="lazy"` attribute while inspecting elements using your browser console because the gallery is generated by JS after the page is loaded.

If in your WordPress installation lazy loading isn't working you could try a different theme or some reference of a tentative to disable lazy loading using the `wp_lazy_loading_enabled` filter like `add_filter( 'wp_lazy_loading_enabled', '__return_false' )`.
I hope it helps. 

I'm closing this issue for now. If I missed something, please leave a comment and we will take a second look.
