### ISSUE TITLE
[COT] Spike into order ID resolution (new COT order ID vs historic post ID)

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#32086]
Various parts of our API surface (REST, programmatic and hook-based) require an order ID.

This task is concerned with looking at ways to disambiguate between the historic post IDs we have traditionally used and the new COT ID that we may ultimately use going forward. Very generally, we wish to make things as clear and obvious to our developers as possible, and we also wish to avoid nasty situations such as a serialized task (ie, a scheduled action) coming back to life and operating on the wrong order due to confusion about which sort of order ID is in use.

- Internal link: p1647447840531029-slack-C0E1AV8T0
- Desired outcome: RFC

**Comment by Konamiman** [comment]
We have decided to go with a "posts first" approach as follows:

* Any new row inserted in `cot` will always have a corresponding row in `posts`
  * If `posts` is authoritative: the corresponding row in `cot` is created during data synchronization.
  * If `cot` is authoritative: a placeholder row is inserted in `posts` beforehand. We’ll use a dedicated post type for that, such as `shop_order_placeholder` (to be decided).
* `cot.id` will have the same value of post.id from the corresponding row.
* We’ll remove the `cot.post_id` field since it’s no longer needed.

Internal links to discussion:

p1649841677898909-slack-C0E1AV8T0
p7bje6-3WQ-p2#comment-7101
