### ISSUE TITLE
Investigate and mitigate any potential build issues relating to The Merge

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32148]
We need to consider how build things like linting and configuration will be incorporated in The Merge.

For example, we currently use the `config/*.json` files to generate a configuration PHP file that is included on the server side. This will need to continue working in some fashion when we are monorepo-ed.

**Comment by moon0326** [comment]
I assigned this to myself, but please feel free to investigate it if anyone is interested. More 👀 the better.

**Comment by moon0326** [comment]
After reading `pcShBQ-e4`, I think it might be too early to see any potential build issues. We should regularly check the status of The Merge and see how it goes. The P2 covers pretty much everything we need, but these are my notes so far.

- Core and WCA use slightly different JS lint configurations — We can either use Core’s JS lint configuration or add our own `.eslintrc` file after the merge.
- Core only has `lint:js` command, but it still lints staged js, css, and ts files automatically. We can suggest adding more lint commands if needed, but I rarely lint files manually with NPM commands since it's done by editors automatically.
- According to the P2, config files will be moved. We should check it back later.
>The configs in plugins/woocommerce-admin/config
 will be moved and the associated build processes will be adjusted. We will investigate automating this process during the coming week.
- `/packages` will be moved as well.
> all of WooCommerce Admin’s packages will be folded into packages/js, as well as hooked up to the Monorepo’s Nx infrastructure. The packages should all now be buildable.
- We use `test:zip`, but core uses `build:zip`. We should use `build:zip` after the merge.
- Core doesn't have storybook related commands. We'll need to add storybook packages and commands.
- We have slightly different `tsconfig.json` We should check it back after the merge and adjust or add our own `tsconfig.json` if needed.

**Comment by becdetat** [comment]
Thanks @moon0326 . I think it's valuable to have an idea of what potential issues we might have post-merge, so that we know where to look and spend time. I expect that there might be a couple of days worth of teething issues. Thanks for breaking down the possible areas we need to consider.

**Comment by adrianduffell** [comment]
Closing this out now that the 6.5 code freeze is made and most teething issues have been solved.
