### ISSUE TITLE
Setup experiment: task chaining - side panel

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#32152]
**User Story:**
As a new merchant
I want to know what I need to do to complete store setup
So I can do it quickly and without clicking through different menus

**Description:**
In attempt to help merchants stay in the flow while setting up their store and boost the number of people who complete more than a few tasks, we'd introduce additional guidance at the end of each task. We'd suggest next step the moment the last one is finished and make the task list available from any screen inside WooCommerce.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/79307566/155328298-95ea15f4-53bf-4467-9a87-b7c1002547a1.png">

**Design overview:**
* pbIJXs-1ew-p2
* G9vi4e286yjdzyIdg8hBb1-fi-123%3A14927

**Acceptance Criteria:**

_Side panel_

- [ ] The `Finish setup` button is available in every screen where the action bar is visible
- [ ] The icon in the button dynamically reflects % of complete tasks [nice to have]
- [ ] The task list has the same layout and structure as the one in the Home screen (it'd follow any experiment/change we try out there)
- [ ] Sections inside the panel can be expanded/collapsed and tasks clicked
- [ ] The panel can be dismissed either by clicking the button in the action bar or anywhere outside of it

**Event tracking:** to be assessed by the team

**Comment by octaedro** [comment]
@jarekmorawski, I have a few questions related to this issue:

>  When all tasks are complete, the panel shows the `Things to do next` list

The `Activity` panel is already showing the abbreviated card with the `Things to do next`. I'm not sure if it's a good idea to show the same thing in two panels.

![screenshot-one local-2022 02 25-16_54_30](https://user-images.githubusercontent.com/1314156/155786385-0a5054dd-55e0-4ea1-b6fb-0f2973e86813.png).

Also, I think that since the button says `Finish setup`, I think that after finishing the setup it would make sense to hide the button.

>  The panel can be clicked either by clicking the button in the action bar or anywhere outside of it

I'm not clear about this. The panel will be shown even when the user doesn't click on the Finish setup button?

> If the merchant completes tasks out of order, what is the “next step”?

It should be the first uncompleted task (may be “before” the task just completed).

**Questions about the tasks groups**
- I can see 3 different groups of tasks: `Cover the basics`, `Get ready to sell` and `Customize & expand`, do we have the images for each group? (I couldn't find them in Figma).
- How are the groups composed? (Which task is in which group?).
- Each group is an accordion, when they are collapsed we show the number of unfinished tasks. When the accordion is not collapsed should we continue showing the number of unfinished tasks? (Looking at the design I suppose that it won't be shown).
- Is it possible to have multiple groups uncollapsed or only one group will be uncollapsed at a time?

**Comment by octaedro** [comment]
- Regarding the progressbar design we also should keep an eye on this comment (pbIJXs-1ew-p2#comment-3437)

**Event tracking**
- When pressing the `Finish setup` button. I'd also track the step already finished, to know better when the button is most clicked.
- We should track every clicked button.
- I would also track the arrows to collapse/uncollapse the task groups.

**Comment by jarekmorawski** [comment]
> The Activity panel is already showing the abbreviated card with the Things to do next. I'm not sure if it's a good idea to show the same thing in two panels.

Can you believe I've never seen it? In that case, there's no point in showing it two places. If possible, we can hide the Finish setup button the moment merchant completes the last task and we show the `Share feedback` popver. I've updated the original issue.

> I'm not clear about this. The panel will be shown even when the user doesn't click on the Finish setup button?

My bad, I meant dismissed, not clicked. 🙈 I've fixed the description. Thanks for bringing this up!

> do we have the images for each group? (I couldn't find them in Figma).

Yes, here they are: G9vi4e286yjdzyIdg8hBb1-fi-942%3A114217.

> How are the groups composed? (Which task is in which group?).

The frame linked above shows all tasks within each section (they're completed, but it should give you the idea). Please note that it's an impossible state for the task list, which brings me to the next answer...

> Is it possible to have multiple groups uncollapsed or only one group will be uncollapsed at a time?

No, only one group can be uncollapsed at a time. When you click to expand another, the previously opened one would collapse. Note, however, that all groups can be collapsed at the same time.

![tasks](https://user-images.githubusercontent.com/79307566/155984743-832b960b-c853-4c67-bb02-67456bbb66f5.gif)

> When the accordion is not collapsed should we continue showing the number of unfinished tasks?

No. The badge's goal is to tell merchants how many tasks are left inside each section.

Let me know if you have any other questions! 👍

**Comment by joelclimbsthings** [comment]
Hey @jarekmorawski , just wanted to confirm as I didn't see it explicitly stated anywhere. Is the intention that when a task is clicked within the side panel, it would be (depending on the task) rendered within the side-panel and completed there as well? 

The alternative would be redirecting to the homescreen when the task would normally be rendered immediately in place of the task list. 

Assuming the former, is there any change in how we would want to handle the back button? Currently it would be rendered on the left side of the screen as it is on the Homescreen, like so: 

![image](https://user-images.githubusercontent.com/444632/168933724-689c04af-79e2-420e-83c6-a6343ce3ffdd.png)

cc @mattsherman

**Comment by jarekmorawski** [comment]
Hey Joel! 👋 

> The alternative would be redirecting to the homescreen when the task would normally be rendered immediately in place of the task list.

I'd prefer this solution since it's simpler and easier to maintain. There can be unexpected layout issues when the internal flows scale down in the drawer, plus some are quite complex and should use a focused, full screen experience.

**Comment by pmcpinto** [comment]
@joelclimbsthings here's a summary of the changes that were discussed yesterday:

- [x] Hide the treatment header in the side panel and emphasize the "follow these steps..." paragraph. I think it will be enough to change the color to #1d2327 and the font-weight. cc @jarekmorawski @verofasulo what do you think?
- [x] Show the "Finish setup" CTA + side panel on all Woo pages. The only exception is the home screen.
- [ ] Tracks:
There's already an event in place to track the "Finish setup" interactions:  `wcadmin_activity_panel_open` - `tab`:`setup`
We just need to add a prop called `screen` to the `wcadmin_tasklist_view` and `wcadmin_tasklist_click` events. This will allow us to understand where the users are interacting with the task list.

- Joel, how much time do you think you need to implement the Finish Setup icon showing the progress? I want to make sure that we don't jeopardize the side panel release with WC 6.7 because of the icon. 

I think this covers everything that was discussed. Thanks

**Comment by verofasulo** [comment]
> Hide the treatment header in the side panel and emphasize the "follow these steps..." paragraph. I think it will be enough to change the color to #1d2327 and the font-weight.

Maybe we can go with something like this? 

![image](https://user-images.githubusercontent.com/98944206/171442298-5c7d59a7-af5f-48b6-a3b0-c57d5a2b9711.png)

G9vi4e286yjdzyIdg8hBb1/%F0%9F%9F%A1-fi-1786%3A159623

**Comment by joelclimbsthings** [comment]
After our call yesterday I went ahead and moved the title exclusively to the Homescreen, and tweaked the font/style of the remaining text on the sidebar:

![image](https://user-images.githubusercontent.com/444632/171486358-bcdd2c0b-6478-4419-bef2-011ac8786db8.png)

Glad to change this further, although so far we _have_ been able to avoid making any direct code changes between the sidebar and homescreen versions, which reduces complexity for maintenance/further changes. So solutions that are just UI tweaks (and not content) have a slight edge in my view :).

**Comment by joelclimbsthings** [comment]
Thanks for the notes @pmcpinto ! I integrated some version of the first two in the previous PR that I merged a short time ago, and I'm opening another for the tracks revisions.

**Comment by joelclimbsthings** [comment]
>Joel, how much time do you think you need to implement the Finish Setup icon showing the progress? I want to make sure that we don't jeopardize the side panel release with WC 6.7 because of the icon.

@pmcpinto If we want to take the pie-slice approach, I'm guessing it wouldn't be more than a 1-2 pointer, although I've had limited experience with programmatically altering SVGs.

**Comment by pmcpinto** [comment]
@joelclimbsthings thanks for the update. Let me know if you have any questions about the Tracks changes. 

> @pmcpinto If we want to take the pie-slice approach, I'm guessing it wouldn't be more than a 1-2 pointer, although I've had limited experience with programmatically altering SVGs.

Feel free to move forward with it, if you think it will be ready in time to be included with 6.7.
