### ISSUE TITLE
Woo Navigation: Category change animation triggered when navigating within a category

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#32213]
### Describe the bug
With the new Woo Navigation, clicking into our out of a category triggers a "slide" animation within the nav. This should only be triggered when changing categories, although I've noticed at least one instance of it being triggered while changing to other screens within the same category.

### To Reproduce

1. Ensure Woo Nav is enabled (WooCommerce -> Settings -> Advanced -> Features -> Check the checkbox next to Navigation)
2. Navigate to Analytics -> Overview 
3. Now, navigate from the Overview to the Analytics -> Products screen
4. Notice the animation within the nav, which shouldn't happen.
5. Navigate from the Products to the Analytics -> Revenue screen.
6. Notice that there is no animation, as is expected.

### Expected behavior

The animation should only be triggered when switching in and out of a category, not within one.

**Comment by chihsuan** [comment]
I've looked into this bug. The root cause is that [they're using different route paths](https://github.com/woocommerce/woocommerce-admin/blob/main/client/layout/controller.js#L76-L144). 

- Overview -> `/analytics/overview`
- Other reports -> `/analytics/:report`

So, when we navigate from the "Overview" to the other Analytics pages, the route path will be changed and it will [re-render the entire layout component](https://github.com/woocommerce/woocommerce-admin/blob/main/client/layout/index.js#L241-L258) along with the navigation animation.

To fix this, I think we might need to redesign the Analytics routes or the layout. It will take more time to plan and fix.

**Comment by joshuatf** [comment]
Good find, @chihsuan.  I think we may want to look at limiting the number of re-renders or in this case, when SlotFill renders.

This problem could happen in other categories outside of Analytics as well once we begin React-ifying more pages and we won't be able to guarantee they're on the same route/path.
