### ISSUE TITLE
Error PHP funcion session_star()

### ISSUE THREAD

**Issue by isacritikian** [woothemes/woocommerce#32388]
Buenas tardes, 

En la pantalla de salud mi WorPress me sale un error crítico que al parecer viene del plugin de WooCommerce y necesitaría solucionarlo. Añado en screenshot el problema en cuestión. 

Se ha creado una sesión PHP por la llamada a la función session_start(). Esto interfiere con la API REST y las solicitudes de retorno. La sesión debería ser cerrada por session_write_close() antes de hacer cualquier solicitud HTTP.
<img width="1159" alt="Captura de pantalla 2022-03-28 a las 16 12 41" src="https://user-images.githubusercontent.com/70335474/160417405-e0871ae3-51d8-4dea-b65c-97c1fed598a1.png">

**Comment by jonathansadowski** [comment]
Hi @isacritikian,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
