### ISSUE TITLE
Setup experiment: Reminder bar should not be shown if coming from a task in the task list

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#32428]
Follow up to #32320 

## User story

As a new merchant
I do not want to be distracted when completing tasks in story setup
So I can do it quickly and easily

## Description

In order to not overwhelm the user and/or lessen the impact of the reminder bar, we don't want to show the reminder bar if the user is in a flow that originated from the task list.

## Acceptance criteria

- [ ] If the current screen was navigated to from a task in the task list (like Add products > Add manually), the reminder bar should not be shown
- [ ] If the current screen was not navigated to from a task in the task list (like Orders), the reminder bar should be shown (all other AC from original story #32161 should be followed still)

**Comment by joelclimbsthings** [comment]
The original PR was meant to capture this requirement, although it looks like we missed a page or two (Product Add/Edit). 

While thinking this over, I just wanted to confirm the requirement. It was [originally worded](https://github.com/woocommerce/woocommerce/issues/32161) as this:

> _Bar doesn't show up in the Home screen and any screen that belongs to the internal task flow (f.e. shipping)_

So we currently have it implemented so that the reminder bar _never_ shows up on a subset of pages that are involved in the task flow. The original implementation missed a page or two as mentioned, but I'm wondering if want more nuance here. It would require a bit more work, but we could make it so that the reminder bar _doesn't_ show on these pages only when they've been navigated to directly from the task list, but it would show otherwise. 

Is that worth considering, or should we just stick with the current implementation? @mattsherman @jarekmorawski

**Comment by mattsherman** [comment]
>  but we could make it so that the reminder bar doesn't show on these pages only when they've been navigated to directly from the task list, but it would show otherwise.

@joelclimbsthings That is exactly how it was intended to be implemented.
