### ISSUE TITLE
Implement order search and filtering in the order listing screen using COT

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#32470]
This would be a continuation of #32385 and scopes adding filtering and search functionality to the order list screen.

These sort and search methods should be implemented in the data store and then used by the list rendering class to display in the UX.

**Comment by barryhughes** [comment]
I think this can be closed, because:

- Filtering was implemented in https://github.com/woocommerce/woocommerce/pull/33789
- Work on search is underway and is encapsulated by:
    - https://github.com/woocommerce/woocommerce/issues/33197
    - https://github.com/woocommerce/woocommerce/issues/34177

I realize this issue pre-dates the others, but it felt cleanest to close this one. Let me know if I'm misread the situation/any concerns!
