### ISSUE TITLE
Task List: Add Products Task - Add event tracking

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#32633]
Event tracking for
- #32634

**Add products**

- Task completion rate
- Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
- % of users that clicks on suggested product types
- % of users that clicks on view more product types
- % of users that clicks on start blank VS start with a template
- % of users that follows the suggested pathway (import products or start with a template) VS follow the secondary one
- List of the most clicked product types

**Acceptance criteria:**

TBD

For import products 👇 
- https://github.com/woocommerce/woocommerce/issues/32811

**Comment by adrianduffell** [comment]
> % of users that clicks on suggested product types

For this type of analytics, there would need to be separate tracks events for views and clicks.

**Comment by chihsuan** [comment]
> To be assessed by the team - some things I'd like to measure:
Task completion rate
Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
% of users that clicks on suggested product types
% of users that clicks on view more product types
% of users that clicks on start blank VS start with a template
% of users that follows the suggested pathway (import products or start with a template) VS follow the secondary one
List of the most clicked product types

Hi @verofasulo @pmcpinto, I've listed the required tracks below for "add products" (We'll have another one for "import products"). Could you confirm if this is okay?

- Task completion rate

   Existing Tracks:

   - `task_view`:  View a single task on the frontend
  
    ```
		task_name: taskId, // experimental-products
		wcs_installed: installedPlugins.includes( 'woocommerce-services' ),
		wcs_active: activePlugins.includes( 'woocommerce-services' ),
		jetpack_installed: installedPlugins.includes( 'jetpack' ),
		jetpack_active: activePlugins.includes( 'jetpack' ),
		jetpack_connected: isJetpackConnected
    ```

   New Tracks:

    a user to select an option and move to the next step

   - `tasklist_add_product_import_csv_click`
   - `tasklist_add_product_template_click`
       - name: product type
       - is_suggested: "yes" / "no" 
  
   - `tasklist_add_product_start_blank_click`
   - `tasklist_add_product_load_sample_products_click`

- Task completion time on average

   New Tracks:

    - `task_completed_time_s`: the amount of time it takes a user to select an option and move to the next step
        - task_name: taskId
        - time: time in seconds

- % of users that clicks on suggested product types

   Existing Tracks:

   - `task_view`:  View a single task on the frontend

   Tracks:

   - `tasklist_add_product_template_click`
       - name: product type
       - is_suggested: "yes" / "no" 

- % of users that clicks on view more product types

   Existing Tracks:

   - `task_view`:  View a single task on the frontend

  New Tracks:

  - `tasklist_add_product_view_more_click`

- % of users that clicks on start blank VS start with a template**

   Existing Tracks:

   - `task_view`:  View a single task on the frontend

  New Tracks:

  - `tasklist_add_product_start_blank_click`
  - `tasklist_add_product_template_click`
       - name: product type
       - is_suggested: "yes" / "no" 

- % of users that follows the suggested pathway (import products or start with a template) VS follow the secondary one

   Existing Tracks:

   - `task_view`:  View a single task on the frontend

  New Tracks:

   - `tasklist_add_product_import_csv_click`
   - `tasklist_add_product_template_click`
       - name: product type
       - is_suggested: "yes" / "no" 
  
   - `tasklist_add_product_start_blank_click`
   - `tasklist_add_product_load_sample_products_click`
   - `tasklist_add_product_3pd_plugin_click`

   Existing Tracks:

   - `task_view`:  View a single task on the frontend

- List of the most clicked product types

  New Tracks:
    
   - `tasklist_add_product_template_click`
       - name: product type
       - is_suggested: "yes" / "no"

**Comment by pmcpinto** [comment]
Hey @chihsuan I think we should leverage what we already have in the current experience and implement it in the new variant:

- `wcadmin_task_view`
Perhaps we should add a new `task_name` value to distinguish the control and the treatment in Tracks. Or include a new prop to distinguish them and fire `task_name`: `products` in both versions (control and treatment)

- `wcadmin_tasklist_task_completed`
No changes are required. It should be fired when the user completes the task using the control or treatment

- `wcadmin_tasklist_add_product`
`method`: 
product_template - fired when one of the template options is selected
manually - fired when the user selects start blank
import - fired when the user selects the import option
migrate - fired when the user selects the migration option
We just need to add one for sample products: sample_products

- `wcadmin_tasklist_product_template_selection`
fired when one of the template options is selected
It's just necessary to add new `product_type` values for grouped and external products

The only new events that need to be implemented are one to track the "view more product types" and the completion time. Let me know if I'm missing anything. Thanks

**Comment by chihsuan** [comment]
@pmcpinto Thanks for confirming! 

> I think we should leverage what we already have in the current experience and implement it in the new variant:

This sounds good! 🙂 

> Perhaps we should add a new task_name value to distinguish the control and the treatment in Tracks. Or include a new prop to distinguish them and fire task_name: products in both versions (control and treatment)

Yes, I think we could do that. I'll check which is easier to implement.

> % of users that clicks on suggested product types

If I’m not mistaken, should we also add a new prop for `wcadmin_tasklist_product_template_selection` to track this? 

- `is_suggested`: "yes" / "no", suggested product types depend on what the user declared during the signup

**Comment by pmcpinto** [comment]
> If I’m not mistaken, should we also add a new prop for wcadmin_tasklist_product_template_selection to track this?
> is_suggested: "yes" / "no", suggested product types depend on what the user declared during the signup

Sounds good! Thanks for the suggestion

**Comment by rjchow** [comment]
> > Perhaps we should add a new task_name value to distinguish the control and the treatment in Tracks. Or include a new prop to distinguish them and fire task_name: products in both versions (control and treatment)
> 
> Yes, I think we could do that. I'll check which is easier to implement.

@chihsuan , I was looking into this and from my understanding the 'products' task id is quite tricky to modify as it is coupled to both the url and the slotfill's ID. [1](https://github.com/woocommerce/woocommerce/blob/c5c1cf438afb54ca96a2ac7d88b7f2557f88a89a/plugins/woocommerce-admin/client/tasks/task.tsx#L48), [2](https://github.com/woocommerce/woocommerce/blob/0d9d463d46ea3002766f35a44b4f25f40813dabd/plugins/woocommerce-admin/client/tasks/fills/experimental-products/index.tsx#L111)

The 'products' task slotfill doesn't seem designed to allow for multiple fills, either - if I try populating the slot with two fills it non-deterministically shows one or the other. 

I don't really have any simple, clean way to resolve this, and none of them involve reusing the existing task_view tracks event - here are my ideas
- Add a new tracks event to the experimental layout
- Move the experimental layout into the same fill as the existing one, so we don't have two fills for one slot that isn't meant for multiple fills, then we can add a tracks event there when we decide which one to render
- Modify the slot to add an extra prop/field - this seems like a hack to me because we're modifying the interface for analytics purposes

What do you think?

**Comment by chihsuan** [comment]
@rjchow 

> I was looking into this and from my understanding the 'products' task id is quite tricky to modify as it is coupled to both the url and the slotfill's ID. [1](https://github.com/woocommerce/woocommerce/blob/c5c1cf438afb54ca96a2ac7d88b7f2557f88a89a/plugins/woocommerce-admin/client/tasks/task.tsx#L48), [2](https://github.com/woocommerce/woocommerce/blob/0d9d463d46ea3002766f35a44b4f25f40813dabd/plugins/woocommerce-admin/client/tasks/fills/experimental-products/index.tsx#L111)

Agree with you. 🙌 

> here are my ideas
> Add a new tracks event to the experimental layout
Move the experimental layout into the same fill as the existing one, so we don't have two fills for one slot that isn't meant for multiple fills, then we can add a tracks event there when we decide which one to render
Modify the slot to add an extra prop/field - this seems like a hack to me because we're modifying the interface for analytics purposes
What do you think?

Good points! I'll take a look and get back to you tomorrow.

I think @moon0326 might also have some ideas on this.

**Comment by moon0326** [comment]
> here are my ideas
Add a new tracks event to the experimental layout
Move the experimental layout into the same fill as the existing one, so we don't have two fills for one slot that isn't meant for multiple fills, then we can add a tracks event there when we decide which one to render
Modify the slot to add an extra prop/field - this seems like a hack to me because we're modifying the interface for analytics purposes
What do you think?

We can create a new task in the backend to render a different I.D. You can see how the backend adds task classes [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L106). I think this is the only way to get a different I.D without refactoring the frontend. Task classes are [here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks). I initialized used this [approach](https://github.com/woocommerce/woocommerce/blob/feature/add-products-task-imports/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L107).

I have mixed feelings about adding an extra prop though. It certainly feels hacky, but it also opens the door for the tasks to customize track props. Instead of accepting just a single prop, what do we think about adding `eventProps` as an object to allow tasks to add/overwrite event props defined in [here](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js#L21)?

```
<WooOnboardingTask.Slot
	id={ id }
        eventProps = {
              task_view: {...}
         }
	fillProps={ { onComplete, query, task } }
/>

// or

<WooOnboardingTask.Slot
	id={ id }
        eventProps = {
              ...
         }
	fillProps={ { onComplete, query, task } }
/>

```

**Comment by chihsuan** [comment]
> Instead of accepting just a single prop, what do we think about adding eventProps as an object to allow tasks to add/overwrite event props defined in [here](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js#L21)?

I like this idea. I think it makes us easier to add customized tracks without changing the code too much.

**Comment by rjchow** [comment]
> > here are my ideas
> > Add a new tracks event to the experimental layout
> > Move the experimental layout into the same fill as the existing one, so we don't have two fills for one slot that isn't meant for multiple fills, then we can add a tracks event there when we decide which one to render
> > Modify the slot to add an extra prop/field - this seems like a hack to me because we're modifying the interface for analytics purposes
> > What do you think?
> 
> We can create a new task in the backend to render a different I.D. You can see how the backend adds task classes [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L106). I think this is the only way to get a different I.D without refactoring the frontend. Task classes are [here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks). I initialized used this [approach](https://github.com/woocommerce/woocommerce/blob/feature/add-products-task-imports/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L107).
> 
> I have mixed feelings about adding an extra prop though. It certainly feels hacky, but it also opens the door for the tasks to customize track props. Instead of accepting just a single prop, what do we think about adding `eventProps` as an object to allow tasks to add/overwrite event props defined in [here](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js#L21)?
> 
> ```
> <WooOnboardingTask.Slot
> 	id={ id }
>         eventProps = {
>               task_view: {...}
>          }
> 	fillProps={ { onComplete, query, task } }
> />
> 
> // or
> 
> <WooOnboardingTask.Slot
> 	id={ id }
>         eventProps = {
>               ...
>          }
> 	fillProps={ { onComplete, query, task } }
> />
> ```

eventProps sounds good to me 😃

**Comment by rjchow** [comment]
Not closed yet, still have more tracks to add
