### ISSUE TITLE
CRITICAL Uncaught TypeError: Argument 1 passed to Pelago\Emogrifier\CssInliner::inlineCss()

### ISSUE THREAD

**Issue by botmiszcz** [woothemes/woocommerce#32978]
Hi, when i want to checkout , on front office its comes:

`Failed to load resource: the server responded with a status of 500 ()   /?wc-ajax=checkout:1 `

I checked status, and i see problem is in class-wc-mail, this is sttatus page:

```
2022-05-12T08:24:40+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to Pelago\Emogrifier\CssInliner::inlineCss() must be of the type string, null given, called in /home/bolchemi/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php on line 570 and defined in /home/bolchemi/public_html/wp-content/plugins/woocommerce/vendor/pelago/emogrifier/src/CssInliner.php:169
Stack trace:
#0 /home/bolchemi/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(570): Pelago\Emogrifier\CssInliner->inlineCss(NULL)
#1 /home/bolchemi/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(658): WC_Email->style_inline('<!DOCTYPE html>...')
#2 /home/bolchemi/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-completed-order.php(69): WC_Email->send('xxx@xxx...', 'Hi xxx xxx...', '<!DOCTYPE html>...', 'Content-Type: t...', Array)
#3 /home/bolchemi/public_html/wp-includes/class-wp-hook.php(307): WC_Email_Customer_Completed_Order->trigger(8626, Object in /home/bolchemi/public_html/wp-content/plugins/woocommerce/vendor/pelago/emogrifier/src/CssInliner.php on line 169
```

Problem started after update woocommerce, what is going on, you have some ideas?

**Comment by sehjad-zerodesigns** [comment]
open plugins/woocommerce/includes/emails/class-wc-email.php
add this code below after line number 565
if($css === null){
    $css = "'';
}

and then try to place order

**Comment by ObliviousHarmony** [comment]
Hi @botmiszcz ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by CyberCr33p** [comment]
I have the same issue in 2 websites

**Comment by dragosstancu** [comment]
The file is here: **/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php**

Search for this line:
**$css_inliner = CssInliner::fromHtml($content)->inlineCss($css);**

Add **''.** to the **$css** variable, to make sure it's not null:

**$css_inliner = CssInliner::fromHtml($content)->inlineCss('' . $css);**

We're not supposed to alter the plugin code, very bad practice.

We're so not ready for PHP 8.0 :)

**Comment by dragosstancu** [comment]
Or better, without tempering with the plugin code:

add_filter('woocommerce_email_styles', 'evs_add_css_to_emails', 9999, 2);
function evs_add_css_to_emails($css, $email) {
    $css .= '';
    return $css;
}
