### ISSUE TITLE
[COT] Properly handle accented characters during migration.

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#33146]
During metadata to metadata migration, if there are accented characters in source data, such as `è`, it's not being copied properly and is being replaced with a `?` character. This issue scopes investigating and fixing this bug.

**Comment by jorgeatorres** [comment]
@vedanshujain: do you have more details on this? I can't seem to reproduce on `trunk`. I might be missing something, though. Is there a particular branch I should be testing with?

Could this maybe be because we're [not setting the charset](https://github.com/woocommerce/woocommerce/blob/13fe9b49707afdb50387bece76d2f588c3f05164/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L821) when creating the COT tables [as we do elsewhere](https://github.com/woocommerce/woocommerce/blob/13fe9b49707afdb50387bece76d2f588c3f05164/plugins/woocommerce/includes/class-wc-install.php#L1021)?

FWIW my `wp_postmeta` table is `utf8mb4` as charset (`uff8mb4_unicode_250_ci` collation) and my COT tables were created with charset `utf8` and collation `utf8_general_ci`.

What are you using or where did you see this being reported?

**Comment by vedanshujain** [comment]
@jorgeatorres this could be the reason, actually. I can't reproduce locally either, let's add a collation then to custom tables as well?

**Comment by jorgeatorres** [comment]
@vedanshujain: submitted #33210 to set the collation. Hopefully that'll take care of this issue.

**Comment by vedanshujain** [comment]
Closing as #33210 was merged, there is a chance that the issue will re-surface since this is a speculative fix, will re-open in that case.
