### ISSUE TITLE
Order confirmation emails stopped sending

### ISSUE THREAD

**Issue by taotravel365** [woothemes/woocommerce#33151]
We used to receive automated order emails after each online sale. These confirmation emails stopped sending. We have email notifications enabled and we have three different email accounts added to receive the confirmation emails, but none of them is receiving any notifications.

**Comment by rwkyyy** [comment]
I have the same issue with two different payment processors; so whatever payment processor is used on different websites, the email confirmation (email tied to processing status) does not go out; Initially I thought it was an issue with the integration from the payment processor, but apparently I have this in two different environments!
I think this should be noted as a critical issue because clients are calling to confirm their orders have been received!

p.s. the new order email for admins, usually gets sent!
