### ISSUE TITLE
Implement the new flow to install and connect WCS in Setting page

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33367]
**User story:**
As a new merchant
I want to focus on the most important setup tasks
So I can review some details later

**Description:**
With Jetpack installed and connected, alongside WCS, we have the opportunity to set things up on the users' behalf, and ask them to review and confirm, rather than start from scratch and think.

**Design overview (with new spotlight component):**
cJQeyyhx9PraQrY3YAtCGM-fi-705%3A80783

**Acceptance Criteria:**

- [ ] Implement the new flow to install and connect WCS.

![159506263-a846740e-b536-4c7f-896f-398d4c2aa238](https://user-images.githubusercontent.com/4344253/172817941-06b27b00-e7cc-4bcc-a271-3fe70e0c18f5.gif)

ref: https://github.com/woocommerce/woocommerce/issues/32318

**Comment by ilyasfoo** [comment]
Since Jetpack's connect-in-place is [removed](https://github.com/Automattic/jetpack/pull/20068), we'll want to use a "Connect" button instead, similar to "Set up tax" task

<img src="https://user-images.githubusercontent.com/3747241/174924210-380899c8-a96b-47df-9f5f-5308dda0c0da.png" width=300>

**Comment by moon0326** [comment]
@woocommerce/ghidorah So the current shipping task has `Set shipping costs` and `Enable shipping label printing` steps, but I don't see them on the gif here.

![Screen Shot 2022-06-21 at 6 53 53 PM](https://user-images.githubusercontent.com/4723145/174926490-f1eb7feb-369d-4910-ac63-09b561b55ee8.jpg)


Are we skipping those two steps?

**Comment by chihsuan** [comment]
> Are we skipping those two steps?

@moon0326 Yup, I think we don't need `Set shipping costs` because they are set automatically in https://github.com/woocommerce/woocommerce/issues/33366. And looks like `Enable shipping label printing` is just renamed to `Install WooCommerce Shipping`. This is a new flow only for the setting page. 

cJQeyyhx9PraQrY3YAtCGM-fi-887%3A116590

**Comment by moon0326** [comment]
> > Are we skipping those two steps?
> 
> @moon0326 Yup, I think we don't need `Set shipping costs` because they are set automatically in #33366. And looks like `Enable shipping label printing` is just renamed to `Install WooCommerce Shipping`. This is a new flow only for the setting page.
> 
> [cJQeyyhx9PraQrY3YAtCGM-fi-887%3A116590](https://href.li/?https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/?node-id=887%3A116590)

Nice! It sounds like we might want to create a new component in that case. The logic in the shipping task is now getting complicated with multiple extra fields and conditions 🤔

**Comment by ilyasfoo** [comment]
Hi, @verofasulo 

I noticed in the design, there's no mention of installing JP. AFAIK, we'll need to install JP in order to connect a site. In the tax task, the task description goes `Jetpack and WooCommerce Tax allow you to automate sales tax calculations`. Should we add JP to our task description as well?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/3747241/175278333-d5a36d07-f5a0-4d79-a7fb-8f0ee7afccb9.png">


cJQeyyhx9PraQrY3YAtCGM-fi-887%3A116590

**Comment by verofasulo** [comment]
Hi @ilyasfoo !

I think we install JP in the third step "Connect your store", right? Or while installing WooCommerce Shipping? Thanks :)

**Comment by ilyasfoo** [comment]
@verofasulo In other similar tasks, JP is installed in the 2nd step together with WCS. I'm assuming we'd want to follow the same flow, since we could also re-use most logic that's established.

Anyway, this is how it's looking like right now, can you confirm if it's alright:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/3747241/175508445-d4c88310-6ab0-4e47-9c90-6460d75abccb.png">

Thanks!

**Comment by verofasulo** [comment]
Hi @ilyasfoo , it looks great 🤩

Just a tiny thing: could you please wrap the "by installing ..." line? I think it's a bit weird to have it close to the button on the right side. Thank you 🤗
