### ISSUE TITLE
Tracks: add block editor prop to the wcadmin_product_add_publish event

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#33406]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Add `isBlockEditor ` property to the `wcadmin_product_add_publish` event
see https://github.com/woocommerce/woocommerce/pull/33321 for context

**Comment by octaedro** [comment]
It looks like the block editor [is not compatible with the product](https://github.com/woocommerce/woocommerce/pull/19543) page. The [plugin Blooms](https://woocommerce.com/products/blooms/) overrides [this check](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-post-types.php#L654-L663) and activates it.

The problem with the block editor here is that it doesn't trigger the action `wp_after_insert_post` after publishing a product.  

That hook should be [fired after a post, its terms, and metadata have been saved](https://developer.wordpress.org/reference/hooks/wp_after_insert_post/), but that is not happening here (probably because of some incompatibilities). As a side effect, we are not able to track the product creation using the block editor, since [we're using the hook to track that event](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L24).

I couldn't find any other plugin overriding [that check](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-post-types.php#L654-L663). @AnnaMag what do you think about closing this issue now and reopening it later after having full compatibility between products and the Gutenberg editor?

**Comment by AnnaMag** [comment]
Thanks for diving into this @octaedro!
Sounds reasonable. I think [adding block editor tracking to` _product_update` event](https://github.com/woocommerce/woocommerce/pull/33321) is a fair enough proxy to gauge its usage, and we can come back to this at later stage.
