### ISSUE TITLE
Product creation experience: streamline the creation of the first variation

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33551]
**Description:** creating the first variation is a convoluted experience, forcing the user to jump back and forth between attributes and variations, apart from having to understand the difference between the two concepts.

**Acceptance criteria:**

- [ ] No added attributes with the "Used for variations" setting checked: show the "add attribute" form in the Variations tab along with a welcome/helper message. Ideally,  tweak the field names to make it seem like people are creating an actual variation, rather than an attribute (it'd be confusing to mix these mental models)
- [x] If there are attributes with "Used for variations" checked: automatically show them in Variations, rather than force people to add them manually (addressed on [#35807](https://github.com/woocommerce/woocommerce/pull/35807))

**Comment by AnnaMag** [comment]
For porter role, it is ok work on one point at a time/in a given week.

**Comment by octaedro** [comment]
Hey @pmcpinto,

I'm working on this issue. I have a [PR ready for review here](https://github.com/woocommerce/woocommerce/pull/35807), to automatically show the attributes in Variations.

I wanted to ask you about the following points

> No added attributes with the "Used for variations" setting checked: show the "add attribute" form in the Variations tab along with a welcome/helper message.

Now we're showing the message: `Before you can add a variation you need to add some variation attributes on the Attributes tab.`

![Screenshot 2022-12-01 at 16 07 56](https://user-images.githubusercontent.com/1314156/205141685-8c5e26f4-468b-4caa-8872-1340ed931119.png)

Should we change that message? What should we say there?

>  Ideally, tweak the field names to make it seem like people are creating an actual variation, rather than an attribute (it'd be confusing to mix these mental models)

What texts should we use here?

**Comment by jarekmorawski** [comment]
Hi Fernando! 👋 

> Should we change that message? What should we say there?

We should change this message to:

> Offer customers multiple product options, like size and color. Start by creating a new variation attribute and enter available values (they’ll be shown as selectable product options). Learn more about creating variations

`Learn more about creating variations` links to [this doc page](https://woocommerce.com/document/variable-product/).

Then, below the message, we should show the new attribute form from the `Attributes` tab (we want to create a bridge between attributes and variations). The only difference is that the `Used for variations` box would be checked and disabled (because attributes used for variations required that). When the user clicks `Create variations`, we'd generate them and display the existing UI for managing their details.

The newly created variation attribute would be added under `Attributes` (there, users will be able to uncheck the `Used for variation` box just like they can for any other attribute).

Here's the design (`6cBYbZmiet1l7gzc28ce8k-fi-4154%3A152641&t=tlKB4btl5qyUaFQF-4`):

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/79307566/205358205-5f33db27-2a53-4967-afab-3015b0528af5.png">

**Comment by pmcpinto** [comment]
@jarekmorawski I think we should call it "custom product attribute" to keep it consistent with what we have in the attributes tab. Also, "variation name" can be confusing, because the user is creating an attribute and not a variation.

**Comment by jarekmorawski** [comment]
Good call! Updated the design. ✅

**Comment by pmcpinto** [comment]
Hey @octaedro, I've just tested what was implemented in #35807 and I think we should revert this implementation until we fix the following:
- We don't inform the user that we only create 50 variations at a time
- We don't have a loading state for when the variations are being created

This can lead to a confusing experience and generate user dissatisfaction. See this example where the variations are auto-created based on 3 attributes with a couple of values per attribute:  
https://user-images.githubusercontent.com/3380168/209570830-d05fe64c-227b-46d4-b988-aa2158bcef33.mp4

Let me know if you have any questions. Thanks

**Comment by octaedro** [comment]
Nice catch @pmcpinto!
I think that @mdperez86 is the porter this week, could you take a look at [Pedro's comment](https://github.com/woocommerce/woocommerce/issues/33551#issuecomment-1365292130)?

**Comment by AnnaMag** [comment]
@mdperez86 let's revert it and create an issue with the changes @pmcpinto suggested. Thank you!

**Comment by mdperez86** [comment]
Revert thread -> p6q8Tx-2sh-p2#comment-6501

**Comment by jarekmorawski** [comment]
Seems like this issue has already been solved. Closing for now. We can revisit it in the future if needed.
