### ISSUE TITLE
Product creation experience: improve the visibility of system status when users change product type

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33562]
**Description:** it's difficult to understand which fields or sections are being added or removed from the post data widget, as there's no indication of what happens when, for example, the user changes the product type from simple to grouped product. 

**Acceptance criteria:**

- [ ] When new product elements appear, for example for downloadable or external products, show a spotlight to point people to the place where they'll find new options

**Comment by louwie17** [comment]
Some additional questions:
- Did we want to make use of the new tour kit for this?
<img width="1261" alt="Screen Shot 2022-10-19 at 4 52 42 PM" src="https://user-images.githubusercontent.com/2240960/196790434-293a2176-7950-471f-909d-6534d8e019ee.png">
- Do we only want to show this to users when the `tutorial=true` query param is added (this currently triggers the tour kit, as shown in the picture above), or show this to a user every time they switch product types? I have a feeling that a user might get annoyed if we switch every-time.

Some thoughts on what to highlight for each product type:
Downloadable:
- The downloadable section ( Downloadable Files, Download limit, Download expiry )
External:
- The Product URL and button text (in the General tab)
Grouped product:
- Maybe auto open the **Linked Products** tab and highlight Grouped products.
- Instead of auto opening the tab we could also just highlight the tab.
Variable products:
- Maybe auto open the **Variations** tab and highlight the notice on top (that points back to Attributes, this might be kinda strange).
- Instead of auto opening the tab we could also just highlight the tab.

**Comment by pmcpinto** [comment]
Now that I think about it again, showing the guide might be too much. What if we include this information in the product type tooltip? For example, "fields like price will be defined at the variation level". 

@jarekmorawski what do you think?

**Comment by mdperez86** [comment]
@pmcpinto and @jarekmorawski do we have any conclusion of this?

**Comment by jarekmorawski** [comment]
I still think we should use a spotlight because in many cases even that is not enough to educate users who usually skim over the helper texts.

> Did we want to make use of the new tour kit for this?

Yes!

> Do we only want to show this to users when the `tutorial=true` query param is added

Only after the user changes the product type for the first time. Do we have a list of all possible change combinations that need copy?

**Comment by mattsherman** [comment]
@pmcpinto @mdperez86 @jarekmorawski  Moved this back to "Prioritization", because it clearly isn't ready to the picked up and implemented.

**Comment by pmcpinto** [comment]
> I still think we should use a spotlight because in many cases even that is not enough to educate users who usually skim over the helper texts.

@jarekmorawski don't you think it will be a convoluted experience if they change types several times?
