### ISSUE TITLE
Review usage of wc_get_product() in Product Attributes Lookup

### ISSUE THREAD

**Issue by anant1811** [woothemes/woocommerce#33730]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For Product Attributes Lookup, we are using wc_get_product(), which can return false, but we are not checking for that possibility. 

Location: `plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php`

### Expected behavior

Review what happens when wc_get_product() returns false. 

### Actual behavior

We are not checking for the possibility when wc_get_product() returns false.

### Steps to reproduce

Review the code in `plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php`

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
✍🏽 Internal ref p1656703027577569-slack-C7U3Y3VMY

A fatal error related to the above was taking place once per day:

```
2022-07-01T09:49:31+00:00 CRITICAL Uncaught TypeError: 
Argument 1 passed to Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore::get_attribute_taxonomies()
must be an instance of WC_Product, bool given.
```

**Comment by nixiack** [comment]
full error, still occuring 1x per day:

```
2022-07-06T15:12:08+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore::get_attribute_taxonomies() must be an instance of WC_Product, bool given, called in /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php on line 454 and defined in /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php:592
Stack trace:
#0 /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php(454): Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore->get_attribute_taxonomies()
#1 /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php(359): Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore->create_data_for_variation()
#2 /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php(237): Auto in /var/www/webroot/ROOT/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php on line 592
```

**Comment by RickardAhlstedt** [comment]
I'm having the same problem

```
unexpected shutdown: PHP Fatal error Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore::insert_lookup_table_data_for_variation() must be an instance of WC_Product_Variation, bool given, called in /srv/users/client/apps/client/public/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php on line 441 and defined in /srv/users/client/apps/client/public/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php:478
Stack trace: 
#0 /srv/users/client/apps/client/public/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php(441): Automattic\WooCommerce\Internal\ProductAttributesLookup\LookupDataStore->insert_lookup_table_data_for_variation(false, 'pa_color', 221748, Array, Array) 
#1 /srv/users/client/apps/client/public/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php(361): Automattic\WooCommerce\Internal\Product in /srv/users/client/apps/client/public/wp-content/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php on line 478
```
Running WC 6.8.2

When can we expect this to be fixed? as of now we can't run any filtering on the website which has over 40k products..

**Comment by phatanha** [comment]
I have also this problem.
Looking forward to hearing from you

**Comment by RickardAhlstedt** [comment]
Any updates on this issue?

**Comment by seanbelly** [comment]
Internal ref: zd-5338547

**Comment by RickardAhlstedt** [comment]
Any news?

**Comment by Konamiman** [comment]
Hi @anant1811, @nixiack, @Dronki, @phatanha: sorry for the late reply, I implemented the product attributes lokup feature and I'll try to fix this issue. However so far I've been unable to reproduce it, and I don't think blindly attempting to release a fix would be a good idea.

Therefore, may I ask to please provide more details about you environment? Specifically:

1. Do you have the "Direct updates" setting for the lookup table turned on? (WooCommerce - Settings - Products - Advanced).
2. Do you see failed scheduled actions related to the lookup table update? (WooCommerce - Status - Scheduled Actions - Failed, hook name `woocommerce_run_product_attribute_lookup_update_callback`)
3. Did the errors start to appear after performing some specific action related to variable products? (e.g. trashing or deleting a product)

...or anything else you think might be relevant. Thank you!

**Comment by RickardAhlstedt** [comment]
@Konamiman 
>     1. Do you have the "Direct updates" setting for the lookup table turned on? (WooCommerce - Settings - Products - Advanced).
Unable to see as the queue is still trying to process, but I would assume so since we're running external systems with the shop.
>     2. Do you see failed scheduled actions related to the lookup table update? (WooCommerce - Status - Scheduled Actions - Failed, hook name `woocommerce_run_product_attribute_lookup_update_callback`)
Yes, one day before I posted on this issue, i.e 6/9-22, 92 failed events
>     3. Did the errors start to appear after performing some specific action related to variable products? (e.g. trashing or deleting a product)
Starting to fail after updating to 6.8.2 (I know, the shop is intentionally kept at a lower version since its delicate)

**Comment by Konamiman** [comment]
Thanks @Dronki, some more questions:

> Yes, one day before I posted on this issue, i.e 6/9-22, 92 failed events

There should be an "Arguments" column next to the action status showing something like `0 => 1234, 1 => 2`:

![image](https://user-images.githubusercontent.com/937723/228554057-90ede8dd-c723-4ec4-9c66-528b2eef4a17.png)

What does it display? Is it the same for all the failed actions?

Context: the value for `0 =>` is the id of the affected product (presumably it's a variation for which the parent product doesn't exist anymore, that's what I'd like to confirm) and `1 =>` is the action to be performed (1=insert, 2=update, 3=delete).

> Starting to fail after updating to 6.8.2

What version had you updated from? Have you updated WooCommerce again since then?

**Comment by RickardAhlstedt** [comment]
No problem @Konamiman 
> What does it display? Is it the same for all the failed actions?

It hovers around the following value for the first argument: `0 => 333570` up to `349083`
`1 => 1` on all of them.

> What version had you updated from? Have you updated WooCommerce again since then?

If I remember correctly the site went from 5.9.x to 6.8.2, we're keeping the site on a lower version since the site is quite delicate to upgrades, and thus easily breaks when updating. (usually taking a few hours to get it working again)

**Comment by Konamiman** [comment]
Thanks @Dronki, I'd need one more thing. Are you able to run SQL queries on the site? I'd like to know if somehow these product ids correspond to "orphan" variations in the database:

```
select id,post_type,post_status,post_parent from wp_posts p where post_type like 'product%' and post_parent!=0 and not exists (select id from wp_posts x where x.id=p.post_parent) limit 50
```

**Comment by seldimi** [comment]
I can't help to reproduce, but I have facing this issue a lot when trying to have active the "Update the table directly upon product changes, instead of scheduling a deferred update." and using external scripts that use CRUD system to create/update products.

And it mostly happens when you load with wc_get_product and update WC_Product_Variation() or WC_Product().

Adding the check if its instance of WC_Product or bool, would help

**Comment by seldimi** [comment]
Doing a deeper research,  I have seen that on my database I've found a post of product_variation with post_parent = 0. So on LookupDataStore.php, line #283  ($this->create_data_for_variation( $product )) has a product, but #376 failed as $variation->get_parent_id = 0, so $main_product = 0.

SO checking my code, the issue happens WHEN

```
$product = new WC_Product_Variable();
$product->set_name("test variable");

if ($product->is_type('variable')) {
     $variation_attributes=[];
     $variation_attributes[wc_attribute_taxonomy_name('Size')]="XL";
     $variation->set_parent_id($parent->get_id());
     $variation->set_attributes($variation_attributes);

     $variation->save();
     $parent->save();
}
```

A variable product is created via CRUD (doesn't have ID yet), and a Variation object is created and saved. On  $variation->save();, product_attribute_lookup is triggered, but this variation has 0 parent_id, and it sends the fatal error.

**Comment by RickardAhlstedt** [comment]
> Thanks @Dronki, I'd need one more thing. Are you able to run SQL queries on the site? I'd like to know if somehow these product ids correspond to "orphan" variations in the database:
> 
> ```
> select id,post_type,post_status,post_parent from wp_posts p where post_type like 'product%' and post_parent!=0 and not exists (select id from wp_posts x where x.id=p.post_parent) limit 50
> ```

Sorry for the delayed response.  
Returned 0 rows from the database.

**Comment by Konamiman** [comment]
Hi @seldimi, thanks for your code example, it's really useful.

So I see two things here:

1. Yes, a check for product or bool is needed in the WooCommerce code that gets the parent id of a variation. But:
2. Your code isn't correct because it will lead to the creation of variations with no parent id created, right? Or am I missing something?

**Comment by seldimi** [comment]
```
<?php
require_once 'wp-load.php';
$product = new WC_Product_Variable();
$product->set_name("test variable");

if ($product->is_type('variable')) {
    $variation=new WC_Product_Variation();
    $variation_attributes=[];
    $variation_attributes[wc_attribute_taxonomy_name('Size')]="XL";
    $variation->set_parent_id($product->get_id());
    $variation->set_attributes($variation_attributes);

    $variation->save();
    $product->save();
}
```

OK fixed my code so someone can run in on a staging environment. 

Yes, it will create a product variation on wp_posts (orphan) and then a product variable without variations.  Though it doesn't bring any fatal error
If we have "Update the table directly upon product changes, instead of scheduling a deferred update" it will bring the fatal error

**Comment by seldimi** [comment]
Yes, it will create a WC_Product_Variation object with no parent (Orphan) and a WC_Product_Variable without children.
But it wont break/give any fatal.

**Comment by Konamiman** [comment]
> Yes, it will create a WC_Product_Variation object with no parent (Orphan) and a WC_Product_Variable without children.
> But it wont break/give any fatal.

Of course! I just wanted to double check if creating a variation without parent order was somehow a legitimate use case. It seems it's not, but indeed, no errors should be thrown when that happens.

At least now I have a way to reproduce the issue, thank you!

**Comment by seldimi** [comment]
Hello
Any updates on this one ?
