### ISSUE TITLE
[Enhancement]: Let unit tests run independently of ESLint failures

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#33757]
### Describe the solution you'd like

At present, an ESLint error will stop PHP unit tests from running (in CI, but it is not an issue locally). Example:

- https://github.com/woocommerce/woocommerce/pull/33756
- https://github.com/woocommerce/woocommerce/runs/7219123396?check_suite_focus=true

*If possible,* it would be great to let PHP tests run anyway and contain the ESLint failures as a separate check.

### Additional context

See also https://github.com/woocommerce/woocommerce/issues/33758

**Comment by samueljseay** [comment]
@barryhughes I don't think this is relevant anymore right?

We have JS lint and JS test together (which certainly we could argue to separate) but eslint and PHP unit tests are separate.

**Comment by barryhughes** [comment]
Hi @samueljseay,

I'm a little unsure. It's not as clear as it was when I tested this in the past, but in https://github.com/woocommerce/woocommerce/pull/39738 (freshly branched from trunk) I replicated the same change as before (which won't pass ESLint checks) and, it seems, various checks including unit tests [now won't run](https://github.com/woocommerce/woocommerce/actions/runs/5858853682/job/15883637550?pr=39738). 

I haven't really parsed the output in detail, so perhaps this is the result of some other problem, but it seems there *may* still be an issue here.

**Comment by samueljseay** [comment]
@barryhughes yep thats another problem. When "monorepo setup" fails it will fail many tasks because its a first step in running a lot of CI checks (we're working on improving that).

I am about to merge https://github.com/woocommerce/woocommerce/pull/39704 anyway, which gives separation of JS lint and test and adds the annotation you asked for so I'll close this on merging that PR, and let me know how it goes.

In the meantime, I'll have a look at this issue you're seeing in https://github.com/woocommerce/woocommerce/pull/39738
