### ISSUE TITLE
Move `plugins/woocommerce-admin/client` Into `plugins/woocommerce/client/admin`

### ISSUE THREAD

**Issue by ObliviousHarmony** [woothemes/woocommerce#33949]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As the last step towards merging WooCommerce Admin, we should fold the admin client into the plugin's directory. Hopefully, all this will include is updating paths.

**Comment by samueljseay** [comment]
I'm not sure if this is registered as a task but there seems like a secondary problem after doing this work.

Much of the scripting/build etc for `@woocommerce/*` is in the admin package. that feels completely wrong, and I think we need to move that work into the respective JS packages so that the webpack config for admin just builds admin and not the packages/js/*

cc @psealock

**Comment by psealock** [comment]
That's a good call @samueljseay. I created this issue to track that task, https://github.com/woocommerce/woocommerce/issues/34918

I think this kind of discovery was intended as part of https://github.com/woocommerce/woocommerce/issues/33947

**Comment by ObliviousHarmony** [comment]
Closing this in favor of new issues as an output from a larger project to complete the merge.
