### ISSUE TITLE
Implement `maxFailures` in E2E tests to limit failures and size of Allure reports

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#34044]
### Describe the solution you'd like

Currently, E2E test runs that have too many failures generate huge Allure test reports, and take a very long time to complete like so:

![Screen Shot 2022-07-19 at 8 23 47 PM](https://user-images.githubusercontent.com/4509348/180435942-d8167e45-db38-4f7e-93cf-c039b089f91c.png)

To address this, we can use Playwright's [`maxFailures`](https://playwright.dev/docs/api/class-testconfig#test-config-max-failures) configuration to implement a fail-fast mechanism to save time on testing a faulty build, and to prevent the Allure reports from getting huge.

**Comment by lanej0** [comment]
This sounds like a great idea.  

I think that the work @Luc45 did with reducing flakiness during `global-setup` should also help a lot here -- that number of failures is 99.9% of the time caused by something going sideways during the setup.  He has the setup retrying a few times, and if setup fails, the [test run is aborted altogether](https://github.com/woocommerce/woocommerce/pull/34004/files#diff-8176eca35e7b44ceda29c5aa8467abd1f6b35367e37db05263df45bb7b46454dR77) (line 77 of global-setup.js).
