### ISSUE TITLE
My Account > Orders title - plural missmatch

### ISSUE THREAD

**Issue by R33D3M33R** [woothemes/woocommerce#34300]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Dear developers, I have found a translation bug in My Account menu item.

### Expected behavior

In [wc-account-functions.php:100](https://github.com/woocommerce/woocommerce/blob/6a95d3ee938ec4e5ab9e3c7c979032a55ebb1a1a/plugins/woocommerce/includes/wc-account-functions.php#L100) the function used to fetch the translations is __() which means that it should receive a single translation, but this is in conflict with the .POT file.

### Actual behavior

The .POT created from this line is marked as plural and any translators that follow the specification will have wrong translations, because the function will fetch the singular value.

### Steps to reproduce

/

### WordPress Environment

Present in the current trunk version of WooCommerce

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Hi @R33D3M33R,

I'm not sure I understand the problem (and, it seems `Orders` is correctly translated—in the context of the My Account menu—so long as the active translation includes that string).

Can you clarify what you want to see, here?

**Comment by R33D3M33R** [comment]
Hi @barryhughes,

the problem is in the way the translations are extracted.

How the string should have been extracted:

```
msgid "Orders"
msgstr ""
```


How it's currently extracted:

```
msgid "Orders"
msgid_plural "Orders"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""
```

If you translate this the proper way, code on line 100 will use msgstr[0] - singular and wrong. Some translators (like the DE team) use workarounds and put plural forms in msgstr[0], but it would definitely be better to fix the extraction process. 

Best regards,
Andrej

**Comment by barryhughes** [comment]
Can you confirm where you see this? Though it's perhaps not a big difference, what I see [in our latest release](https://plugins.svn.wordpress.org/woocommerce/tags/6.8.2/i18n/languages/woocommerce.pot) is this (only two message strings, rather than four):

```
msgid "Order"
msgid_plural "Orders"
msgstr[0] ""
msgstr[1] ""
```

I'd also note that we aren't doing anything special-to-WooCommerce in terms of how we build the `.pot` file. For example, if I have a plugin containing the following code (this is essentially a simplification of what WooCommerce does, in relation to the strings 'Order' and 'Orders'):

```php
function a() {
	__( 'Dolphin', 'test' );
}

function b() {
	_n( 'Dolphin', 'Dolphins', 2, 'test' );
}
```

And I run `wp i18n make-pot` for that plugin, the resulting file includes:

```
msgid "Dolphin"
msgid_plural "Dolphins"
msgstr[0] ""
msgstr[1] ""
```

This makes sense to me, and it matches what we see in the case of WooCommerce. You've described how you believe the strings *should* be extracted, but what I'm not understanding is the problem the current approach creates for you as a translator. Can you confirm?

**Comment by R33D3M33R** [comment]
Hi, the first example is only one of the "Orders" strings in the file. The second one is in line 11038, where it says:

```
msgid "Orders"
msgid_plural "Orders"
msgstr[0] ""
msgstr[1] ""
```

In [some languages](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) you then get msgstr[2] and msgstr[3].

Here how the DE team translated this:

```
msgid "Orders"
msgid_plural "Orders"
msgstr[0] "Bestellungen"
msgstr[1] ""
```

If they would translate this in the proper way (Plural-Forms: nplurals=2; plural=n != 1):

```
msgid "Orders"
msgid_plural "Orders"
msgstr[0] "Bestellung"
msgstr[1] "Bestellungen"
```

The translation would be wrong. I hope it's clear now.

**Comment by barryhughes** [comment]
Understood now, thank you for persevering!

@woocommerce/atlas do you have thoughts on this—is it possible to look at our tooling in this area?
