### ISSUE TITLE
Featured image not showing at Woocommerce product (URL)

### ISSUE THREAD

**Issue by markmettler** [woothemes/woocommerce#34390]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I set an product image to a product, I also want to be that image a featured image. So when I send the link(URL) of the product also the product image is displaying in that link. 

For some reason the link is showing the logo of the website instead of the product image. 

### Expected behavior

For some reason the link(URL) is showing the logo of the website instead of the product image. 

### Actual behavior

For some reason the link(URL) is showing the logo of the website. 

### Steps to reproduce

Just added an image to the product. Sending the link (on whatsapp for instance) and hoping the image of the product will showing with that link instead of the logo of the website. But that does not happening. 

### WordPress Environment

Wordpress: 6.0.1 (with all updates done)
PHP 7.4

Theme: Mesmerize

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by joelclimbsthings** [comment]
Thanks @markmettler !

I assume when you're referring to the link you mean the direct product link? Something like this: 
`https://public-woocommerce-site.com/product/rustic-linen-gloves/`

And then you expect the image preview shown in chat application and otherwise to be the image of the product? 

My understanding is that this preview is generated with a series of meta tags, such as `og:image` that points towards the image to be used. I actually don't believe these are generated at all by default with WooCommerce product pages, so perhaps you're seeing something generated by a plugin such as Yoast?

If that's the case you may need to direct your question to them.
