### ISSUE TITLE
Live Branches: Create webhook on build to notify Jetpack's Beta Download

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#34523]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

A pull request kicks off a workflow to build an artifact of WooCommerce. After this has run, create a job that ping's Jetpack's Beta Download with metadata about the build.

Beta Download will grab the build and add it to its manifest.

Here is an example of Jetpack's job

https://github.com/Automattic/jetpack/blob/53d99a9ae0a67f86dfb401cad8b9b4525d7d8a74/.github/workflows/build.yml#L269-L281

Here is an example of Jetpack's manifest https://betadownload.jetpack.me/jetpack-branches.json

The beta download should be already configured to accept multiple plugins, see https://github.com/Automattic/jetpack-builder/pull/18 for background there. 

- [ ] Create hook to ping beta download
- [ ] Ensure builds are added to a WooCommerce manifest
- [ ] Ensure a build is removed from the manifest once the pull request is merged or closed

**Comment by samueljseay** [comment]
Since I am about to go on leave, I will do some handover for where I'm up to so far.

Please see my branch to see progress: https://github.com/woocommerce/woocommerce/compare/dev/live-branches-ui?expand=1

I've setup a new page for live branches, I've set up TypeScript tooling and webpack tooling to build the additional JS assets.

I've used Emotion for styling since its what is used in `@wordpress/components` and makes the styling solution really easy.

Prettier is not yet setup correctly afaict, so you'll need to fix that at some point.

Here is where I render basic information about each live branch: https://github.com/woocommerce/woocommerce/blob/8dd991c2d07829f786a78c2e9bcdfe5e6a7ce09a/plugins/woocommerce-beta-tester/src/live-branches/components/BranchList.tsx#L9

So next steps will be to write the code that takes the `download_url`, download the `zip` and install that as the WooCommerce plugin. Right now I'm using Jetpack data so to properly test this you're gonna need to have done the work to generate zips for pull requests before you can do it properly.

For now you could just test by installing Jetpack ZIP files until thats ready.

**Comment by jonathansadowski** [comment]
Make some progress on the manifest... pretty sure I have it working in #35344, or at least I see the build for that PR showing up in https://betadownload.jetpack.me/woocommerce-branches.json

I have some things to clean up and need to update the PR with testing instructions, etc, but hopefully having some values in the manifest file unblocks other things
