### ISSUE TITLE
Slides overlap with each other in the Marketing Slider

### ISSUE THREAD

**Issue by aezazs-multidots** [woothemes/woocommerce#34602]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the backend of the site, when we slide the marketing slider next and then the preview slide, then the slides overlap with each other.

To understand the issue better, I have added the link to the video recording below.

[https://share.cleanshot.com/tN3UlvSs2PsndzXHCTWy](https://share.cleanshot.com/tN3UlvSs2PsndzXHCTWy)

### Expected behavior

When we slide the marketing slider next and then the preview slide, then the slides **do not overlap** with each other.

### Actual behavior

When we slide the marketing slider next and then the preview slide, then the slides **overlap** with each other.

### Steps to reproduce

1. Go to the backend of the site
2. Go to "Marketing" page

### WordPress Environment

WooCommerce Version: 6.8.2
WordPress version: 6.0.2

PC
Mac OS: Version 12.4
Google Chrome: Version 103.0.5060.114 (Official Build) (arm64)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @aezazs-multidots,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.8.2 version and WordPress 6.0.2 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/189055935-e6a98f3b-fcad-4b2e-9a8f-7263dc8f466d.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by aezazs-multidots** [comment]
Hello @swatipawarGS 

Can you tell me what the progress status of this ticket is?

Thank you in advance.

**Comment by eason9487** [comment]
## Recap

After #37430, only the Marketing Coupon page uses the [`KnowledgeBase` component](https://github.com/woocommerce/woocommerce/blob/38d0081fab438193c947fdeedaf029eeb425a7e3/plugins/woocommerce-admin/client/marketing/coupons/index.js#L39-L45).

This issue happens in both sliding directions and can be observed more clearly by slowing down the transition duration to 1 second.

https://github.com/woocommerce/woocommerce/assets/17420811/744b90e8-ad39-44df-9c08-e663eb5fac95

## Developer feedback

The root cause is [the CSS property `transition`](https://github.com/woocommerce/woocommerce/blob/38d0081fab438193c947fdeedaf029eeb425a7e3/plugins/woocommerce-admin/client/marketing/coupons/slider/style.scss#L16-L20) was placed under `.woocommerce-marketing-slider__slide` class, but [the doc of `CSSTransition`](https://reactcommunity.org/react-transition-group/css-transition) suggests placing it under `*-active` classes:

> `*-active` classes represent which styles you want to animate **to**, so it's important to add `transition` declaration only to them, otherwise transitions might not behave as intended!

I will open a PR to fix it.
