### ISSUE TITLE
[Shipping] Shipping class dropdown add new option

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#34657]
**User story**

- As a merchant, I want to the ability to create new shipping classes within the product edit screen.

**Design**
(design: `5sAIeTRd9Yp7nSCT33BAWz-fi-6590%3A287898`)

**Acceptance criteria**

- [x] A new `New shipping class` option should be added to the dropdown
- [x] When the New shipping class option is selected, we show a modal where the user can enter the name, slug, and description 
- [x] The name and slug are automatically populated based on the first added product category. For example, if the product is added to `Shirts`, the class’s name and slug will be `Shirts`.
- [x] If the product doesn’t have any categories yet, the name and slug are respectively populated with `New shipping class` and `new-shipping-class`.
- [x] When created, the name of the new shipping class appears in the dropdown.

**Comment by mdperez86** [comment]
@jarekmorawski , @pmcpinto the new `New shipping class` option will be added to the list when there are no other classes or always?

If always: Since this is a dropdown with autocompletion feat, what are we plan to do with that? 
- The new option should always be shown no matter the text the user is typing?
- At the top or bottom of the dropdown menulist?
- We should show the new option the first time the user focus the dropdown and after start typing the option will be filtered as well as the rest of classes?

**Comment by pmcpinto** [comment]
I think we should keep it simple in the MVP and just display the option when there are no classes. @jarekmorawski what do you think?

**Comment by jarekmorawski** [comment]
If the effort to make the option available at all times is too great, we can skip it for the MVP. I'd vote for having it there, though, because 1) it's very useful 2) we might forget about it during the later stages of development.

> The new option should always be shown no matter the text the user is typing?

No. If the user is typing, we should only display the search results. When the user removes the query, we can show the full list with the `Add new` option. Out of curiosity, how are you planning to build this dropdown, @mdperez86? Does the vanilla `<select>` element support autocomplete? Why do we want it in the first place? Does an average store have many shipping classes? 🤔 cc @pmcpinto 

If we will do a custom dropdown, we could make a few tweaks to customize the experience. For example, if the user starts typing and we can't find a match, we'd show the `Create [query]` option letting them create such a class.

> At the top or bottom of the dropdown menulist?

At the bottom, it should be the last item. Alternatively, it could be fixed at the bottom of the list so that the user always sees the option as they scroll up and down.

> We should show the new option the first time the user focus the dropdown and after start typing the option will be filtered as well as the rest of classes?

If no classes are added in settings, the user should see `No shipping class` (pre-selected) and `New shipping class`. The focus should be on the first option. If some classes exist already, they should be displayed first (before `No shipping class` and `New shipping class`), and the focus should be on the first available class.

**Comment by mdperez86** [comment]
@jarekmorawski for the MVP we are using the native select so we can show at all times the `Add new shipping class` options. We suggest to use an autocomplete dropdown for performance reasons but only if we can validate the hypothesis you mentioned about what is the avg amount of shipping classes the users create. If that it's not a big deal and also if you don't want to enhance the experience we can just keep using the native select otherwise the autocomplete. Do we have a way to know how many classes had been created in avg across a selected set of users?

**Comment by pmcpinto** [comment]
> Do we have a way to know how many classes had been created in avg across a selected set of users?

We don't have that data. @mdperez86 how much time do you think it will be necessary to implement this? This will help decide on implementing it now or later. Thanks.

**Comment by mdperez86** [comment]
@pmcpinto 

> how much time do you think it will be necessary to implement this?

1. Do you meant adopting the autocomplete functionality?
2. Implement something to gather the shipping classes creation avg?
