### ISSUE TITLE
[EPIC] Inbox low-effort improvements to increase the visibility of new messages

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#34926]
**Description:** At the moment, a high percentage of users have reached the limit of the number of messages shown on the panel (25). This creates an overwhelming experience, making it difficult to parse all the information and distinguish new messages from older content. This epic will include a number of low-effort improvements to increase the visibility of new messages.

**Comment by DavidAnderson684** [comment]
Is the reason why a high percentage of users have reached this limit because they don't read them?

**Comment by AnnaMag** [comment]
full view: https://github.com/orgs/woocommerce/projects/60/views/17

**Comment by pmcpinto** [comment]
> Is the reason why a high percentage of users have reached this limit because they don't read them?

Good question. One of our assumptions is that users view the Inbox but may not notice that there's an option to remove the message. Improving the visibility of the "Dismiss" button will help them in this area.

**Comment by DavidAnderson684** [comment]
> One of our assumptions is that users view the Inbox

I only have anecdotal evidence to go on. But I'd question this. When it first was proposed I was against it because my view (again, anecdotal) is that few people want one more inbox, one more place to check for messages - and personally since that time I almost forgot it existed on my own sites, and only tend to remember when I see it mentioned here in the issue tracker!

**Comment by pmcpinto** [comment]
Interesting. Thanks for sharing your feedback on this :)
