### ISSUE TITLE
[Shipping] Shipping class creation error handling

### ISSUE THREAD

**Issue by mdperez86** [woothemes/woocommerce#35037]
**User story**

- As a merchant,
- I want when new shipping classes is been creating and the server responds an error a message should be shown.
- So that the customer know there were a problem creating the new class.

The create new shipping class logic will be done as part of https://github.com/woocommerce/woocommerce/issues/34657

**Design**
5sAIeTRd9Yp7nSCT33BAWz-fi-6590%3A287898

**Acceptance criteria**

- [x] If server sends an error during the class creation a dismissible snackbar with this error massage should be shown `We couldn’t add this shipping class. Try again in a few seconds.`
- [x] Removed the default value `New shipping class` from the `Name` field and replaced it with a placeholder: `e.g. Fragile products`
- [x] Only used the category's name when the user creates a new shipping class for the first time
- [x] Next and every other time when the user adds a new shipping class, they'd only see the placeholder

**Comment by jarekmorawski** [comment]
Thanks for creating the issue, @mdperez86. Initially, we discussed using a snackbar message for this, but after the demo, I think it'd be more suitable to show an in-form validation, much like the empty field. Given that the problem is with the slug, perhaps we could run a check when the user exits the field and 1) show the validation message 2) disable the `Add` button.

The message could read:

`A shipping class with this slug already exists. Try a different one.`

As discussed during the call, we could avoid the duplication altogether if:
* we removed the default value `New shipping class` from the `Name` field and replaced it with a placeholder: `e.g. Fragile products`
* we'd validate both the slug field and the name dynamically (when the user leaves the field) for 1) status (the name field can't be empty 2) duplication
* we only used the category's name when the user creates a new shipping class for the first time
* next and every other time when the user adds a new shipping class, they'd only see the placeholder

**Comment by mdperez86** [comment]
@jarekmorawski 
> Given that the problem is with the slug

This is an assumption! I mean, as a dev I know the server error was caused by a slug duplication. But if we look at the server response, there is no way to know it's something related to the slug at all. 
```json
{
  "code": "term_exists",
  "message": "A term with the name provided already exists in this taxonomy.",
  "data": { "status": 400, "resource_id": 57 }
}
```
Which means we can not bind this error to the slug field. This error is more like a global one and should not be treated as per-field error. If we do that then other possible error (not necessarily related to the slug) will be shown in the same way.

> we'd validate both the slug field and the name dynamically (when the user leaves the field) for 1) status (the name field can't be empty 2) duplication

Currently the form is performing validations like `The field cannot be empty` in case of the `name` because it's the only require field. But in order to performe validations like `duplications` we need a valid server response for that. With the current response we get from the server we cannot distinguish where the error is related to the `slug` or any other field like `name`.

> we only used the category's name when the user creates a new shipping class for the first time

How do I know that the user created a new shipping class for the first time? If the shipping class list is empty!?

**Comment by jarekmorawski** [comment]
> Which means we can not bind this error to the slug field. This error is more like a global one and should not be treated as per-field error

Gotcha! Let's use the snack bar, then. 👍 

> How do I know that the user created a new shipping class for the first time? If the shipping class list is empty!?

No, I meant in relation to the current session. For example, the user creates a new shipping class and sees the category filled in. But if the add another one _while still working on the same product_, the fields in the add shipping class modal would be empty. Does that make sense? 🤔
