### ISSUE TITLE
Category management improvements

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35173]
**Description:** the new category management flow has some flaws that should be fixed before we test the new experience with users

**Acceptance criteria:**

- [x] The user should see an option to create a new category when he starts typing
- [x] The category list should appear on the first click

**Comment by octaedro** [comment]
Hi @pmcpinto,

> The category list should appear on the first click

What should we show after clicking the input? Is it ok to show the first 20 categories?

**Comment by pmcpinto** [comment]
I think a total of 10 is a good starting point (including sub-categories). @jarekmorawski  what do you think?

**Comment by jarekmorawski** [comment]
Will we load the next items as the user scrolls down the list? If so, 10 sounds like a good starting point.

**Comment by AnnaMag** [comment]
@mdperez86 could we prioritize it, please?

**Comment by mdperez86** [comment]
@louwie17 is working on `The user should see an option to create a new category when he starts typing` and this is the ongoing PR  https://github.com/woocommerce/woocommerce/pull/35132

**Comment by mdperez86** [comment]
Having a discussion with @louwie17 about

> Will we load the next items as the user scrolls down the list? If so, 10 sounds like a good starting point.

We have some things to say. Currently the category dropdown field component was made to manage nested categories in the form of a tree which is created client side only because the server does not returns a category tree but a category list. So paginating a list that will looks like a tree it's not something trivial to do. For now the category dropdown requests the first 100 categories from the server. If the total is less than 100 the filtering process happends client side if not then it happends server side.
There are diferent ways to implement a pagination that matches the requirement described above but I think this should be a topic to discuss as a team.

In order to not block this issue I suggest:
- Consider the PR from @louwie17 for the AC1
- For the AC2 focus only on showing the categories already loaded by the current category component algorithm as it is right now.
- For pagination, create a new issue only about that and discussing it with all the team in order to find the best solution for our product requirements. Because it might affect the backend category endpoint currently implemented.

cc: @jarekmorawski @pmcpinto

**Comment by AnnaMag** [comment]
> For the AC2 focus only on showing the categories already loaded by the current category component algorithm as it is right now.

LGTM for the MVP @mdperez86.

Let's continue the discussion on the final solution.

**Comment by pmcpinto** [comment]
> For the AC2 focus only on showing the categories already loaded by the current category component algorithm as it is right now.

LGTM as well. Thanks for surfacing potential issues with the categories list pagination
