### ISSUE TITLE
[Enhancement]: Add tooltips for all icons in the image toolbar

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35184]
### Describe the solution you'd like

For better clarity and accessibility, let's add tooltips when the user hovers over the non-text buttons in the image toolbar.

### Mockup

<img width="320" alt="image" src="https://user-images.githubusercontent.com/79307566/196688362-e2843b67-d46c-4475-9095-f07c5063246d.png">

### Acceptance criteria

- [ ] The tooltips are positioned correctly, below the corresponding toolbar button (see https://wordpress.github.io/gutenberg/?path=/story/components-toolbar--toolbars)
- [ ] The drag handle tooltip says `Drag to reorder`
- [ ] The left arrow icon tooltip says `Move left`
- [ ] The right arrow icon tooltip says `Move right`
- [ ] The cover icon tooltip says `Set as cover`
- [ ] The trash icon tooltip says `Remove`

**Comment by mattsherman** [comment]
The tooltips are actually currently being set. But, they are appearing in the wrong position. This can be more easily seen in Storybook.

So, the main complexity of this story will be fixing this issue. It is likely due to how we are styling/positioning the toolbar component in the image gallery, as the base `<ToolbarButton>` component from `@wordpress/components` does not seem to exhibit this issue.

**Comment by mattsherman** [comment]
Code reference for `<ImageGallery>`:

https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/image-gallery

**Comment by mattsherman** [comment]
I'm estimating this as a `2`. The fix *might* be easy, but figuring it out will involve some trial-and-error, experimenting with different DOM and CSS changes until we hit the magic "correct" structure.

**Comment by mdperez86** [comment]
Estimation: 2

**Comment by mattsherman** [comment]
The position of the tooltips is actually fixed in the version of `@wordpress/components` included in WordPress 6.1 (`21.0.6`, see https://github.com/WordPress/WordPress/commit/bfbf1bc0530e5c915122f6a207349e6f4b7e942f).

So, how do we handle such an issue? We always use the version of `@wordpress/components` included in WordPress, correct? (/cc @joshuatf)

We should separately update the version of `@wordpress/components` we depend on in `@woocommerce/components` so that Storybook gets this fix... it is still on version `19.5.0` of `@wordpress/components`. But, that seems like a larger scope than this issue.

**Comment by mattsherman** [comment]
@jarekmorawski 

I think that the current tooltips of:

* `Move previous`
* `Move next`

are better than `Move left` and `Move right` respectively, since "previous" and "next" work better in a RTL/BiDi environment. Unless we want the translation actually changed from "left" to "right" (and vice-versa) for those locales where RTL/BiDi is used.

What do you think?
