### ISSUE TITLE
[Enhancement]: [HPOS] Orders List table overrides sortable columns and doesn't allow custom filters

### ISSUE THREAD

**Issue by dbarproductions** [woothemes/woocommerce#35275]
### Describe the solution you'd like

With the List Table for WC Orders when using the new HPOS system, I can add my custom columns for my wholesale ordering plugin in a similar fashion to the way it was done with the old wp_posts based orders. I can also mark my column as sortable by using the newer filter hook:
'manage_woocommerce_page_wc-orders_sortable_columns'
which then properly makes the column sortable and sets the URL arguments accordingly
However, in the new admin orders ListTable class, when it creates the query arguments to use for wc_get_orders, the function only allows the predefined sortable columns in that class, and there are no filters in place to add our custom columns to that class. There either needs to be a filter on the get_sortable_columns method to allow adding custom columns, OR there needs to be a filter within the set_order_args method to allow adding custom columns to the array of sortable columns.

In addition, with the old wp_posts based orders, I was able to use the restrict_manage_posts hook to add a custom filter to allow admin to view only wholesale or only retail orders. I see no current way to add a similar filter to the new list table used by the HPOS system.

**Comment by rajeshsingh520** [comment]
I am facing the same issue I am able to do the sorting of orders using this filter hook whict gives the arguments for wc_get_order

woocommerce_shop_order_list_table_prepare_items_query_args

but in my case it is not working as my custom column is bases on custom meta value which is Date 

when I do this it does not do the proper sort

`

            $args['orderby'] = 'meta_value';
$args['meta_query'][] = array(
                                         'key' => 'my_meta_key',
                                         'type' => 'DATE'
                                       );      

`

**Comment by unfulvio-godaddy** [comment]
I also have bumped into this issue while working at compatibility updates for the SkyVerge plugins.

There seems to be no direct replacement for these filters when HPOS is used:

* `posts_orderby`
* `posts_join`
* `posts_where`

The `woocommerce_shop_order_list_table_prepare_items_query_args` allows for filtering admin queries for orders in the list orders table page, but the `orderby` argument is very limited. There are no filters in place in `OrdersTableQuery` for example in `build_query()` to get around this limitation. Perhaps allowing filter(s) for the properties handled by this method?

**Comment by jan-potuznik-z** [comment]
We are using the `posts_clauses` filter to filter orders based on data stored in our custom tables on the non-HPOS (High-Performance Order Storage) order overview page.
We would like to have some option to do that on the HPOS order overview page.
Migration of columns used for filtering to the order meta data is currently the only known workaround.
That said, we'd really need some new filter to do that without migration.

**Comment by jorgeatorres** [comment]
Hi everyone!

We've made some recent changes that dramatically increase flexibility and should make the workflows described here possible.

- In the specific case of the columns in the list table, it's true that we override the parent method and so `manage_woocommerce_page_wc-orders_sortable_columns` doesn't work, but we do offer an HPOS-specific one: `woocommerce_<order_type>_list_table_sortable_columns` that should do the same. Here `<order_type>` is `shop_order` by default but other order types are supported.
- The [ListTable](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php) class now has various other filters and hooks, both generic and order type specific, that should cover a bunch of scenarios.
- Similarly, for modifying the query in the list table we now have various options:
   - [`woocommerce_<order_type>_list_table_request`](https://github.com/woocommerce/woocommerce/blob/ad8b121e2198e0daf98d32c88a586b408249887d/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L373C14-L373C14) allows filtering the request (GET args) considered by the list table. This before `wc_get_orders()` is called.
   - After the list stable has determined the args to be passed to `wc_get_orders()`, we give 3rd parties a chance to add/modify the actual query args with [`woocommerce_order_list_table_prepare_items_query_args `](https://github.com/woocommerce/woocommerce/blob/ad8b121e2198e0daf98d32c88a586b408249887d/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L389C47-L389C100) (generic) and [`woocommerce_<order_type>_list_table_prepare_items_query_args`](https://github.com/woocommerce/woocommerce/blob/ad8b121e2198e0daf98d32c88a586b408249887d/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L398C18-L398C19) (order type specific).
- The SQL used for order queries (in the list table but also elsewhere) can be modified via [`woocommerce_orders_table_query_clauses`](https://github.com/woocommerce/woocommerce/blob/ad8b121e2198e0daf98d32c88a586b408249887d/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php#L735C3-L735C3) and [`woocommerce_orders_table_query_sql`](https://github.com/woocommerce/woocommerce/blob/ad8b121e2198e0daf98d32c88a586b408249887d/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php#L760C43-L760C77), which allow changing some of the clauses (fields, join, etc.) and the final SQL respectively.

All of the above was added after this issue was initially created, of course, but given now we have it, I'm going to close this now. Feel free to re-open if I missed something or there are still some gaps that we need to close in terms of flexibility.

Thanks for the report!

**Comment by EdithAllison** [comment]
@jorgeatorres I'm struggling to find information how to correctly make a column sortable. 

I've got the filter `woocommerce_<order_type>_list_table_sortable_columns`, but in CPT I also use `pre_get_posts` to enable sorting on meta values. 

I've tried using `woocommerce_<order_type>_list_table_prepare_items_query_args` but that results in an Inner Join which hides all products that don't have the meta_key. I can see that eg WCS is using sortable columns with a Left Join, but am having a hard time figuring out how I can correctly add this. Is there any documentation or "correct way" to do this?

**Comment by jorgeatorres** [comment]
@EdithAllison: Apologies for the delay here. Given this issue was already closed I missed the ping. It shouldn't be too hard to translate what you were doing before. Would you mind sharing the code for the CPT vs HPOS version? You can find me on the Woo community Slack, if you'd rather discuss over there.
