### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by michael1181** [woothemes/woocommerce#35297]
### Describe the solution you'd like

Under general setting there should be a cart persistence setting that allows you to change the amount of time between carts being emptied. as with bookings there is a fine line between waiting too long for customers paying and customers abandoning there cart.

### Describe alternatives you've considered

I know there are paid for alternatives to add this feature but there is already a setting for it. it just needs adding to the settings as you can already do this in the settings. https://woocommerce.com/document/change-the-default-cart-session-length/?aff=10486&cid=1131038

**Comment by barryhughes** [comment]
Thanks for submitting this, but it may be better to post it as a feature request [over here](https://woocommerce.com/feature-requests/woocommerce). That way, we can gauge how much interest/demand there may be for this change (this is simply because, as a rule of thumb, we don't want to add more settings than are necessarily and potentially over-complicate the UI if there is not likely to be much usage).
