### ISSUE TITLE
Fatal Error - Make compatible with PHP 8.1.x version

### ISSUE THREAD

**Issue by danishashraf047** [woothemes/woocommerce#35327]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The latest version of WooCommerce is still not compatible with PHP 8.1.x version because getting this error

`PHP Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/vhosts/sanjanatur.de/httpdocs/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php:2289`

This error occurs when the plugin is auto-updated or manual updated. So, I always fix this issue with this code:

`$params['orderby']['enum'] = array_merge( [$params['orderby']['enum']], array( 'menu_order' ) );`

Can you add this code or if you think the solution would be different so it would be great if you fix this issue?

### Expected behavior

The fatal error must not be occurred.

### Actual behavior

Fatal error occurs.

### Steps to reproduce

Auto-update or manual update.

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.0.0
REST API Version: ✔7.0.0
WC Blocks Version: ✔8.5.1
Action Scheduler Version: ✔3.5.2
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 12GB
WP Debug Mode: ✔
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 7.4.32
PHP Post Max Size: 10GB
PHP Time Limit: 9000
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Status report information ###

Generated at: 2022-10-26 06:27:04 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hey @danishashraf047!

Thanks for the report and apologies for the delay in responding. We're currently looking at fixing all the incompatibilities/warnings with PHP 8.1 and 8.2.

I wasn't able to reproduce the problem here. The [problematic line](https://github.com/woocommerce/woocommerce/blob/28c72e81c48d85affdeef8a98408d8e60a6934eb/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php#L2291
) assumes `$params['orderby']['enum']` is an array, but that's precisely the case as `$params` is populated with the results from `get_collection_params()` which defines `$params['orderby']['enum']` as an array:

https://github.com/woocommerce/woocommerce/blob/722a752a2e586818c275404fd328d9a43b132dba/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php#L646-L653

The only way I found to replicate was to alter the collection params via the `rest_product_collection_params` filter and set `enum` to something other than an array, with a snippet like this:

```php
add_filter(
	'rest_product_collection_params',
	function( $params ) {
		$params['orderby']['enum'] = 'not-an-array';
		return $params;
	}
);
```

This makes me think what you're seeing might be a plugin conflict. Is there any chance you can confirm? Is this still happening to you? If so, could you provide step by step instructions on how to reproduce?

Thanks!

**Comment by rrennick** [comment]
I'm closing this for lack of feedback. If the issue does recur, please let us know and we can re-open the issue.
