### ISSUE TITLE
PHPCodeSniffer: Lint only lines that were changed

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#35369]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

PHPCS was [recently changed](https://github.com/woocommerce/woocommerce/pull/35237) to remove usage of [an action](https://github.com/thenabeel/action-phpcs) that was limiting our control and causing issues. The problem is this action restricted failures to violations found in changed lines as opposed to the entire file.

That causes difficulties when reviewing simple fixes, often times [contributions from the community](https://github.com/woocommerce/woocommerce/pull/35329).

**Comment by roykho** [comment]
To add a possible solution which I've actually looked at in the past and got it work: https://github.com/sirbrillig/phpcs-changed

The backstory as to why I didn't go with it at the time was because there was no annotation in the action itself which we've had. But perhaps we could add it upstream I guess.
