### ISSUE TITLE
[HPOS] 'restrict_manage_posts' hook used to add custom filters on Orders page does not work

### ISSUE THREAD

**Issue by rashmimalpande** [woothemes/woocommerce#35466]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

'restrict_manage_posts' hook is not working to create custom filters on WooCommerce Orders page. There is no hook present to add custom filters on orders page.

### Expected behavior

The custom filters added on orders page with current version of WooCommerce should work with HPOS too.

### Actual behavior

The custom filters added with 'restrict_manage_posts' on orders page are not visible anymore with HPOS version.

### Steps to reproduce

1. Enable HPOS/COT.
2. Go to WC > Orders.
3. Check if the filters added through 'restrict_manage_posts' are visible or not.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @rashmimalpande!

Thanks for your report. We noticed this omission a while back and introduced two action hooks for the new HPOS orders page:

- [`woocommerce_order_list_table_restrict_manage_orders`](https://github.com/woocommerce/woocommerce/blob/e0b829413db0738487f2f1e57898bb10f4eb8342/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L601)
- [`woocommerce_order_list_table_extra_tablenav`](https://github.com/woocommerce/woocommerce/blob/e0b829413db0738487f2f1e57898bb10f4eb8342/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L624)

Depending on your needs, one or the other might work better. `woocommerce_order_list_table_restrict_manage_orders` might be the closest replacement for `restrict_manage_posts`.

We understand this means you'll have to hook to both `woocommerce_order_list_table_restrict_manage_orders` and `restrict_manage_posts` if you want to support both HPOS and non-HPOS. While this might be inconvenient, we didn't want to blindly re-use the `restrict_manage_posts` in the new screens as that might've resulted in serious compatibility issues. Also `restrict_manage_posts` is fired for all posts tables, which means code hooked onto it might have expectations that are no longer true in the specific case of the HPOS list table.

To make things easier, `woocommerce_order_list_table_restrict_manage_orders` does send the order type ("shop_order" by default) as second argument (similar to what `restrict_manage_posts` does) so that you can (maybe) re-use the same callback for both.

Given the above, I'm going to close this issue, but feel free to re-open if I've missed something or in any way misrepresented your concern.
