### ISSUE TITLE
Adapt the width of the price fields

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#35538]
Follow-up to https://github.com/woocommerce/woocommerce/issues/35180.

The currency placement is correct as per designs, but the width of the fields differs.

>keep the current setup (with the currency symbol fixed inside the input field and synced with the store's locale) and make the field 50% wide on desktop and 100% on mobile

![Image](https://user-images.githubusercontent.com/13561163/201067060-ff8e62e5-577c-437e-bc30-31642c48c059.png)

EDIT: 
we could consider updating Inventory + Shipping within the same PR

<img width="826" alt="Screenshot 2022-11-15 at 21 15 37" src="https://user-images.githubusercontent.com/13561163/202016858-554ada6c-7780-4fb4-823e-e212a903f300.png">

**Comment by AnnaMag** [comment]
Note: more fields in the form seem to need a modification, but let's keep the scope here very limited.

**Comment by mattsherman** [comment]
@AnnaMag Do we have other issue(s) to address the other fields?

Also, I wonder if this really reduces scope much, since we are talking about just a breakpoint with a `width` setting probably. We could probably apply that CSS change to the other necessary fields and test those fields without a sizable increase in scope. Just a thought.

**Comment by AnnaMag** [comment]
Thanks for pointing this out @mattsherman. 

@nathanss there are 2 more sections that will require similar adjustment. I updated the issue description-- those can be handled in the same or a separate PR.
