### ISSUE TITLE
[Enhancement]: Fade the value selection field in the Attributes modal when no attribute is added

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35568]
### Describe the solution you'd like

When the user opens the Attributes modal and doesn't select any attributes yet, the value selection field looks active, while in reality, it's not interactive. We should fade it out just like the trash icon to avoid confusion.

Current implementation

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/79307566/201641754-8c0b9bb5-1861-4b46-a4f4-dc40a56280f9.png">

Design

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/79307566/201641547-bbc36d6f-971b-4a47-9bfe-ce958e106292.png">

**Acceptance criteria**

- [ ] The value selection field has 50% opacity until the user selects an attribute.

**Comment by joshuatf** [comment]
Just noting that we should opt to use the `disabled` prop which will hopefully handle most of the styling we need.

These styles are probably not yet added or inherited since this our own component.  I wonder if there's an easy way to inherit them without copy/pasting them, but that may be the easiest short-term solution.
