### ISSUE TITLE
[Enhancement]: Add a bottom padding to the whole form

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#35571]
### Describe the solution you'd like

Let's add a fixed `padding-bottom` of 128/64 px to the whole form's body to give it a little breathing space. Currently, the last section on the page is virtually glued to the screen's edge.

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/79307566/201647809-457d3951-27af-489c-a994-3a8856c24fa2.png">

**Acceptance criteria** 

- [x] The form has a fixed `padding-bottom` of 128 px on desktop and tablet/mobile.

**Comment by joshuatf** [comment]
We should also take into account the mobile screen which has a fixed bottom bar and may need more or less padding for smaller viewports.

Some padding has been added as a part of https://github.com/woocommerce/woocommerce/pull/35623 but this may need to be adjusted.

**Comment by mdperez86** [comment]
@jarekmorawski do you think it's necesary to differentiate the margin between desktop/mobile? Take a look if I add mb-128px for all screens. Consider that the bottom bar is 69px height (68px + 1px border top). So 64px is considered less than 69px on mobile screens. That's why I thing 128px could fit for both screens considering the bottom bar on mobiles, but you are the designer. Let me know the final margin on mobile please.
Mobile:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13334210/203864138-6e1e15a8-c128-4cbf-9d7d-a0b252953f51.png">
Desktop:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/13334210/203864175-fa62c2fc-995c-41b8-b6c1-e6c0f9ed7924.png">

**Comment by jarekmorawski** [comment]
Alrighty. 👍 I just checked in the mobile view in Chrome and it looks fine. Let's go with 128 on both desktop and mobile. I'll update the AC.
