### ISSUE TITLE
[HPOS] Translating `WooCommerce` causes a fatal error

### ISSUE THREAD

**Issue by PanosSynetos** [woothemes/woocommerce#35677]
I used the `Say What` plugin, to translate `__( 'WooCommerce', 'woocommerce' )` to `WooCommerce LaWooCommerce` (a la Ferrari LaFerrari :lol: )

When visiting `wp-admin/admin.php?page=wc-orders` there is a fatal error

```
PHP Fatal error:  Uncaught Error: Call to a member function prepare_items() on null in /Users/panos/Local Sites/somewherewarm/app/public/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php:170
Stack trace:
#0 /Users/panos/Local Sites/somewherewarm/app/public/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Internal\Admin\Orders\PageController->output('')
#1 /Users/panos/Local Sites/somewherewarm/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /Users/panos/Local Sites/somewherewarm/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /Users/panos/Local Sites/somewherewarm/app/public/wp-admin/admin.php(259): do_action('woocommerce-la-...')
#4 {main}
  thrown in /Users/panos/Local Sites/somewherewarm/app/public/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 170
```

As discussed with @jorgeatorres , 

> This does sound like a bug. I can see from the stack trace that we’re running an action with the translated name (`do_action('woocommerce-la-...')`).

**Comment by jorgeatorres** [comment]
Just mentioning that this seems to be a result of https://core.trac.wordpress.org/ticket/18857. 

In particular, it affects the new Orders admin page, but there are other instances of similar `load-{$page}` actions in the codebase that could be affected by a translation, even when HPOS is disabled. For example, we have code that assumes `woocommerce_page_wc-settings` or `woocommerce_page_wc-reports` are the correct page names for certain sections.

A translation would break that, as well as screen IDs, affecting scripts/styles and whatnot.

Maybe an 'easy fix' would be to change [the code where we register the main WC menu](https://github.com/woocommerce/woocommerce/blob/29b9c691cdde2f3dac182451a06256a85650c3c4/plugins/woocommerce/includes/admin/class-wc-admin-menus.php#L71) so that the `$menu_title` arg is not translatable, but not sure what the implications are for this. It'd prevent translating the main menu but that would be less effort than fixing code everywhere (even outside of WC, as there's similar code in gateways or Subscriptions).

The following code helps reproduce the problem:

```php
// You would expect the screen ID/page name for this new page to be `woocommerce_page_my-page`
// but if "WooCommerce" is translated, to say, "LaWooCommerce" it'll be `lawoocommerce_page_my-page` :(

add_action(
	'admin_menu',
	function() {
		add_submenu_page(
			'woocommerce',
			'My Page',
			'My Page',
			'manage_options',
			'my-page',
			function() {
				var_dump( get_current_screen()->id );
			}
		);
	}
);
```
