### ISSUE TITLE
[Enhancement]: Add custom filters to ListTable - HPOS

### ISSUE THREAD

**Issue by brucealdridge** [woothemes/woocommerce#35753]
### Describe the solution you'd like

Related to #35601 and open PR #35658

When using  [Custom Order Types HPOS Screens](https://github.com/woocommerce/woocommerce/pull/35658), extensions like [WooCommerce Subscriptions](https://github.com/Automattic/woocommerce-subscriptions-core) should be able to add custom filters in the [ListTable](https://github.com/woocommerce/woocommerce/blob/38295542ab9a153acebdca562c6e177d1118da31/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php) class.

WooCommerce Subscriptions [currently attach](https://github.com/Automattic/woocommerce-subscriptions-core/blob/8b6ca338e1f1b010d0363407c82dd6b088875fb2/includes/admin/class-wcs-admin-post-types.php#L78-L80) to the `restrict_manage_posts`hook when using CPT.

Adding [this hook](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-posts-list-table.php#L574-L589) before `submit_button` in `extra_tablenav()` would allow for drop-in replacement.
https://github.com/woocommerce/woocommerce/blob/38295542ab9a153acebdca562c6e177d1118da31/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L531-L536

### Additional context

**CPT**
![Screenshot 2022-11-29 at 1 59 36 PM](https://user-images.githubusercontent.com/57298/204412644-f9857c59-57cd-44ec-949a-2fc6d05093d5.png "CPT ListTable screen showing filters")
**HPOS**
![Screenshot 2022-11-29 at 2 00 56 PM](https://user-images.githubusercontent.com/57298/204412653-37094cad-8338-409f-b407-0963b2d492a0.png "HPOS ListTable screen showing filters")

**Comment by jorgeatorres** [comment]
Hi @brucealdridge! 👋 

We briefly discussed this on the team (see p1669839465419919-slack-C0E1AV8T0) and we believe it is better for now to use new hook names. `restrict_manage_posts` still references "posts" and firing that post-related hook on the new HPOS implementation might break things for anything not yet HPOS ready.

For now, I've added the [`woocommerce_order_list_table_extra_tablenav` action](https://github.com/woocommerce/woocommerce/pull/35658/commits/2e729d7dd19169f51fae7893645af48c514f4ab5) which also passes the order type as argument so it's sort of compatible with `restrict_manage_posts` (in the sense that you could use the same callback).
Looking at Subscriptions, I see the callbacks don't deal with the post/order type arg at all and instead rely on `$typenow`, which isn't set in HPOS screens. This might change when we're done with all this changes, but I believe it'd be safer in general to use the post type arg instead of checking `$typenow`.

I'm going to close this given there's a "fix" [in our working branch](https://github.com/woocommerce/woocommerce/tree/issue-35601) but feel free to re-open if I've misinterpreted the problem or the solution I've provided doesn't work well for WCS.
