### ISSUE TITLE
Refactor attributes component to reuse for options

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35770]
Under the hood, attributes and options are nearly identical with the exception of the `variation` flag.

The attributes flow has already been created and configured to work in the new product management experience.  We should reuse those components with some small tweaks to allow them to be used for options as well.

https://github.com/woocommerce/woocommerce/blob/b186c77cbc61572d2a6e607d6faadf80226e0b1f/plugins/woocommerce-admin/client/products/fields/attribute-field/attribute-field.tsx#L24

Note that `variation` ("used for variation") does not appear to be a property in the [REST API](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes) and could be problematic if we can't use this flag to distinguish between options and attributes.  We may need to add that to the endpoint before tackling this issue.

https://github.com/woocommerce/woocommerce/blob/185d3337cac78ba12a4dd6c0384a82df32629cb2/plugins/woocommerce/includes/class-wc-product-attribute.php#L254

![Image](https://user-images.githubusercontent.com/10561050/204642027-6aaf958a-3db9-417a-8ebf-8412ff01c87c.png)

**Acceptance criteria**

* [ ] Add a prop to distinguish between options and attributes on the `AttributeField` component
* [ ] Render the component under the "options" tab
* [ ] Make sure on localized strings use the word "option" instead of "attribute" when the options prop is set
* [ ] Limit fetched and shown options to those that have

**Comment by joshuatf** [comment]
Barring any issues with getting the `variation` property on the attributes, this will hopefully be relatively straightforward and we can reuse most of the code in the attributes.

Some thought may need to given on how those components are structured to make using it for both options and attributes to use.

Estimate: 3

**Comment by louwie17** [comment]
> Note that variation ("used for variation") does not appear to be a property in the [REST API](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes) and could be problematic if we can't use this flag to distinguish between options and attributes. We may need to add that to the endpoint before tackling this issue.

This is actually because the variation option is an option only available on a product level and not an attribute level. You can’t set attributes globally as variation attributes.
The API does support the variation flag on an attribute level as you can see here: https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes-properties ( I will post this in the GH issue as well, so it doesn’t get lost in Slack).
Meaning that when you save the product as a whole you can add the `variation` flag to the attributes data.

Attributes on a product level are actually handled slightly oddly, as the selected `options` are only being passed in as a list of strings from the product level, and updated this way as well. But in reality each of those strings is it's own term object with a unique id. Custom attributes is the only exception to this rule, which may the reason why it was done this way.

**Comment by louwie17** [comment]
> The attributes flow has already been created and configured to work in the new product management experience. We should reuse those components with some small tweaks to allow them to be used for options as well.

Tweaks to the component would work, but given all the options are `variation` by default, you may not even need to modify the component and only update the `onChange` function to set `variation` to `true` for all the values.
In the case you may have to also filter out all the attributes that do not have `variation` set to `true` into the `value` object.

I would also recommend something like that, to avoid adding to much custom `variation` logic within the Attributes field, but I could be easily convinced otherwise.

**Comment by mattsherman** [comment]
> I would also recommend something like that, to avoid adding to much custom variation logic within the Attributes field, but I could be easily convinced otherwise.

Because both lists, "Attributes" and "Options", will need to filter what is shown (see [discussion in epic](https://github.com/woocommerce/woocommerce/issues/35659#issuecomment-1343023302)), and need to have all the `attributes` available to prevent things from appearing in both lists, I think that the filtering/customization should actually be within the `AttributesField`, configurable via props. I am exploring this approach and will share a draft PR when I have something minimally functional before I get too far into the details.

**Comment by mattsherman** [comment]
**2022-12-15 update**

- https://github.com/woocommerce/woocommerce/pull/35997 - This PR has been created to refactor `AttributeField` into sub-components that expose all UI strings as props. This will make supporting Options easier, regardless of which approach we take below.
- For next steps, we can either
    - Add a `type` prop to `AttributesField` to switch between Attributes and Options. Probably the least additional refactoring required and the quickest solution to get something working.
    - Continue refactoring `AttributesField`, pulling out more logic and components that both `AttributesField` and `OptionsField` (new component) can use, without too much duplication. Probably the most flexible and maintainable long term, especially if Options and Attributes diverge further in the future.
- In any scenario, we need to figure out how to best handle attribute hydration. If we have the `AttributesField` and `OptionsField` (or, two instances of `AtttributesField`) both looking at all attributes (which is needed in order to select from global attributes and also not allow global attributes to be selected that are already used by the other list), we need to somehow have both components have the most up-to-date hydrated attributes. See initial draft PR where I worked around this by disabling hydration: https://github.com/woocommerce/woocommerce/pull/35910
- We should also be mindful of any requirements and/or UX flow changes that came out of the recent Options and Attributes discussion. I have not yet fully reviewed the latest proposals: pcQJnU-Ww-p2

/cc @joshuatf

**Comment by joshuatf** [comment]
Great work on the initial refactor @mattsherman!

>Add a type prop to AttributesField to switch between Attributes and Options. Probably the least additional refactoring required and the quickest solution to get something working.

I'm in favor of this short-term.  I think this is a quick and easy win, but if we want to further break down components we can always do so later.

>we need to somehow have both components have the most up-to-date hydrated attributes

Sounds like the attributes should be hydrated in the parent component and passed down to the `AttributeField` as opposed to fetching inside of this component.

**Comment by mattsherman** [comment]
@joshuatf @octaedro @mdperez86 I've left some comments in the following PR. I think that PR could be a good base to continue refactoring in order to finish implementing the Options section. But, if it is decided that a better approach should be taken, please don't hesitate... I won't cry over it! 😄

- https://github.com/woocommerce/woocommerce/pull/35910
