### ISSUE TITLE
Product variation quantity status indicator

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#35791]
The variations should show a quantity status indicator next to the inventory levels. 

Is this affected by stock status?

**Design**

BaoQ3PGPnhAiJCsJtxgej3-fi-106%3A1922&t=Jsh233onKmJpJYtN-0

![Image](https://user-images.githubusercontent.com/10561050/204896398-5d5baaa9-9a0d-4f11-8bac-e77c3794a9f7.png)

**Acceptance criteria**

* [ ] The indicator should be green when the inventory is >= 10
* [ ] The indicator should be yellow when the inventory is < 10 and > 2
* [ ] The indicator should be red when the inventory is <= 2

**Comment by joshuatf** [comment]
>Quantity status indicator: red when >=10, yellow when <5, red when 2, 1 or 0.

@jarekmorawski @pmcpinto I think the original criteria might have had a typo so I adjusted above in the acceptance criteria.  Please let me know if my assumptions were accurate.

Also curious if this stock status indicator will exist when inventory is not tracked and stock level is manually tracked.

**Comment by jarekmorawski** [comment]
> I think the original criteria might have had a typo so I adjusted above in the acceptance criteria. Please let me know if my assumptions were accurate.

Looks good to me! Thanks, Josh.

> Also curious if this stock status indicator will exist when inventory is not tracked and stock level is manually tracked.

Oh, thank you for bringing this up. In this situation, we'd also use color coding, but differently.

- Green dot for `In stock`
- Red dot for `Out of stock`
- Yellow dot for `On backorder` (temporarily, because we won't have this status later on)

<img width="750" alt="image" src="https://user-images.githubusercontent.com/79307566/204985379-d1944b21-8bc5-44ad-9e12-2d77211b8d73.png">

**Comment by joshuatf** [comment]
Estimate: 1

Stock status has already been implemented as a part of https://github.com/woocommerce/woocommerce/pull/35889 so this will only involve adding the indicator dot and colors.
