### ISSUE TITLE
Credit Card function not working as of today 12/1/2022

### ISSUE THREAD

**Issue by sstourmanagement** [woothemes/woocommerce#35813]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have confirmed that when checking out on my website with woo commerce the prompt that gives the user a chance to enter their credit card is not coming up on the screen.  It's just a blank space but it still allows the user to click submit to make payment.  Then the payment fails because no credit card was entered.

### Expected behavior

The credit card prompt should exist so I can enter my card details at checkout

### Actual behavior

the screen is simply blank where the credit card entry should be

### Steps to reproduce

1) add product to cart (same issue with any product)
2) scroll down to credit card. 
3) select add new credit card
4) NO prompt or popup for credit card exist.  It's blank. 

### WordPress Environment

6.1.1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment]
Hi @sstourmanagement, 

Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

Additionally, please confirm that you're able to reproduce this bug when only WooCommerce plugin is active.
