### ISSUE TITLE
[Enhancement]: When you type the first letter to search in a dropdown all the names "beginning with that letter" should display

### ISSUE THREAD

**Issue by smudra** [woothemes/woocommerce#35864]
### Describe the solution you'd like

<img width="622" alt="Screenshot 2022-12-01 at 4 37 12 PM" src="https://user-images.githubusercontent.com/3485554/206019510-85765d65-b2b3-4b80-93a9-303b13a93863.png">

When I type CA for canada in the countries list, all countries beginning with those letters should display. Currently, all countries having those letters are displaying. Is it possible to display country name beginning with those letters to display at the top.

**Comment by barryhughes** [comment]
We agree, this would be a nice change. Added to the backlog.

**Comment by mikejolley** [comment]
I like this suggestion, but I do still think there is value in showing other results since its not always those starting characters. For example, if I type US, I would expect United States to be shown in the list. However with this suggestion it would be filtered out unless I typed UN.

Since our team is currently focused on the Cart and Checkout experience powered by blocks I reviewed this behavior in the blocks experience. It looks as though its better there because the top results match the starting characters:

![Screenshot 2023-10-25 at 11 34 57](https://github.com/woocommerce/woocommerce/assets/90977/6b303afc-672b-478f-bfc8-613852baa100)

So with this in mind, I think we can close this issue.
