### ISSUE TITLE
Improve `Form` component performance

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#36102]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently the [`Form` component](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/form) stores its state within the Form component using `useState`, this causes every nested field `render` function to be triggered on every form update (meaning every character a user types).
This is fine for smaller forms with just a couple fields, but quickly becomes a bottle neck for larger forms.

We should look into ways of updating the `Form` component to avoid this. We may want to use a 3rd party package for this like: [react hook form ](https://react-hook-form.com/) which has already tackled this issue, or work off of what Gutenberg has done with its editor by the use of redux (see this article in relation to that: https://riad.blog/2020/02/14/a-journey-towards-a-performant-web-editor/ ) here is also an example of how Gutenberg is used when creating a post edit form from scratch: https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/data-basics/3-building-an-edit-form.md

**Acceptance criteria:**
These are two core items, but there are probably others.
- [ ] Nested React fields render method should not be triggered on every form update
- [ ] Nested fields should have the ability to listen to other field changes specifically

**Comment by nathanss** [comment]
@joelclimbsthings @louwie17 
Hello, I opened [this draft PR](https://github.com/woocommerce/woocommerce/pull/36655). 
Can you check it out and let me know if you think this is the right track?

Some insights so far:
- I don't see a good way of adding react-hook-form as a drop-in replacement for our Form. We would have to review all the fields and adapt accordingly, like how I did with the name field (am I missing something?).
- Since we use UI components and not native HTML elements, we would need to wrap our fields with the Controller component, [as described here.](https://react-hook-form.com/get-started#IntegratingControlledInputs)
- react-hook-form doesn't have an equivalent of a global “validate” function from what I've seen. We would possibly have to migrate the logic of the [validate function.](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/product-validation.ts#L84) Validations seem to be more decentralized, each on it's own field ([example in docs](https://react-hook-form.com/api/useform/register#options)).
- There's a lot of logic in the current Form's `handleSubmit`, `getInputProps`, `getCheckboxControlProps`, and `getSelectControlProps` that we will need to rewrite. react-hook-form's register function only returns `onBlur`, `onChange` , `ref` and `name`.

**Comment by nathanss** [comment]
@louwie17 @joelclimbsthings 

I ran the following test script on `trunk` and on the [branch of this PR](https://github.com/woocommerce/woocommerce/pull/36655):

1. Fill name: Notebook
2. Click on categories, type 'Computer' and select 'Computer'
3. Check 'Feature this product'
4. Click on Summary and type 'Notebook''
5. Click on Description and type 'Notebook'

I throttled CPU by 6x.
I profiled with React Developer Tools.
Then I saved the profile json and wrote this program to add all the render duration times:
```js
"use strict";

const fs = require("fs");

const data = JSON.parse(fs.readFileSync(process.argv[2]));

const totalRenderTime = data.dataForRoots[0].commitData.reduce(
  (acc, value) => acc + value.duration,
  0
);

console.log(totalRenderTime);
```

These are the results, in milliseconds:

New Form
1519.8000001460314

trunk
2281.900000035763

It seems to have reduced render time by around 33%, for a Form with 5 fields. I would expect this difference to increase based on the number of form elements.

**Comment by nathanss** [comment]
@louwie17 Here's a video of how I tested it


https://user-images.githubusercontent.com/13437655/216044410-5f8178c9-0019-4385-ab8a-3bcaaab70fb5.mov

**Comment by nathanss** [comment]
For reference, here's the profiling without react-hook-form:


https://user-images.githubusercontent.com/13437655/216048721-abe39f2f-2651-485b-bdd9-c329d0c91d4b.mov

Notice how it lags when I type fast.

**Comment by nathanss** [comment]
Hello, here are more benchmarks:

Without react-hook-form:

https://user-images.githubusercontent.com/13437655/216361279-6809d42d-e03f-401d-896f-4a7b78e283d5.mov

Total render time: 4931ms

With react-hook-form:

https://user-images.githubusercontent.com/13437655/216361533-5df15f01-a2dd-4079-9581-d1c1b462f61e.mov

Total render time: 3808ms

It may seem like a small difference, but most of this render time occurs while typing, it's possible to "feel" the UI freezing while typing fast without react-hook-form. I think adopting react-hook-form is worth it.

**Comment by nathanss** [comment]
Closing for now because we're going to move forward with implementing blocks which makes this obsolete.
