### ISSUE TITLE
[Enhancement]: Add a capability to define Shipping Tax rate that is different from the Tax rate

### ISSUE THREAD

**Issue by namiokuzono** [woothemes/woocommerce#36111]
### Describe the solution you'd like

Add an area where shipping rate can be different from the tax rate for products. 

Usecase: 

- Tax class A has 10% tax rate
- Tax class B has 15% tax rate
- Tax for shipping should be 8%

More and more countries could introduce complicated tax structures, so being able to define different tax rate for shipping separately may be considered. 
 

### Describe alternatives you've considered

Something discussed in this thread could be alternatively considered: https://stackoverflow.com/questions/32902664/woocommerce-calculate-tax-based-on-shipping-method

### Additional context

5803903-zen

**Comment by vedanshujain** [comment]
hey @namiokuzono , this should already be possible, although unfortunately its not straight forward. Follow these steps to configure a tax rate just for shipping:

1. Go to WooCommerce > Setting > Tax > Tax options.
2. Create another dedicated rate, say `Shipping` by adding another line in `Additional tax classes` setting area.
3. Click on save. Then go the tab for this newly created rate by going to WooCommerce > Settings > Tax > Shipping rate.
4. Configure it to say 8% for example.
5. Come back to tax options page by going to WooCommerce > Settings > Tax > Tax options. Configure the setting `Shipping tax class` to this newly created `Shipping rate`.

This should give you what you expect. I am going to close the issue because of above way, but feel free to comment back and we can re-open and discuss.
