### ISSUE TITLE
[Enhancement]:  Give option to remove Congratulations on Sale for New Orders in the Emails

### ISSUE THREAD

**Issue by ljgarnes** [woothemes/woocommerce#36360]
### Describe the solution you'd like

My client prints his New Order Email and includes this in his shipment.  He sells fossils.

He wants Congratulations on the sale to be removed from the New Order Email.  

### Describe alternatives you've considered

I found the option to remove it from the mobile template.  Where can I remove it for the email template?

**Comment by shaunkuschel** [comment]
The "Congratulations on the sale." message is initially included in the 'Additional content' field of the admin New Order email, seen below:

<img width="946" alt="Markup 2023-01-26 at 17 50 31" src="https://user-images.githubusercontent.com/10855013/214976328-98cefee5-d9fe-4fec-b041-f223a5037b38.png">

I'd expect that text to be removed from the email after it is deleted from that field but it's still included in the New Order emails.

As a workaround, I used [this code](https://gist.github.com/shaunkuschel/82bf0defe4839859576f9e490c829134) to translate that text string to an empty string, which worked in my case.

**Comment by jorgeatorres** [comment]
Hey @ljgarnes!

Thanks for the report. This does seem like a bug. We're updating the labels and will add this to our backlog. Thanks again!

**Comment by shadimanna** [comment]
@jorgeatorres I can take this one.

From reviewing the code it seems that the "Additional content" will be populated on all email with the default text if it is empty.  I would suggest to simply remove the default functional call within `get_option` [here](https://github.com/woocommerce/woocommerce/blob/e0049fe1d29bbb2a27c9311cf497df9f9cf939a3/plugins/woocommerce/includes/emails/class-wc-email.php#L403) in order to avoid this.

Let me know if you all agree and I can add the PR.

**Comment by jorgeatorres** [comment]
> I would suggest to simply remove the default functional call within get_option [here](https://github.com/woocommerce/woocommerce/blob/e0049fe1d29bbb2a27c9311cf497df9f9cf939a3/plugins/woocommerce/includes/emails/class-wc-email.php#L403) in order to avoid this.

@shadimanna: If I understand correctly, I believe you're right. The tricky part here is that we don't necessarily want to remove _using_ the default, as that's required, for example if you haven't customized the e-mail at all and the setting doesn't even exist in the options table.

The thing is that the [`WC_Settings_API::get_option()`](https://github.com/woocommerce/woocommerce/blob/b0f042e252cd7adeabfe6c131734c3b0aa40bd36/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php#L283-L284) (which `WC_Email` uses) doesn't really differentiate between a non-set value and an empty string *when* the second argument is passed.

My only concern is whether this could affect other e-mails in a bad way, so maybe we could limit the fixes to the PR to the new order email (`WC_Email_New_Order`) for now and see how it goes.

Let me know if you have any questions.

**Comment by shadimanna** [comment]
@jorgeatorres I am continuing to investigate this function [WC_Settings_API::get_option()](https://github.com/woocommerce/woocommerce/blob/b0f042e252cd7adeabfe6c131734c3b0aa40bd36/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php#L283-L284). It seems to me that if it is **not** set it WILL use the default value, however **if it is set to empty** it will then set the field to `$empty_value`.  We want the former but not the latter in the case of "Additional content" I believe, therefore we should not pass `$empty_value` to avoid the default being shown when the field is set to empty.

Let me run some tests on a fresh install and confirm my assumptions.  Is it possible to continue this tomorrow or does it have to be by end of day?

**Comment by jorgeatorres** [comment]
> Is it possible to continue this tomorrow or does it have to be by end of day?

Of course you can continue! We're committed to following-up on reviews/etc. not only through this day but until completion. Feel free to come back to this tomorrow.

**Comment by jorgeatorres** [comment]
As for your question, I think you're right but we don't necessarily need to modify `get_option()` as that might end up affecting other things. I believe we could just override [`get_additional_content()`](https://github.com/woocommerce/woocommerce/blob/a7b1beaa05f303d8b933548f421fe2b2d54859c0/plugins/woocommerce/includes/emails/class-wc-email.php#L402-L404) from `WC_Email` *but* in `WC_Email_New_Order`.

In that case I'm pretty sure we can remove the second arg ("the default") in the call to `get_option()` as when unset it'll use the default as specified by the form fields themselves, which `WC_Email_New_Order` correctly sets (and `WC_Email` in general).
I'm hesitant to make that change directly in `get_additional_content()` in `WC_Email` because we can't be certain that other possible implementations of this class set the default `additional_content` key correctly.

In any case, we could start with `WC_Email_New_Order` and maybe move changes up to `WC_Email` or not depending on how things go. What do you think?

**Comment by shadimanna** [comment]
@jorgeatorres sounds good, I have created [PR 37883](https://github.com/woocommerce/woocommerce/pull/37883) which overrides the `get_additional_content()` in `WC_Email_New_Order`.

We can always apply this to other individual email templates of the parent class at a later time.
