### ISSUE TITLE
Vulnerability Detection: Static Analysis

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36440]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Evaluate and determine the cost/benefit to using a Static Analysis tool for discovering vulnerabilities either on the current code base or as part of a PR check.

Consider factors such as cost, effectiveness, developer friendliness, etc. If the addition of Static Analysis makes sense, propose its addition with an RFC.

- [x] Evaluate [Snyk](deepcode.ai)
- [x] Evaluate [Semgrep](https://semgrep.dev/)

**Comment by samueljseay** [comment]
For this task I think I would like to explore: https://www.deepcode.ai/

After evaluating what's on the market right now, I think this stands out as being way ahead of other offerings and its also free for OSS.

@psealock does it sound ok if we do a spike putting this into our CI checks and maybe do some kind of time limited trial to see how effective it is?

**Comment by samueljseay** [comment]
@psealock Is it ok to maybe try an experimental integration instead of starting with the RFC?

I think there is one stand out option for this right now which is https://deepcode.ai 

A quick explore shows it has PR check support and options to scan the whole repository. It's also free for public OSS repositories.

I'm thinking maybe a time limited test with PR checks set to "not required" could help us see whether this tool is valuable. I was not impressed by much else on the market especially because language specific options that are not AI powered are limited in use and many tools produce a lot of false positives which is the biggest problem with getting benefit from a tool like this.

**Comment by psealock** [comment]
>Is it ok to maybe try an experimental integration instead of starting with the RFC?

Absolutely. Evaluate as best you see fit.

See also p6JqRr-8mF-p2

**Comment by samueljseay** [comment]
## Summary of Snyk (deepcode.ai)

Snyk has an easy to use dashboard and performs a scan of vulnerabilities in your code base. It highlighted some issues and I decided to go down the rabbit hole with as many as I could.

Most were false positives because of how we sanitize inputs in various ways on WooCommerce. It was not able to distinguish that, but it did have a very accurate ability to analyze a variable from HTTP origin through to where it was rendered or output. If it wasn't for the issue with picking up various sanitization methods I'd say the output was very good.

It was good also at picking up dependency issues, although due to the nature of DEWP some of these were false positives. I still felt it was good it picked these up because often our package json does not reflect the version we load in some cases so these are worth fixing up.

### Snyk VSCode Extension

Snyk also has a VSCode extension that scans for vulnerabilities and code quality issues. It shows underlining on problems in code but also a tree view summary of problems. **Note that it seems code quality issues were only reported on JS/TS files**


![Image](https://user-images.githubusercontent.com/1281828/213961716-12fc7120-eaee-4586-9b73-08ca81a97e73.png)

The plugin closes the loop on making sure your code is quality I think, because extension + CI checks + scanner dashboard means we will catch problems as early as possible.

Snyk also supports a `.snyk` file that allows you to ignore certain directory or path patterns. This is an important feature to reduce false positives (for example by ignoring vulnerabilities in test code).


### Pricing

Snyk is free for OSS making it an attractive option.

**Comment by samueljseay** [comment]
## Summary of Semgrep.dev


### Dashboard

Semgrep dashboard is similar to Snyk. It shows high/medium/low severity risks in your code base with good descriptions of each. My one gripe with this dashboard is doesn't show the code examples inline like Snyk does, so you need to go to the line of the code in your own environment to explore the vulnerability.

Semgrep reported many similar false positives like Snyk. Semgrep however does seem to report on a wider amount of PHP related vulnerabilities. While I could not validate if any of them were legitimate issues in the time I had I did see some interesting things mentioned such as cookie security, http header manipulation and other issues. I did not see Snyk report on all these things so I **suspect** that Semgrep may be more comprehensively able to target PHP specific issues.

**Also** Semgrep reported on Github CI related vulnerabilities as well. This was not something Snyk did and I think it could be quite valuable to report on these kinds of vulnerabilities.

### Dev tooling

Semgrep is a little worse than Snyk in this case. The user must have brew on mac os and install a staggering amount of dependencies to use the toolchain locally. This is also required to use the VS Code extension but capabilities are similar to Snyk.


### Pricing

The pricing is a problem. I think one of the biggest benefits we will get from these products is to do PR checks on new code to check for vulnerabilities. The cost is free for up to 20 developers. But if you exceed this limit you are expected to pay $40 per dev / per product / per month. This pricing will be untenable for WooCommerce and probably a show-stopper imo.

**Comment by samueljseay** [comment]
**Summary**

### Semgrep

**Semgrep Pros**

* Reports on a slightly wider net of vulnerabilities in PHP
* Reports on Github CI vulnerabilities

**Semgrep Cons**

* Dev tooling exp is slightly worse
* Pricing puts it out of reach
* Lots of false positives

### Snyk

**Snyk Pros**

* Very good tooling experience
* Pricing is free

**Snyk Cons**

* Lots of false positives


### Further Notes

I think it's also worth mentioning that many XSS hotspots found by the editor had linter warnings suppressed around them, suggesting that the linter is picking up many of these situations in PHP already. They were suppressed by the developer for various reasons in these cases (usually sanitization done in some way that lints can't recognize.)

This leads me to believe that linting is picking up most of these false positives already. But that doesn't mean Snyk or similar could not be useful in the PR process, I think it just might get to be annoying as a secondary layer when linting is already giving false positives on these supposed XSS vulnerabilities.

My main concern is the value overall of integrating any of these solutions feels questionable right now. I think we may be better to address training devs to write cleaner, less vulnerable code. 

Some existing "detected vulnerabilities" will be incredibly time consuming to validate. I think part of the problem is that we often use techniques we should avoid in code even if after checking carefully it appears to be safe. If there is an exploit for some of these pieces of code it may be more advanced or difficult to exploit. It would be great if we could avoid these techniques (for example using `innerHTML`) But I do understand sometimes it's difficult to do this. 

### Recommendation

I don't think we should take action to include these tools in our workflow at the moment, but I don't think the discussion should end here.

I'd like to see some process in place for explaining why we suppress lints (e.g. detailed comments) and I would like to see evidence that careful review of XSS potential is being addressed in PRs. At the moment I don't see evidence of any discussion going on in PRs even when code looks very suspicious, so I wonder if we are being careful enough.

cc @psealock
