### ISSUE TITLE
[Enhancement]: Disable postal code field for Chile.

### ISSUE THREAD

**Issue by TheRadicalDreamer** [woothemes/woocommerce#36546]
### Describe the solution you'd like

Disable postal code field for Chile.

We have never used it here. It only uses space in the checkout field.

### Describe alternatives you've considered

Using a custom code like:
    unset($fields['billing']['billing_postcode']);

### Additional context

I have asked for this on #30375

**Comment by vedanshujain** [comment]
Thanks for the report, marking priority low for now as compare to other high priority issues we have open in the repo. Note that this change needs to be backward compatible with payment gateways, shipping providers (who might be expecting zip code) etc.

**Comment by TheRadicalDreamer** [comment]
It will be.

I have all the payment getaways of my country installed on my site.

**Comment by TheRadicalDreamer** [comment]
We have never ever, in 200 years of existence of this country used postcode.

So please disable, it won't affect any payment getaways, and absolutely no shipping provider.

If you check multiple shipping plugins for this country, ALL of them remove the postal code.

So please, it is just a line

**Comment by EstebanForge** [comment]
Chilean here. Also i have made some WP/WC plugins. And i've setup a lot of stores for clients with that combo, since WC 1.0.

Can confirm what @TheRadicalDreamer is saying is true.

Here you have two big stores here in Chile, well know for everybody living here:

https://shottr.cc/s/CZof/SCR-20231020-m1b.png

https://shottr.cc/s/CP1q/SCR-20231020-m1y.png

As you can see, when purchasing something, even as a guest (without account), they never ask for the address's postal code. Never.

Here you have Lider. This is Walmart in Chile.
Even they don't ask for a zip code (postal code) when you want to buy something from them online:

https://shottr.cc/s/CysX/SCR-20231020-m3p.png

So yes. Pretty much what TheRadicalDreamer said. In Chile, we don't use the zip/postal code for purchases made inside and shipped in the same country.

We only have to find our zip/post code, when we buy something outside. Shops like Amazon ask for it.
But it's not useful when a WC store, located in Chile, is sending only inside Chile itself.

Esteban

**Comment by mikejolley** [comment]
Thanks for this feedback everyone. I see that in the current setup, postcode is completely optional in the address form.

> We only have to find our zip/post code, when we buy something outside. Shops like Amazon ask for it.
> But it's not useful when a WC store, located in Chile, is sending only inside Chile itself.

This indicates that some stores may need the field, but stores located within Chile do not. With that in mind its probably best addressed conditionally depending on the store base location. If within Chile, remove the field. Does this sound like what is needed here?

**Comment by EstebanForge** [comment]
Yes, @mikejolley, that seems correct. A sensible solution.

**Comment by TheRadicalDreamer** [comment]
Yes. And to add to that.
Because it is not used here, most of the people don't even know what it is. And I have received emails asking what the postal code is. So it only confuse some users
