### ISSUE TITLE
Create Extension: Call @wordpress/create-block under the hood

### ISSUE THREAD

**Issue by psealock** [woothemes/woocommerce#36575]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Currently, Create Extension is called via

```
npx @wordpress/create-block -t @woocommerce/create-woo-extension my-extension-name
```
It needs to be shortened to 

```
npx @woocommerce/create-woo-extension my-extension-name
```
Use Commander to wrap the call to `@wordpress/create-block`. The motivation for doing this is:

1. Provide an opportunity to make async calls, see https://github.com/woocommerce/woocommerce/pull/35922 for use cases. That PR will likely be abandoned due to no movement from Gutenberg.
2. Shorten the invoking command
3. Provide interactivity so users can craft the resulting repo depending on the example they'd like to create. See https://github.com/woocommerce/woocommerce/pull/36489 for an example.

**Comment by ObliviousHarmony** [comment]
We dove into this in our last team meeting and decided against completing the task. Without any documentation a tool like this provides questionable value over the existing tool provided by WordPress. While it's true that tool provides extra files we don't need, realistically, it's not that hard to delete them.

This kind of generator would make more sense in the context of a new open-source extension development + deployment tool. The `@wordpress/create-block` package is _very_ small, so, it just makes more sense for us to make something ourselves rather than trying to work around the original tool and wrap it.

We will take a look at this kind of generator again when we take a step towards the above.

cc @lsinger because there's an open PR above that we'll just close.
