### ISSUE TITLE
Generated SKU is not updated after name changes in new product management experience

### ISSUE THREAD

**Issue by nathanss** [woothemes/woocommerce#36585]
When creating a new product in product management experience, after choosing an already existing name, all subsequent changes to the name don't update the generated SKU.

Steps to reproduce:

1. Try to create a new product with the same name as an existing one
2. It will fail due to duplicated SKU
3. Update the name to a name that would not generate a duplicated SKU and try to Publish
4. It will fail because it's trying to publish with a generated SKU from the first name

**Comment by Konamiman** [comment]
Additional information:

- This only happens when using the new product editor, since the old one apparently doesn't assign a SKU to newly created products.
- While the received response from the REST call to create the product has the proper "Invalid or duplicated SKU" error message, the UI shows only a generic "Failed to publish product" message, this is also something to improve.

**Comment by octaedro** [comment]
Hey @jarekmorawski,
We're already showing an error for a repeated SKU. Is this error enough or should we do anything else?
Maybe we can add a quick action to the notice we show to let users create another SKU automatically.
![Screenshot 2023-08-08 at 1 59 07 PM](https://github.com/woocommerce/woocommerce/assets/1314156/d2fb54cd-a8b3-4f22-b1eb-7371b80deeba)

**Comment by jarekmorawski** [comment]
Good call! If we can create another SKU automatically, can we do it in the background when the user publishes or updates the product? The desired behavior is described in #36774.

**Comment by AnnaMag** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce/issues/36774.
