### ISSUE TITLE
Product List or categoy List not scrollable the header freezes on the sceen after scrolling down

### ISSUE THREAD

**Issue by Sai777722** [woothemes/woocommerce#36648]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PRODUCTlist or any list doesnt scroll for viewing more products 

### Expected behavior

pRODUCT LIST WILL BE SCROLLABLE

### Actual behavior

pRODUCT LIST WILL BE SCROLLABLE

### Steps to reproduce

![image](https://user-images.githubusercontent.com/97309044/215043921-be1e6386-73e4-4b68-be27-6c273cde4100.png)

### WordPress Environment

Woocommerce<Products

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @Sai777722,

Thank you for raising this issue. However, I can’t reproduce it on my end.

I see that you have several plugins installed, which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
