### ISSUE TITLE
[Enhancement]: Free shipping above $x is not possible without code

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#36667]
### Describe the solution you'd like

I have several WooCommerce stores in which I grant free shipping for orders above $65.

So we have two shipping methods:

- Flat rate at $5 for orders below $65
- Free shipping for orders above $65. This simple structure is not achievable by default on WooCommerce.

 I can set a minimum cart total to qualify for free shipping, but if a customer reaches the threshold, both the free and paid shipping options are displayed, which does not make sense and just confuses the customer, and I have to write a PHP snippet or add a plugin just to remove the paid shipping.

### Describe alternatives you've considered

I've considered a few ways to fix this simple issue:

1. Add a checkbox to the **paid shipping** methods that says "qualifying for other free shipping methods removes this paid shipping method" (because sometimes stores want to set up free and paid shipping methods based on cart total, but also a fast premium shipping method that costs money regardless of the cart total). 
2. Add a checkbox to the free shipping method that says "qualifying for this shipping method hides the following shipping methods:" and the possibility to select one or more shipping methods.
3. Right now, the free shipping method allows to set a minimum cart total to enable it. Why not also allowing to set a maximum cart total to display the paid shipping method? This way, I could set the minimum threshold that qualifies for free shipping, and the maximum threshold that removes paid shipping as an option.

There is also a [WooCommerce developer document](https://woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/) that describes possible solutions with some php snippets, however out there, there are many store managers and merchants who are not developers and this relatively easy-to-fix issue may disincentivize them to use WooCommerce in favor of other platforms.
I would suggest to implement this feature in the core, as it is very easy to do and will not require extensive testing and troubleshooting.

### Additional context

As you can see from the attached screenshot it doesn't really make sense to give customers a choice between the same shipping service. They will contact customer support asking what the difference is between the two options, slowing down the checkout process.

<img width="369" alt="Screenshot 2023-01-28 at 7 06 30 PM" src="https://user-images.githubusercontent.com/47855768/215283599-02bcd9f0-b414-495f-bf5b-dbe1dcd6e723.png">

**Comment by tomxygen** [comment]
Hello, I haven't received a feedback yet.

**Comment by barryhughes** [comment]
Thanks, this seems like a great idea and we agree it would make a nice enhancement.

**Comment by tomxygen** [comment]
Hello. Are there any progress regarding this issue?
I've seen several complaints online regarding the fact that it is impossible to manage free shipping without code or plugins.

**Comment by kloon** [comment]
@tomxygen the title is a bit misleading as free shipping above x is indeed possible without code or plugins. Your issue seems to lie in the fact that if you have multiple shipping methods that are valid, they all display, whereas you would just like to display the free shipping method.

It is not uncommon for stores to have multiple shipping options at checkout, including free and paid ones together. The key I would say to making this understandable for your customers is to label these shipping methods appropriately.

Having full conditional shipping functionality bundled with the core plugin I would argue is out of scope, there are extensions free and paid that would give you this functionality, the official Woo one is [Conditional Shipping & Payments](https://woo.com/products/conditional-shipping-and-payments/) but a google search will also give your free options.

If you really do not want to use a plugin then I would suggest you rethink the labelling of your shipping methods, like changing Free Shipping to `Free Shipping (Orders above $65)` or if your Flat Rate and Free shipping are the exact same add the expected delivery dates to both ie `Flat Rate (3-5 business days)` and `Free Shipping (3-5 business days)`, this will give your customers the clarity that is is the same shipping method, the one is just free. Other options include indicating it on your site using banners that you offer free shipping for orders above $65 if not already, and add a shipping page detailing your shipping options and that there is no difference between your flat rate and free shipping apart from that you qualify for the one if you spend more.

Going to close this request for now but am happy to revisit it if there's enough feedback to support looking into this further, as stated there are more than enough options to overcome the limited core shipping shortcomings, even without you having to spend money or be technical.

**Comment by ResponsiveFlow** [comment]
@kloon thanks for your reply!
I generally don't agree with your verdict, here are the reasons why:

> full conditional shipping functionality bundled with the core plugin [...] is out of scope

I completely agree with that. I'm not saying that there should be any advanced conditional shipping built in core, but "free shipping above X" is arguably the most adopted marketing feature in the entire ecommerce industry and setting the threshold to make the paid shipping free (and removing the paid one) should be easily achievable without having to rely on plugins or additional code.

> It is not uncommon for stores to have multiple shipping options

Yes, there are some stores that do offer multiple shipping options, but the vast majority of online stores offer only one shipping, which is paid below a certain order total and free above that.
That's what customers expect to see. They generally don't care if you ship via DHL, BRT, USPS etc, and even wether it is an express courier or not. They only care about price and delivery time. 

oceansapart.com and gymshark.com are the first two stores that I can come up with that have this kind of policy.

> happy to revisit it if there's enough feedback

I sent the same request in Woo Feature Request Portal and although the portal is not very well known and participated, this feature request is the second most voted: https://woo.com/feature-request/fix-the-free-shipping-for-order-above-x/
