### ISSUE TITLE
Error : Sorry, you cannot list resources. 

### ISSUE THREAD

**Issue by otaku0304** [woothemes/woocommerce#37013]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

I'm using WAMP as localhost and created the Consumer_key, and secrect_key for using woocommerce Rest API, I'm trying this rest API in the postman. First I tried to fetch the list of all products. So this is the endpoint: GET /wp-json/wc/v3/products and coming to my link it will be http://localhost/fashion2000/wp-json/wc/v3/products also used Basic Auth in the place of Authentication given Username = consumer_key , Password = secrect_key. The response is 401 with error : Sorry, you cannot list resources

Also enable Legacy Rest API.

**Comment by WillBrubaker** [comment]
Doesn't Basic Auth require [HTTPS](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https)? Since you're using HTTP, see: [Authentication over HTTP](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http)

**Comment by otaku0304** [comment]
But my link is http://localhost/fashion2000
![site](https://user-images.githubusercontent.com/107242846/222059740-ff7739c5-b64c-406c-9cff-baad5d90f287.png)

If try with "https" I was getting another issue. Below is the picture for that
![https](https://user-images.githubusercontent.com/107242846/222059856-a2885140-49de-4efe-a9e4-ea677adcf997.png)

**Comment by jonathansadowski** [comment]
Hi @otaku0304,

Thanks for the report. As @WillBrubaker mentioned, you won't be able to use Basic Auth for authentication on `localhost`. If you wanted to use https locally, you'd have to setup your local environment with a self-signed certificate and listen on port 443. If you don't want to do that, you'd have to use an auth method other than Basic Auth. More information on that is available [here](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http).

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. I'm going to close this issue, as it looks like this is expected behavior for sites that don't use HTTPS. If this is a mistake or there's something I misunderstood, please feel free to open a [new issue](https://github.com/woocommerce/woocommerce/issues/new/choose) with a detailed list of steps that you took so that we can try and reproduce the issue.

**Comment by rrennick** [comment]
> you won't be able to use Basic Auth for authentication on localhost.

You can use basic auth on a local install by installing `https://github.com/WP-API/Basic-Auth/archive/master.zip`.
