### ISSUE TITLE
[Enhancement]: New empty state for variations - no attributes

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#37139]
When navigating to the `Variations` tab, a new empty state is displayed when no attributes have been assigned to a product with the `Used for variations` option enabled.

It should be noted that at least one global attribute has been created previously but has not been assigned to the product in question.

The empty state message displays an icon and the following text: "Add some attributes in the Attributes tab to generate variations. Make sure to check the Used for variations box. Learn more".

In this message, the word `Attributes` serves as a hyperlink to the `Attributes` section, while the `Learn more` link directs users to the WooCommerce documentation on variable products: https://woocommerce.com/document/variable-product/.

Copy:
```
Add some attributes in the Attributes tab to generate variations. Make sure to check the Used for variations box. Learn more
```
Links:
- Attributes    -> Opens the `Attributes` tab
- Learn more -> https://woocommerce.com/document/variable-product/

<img width="488" alt="image" src="https://user-images.githubusercontent.com/79307566/223403057-a51aa181-75da-441c-b889-76a3d3c9c6be.png">

**Designs:**
`zs56kcy53K7GoGhgyjcQ2R-fi-211%3A34116`

```[tasklist]
### Acceptance criteria
- [ ] Add a new empty state screen for the variations.
```

**Comment by octaedro** [comment]
Hey @jarekmorawski,
During our latest grooming session, the @woocommerce/mothra-enhancements  team realized that we've been working on a similar page [here](https://github.com/woocommerce/woocommerce/pull/36957). The [issue](https://github.com/woocommerce/woocommerce/issues/36658) comes from [this comment](https://github.com/woocommerce/woocommerce/issues/35115#issuecomment-1403910659). Users who navigate to the Variations tab without creating any attributes should see the following form as an empty state.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/79307566/214624354-abcf47ae-0122-43f7-b628-90bb7ffd9fa0.png">

Given this, we're wondering whether we should modify the page again.

**Comment by jarekmorawski** [comment]
The above design makes sense and applies to a different scenario. It could use a minor visual update to align with the newer empty states, but generally, there's a place for it in the flow.

1. The above empty state is shown when no attributes exist in the system (nothing exists when the user navigates to Products > Attributes).
2. The empty state that is the subject of this issue is shown when some attributes exist but have not been added to a product yet.
3. The empty state described in https://github.com/woocommerce/woocommerce/issues/37147 is shown when attributes exist and have been added to the product with the Used for variations box checked.

Let me know if that helps!
