### ISSUE TITLE
[HPOS] Use `SELECT *` instead of individual column names in Order select query

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#37362]
In HPOS, we use verbose table alias names, such as `order_operational_data`, `wc_order` etc. This issue scopes changing it to `SELECT *` notation so that length of our final select query is small. See methods: `get_op_table_alias`, `get_address_table_alias` in OrderTableDatastore.

**Comment by tommyshellberg** [comment]
I'd like to work on this one 🤚 
I've got a working solution but I'd like to test the performance after changes are made.
I was thinking of using the [Smooth Generator](https://github.com/woocommerce/wc-smooth-generator) plugin on a local Docker install to generate a bunch of Orders to properly test it.
@vedanshujain since you worked on this originally and did some performance testing, could you provide some advice on how to test the performance of the query over a high sample size or if the query should be tested with a site that has a large number of WC Orders?

**Comment by vedanshujain** [comment]
@tommyshellberg thanks!

I don't think on a vanilla install, swapping queries with SELECT * instead of listing out individual column names will have any measurable impact. It would affect only those hosts that are running regexes on queries before they are fired (i.e. they now have to a scan a smaller query instead of a longer one).

Although, note that because of scope change in the last edit, I am don't think its a good candidate for a first issue and will require knowledge of WC beforehand, so I am removing that label.

**Comment by tommyshellberg** [comment]
I've unassigned myself from this one as I've had other priorities and this one will require more intimate knowledge of WC core internals.
