### ISSUE TITLE
Remove use of `page.fill()` in variable product e2e tests

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#37458]
## Issue description

The use of `page.fill()` is discouraged by Playwright ([doc](https://playwright.dev/docs/api/class-page#page-fill)). Instead, `locator.fill()` should be used. This is because:

* Tests are more resilient when they use "user-facing attributes and explicit contracts such as `page.getByRole()`. We can change the implementation (DOM, classes, etc.) and as long as how the user perceives the UI (roles, labels, etc.) stays the same, our tests will still function.
* If multiple elements match the selector passes to `page.fill()`, by default the first one found will be used. This can be a source of unexpected errors and flakiness. `locator.fill()`, by default, will throw an error and fail the test if more than one element matches the criteria for the locator.

## Acceptance criteria

- [ ] Remove all use of `page.fill()` in [`plugins/woocommerce/tests/e2e-pw/tests/merchants/create-variiable-product.spec.js`](https://github.com/woocommerce/woocommerce/blob/82a172cd066423601841cda945bbe48535552334/plugins/woocommerce/tests/e2e-pw/tests/merchant/create-variable-product.spec.js#L4) with `locator.fill()` based imlpementations
- [ ] All tests continue to reliably pass

**Comment by ravinderk** [comment]
@mattsherman I would like to work on this

**Comment by rodelgc** [comment]
Hello @ravinderk 👋 Thank you very much for picking this up! This is very much appreciated. 😄 

For the meantime, I assigned to you this [first issue](https://github.com/woocommerce/woocommerce/issues/36698) and will keep this `page.fill()` one open for other contributors for the meantime. Once the first issue is done, and if this issue is still unassigned to anybody else, then I or any of the upcoming facilitators can assign this issue to you.

**Comment by mattsherman** [comment]
@ravinderk Thanks for volunteering on this one... as @rodelgc mentioned, any of the facilitators can assign this to you once you wrap up the other issue. Thanks for helping to make WC's e2e tests more robust!
