### ISSUE TITLE
[Enhancement]: Improve the transition from the WCPay KYC to the Payments Task

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#37542]
### Describe the solution you'd like

When a user completes the KYC and returns to the task, the screen does not provide any acknowledgement the merchant completed the process. Instead a list of other payment providers is shown.

To solve this a completion screen could be shown to provide a better transition and acknowledge the progress the merchant has made.

**Edit:**

Per the comments below, we can redirect to the WooPayments success screen. The return URL is handled in the WooPayments plugin [here](https://github.com/Automattic/woocommerce-payments/blob/a090a8571feafb937a3271d9c56faf356f612b1d/includes/class-wc-payments-account.php#L1403-L1404). 

I think the URL will be `static::get_overview_page_url()` + `&wcpay-connection-success=1`

We will now also need to add a new `$wcpay_connect_from` case to handle LYS. This should redirect back to the LYS hub.

**Comment by elizaan36** [comment]
EDIT: The Payments Overview is too busy to present this full card, and it has the potential to get lost. Refer to [this comment ](https://github.com/woocommerce/woocommerce/issues/37542#issuecomment-1543304842)for the correct recommendation. :)

__

Hey @brandonwanA8C @daquinons I noticed this issue came about from the recent onboarding user flow review and considering the potential for positive impact on the experience makes sense to be prioritized as separate from the experiment and phased rollout of the progressive onboarding project.

Once the user completes the KYC, rather than being directed to the list of extensions on the Payments task, we'll direct them to the WCPay Overview with the new design.

<img width="1440" alt="Overview" src="https://user-images.githubusercontent.com/5121465/236496327-706aec31-9527-4181-be7e-6624e06ec994.png">

Here they'll see a motivational message celebrating all the work they've done, and will have clear recommendations for APMs that work alongside WCPay. Thoughts?

**Comment by brandonwanA8C** [comment]
this was one of the recommendations from Beau. this is fine although it is hard to quantify the "lift" from UX & data.
since this is post-KYC, i'd recommend this change be considered away from PO scope to minimize scope-creep. 
will let @daquinons assess the eng effort required.

**Comment by daquinons** [comment]
@elizaan36 @brandonwanA8C Thanks for the ping!

It seems like this issue is for Ghidorah to handle the redirection after completing the Core setup checklist. Redirecting to the Payments screen with the new success message could be a good solution.

@elizaan36 About the APMs in Payments, we'll need an issue in WC Payments repo to prioritize, as that part is independent of this issue scope. Could you please create it and add any additional details on it? 🙏 (Things like, do we want to always display APMs every time merchants enter into the Payments screen, or only when the success banner is shown after KYC?). With that in place, we'll be able to tackle it after PO project.

Thanks a lot!

Extra context for @adrianduffell The param needed in order to display the success banner is `&wcpay-connection-success=1`. You can see that in the testing instructions of this PR https://github.com/Automattic/woocommerce-payments/pull/5992

**Comment by elizaan36** [comment]
For this could we simply present the "Set up additional payment methods" task in the "Things to do" list?

<img width="766" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5121465/1fe41ea1-a3ba-4bea-ad52-d78e4bb31895">

It was my understanding that any payments-related tasks would appear on both Woo Home and the overview but I don't think this one does for some reason. It would redirect the user to the "Set up payments" task with all recommended APMs and dismiss if it's actioned on from either place.

<img width="834" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5121465/d9385d06-206b-4980-85ce-90978131fef8">

The task currently shows Afterpay and Affirm but those would be removed to focus on enabling the WooPayments methods.

While we're at it, we have a new design for this screen that includes a prompt to enable the WooPayments methods such as BNPL and LPMs. Let me know your thoughts on this.

**Comment by brandonwanA8C** [comment]
Marking as Product/UX enhancement, backlog for H2/future onboarding-related UX related improvements.

**Comment by brandonwanA8C** [comment]
<img width="933" alt="Screenshot 2023-07-10 at 3 05 06 PM" src="https://github.com/woocommerce/woocommerce/assets/113071364/1e3d944e-7328-4f33-aa64-ff24cb582e11">

**Comment by brandonwanA8C** [comment]
saw the similar "celebration screen" for PO completion above.
if the [original UX](https://github.com/woocommerce/woocommerce/issues/37542#issuecomment-1543304842) has not been implemented, we can prioritize it for Q3/4.

**Comment by adrianduffell** [comment]
Thanks for jumping onto this one folks!

@daquinons Just to confirm -- is the solution from Ghidorah's side just to redirect to the WCPay Payments → Overview screen and add the param `&wcpay-connection-success=1`?

**Comment by daquinons** [comment]
@adrianduffell That's correct!

**Comment by psealock** [comment]
@adrianduffell Is this issue still relevant?

**Comment by adrianduffell** [comment]
> Is this issue still relevant?

@psealock Yes, I think so. I'll schedule it in for our next cycle.

**Comment by elizaan36** [comment]
well hello! I was trying to remember where I had shared this before. 

@vladolaru FYI the Ghidorah team will create the redirect from the Stripe KYC to the Payments Overview as part of this change. Should we create a new issue to [remove the BNPL options](https://github.com/woocommerce/woocommerce/issues/37542#issuecomment-1543304842) from the Payments task when WooPayments is enabled since they're redundant with the bundled payment methods?

**Comment by vladolaru** [comment]
Thanks for finding this @elizaan36. Yes, I think for the removal of the BNPL options a separate issue would be best, but I'll leave Ghidorah folks to decide.

**Comment by adrianduffell** [comment]
> Should we create a new issue to https://github.com/woocommerce/woocommerce/issues/37542#issuecomment-1543304842 from the Payments task when WooPayments is enabled since they're redundant with the bundled payment methods?

Hey @elizaan36, yes could you please create a new issue for this?

**Comment by elizaan36** [comment]
Hey yep, the new issue was created here! [Remove BNPL options in WooCommerce core > Additional payments options #8603](https://github.com/Automattic/woocommerce-payments/issues/8603)

**Comment by chihsuan** [comment]
> We will now also need to add a new $wcpay_connect_from case to handle LYS. This should redirect back to the LYS hub.

Hey @adrianduffell Since we have implemented a catch-all return to LYS hub in https://github.com/woocommerce/woocommerce/pull/47606 Do we still need this?  🤔
