### ISSUE TITLE
[COT] Compatibilize order query arguments between HPOS and non-HPOS

### ISSUE THREAD

**Issue by Konamiman** [woothemes/woocommerce#37564]
## The problem

Right now querying orders with `WC_Order_Query` or `wc_get_orders` using arguments presents incompatibilities between the cases of the new tables or the posts tables being authoritative. This forces to modify existing code so that it uses one set of arguments or other depending on which table is authoritative.

As an example, this is how to get all the orders for a given customer when the posts table is authoritative:

```php
$orders = (new WC_Order_Query([
	'post_type' => 'shop_order',
	'meta_query' => [
		['key'=>'_billing_email', 'value' => 'customer@example.com']
	]
]))->get_orders();
```

This won't work when the new tables are authoritative. Instead, this is the correct query in that case:

```php
$orders = (new WC_Order_Query([
	'field_query' => [
		['field'=>'billing_email', 'value' => 'customer@example.com']
	]
]))->get_orders();
```

## The solution

Some adapter code should be put in place so that either set of arguments work on either set of tables; by doing that, code that already queries orders in the correct way (by using `wc_get_orders`, `WC_Order_Query` et al) won't need any modification (and doesn't even need to know that HPOS is a thing).

[The column mappings in OrdersTableDataStore](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L483-L494) can be used as the starting point to know what needs to be adapted.

For the new -> old conversion, the adapter code should probably go in `OrdersTableQuery` and/or in `OrdersTableMetaQuery`. For the old -> new conversion it looks like the code should go in `WC_Order_Data_Store_CPT`.

**Comment by sibelius** [comment]
why meta_query is ignored here https://github.com/woocommerce/woocommerce/blob/6f818f7787aa752c14c7fec7da7bed41554f5932/plugins/woocommerce/includes/data-stores/class-wc-data-store-wp.php#L284

?

**Comment by matthew-muscat** [comment]
Hi WooCommerce team,

We ran into this gap as part of an upgrade to a plugin we develop — this resulted the `wc_get_orders ` silently ignoring `meta_query` filters when a merchant is configured to use legacy order storage.

This resulted in a significant bug that impacted merchants using the WooCommerce platform.

Beyond a fix to close the gap, can i also suggest the following is considered...

1. Update the documentation of `wc_get_orders` to make it clear that `meta_query` filters are not supported when operating in legacy order storage mode
2. Throw an warning / error / exception (at least something) to indicate that the `wc_get_orders` call does not support using `meta_query` filters when a store is operating in legacy order storage mode

IMO silently ignoring query filters should be avoided

**Comment by kkmuffme** [comment]
This is a major issue, since it's not documented at all anywhere too, but silently leads to inconsistent behavior on often huge WooCommerce stores with millions in sales...

**Comment by Sartoric** [comment]
I'm facing the meta_query issue too.
I had to debug the whole process to find that the meta_query was simply ignored in the final SQL, having all the orders returned by the query.
If the **wc_get_orders()** function must not be used for legacy orders, It would be at least useful to return no orders making it easier to find that something is wrong.

I second the needs to update the documentation.

[I've added a new bug report](https://github.com/woocommerce/woocommerce/issues/46076)

**Comment by jorgeatorres** [comment]
Hey everyone!

Thanks for all the feedback! We agree that the current situation is not ideal, but making the posts implementation fully compatible with the new querying functionality would be too complicated (or non-performant) due to the differences in the underlying database structure.

That said, we agree that the current situation is not ideal and order queries shouldn't silently fail or return the wrong results. Even though [the docs](https://developer.woocommerce.com/docs/hpos-order-querying-apis/) already indicate that the new querying features belong to HPOS, I've added a task in #40699 to make sure we make that even clearer.

At the same time, PR #47457 takes care of adding a doing-it-wrong warning when the new query arguments are used in a non-HPOS context.

As such, I'm closing this issue in favor of the other two related ones, but feel free to re-open if I've missed or misinterpreted anything in this discussion. Thanks again!
