### ISSUE TITLE
Checkout field removal causing undefined value rendering in WooCommerce 7.5.1

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#37627]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**EDIT: The problem also affects WooCommerce default settings in `Appearances > Customize > WooCommerce > Checkout`.** [Please check my comment below for more details.](https://github.com/woocommerce/woocommerce/issues/37627#issuecomment-1501222835)

Reported in zd-6174238

The removal of checkout fields in WooCommerce 7.5.1 is causing a problem. While the removed fields are no longer displayed in the checkout and cart, adding another product can result in the fields rendering with an "undefined" value.

<img src="https://d.pr/i/sVOnfw+" alt="">
Link to image: https://d.pr/i/sVOnfw

### Expected behavior

The checkout fields to be removed.

### Actual behavior

They are removed from checkout but replaced with "undefined" when visiting the cart page.

### Steps to reproduce

1. Remove a checkout field as  mentioned in this guide: https://woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/
2. Add a product to the cart and navigate to the checkout page, the field will be removed.
3. Now go back to the shop page, add another product then navigate to the cart page again, the removed file will be in the cart page replaced with "undefined" as shown in the screenshot above.

### WordPress Environment

```
`
### WordPress Environment ###

WordPress address (URL): https://xxxxx.wpcomstaging.com
Site address (URL): https://xxxx.wpcomstaging.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

`
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Babylon1999** [comment]
One more case in zd-6126229 , although it's a bit different. 

The merchant has a snippet that removed billing details for virtual products. When they go back to the shop page and add a physical product all billing fields are set to `undefined` on **checkout**.

**Comment by Gilou24** [comment]
Hi,
I have the same problem : https://wordpress.org/support/topic/undefined-text-on/

**Comment by rynaldos** [comment]
Howdy, 

As far as I can tell, this isn't a bug. I don't see any recent updates to the core code have not introduced any changes to the cart or checkout pages that would affect the behavior in question. It appears that the issue only arises with custom code. Additionally, the behavior of the custom code is correct, even under mixed cart conditions. When the previously "unset" fields are restored, the fields will initially display as "undefined" until filled in, as the cart is stored in the customer session and the fields were never populated. At this point, it still needs to be filled in. 

The issue in question can only be replicated when the user is in a current cart session and using custom code. If the custom code is removed and the user session is cleared, the issue cannot be replicated with the core code alone. Therefore, the issue lies solely with the custom code and needs to be addressed through an update of the code.

You can update the code to something like this, to include an additional condition check: 

```
add_filter('woocommerce_checkout_fields', 'bbloomer_simplify_checkout_virtual', 10);

function bbloomer_simplify_checkout_virtual( $fields ) {

   $only_virtual = true;

   foreach( WC()->cart->get_cart_contents() as $cart_item ) {
      // Check if there are non-virtual products
      if ( ! $cart_item['data']->is_virtual() ) {
         $only_virtual = false;
         break;
      }
   }

   if( $only_virtual ) {
       // Unset billing fields only if they have been set already
       if (isset($fields['billing']['billing_company'])) {
           unset($fields['billing']['billing_company']);
       }
       if (isset($fields['billing']['billing_address_1'])) {
           unset($fields['billing']['billing_address_1']);
       }
       if (isset($fields['billing']['billing_address_2'])) {
           unset($fields['billing']['billing_address_2']);
       }
       if (isset($fields['billing']['billing_city'])) {
           unset($fields['billing']['billing_city']);
       }
       if (isset($fields['billing']['billing_postcode'])) {
           unset($fields['billing']['billing_postcode']);
       }
       if (isset($fields['billing']['billing_country'])) {
           unset($fields['billing']['billing_country']);
       }
       if (isset($fields['billing']['billing_state'])) {
           unset($fields['billing']['billing_state']);
       }
       if (isset($fields['billing']['billing_phone'])) {
           unset($fields['billing']['billing_phone']);
       }
       add_filter('woocommerce_enable_order_notes_field', '__return_false');
   }

   return $fields;
}
```

Then, clear the customer session here:

<img width="1245" alt="Screenshot 2023-04-09 at 11 47 38" src="https://user-images.githubusercontent.com/89896100/230766089-d96fe034-9589-49ca-97a8-e2c7ef9621b4.png">

Now, add the virtual product only. You'll see this: 

<img width="668" alt="Screenshot 2023-04-09 at 11 48 50" src="https://user-images.githubusercontent.com/89896100/230766074-bb43c337-8382-495e-a63c-4fd4ed3cffa5.png">

Now you go (directly from the cart page), back to the shop page to add the physical product. You'll see this: 

<img width="736" alt="Screenshot 2023-04-09 at 11 49 03" src="https://user-images.githubusercontent.com/89896100/230766070-0a8bf563-fc3f-43f2-a541-b48147612ab4.png">

The checkout fields displays correctly in both cases — when only virtual products (fields unset), or fields restored when the cart is mixed. 

Again, when only core (without custom code), it works as it should be.

**Comment by Gilou24** [comment]
Hello rynaldos,
Thank you for your reply
The **problem only occurs if you go to the checkout page** (not just to the cart) after adding a virtual product... and your code then changes nothing, unfortunately ("undefined" appears always in the address entry fields).
We agree: it works well without additional code (but the purpose of this code is precisely not to ask for an address when it is not necessary)... And the different plugins for editing checkout fields (j 've tried several) have the same problem since version 7.5.0 of woocommerce (while it works perfectly with version 7.4.2). So it doesn't necessarily mean that there is a woocommerce bug, but that the existing fields editing codes are no longer compatible...
So I'm looking for a solution to make them compatible.
Regards

**Comment by Babylon1999** [comment]
Hello @rynaldos,

Thank you for the input! 😃

Although your approach makes sense by checking if there's a value and then removing it, however, [on my test site it's the same result.](https://d.pr/i/bMEB98)

In case I didn't mention the problem is reproducible from code by [this guide.](https://woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) 

Furthermore, I tried checking if WooCommerce's default checkout settings are also affected by this and can confirm they are.

To reproduce this issue, hide all checkout fields from "`Appearances > Customize > WooCommerce > Checkout.`" Next, navigate to the shop page and add a product, proceed to checkout, go back to the shop page, add another product, and you'll be greeted with this:

The reason only address 2 renders as undefined is that it's the only one that will render on the cart page by default, other hidden fields will be in checkout only.

<img src="https://d.pr/i/XEhP3D+" alt="">
Link to image: https://d.pr/i/XEhP3D

**Comment by Babylon1999** [comment]
2 more cases in zd-6080751

**Comment by Martje65** [comment]
Hello i have the same problem on a mint Wordpress / Woocommerce instal : https://wordpress.org/support/topic/woocommerce-undefined-address-line-2-bug/

**Comment by stoltzrx** [comment]
6205726-zen

**Comment by Konamiman** [comment]
This bug had been introduced in https://github.com/woocommerce/woocommerce/pull/36275, which has been reverted in https://github.com/woocommerce/woocommerce/pull/37463 so it will be fixed in the next release.

**Comment by anon191983** [comment]
That's good news - thank you! Are we talking about the next release of amazonpay-plugin oder woocommerce (or both)? When will it be released?
