### ISSUE TITLE
[Enhancement]: woocommerce_before_quantity_input_field & woocommerce_after_quantity_input_field with $args

### ISSUE THREAD

**Issue by Stas0238** [woothemes/woocommerce#37661]
### Describe the solution you'd like

Recently you made some improves for quantity-input to change input type to 'text', 'number' or 'hidden' according to specific conditions current product has (https://prnt.sc/8oZEpssKCK10). 
In my theme I improved basic browser input with plus & minus buttons for increasing/decreasing quantity of product to buy but now for some product my clients see next issue -> https://prnt.sc/UgNC32KEN6pN, those buttons are showing when they are not really needed but the input is hidden because of the 'Limit purchases to 1 item per order' option enabled -> https://prnt.sc/K4Gmn4dKl895.

What I would ask you to implement is to add ```$args``` param to woocommerce_before_quantity_input_field & woocommerce_after_quantity_input_field hooks like here -> https://prnt.sc/Tlm5z_uamkLt
In such case I (and I think many other theme/plugin developers) will be able to check if those plus/minus button are needed to add for this product -> https://prnt.sc/lJA0Bcs0Mz20 

Additionaly to say I know that I can rewrite that file in my theme but that is my better to have globally so anyone could make it fixed in theme/plugin's code without copying file inside that is also not allowed to do in 3rd-plugin from WooCommerce plugin.

Hope you understand my position fully and you will implement this small but vital thing in next update !

Regards, @stas0238

**Comment by mikejolley** [comment]
First off, thanks for your feedback. I can see why this might be useful when customising the templates via PHP, however, our primary focus is now on the new Cart and Checkout experience powered by blocks. These blocks have +/- buttons built in, so that would be handled for you.

For the current templates, I can think of a few workarounds to this issue without implementing a change to the template hooks. For example:

- Forcing `woocommerce_quantity_input_type` to number so its never hidden
- Conditionally enqueue/dequeue the buttons during `woocommerce_quantity_input_args` (which has a $product arg you can reference) so that the buttons are only added under specific circumstances.

Both can solve the problem without using a template override. I hope this helps!
