### ISSUE TITLE
[Enhancement]: Make payment_method_title translatable

### ISSUE THREAD

**Issue by Estalhun** [woothemes/woocommerce#37678]
### Describe the solution you'd like

**Make payment_method_title translatable via a new filter hook.**

My proposal is as follows:
#1. Add a new filter in the class-wc-oder.php to this function:

`public function get_payment_method_title( $context = 'view' ) {
	return $this->get_prop( 'payment_method_title', $context );
}`

Modify to:
`public function get_payment_method_title( $context = 'view' ) {
	return apply_filters( 'woocommerce_get_payment_method_title', $this->get_prop( 'payment_method_title', $context ) );
}`

Filter hook to change the text.
TranslatePress saves the locale to the postmeta table, so easy to restore the order's language. :-)

**Problem description:**
I use TranslatePress plug-in (similar to the 'Say what?') on more site, but the payment method title is not translatable because the gettext function is not used on the existing 'woocommerce_order_get_payment_method_title' hook.
I think the origin of the problem is:

- The customer leaves the site to pay via Paypal or credit card.
- The payment provider mark the order as paid via IPN.
- The email sent but the determine_locale() or get_locale() function returns the site's default language.
- The customer returns to the shop.

So, some part of the email sent to the user is in the site's default language but the most of parts are in the user's language.
The payment method title is in the site's default language in the customer's email.

I put this code to the functions.php to log the strings:
`add_filter('woocommerce_order_get_payment_method_title','my_payment_method_title');
function my_payment_method_title($title) {
    $locale = '';
    $locale = determine_locale();
	error_log('Payment method title: ' . $title . ' Locale: ' . $locale);
    if( is_admin() && !wp_doing_ajax() ) { return $title; }
    return __($title,'woocommerce');
}`

The result:
[12-Apr-2023 13:24:20 UTC] Payment method title: PayPal Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: Utánvét Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: Utánvét Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: Bankkártya Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: Bankkártya Locale: en_GB

The payment method title is Hungarian (default language of the site) even though the locale is en_GB.

### Describe alternatives you've considered

#2. (if the #1 has any serious problem)

Modify the fucntion in the class-wc-oder.php:

`public function get_payment_method_title( $context = 'view' ) {
	return $this->get_prop( 'payment_method_title', $context );
}`

To:
`public function get_payment_method_title( $context = 'view' ) {
		return __( $this->get_prop( 'payment_method_title', $context ) );
}`

In the second case I can translate the text but I can't use the get_locale() function. :-(

#3. (if the #1 or #2 have any serious problem)

Modify the function in the class-wc-oder.php:

`public function get_payment_method_title( $context = 'view' ) {
		return $this->get_prop( 'payment_method_title', $context );
}`

To:

`if( !function_exists('get_payment_method_title') ) {
	public function get_payment_method_title( $context = 'view' ) {
		return $this->get_prop( 'payment_method_title', $context );
	}
}`

In this case I can override the original function before WC try to create this function. :-(

Bye,
Estal

### Additional context

https://drive.google.com/drive/folders/1yeLkcA4FuCCEB1fTYT7dGgXf14F_vAu6?usp=share_link

**Comment by barryhughes** [comment]
Thanks for the suggestion, which we also discussed in more detail [over here](https://github.com/woocommerce/woocommerce/pull/37363).

- It probably is not appropriate (and would be against best practices) for us to pass these titles through `gettext`.
- We have an existing filter hook `woocommerce_order_get_payment_method_title` which can be used to achieve essentially the same thing as in the proposal.

Since that existing hook would seem to solve the problem, I'll go ahead and close this issue.

**Comment by Estalhun** [comment]
> Thanks for the suggestion, which we also discussed in more detail [over here](https://github.com/woocommerce/woocommerce/pull/37363).
> 
>     * It probably is not appropriate (and would be against best practices) for us to pass these titles through `gettext`.
> 
>     * We have an existing filter hook `woocommerce_order_get_payment_method_title` which can be used to achieve essentially the same thing as in the proposal.
> 
> 
> Since that existing hook would seem to solve the problem, I'll go ahead and close this issue.

My question is simple. The existing 'woocommerce_order_get_payment_method_title' how solve the translation problem if the title does not get through gettext()?

The result of the existing hook:
[12-Apr-2023 13:24:20 UTC] Payment method title: PayPal Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: **Utánvét** Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: **Bankkártya** Locale: en_GB

The result of the existing hook should be:
[12-Apr-2023 13:24:20 UTC] Payment method title: PayPal Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: **Cash on delivery** Locale: en_GB
[12-Apr-2023 13:24:20 UTC] Payment method title: **Credit card** Locale: en_GB

**Comment by barryhughes** [comment]
I'm not sure I follow your examples. What does your filter function look like?

**Comment by Estalhun** [comment]
> I'm not sure I follow your examples. What does your filter function look like?

I simply want to send the string through the gettext() function:
`add_filter('woocommerce_get_payment_method_title', 'my_payment_method_title'); 
function my_payment_method_title($title) { 
if( is_admin() && !wp_doing_ajax() ) { return $title; }
return wp_kses( __($title,'woocommerce'), array('strip') ); 
}`

Note that the same code returns the string in the site's default language using the existing `woocommerce_order_get_payment_method_title` hook.

**Comment by barryhughes** [comment]
OK, so, modifying your snippet to use the existing hook:

```php
add_filter( 'woocommerce_order_get_payment_method_title', 'my_payment_method_title' );

function my_payment_method_title( $title ) {
	if ( is_admin() && ! wp_doing_ajax() ) {
		return $title;
	}

	return wp_kses( __( $title, 'woocommerce' ), 'strip' );
}
```

With that in place, my testing shows that the `$title` ***is*** successfully passed through `gettext`. Of course, if you manually re-send emails from the order editor, that will not happen because of the `if` statement at the start of the function. 

You can see the translation at work if you modify the snippet as follows, then place an order as a customer:

```php
add_filter( 'woocommerce_order_get_payment_method_title', 'my_payment_method_title' );

function my_payment_method_title( $title ) {
	if ( is_admin() && ! wp_doing_ajax() ) {
		return $title;
	}

	$gettext_filter = function( $text ) use ( $title ) {
		return ( $text === $title ) ? "TRANSLATED [$title]" : $title;
	};

	add_filter( 'gettext', $gettext_filter );
	$translated_title = wp_kses( __( $title, 'woocommerce' ), 'strip' );
	remove_filter( 'gettext', $gettext_filter );

	return $translated_title;
}
```

The resulting email (order received notification) should look something like this (note the 'translated' payment gateway title):

<div align="center"><img width="500" alt="translated-gateway-title" src="https://user-images.githubusercontent.com/3594411/231822557-ee2dcbe9-a64a-48af-ac5f-510e58a6409f.png"></div>

I think your case is a little more complex, as it sounds like you have a multi-language setup involving TranslatePress. All I'm trying to make clear, though, is that:

- The existing filter hook is sufficient/adding the new hook you proposed does not fundamentally change things.
- It is possible to pass the payment gateway title through `gettext` if you wish to do so.

Applying the correct language, in a multi-language scenario, is a different problem and is beyond the scope of what we can do here.
