### ISSUE TITLE
E2E: Split `can create product, attributes and variations, edit variations and delete variations` into smaller tests to avoid timing out

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#37724]
### Describe the solution you'd like

The `can create product, attributes and variations, edit variations and delete variations` test has become flaky due to a new, different reason this time: It's reaching the 90sec test timeout in CI. Even a [passing run](https://github.com/woocommerce/woocommerce/actions/runs/4696016428/jobs/8325811285#step:5:151) of that test already reaches 1.4mins.

<img width="1003" alt="M1EPXoEgHO" src="https://user-images.githubusercontent.com/4509348/231948974-c88477b7-2cda-4ccd-83b5-cb56245813bc.png">

So I'm suggesting to split this into smaller tests, maybe something like:

```
test.describe( 'Add New Variable Product Page'...
    
    test('can create product, attributes and variations' ...

    test('can edit variations' ...

    test('can delete variations' ...
```

I initially thought of splitting the first one ( `can create product, attributes and variations` ) even further, but I realized it's a more realistic user journey to keep these three together in a single test.

**Comment by lanej0** [comment]
I hadn't realized we have a hard 90 second timeout on tests. 

This test is a combination of previous tests because we had an "add" test, and then an "edit" test that edited the product added (it wasn't following best practices).

I'm 👍 for splitting this test, as long as we do it the right way, and we don't create dependencies between tests.
