### ISSUE TITLE
[Enhancement]: Auto-dismiss database update complete notice

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#37756]
### Describe the solution you'd like

The DB update success notice should self-dismiss after single view/load. The notice contributes to admin clutter and shouldn't need to persist. If that's not possible, at a minimum, "thanks" should be something more relevant like "dismiss"

![image](https://user-images.githubusercontent.com/507025/232510679-e1b9a6d9-b503-441c-ad08-11181e28f422.png)

**Comment by DavidAnderson684** [comment]
Or better, WooCommerce should check and update its own database tables upon update. Telling the user to do it manually feels like something from the dark ages.

**Comment by helgatheviking** [comment]
That's definitely bigger in scope. I can see the pluses and minuses in doing it that way.

**Comment by vedanshujain** [comment]
We should definitely rename it to `Dismiss` and dismiss it anyway after first reload. Although not so sure about automatically running these migrations though, many large shops would like to do it in a controlled way via CLI for example, so that's a different issue with its's pros and cons. Marking this as a good first issue and limiting scope to changing text and auto-dismissing.

**Comment by barryhughes** [comment]
Closing: it feels like we can address this via https://github.com/woocommerce/woocommerce/issues/41925.
