### ISSUE TITLE
Product Block Editor: Form is broken after drag and dropping images within Images block

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#37955]
**Description**

**Update**
Updated this as part of the [on-going discussion below](https://github.com/woocommerce/woocommerce/issues/37955#issuecomment-1524612787), this issue will address disabling the drag and drop behaviour. A separate issue will be created to add support for dragging and dropping images.

When attempting to re-arrange images within the images product block it seems to freeze the images block and break it.
The dragged image is frozen, but the rest of the form is still useable. See video for reference:

https://user-images.githubusercontent.com/2240960/234034221-81a633cc-fde3-4002-84f5-9f0065d4b54d.mp4

**To reproduce**

1. Build the latest on `trunk` and enable the `product-block-editor` feature flag
2. Go to **Products > Add New** and add a couple pictures to the Images field
3. Now try dragging one of the images, and notice the frozen state.

**Acceptance criteria**

- [ ] Dragging and dropping should be disabled within the images field block
- [ ] A user can still re-arrange images by use of the arrows.

**Comment by louwie17** [comment]
Update on this issue:
Dragging and dropping within the product editor is not possible unless each dragged item is an individual block (see this issue about the dragging and dropping -> https://github.com/WordPress/gutenberg/issues/12635 ). 

The `core/gallery` block does allow for dragging and dropping images, we should re-use this block if possible to fix this issue.

**Comment by joshuatf** [comment]
There are a couple of problems with using the `core/gallery` block directly:

1. Like most blocks, there's no callback function we can use to grab the block data (images) once they've been set.  I.e., we don't know which images are selected and can't update the product accordingly
2. There is no "Cover" label on the images and no way to "set cover" as we do in our current gallery
3. The core gallery block includes other functionality around images (tones/captions/etc) that I'm not sure is supported or not in product galleries.
4. We could copy the whole gallery block component, [but it's rather large](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/edit.js) and that's just one file.

I don't see the ability to drag/drop with that component either.  Do you see otherwise?  If we can't drag that component either, I wonder if we should just disable the dragging on the product gallery and only allow sorting by the toolbar arrows.

**Comment by joshuatf** [comment]
@jarekmorawski This is probably going to require us to recreate the gallery block in our components and may take a week or two to implement.

Is this worth the time investment to do this?  Or should we disable dragging and just allow sorting by the arrows for the time being?

**Comment by louwie17** [comment]
I would agree that disabling the drag & drop and allowing users to re-arrange with the arrows would be the best approach for now and add support for drag and drop to a follow up release.

**Comment by jarekmorawski** [comment]
Works for me. 👍

**Comment by louwie17** [comment]
I updated the description of this issue to address the disabling of drag and drop.
I created this new issue: https://github.com/woocommerce/woocommerce/issues/38046 for adding support for drag and drop.
