### ISSUE TITLE
Product Block Editor: Pricing blocks are not respecting currency position setting

### ISSUE THREAD

**Issue by louwie17** [woothemes/woocommerce#38220]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The currency position is always on the left, changing it in the settings to be after the price doesn't affect this. We should correctly display the currency position depending on the locale.

**Acceptance criteria**

- [ ] We should correctly display the currency position depending on the locale.

**Comment by louwie17** [comment]
@jarekmorawski we just wanted to double check that this is actually expected behaviour, as the `currency position` is only considered for the front-end prices? but not within the product editor.

**Context** This issue was created from the internal testing feedback.

**Comment by jarekmorawski** [comment]
Thanks, @louwie17. The editor should reflect the locale. cc @mdperez86 because we chatted about this when working on the original product form.

**Comment by mattsherman** [comment]
Could potentially use: `Intl.NumberFormat.prototype.formatToParts()`

**Comment by nathanss** [comment]
One more example:

```
var data = 10000000;
data.toLocaleString('it-IT')
// → 10.000.000
data.toLocaleString('en-US')
// → 10,000,000
With this method, you can also format numbers with currency informations:
data.toLocaleString('it-IT', {style: 'currency', currency: 'EUR'})
// → 10.000.000,00 €
data.toLocaleString('it-IT', {style: 'currency', currency: 'USD'})
// → 10.000.000,00 US$
data.toLocaleString('en-US', {style: 'currency', currency: 'EUR'})
// → €10,000,000.00
data.toLocaleString('en-US', {style: 'currency', currency: 'USD'})
// → $10,000,000.00
For more details: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
```

**Comment by mdperez86** [comment]
I'm still not sure of this issue! Since formatting the currency is way more complex than just moving the symbol. Because of that I don't recommend to transform the field into a mirror of the formatting (There are always other ways to show to the user what is going to be the final format, like using the helper text below the field). Also the alignment will be bad when the symbol is at the right or at the left. Comas or dots change too, the amount of significant decimals are not the same for the same local and different numbers/currencies. It does not worth the effort to maintain such kind of field.

First of all this is not depending on the locale at all. This is depending on the Woo Settings 
<img width="684" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/281505a8-4f28-4010-b362-497449a7f3d9">
which is totally a different thing.

**Comment by louwie17** [comment]
Closing this, given its not relevant at the moment, see last comment.
