### ISSUE TITLE
[Enhancement]: automatically update the database after plugin update

### ISSUE THREAD

**Issue by JeePeeNL** [woothemes/woocommerce#38315]
### Describe the solution you'd like

After the Woo plugin update, you need to manually click a button to perform the database update. That should be done automatically because the updated plugin requires specific fields and tables in the database for it to correctly work.

Side note: if you use a WordPress management plugin to run updates on all your websites you usually don't visit the WP dashboard so you don't see the database update instruction

### Describe alternatives you've considered

Add a code snippet to functions.php of a child theme. Although that will work, the update should be done automatically. I guess an auto update is useful for the majority of users, so this filter should probably be the other way around so users can opt-out of the database update. Or better yet, have an option in the plugin setting to disable auto update.

add_filter( 'woocommerce_enable_auto_update_db', '__return_true' );

### Additional context

See this support threat
https://wordpress.org/support/topic/can-the-database-update-be-done-automatically/

**Comment by barryhughes** [comment]
Thanks.

Especially since (as you noted) we have the existing filter hook `woocommerce_enable_auto_update_db`, I think the current situation is pretty reasonable. However, we are actively thinking about the management and nature of database updates in relation to a larger body of work, so some changes may be coming.

For now, though, I'll close this report.
