### ISSUE TITLE
WooCommece Error wp_woocommerce_tax_rates   Slow to Load Error

### ISSUE THREAD

**Issue by KennethErvinYoung** [woothemes/woocommerce#38461]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When running Query, the tool flags WooCommece Error wp_woocommerce_tax_rates  as SLOW TO LOAD. These are the by zip USA tax tables for WooCommerce. How can this be sped up?

Thanks in advance.

Ken Young

<img width="2042" alt="WooCommece Error wp_woocommerce_tax_rates   2023-05-25 at 1 47 07 PM" src="https://github.com/woocommerce/woocommerce/assets/4039950/a84b74be-70c4-431c-8d7d-5d6657536f3a">

I included the system status report.

[SystemStatusReport_www.mbsdpipes.com_2023-05-25T17-57-50.txt](https://github.com/woocommerce/woocommerce/files/11567930/SystemStatusReport_www.mbsdpipes.com_2023-05-25T17-57-50.txt)

### Expected behavior

Tax tables should not load so slow

### Actual behavior

Tax tables load too slowly.

### Steps to reproduce

<img width="2042" alt="WooCommece Error wp_woocommerce_tax_rates   2023-05-25 at 1 47 07 PM" src="https://github.com/woocommerce/woocommerce/assets/4039950/aaa656ba-6974-439d-9ef6-0803da948943">

### WordPress Environment

[SystemStatusReport_www.mbsdpipes.com_2023-05-25T17-57-50.txt](https://github.com/woocommerce/woocommerce/files/11567967/SystemStatusReport_www.mbsdpipes.com_2023-05-25T17-57-50.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Hey @KennethErvinYoung, looking at your screenshot it seems like you have 41k tax rates and zip codes defined in your database, this can definitely have an impact on the performance and loading the tax rate table, that said the screenshot also points out that the query only took 0.053s to run which is not that slow, Query Monitor might just be reporting it as slow relative to the other queries running on that page.

The slowness would also only be experienced in wp-admin as that is where you manage your taxes, but on the frontend, for a customer, it should be much faster as we then do exact matching instead of retrieving the whole table and doing the matching on the results.

Closing as there is not much that can be done at this stage to improve the wp-admin speed for the tax interface if you have a large number of zip codes defined, but as pointed out the frontend and customer will not experience this same delay.
