### ISSUE TITLE
[Enhancement]: The problem of displaying Persian dates (Shamsi / Jalali) in WooCommerce

### ISSUE THREAD

**Issue by clonerdev** [woothemes/woocommerce#38611]
### Describe the solution you'd like

Hello WooCommerce team

For stores operating in Farsi, the dates entered in WooCommerce, such as May and July, etc., have been translated incorrectly. Instead of its solar equivalent, the Gregorian date is used, on the other hand, there are no dates such as July, May, February, etc. in the translation section of the plugin in the WooCommerce repository and po file. Modify the po file
The dates must be available in the po file and also in solar/jelali format for Farsi (Persian) language.

Please add the date and name of the months used in WooCommerce to the WooCommerce language po file so that we can translate it and everyone can use it in their own language.

Of course, using other third-party plugins just for this purpose, which can be easily modified, is not necessary and is a mistake, especially for a store website.

Thank you

### Describe alternatives you've considered

Please add the dates to the po file
These dates are available in the order list, store analysis section, etc

**Comment by coreymckrill** [comment]
@clonerdev Can you provide a screenshot of somewhere that the month names are getting translated incorrectly? If they aren't showing up in the WooCommerce translation file, it might be because they are coming from a different plugin or from WordPress itself.

**Comment by clonerdev** [comment]
> @clonerdev Can you provide a screenshot of somewhere that the month names are getting translated incorrectly? If they aren't showing up in the WooCommerce translation file, it might be because they are coming from a different plugin or from WordPress itself.

Thank you for your attention, yes, I will definitely attach and send two pictures.
It was not taken from another plugin, and all plugins were disabled and tested, but the point is that they are not in the WooCommerce translation file, and if they are called from WordPress core, why does this problem exist!!!? Because in the WordPress core, there is no problem in WordPress and other sections by putting it on Farsi language, and only in WooCommerce, the dates are not solar.
The dates to be translated do not exist either in the WooCommerce language file (pot) or in the WooCommerce translation file (po).
* Two images attached
* Image 1: Dates of the WooCommerce orders section
* Image 2: Dates of the WooCommerce analysis section
![1](https://github.com/woocommerce/woocommerce/assets/107908907/3179b0f7-36a3-43f7-a2b2-d7cd68b01045)
![2](https://github.com/woocommerce/woocommerce/assets/107908907/8b01246c-2b5a-4b39-9e1f-06ba3e43002b)

**Comment by coreymckrill** [comment]
@clonerdev Thanks for the screenshots! I think I see what the issue is. The month names themselves are not getting translated, but rather the date formatting code. Here is the Farsi translation that outputs the date on the Orders list screen:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fa/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5605082&filters%5Btranslation_id%5D=61400463

For comparison, here is the translation in WordPress Core that outputs the date on the Posts list screen:

https://translate.wordpress.org/projects/wp/dev/fa/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=46&filters%5Btranslation_id%5D=68768754

So if you would prefer the Order dates to be in the same format as the Post dates, you could try using the `Y/m/d` format code instead. You could also submit a suggestion to have the translation updated.

**Comment by clonerdev** [comment]
Thank you for your answer, but the problem is exactly that the months themselves do not exist in the translation file to be translated and the formatting code is date, there is no problem in terms of formatting. Months in WooCommerce are called from WordPress core and only its formatting is called from WooCommerce? Because this problem also exists in WordPress core, Persian language users in Persian language stores are forced to use third-party plugins such as the following plugin:
https://wordpress.org/plugins/wp-parsidate/
In your opinion, what is the solution to solve this problem without using a third-party plugin or adding code to the shell function? Because they cause problems.
My suggestion to update the translation is to add the months in the WooCommerce translation file so that we can also translate it, because the problem is the names of the months, not their format.
Thank you very much

**Comment by clonerdev** [comment]
Thank you for your answer, but the problem is exactly that the months themselves do not exist in the translation file to be translated and the formatting code is date, there is no problem in terms of formatting. Months in WooCommerce are called from WordPress core and only its formatting is called from WooCommerce? Because this problem also exists in WordPress core, Persian language users in Persian language stores are forced to use third-party plugins such as the following plugin:
https://wordpress.org/plugins/wp-parsidate/
In your opinion, what is the solution to solve this problem without using a third-party plugin or adding code to the shell function? Because they cause problems.
My suggestion to update the translation is to add the months in the WooCommerce translation file so that we can also translate it, because the problem is the names of the months, not their format.
Thank you very much

**Comment by clonerdev** [comment]
Thank you for your answer, but the problem is exactly that the months themselves do not exist in the translation file to be translated and the formatting code is date, there is no problem in terms of formatting. Months in WooCommerce are called from WordPress core and only its formatting is called from WooCommerce? Because this problem also exists in WordPress core, Persian language users in Persian language stores are forced to use third-party plugins such as the following plugin:
https://wordpress.org/plugins/wp-parsidate/
In your opinion, what is the solution to solve this problem without using a third-party plugin or adding code to the shell function? Because they cause problems.
My suggestion to update the translation is to add the months in the WooCommerce translation file so that we can also translate it, because the problem is the names of the months, not their format.
Thank you very much

**Comment by coreymckrill** [comment]
The problem is that neither WooCommerce nor WordPress use translations of month names when they output dates (they exist in the WordPress translation files for other reasons). The month names come from the underlying PHP code, and the locale settings of the particular server where the website is running. So even if the month names were added to the WooCommerce translation files, it wouldn't change anything.

There's a bit more discussion about this in these feature requests for WordPress Core:

* https://core.trac.wordpress.org/ticket/58148
* https://core.trac.wordpress.org/ticket/37491

So, what it comes down to is, this is a very complex problem to solve, and it should be solved in WordPress Core rather than in WooCommerce (this has actually come up before, #4454, #13289). Since there is no solution in WP Core yet, my recommendation would be to contact the developers of the Parsi Date plugin you linked above and ask if they can improve their WooCommerce integration to cover the Orders and Analytics areas you mentioned where things are not displaying correctly.
