### ISSUE TITLE
Create Settings screen with Admin for Woo AI

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#38746]
We'll soon have the need to capture global preferences that relate to our AI features, such as those governing store-wide personality. A couple that have been mentioned:

- Tone
- Style

Acceptance Criteria:
- [ ] Create new settings screen accessible from the sidebar
- [ ] Add tone setting.
- [ ] Add style setting.

**Comment by joelclimbsthings** [comment]
@laurendavissmith We'll need more detail on these `tone` and `style` settings--should I reference the Ghidorah work to guide that, or do you have other references or thoughts?

**Comment by joelclimbsthings** [comment]
Some designs illustrating what's needed:



![Image](https://github.com/woocommerce/woocommerce/assets/444632/73f5e034-1911-4fd7-913b-d739e57058c2)
![Image](https://github.com/woocommerce/woocommerce/assets/444632/d4845084-8c02-441c-a52c-2a7d0360b2a3)
![Image](https://github.com/woocommerce/woocommerce/assets/444632/fcabef6f-948a-4fa7-b281-19e8a476688b)

**Comment by joelclimbsthings** [comment]
Going over the above visuals, I see something along these lines in terms of valid global options:

_What you're selling_ - text field

_Describe your business_ - text box

_Tone_ - select
- Informal
- Humorous
- Neutral
- Youthful
- Formal
- Motivational

_Style_ - select
- Modern
- Bold
- Classic
- Energetic
- Retro
- Warm

**Comment by tommyshellberg** [comment]
We could also look at creating a link to this new settings page that is discoverable while using the Product Titles generation functionality, e.g:
`For a more consistent tone to match your brand, submit some copy samples here`

**Comment by joelclimbsthings** [comment]
> We could also look at creating a link to this new settings page that is discoverable while using the Product Titles generation functionality,

I definitely like this idea. We may want a separate issue that actually adds support to our existing prompts/etc for these settings, and that would be a good place for a link as well.

**Comment by tommyshellberg** [comment]
> We could also look at creating a link to this new settings page that is discoverable while using the Product Titles  We may want a separate issue that actually adds support to our existing prompts/etc for these settings, and that would be a good place for a link as well.

For sure; I wrote this comment as a placeholder because I didn't want to create an issue yet 😆 

For the first version of this Settings page, I like the idea of having Tone + Style as manually selectable with future iterations allowing for automatic tone + style recognition and setting. 
If this is indeed what the first version will look like for this settings page, do we need these two text fields? It's not clear if this information will actually be usable until we have a way to detect tone + style?

> What you're selling - text field
> Describe your business - text box

My thinking here is that we'll probably want to create an endpoint first for detecting tone + style to then be able to collect this information and automatically generate tone + style. 🤔

**Comment by joelclimbsthings** [comment]
> If this is indeed what the first version will look like for this settings page, do we need these two text fields? It's not clear if this information will actually be usable until we have a way to detect tone + style?

I suppose my assumption was that it could potentially be injected into prompts to give the LLM more context (although I'm not precisely certain where we'd want to do this). I don't think it hurts to have a spot to edit this text since it's being gathered in the new onboarding, although you're right that I'm uncertain how we'll be using it in the short term.

**Comment by tommyshellberg** [comment]
> I suppose my assumption was that it could potentially be injected into prompts to give the LLM more context (although I'm not precisely certain where we'd want to do this). I don't think it hurts to have a spot to edit this text since it's being gathered in the new onboarding, although you're right that I'm uncertain how we'll be using it in the short term.

After thinking about it more, I'm cool with the idea of collecting the data now, even if we can't do anything with it, provided that users aren't given false hope about what Woo AI can do with it. 😆 
This Settings page might be something a user looks at once and never again so it could actually be a good idea to get this data right away so that we could use it later without needing to prompt someone to go back into the settings page and add more information. 🤔
