### ISSUE TITLE
woocommerce_cart_item_name filter is applied twice

### ISSUE THREAD

**Issue by dennisnissle** [woothemes/woocommerce#38744]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `woocommerce_cart_item_name` filter in the 7.8.0 [cart.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php#L49) template is applied twice. That leads to issues with plugins that use the filter to adjust the cart item name (as the additional info may be added twice).

### Expected behavior

Do only apply the filter once or pass the original, non-filtered `$_product->get_name()` as first parameter to the next filter call instead of `$product_name` (which already has been filtered).

### Actual behavior

The filter is being applied twice. First on creating the variable:

`$product_name = apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key );`

and during output:

`echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $product_name, $cart_item, $cart_item_key ) . '&nbsp;' );`

### Steps to reproduce

1. Add a snippet to your functions.php:

```php
add_filter( 'woocommerce_cart_item_name', function( $cart_item_name ) {
   return $cart_item_name . ' - test';
} );
```
2. Add a product to cart
3. See how the `-test` suffix is added twice.

### WordPress Environment

Latest WP and Woo version. Latest storefront theme.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Peter-HVD** [comment]
I can confirm that this is happening. If you want to see it on a live site, check out https://tickets.brightongmc.org and add a ticket to your cart. You'll need to inspect the html as I've found workaround of wrapping my added text in a span and hiding the 2nd version of it with css. You can also add a donation to your cart to see it happening in a plugin that I'm using which uses the same filter.

**Comment by helgatheviking** [comment]
I am filtering `woocommerce_cart_item_name` in my Mix and Match Products plugin and getting reports on this too. Can reproduce it locally too with a similar snippet.

Changing `$product_name` to `$_product->get_name()` [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php#L96) and [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php#L104) resolve it, but begs the question of why that's necessary to have the same filter running multiple times in a template? 

If there's a permalink, why does `woocommerce_cart_item_name` also allow filtering the `<a href="%s">%s</a>` markup? Since `$product_name` is already defined I think we can reduce [lines 87-105](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php#L87-L105)

```
if ( ! $product_permalink ) {
	echo wp_kses_post( $product_name . '&nbsp;' );
} else {
	printf( '<a href="%s">%s</a>', esc_url( $product_permalink ), wp_kses_post( $product_name ) );
}
```
