### ISSUE TITLE
Typo: says "Product Categories" should be "Product Tags"

### ISSUE THREAD

**Issue by matt-matt1** [woothemes/woocommerce#38780]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Admin > Appearance > Customize > WooCommerce > Product Archives > Cards Options > General
switch says "Product Categories" should be "Product Tags"

### Expected behavior

switches "Product Tags"

### Actual behavior

switch says "Product Categories" but switches "Product Tags"

### Steps to reproduce

Admin > Appearance > Customize
WooCommerce > Product Archives > Cards Options

"Customizing ▸ Product Archives
Cards Options"

General tab
switch says "Product Categories" should be "Product Tags"

### WordPress Environment

WooCommerce version: |   | 7.8.0
-- | -- | --

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by AashikP** [comment]
Hi @matt-matt1,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin since core WooCommerce does not come with an option called Product Archives > Cards Options. 

Here's what you can find under _Customize > WooCommerce_ :

![LV1Fkb.png](https://github.com/woocommerce/woocommerce/assets/17475174/3acc666b-792c-4c67-8fbe-2c93cd0d743f)

Please contact the author of the plugin directly for further help.
