### ISSUE TITLE
Add header buttons to the description editor modal

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#38831]
Let's add the missing buttons to the description editing modal's header.
This issue focuses on adding the `Done` and `Cancel` buttons to the editor modal header.

**Design**

`AkVNGImLgSqCObTQ3idVn7-fi-1005-134278&t=qXWHtVZH4AdAimkb-4`

<img width="639" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/9bef19f6-dc42-4fef-97f8-1f1da1e338db">

**Acceptance criteria**

- [ ] There's a `Done` button in the header.
- [ ] There's a `Cancel` button in the header.
- [ ] [Nice to have] If the modal has unsaved changes and the user clicks `Cancel`, we show the browser's dialog window.

**Done in other issues**
- [ ] There's a more button in the header. It contains the same options as the post editor -  #39024
- [ ] There's a show/hide sidebar button in the header - #39025

**Comment by louwie17** [comment]
> The Save button changes to Update when the user edits an existing description.

@jarekmorawski question around this copy, the `save` and `update` copy suggests to the user that we are actually saving the description when the user clicks this, when at the moment we don't do this until the user hits `update` on the main product editing page.
Do you want us to save the description (only) when the user clicks `save`? Or should we change the copy a bit, for example use `done` instead of `save`?

**Comment by jarekmorawski** [comment]
Good question. I think it's OK to use `Done` instead. I'll update the AC and remove the one about changing the copy because `Done` will work in any case.

Edit: I just realized I went with `Done` in the design. The AC must come from an earlier version. Thanks for bringing this up, @louwie17.
