### ISSUE TITLE
New partially refunded total amount is not respected when manually creating orders

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#39064]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in zd-6481464

If you create a manual order, and then decide to refund part of it before the customer pays, the new total will not be respected.

The refund function is clearly designed to be used when the customer has paid already. However, considering the total is being changed on the order page itself, this is certainly something that needs to be fixed in my opinion.

<img src="https://d.pr/i/44rwt7+" alt="">
Link to image: https://d.pr/i/44rwt7

### Expected behavior

The new total to be charged (which is the previous total - refund)

### Actual behavior

The refund amount is not respected

### Steps to reproduce

1. Create an order manually
2. Add customer information & product
3. Publish
4. The order will have a "Pending Payment" status
5. Manual refund part of the total and click recalculate.
6. You'll see the refunded amount deducted on the order page and when visiting the payment page, however, the amount charged will be total without refund.
7. Tried with both WooCommerce Payments and Stripe

A screencast describing the issue can be found here: https://wordpress.org/support/topic/pending-payment-refund-not-working/#post-16858522

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://Test.wpcomstaging.com
Site address (URL): https://Test.wpcomstaging.com
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.5.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Status report information ###

Generated at: 2023-07-03 23:12:30 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Manual refund part of the total and click recalculate.

@Babylon1999 You can edit the order directly and add/remove items or adjust the prices when the order status is pending payment. The refund function is for returning some or all of the payment. Closing this as a support question.

**Comment by electro-Z** [comment]
- After depth review on WOO database and community forum, there is no solution to this issue. this is a bug in WOO core plugin.
- Hence this is a bug in WOO core plugin, and not in a payed plugin, ticket in WooCommerce support cannot b opened.
- The post creator did add a clear steps to reproduce it including an image
- you can find a full screen recording of issue reproduction in the following link:
https://www.awesomescreenshot.com/video/17724596?key=4b6f44b978310d4b40b90ee1c8539373

I believe this issue is concerning any WOO system customer that will try to refund a pending payment total and this should be taken care by WOO developing team.

Just to make it clear, few months ago refunding a pending total was working fine!
Downgrading WOO core plugin did not solve the problem.
