### ISSUE TITLE
WooCommerce Membership Content Restriction for Event (Events Calendar)

### ISSUE THREAD

**Issue by rajshree-agaetis** [woothemes/woocommerce#39088]
I'm currently working on implementing content restrictions for events using WooCommerce Memberships. I've noticed that when I apply content restrictions to individual events, they don't take effect as intended. The events still appear accessible to users. However, when I apply content restrictions to all events collectively, the restrictions work correctly.

I would appreciate guidance on troubleshooting this matter and resolving the issue. Is there a particular configuration I might be missing or any potential conflicts I should be aware of when applying content restrictions to individual events using WooCommerce Memberships?

**Comment by AashikP** [comment]
Hi @rajshree-agaetis ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [WooCommerce Memberships](https://woocommerce.com/products/woocommerce-memberships/?aff=10486&cid=1131038) plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the support team by [opening a ticket with the developers directly](https://woocommerce.com/my-account/create-a-ticket/?form=ticket). 

Please select `WooCommerce Memberships` extension (_it will be displayed when you're logged in to the account where you purchased the extension from_) in the **I need help with** dropdown: 

![6NYfit.png](https://github.com/woocommerce/woocommerce/assets/17475174/b7e6ef15-85e7-4552-a2dc-a430c1a55142)

If you don’t see all your purchased extensions in the list, please use the Search box to locate it.

They will further assist you with your query.
