### ISSUE TITLE
[Enhancement]: The kebab menu in the description modal doesn't toggle color

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#39261]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the blocks product editor. After pressing `Add description` a modal will be visible. After pressing the kebab menu on the top right corner, the button color should toggle like the `Show/hide block inspector` button when the menu is open.

Now it's looking like this:

<img width="500" alt="Screenshot 2023-07-14 at 16 49 39" src="https://github.com/woocommerce/woocommerce/assets/1314156/3413c1f4-ebaf-4075-9ed6-611850956576">

And it should look like this:

<img width="304" alt="Screenshot 2023-07-14 at 16 45 45" src="https://github.com/woocommerce/woocommerce/assets/1314156/162dc5de-dccb-4204-a168-5418fdcb9797">

**Comment by mattsherman** [comment]
@octaedro @jarekmorawski This is not the behavior of the kebab menu in the post editor. I suggest we have the same behavior in our modal, for consistency.

**Comment by jarekmorawski** [comment]
Thanks for the ping, @mattsherman. I agree that we should be consistent with the post editor. It makes sense because the toggled button is reserved for displaying elements that become integral parts of the interface, like the sidebar. Meanwhile, the kebab opens a transient menu that doesn't affect the interface structure and will disappear once the user takes action or clicks outside the dropdown.

I'll close this issue and update the designs in Figma.
