### ISSUE TITLE
[Customize Your Store] Spike: Integrate Text Completions Endpoint

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39527]
A generic text completions endpoint is available in the Woo AI package here: https://github.com/woocommerce/woocommerce/blob/566d5092b2d18f3127b5814635b86314a608bec7/packages/js/ai/src/utils/text-completion.ts#L93-L105

Explore integrating this to the project and potentially modifying it to allow non-streaming behavior.

**Comment by chihsuan** [comment]
> Explore integrating this to the project and potentially modifying it to allow non-streaming behavior.

I think it would be better to call AI API on the **server side** because we don't need to show the results on the UI, but we'll need to save response data to the database to populate patterns. Besides, we can also easily combine other necessary data on the server side or allow users to call OpenAI API with their token. 

To use the AI endpoint on the server side, we'll first need to retrieve the AI JTW token via [`\Automattic\Jetpack\Connection\Client::wpcom_json_api_request_as_user`](https://github.com/Automattic/jetpack/blob/0962ee5610ce7753b9448dc2504d547ae8c009ca/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L776-L794).

Then, we can call https://public-api.wordpress.com/wpcom/v2/text-completion API directly.

- text-completion endpoint source code (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Snv%2Qgrkg%2Qpbzcyrgvba.cuc%3Se%3Qs7904rq8-og)
- JWT Token acqusition endpoint (PCYsg-R3X-p2)

Note that we can also pass `_fields` parameter to receive only the `completion` field in the response.

I've tested the API and confirmed it works as expected.

P2 Reference: pe5sF9-1Il-p2
