### ISSUE TITLE
[SPIKE] Woo AI Image Background Removal - Single Media File Editor

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#39728]
Before we start adding the "Remove Image Background" button to the single media file editor panel, we need to determine a couple of things:

- [ ] Is it possible to replace the image currently being edited with a new image?
- [ ] Is it possible to register the background removal as an "action" within the editor which could be reverted using the "undo" action?

These findings will determine the UX for removing the background of a single image within the media library.

**Comment by nima-karimi** [comment]
The image editor in WordPress is not easily extendible. The edits mostly happen on the backend by calling an ajax method and providing a "history" of edits to perform on the image.

For example, when you rotate an image 90 degrees, the only thing that happens on the front end is that an object like `"{r: 90}"` is built and then send as a `history` parameter to the following URL: 
```
/wp-admin/admin-ajax.php?action=imgedit-preview&_ajax_nonce=xyz&postid=123&history=[{"r"%3A90}%2C{"r"%3A-90}%2C{"b"%3A-90}]
```

We can modify this history array using JS by calling methods of an `window.imageEdit` object (like 'imageEdit.addStep` to add an item to the history). However, the backend needs to be aware of the entries created in the `history` parameter so that it can perform those edits on the image.

The backend functions are all located under the `src/wp-admin/includes/image-edit.php` file, and the edit actions are all hardcoded without any filters allowing us to modify them (see the function `image_edit_apply_changes`). 

There is a filter called `wp_image_editor_before_change` that might be helpful because we could modify the image object when we detect the background-removal action in the history; however, we can't do any edits in the order specified because that's done after the filter is applied. This means that we can either do a hacky implementation and reapply all of the WordPress edits in the filter, or just break the Undo pattern whenever the background-removal action is applied and clear the history.

```php
/**
 * Filters the WP_Image_Editor instance before applying changes to the image.
 *
 * @since 3.5.0
 *
 * @param WP_Image_Editor $image   WP_Image_Editor instance.
 * @param array           $changes Array of change operations.
 */
$image = apply_filters( 'wp_image_editor_before_change', $image, $changes );
```
---
So in conclusion to answer the questions asked above:

>  Is it possible to replace the image currently being edited with a new image?

Yes, this is possible by using the `wp_image_editor_before_change` filter. However, to do this we should either skip the `undo` part and clear the history. Or implement the image editing actions that are applied in WordPress in our codebase too and make those changes in order so that we can keep the change history.

>  Is it possible to register the background removal as an "action" within the editor which could be reverted using the "undo" action?

Yes, this is _possible_ but it might be tricky to apply "undo" because the WordPress backend code that applies the actions is not extendible. So we'd have to implement the code to apply every other action in the list too (e.g. rotate, flip, crop, etc.) so that we can do them in order.
