### ISSUE TITLE
[Customize Your Store] Homepage Templates

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#39720]
## User Story

> As a new merchant, I would like a to fine tune the AI design, so I can add my personal touch.

## Design

* [Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?node-id=2631%3A262328&mode=dev)

![Image](https://github.com/woocommerce/woocommerce/assets/9312929/052ba263-8c71-4194-8b58-1eab7155fb68)

Should be similar to header implementation, please refer to:

- https://github.com/woocommerce/woocommerce/issues/39718

## Acceptance Criteria

```
Scenario: Homepage panel is opened
    Given the user opens the header panel
    Then available homepage templates are shown

Scenario: User changes the homepage template 
    Given the user changes the homepage template
    Then the homepage should be updated in the preview pane

Scenario: Save
    Given the user presses the save button
    Then the rendered preview should be saved permanently
```

**Comment by ilyasfoo** [comment]
@adrianduffell I assume this task doesn't include building the templates, correct?

**Comment by adrianduffell** [comment]
@ilyasfoo That's correct!

**Comment by moon0326** [comment]
@adrianduffell @chihsuan  Which category should we use for `homepage`? I've tried `woo-commerce` and `featured` and they do not look like homepage templates.

**Comment by chihsuan** [comment]
Hey @moon0326, ~These categories are we need to show for homepage:~

You can find the corresponding  pattern slugs here:
- https://github.com/woocommerce/woocommerce-blocks/issues/10086

**Comment by moon0326** [comment]
Thank you @chihsuan 👍

**Comment by chihsuan** [comment]
Hey @moon0326 👋 Actually, in MVP, we only need to display templates recommended by AI. 😅  That part is not finished yet. So I think you can just pick some template patterns to show for now.

**Comment by chihsuan** [comment]
Hey @verofasulo I want to ensure I understand the home template display logic correctly. 🙂 

If the AI ​​determines that the site is SMB and Art, Ceramic category, we just pick one as default and show templates belonging this that category (F5AAbRJOGbTeEweXPFtHgf-fi-2283_33975) in the assembler hub?


![Image](https://github.com/woocommerce/woocommerce/assets/4344253/d7c59a0c-d111-4e05-9324-935e2a65c32e)


I'm a little confused. Because from the design here (Mrk6SERPZ4KrFHSjM0a8TK-fi-2631_260030), it seems that the patterns displayed on the sidebar are a single pattern view (for example, feature product pattern F5AAbRJOGbTeEweXPFtHgf-fi-2242_36105), not a full home template. Do we just show a pattern preview to represent the home template? 🤔 


![Image](https://github.com/woocommerce/woocommerce/assets/4344253/9a0882c2-6b96-4b0d-a420-0e4885d3df84)

**Comment by verofasulo** [comment]
Hey @chihsuan 🙂

> If the AI ​​determines that the site is SMB and Art, Ceramic category, we just pick one as default and show templates belonging this that category (F5AAbRJOGbTeEweXPFtHgf-fi-2283_33975) in the assembler hub?

They are different streams, actually — the AI determines:

- If it's a small/medium catalog vs. a large catalog and defaults to one of the three templates (they are 6 in total, 3 for small and 3 for large catalogs).
- What the merchants are selling and, therefore, the most appropriate images.

> it seems that the patterns displayed on the sidebar are a single pattern view (for example, feature product pattern F5AAbRJOGbTeEweXPFtHgf-fi-2242_36105), not a full home template.  

Good question. They are not patterns, they are homepage templates. I just clipped the content to avoid having super long boxes. 🙂

**Comment by chihsuan** [comment]
> If it's a small/medium catalog vs. a large catalog and defaults to one of the three templates (they are 6 in total, 3 for small and 3 for large catalogs).
What the merchants are selling and, therefore, the most appropriate images.

Ah, understood. Thank you! @verofasulo  😊 

> Good question. They are not patterns, they are homepage templates. I just clipped the content to avoid having super long boxes. 🙂

Okay!

**Comment by chihsuan** [comment]
@moon0326, In that case, I think we will need to create predefined template arrays based on figma (F5AAbRJOGbTeEweXPFtHgf-fi-2283%3A33977). 

I think predefined template arrays might be something like the below:

```js
const SMB_TEMPLATES: [
   // template1
   [block-slug1, ...],
   // template2
   ...
   // template3
   ...
]

const LB_TEMPLATES = [
   // template1
   [block-slug1, ...],
   // template2
   ...
   // template3
   ...
]
```
We don't need to deal with images because Store editing team has implemented an endpoint to populate the image. We'll call that API during the AI loading screen.

To render the home templates on the sidebar, we can fetch AI results (once the loading screen is completed) and https://github.com/woocommerce/woocommerce/pull/40107/files#diff-da49a2d883e988190a443d31ce9fb0f2640fa4b1d86e21cac2f5e7c42c28b3afR29 and then replace slugs with actual block objects. 

Let me know if you would like me to create template objects. 🙂

**Comment by chihsuan** [comment]
## Large Business

Template 1: 

- a8c/cover-image-with-left-aligned-call-to-action
- woocommerce-blocks/featured-products-5-item-grid
- woocommerce-blocks/shop-by-price
- woocommerce-blocks/featured-category-triple
- a8c/3-column-testimonials
- a8c/quotes2
- woocommerce-blocks/social-follow-us-in-social-media

Template 2:

- woocommerce-blocks/hero-product-split
- woocommerce-blocks/shop-by-price
- woocommerce-blocks/featured-category-triple
- woocommerce-blocks/shop-by-price
- a8c/three-columns-with-images-and-text
- woocommerce-blocks/testimonials-3-columns
- a8c/subscription

Template 3:

- a8c/call-to-action-7
- a8c/3-column-testimonials
- woocommerce-blocks/shop-by-price
- woocommerce-blocks/featured-category-cover-image
- woocommerce-blocks/featured-products-5-item-grid
- woocommerce-blocks/featured-products-5-item-grid
- woocommerce-blocks/social-follow-us-in-social-media

## SMBs

Template 1:

- woocommerce-blocks/shop-by-price
- woocommerce-blocks/testimonials-single
- woocommerce-blocks/hero-product-3-split
- a8c/contact-8


Template 2:

- a8c/about-me-4
- a8c/product-feature-with-buy-button
- woocommerce-blocks/shop-by-price
- a8c/subscription
- woocommerce-blocks/testimonials-3-columns
- a8c/contact-with-map-on-the-left

Template 3:

- a8c/heading-and-video
- a8c/3-column-testimonials
- a8c/quotes2
- a8c/product-feature-with-buy-button
- a8c/simple-two-column-layout
- woocommerce-blocks/social-follow-us-in-social-media
