### ISSUE TITLE
Product Block Editor: add tracks to the Variations tab.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#39831]
We miss a few events around OPTIONS usage:

  - `wcadmin_product_options_add_button_click` **Add new** button,
  -  follow-up to the latter: `wcadmin_product_options_add` with props '{'attribute': X, 'values': array[]}'. Given that there might be a few of those, we could consider using an array as a prop,
   - `wcadmin_product_options_edit` Edit,
   -  within the latter one: `wcadmin_product_options_update` with props {'filter': true/false, 'default': true/false, 'visible': true/false} on Update (if values changed)

VARIATIONS:
`wcadmin_product_variations_hide` (Not visible to customers).

**Comment by AnnaMag** [comment]
cc @mdperez86

**Comment by mdperez86** [comment]
@AnnaMag we add more than one attribute + options at once so what do you think the event should looks like?
Consider that this case happens when clicking the `Add` button from the `Variation options` modal.

Should we fire one event per attribute like
`wcadmin_product_options_add` `{ attribute: 'color', values: ['red', 'blue'] }`
`wcadmin_product_options_add` `{ attribute: 'size', values: ['xl', 'sm'] }`


Or should we fire one event for all attributes like 
`wcadmin_product_options_add` `{
 options: [
  { attribute: 'color', values: ['red', 'blue'] },
  { attribute: 'size', values: ['xl', 'sm'] }
 ] }`

**Comment by AnnaMag** [comment]
> we add more than one attribute + options at once so what do you think the event should looks like?

That is right and I made a suggestion in the main text:  _Given that there might be a few of those, we could consider using an array as a prop,_ , which matches as an idea your option # 2. Nitpick: I'd use `options` as the name of the array.

**Comment by mdperez86** [comment]
> `wcadmin_product_options_add_button_click` Add new button

@AnnaMag currently we are sending `wcadmin_product_add_attributes_click` event when clicking the same button. Do you want me to change the name of the event for the one you provided?

**Comment by AnnaMag** [comment]
@mdperez86 Great question. 
There are indeed a couple of events in the legacy editor, but the data collection is incomplete. 
Let's create a new cohesive tracking using the language that matches the front-end (using `options`). Let me know if you think we should discuss it further!

**Comment by mdperez86** [comment]
> @mdperez86 Great question. There are indeed a couple of events in the legacy editor, but the data collection is incomplete. Let's create a new cohesive tracking using the language that matches the front-end (using `options`). Let me know if you think we should discuss it further!

For me is ok, so lets go with your suggestion `wcadmin_product_options_add_button_click` then
