### ISSUE TITLE
[Enhancement]: WC_Widget_Product_Categories should be hide if no ancestors categories found

### ISSUE THREAD

**Issue by khoipro** [woothemes/woocommerce#39959]
### Describe the solution you'd like

When we try to use an existing product categories widget, if the product category is last level with no child category, a widget displays "No product categories exist."

### Describe alternatives you've considered

This information "No product categories exist." seems to be a very bad idea. It's good to stop rendering a whole widget. If there is no way to filter and make it work, we must hide this widget using JS (to check if contains ul or not).

**Comment by AnnaMag** [comment]
@rrennick I believe this should be moved to the Site Editing backlog. WDYT?

**Comment by rrennick** [comment]
> I believe this should be moved to the Site Editing backlog. WDYT?

@AnnaMag Thanks for the follow up. That could be the case if this is a FSE theme.

@khoipro Could you provide us with your System Status report?

**Comment by khoipro** [comment]
I think the System Status has nothing to see, just because when working with all Woo sites, it will have the same condition.

**Comment by khoipro** [comment]
Ping @rrennick @AnnaMag @htdat  for this issue again.

**Comment by rrennick** [comment]
> I believe this should be moved to the Site Editing backlog. WDYT?

Moving to site editing. 

> I think the System Status has nothing to see,

@khoipro Could you let us know which theme you are reporting this for?

**Comment by Aljullu** [comment]
Hi there, @khoipro, thanks for opening this issue!

My understanding is that you are using the _Product categories_ widget, is that correct? Since 2021, the classic widget has been deprecated in favor of the _Product Categories List_ block, so I would suggest updating. The block can be found in the inserter when adding a new widget:

<img src="https://github.com/woocommerce/woocommerce/assets/3616980/1f13e23a-5999-4901-a137-5e9cdfd96024" alt="" width="735" />


The block has an option to only display categories which are descendents of the current category:

<img src="https://github.com/woocommerce/woocommerce/assets/3616980/2af1943d-a698-460b-a73f-9284b8069d65" alt="" width="297"/>

When selected, if there are no children categories, no message is displayed:

[Enregistrament de pantalla del 2024-03-18 15-36-21.webm](https://github.com/woocommerce/woocommerce/assets/3616980/56d91716-f271-4338-b7c3-59e5a146e9c9)

I'm going to mark this issue as solved, but feel free to reply if you think that's a mistake. :slightly_smiling_face:
