### ISSUE TITLE
[Enhancement]: Shop page template for Block Editor

### ISSUE THREAD

**Issue by rodolfomartinez** [woothemes/woocommerce#40024]
### Describe the solution you'd like

I really enjoy the new block editor themes (6.x) and for the most part woocommerce integrates nicely, but I keep having issues with the actual "Shop" page. I know that solutions like elementor and Divi allow for direct editing of the Shop page template; can we get the same in stock wordpress installs? My current work around is to create a new page that is basically the new shop page, but I feel like there is too much room for error or for missing links etc.

### Describe alternatives you've considered

Currently, I create a new page using the woocommerce widgets to get the look that I like

### Additional context

It would be nice to have the shop page here:

<img width="337" alt="Screenshot 2023-09-04 at 2 03 58 PM" src="https://github.com/woocommerce/woocommerce/assets/7537946/dd8a74d1-148e-41fe-92ea-21b5bd8d3c60">

**Comment by bartmika** [comment]
+1

**Comment by wpchannel** [comment]
Just edit Product Catalog template?

**Comment by rodolfomartinez** [comment]
@wpchannel yes a potential work around but honestly I would prefer to have access to the Shop page itself, similar to how Divi/Elementor work

**Comment by nerrad** [comment]
Hi @rodolfomartinez, I'm curious why you would prefer to make the changes on the Shop page when the Product Catalog template gives you the ability to modify everything that is rendered on shop routes. We're open to considering changes here.

I'm closing this issue because it's not immediately actionable, but I'll still receive replies to it.
