### ISSUE TITLE
[Product Block Editor] Variable products with stock are displayed as unavailable.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#40042]
Variations without prices will not be displayed on the product page. There's no way to inherit it from the parent product, so we must make it easy for the user to add prices to all variations at once. If they want to edit them for individual variations, they can use quick actions.

For the MVP, we'll limit the scope and only let users set up list prices in bulk.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-6769_247347

**Acceptance criteria**

- [x] When variations are first created, we display a notice in the variations table. `The copy reads: XX variations do not have prices. Variations that do not have prices will not be visible to customers.`
- [x] If dismissed, the notice will only show up again when the user attempts to publish a product. It's treated as an error message and must be validated. The "Add" button is always available. If the user is in another tab, we take them to the Variations tab and scroll to the Variations table. We also show a snackbar message that reads: `Set variation prices before adding this product.`
- [x] Because the variations are hidden until the prices are added, they are automatically disabled and we show an icon to indicate that (AkVNGImLgSqCObTQ3idVn7-fi-6769_247347).
- [x] We show stock as "Out of stock".
- [x] The "Set prices" button opens a browser dialog window where the user can enter the regular price. It's the same window that show up when the user selects any pricing-related option from the `Quick update` menu.
- [x] Once the prices are added, the red notice disappears.
- [x] Once the prices are added, we show a snackbar message in the bottom left corner.
- [x] Once the prices are added, all variations are set to be visible and get the “In stock” status.
- [ ] If the user adds new variations by creating new options or option values, they inherit the stock and price from the first variation in the list.

**Comment by mdperez86** [comment]
@AnnaMag This is happening because the variation does not have a list price. We need to think about how we want to approach this like: During the variations auto generation moment (what should be the right amount to set as list price to each auto generated variation?)

**Comment by AnnaMag** [comment]
Fyi: related issue within the legacy editor https://github.com/woocommerce/woocommerce/issues/39276

**Comment by AnnaMag** [comment]
@pmcpinto, what do you think? ^^

**Comment by pmcpinto** [comment]
If the parent product already has a price, we should assign this price to all variations.
If it doesn't have a price, we should notify the user. I'm afraid that the snackbar doesn't have enough visibility. IMO it should be something more prominent. cc @jarekmorawski

**Comment by AnnaMag** [comment]
@mdperez86 I added it to the Variations project board so that it is visible in the context of the 8.2 code freeze.

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag 

> If the parent product already has a price, we should assign this price to all variations.

It's not possible to get the pricing values from the parent product due to some server rules that ignore these values when a product is of type `variable`. We had a discussion about that long ago with @jarekmorawski and because of that the issue https://github.com/woocommerce/woocommerce/issues/36775 was created to tackle that problem in a different way.
Because now we don't have a specific page to edit a variable product maybe we will need to change the ACs described in #36775 to fit our current use case. (We are editing variations only through the quick actions menu in the variations table)

**Comment by AnnaMag** [comment]
Thanks @mdperez86 for grooming this work.

I wonder if, [given the comment that closes the ref issue](https://github.com/woocommerce/woocommerce/issues/36775#issuecomment-1682333535), there is an issue open with a solution that we missed 🤔 
Let's wait for @jarekmorawski to chime in.

**Comment by pmcpinto** [comment]
I've talked to Jarek about this issue. He'll share a proposal tomorrow or Wednesday.

**Comment by jarekmorawski** [comment]
https://github.com/woocommerce/woocommerce/issues/36775 is about adding prices on an individual variation level, not in the parent product. We still need to a solution for this (arguably more common) use case.

@mdperez86, I know there are constraints when it comes to grabbing the price on a technical level, but maybe we could find a workaround? For instance, we'd run a check to see if the price field is filled and copy its value only on the front-end level, bypassing the server. Could that work?

If that's not feasible, we'd default to 0.00 and make it easy for merchants to add prices to individual variations or all of them at once. I was considering a notice, but it can be ignored. I think it's safer to default to 0.00 and let users change the price using the Quick update menu.

**Comment by mdperez86** [comment]
@jarekmorawski 

>For instance, we'd run a check to see if the price field is filled and copy its value only on the front-end level, bypassing the server. Could that work?

That won't work because if the server does not retains the value, then the user needs to set those values on each page refresh before going to generate variations. Also if we do it anyway client side and the user bypasses the Pricing tab directly to the Variations tab, what the user will see there then? "You should first fill the list price under the Pricing tab"? Or we disabled the variations tab if the pricing fields are empty? Or we don't generate variations automatically on each attribute creation but create a button to manually generate them all if the pricing fields are set?...

>we'd default to 0.00 and make it easy for merchants to add prices to individual variations or all of them at once. I was considering a notice, but it can be ignored. I think it's safer to default to 0.00 and let users change the price using the Quick update menu.

I think this could work and it is a straightforward solution to implement, but I suggest this:
It is ok to generate variations with no pricing at all, but those variations should not have status publish at that moment because they are not ready yet, so we should not be able to see the public preview of any variations yet until the parent product is being published, so in that process we can validate if the variations are ready to be published too as well as their own parent product. If variations are not ready yet, we can show the error messages to let the users know that they need to set the variations pricing fields. It should be at least one variation ready by the moment the users want to publish the product, if that is not the case we should not let users to publish the parent product.
From my point of view this is the way this process should looks like.

With that we prevent users to publish non ready variations and their parent product, at the end, if the parent product is a variable one, it does not make sense to publish it with no associated variation right!

cc: @pmcpinto @AnnaMag

**Comment by AnnaMag** [comment]
+1 to @mdperez86 proposal.

**Comment by pmcpinto** [comment]
> If variations are not ready yet, we can show the error messages to let the users know that they need to set the variations pricing fields.

How would you show the error? With the snackbar?

**Comment by mdperez86** [comment]
>How would you show the error? With the snackbar?

A red alert message error indicating that at least one variation must have a price set, and we can highlight the variations table or a specific row too. Similar to what @jarek shared here p1694601013503399-slack-C01CMSA1VHS

**Comment by jarekmorawski** [comment]
Thanks for the discussion here and on Slack, team. I updated the issue description with designs and new ACs.

**Comment by pmcpinto** [comment]
@jarekmorawski thanks for updating the AC. I just have one question:

> When variations are first created, we display a notice in the variations table. The copy reads: XX variations do not have prices. Variations that do not have prices will not be visible to customers.

Should we show the notice every time a variation is created?

**Comment by jarekmorawski** [comment]
> Should we show the notice every time a variation is created?

I'd assume we'd only show it the first time the variations are generated, then copy the price added to other variations to all others that will be added from now on. @mdperez86, is that possible? I know we can't copy from the parent product, but can we copy from other variations?

**Comment by pmcpinto** [comment]
In the legacy UI, we show the notice when the user creates more variations, but let's wait to get Maikel's feedback.

**Comment by louwie17** [comment]
> @mdperez86, is that possible? I know we can't copy from the parent product, but can we copy from other variations?

@mdperez86 is AFK till Wednesday. so just responding for him.
It is possible to copy the price from other variations, but the slight problem there is that which variation will we choose to pick the price from? Always the first one?

I would almost think that we wouldn't want to auto set the price, to avoid confusion, and instead show the notice again.
This part also overlaps a little bit with the logic we discussed else where when adding a new attribute and taking the price from the previous created variation if the price was already added.

But we could certainly always go with the first variation with a price, and see what the feedback is.
Another option is if the user previously used the notice to add prices to all the variations, that we save that price as a `default` and use that for any future generated variations. Although we did probably want someway for the user to modify that default value if they wanted (for the specific product).

**Comment by louwie17** [comment]
<img width="650" alt="Screenshot 2023-09-18 at 4 32 08 PM" src="https://github.com/woocommerce/woocommerce/assets/2240960/32965a16-f073-471e-a19f-06fa47c07ddb">

@jarekmorawski do we want to use the same background colour here as the notice error from Gutenberg? Or go ahead with the one above? https://wordpress.github.io/gutenberg/?path=/docs/components-notice--docs

<img width="717" alt="Screenshot 2023-09-18 at 4 33 24 PM" src="https://github.com/woocommerce/woocommerce/assets/2240960/b138d475-0479-4280-a03b-44fa86481c18">

**Comment by jarekmorawski** [comment]
Let's use the one above. Gutenberg's a bit outdated and it'll be changed soon.

**Comment by jarekmorawski** [comment]
Additional context from p1695046860559099-slack-C01CMSA1VHS and pcQJnU-1PE-p2#comment-2109: we've decided to use the existing implementation and use the browser's dialog window to let users enter a regular price when they click `Set prices` in the modal. This means that it'll work exactly the same as the `Quick update` action.

> It is possible to copy the price from other variations, but the slight problem there is that which variation will we choose to pick the price from? Always the first one?

For the MVP, I think it's okay to just copy the price from the first variation no matter what. I'll update the AC.

**Comment by louwie17** [comment]
I am re-opening this, as it auto closed because of my PR.
I believe just this AC is still required: `If the user adds new variations by creating new options or option values, they inherit the stock and price from the first variation in the list.`
