### ISSUE TITLE
Update the select all behavior in the variations table

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#40214]
Currently, when the user clicks "Select all", we only select items that are visible on the page. Let's tweak that so all items on the page are selected when the user clicks the checkbox in the top left corner, but when they click "Select all", we select all existing items across all pages.

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1641_213260

**Acceptance criteria**

- [x] Clicking the checkbox in the top left corner selects all visible items.
- [x] We display the number of selected items, e.g., "5 selected".
- [x] Clicking "Select all" selects all _existing_ items.
- [x] We display a number of all existing items next to the button, e.g., "Select all (25)".
- [x] When all items are selected, the selection persists when the user changes pages. So, if I select 5 items on page 2 and 3 items on page 2, I'll see the selected items while switching between pages.
- [x] When only some items are selected on the page, we show an additional button that says "Select page (X)" where X stands for the number of rows on the page. Clicking it selects all rows on the page.
- [x] Clicking "Clear selection" deselects all items.

**Comment by mattsherman** [comment]
> Let's tweak that so all items on the page are selected when the user clicks the checkbox in the top left corner, but when they click "Select all"

I haven't seen this pattern before. It sounds confusing. I would expect the unlabeled checkbox and the "Select all" right next to it to do the same thing.

**Comment by jarekmorawski** [comment]
That's how Gmail currently works and I think it strikes a good balance between performance and user experience. Selecting items across all pages may impact performance, so it's better to offer that as a secondary action for users who actually require it.

When only some variations are selected, we'd display an additional button to select all items on the page.

<img width="698" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/52d17948-5dd1-49d2-97b4-6c4b117d2447">

**Comment by mdperez86** [comment]
@jarekmorawski 

I will add this to the project and implement this with your requirements. I would like to suggest here to track special events to be able to measure how this is going to behave, especially in those scenarios with large amount of variations. We should track the amount of selected variations and the whole time it takes to complete the bulk update request.

cc: @pmcpinto @AnnaMag

**Comment by AnnaMag** [comment]
@mdperez86, thanks for bring this up and +1 to the idea.

Let's revisit when the issue is back in scope, it was punted to the next round of enhancements.

**Comment by mdperez86** [comment]
@pmcpinto @jarekmorawski @AnnaMag 

During the implementation of this issue I found some points that are code limitations/rules intentionally hard coded and I want to share them with you so that we can make a decision on how/when we are going to bypass/change/keep them.

1. The first thing not necessary directly related to this issue is the cap that we have when generating variations which is currently 50, meaning that if the user adds options to go beyond the cap then only 50 variations will be generated. So, how the user is going to generate/create the rest if we don't have a way to create one or many in a different way than generating them?
2. If we want to `Select all` existing variations then we need and endpoint that responds at least all the variation ids we are selecting because they are needed to batch update them later. Well the endpoint already exists but we have another cap here, so we can only get a max amount of 100 variations. So if the user somehow is able to generate/create (remember the point 1) more than 100, then the select all feature is not going to work as expected.
3. And finally the batch update endpoint has also a cap of 100 items at a time, which means that event if we are able to select more than 100 in the point 2, then the user is not going to be able to save all, in fact for this case the server responds with and error.

So now that we know this 3 problematic things that are being implemented for performance reasons. What are we going to do? A cap will always exists since resources never are unlimited. And if we modify these caps for greater values then how the UI is going to behave when those limits are reached? Remember that we are going to deal with expensive/resource intense operations here and the user could take a long time waiting for the operation to be completed. If the operation takes too much time it can be cut by any network restriction or a php server execution time.

**Comment by jarekmorawski** [comment]
Thank you for a detailed overview, Maikel. It seemed that we should launch a small project to explore a better UX for handling the limits for creating and editing variations.

A few thoughts:

- From the top of my head, I'd suggest updating the cap from 50 to 200 variations or more. It's already [possible with code](https://tishonator.com/blog/how-to-increase-woocommerce-variations-count-limit) (and many merchants I spoke with used this workaround), so we might as well make it official.
- Maybe the cap could be an option somewhere in Woo settings? This would give us the space to explain possible consequences.
- The "Select all" behavior shouldn't have a cap and must always affect all existing variations. If we need a new endpoint for that, let's add it because it'll be useful later down the road (in the overhauled product list, for example).
- If the bulk edit operation on all selected variations will take a long time, we need some sort of UI to show the progress and let users pause, cancel, or resume the process in case of interruptions. The simplest solution would be to show above the Variations table a notice with a progress bar and contextual actions, but that'd probably mean building a new component.
- It sounds like some component changes are needed to make some of this stuff happen: we'd need a better snackbar with more options and a notice with the new features outlined above.

cc @j111q, since it's a design problem we must solve in the next couple of weeks. Let me know if you have any thoughts!

**Comment by AnnaMag** [comment]
cc @louwie17 - to consider this in the next cycle planning.

**Comment by pmcpinto** [comment]
I wonder if we should only allow them to use the "select all" option for up to 100 variations. @AnnaMag do we have data on how many users have more than 100 variations?
