### ISSUE TITLE
[Customize Your Store] Switch Theme to TT23

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#40462]
### User Story

> As a new merchant, I want to be presented with simple flows to customize my store, so that I can start selling sooner.

### Acceptance Criteria

```
Feature: Customize Your Store AI Wizard Loading Screen

  Scenario: AI Wizard loading screen is entered
    Given the AI Wizard loading screen is active
    Then the theme should be switched to Twenty Twenty-Three
```

**Comment by adrianduffell** [comment]
We may be able to utilize the [existing themes onboarding endpoint](https://github.com/woocommerce/woocommerce/blob/c552358ef51eccbad320d0425c73308bb778fac2/plugins/woocommerce/src/Admin/API/OnboardingThemes.php#L20-L21) to switch the theme.

**Comment by moon0326** [comment]
@adrianduffell By "AI Wizard Loading screen", do you mean the API Loader after submitting the store description in Design with A.I flow?

**Comment by adrianduffell** [comment]
> By "AI Wizard Loading screen", do you mean the API Loader after submitting the store description in Design with A.I flow?

@moon0326 Sorry - Yup, I mean in this loading screen:

<img width="687" alt="Screen Shot 2023-09-28 at 11 15 01 am" src="https://github.com/woocommerce/woocommerce/assets/9312929/e50c752a-133d-417a-9723-3cc18544c4e0">

**Comment by chihsuan** [comment]
https://github.com/woocommerce/woocommerce/blob/6d52afa5e99b8f2a179190d3a6a82c06d4f34326/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/CustomizeStore.php#L21


We will also need to modify the completion logic here because we don't want to mark the task completed during the loading screen. When user choose AI flow, we mark the task completed when the user clicks "Done" button on the Assembler hub.

A simple way may be to just ignore the theme switch from WooX default theme to TT3. Otherwise, we need to implement another way to mark the task completed when the user triggers the theme switch.
