### ISSUE TITLE
[Enhancement]: Validate phone field against country rules

### ISSUE THREAD

**Issue by KarlisJ** [woothemes/woocommerce#40544]
### Describe the solution you'd like

When a phone number is entered in checkout, it should be validated against the country. Right now, customers can enter any invalid phone number and submit it.

### Additional context

For some payment providers, like Klarna, the lack of a validation for phone field can cause problems as they expect that the number passed will be a valid number for the selected country.

**Comment by ArSenic04** [comment]
Can You tell in which file i have to edit

**Comment by opr** [comment]
Thanks for reporting this issue. I don't think that WooCommerce should be responsible for this level of validation as there are a lot of different standards/formats of phone numbers and finding out the patterns for each country and implementing these checks is a big task. Also, just because a shopper is ordering to a specific country, they may have a phone number from a different one, e.g. someone on vacation, someone ordering for a relative who lives abroad, or someone living close to a border.

If an extension requires a valid phone number, I'd recommend they implement their own validation system and check that the number meets their requirements before processing the order.

https://stackoverflow.com/questions/28603144/custom-validation-of-woocommerce-checkout-fields

In the case of WooCommerce Blocks, a similar approach can be used by [listening for changes in the billing/shipping address](https://github.com/woocommerce/woocommerce/issues/42185) and adding an error to the [`wc/store/validation` data store](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/validation.md) therefore preventing checkout.

A similar check would need to be implemented on the server side when processing the order to ensure no incorrect data is posted via the store API for example using [`woocommerce_store_api_checkout_update_customer_from_request`](https://github.com/woocommerce/woocommerce-blocks/blob/73d510362be8b149ac981f888f5b3c49bb8f2be1/docs/third-party-developers/extensibility/hooks/actions.md#L682).
