### ISSUE TITLE
[Enhancement]: update_meta_data() could be able to update $internal_meta_keys like update_post_meta()

### ISSUE THREAD

**Issue by Miguel-MultiSafepay** [woothemes/woocommerce#40545]
### Describe the solution you'd like

Dear WooCommerce team,

As we work on implementing the new High-Performance Order Storage (HPOS) feature, we've encountered the need to modify the '**_payment_method**' and '**_payment_method_title**' metadata in the '**wc_orders_meta**' DB table.

In certain scenarios of our payment platform, a user can change their selected payment method after leaving the checkout page of WooCommerce. We want to reflect this change in the database once a callback is sent to our plugin from our servers. However, we are currently unable to update the above-mentioned metadata in that table.

We've tried to use the '**update_meta_data**' method provided by WooCommerce to update this metadata. However, if the key is part of the '**$internal_meta_keys**' array, we are unable to add the new payment values to the '**wc_orders_meta**' DB table.

As you know WordPress's '**update_post_meta**' allows for the updating of any metadata in the '**wp_postmeta**' DB table. We are wondering if a similar functionality could be implemented in WooCommerce, perhaps with certain conditions that you consider appropriate.

We believe this feature request is important as it addresses a potential oversight. In our case, a user may select a generic payment method, only to choose a specific option later. We would like to accurately reflect these changes in the metadata, but we cannot use the current set of methods to do it.

While we could force an update on the '**wc_orders_meta**' DB table through a direct insert/update process, we would prefer to utilize the tools provided by WooCommerce. This would ensure our plugin remains fully compatible with your platform.

We would greatly appreciate your thoughts on this matter. Thank you in advance for your time and support.

Best Regards,
Miguel Perez

**Comment by jorgeatorres** [comment]
Hi @Miguel-MultiSafepay,

Thanks for the report. Please correct me if I'm wrong, but my understanding is that you'd like to modify some of these properties directly using WP functions such as `update_post_meta()`.

While this was possible pre-HPOS, precisely because we stored most details as post metadata, this information was meant to be modified using the CRUD API (i.e. `$order->set_payment_method(...)`) instead of the WordPress functions.

Is there any reason you specifically want to use the WP functions for this purpose?
By the way, `update_meta_data()` should still work correctly (as it does when HPOS is not active) but you have to save the order after making the modifications.

I guess an example will be helpful:

```php
// The following will work equally well with HPOS enabled and disabled.

$order = wc_get_order( 123 );
$order->set_payment_method( 'bacs' );

$order->set_payment_method_title( 'A Method Title' );

// The following is actually functionally the same as the above.
// $order->update_meta_data( '_payment_method_title', 'A Method Title' );
//

$order->save(); // important!
```

By the way, force updating `wc_orders_meta` (at least for the properties you've mentioned) won't work in HPOS as the method and method title data is no longer stored as metadata.

Please let me know if the above makes sense for your use case or if I've missed something. Thanks again for reaching out!

**Comment by Miguel-MultiSafepay** [comment]
Thank you very much for your reply.

Yes, basically the code you mentioned solves the issue.

It doesn't write on table wc_orders_meta: '_payment_method', and '_payment_method_title' as update_post_meta() was doing before HPOS, BUT is OK because is not necessary ... because the two methods you mentioned change the payment_method column on table wc_orders, which is pretty enough.

Another good point is that also changes the two meta_key columns: '_payment_method', and '_payment_method_title' on table wp_postmeta, without using update_post_meta(), so I was also able to remove the latter and use the methods you mentioned before, unifying the code and being valid for HPOS and pre-HPOS.

Thanks again for the great support.

Kindest regards,
Miguel

**Comment by jorgeatorres** [comment]
@Miguel-MultiSafepay: Good to know you were able to solve the problem by using the CRUD API. Feel free to reach out again if you need any assistance. Have a great day!
