### ISSUE TITLE
TT4 Order Confirmation styling issue

### ISSUE THREAD

**Issue by alexflorisca** [woothemes/woocommerce#40663]
## Describe the bug

On the order confirmation _page_ and _template placeholder_,  the horizontal list including the order number, date, email, total and payment method has bullets next to each item.

## To reproduce

1. Switch to WP 6.4 Beta
2. Activate the TT4 theme
3. Add something to your cart and checkout
4. See the order confirmation page looks like the screeshot below

## Expected behavior

The list should not be bulleted.

## Screenshots

![Screenshot 2023-10-03 at 11 27 09](https://github.com/woocommerce/woocommerce-blocks/assets/3966773/339c1911-20f5-4dd6-9bdd-6b13f64c1b93)

### WordPress (please complete the following information):

-   WordPress version: 6.4-beta1
-   WooCommerce version: 8.1.1
-   WooCommerce Blocks version: 11.2.0
-   Site language:
-   Any other plugins installed:

**Comment by nielslange** [comment]
Upon investigating, I discovered that the issue impacts the standard WooCommerce core order confirmation page. It specifically affects the Twenty Twenty-Four theme. Older themes remain unaffected due to WooCommerce's use of legacy CSS, as seen in:
- [Twenty Twenty-One CSS](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/css/twenty-twenty-one.scss)
- [Twenty Twenty-Two CSS](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/css/twenty-twenty-two.scss)
- [Twenty Twenty-Three CSS](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/css/twenty-twenty-three.scss)
