### ISSUE TITLE
Legacy Reports are not compatible with HPOS

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#40671]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
When HPOS is active (without sync), the legacy WC > Reports section is empty.

To reproduce:

1. Go to WC > Settings > Advanced > Features and make sure HPOS (no sync) is active.
2. Create a couple of orders in WC > Orders including certain items.
3. Go to WC > Reports.
4. No reports available.
5. Go to WC > Settings > Advanced > Features and enable sync.
6. Wait until orders are synced.
7. Go to WC > Status > Tools and **Clear Transients**.
8. Go back to WC > Reports and confirm that data is available.

**Comment by dcx15** [comment]
Just want to say that this is a big issue which stops me moving to HPOS on the sites I manage. It would be great to fix in an upcoming release.

**Comment by barryhughes** [comment]
Noting here that legacy reports have been deprecated for approximately 4 years, and so addressing this is not a high priority from our perspective.

<img width="1123" alt="legacy-reports-notice" src="https://github.com/woocommerce/woocommerce/assets/3594411/c65543a2-13cb-4eab-807d-d14ed54c0e7b">

If there are limitations stopping you from adopting the new Analytics experience, please don't hesitate to comment on existing bug reports and enhancement requests, or create new ones as required.

**Comment by dcx15** [comment]
Hi @barryhughes, understood, and I do appreciate why this may be low (or indeed zero) priority issue. Hopefully my thoughts below can give an outsider view from someone that manages several high traffic/order stores.

We disable the new analytics feature on our stores because:

1. Ultimately we don't need the features that come with the new analytics, which compounds the following points further
2. In testing, it was heavier and slower, more requests to server etc
3. As far as I'm aware, it requires WC Admin, which adds Javascript bloat to wp-admin and a lot of extra unnecessary pages/sections to the screen. We currently disable WC Admin due to this.

I'd bet that 90% of sites that benefit most from HPOS will also disable analytics and WC Admin for similar reasons. After all, HPOS is designed to optimize storage and performance for large and established stores. Enabling WC Admin and the new analytics has the opposite effect.

It would be a shame if the official implementation of HPOS was not backwards compatible with legacy reports, especially since many people will be migrating from https://github.com/liquidweb/woocommerce-custom-orders-table which does work with legacy reports.

**Comment by barryhughes** [comment]
> As far as I'm aware, it requires WC Admin.

I think it is worth noting here that [WC Admin](https://wordpress.org/plugins/woocommerce-admin/) is now fully integrated into the core plugin. It may still be possible to disable it, via custom code, but it is still very much a part of the default core experience.

> Ultimately we don't need the features that come with the new analytics.

OK, but can the unwanted reports (or functionality) provided by the new analytics experience just be ignored? If that isn't practical, perhaps there are UI improvements we can offer? The reality is, we don't really have the resources to support two parallel systems that, at a high level, serve the same need.

> In testing, it was heavier and slower, more requests to server etc.

That's fair feedback, and I understand the concern but, building on the last point, maintaining two solutions for the same core problem isn't really viable. Perhaps the best course of action is simply to create issues or discussions (or up-vote/participate in any suitable existing ones) that aim to improve the 'new' Analytics experience. I'm sure they would be welcomed.

**Comment by superbmario** [comment]
@barryhughes

I'd like to add my +1 for making the legacy reports system compatible with HPOS. My reasons are similar to what has been mentioned so far. I have a large store which I was hoping HPOS would minimize server resources and database storage size. This is the exact same reason I disable the new Analytics feature too. Any store with a large volume of orders will most likely take a similar approach. We offload our metrics to Google Analytics and use the legacy reports feature to compliment/confirm any general results.

Regarding WC Admin in general, please note the responses on [this post](https://developer.woo.com/2021/05/18/request-for-comments-removing-the-filter-to-turn-off-woocommerce-admin/). There are many people that have this feature disabled and have no need for it.

I also think there should be a similar discussion or request for comments about making HPOS compatible with legacy reports, as I suspect there will be many people in similar situation to myself too.

Lastly, if legacy reports were not updated to process HPOS data, this will be a divergence from what the WooCommerce Subscriptions team [announced previously](https://developer.woocommerce.com/2023/03/07/woocommerce-subscriptions-hpos-understanding-next-steps/). Specifically "we decided to temporarily disable our reports while we work on updating them to support the new HPOS feature".

**Comment by lkraav** [comment]
Metorik probably solves all reporting problems far better than WC core ever could, or probably will in the future, at a cost level pretty much everyone can afford. @bryceadams lives and breathes to continue making it happen.

As long as external platform syncing API queries continue to be properly optimized, there are at most negligible overall performance effects.

Reporting at the modern fidelity we are expecting esp. on larger stores, is a whole standalone product, not some bench player feature.

I say good riddance. Deleting code is a significant win for having more bandwidth for other mission critical core things.

**Comment by nburch** [comment]
Hello all,

I just wanted add my voice here. I have to respectfully disagree with @lkraav - However it is implemented reliable, scalable, solid reporting is fundamental to the very nature of any e-commerce platform. 

There are a few major issues we have experienced related to the new-ish reports. 

1.) First off and most majorly is that the newer reports seem to **provide inaccurate numbers.** - They are not off by much, but they're are off consistently. Gross Sales amounts, Net Profit, Items Sold, and even number of orders over a given period will often be different from the legacy reports. Sometimes it's just a little but sometimes there can be a statistically significant difference over a given time period. 

In our case, this presents an issue of having to make a choice. But our internal auditing has found the legacy reports more reliable. 

2.) **This is for legal and business purposes.** Things like tax reporting, audits, contractual agreements, etc. require having reliable numbers as a basis to pay vendors and more. Getting a different set of books with different numbers is very problematic for all sorts of reasons. 

3.) As noted above a _major issue_ in our case is the lack of support for Woo Subscriptions. This is a deal breaker of us as we need to be ale to track various things related to subscriptions for business purposes. As pointed out by @superbmario in the posts he linked to this position seems to contradict the statements made by the Woo Subscriptions team, as well as support tickets. 

So, until this is resolved our site with 700K orders and 200K customers is stuck in "hybrid" mode and cannot reap the benefits of HPOS*. 

*Side Note: So far on staging site when running in pure HPOS mode for testing, we have not found HPOS to give us the speed of scalability bump that we had hoped - Several posters on [THIS THREAD](https://github.com/woocommerce/woocommerce/issues/41317#issuecomment-2046956712) have noted that it seems slower than "custom orders table plugin" precursor.

**Comment by lkraav** [comment]
> I just wanted add my voice here. I have to respectfully disagree with @lkraav - However it is implemented reliable, scalable, solid reporting is fundamental to the very nature of any e-commerce platform.

You're certainly not wrong. But odds of such a hifi reporting product emerging in core any time soon is a low odds bet.

For business longevity, if marketplace already has a much better solution ready to go, why not switch and profit immediately?

**Comment by nburch** [comment]
> or business longevity, if marketplace already has a much better solution ready to go, why not switch and profit immediately?

Fair Question! 3rd party reporting is certainly something we are looking into. 

One of the issues, especially at sites with large scale & long history, is that testing any such system takes a significant amount of time and potentially touches a lot of moving parts. 

To date, the existing reports have worked like a champ so, until this issue with HPOS/Woo Subscriptions popped up, it was not top of the list. 

EDIT: I should also add that since the Woo Subscriptions team has indicated they are working on a solution it has caused a bit of a "wait & see" stalemate on which direction might be best. 

Secondly, one potential hurdle at least in our case is a policy of minimizing who has access to our sales and customer data. This can be for both security and privacy reasons.  

In a post GPDR world it's always surprising to me how many plugin dev's will simply request admin access to a site to troubleshoot issues. 

I think as a general rule it's a good practice to try to minimize 3rd party access as much as possible.

**Comment by jorgeatorres** [comment]
Thanks everyone for the feedback and the discussion here! We understand that the situation with Subscriptions and the "new" reports, which seems to be the most urgent problem, is not ideal, but our understanding is that they are working on it. Also worth mentioning that we offer compatibility mode to help with things like this, at least until proper HPOS support is added by 3rd party code or plugins. Obviously this doesn't come without its drawbacks.

Considering the legacy reports have been deprecated for more than 4 years (even completely hidden in certain cases), we're going to close this issue now. Keep in mind that even if stable, Reports is a complex part of the codebase, and the effort required to add HPOS support might not be trivial, even if we ignore the chance of introducing new bugs in deprecated/unmaintained code.

Feel free to reach out in case I've missed something!
