### ISSUE TITLE
Spike: Explore the feasibility of releasing Woo AI for self hosted stores

### ISSUE THREAD

**Issue by nima-karimi** [woothemes/woocommerce#40837]
The objective is to assess the feasibility of making the Woo AI functionality, currently only accessible on Woo Express, available as a standalone plugin or as an integral part of the WooCommerce core, and explore the potential for enabling these features on websites using the Jetpack plugin or by utilizing the Jetpack connection package recently incorporated in Woo core.

**Comment by tommyshellberg** [comment]
The other side of this is not just technical feasibility but the costs side.
If the reason for limiting the exposure of Woo AI is to gather feedback without incurring a lot of costs due to using external services, would it be easier to open up Woo AI if we switched to internal text completion? The costs would surely be significantly lower, provided we have the resources available.

**Comment by nima-karimi** [comment]
> The costs would surely be significantly lower, provided we have the resources available.

I wonder if we have a way to measure and compare the cost of running the same prompts (for the same amount of requests) on our internal infrastructure versus using external APIs.

There are also a few more unanswered questions; before we switch over to the internal infrastructure, we need to know the following: 

- Can our current infrastructure handle a large volume of requests? 
- What's the current maximum capacity? 
- Are we prepared to scale it efficiently?

**Comment by nima-karimi** [comment]
P2 post published: pf8sIm-61-p2
