### ISSUE TITLE
[Enhancement]: Enable Cart and Checkout Blocks as the default checkout experience on WooCommerce

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#40865]
### Describe the solution you'd like

The primary goal of this project is to enable the Cart and Checkout blocks as the default experience for new stores running WC 8.3+ (released on Nov 14th). This decision is driven by the understanding that the initial impression a user forms tends to stick with them. While there is potential for enhancements, it is essential to guarantee a bug-free experience for users when they interact with these blocks. Maintaining user trust is vital, as it promotes engagement and excitement for the upcoming improvements to the Checkout block-based experience.

Project Thread
pdFofs-1sE-p2

### Describe alternatives you've considered

An attempt at doing this from WooCommerce Blocks was blocked by WordPress plugin activation in a sandbox, making it impossible to attach custom code to the `woocommerce_create_pages` filter on `WC_Install::class` execution. Changes must be made directly in core, a change that would naturally occur after WooCommerce Blocks merges into the monorepo, saving future tech debt on both repos.

Original epic from Blocks:

https://github.com/woocommerce/woocommerce-blocks/issues/11264

### Additional context

The change will affect content for the default content on Cart and Checkout pages, created on WooCommerce Activation and by running WooCommerce > Status > Tools > Create Pages.

**Comment by DavidAnderson684** [comment]
I don't think this should be done before the work for adding custom checkout fields - https://github.com/woocommerce/woocommerce-blocks/discussions/11173 - has been completed. Otherwise, what are extension developers supposed to do - to create their custom fields in other ways so as to be ready when blocks become the default, and then port it over to the new interfaces a second time afterwards?
