### ISSUE TITLE
[Enhancement]: Clean old order data from _posts and _postmeta tables after migration to HPOS structure

### ISSUE THREAD

**Issue by rwkyyy** [woothemes/woocommerce#41062]
### Describe the solution you'd like

a function/option/button that cleans the unused order data stored before migration

### Describe alternatives you've considered

writing a risky SQL query / function and test it out on a local bench

### Additional context

While testing migration to HPOS I have noticed that for existing stores, there is no way to clean the old(unused) data! Upon testing on bigger stores I have noticed that from a 2GB table size it jumps to 3.8GB! This becomes an issue when the database has to query both orders table (HPOS structure) and other posts data, it eats a lot of memory and has to wait a lot for the engine to parse that big table size (for real reason).

**Comment by jorgeatorres** [comment]
Hi @rwkyyy,

Thanks for the report. I get what you're saying and rest assured, this has always been the end goal. We're already working on some improvements to the HPOS tooling that will enable us to offer the ability to cleanup old data from postmeta safely once HPOS is enabled. You can follow either #40714 or #39656 for updates on this specific topic.

I'm going to close this issue as a duplicate but feel free to re-open if I've misinterpreted anything.

Thanks again!

**Comment by jorgeatorres** [comment]
@rwkyyy: I forgot to mention that, if you wish so, you can disable sync altogether which should limit the number of data that gets added to the old tables. We also have the filter `woocommerce_hpos_enable_sync_on_read` which will only disable sync on read (reducing the need to query both tables) but will still write to the posts table for backwards compatibility.

**Comment by rwkyyy** [comment]
Hello @jorgeatorres and thank you for the fast reply! Right now I have all my projects set in compatibility mode as most of the plugins I use are not fully compatible, but I want to see them (the projects) in the not-so-far future as being fully set on the new table architecture.

**Comment by makeonlineshop** [comment]
Thank you to make it happen ! If you need beta testers I have not so important live websites on which I can try.

**Comment by JeremyAcyba** [comment]
Hi, please do not overlook WooCommerce Subscription meta data when a _postmeta cleaning option is added 🙂

**Comment by thinkjarvisdesignandmarketing** [comment]
Has this been implimented?
@rrennick @rwkyyy 
You cant just move the data to the new table and leave the old redundant data there. That is a joke! If you have a store with 50,000 orders then that is a stupendous quantity of data in the posts and post meta table. This will increase the lookup times for all post queries.

The only thing I can think of doing is running something like this:
https://www.businessbloomer.com/woocommerce-bulk-delete-orders-products-super-fast/

`
DELETE FROM wp_woocommerce_order_itemmeta;
DELETE FROM wp_woocommerce_order_items;
DELETE FROM wp_comments WHERE comment_type = 'order_note';
DELETE FROM wp_postmeta WHERE post_id IN ( SELECT ID FROM wp_posts WHERE post_type = 'shop_order' );
DELETE FROM wp_posts WHERE post_type = 'shop_order';
`
Question - 
As far as I can see - These are the old order tables? **Can anyone confirm?**
But
Delete from WP_Comments above - **Does HPOS move the order notes to the new db structure?** If not then I will need to remove this from the query above to safely remove all old orders.

**Comment by jorgeatorres** [comment]
Hi @thinkjarvisdesignandmarketing!

As I mentioned, this is the next step for HPOS: cleaning up metadata from the WordPress tables that's no longer in use. We understand this leads to some duplication for the time being (even after disabling compatibility mode) but we'll definitely be providing a tool for that in a future version. We're just making sure that our current validation is robust enough so that this doesn't result in any serious data loss.

I wouldn't suggest running risky queries _right now_ unless you're entirely sure that HPOS is working fine for you. Provided you take precautions (database backup, etc.) you could try something like the following:

```sql
DELETE pm.* FROM wp_postmeta pm WHERE pm.post_id IN (SELECT id FROM wp_wc_orders)
```

Again, our suggestion would be to wait for the proper verification/cleanup tool. **Please don't run any of the queries you listed above** as that can result in data loss:

- Order items and item meta (`woocommerce_order_items` and `woocommerce_order_itemmeta`) are still used in HPOS. Deleting data from those tables will result in all orders losing their items.
- Order notes are still stored as comments.
- For the time being, a record will still need to exist in the `wp_posts` table for every order (as a placeholder).

In regards to the HPOS project, besides fixing of any critical bugs, cleaning up metadata is one of our top priorities. Hope this helps clarify the situation. Feel free to follow the issue linked above (or [our public HPOS board](https://github.com/orgs/woocommerce/projects/124)) for our progress.

Let me know if you have any questions!

**Comment by thinkjarvisdesignandmarketing** [comment]
@jorgeatorres 
Thank you for your detailed response.
I 100% agree I will wait for an official tidy up feature.

Thank you for clarifying the queries above I wouldnt want someone to run them and break their DB so your response is massively appreciated.

I have one client in particular with 20,000 orders. So we will be migrating them to HPOS. But 20,000 orders is a lot of data sat in the post tables. This will increase the lookup times in that table - It almost defeats the point of HPOS.

So I am looking forward to seeing the full migration process integrated into WC.
It makes total sense - Plugin developers are still updating plugins for compatibility - So there will likely be bugs to fix so by not instantly letting us delete from the old tables is probably a good idea. Just dont leave it too long! :)

**Comment by Joe-HolisticPPL** [comment]
@jorgeatorres Thank you so much for taking time to clarify :)

1 
how to get notified about legacy orders cleanup tool ?? ETA ?

2 
please advise: suggested workflow - without cleanup tool -  Is exporting all orders, delete all, and re-importing as HPOS only could work ? - see below 


Use case: 
WC 8.3x 
15,000 orders in legacy posts table 
switched to HPOS - compatibility mode

A
 I realize it could have been better to wait with HPOS - it actually added to our site db size. I consider deleting the HPOS new table until the cleanup tool is ready. or just wait for the cleanup tool.

B
without a proper cleanup tool - the recommendation to switch to HPOS could be better addressed to shops with OR without X size of legacy orders history. 
I'm not sure what X size of legacy orders - would make it performance-wise cost-effective to switch to HPOS. 
given that old legcy orders are ACTUALLY KEPT we wouldn't switch to HPOS yet. and cleaning up HPOS is not easy as well.

**Comment by Joe-HolisticPPL** [comment]
2
is this workflow without cleanup tool worthwhile ?
thank you @jorgeatorres @rwkyyy @thinkjarvisdesignandmarketing 

starting point:
Shop with HPOS in compatibility mode 
  - tons of orders history is duplicated.
  - new orders do work well with HPOS.

cleanup steps:

- clone to dev site
- export ALL orders (wp all export plugin)
- delete ALL orders - both HPOS and legacy order
  ==> how well is the cleanup when deleting ALL orders with wp admin, and then with db cleanup tool [meow db cleaner]

- switch to HPOS only. turn off compatibility.
- re-import all orders into HPOS only, as in WC 8.2+
- push all orders to live

in our use case this orders re-import is anyhow needed because we import order data from other sales channel into WC

Thank you so much

**Comment by rwkyyy** [comment]
> 2 is this workflow without cleanup tool worthwhile ? thank you @jorgeatorres @rwkyyy @thinkjarvisdesignandmarketing
> 
> starting point: Shop with HPOS in compatibility mode
> 
> * tons of orders history is duplicated.
> * new orders do work well with HPOS.
> 
> cleanup steps:
> 
> * clone to dev site
> * export ALL orders (wp all export plugin)
> * delete ALL orders - both HPOS and legacy order
>   ==> how well is the cleanup when deleting ALL orders with wp admin, and then with db cleanup tool [meow db cleaner]
> * switch to HPOS only. turn off compatibility.
> * re-import all orders into HPOS only, as in WC 8.2+
> * push all orders to live
> 
> in our use case this orders re-import is anyhow needed because we import order data from other sales channel into WC
> 
> Thank you so much

for a few Ks of orders, it's OK, but for 100k+ orders, you either pay thousands of bucks on servers and you still have to wait a few hours, or you wait for a cleanup tool; either way this solution is more costly than effective.

I do not have all used plugins in my stack HPOS compatible yet, so it's not a rush, but would like to see it in near future!

**Comment by majidempire** [comment]
Unfortunately, the HPOS procedure lacks full compatibility with its WooCommerce plugin, such as the WooCommerce status widget in the WP dashboard. When compatibility mode is turned off and only HPOS tables are used, it displays outdated and inaccurate data. Consequently, due to the necessity of continuous syncing, the system requires twice (and maybe more) the resources when an order is added or removed. This occurs because parallel records are added to two separate table systems.

Until now, this seems like the most viable solution. However, I'm uncertain about the implications of exporting orders and subsequently clearing them from the WC admin, especially considering the considerable time it takes due to the shops' extensive order volume. My concern lies in the impact on customers: upon re-importing orders, will they seamlessly reassign to their respective existing customers or users?

So what is the HPOS main goal? does it mean to run only new shops ?

**Comment by thinkjarvisdesignandmarketing** [comment]
> Unfortunately, the HPOS procedure lacks full compatibility with its WooCommerce plugin, such as the WooCommerce status widget in the WP dashboard. When compatibility mode is turned off and only HPOS tables are used, it displays outdated and inaccurate data. Consequently, due to the necessity of continuous syncing, the system requires twice (and maybe more) the resources when an order is added or removed. This occurs because parallel records are added to two separate table systems.
> 
> Until now, this seems like the most viable solution. However, I'm uncertain about the implications of exporting orders and subsequently clearing them from the WC admin, especially considering the considerable time it takes due to the shops' extensive order volume. My concern lies in the impact on customers: upon re-importing orders, will they seamlessly reassign to their respective existing customers or users?
> 
> So what is the HPOS main goal? does it mean to run only new shops ?

Exactly what @majidempire said - I was wrong our store has 50,000 orders in it not 20,000 and that number is growing daily. (2 years worth of orders).

We must have a mechanism built in to the migration process that removes the records from the original tables. HPOS is currently not ready for the production environment unless you are running a new store.

**Comment by jorgeatorres** [comment]
Hey @Joe-HolisticPPL!

Thanks for reaching out. Some answers below:

> how to get notified about legacy orders cleanup tool ?? ETA ?
We will be publishing a post shortly on our [dev blog](https://developer.woo.com/blog/) about HPOS and next steps. We've prioritized fixing some bugs that have been reported since the initial availability of HPOS, but we're definitely working on the cleanup tool.

We've outlined specific tasks in this issue: https://github.com/woocommerce/woocommerce/issues/40714.

We realize this is important and I can assure you it's the next thing on our list.

> please advise: suggested workflow - without cleanup tool - Is exporting all orders, delete all, and re-importing as HPOS only could work ? - see below

Given you already have the data in your db, I don't think it's worth exporting and re-importing. If your site is already running with HPOS and you're certain about things working fine, you could start by disabling sync/compatibility mode and, provided you take reasonable precautions (backups, etc.), you could just manually remove everything related to orders from the `postmeta` table (not the `posts` table!).


> without a proper cleanup tool - the recommendation to switch to HPOS could be better addressed to shops with OR without X size of legacy orders history.

You're right. That's why it's only the default for _new_ installs for now. Our goal, though, is for everyone to switch to HPOS (no sync mode) and that's why we're focusing on the cleanup tool now that we've had some time to fix critical bugs and work on stabilization.

**Comment by jorgeatorres** [comment]
Hey @majidempire! 👋 

Please report any compatibility issues you find with WC when running with HPOS active. We're currently tracking the status widget one you mentioned in https://github.com/woocommerce/woocommerce/issues/40382 and will be adding a fix to WooCommerce soon. Please do report any other issues you find. We definitely want to address those.
