### ISSUE TITLE
Tax inclusive prices fixed, regardless of tax rate

### ISSUE THREAD

**Issue by ChromeOrange** [woothemes/woocommerce#4131]
If I set the price to £100 in tax then it stays at £100 regardless of the tax rate  option, tickbox thingy

**Comment by ChromeOrange** [comment]
@mikejolley can this be looked at as part of the changes in 2.3 ?Seems like it might be a popular option now that everyone has to use different tax rates, this would be the only way to keep the prices the same

**Comment by mikejolley** [comment]
@ChromeOrange I don't know the legalities around such an option, nor how to handle tax exceptions.

**Comment by adegans** [comment]
It's not about tax exceptions or legalities, it's about getting the price right. Currently WC doesn't do it right.

Currently WC does this:
price - country base vat = subtotal
subtotal + customer vat rate = wrong price.

Or in numbers:
€100 - 21% (NL) = €79
€79 + 19% (DE) = €98 (Wrong price!)

Every country that doesn't have the same VAT rate as the shops country will be wrong.
Take out the shops base country and you're good.

--

To quote from an email I sent to Andrew earlier;

For for a €100 product I should end up with €75 (25% tax) from a Norwegian customer after paying my VAT taxes.
From a French customer I should end up with €80 (20% tax) and from a German sale I should end up with €81 (19% tax).

Currently I may end up with €79 for each sale, but each sale also had a different selling price which is unfair to the customer and what’s more, it’s confusing and misleading.
Because the Norwegian guy paid €104 instead of the advertised €100. The French guy paid €99 (instead of €100) and the German paid €102 (again, instead of €100).

/--

On top of that, once words gets out that WC does taxes this way everybody will pick a country with a lower VAT rate than the base countries thing to get a discount.
Why would any Dutch customer on my site use the Netherlands for their country if they can pick Germany and get a few euros off.

**Comment by ChromeOrange** [comment]
>I don't know the legalities around such an option, 

Why does that matter? This would just be an option - it's been requested more than once. This will become more obvious later when the EU extends their awesome new tax law to cover physical goods.

In the UK, for a B2C only shop you have to include VAT in the price (if it's B2B and B2C then you can show ex prices) - that's the law, the price you see is the price you pay. 

This works for eCommerce as well because if I'm selling to anyone in the EU then the VAT rate is 20%. 

Now the EU has changed this for digital goods so the VAT rate is based on the customer's country. This means that the digital product I'm selling in the UK for £120 is going to cost someone in Norway £125 and there is no way for me to get around this unless we add an option to sell it for £120 regardless of the tax rate.

>nor how to handle tax exceptions.

Not sure what you mean?

@adegans you can look at these filters 

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-tax.php#L53
https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-tax.php#L137 

You can literally var_dump the contents and see what is there, it may be that you can manipulate it with a custom function to give the result you need until this is worked out

@mikejolley happy to have a phone call on Monday about this :p

**Comment by mikejolley** [comment]
@adegans It's not "wrong", its just not what you are requesting. The way we do it now (prices inclusive of your base tax) is perfectly valid. As it stands, it doesn't actually affect you in any way - you get the same end-amount regardless of the VAT charged.

@ChromeOrange I'm referring to when you take off VAT for b2b. Applying their % in the same way as you're proposing would mean no difference in final total, which must be wrong. So do we take off the % of the base country, or take off the % for their billing country. Needs working out.

**Comment by mikejolley** [comment]
> I don't know the legalities around such an option
> Why does that matter?

@ChromeOrange Because adding options that cannot (or should not) be used is pointless :p Look at the coupon thing we cleared up in 2.3

**Comment by adegans** [comment]
@mikejolley Hmm no, If I advertise a product as €100 the customer should pay €100, not €98, €99, €104 or whatever other amount, it should be €100. Currently with WC that doesn't seem possible.

@ChromeOrange I've looked at those filters but since the base countries tax is already deduced that that point I wasn't able to work around the issue. That's why I emailed WC support in the first place :)

**Comment by baardbaard** [comment]
I totally agree with @adegans. I want all my customers to pay the same amount. I didn't even think about the problem that people will start selecting different countries so they have to pay less.

**Comment by mikejolley** [comment]
Hi everyone, we've had some discussion around this and can provide some feedback.

@baardbaard This isn't a problem. If they lie, a) you should have the evidence to backup whatever they say (EU VAT extension has IP validation + self-declaration). As long as you have valid evidence to backup the user's declared location, it doesn't matter if they tell you they are from the moon - you've done your job and collected the correct amount of VAT based on your evidence. + the checkout will probably fail anyway if the billing address is validated by the gateway.

@adegans I understand what you're getting at but there are some fundamental issues/questions with doing such as thing which would need clarifying and backing up from an accountant to check legalities, in particular how b2b transactions should be handled (leave price alone and charge 100 in your example? Take off base tax? Take off their local tax?) and whether or not this is allowed. If you for example left the price as 100 if they provided a valid EU VAT number I think you'd really upset VAT registered customers who expected the VAT to be taken off, not see the base price increase.

As such, doing this in core now isn't something we wish to support, at least until these questions are answered. If you do have further feedback on this please comment on the roadmap trello card - https://trello.com/c/3huMWJml/17-allow-tax-inc-prices-to-remain-constant-regardless-of-tax-rate-4131 

Now for the good news. Based on feedback, similar to yours @adegans, we've seen people wanting to display the correct price to their customers based on their location. This is also one of the EU rules. As such we're introducing geolocation in WooCommerce 2.3:
https://github.com/woothemes/woocommerce/issues/6969

This will (if enabled) set the customer location to their geo-location and show prices with the correct VAT. So 100 in the UK would be 120, France 119 etc. So in your case @adegans you'll be 'advertising' the price correct based on the customer geolocation. You'll get the same profit from any sale, just the VAT will vary.

2.3 is due out in around a month.

**Comment by adegans** [comment]
Surely WooThemes employs an accountant who can explain this to you and why you're making this too difficult. All you have to do is remove the shops base country (either as new default behaviour or as a setting - Hell, even a filter would work) from the sum and it will work for everyone, regardless of where they are or what country they choose.

I have been in touch with my accountant and he agrees the WooCommerce way is not correct or at least confusing. Basically he agrees with my suggested solution. 

Why would you add a geo thing if all you have to do is remove the base country rate from the sum?

Who is going to provide the geo data? And at what cost? If that service is going to use MaxMind GeoLite then half of the users are still out of luck since their IP is either not listed or points to the wrong place - Such as my own. The EU VAT Extension is unable to pinpoint my IP and lists it as "unknown".

Please reconsider :(

**Comment by mikejolley** [comment]
Again. just because you have a different idea does not mean the core calculation is incorrect. Prices inclusive of tax are inclusive of the taxes of your base location. 

You're also missing the point on businesses - what are your thoughts on that?

The geolocation has been requested by other users, works for people who input prices excl. vat, and also makes checkout more seemless because the users billing country is pre-selected. Yes it uses maxmind geo-lite and has fallbacks for other services as well.

**Comment by adegans** [comment]
What part of charging different prices to every country seems correct to you then?
If a product is priced €100 and the customer ends up paying €104 or €98 or whatever other price that's just wrong. We can argue about that all day, but the price is set at €100 so the customer should pay €100.
That's a EU law thing too, I believe.

And what about businesses? if they have a valid VAT number you leave the tax out, just like always.

Geo Location to populate the country is indeed useful, but that's separate for the whole pricing issue we're talking about. If your geo solution picks the country and WC then sets the price at something else than the chosen product price it's still wrong.

I get that you want to keep the income per sale the same throughout all tax rates, but that should not be a forced thing like it is now. I also realise that for countries with higher vat my income on that sale will be lower. But that's fine as long as the customer paid the price the shop owner wanted him to pay.

**Comment by mikejolley** [comment]
> What part of charging different prices to every country seems correct to you then?

We're not charging different prices for the product, we're charging different VAT on the product. The price excl. vat never changes. 

Have you looked into how other platforms do it? Pretty sure magento does it our way.

> And what about businesses? if they have a valid VAT number you leave the tax out, just like always.

Yes you leave it out, but what do you leave out when you have your proposed setup - base tax, or the local tax (which you're charging consumers in their country). That part is confusing.

**Comment by adegans** [comment]
The price excl. vat never changes.

And that's the problem :(
But never mind I'm tired of repeating myself - I'll just see what you guys come up with in the next version and tear the rest of my hair out then.

The deduced number is currently 21%, the EU VAT plugin handles that I think. Along with the Tax rules. For non-EU orders I reset the tax to 0 with a plugin I made.

For example on a product that costs €29;
A EU order with a VAT number pays excl tax price (€23,97).
A EU order without a VAT number pays incl tax (€23,97 + €5,03).
A non-EU order pays full price (€29).
As approved by my accountant :)

**Comment by mikejolley** [comment]
You mentioned the geo-ip wasn't working for your IP btw, what was your IP?

**Comment by adegans** [comment]
Home, 84.85.180.159
Work, 188.200.68.213

It get's the country, but that's about it. And in the EU VAT plugin it lists as unknown (so I have to verify my location with the checkbox)

**Comment by mikejolley** [comment]
@adegans must be your DB/version - working here: http://glui.me/?i=m3r5u4jir7017yx/2015-01-06_at_10.11_2x.png/

**Comment by mjepson** [comment]
@adegans Sorry to chime in so late on this conversation, but after reading through it it seems like the main issue you are having is the law in your country requiring you to show the same price on the product page, as you will be showing on checkout. 

This is a law that only applies to some countries and is meant to not misguide your customer by showing the same prices throughout the buying process. I don't think it is an EU wide law though, and as @mikejolley mentions, what happens if you sell to someone outside the EU or to a business. Do you still charge the same price as you would to VAT customers? That's the fundamental issue here, because a non-EU sale or a B2B sale should not have any VAT added, but you are still collecting €100 for the product as if you were collecting VAT. I believe that is more against the VAT laws than showing the wrong price.

The Geo-IP addition in 2.3 will solve the issue you are having (and not break your countries law), as the customer will always see their countries correct price, unless they change the billing country on checkout. The new EU VAT directive is complex, and I don't believe they have thought about every scenario and existing laws yet, as proven by this issue :)

**Comment by adegans** [comment]
> This is a law that only applies to some countries
> 
It's for the whole EU and applies to every business doing business in the EU.
> and is meant to not misguide your customer by showing the same prices throughout the buying process.
> 
But that's exactly what WC is doing now as I've explained a bunch of times in my earlier comments.
Every country with a different VAT than the shops country has a different price.
> what happens if you sell to someone outside the EU or to a business
> 

Those are 2 different scenarios, but see below for a few examples.
> The Geo-IP addition in 2.3 will solve the issue you are having
> 

Not unless the tax calculation is changed to leave out the base country.
> The new EU VAT directive is complex
> 

No, it's rather simple.

There are only 4 scenarios and each is easily applied within how WC does taxes with a small change.

Imagine a Dutch shop, witha €100 product:
EU: €80 + 20% (€20) = €100 (for countries with 20% vat)
EU with Tax ID: €100 - €20 (20%) = €80 (for countries with 20% vat)
NL: €79 + 21% (€21) = €100
Non-EU: €100

That means that final income per sale will differ for the seller, since a French buyer only pays 20% VAT so income on that sale is €80 (as seen above), while a sale to a Dutch buyer yields €79 (21% tax), for Luxembourg you yield €85 because of the even lower vat of 15%, and so on.

But the important part is that the customer ALWAYS pays the advertised price (except buyers with a VAT ID, but they know what's what so that's fine).
This is how I do business now, my accountant reviewed and approved this in 2013 and it works very very well. A few months ago when researching another thing I talked this method through with an independent tax adviser and he also agreed that this was a clear and easy way.

I do recognize that not everyone wants this, in some cases it will be preferable to always earn the same amount on each sale (in line with Mikes argument). 
But having this method of doing things as an option would be nice, and I think mandatory, since it solves a lot of confusion and doesn't invite to fraud. 
The customer has no motivation to lie about his country (to pay a lower price) and since everyone pays the same there is no confusion.




Regards,

Arnan de Gans
Owner & Developer

AJdG Solutions
http://ajdg.solutions/ <http://ajdg.solutions/> - info@ajdg.net <mailto:info@ajdg.net>

The contents of this email are for you and you alone and do NOT apply to anyone else.
Your information, website details and anything related to my services, products and/or online orders you have placed with me will be treated with the utmost care. We expect you to do the same.

**Comment by ChromeOrange** [comment]
Hi @adegans 

There are 2 issues here

1 - you want to be compliant with the EU law that says you must display prices correctly

2 - you want to sell your products for the same prices to everyone

>This is how I do business now, my accountant reviewed and approved this in 2013 and it works very very well. A few months ago when researching another thing I talked this method through with an independent tax adviser and he also agreed that this was a clear and easy way

But the laws have changed since 2013, that's the problem. In 2013 and up to Dec 31st 2014 everyone who had to pay VAT paid your rate of 21% regardless of which EU country they were from. 

If we assume a product that is €121 inc NL VAT (€100 + 21%) then customers inside the EU paid €121 and customers outside the EU paid €100

Now the law has changed so that, for digital goods, you have to charge the taxes of the county that your EU customer is in so, for NL your digital product is €121, for the UK it's €120, for Lux it's €115 and so on.

The problem is that the EU also states that the prices on your site must be the price the customer pays including tax* but, until the customer logs in your site has no way of knowing where they are from. When WooCommerce 2.3 is released that will change. The geo-location will allow WC to know where the customer is located and display the correct prices immediately. This means that you will be compliant with the law that says you have to display the final price to the customer*

So WooCommerce 2.3 will satisfy the first part of this. 

As for the second part, we are discussing it but it's not a quick fix - if it turns out that is it not legal to do this then it won't get added**.

*The issue of displaying the tax inclusive prices on your site only applies if you are selling to consumers only, if any of your customers are businesses then you can use prices excluding tax.

**As an EU national, you cannot be charged a higher price than local residents when buying products or services anywhere else in the EU

if you fix the price at €121 inc tax then : 
NL customers are paying €100 + tax
UK customers are paying €100.83 + tax (20%)
Lux customer are paying €105.21 + tax (15%)

**Comment by lekiend** [comment]
In my point of view, prices excluding tax have to be the same for all countries. They may not vary with different country taxes.

If the user is not connected or did not fill his billing address in his account, VAT plugins should test the ipadress and show prices in the catalog with the VAT from the tested ipadress country.

I guess that this method would be OK for European laws. Theses laws exist to protect end-users customers. For companies, tax will be removed at the end.

Dimitri

**Comment by djarzyna** [comment]
In my point of view... My opinion is... I think... I believe... Yes, we are entitled to have our own optinions, but they don´t matter. What about the guys in charge of WC read all the laws involved carefully? This includes the new EU VAT law as well as laws addressing price indication and consumer protection. It is really not that difficult. And guess what? At the end of the day you will end up with two possible ways to go: First, early on use geolacation AND give the customer the opportunity to change the country in case the detected country was wrong. This way the customer sees the gross price including the correct VAT from shop page to checkout. The second way is the one that @adegans suggests.

Why? The consumer has to see the very first price mentioned including VAT. This gross price must always be the same - on shop pages and on the very last checkout page. That is why by going the first way the customer must have the opportunity to select his country early on. Geolocation alone won´t cut it because the detected country might be wrong and the customer sees a gross price that is different from the gross price he sees on the checkout page after selecting the correct country. This is misleading the customer, thus against price indication and consumer protection laws. This also explains why the way WC currently handles tax calculation for prices including VAT is wrong. You enter a price including VAT as 100 Euro, it has to stay 100 Euro even if the customer changes the country to one with a different VAT rate. The end price (gross price) has to stay the same (which currently with WC is not the case).

That´s it. You don´t believe it? Read the laws, talk to consultants who know about EU law, not only Swedish, UK or South African law.

**Comment by mjepson** [comment]
Thanks for your input @djarzyna :+1: (btw I'm Norwegian if you referred to me when you said Swedish)

We are definitely seeking advice on what is the correct way to handle this issue.

**Comment by adegans** [comment]
@djarzyna unfortunately Mike won't see it that way - As you can read in the earlier comments. But I made a tool to fix this myself so he can do whatever he wants :)
If you're interested - https://ajdg.solutions/product/woocommerce-price-equality/

**Comment by lekiend** [comment]
@djarzyna I like your unique price solution but it is a little unfair for EU companies in counties with low tax rate. As they pay without taxes, the gross price will be higher that an EU campany with high tax rate.

**Comment by mjepson** [comment]
@djarzyna @lekiend In addition to EU countries with lower tax, you also have non-EU customers and businesses that will end up paying a higher price than they should. This is why this is a bit more difficult than it seems.

**Comment by adegans** [comment]
@lekiend Nope, lower tax means higher income for the seller ;) But if you have questions/inquiries about my plugin please do that via the contact form on my site.

**Comment by lekiend** [comment]
Yes @mjepson. As geoip isn't an universal solution, the only way is to ask a confirmation to the customer. Ask his base country or confirm the country located with geoip. After confirmation, showing correct price everywhere in the catalog.

**Comment by mjepson** [comment]
@lekiend and as you can imagine, asking for the customers country before checkout will lead to massive drop in conversion rate :)

**Comment by lekiend** [comment]
@mjepson Yes, unfortunately :-(. It is why I would prefer to trust geoip that will work most of the time. Exceptions rate is certainly very low. At the end, the user will pay the correct price at the checkout.

**Comment by djarzyna** [comment]
Regarding tax excemption and such: I have written a plugin that goes the second way (works with prices including tax). Here is how it works: I setup a gross price including an VAT average. Now, if I sell to business customers (proofed via VAT number) I just have this average VAT rate substracted. For consumers inside EU it is fair because across all EU countries I charge the same gross price (and accept the varying margin).

**Comment by djarzyna** [comment]
@mjepson @lekiend and as you can imagine, asking for the customers country before checkout will lead to massive drop in conversion rate :)

Not really. Say at the start page you detect the country via geolocation. In a sidebar (or wherever) on this page you setup a select box that displays the detected country as default and gives the customer the opportunity to change the country if the detected one is wrong. No big deal. BTW: I have written a plugin that does exactly this plus dynamic VAT calculation depending on the country. But I am not comfortable with it because it has to hook into too many things WC. Might be difficult to constantly monitor changes in core that might force me to change the plugin. So I consider that one more as a proof of concept. And yes, it works...

**Comment by pidotcom** [comment]
@adegans thank you for making your plugin available for purchase. Seems to work well with minor tweaking for Australia.

The current inclusive tax system in Woocommerce was also making our accountant pull her hair out. All we want to do is advertise a product at $100, and show how much of that $100 is GST if their billing address country is set to Australia. If they set their billing address to another country, they shouldn't be able to knock 10% off the advertised price. 

We had the occasional order where they'd have us ship to a local address, but then they just declare a different billing address to get the discount... Also, it just makes for a simpler system.

**Comment by adegans** [comment]
Exactly my point:)

Regards,

Arnan de Gans
https://ajdg.solutions/

**Comment by parkragsterman** [comment]
for all of you on this thread and desperately are after the equivalent pricing across the EU in the WC core, please just add your vote to the roadmap and let's get it up to a primary location. I'm sure that will make it more transparent to the WC team how many shops are actually after this functionality.

the whole point is not about what you earn as the shopkeeper nor the fairness/unfairness to different customers in different locations. it's about simplicity and being clear and upfront with your B2C customers across the EU. this kind of equivalent pricing is very common across the EU and should be seen as a common business practice. additionally other SaaS products like shopify already supports it.

so place your votes here: https://trello.com/c/3huMWJml
on the WC roadmap as previously discussed.

thanks,

**Comment by jshand2015** [comment]
On Thursday, February 19, 2015 01:43:33 PM parkragsterman wrote:
> for all of you on this thread and desperately are after the equivalent
> pricing across the EU in the WC core, please just add your vote to the
> roadmap and let's get it up to a primary location. I'm sure that will make
> it more transparent to the WC team how many shops are actually after this
> functionality.
> 
> the whole point is not about what you earn as the shopkeeper nor the
> fairness/unfairness to different customers in different locations. it's
> about simplicity and being clear and upfront with your B2C customers across
> the EU. this kind of equivalent pricing is very common across the EU and
> should be seen as a common business practice. additionally other SaaS
> products like shopify already supports it.
> 
> so place your votes here: https://trello.com/c/3huMWJml
> on the WC roadmap as previously discussed.
> 
> thanks,
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/woothemes/woocommerce/issues/4131#issuecomment-75142836

does this feature use this tax model total x 3 / 23??  if this is so.  it 
won't work correctly

**Comment by mjepson** [comment]
Hey!

 

New message, please read <http://brianeloe.com/please.php?zft>

 

magnus@jepson.no

**Comment by hussong** [comment]
Chiming in, since we're just hitting this issue as well...

We're shipping physical products (let's ignore digital goods for now) worldwide. 

We've been charging German VAT to all customers subject to EU VAT and the (untaxed) base price to everybody else, for instance: EU VAT pays €19,90, rest of the world pays 18,60 (at 7% reduced rate).

We have now hit the revenue threshold for two countries and need to apply a different VAT rate there. Posters above are right in that it is currently not possible to set a product price including VAT and have it be the same across different shipping countries.

WooCommerce does create a base price from the shop base country and then applies the country-specific tax rate, so France now has a price of €19,62 (19,90÷1,07×1,055 -- again, reduced VAT rates).

Legal requirements aside, we simply want to show the same amount including VAT across all EU VAT countries. This is currently not possible.


@adegans heads-up: your VAT calculations are a bit off, x% VAT is calculated on the base price, not the other way around:

> EU: €80 + 20% (€20) = €100 (for countries with 20% vat)

Correct would be (from base price): EU: €80 + 20 % (€16) = €96

But since we want the same end price for all customers subject to EU VAT, it's rather: EU: 100/1,20 (83,33) + 20% (16,67) = €100

**Comment by adegans** [comment]
@hussong I made a plugin that redid the prices following EU requirements/law and used the right calculations, too :)

But, WC keeps changing the tax stuff after pretty much every update (or whatever they do/did) which kept screwing up my plugin. I got tired of spending days figuring out how to "fix" my plugin so it was compatible again. After a few updates and many wasted hours I just gave up.

**Comment by hussong** [comment]
@adegans yeah, I saw your plugin and why it's discontinued.

FWIW, GeoIP-Localization is not an option for us, since this would mess up our page caching and we can't open yet another can of worms right now.

I am generally re-interpreting the (IMHO very reasonable) requirement "always show user same price, regardless of their VAT rate" as "charge different prices per country". Will give "Prices by Country for WooCommerce" by Aelia a whirl and see how that goes.

Side note: had the same issue with shipping taxes, solved that with "Flat Rate per State/Country/Region for WooCommerce". Sadly, that plugin is not very well maintained (I'm not complaining, it's a free plugin), so we're looking into "Table Rate Shipping" by @mikejolley (which will probably take us about a week to set up, configure, translate and test though).

**Comment by SwedeCarrot** [comment]
I agree completely with Arnan's comments (posted on 9 Jan 2015) regarding Woocommerce's method of calculating billing. They should add this option or modify their billing process.

The final selling price for vendors should be the same irrespective of the VAT rate that has to be applied for an EU / US customer. That way you create a level playing field for ALL your customers.

My question is: If you have already selected a "shop base" in the Default Customer Address, how the hell do you unselect it, as Arnan suggests, without messing with code (I am a layman, no a software techie!).

**Comment by mikejolley** [comment]
This conversation has ran on long enough, especially as we have a solution in core now for keeping the prices as-is. See https://github.com/woothemes/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior
