### ISSUE TITLE
Issue with New Product Editor for Virtual or Downloadable Products

### ISSUE THREAD

**Issue by Chrystll** [woothemes/woocommerce#41584]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I encounter a problem when trying to use the new product editor for virtual or downloadable products. If these options are checked, the new product editor becomes inaccessible, I still get the classic product editor. However, by unchecking these options, I can access the new product editor.

### Expected behavior

 I expect to have the new editor available even for virtual or downloadable products.

### Actual behavior

I have the classic editor with the virtual and downlodable products.

### Steps to reproduce

1. Navigate to WooCommerce > Settings > Advanced > Features and enable the new product editor.
2. Edit a simple product set as virtual or downloadable => you get the classic product editor
3. Uncheck the virtual or downloadable option, save your changes, and you'll be redirected to the new product editor.

**Request for Information:**
I've read that the new editor will be functional by early 2024. Could you provide a more specific date (which month)?

### WordPress Environment

[system status report.zip](https://github.com/woocommerce/woocommerce/files/13415869/system.status.report.zip)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by louwie17** [comment]
Hi @Chrystll,
Thanks for creating this issue. At the moment this is expected behaviour as the new editor doesn't support the virtual and downloadable products yet, which is why we redirect to the classic product editor.

Having said that, we have actually added support for virtual/downloadable products as part of our next WooCommerce release and should be supported with WooCommerce 8.4, which is planned to be released on Dec 12th ( next week ).

> I've read that the new editor will be functional by early 2024. Could you provide a more specific date (which month)?

Unfortunately not yet, we are currently discussing the remainder of the work to come up with a more specific date/month.
You can keep an eye out for this here: https://developer.woo.com/roadmap/block-based-product-creation-experience/

I will close this issue, given this will be available in WooCommerce 8.4 ( feel free to re-open if you notice an issue around this ).
