### ISSUE TITLE
"views_edit-shop_order" and "parse_query" filters are not working when HPOS in ON

### ISSUE THREAD

**Issue by pulkitjuneja-1216** [woothemes/woocommerce#41636]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"views_edit-shop_order" and "parse_query" filters are not working when HPOS in ON. I am trying to add a custom filter to the WooCommerce orders section. The above filters are properly working when HPOS is OFF and POST tables are ON for order creation.

### Expected behavior

custom filters should be visible in the woo-commerce orders section when HPOS is ON.

### Actual behavior

Not able to see custom filters in woo-commerce orders section when HPOS is ON

### Steps to reproduce

1. Add the below code to the main file of the custom plugin.

````php
 add_filter( 'views_edit-shop_order', array( $this, 'ced_amazon_add_woo_order_views' ) );
add_filter( 'parse_query', array( $this, 'ced_amazon_woo_admin_order_filter_query' ) );

/**
	 * Add filter in order
	 *
	 * @since    1.0.0
	 */
	public function ced_amazon_add_woo_order_views( $views ) {
		if ( ! current_user_can( 'edit_others_pages' ) ) {
			return $views;
		}

		echo 'yes';
		$class        = ( isset( $_REQUEST['order_from_amazon'] ) && 'yes' == sanitize_text_field( $_REQUEST['order_from_amazon'] ) ) ? 'current' : '';
		$query_string = esc_url_raw( remove_query_arg( array( 'order_from_amazon' ) ) );

		$query_string = add_query_arg( 'order_from_amazon', urlencode( 'yes' ), $query_string );

		$views['amazon_order'] = '<a href="' . $query_string . '" class="' . $class . '">' . __( 'Amazon order', 'amazon-for-woocommerce' ) . '</a>';
		return $views;
	}

	/**
	 * Add filter in order
	 *
	 * @since    1.0.0
	 */
	public function ced_amazon_woo_admin_order_filter_query( $query ) {
		global $typenow, $wp_query, $wpdb;

		if ( 'shop_order' == $typenow ) {

			if ( ! empty( $_GET['order_from_amazon'] ) ) {

				if ( 'yes' == $_GET['order_from_amazon'] ) {

					$query->query_vars['meta_query'][] = array(
						'key'     => 'ced_umb_order_sales_channel',
						'compare' => 'EXISTS',
					);
				}
			}
		}
	}
```

### WordPress Environment

6.3

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @pulkitjuneja-1216! 👋

Thanks for reaching out. This is on purpose as re-use of hooks could be problematic in certain cases (due to certain hooks expecting `WP_Post` instead of `WC_Order`, for example).
In any case, in HPOS you could use filter `views_woocommerce_page_wc-orders` to add your own views (in lieu of `views_edit-shop_order`).

Similarly, you could use `woocommerce_order_list_table_prepare_items_query_args` ([ref](https://github.com/woocommerce/woocommerce/blob/808a0fc54f6fbc202e35e9d655694929c884a817/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L402
)) to modify the arguments in the query.

Hopefully you'll find this useful. If you have any more questions, we suggest reaching out via [the community Slack](https://woo.com/community-slack/), as GitHub is reserved for bugs and enhancements. For HPOS-specific questions, you can use the #hpos-upgrade-party channel.
