### ISSUE TITLE
Seeking WooCommerce Order Update Hook Events

### ISSUE THREAD

**Issue by namnv1997** [woothemes/woocommerce#41941]
Previously, I used the "save_post" hook to update orders in WooCommerce. However, it is not working now. 

I've attempted other hooks, such as "woocommerce_update_order" and "woocommerce_saved_order_items" but they haven't performed as desired.
The "woocommerce_update_order" hook triggers multiple times, while "woocommerce_saved_order_items" retrieves order data before it is saved.

**Comment by mikejolley** [comment]
Hi @namnv1997 

Orders are still technically posts so `save_post` would trigger, however, this isn't really an appropriate hook to use since it runs for all post types.

I'm not sure what you mean by "performed as desired" but `woocommerce_update_order` is fired every time an order is saved with changes so that should work for any use case. This hook gets passed both the order ID and order object. If you're saving the order again within this hook you need to take care that your code isn't causing an infinite loop which would cause it to fail. Also note that its true `woocommerce_update_order` will fire multiple times, since multiple things may be updating the order around the same time.

If you're looking for checkout events instead there are hooks such as `woocommerce_checkout_order_processed` and `woocommerce_store_api_checkout_order_processed` which run once. 

I hope this helps. I'm going to close this issue because hooks do already exist.

Thanks
