### ISSUE TITLE
[Enhancement]: Add “Shipped” order status

### ISSUE THREAD

**Issue by natko1** [woothemes/woocommerce#41959]
### Describe the solution you'd like

I think it would be great to add this as a default order status, bit surprised this hasn’t been added yet.

**Comment by Konamiman** [comment]
Hi @natko1, thanks for your idea. We already have an open request for this feature here: https://woo.com/feature-request/shipped-order-status/, feel free to vote for it and add a comment if you have further feedback on it.

**Comment by natko1** [comment]
Thanks! Any progress on it or is it actively being looked into? Almost a year in.

Hopefully this can be implemented without mandatory tracking as some stores ship products standard mail (no tracking). But changing the order to shipped instead of completed makes more sense and customers know that their product(s) were shipped.

**Comment by HLFH** [comment]
@Konamiman Would you accept PRs on that? I use connectors to sync WooCommerce to Odoo. I added a plugin on WooCommerce that supports custom order statuses such as "shipped". But because it is not a default status provided by WooCommerce Core, the third-party connector does not have to support it. So when an order has just been shipped or is completed/delivered is handled the same way, and it is a major issue.

**Comment by Konamiman** [comment]
Hi @HLFH, we're working on a project to implement an additional "fulfillment status" for orders (additional to the regular order status), which should cover your use case. We can't provide more details yet, but we'll make a public announcement once it's ready to test.
