### ISSUE TITLE
[Output] Provide integration in Airtable to generate a report from a view

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#41985]
Airtable [allows for extensibility](https://support.airtable.com/docs/button-field) in it's interface. See if it's possible to add a form/button accessible for any view in the FSOR table that will trigger a report being generated on the containing rows.

We may want to limit this to only views containing a minimum number of records.

One complicating factor is that we may need a way to decide on the number of clusters, and perhaps other parameters, for these report runs. It may make sense to generate a higher number of clusters for larger views, and less for smaller ones.

This will also likely involve exposing the Ray service via a WPCOM endpoint of some kind.

**Acceptance Criteria**
- [ ] A form/button to generate a report is accessible from a view.

**Comment by nima-karimi** [comment]
I did some research into this and it seems the easiest and most straightforward way would be to add a script on the Airtable interface so that people can run. This script will access a WPCOM endpoint to trigger a report generation job.

An example screenshot:

![Image](https://github.com/woocommerce/woocommerce/assets/73110514/dad23905-c746-4cab-b20e-6ae7d99c26b8)


However, this should be on hold until we get the ai-services PR merged since that is a dependency.

**Comment by nima-karimi** [comment]
This diff is ready for review: D133765

**Comment by nima-karimi** [comment]
I've merged the proxy endpoint for this and also wrote the Airtable script required to call the endpoint. The script is added to both the dev and prod instances and also included in the https://github.com/Automattic/ai-services/pull/924 for future reference. Closing the issue since it is completed.
