### ISSUE TITLE
Consider storing additional fields in individual meta values instead of a single one.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42025]
Currently, we store the additional fields values in a single meta field per group (billing, shipping, additional), this means values are saved as a serialized array, which means they're not searchable or filterable (You can't add UI to filter orders and customers per custom value).

Saving them in a single meta field per field would make that easier.

**Comment by mikejolley** [comment]
Should we still do this @senadir? Current system seems to be working ok ¯\_(ツ)_/¯

**Comment by senadir** [comment]
Well we would have a hard time doing this down the road, I think the value we would see possibility to filter/query orders by value?

**Comment by webdados** [comment]
This is mandatory. The current storage in three arrays make it virtually impossible for developers to filter order by their meta fields.
Also: the meta key name should be easily changed during the field registration. I see this new extensibility being used primarily by developers who already have custom fields in place on the classic checkout, either in the form of custom development or plugins (and this is where things can get messy) and they need to be able to store the values on the exact same meta they're already using.

**Comment by webdados** [comment]
We should be able to set:

- Field ID on the checkout form
- Meta key for orders
- Meta key for users

This can be (and it is currently) different in many cases. For example, look at the official WooCommerce EU VAT plugin.
The field name on the classic checkout is `woocommerce_eu_vat_number`. The meta key for orders is `_billing_vat_number` and the meta key for users is `vat_number`. This is an official WooCommerce plugin.

The first people to actively use this new API are going to be plugin developers updating their already existing plugins to work with the blocks checkout, enriching the WooCommerce ecosystem. It's not expected that they (me included) need to change all their plugin logic because of this. They should only be required to declare the news fields, and use the same IDs and meta keys they already used for the classic checkout

**Comment by webdados** [comment]
Is there any further discussions on this going on behind the scenes?

**Comment by senadir** [comment]
Not really, we know we will work on this, but we didn't start on it yet (it's the next thing to do, and will happen before graduating the API to stable).
