### ISSUE TITLE
Product Gallery: Investigate the use of template part for the popup overlay lightbox

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#42044]
We have tentatively agree to use template part for the popup overlay with minimal user configurable settings for the initial phase.

We need to investigate what is possible here. In my early research it seems you are bound to all the editor settings as the product block and cannot remove/hide any settings. Is this possible without some hacky ways? If we leave it showing, it would be very confusing as we don't intend to make any of those settings functional for now.

Deliverable:

- Investigate if we can even use the template part without surfacing all the editor settings

**Comment by danieldudzic** [comment]
I believe since there isn't much time left until launch we should give up the customizability of the Template part/Pop-up for now, by:
- Implementing the no-thumbnails design suggested by @jarekmorawski: p1701362746136319-slack-C02FL3X7KR6
- Preventing the Product Gallery template part from being registered (and surfaced in the Template Part editor)
