### ISSUE TITLE
Filter blocks should support block and global style

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#42056]
Supported style attributes can be carried over from the current filter blocks. Currently, filter blocks only support text color.

Note: The dropdown should respect the color setting.

**Comment by samueljseay** [comment]
@dinhtungdu 

Notes:

* https://github.com/woocommerce/woocommerce/pull/43068 addresses block style for text color only.
* Note that existing filter blocks where they do support color also only support text color right now.

Questions: 

* Could you elaborate on how the blocks should support global style?
* I go back and forth on whether text support should include text color of inputs like in price slider, but since the dropdown is sort of an input too, shall we color the text of inputs in price slider do you think?

**Comment by dinhtungdu** [comment]
> Could you elaborate on how the blocks should support global style?

When a block registers support using Supports API, it's automatically registered to Global style.

> I go back and forth on whether text support should include text color of inputs like in price slider, but since the dropdown is sort of an input too, shall we color the text of inputs in price slider do you think?

I think yes, the price slider also have an option to show only text, not input, so the color can be applied there logically.
