### ISSUE TITLE
Checkout Block: HTML Tags Are Not Stripped from the Payment Gateway Description

### ISSUE THREAD

**Issue by Babylon1999** [woothemes/woocommerce#42123]
## Describe the bug

If you add a description for a payment gateway, for instance, BACS, and wrap it with some HTML, the HTML tags will be displayed on the front end.

## To reproduce

<img src="https://d.pr/i/DhZ9hH+" alt="">
Link to image: https://d.pr/i/DhZ9hH

<img src="https://d.pr/i/SKK95N+" alt="">
Link to image: https://d.pr/i/SKK95N

## Expected behavior

The tags to be removed.

### WordPress (please complete the following information):

-   WordPress version:  6.3.2	
-   WooCommerce version: 8.2.1

### Desktop (please complete the following information):

-   OS: MacOS
-   Browser FireFox

## Additional context

Reported originally in zd-7254448

https://wordpress.org/support/topic/new-block-checkout-strips-doesnt-display-html-in-front-end-from-payment-descri/

**Comment by nielslange** [comment]
Thanks for reaching out, @Babylon1999. I was able to reproduce this issue, but also noticed that the HTML tags are visible in the classic checkout. For backwards compatibility reasons, I believe that HTML tags should be allowed in the Checkout block rather than stripping them out. I'll add this issue to our backlog for now and discuss further steps with our team.

<table>
<tr>
<td valign="top">Classic checkout:
<br><br>
<img width="755" alt="Screenshot 2023-11-08 at 11 37 02" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/7bd53850-31e4-4f3b-bb31-986ec2b3b57f">
</td>
<td valign="top">Checkout block:
<br><br>
<img width="691" alt="Screenshot 2023-11-08 at 11 37 12" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/a77cc5bb-4ead-468b-b6c1-3e5f808da24d">
</td>
</tr>
</table>

A while ago, we applied changes to [Allow rendering HTML in shipping package names](https://github.com/woocommerce/woocommerce-blocks/pull/7147). Part of that change was introducing the function [`sanitizeHTML`](https://github.com/woocommerce/woocommerce-blocks/blob/f3fc0ac00d791e186159bcc842ae487ebb7e0463/assets/js/utils/sanitize-html.ts), which we could use in this case.

**Comment by Babylon1999** [comment]
> For backwards compatibility reasons, I believe that HTML tags should be allowed in the Checkout block rather than stripping them out.

My bad  🤦‍♂️ , that's what I actually meant for the tags to be rendered, not removed, just like with shortcodes.

**Comment by nielslange** [comment]
> > For backwards compatibility reasons, I believe that HTML tags should be allowed in the Checkout block rather than stripping them out.
> 
> My bad 🤦‍♂️ , that's what I actually meant for the tags to be rendered, not removed, just like with shortcodes.

All good, @Babylon1999. 😀
