### ISSUE TITLE
Billing address prefilled with the shipping address once shown in the checkout

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#42140]
## Describe the bug

If I have shipping address filled with some data and then decide to use a different one for the billing (via checkbox), I see billing already prefilled with shipping address. We should have billing address empty in this case.

## To reproduce

1. As a guest go and add some item to the cart
2. Proceed to the checkout
3. Fill shipping address with any data
4. Click checkbox to use a different address for the billing
5. Observe issue

## Expected behavior

Empty field for the billing address

## Screenshots

GIF: https://d.pr/i/F1QCUg

## Additional context

Discussed on Slack: slack/C02TS23QJ1X/p1699025951440299

**Comment by opr** [comment]
Hi @veljkho - I don't agree that this is a bug, rather an opportunity for improvement.

Baymard suggests it should be cleared too https://baymard.com/premium/guideline-collections/ahnvda/566 (3,1)

I'll re-label this and add it to our backlog!

**Comment by pmcpinto** [comment]
@ralucaStan we should add this one to the next cycle backlog, as it's a good low-effort improvement to the shopper experience.

**Comment by ralucaStan** [comment]
this should also be fixed in the shortcode side https://github.com/woocommerce/woocommerce/issues/30258

**Comment by tarunvijwani** [comment]
>this should also be fixed in the shortcode side https://github.com/woocommerce/woocommerce/issues/30258

@ralucaStan I have done some investigation and found that in the Checkout block, we're syncing the shipping address with the billing address. That's why we have the billing form pre-filled. It was controlled through JS/React. This will be fixed in https://github.com/woocommerce/woocommerce/pull/44347. 

In the Checkout shortcode, the billing address is initially correct. However, it is mistakenly taking the shipping address field and updating it in the billing address field as changes here: https://github.com/woocommerce/woocommerce/blob/7bc3312ab775e689d94e46aecf5014b8f13d2f06/plugins/woocommerce/includes/class-wc-customer.php#L465
These changes are being controlled by PHP when we load the Checkout page. We need to investigate more when and how these changes are occurring and fix them to override the billing address. Hence  https://github.com/woocommerce/woocommerce/issues/30258 needs to be worked on separately.

**Comment by senadir** [comment]
Any idea why we limited this to guest only?
