### ISSUE TITLE
Product Collection block - "Return to top" behavior/option when loading new page/results

### ISSUE THREAD

**Issue by gfarma** [woothemes/woocommerce#42195]
## Is your feature request related to a problem? Please describe.
The problem with pagination at the product collection block is that the page stays at the same point. It doesn't drive you at the top.

## Describe the solution you'd like
I think we should have the choice after clicking the next (or previous) page to drive you at the top of the block.

## Additional context
When I click page two: https://prnt.sc/EwS5tksg08aF then the page stays at the same level https://prnt.sc/7LEfmfTog2yw.

**Comment by kmanijak** [comment]
Thanks @gfarma for this issue!

@imanish003 , do you remember what's the latest here? I think we explored this idea to scroll to the top of Product Collection when changing pages.

**Comment by gfarma** [comment]
Hi @kmanijak @imanish003 any update regarding this?

**Comment by imanish003** [comment]
Hi @kmanijak @gfarma,

As far as I remember, we implemented this feature, but then decided to remove it because it doesn't always make sense to direct the user to the top of the page. For instance, if there are five Product Collection blocks on the same page, and the user utilizes pagination for the bottom-most block, it might not be logical to always take them to the top. We'll need to investigate the most effective way to address this.

A potential solution would be to adopt the approach used by the Query Loop block. After successfully navigating, they focus on the first clickable element of the new page, typically the feature image (if clickable) or the post title. Consequently, the browser automatically adjusts the scroll position to accommodate this change in focus for accessibility reasons.

Here's a quick demo video illustrating how this works in the Query Loop block:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/d63e300a-d464-477e-98b2-8db19c55f8d5

I believe adopting a similar approach as the Query Loop block could be beneficial since we're essentially addressing the same issue. What are your thoughts?

**PS:** [This PR](https://github.com/WordPress/gutenberg/pull/53812) introduced the change in Query Loop block.

**Comment by gfarma** [comment]
Hi @imanish003 @kmanijak. Considering the above I think the anchor should be optional (so if someone has many of them in a page it will work only at the selected). Then it should drive you back at the top of the Product collection block with an offset value (with - + values) maybe to adjust the height, not at the top of the page. Offset is essential to cover almost all scenarios. What do you think?

**Comment by imanish003** [comment]
Hi @gfarma, Thank you for your valuable input 🚀

> Considering the above I think the anchor should be optional (so if someone has many of them in a page it will work only at the selected)

Could you please clarify what you mean by making the anchor optional?

> Then it should drive you back at the top of the Product collection block with an offset value (with - + values) maybe to adjust the height, not at the top of the page

To elaborate on my earlier suggestion, when a page changes, we can focus on the first product in the product collection. This will automatically move the user to the top of the Product Collection block, bringing the focused element into view.

**Comment by gfarma** [comment]
Hi @imanish003,

> Could you please clarify what you mean by making the anchor optional?

I mean to add a button like this: 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/e137db9f-3855-435e-8a5f-4065e6cf4895)
to make it optional backend
Something like "anchor link" or "drive at the top"
With this feature if someone don't need it, just leave it disabled.

> To elaborate on my earlier suggestion, when a page changes, we can focus on the first product in the product collection. This will automatically move the user to the top of the Product Collection block, bringing the focused element into view.

yes but I think an Offset value to control the height of the drive to top is crucial.
Maybe someone would like to to display also the sorting after the pagination. And the sorting at most cases is above the first product.

Hope that helps :)

**Comment by imanish003** [comment]
Hi @gfarma,

Thank you for the detailed explanation; I genuinely appreciate it. 

Here's my proposed approach:

1. Focus on the first product so that the browser will automatically scroll to the focused element when the page changes. This seems like a logical initial step.
2. If that doesn't adequately address the issue, we can explore other methods which might necessitate input from a UX designer.

I'd also like to note that we'll be implementing a Scroll layout for the Product Collection. Consequently, we'll need to factor that into our considerations. For more information, please refer to the Github discussion [#10692.](https://github.com/woocommerce/woocommerce-blocks/discussions/10692)

@kmanijak What do you think?

**Comment by gfarma** [comment]
Hi @imanish003 sounds good to me :)

Regarding https://github.com/woocommerce/woocommerce-blocks/discussions/10692 Scroll layout, "pagination" is not necessary. Scrolling or arrows by moving 1 card (product)/per click at the arrow seems a good choice. 

One last recommendation about the block, maybe you should add how many products to display per page

**Comment by imanish003** [comment]
Hi @gfarma,

> Regarding https://github.com/woocommerce/woocommerce-blocks/discussions/10692 Scroll layout, "pagination" is not necessary. Scrolling or arrows by moving 1 card (product)/per click at the arrow seems a good choice.

Agreed! I meant to say that we need to keep the scroll behaviour in mind(while implementing scroll layout) to avoid refactoring later on 🙂

> One last recommendation about the block, maybe you should add how many products to display per page

From your current message, I gather you're mentioning a feature that appears to already exist, as depicted in the image below:
<img width="400" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/16707866/599d6eba-7982-4b99-8251-6838299c91cc">


If there has been any misinterpretation on my part regarding your recommendation, please let me know. Your input is highly valued and greatly appreciated.

**Comment by gfarma** [comment]
Hi @imanish003 ,

> From your current message, I gather you're mentioning a feature that appears to already exist, as depicted in the image below:

This feature is not working when you enable 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/3fa37016-cd67-46f6-a150-be5415b3e677)
is this something that is done on purpose?

**Comment by imanish003** [comment]
Hi @gfarma,

> This feature is not working when you enable
> is this something that is done on purpose?

Currently, query settings are hidden when the "Inherit query from template" option is enabled. Our methodology mirrors that of the Query Loop block. By enabling "Inherit query from template," we defer to the template's predetermined query parameters and refrain from modifying them. This strategy ensures that the template's functionality remains intact. However, I believe we can consider allowing modifications to the query settings that do not compromise the template's integrity.

What are your thoughts on this, @kmanijak  @manospsyx?

**Comment by gfarma** [comment]
Hi @imanish003 ,

Is the anchor feature in the near future roadmap?

**Comment by imanish003** [comment]
Hi @gfarma,

I agree that it would be a great addition to our roadmap. At the moment, our attention is centered on the tasks listed in Epic https://github.com/woocommerce/woocommerce/issues/42161. I'll bring this up with the team and see how we can fit this feature into our planning. Your input is very much appreciated. Thanks! 🙏🏻

**Comment by Aljullu** [comment]
Heads-up that we received another request in https://github.com/woocommerce/woocommerce/issues/42829.

**Comment by Brianmitchtay** [comment]
We've received another request for the scroll to top behavior on Product Collection Block pagination in 7516771-zd-a8c
