### ISSUE TITLE
Sticky the order summary/cart summary when scrolling

### ISSUE THREAD

**Issue by webdesksoft** [woothemes/woocommerce#42230]
## What do you think is missing from the Cart & Checkout blocks?

Hello, I would like to say that you've added a new feature to the cart and checkout blocks,,, especially for those blocks that hold the summary part of the cart and checkout. 

# feature that you should add to this cart and checkout is 

sticky position at X axis with the position value for the desktopn mode. if suppose user have added multiple products into the cart and then he did scroll then the cart summary widet disapperared mean they scrolled up at top and not visible in front of user to proceed to checkout very easily.

same feature for the checkout summary widget that hold the summary of the product, but it has also got dissapeared after scrolling the down so user don't have the simultaniouse widget to see and think for which product is not valuable to remove it.

thanks, please have a look on it. thanks.

**Comment by mikejolley** [comment]
Thanks for the suggestion. I'll add this to our backlog for consideration.

**Comment by senadir** [comment]
Suggested by @nikkivias 

## On desktop

The `Place order` button is often below the fold, which requires a user to scroll up to review their order items before finalizing their purchase.

### 💡 Proposed solution
We want to enable a sticky on scroll summary so that the Order summary details are easily accessible ([Prototype](https://www.figma.com/proto/2JyXNimI4oGeJZhgQNZE9V/Checkout-Blocks-Optimization-(Shopper-UX)?page-id=1501%3A37611&type=design&node-id=2094-47535&viewport=-333%2C5473%2C0.5&t=sKO2tRpMnDLM0Xxd-1&scaling=min-zoom&starting-point-node-id=2107%3A53471&mode=design))

![CleanShot 2024-03-04 at 16 01 05](https://github.com/woocommerce/woocommerce/assets/99638528/0b378d71-474e-4b81-8810-578edbdafd11)

**Comment by webdesksoft** [comment]
I agree with Nikki proposal.
What I want to add extra.
Add #sticky or floating buy now button+ quantity and product name on Single
product page.
Why is it required?
People/ audience scrolling down while reading the product description and
after a span of section. The buy now button goes to hide. So user will
again go to the up through scrolling. Which takes time. So add same feature
in single page too, but in floating or sticky way.
