### ISSUE TITLE
Product summary block doesn't reflect formatting added in the product short description 

### ISSUE THREAD

**Issue by tomxygen** [woothemes/woocommerce#42329]
in the product editor, if you format the text in the short product desctiption, the changes are not reflected on the frontend.
For example, if I make a word bold or I change the text color, those changes are not reflected in the product page. 

## To reproduce

1. enable the blockified product template
2. create a new product
3. add formatting to the short product description, like bold text or color text.
4. Changes are not reflected in the product page

## Expected behavior
Just like the old product page, text formatting should be applied in the product page.

**Comment by Babylon1999** [comment]
zd-6526835

**Comment by Babylon1999** [comment]
Hello,

Just wanted to note this extends to shortcodes as well. 

To replicate, you can try embedding an audio file using [[audio]](https://wordpress.org/documentation/article/audio-shortcode/). On non-block based these, the shortcode works fine.

With twenty-twenty three:

<img src="https://d.pr/i/IECBUr+" alt="">
Link to image: https://d.pr/i/IECBUr



I managed to get the shortcode working by creating a new product template and placing it in a separate block. However, this may not be an ideal solution for merchants that heavily rely on shortcodes to display product information, etc.





<img src="https://d.pr/i/ikywJ8+" alt="">
Link to image: https://d.pr/i/ikywJ8

**Comment by ccwalburn** [comment]
Another report here: 6580961-zd-a8c

**Comment by mimiseku93002** [comment]
Hello,

Any idea when this bug will be fixed?
Thx

**Comment by filipanoscampos** [comment]
Reported here: 7145475-zd-a8c

**Comment by sverleis** [comment]
Another report via 7168412-zen

**Comment by wyter** [comment]
7321934-zen

**Comment by dolgelukkig** [comment]
Another report here: 7464622

**Comment by solstudioim** [comment]
Affected: 7610827-zd-a8c

To replicate:
- Activate block theme
- Add an audio file into the product short description: ![Z4524V.png](https://github.com/woocommerce/woocommerce/assets/17371139/468172ad-1e5c-495f-912b-8c2e2bac0ded)
- It's missing on the front end: ![8ZJfqy.png](https://github.com/woocommerce/woocommerce/assets/17371139/813faf7d-7324-48ae-a61f-f4599c9ead45)
- Switched the theme to Classic Storefront, it worked: ![zPpwsY.png](https://github.com/woocommerce/woocommerce/assets/17371139/617ab577-ca01-468c-ba1a-a5862fa8121f)

**Comment by BrettsNatural** [comment]
I don't know if this is even the same problem that I'm having.  The latest update to Woocommerce caused my audio files to disappear.  
![image](https://github.com/woocommerce/woocommerce/assets/158171176/0ff93347-e2ea-4465-8dbe-dc55e43c32cc)
The MP3 is supposed to be in the blank white space.  It shows on the back end but not on the front.  So now I've gone back to the previous version of Woocommerce and cannot update until this problem is fixed!  That audio file is crucial for the sales of my pillows!

**Comment by filipanoscampos** [comment]
Another case, here: 7917680-zd-a8c

**Comment by ResponsiveFlow** [comment]
Although there are many other reports, no action has been taken.
cc @nerrad

**Comment by nerrad** [comment]
This looks like a duplicate of #44245 and is also covered by some discussion happening in #44260. The root of the issue is that the Product Summary block is a variation of the WP Post Excerpt block which has its [own issue here](https://github.com/WordPress/gutenberg/issues/55562). 

I'm going to close this as a duplicate but this is something as recently as 2 weeks ago had some action on and from the [last comment here](https://github.com/woocommerce/woocommerce/issues/44245#issuecomment-1964379956) it looks like @kmanijak is hoping to take another look at it.
