### ISSUE TITLE
Product Gallery: Allow usage within the Single Product block

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#42325]
Currently, it is not possible to add the Product Gallery block to the Single Product block:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/bda4fb81-2520-40d1-af09-ff3dff1982a5

This is a blocker for the conversion of the **Product Listing with Gallery and Description pattern** to rely on a Single Product block instead of native WordPress blocks (see https://github.com/woocommerce/woocommerce/issues/42330).

## Expected Outcome

Ensure the Product Gallery block can be used within the Single Product block.

**Comment by nefeline** [comment]
@thealexandrelara do you have anything on deck for enabling the Gallery block within the Single Product block as part of the project you and @danieldudzic are working on over here: https://github.com/woocommerce/woocommerce-blocks/issues/9907 ? 

How long do you estimate that the project will take to be 100% complete? I'm asking because we need this block to be a bit more flexible and customizable for powering patterns such as the one mentioned in this issue and potentially upcoming patterns coming from the Woo Express project, so it would be great to have a better idea of what can and cannot be done in the short term. Thanks in advance! 🙏

**Comment by nefeline** [comment]
@thealexandrelara @danieldudzic, additional question: have you already decided if a new Gallery block will be created or the existing one will be revamped instead? Thanks!

**Comment by thealexandrelara** [comment]
> @thealexandrelara do you have anything on deck for enabling the Gallery block within the Single Product block as part of the project you and @danieldudzic are working on over here: https://github.com/woocommerce/woocommerce-blocks/issues/9907 ?

Hey @nefeline, thank you for bringing this and creating the issue. Well, this was something that I'm waiting for a feedback from UX (ref: pdnLyh-3J5-p2#comment-2513), but I think this would be a great addition and now even more since you shared a use case that you would attend your needs as well.

> How long do you estimate that the project will take to be 100% complete?

Currently, we just started building the base blocks that will compose the Product Gallery block. The initial estimation would be to finish it in August; however, it depends on how we can continue advance without facing any limitations that we may encounter while implementing the block. I think we need a few weeks exploring and working on it to get to provide a more accurate estimation.

> Have you already decided if a new Gallery block will be created or the existing one will be revamped instead?

Yes, we have decided to create a new block instead of updating the existing one, and hopefully, this decision will help us progress more quickly
