### ISSUE TITLE
Checkout block: Post editor > show the enabled express payments instead of the current placeholder for the Express Checkout section

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42353]
This is a sub ticket for woocommerce/woocommerce#42384

If there are express payments defined then those should be visible in the post editor, as they appear in the front-end for the shopper. 

Currently, we show a placeholder that shows Apple pay, independent of what express payments are available.
<img width="933" alt="Screenshot 2023-04-28 at 12 09 08" src="https://user-images.githubusercontent.com/1628454/235120000-3fe8f402-7df6-40a2-bdb7-62a877da2e3d.png">

Things to keep in mind: 

- The buttons should come from the `edit` property of the registered express payment option. This is the first time we are accessing this property, so if there are any limitations please mention them in this ticket as a comment.
- The shopper sees the express payments if they are registered and the website is using https. Some options like Apple Pay and Google Pay need to be correctly set up in the browser in order to appear. This means that they would not appear for the merchant if they don't have this setup.
- The buttons that appear in this section should be disabled. Clicking on them should not be possible. 
- if no Express Payments are set up we hide the Express Checkout section inner block (current behaviour). We won't show any placeholder for an empty state

Things not covered by this ticket:
- listing the express payments methods in the sidebar of the post editor
- refactoring the way the express payment buttons are rendered

**Comment by opr** [comment]
When registering, payment gateways get to provide an `edit` component to us which will render in the post editor.

In the case of Stripe, it looks like [they always opt to render the Apple Pay preview button](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8ffd22aff3b06eda02a1ae2fd8368b71450b36a9/client/blocks/payment-request/index.js#L18)

I'm wondering if this issue is something that needs a fix on our side or if we should defer to the payment gateway to show the correct icons.

By the way, one approach that _may_ be considered is replacing the `edit` component with the `content` component in the post editor, however I would not recommend that as the `edit` component may contain controls for settings etc. which would need to be displayed in the editor.

**Comment by ralucaStan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Rubik-Engineering-5a84601e79f97c2acc45cc58/issues/woocommerce/woocommerce-blocks/9668?planning-poker) with Zenhub @opr

**Comment by ralucaStan** [comment]
We should be the ones controlling that area in the Editor because:
- there can be other Express methods from other gateways, so Stripe will remove those
- in future iterations we will need to control the look and feel of this area across the checkout process (how many buttons are shown and how)

It would be interesting to see if we can overwrite what Stripe is doing

**Comment by opr** [comment]
> there can be other Express methods from other gateways, so Stripe will remove those

This is not true. The same logic to display express buttons on the front-end is used also in the editor, the only difference is [whether the gateway's `content` or `edit` component is rendered](https://github.com/woocommerce/woocommerce-blocks/blob/cffafeb6687dc4afee128bc402810fd1c4d414f5/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.js#L142-L143). If multiple gateways register an express payment method, each one will be rendered in turn in the editor.

> in future iterations we will need to control the look and feel of this area across the checkout process (how many buttons are shown and how)

👌🏼 exactly, super useful information for this issue thanks Raluca!

**Comment by alexflorisca** [comment]
Howdy! Just started working on this and had a few thoughts

I think if we render the `edit` component, we loose control of what's being displayed - this falls with the third party plugins.

If we override it, it gets tricky. We would need to map an image preview of each payment method to some data from the payment method (which we do not control). To add to the complexity, stripe for example only registers one express payment method which acts as Google / Apple / Link pay, depending on the browser you're in. So you never get the choice of all 3. 

I think the solution would be to remove the need for an `edit` component, and use the `content` component for both, that way we are making it easier for the plugin author and more consistent for us. 

I do get your concern here @opr 

> I would not recommend that as the edit component may contain controls for settings etc. which would need to be displayed in the editor.

Can you think of any plugins that do this? Is it documented that we support this? Could we move this logic to the `content` component and ask them to use the `isEditor` flag for any editor functionality?

I can't think of another way to ensure consistency between front end and editor in terms of what's displayed otherwise unless you can?

**Comment by alexflorisca** [comment]
I've been thinking about this a bit more.

The other challenge @ralucaStan mentioned is that if the merchant isn't logged in to Google or Apple, they might not see those methods. Or anything for that matter. But rather than hiding the block or displaying a placeholder, I think it would be ideal to display all of the express methods available. So in stripe's case, we'd want to display a preview for Apple, Google and Link.

We'd need a way to know which gateways each registered express payment method supports though, so we'd need to rely on plugin authors to tell us, maybe via a new property on the payment object they register.

I don't think it's possible to get parity with front end here, as the whole point is the customer will see a tailored express payment method based on their environment. So best case would be to show merchants what all of these would look like in the editor. 

Thoughts?

**Comment by ralucaStan** [comment]
@alexflorisca you make a good point. We know we can detect what express payments are registered for the checkout blocks, but can we detect which ones are activated? I am not sure if in blocks these two actions are separated. 

This ticket is an intermediary step toward a polished express checkout block. We will iterate on this area in the future. Our current goal is to show in the editor what the user sees in the front end. Even if it's not an ideal solution, it's better than the status quo. 

Looking at the editor, this one is for the merchant. I agree it makes sense to show there what express options are activated (not all registered). To confirm for the merchant his setup is working. I would ignore the conditions needed to display something just for the editor. For example, if the merchant does not have Apple pay in the browser, but has it activated for its shopper, they should see it in the editor. 

these are my thoughts. Curious what @pmcpinto has to say

**Comment by alexflorisca** [comment]
> I would ignore the conditions needed to display something just for the editor. 

> For example, if the merchant does not have Apple pay in the browser, but has it activated for its shopper, they should see it in the editor.

These two seem to be in conflict with each other. If the merchant is looking at the editor in say Chrome, and they have Google pay set up, they will see Google Pay. Where as the shopper may be viewing the store in Safari or iOS and see Apple Pay. The shopper and the merchant experiences will be different here. But I understand your point about the merchant testing the setup works ok. So they would need to view the checkout in the editor in all respective browsers to confirm all the express payment methods work ok.

> We know we can detect what express payments are registered for the checkout blocks, but can we detect which ones are activated? I am not sure if in blocks these two actions are separated.

We can do both. The active payment methods live in the payment data store, the registered payment methods live in the payment registry. The challenge here is as I said above. Only 1 express payment method is registered, and the same one is activated for Google / Apple / Link pay. The code that works out which one to display is part of the stripe plugin and we haven't got access to that. So we don't actually know which one of those is being rendered at any one time.

**Comment by alexflorisca** [comment]
@ralucaStan @pmcpinto 

> if no Express Payments are set up we hide the Express Checkout section inner block (current behaviour). We won't show any placeholder for an empty state

Are we sure about this? There could be a situation where the merchant isn't logged into any Google / Apple / Link pay and so will not see the express payments section at all. Where as a user might be, and they will see it. If the goal is for the editor to be as close as possible to the front-end, I would add a placeholder here, to make it clear to the merchant that this section _might_ be available to shoppers.

**Comment by pmcpinto** [comment]
> if no Express Payments are set up we hide the Express Checkout section inner block (current behaviour).

I think we display the Express Checkout inner block independently if the user has Express options enabled. But this should be fixed.

At a fundamental level, we want to ensure merchants using Express options understand where they're located at the checkout. If it's too complicated to accurately represent what the shopper will see on the front end, we should present one or all of the available Express options. We can use the block description or something similar to add more context/guidance.

**Comment by alexflorisca** [comment]
> I think we display the Express Checkout inner block independently if the user has Express options enabled. But this should be fixed.

Are you talking about the editor or the front end? We hide the Express Checkout inner block on the front end if a shopper doesn't meet the conditions for any express payment methods. But we do show the inner block (empty) on the editor. I think this is right, but it looks a bit bare.

![Screenshot 2023-07-19 at 14 51 00](https://github.com/woocommerce/woocommerce-blocks/assets/3966773/3268bfcc-6057-440e-b06e-425de97a0634)

I just had a play to see if we can detect when there are no buttons rendered but this is difficult as the code to do this lies with the third party plugins. It is technically possible, but its very messy, both in terms of UX and performance. If we decide to put a placeholder there, the placeholder will be rendered first, then because the buttons take a while to load, it may be replaced by an express button after a few seconds. 

I'd suggest leaving it empty for the merchant and maybe explain in the sidebar something about needing to configure Google / Apple pay to test.

**Comment by pierorocca** [comment]
> These two seem to be in conflict with each other. If the merchant is looking at the editor in say Chrome, and they have Google pay set up, they will see Google Pay. Where as the shopper may be viewing the store in Safari or iOS and see Apple Pay. The shopper and the merchant experiences will be different here.

I'm in agreement with @pmcpinto on this and Shaun's guidance in his Express Checkout Block P2 post. The merchant experience needs to be abstracted from the browser and platform they're using for editing. That means what they see in the editor is a representation of ALL the possible options a shopper may experience based on a shopper's browser and platform combination.

**Comment by opr** [comment]
The thing about express payment methods is we do not control what express payment methods choose to show in their `edit` component or their `content` component. In the case of Stripe, as far as WooCommerce Blocks is concerned, it is completely unaware that Stripe may render up to three different buttons. All WC Blocks sees is "Stripe", not GPay, Apple Pay, or Link.

Besides _encouraging_ express payment methods to render all of their options in the editor through documentation and dev notes, I'm not sure how we could force them to show all of the options. As long as these payment methods can render arbitrary content (which they can) we have no jurisdiction over them.

We probably do need to continue to allow this arbitrary content too since the likes of Link use iframes to show their button.

<img width="363" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5656702/5641b283-d752-4589-bfe5-f2e5610d22f1">

The use case is that they need to do some server-side processing on _their_ systems to render the correct content inside the button.

**Comment by pmcpinto** [comment]
> Are you talking about the editor or the front end? We hide the Express Checkout inner block on the front end if a shopper doesn't meet the conditions for any express payment methods. But we do show the inner block (empty) on the editor. I think this is right, but it looks a bit bare.

I was talking about the editor. I have WCPay enabled in my test store with the express checkout options disabled (they were enabled before) and I'm getting this:

<img width="844" alt="Captura de ecrã 2023-07-20, às 15 18 42" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/7496942f-e6ea-4f82-a960-2bbcdb28926f">

Maybe it's a bug?!

> I just had a play to see if we can detect when there are no buttons rendered but this is difficult as the code to do this lies with the third party plugins. It is technically possible, but its very messy, both in terms of UX and performance. If we decide to put a placeholder there, the placeholder will be rendered first, then because the buttons take a while to load, it may be replaced by an express button after a few seconds.

> I'd suggest leaving it empty for the merchant and maybe explain in the sidebar something about needing to configure Google / Apple pay to test.

> In the case of Stripe, as far as WooCommerce Blocks is concerned, it is completely unaware that Stripe may render up to three different buttons. All WC Blocks sees is "Stripe", not GPay, Apple Pay, or Link.

> Besides encouraging express payment methods to render all of their options in the editor through documentation and dev notes, I'm not sure how we could force them to show all of the options. As long as these payment methods can render arbitrary content (which they can) we have no jurisdiction over them.

Alex and Thomas, thanks for checking this and the additional context. So it looks like we have no way to display in the editor all the express checkout options activated. In that case, I recommend having a placeholder with the most common options (Apple Pay and Google Pay) if the store has express checkout options enabled, which is essentially what we have now. Maybe we can tailor the placeholder if the user has WCPay or Stripe. Let me know what you think.

**Comment by opr** [comment]
>  I recommend having a placeholder with the most common options (Apple Pay and Google Pay) if the store has express checkout options enabled

We can do this for sure, should we add a disclaimer/notice to the editor sidebar when selecting this block explaining it's just a preview and shoppers may see different buttons depending on their browser, location, etc.?

> Maybe we can tailor the placeholder if the user has WCPay or Stripe. Let me know what you think.

If we don't go ahead with the above, since these are Woo owned, why don't we have WCPay and Stripe update their `edit` component to return all the buttons they can show?

**Comment by alexflorisca** [comment]
Thanks for your comments

> Maybe it's a bug?!

The reason you're only seeing an Apple Pay button in the editor is because that's what the stripe plugin provides as a preview, no matter what platform or browser you're on. It's just what they decided for some reason. 

>  I recommend having a placeholder with the most common options (Apple Pay and Google Pay) if the store has express checkout options enabled, which is essentially what we have now. Maybe we can tailor the placeholder if the user has WCPay or Stripe. Let me know what you think.

> If we don't go ahead with the above, since these are Woo owned, why don't we have WCPay and Stripe update their edit component to return all the buttons they can show?

I think we need and either or approach here. Either we show a placeholder for ALL payment plugins that define express payment methods (not just stripe and WCPay) or we display whatever the payment methods decide to render as a preview. 

One concern with us owning the preview and displaying say, the 3 or 4 most popular ones, is that they may be the most popular in the US or UK, or even Europe, but not in other countries. Someone in Japan could have a payment plugin that renders 3 completely different express payment methods, and then they might be scratching their heads as to why they are seeing Google Pay or Apple Pay in the preview. Maybe a small disclaimer would help here, but I thought I'd point this out.

**Comment by pmcpinto** [comment]
> The reason you're only seeing an Apple Pay button in the editor is because that's what the stripe plugin provides as a preview, no matter what platform or browser you're on. It's just what they decided for some reason.

Gotcha. Thanks for the clarification.

> I think we need and either or approach here. Either we show a placeholder for ALL payment plugins that define express payment methods (not just stripe and WCPay) or we display whatever the payment methods decide to render as a preview.

Good point, as it's common to have WCPay/Stripe + other providers (PayPal, BNPL solutions, etc).

> One concern with us owning the preview and displaying say, the 3 or 4 most popular ones, is that they may be the most popular in the US or UK, or even Europe, but not in other countries. Someone in Japan could have a payment plugin that renders 3 completely different express payment methods, and then they might be scratching their heads as to why they are seeing Google Pay or Apple Pay in the preview. Maybe a small disclaimer would help here, but I thought I'd point this out.

Yeah. I think it's important to inform users that this is a placeholder and it will be tailored depending on the extensions/settings they have configured.

Just to confirm: I assume that the way this area is extended by the 3PDs will make it difficult to allow any merchant customization directly in the editor, right? I'm mainly thinking about styling, positioning, ordering, and defining the number of options.

**Comment by alexflorisca** [comment]
> Just to confirm: I assume that the way this area is extended by the 3PDs will make it difficult to allow any merchant customization directly in the editor, right? I'm mainly thinking about styling, positioning, ordering, and defining the number of options.

Yeah we do not have control over those things. They can render a react component which can be anything! We only have control over the container in which it renders, which we can't do a lot with. We can provide a style guide in some documentation, but it will be difficult if not impossible to control those things with code. The only 1 that could MAYBE work is the number of buttons. But given every plugin will likely register a different amount of express buttons, I don't see a huge benefit in specifying this.

So given all this, what option are you leaning more towards?

**Comment by pierorocca** [comment]
One idea tossed out during the PayPal blocks implementation was providing each gateway their own block for express checkout buttons. PayPal specifically is problematic because their button can be dynamic and the orientation and number of buttons is unpredictable. And their styling and button sizes clash with almost everything out there. It'd be so much better for interoperability if each gateway was contained to their own block each with their own editable configuration.

The tradeoff is if a merchant wants a look that more tightly integrated then they can shop for an all-in-one gateway, limit the number of choices, or live with the tradeoff.

**Comment by pmcpinto** [comment]
> Yeah we do not have control over those things. They can render a react component which can be anything! We only have control over the container in which it renders, which we can't do a lot with. We can provide a style guide in some documentation, but it will be difficult if not impossible to control those things with code. The only 1 that could MAYBE work is the number of buttons. But given every plugin will likely register a different amount of express buttons, I don't see a huge benefit in specifying this.

Thanks for the additional context. In this thread it was discussed the idea of adding a new API that would allow us to have more control over the experience: pdnLyh-3L2-p2#comment-2547
But based on what's been discussed in this thread it looks like supporting the two options could easily turn into a messy situation. What do you think? 

> So given all this, what option are you leaning more towards?

It looks like anything beyond providing a placeholder with the most common options will have a higher cost in terms of implementation and maintenance, right?

**Comment by alexflorisca** [comment]
> But based on what's been discussed in this thread it looks like supporting the two options could easily turn into a messy situation.

I like the idea of a new API with a primary colour and a logo too, but like @ralucaStan said, it's a big change and it will need a bit of experimenting with to see how we'd deal with logos of different sizes, etc. It's also a breaking change, meaning we'd have to ask all developers to change their plugins.

Speaking of backwards compatibility, I think we're aiming for too much here. We can't really let the render what they want (current approach) AND control the look and feel. The ideal situation, from my point of view, is we change the API to something that gives us more control (for example the primary colour and a logo as mentioned), and we deprecate the old one. We cannot maintain the old API indefinitely, otherwise that defies the point. Plugins will still be able to insert custom buttons and render whatever they want unless we take that away from them at some point.

Anything we deprecate requires time for the plugin developers to change their code to the new approach. In the long run, it's the preferred thing to do. If we're to go down this route, we want to avoid making future breaking changes, at least for a while. So we'd need to properly think through the entire express checkout section, make some decisions and then implement the API to achieves them, giving developers plenty of time to change their code ( at least 6 months I think)

Now I know we have a deadline in November where we go default, but that shouldn't stop us from building towards the optimum solution. 

If we want to hit the deadline, we have 2 options really:

1) we create placeholder buttons and show them for EVERY payment plugin that registers express payment methods, no matter what those methods are. Ignore whatever the plugins provide for the editor buttons

2) We keep the current approach and let them render whatever they want

Since we're building this for the long term, I'd suggest going for option 2), while deprecating the existing approach and building the new API for providing colour and a logo. There's a good chance that some of the major plugins that have active development can adopt to this new approach by November, and we can keep working towards an ideal solution from there.

That's my 2 cents but the decision is yours @ralucaStan @pmcpinto

**Comment by pmcpinto** [comment]
> The ideal situation, from my point of view, is we change the API to something that gives us more control (for example the primary colour and a logo as mentioned), and we deprecate the old one. We cannot maintain the old API indefinitely, otherwise that defies the point. Plugins will still be able to insert custom buttons and render whatever they want unless we take that away from them at some point.

I fully agree that creating a new API to have more control e promote a cohesive experience is the ideal solution, and the design team is already doing some explorations in this space. Supporting two APIs doesn't seem sustainable in the long-term, but we still need to confirm with 3PDs if a new API would be enough to address their needs.

> Now I know we have a deadline in November where we go default, but that shouldn't stop us from building towards the optimum solution.

It would be great to have a decision and solution regarding a new API for the Express area by November but I don't see it as a hard deadline.

Re: placeholder in the block editor. How long it will take to implement option 1?

**Comment by ralucaStan** [comment]
> PayPal specifically is problematic because their button can be dynamic and the orientation and number of buttons is unpredictable. And their styling and button sizes clash with almost everything out there. It'd be so much better for interoperability if each gateway was contained to their own block each with their own editable configuration.

Sharing this image for people to understand the PayPal case
![image-15](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/7917ca63-379b-4a80-869a-56b76dde991d)
Image from https://woocommerce.com/document/woocommerce-paypal-payments/#woocommerce-blocks

**Comment by ralucaStan** [comment]
The way the situation presents itself I understand that:
1. if we want to show in the editor all the express possibilities, we need to tell extensions to do that, create the API and display the options. We'd also need to have a decision on presenting the express payments; and we are not there yet. 
But we can think about this editor aspect when tailoring the final experience.

> we create placeholder buttons and show them for EVERY payment plugin that registers express payment methods, no matter what those methods are. Ignore whatever the plugins provide for the editor buttons

a couple of questions: @pmcpinto 
- how do you see these buttons? Without visual support, everybody might understand something different
- do we control these buttons? because on the shopper side, the buttons are controlled by the extension
-  Buttons look and feel will change in the future (if we impose standards). If we add branded/hardcoded buttons we are risking visual inconsistencies. 

I do like the idea of a placeholder, but maybe we should not rely on buttons, but on another visual representation. 
maybe this is a good opportunity to document the Express checkout option and link to a public documentation page on the plugin outlining: what EC (Express Checkout) is, list benefits & what plugins offer EC options, how to set up etc

This was the proposal for the state where nothing was configured. more context on pdnLyh-3L2-p2

<img width="562" alt="Screenshot 2023-08-04 at 16 57 05" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/782ed7db-8294-4031-97b6-e0a6da44ab7a">

What we could do: 
0. Plugins don't have EC
Link to the documentation page mentioned above with info on the experience
2. Plugins have EC but merchant did not enable it
Highlight to the merchat that the plugin X offers EC; link to plugin setup page; + link to documentation to learn more;
4. Plugins have EC and merchant enabled it
List the Plugins that enable EC for the merchant; links to plugin setup page (if possible)


One benefit of this approach is that we can keep the editor vs the shopper experience separated until we gain clarity on the expected result for this area.

**Comment by ralucaStan** [comment]
@pierorocca curious what you think about the proposal above

**Comment by pierorocca** [comment]
@ralucaStan is the PayPal block of buttons still an iFrame in the new Blocks implementation?

**Comment by pierorocca** [comment]
The objectives as I understand and am summarizing are:

1. Allow a merchant to view and configure Shopper checkout experiences despite not using the same platform/browser and/or not having GPay or Apple Pay setup on their client
2. Renders the buttons in a usable and an attractive way even if there are many buttons or multiple gateways enabled
3. Provide merchants with information/visual feedback that a particular EC may not be setup properly e.g. Apple domain registration not complete
4. Accurately represent EC button sizes, logos, colors, shape, etc.
5. The solution must work with any gateway and we don't know ahead of time what EC's they support

Things we know:

- Chrome and Google Pay is available across desktop and mobile platforms.
- Google Pay is also available on iOS Safari, Edge, Opera, and Firefox (Stripe does not support)
- Apple Pay is the only EC that is not cross-platform, but is cross-browser on iOS (Mac OS?)
- Safari is not cross-platform
- Some implementations may not render one or more EC buttons despite being supported on that browser/platform. e.g. Stripe's payment elements does not render Google Pay on iOS Chrome

> 1. Plugins don't have ECs
> Link to the documentation page mentioned above with info on the experience

In this scenario, I don't think anything needs to be shown or linked to. Seems like an N/A scenario. Keep it minimalistic.

> 2. Plugins have EC but merchant did not enable it
> Highlight to the merchant that the plugin X offers EC; link to plugin setup page; + link to documentation to learn more;

In principle a merchant should see what's possible and what's enabled/disabled on the editor. If the EC is not enabled, ideally we show that EC in a disabled state AND allow the merchant to enable it from the front end. I'd encourage a push to have the plugin support FSE rather than aim for backward compatibility (through merchant manual intervention) and making the merchant UX overly complex and inconsistent. If there's no way around this then your approach to deep link the merchant to a settings page makes sense...even better if visually the EC can be shown in the FSE even if it can't be edited.

> 3. Plugins have EC and merchant enabled it
> List the Plugins that enable EC for the merchant; links to plugin setup page (if possible)

Same comment as above in 2.

For the multiple gateway/plugin scenarios, here's another idea. By default separate out each gateway into separate blocks each with their own settings until such time there's a move to a more opinionated and structured model. Allow the blocks to be grouped as an option so that visually they combine into one express checkout block. The grouped block has a limited set of editing options while each block within the group retains its own settings. Until checkout is a lot more opinionated than it is today, keeping plugins separated and contained may be the only way to manage all of the possibilities.

**Comment by ralucaStan** [comment]
> @ralucaStan is the PayPal block of buttons still an iFrame in the new Blocks implementation?

apologies @pierorocca I missed this comment.

Yes, in the express payments area they render an iframe. So does Stripe with link
<img width="658" alt="Screenshot 2023-08-10 at 11 54 00" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/147f7cc9-88c9-417d-a18d-550204811c88">

cc @opr

**Comment by pierorocca** [comment]
No worries and thanks @ralucaStan. What impact if any does that have on managing the express checkout block and the editing experience?

**Comment by opr** [comment]
> What impact if any does that have on managing the express checkout block and the editing experience?

The payment plugin is responsible for choosing what to show in that section in the editor, so we can't actually force or change what gets shown there. For example Stripe only shows the Apple pay button in the editor context, there's no reason it can't show more buttons.

The impact of this is that the merchant may not see what their customers would see in practice on the front end.

**Comment by ralucaStan** [comment]
One update on the state of the Express Payment buttons in the Post Editor for the Cart and Checkout blocks; I have Stripe and PayPal installed; This is displayed on my Chrome browser; both buttons are coming from an inframe as I've mentioned in a previous comment.

## Cart block
<img width="857" alt="Screenshot 2023-08-11 at 16 58 03" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/8e8d9335-0818-4958-a378-14b09193998f">

## Checkout block

<img width="1416" alt="Screenshot 2023-08-11 at 17 17 16" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/1b6a5828-4df1-48c8-82b3-beb45810ff23">

**Comment by ralucaStan** [comment]
Moving this issue to the backlong until @pmcpinto can come back with an answer

**Comment by pierorocca** [comment]
For the Stripe buttons, is there any benefit to using our own buttons as described [here](https://stripe.com/docs/stripe-js/elements/payment-request-button?client=html#html-js-own-button)? There appears to be a limitation with Link as well.

I'll be setting up time to speak with Stripe about their express checkout element. They're not investing in the PRB implementation and the payment request API W3C standard it's based on has limitations. 

@elizaan36 @bummytime it may be time to start looking at [Stripe's Express Checkout element](https://stripe.com/docs/elements/express-checkout-element/accept-a-payment#connect) to see what benefits it provides, can WooPay and Link co-exist in the mutually exclusive way we're currently setup, and how does it figure into the design effort for button display and FSE config.

**Comment by ralucaStan** [comment]
@pierorocca might be worth taking a look at this pdFofs-1if-p2 about PayPal Stripe combinations

**Comment by pierorocca** [comment]
@ralucaStan is the Stripe gateway using the [PRB](https://stripe.com/docs/stripe-js/elements/payment-request-button) or the [Express Checkout Element](https://stripe.com/docs/elements/express-checkout-element) in its implementation?

**Comment by ralucaStan** [comment]
From what I saw they do use PRB. 

https://github.com/woocommerce/woocommerce-gateway-stripe/tree/9f3e866912112220beb8dfa6244a74b9b2addf8a/client/blocks

Might be worth reaching out to the plugin maintainers for extra details.

**Comment by pierorocca** [comment]
Thank you! Will do. The PRB is limiting, creating a competitive gap. Will connect with Brent on the Stripe gateway implementation and if there are any known problems/reasons why the Express Checkout Element is problematic. There's a possibility this is a dependency for any discussion around refactoring buttons and button config.
