### ISSUE TITLE
Unexpected padding when changing Product Template background color

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#42442]
### Steps to reproduce
1. Go to Editor
2. Add _Products_ block
3. Focus on _Product Template_
4. Change the Background color

**Expected:** Color changes
**Actual:** Color changes, but there's additional padding added to the element (only in Editor)

### Video

https://user-images.githubusercontent.com/20098064/224046285-f32dcee9-def8-444e-96be-bdcb40a2f1a6.mov

**Comment by nerrad** [comment]
I see this happen with a grid pattern for the Query Loop block too so this looks like something that should be fixed upstream?

**Comment by imanish003** [comment]
I took a quick look, and it seems that the issue is due to CSS leaking from [style.scss](https://github.com/WordPress/gutenberg/blob/8d4bbb513df0637c6ab19af2fbbbb8640553e24c/packages/block-library/src/list/style.scss#L8) of the core/list block. In my opinion, this needs to be fixed in the core/list block. I will create a PR for this in GB.

**Comment by kmanijak** [comment]
We're not going to focus on Products (Beta) and issue not reproducible in Product Collection hence closing.
