### ISSUE TITLE
Sale Badge: Explore a new implementation based on the Cover block

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woocommerce#42478]
We should explore a new implementation of the **On-Sale Badge** block in patterns to obtain similar behavior as current **Product Image** block options. The WP Core **Cover** block has been identified as a good candidate providing a lot of the necessary functionality.

Related discussions:

- pdnLyh-30z-p2
- pdnLyh-37o-p2

**Comment by sunyatasattva** [comment]
Should we put this within the woocommerce/woocommerce#42616 epic?

**Comment by danieldudzic** [comment]
> Should we put this within the woocommerce/woocommerce#42616 epic?

Added!

**Comment by imanish003** [comment]
Hi @sunyatasattva, based on my understanding, in this task, we want to create a new block that will replace the Product Image block. The new block will use the Cover block and the On-sale badge block as inner blocks. Is that correct? 🤔

Additionally, I think we could consider using the `Post Featured Image` instead of the Cover block. What do you think? 🙂

**Comment by paaljoachim** [comment]
The Cover block has a specific focus and so does the Post Featured Image block. Cover is meant to stand alone on a screen perhaps including some text and a button. Post featured image is meant to show images and has better suited controls to do so.

The Post Featured Image block is used inside the Query Loop and it has options that help keep images the same size even though these might be very different.

The Cover block settings.
![Screenshot 2023-04-19 at 14 54 44](https://user-images.githubusercontent.com/5323259/233081683-f04cdedb-53be-4e13-ab95-5b46024851ad.jpg)

Post Featured Image block when inside the Query Loop block.
When inside the Query Loop block it adds a Scale option - Cover - Contain - Fill.
It also has an Aspect Ratio.

![Screenshot 2023-04-19 at 14 56 37](https://user-images.githubusercontent.com/5323259/233082224-a3930bb5-08bb-4887-9135-fa412a7b60ea.jpg)

The 3 above images are different sizes, but because of using Cover option they will all fit out the space they have available. I can change the Aspect Ratio and all the images will stay within the space they have assigned.

This means that images that are tall, slim, wide etc all can be the same size when using the for instance Scale controls.
This I would say is the most important feature of the Post Featured Image block when it is inside the Query Loop block. As one struggle is that product images will be different sizes. Some tall and others wide. But having the opportunity to show an even set of product images helps a lot.

**Comment by sunyatasattva** [comment]
@paaljoachim @imanish003  The problem with the Featured Image block is that it doesn't accept Inner Blocks, as opposed to the Cover block. Our current problem is that we need a separate “Product Image” block to account for the “On Sale” badge being overlayed on top of the image, which seems a waste when other blocks are available with much better options.

The “Cover” block was an idea proposed in this investigation, because it already provides the capability of hosting the “On Sale” badge and positioning it around, but is by no means the final say.

**Comment by paaljoachim** [comment]
So the dilemma present:
Post Featured Image block when used in the Query Loop block has Aspect Ratio, Height/Width and Scale. The exact tools needed inside a Query Loop. Making sure that all the Query Loop images are the same size. BUT it does not have a way to add inner blocks. So one is not able to add a Sales Badge.

The Cover block is not meant to be used inside the Query Loop block, as it does not have a way to scale images. But one can add the Sales Badge. Perhaps the best solution would be to add the Aspect Ratio, Height and Width as well as Scale from Post Featured Image block to the Dimensions panel of the Cover block. Like so.

Cover block Dimensions panel
![Screenshot 2023-05-03 at 10 32 50](https://user-images.githubusercontent.com/5323259/235867965-4eaba8a4-b8f9-43c8-92aa-298b81027ba0.jpg)

Cover block Dimensions panel + Post Featured Image Dimension options.
![Cover block Dimension options + Dimension options from Post Featured Image block](https://user-images.githubusercontent.com/5323259/235868522-3d98c93c-81c7-46aa-93b4-a65c7c212846.jpg)

This way one continues to use the Cover block but it includes the needed scaling options to keep Product images the same size when inside the Product Image Query Loop.

**Comment by paaljoachim** [comment]
Btw additional image controls will gradually be added to multiple blocks see:
https://github.com/WordPress/gutenberg/issues/38990#issuecomment-1541658123

**Comment by kmanijak** [comment]
I'm closing this issue in favor of https://github.com/woocommerce/woocommerce/issues/44387, as we won't be trying to create a new block but rather explore using Cover block directly.

Closed issues can still be commented on.

**Comment by paaljoachim** [comment]
Cover block has just included:
Dimensions: Add Aspect Ratio block support
https://github.com/WordPress/gutenberg/pull/56897

So that will be helpful to keep the Product images the same size.

EDIT: I installed the latest nightly of WP 6.5 and see the new aspect ratio added to the Cover block.

![Screenshot 2024-02-06 at 11 36 38](https://github.com/woocommerce/woocommerce/assets/5323259/b348c4a0-1aa0-4be5-bb70-505b93da9abe)

**Comment by paaljoachim** [comment]
One more thing.
A Sales Badge block is needed.
That contain Image settings and Sales Badge settings in one block. That by default it would be added to the Cover block inside the Product Query Loop. The settings would be set so that only sales products will show the badge.
