### ISSUE TITLE
Improve the account creation during Checkout experience

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#42529]
## Describe the bug

When the customer chooses to create an account during checkout they do not have any prompt about the state of their account after the order is placed. 

## To reproduce

1. Go to WooCommerce > Settings > Accounts & Privacy. 
2. Enable the `Allow customers to place orders without an account` option. 
4. Go to checkout block page editor. 
5. Go to WooCommerce > Settings > Accounts & Privacy. and enable ` Allow customers to create an account during checkout`
7. Visit the store as a logged out user
8. Add a product to the cart
9. Go to checkout block page
10. Notice `Create an account` checkbox is visible. 
11. Select `Create an account` and place an order with a random email. 
12. Notice the order is getting placed and a normal Thank you page is visible with no info about the account
13. Notice that you are logged in at this point.
14. Go to my account section and notice that your email is registered, but no password is visible
15. Check your email and see that you receive an `Your account has been created!` email, see screenshot below

## Expected behavior

When the order is placed the user should see info about the state of their account. 
He should at least see a link to the Account details`/my-account/edit-account/` and a prompt to choose a password.

## Screenshots

Email received by the user after they placed the order

<img width="633" alt="Screenshot 2022-11-14 at 14 35 05" src="https://user-images.githubusercontent.com/1628454/201675575-12529643-6f50-48a4-90ff-8a1d88ac3dc7.png">

**Comment by ahmedobaa** [comment]
I have the same problem why not add an entry for the new password when "create an account" is checked

**Comment by roohaani786** [comment]
this issue needs fixing

**Comment by synerp** [comment]
Hi there,  how do you make it only send the welcome email if the payment has been successful?  If the payment fails, the user will still receive a welcome email even though they have not completed the checkout.  This can make them beleive they have already finished the purchase.
___
For anyone looking on how to get this going, what I did was change the users email address before it was created, then change it back and send the email when payment was complete. Something like this: 


```
// Modify customer data before creation
function modify_customer_data_before_creation($customer_data) {
    $random_email = 'user_' . wp_generate_password(10) . '@somedummydomain.com';
    
    // Modify the email address in the customer data
    $customer_data['user_email'] = $random_email;

    return $customer_data;
}
add_filter('woocommerce_new_customer_data', 'modify_customer_data_before_creation');


// Update user email and send new user email
function update_and_send_new_user_email($customer_id, $order_id) {
    // Get the billing email from the order
    $order = wc_get_order($order_id);
    $billing_email = $order->get_billing_email();

    // Update the user's email address to match billing email
    wp_update_user(array('ID' => $customer_id, 'user_email' => $billing_email));

    // Send the new user email manually
    WC()->mailer()->emails['WC_Email_Customer_New_Account']->trigger($customer_id);
}

// Hook into the WooCommerce order completion action
function send_new_user_email_on_order_completed($order_id) {
    $order = wc_get_order($order_id);

    // Make sure the order is completed
    if ($order && $order->get_status() === 'completed') {
        $customer_id = $order->get_customer_id();
        update_and_send_new_user_email($customer_id, $order_id);
    }
}
add_action('woocommerce_order_status_completed', 'send_new_user_email_on_order_completed');

// Hook into the WooCommerce created customer action
function send_new_user_email_on_customer_created($customer_id) {
    $order_id = get_user_meta($customer_id, '_customer_order_id', true);
    if ($order_id) {
        update_and_send_new_user_email($customer_id, $order_id);
    }
}
add_action('woocommerce_created_customer', 'send_new_user_email_on_customer_created');

```

**Comment by pmcpinto** [comment]
@elizaan36 do you have time to look at this in the upcoming days? We can review this problem in the next call. Thanks

**Comment by elizaan36** [comment]
👋 Sorry for the delay in response but we've been discussing this issue elsewhere. I wanted to note that account creation is part of a wider analysis of usability issues of the checkout flow overall and @nikkivias will be taking over on this.

**Comment by Dominic-Marcelino** [comment]
Is there any update on this? There's also mission options (in the settings + via filter) to:
1. allow the user to set a password at the registration
2. preselect the "Create an account" checkbox

**Comment by ralucaStan** [comment]
The team is iterating on the designs and work will start as soon as we have a good path forward. Thank you all for your feedback and patience and we'll be sure to communicate progress

**Comment by dominique-vias** [comment]
@pmcpinto @ralucaStan 

### Design proposal

Here is the design I came up with for this issue. We would be employing a top banner to communicate the successful account creation. And it will be pulling in colors from the site's global colors.

<img width="1892" alt="Group 1000005584" src="https://github.com/woocommerce/woocommerce/assets/99638528/b9e5b557-042d-48b9-8a9c-3bace17b5d67">

### Other exploration

I also explored this version where I show it a little further down in the page. However, I decided against it because while it looks okay on desktop, it pushes the `Order details` a bit further down the page on mobile. In the final proposal above, the notification is noticeable but it still appears secondary and does not demote other important information on this page.

I also tried to use different text in this version, but ultimately ended with `We emailed you a link to set your account password`

> You can now view your recent orders, manage your shipping and billing addresses, and edit your password and account details.



![Image](https://github.com/woocommerce/woocommerce/assets/99638528/c7e0c682-be29-46f7-9d40-660ab9ffdbe6)

**Comment by pmcpinto** [comment]
@nikkivias thanks! The proposed solution looks good to me. @ralucaStan can we remove this one from the blocked column?

**Comment by elizaan36** [comment]
Nice ideas, @nikkivias! This message could use the store notice component to align with the site's other notices, no?.

**Comment by dominique-vias** [comment]
Yes exactly @elizaan36 👍🏽

**Comment by opr** [comment]
@nikkivias hi - the design with the banner going across the top looks great! 👏 

I'm wondering if you could clarify though, @elizaan36 mentioned

> This message could use the store notice component to align with the site's other notices, no?

which is what I was wondering too, so does that mean it should actually look like the below?

![Image](https://github.com/woocommerce/woocommerce/assets/5656702/2583342c-f189-4c40-8f99-10a85839837a)

Also, on my store, the header still contains the nav menu on the order confirmation page, would this notice appear above or below that?

Thanks!

**Comment by dominique-vias** [comment]
Hi @opr this is the component I meant

![CleanShot 2024-05-17 at 16 47 14@2x](https://github.com/woocommerce/woocommerce/assets/99638528/b0cde495-9e59-4907-855c-250db31ae388)

**Comment by mikejolley** [comment]
@nikkivias I think its likely some confusion with naming. Store Notice is a component in blocks and you can see the storybook entries here:

https://woocommerce.github.io/woocommerce-blocks/?path=/docs/external-components-storenotice--docs

I'm assuming we'd use `informational` or `success` subtype and render it at the very top of the order confirmation template.

The other banner (with the demo store example) is not something we've used in this project before and given how its uniquely tied to the "demo store" setting you screenshot, won't be reusable without refactoring, and will not support icons like StoreNotice does. I would suggest not using this. If the full width notice banner type is important to the design, and something we'd likely need to have in place for future designs, it could be a new option for the StoreNotice component (if possible).

Could you also respond to @opr's question because I wonder the same:

> Also, on my store, the header still contains the nav menu on the order confirmation page, would this notice appear above or below that?

**Comment by dominique-vias** [comment]
Hi @mikejolley 

> Could you also respond to @opr's question because I wonder the same:
> 
> Also, on my store, the header still contains the nav menu on the order confirmation page, would this notice appear above or below that?

To answer this question, it would be below the header.

Also thank you for explaining about the componentry. Are you recommending we use the blocks store notice instead to deliver the success message?

The visual appearance of the store notice (with icon) component is not preferred because it calls too much attention, however, as far as solving the problem of delivering a message— I would say the full-width banner is not considered crucial, and the existing componentry can do the job... It won't be a permanent component on this page after all.

[Figma](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=773-3533&t=Nub1gFL5aSE1Kbho-1)

<img width="1440" alt="Checkout-Info" src="https://github.com/woocommerce/woocommerce/assets/99638528/834d052f-5c6b-4bc2-9373-8abc70b27727">

**Comment by elizaan36** [comment]
> It won't be a permanent component on this page after all.

@nikkivias @mikejolley Along these lines, We should make this notice dismissible to give merchants control over the display.

**Comment by mikejolley** [comment]
@elizaan36 How important is this given there is no other action required on this page? 

The user can just close the site or navigate away. If we did have to make this dismissible we'd need some way to track if it were dismissed at account level, and some new endpoint for the click event to talk to. That seems a lot of work for a notice that only displays on this page.

The notice itself is never shown again once the user sets a password. WordPress keeps track of this.

**Comment by elizaan36** [comment]
It was my understanding that store notices were dismissible by default. I think that was in the guidelines when they were implemented. If there's a strong reason that the notice shouldn't be dismissible then it's fine though, I will leave it up to you and Nikki.

The notice component is meant to be a temporary UI, so it's a little odd to use this as a persistent element on the screen if it's informative. I'm only aware of one reason to use a non dismissible notice, in the case of critical errors.

**Comment by mikejolley** [comment]
@elizaan36 We could make it dismissible from the page without extra server side code, but it would come back if you refreshed the page or did another checkout without setting account password.

**Comment by elizaan36** [comment]
That sounds like a good plan. It will give the shopper at least some control over the immediate view, and it makes sense that it would return if the password has still not been set.

**Comment by mikejolley** [comment]
@elizaan36 I took a look into this and it seems we cannot do this without more effort. We're rendering this notice on the confirmation page using the PHP side notices:

https://github.com/woocommerce/woocommerce/blob/6e36d92a59b5953d4c2c981e82d3c61c59aa746e/plugins/woocommerce/includes/wc-notice-functions.php#L194

These notices only display. They do not show or allow dismissing.

I thought we could use the React component, however the order confirmation page is not rendered dynamically with React like the rest of the Checkout is, so in order to allow dismissing I need to either:

- Add react components somehow to the confirmation page for this one notice
- Build a dismiss notice feature into the PHP side notices

Given @nikkivias said "It won't be a permanent component on this page after all." I don't feel it worth the extra time investment to add dismiss functionality so I'll proceed with the non dismissible version from Figma.
