### ISSUE TITLE
Surface custom fields in My Account Order page.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42779]
Custom fields should be visible in the order screen in My Account page.

It's unclear where additional fields (ones that don't belong to Billing or Shipping) and we might need design input.

<img width="718" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/f31dfd63-bd1e-4b73-9136-85145157d17b">

**Comment by elizaan36** [comment]
Any custom fields added as part of the Contact information section could be added to the account details tab in order to be edited there.

![Surface custom fields in my account order page](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/2a9ef47d-9208-4f83-8853-a136aca8a394)

For Shipping and billing address custom fields, these can follow the same pattern as on the [shopper view for the order confirmation](https://github.com/woocommerce/woocommerce/issues/42776).

**Comment by mikejolley** [comment]
Its not clear from the issue description or design feedback if the fields added here are editable. Also, this data is collected at order level so I'm not sure it makes sense to show in account details because its many to one (multiple orders could have different values).

**Comment by opr** [comment]
> Also, this data is collected at order level so I'm not sure it makes sense to show in account details because its many to one (multiple orders could have different values).

Some fields are account-level (fields in the address) and some are order level (contact, and additional information) so the address ones should be editable.

**Comment by opr** [comment]
As for editing the values after the order has been placed, editing fields on an order isn't possible anyway (is it?)

**Comment by senadir** [comment]
This issue doesn't include editing those values yet, but it can handled in it.
