### ISSUE TITLE
Move Phone, Company, and Address 2 to be part of fields definitions instead of being hard-coded into UI.

### ISSUE THREAD

**Issue by senadir** [woothemes/woocommerce#42773]
Currently, the logic of showing/hiding, and requiring the Phone, Company, and Address 2 fields is saved to the Checkout attributes (and HTML), this causes a problem in which you can't access those values outside of Checkout, think My Account or Store API, this might causes conflicting expectations, as My account is still using the legacy options.

The expected outcome (without diving too deep into implementation detail) is that the value of those fields should be saved and read from outside the Checkout block, so that My Account has access to it and that Store API has access to it as well.

**Comment by senadir** [comment]
This might be too far fetched to achieve right now and might go with merchant fields.

**Comment by ralucaStan** [comment]
@senadir I would appreciate it if you can provide more details in the description.

what is the problem we are fixing? Provide Links and extra details to provide more context
what is is expected result? 
how do we plan to achieve it?

Can this be broken down into 3 tickets, for each field?

**Comment by ralucaStan** [comment]
This is part of the nice to have for additional fields. @pmcpinto did you add this for cycle 3?

**Comment by senadir** [comment]
> Can this be broken down into 3 tickets, for each field?

I don't see a value in that, once you figure out how to do it for a single field, it will be copy-pasted into other fields. Having 2 people doing it at the same time will be problematic.

As for explaining this issue, I will revisit again to better explain it, but overall the goal would be to have the settings applied in the Checkout block (require phone for example) to be applied in say, the my account page.

**Comment by pmcpinto** [comment]
> This is part of the nice to have for additional fields. @pmcpinto did you add this for cycle 3?

I'd move this to cycle 4, considering that we'll have fewer resources in the upcoming weeks. What do you think?

**Comment by senadir** [comment]
I'd say this is not a high priority anytime soon, and we might want to consider it once we add merchant custom fields.

**Comment by ralucaStan** [comment]
I don't know why I marked this as blocked. Maybe I thought it needed a better description. Could you update the description using the WooCommerce issue template @senadir ?

**Comment by senadir** [comment]
Good point, this is very related to the recent proposal I had for phone number, the idea is getting clearer in my mind now, I will update this with expected outcome. There's a chance that duplicates of this exists.

**Comment by reykjalin** [comment]
We need better support for this for Express Checkouts like Apple Pay and Google Pay. Those buttons are often displayed on Product and Cart pages in addition to the Checkout page. I think the experience for merchants that require phone numbers can be quite confusing when they've configured their checkout to require phone numbers, but _sometimes_ when customers pay via Express Checkout -- e.g. in when paying from Product/Cart) -- the phone number is missing.

It's also awkward for us because we have to decide on the merchant's behalf whether phone numbers are required or not. I think we've typically just decided they're not required for Express Checkouts, but I think we'll want to respect a merchants choice here.

In short, the requirement for us is:

* The option to indicate whether the phone number is required or not must be accessible on Product, Cart, and Checkout pages.

There are various ways to achieve that. For our purposes it doesn't matter whether this as an option is always loaded into the front-end -- e.g. on `wcSettings -- or available on the PHP side. It seems to me that the PHP side is slightly more flexible since we can choose how we load it into the front-end ourselves. Having both would be the most complete solution 🙂 

***

One thought I've had is why this isn't part of the WC Core settings in **wp-admin &rarr; WooCommerce &rarr; Settings** somewhere. It feels a bit odd to split settings across different parts of wp-admin, particularly things like this that you'd assume would apply to the whole store. That said I fully understand the assumption that these settings would only apply to the Checkout page but we can safely confirm that's not the case 🙂 .

It might require more effort -- and @ralucaStan mentioned a possible need to deprecate the current option? -- but it seems to me that the most correct approach is some sort of way to configure this in the WC Core settings page?

**Comment by ralucaStan** [comment]
more context p1726189572812779/1725317802.164659-slack-C8X6Q7XQU
