### ISSUE TITLE
Product Collection: trigger `experimental__woocommerce_blocks-cart-add-item` JS action from Add to Cart button

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#42924]
Usually, developers can listen for the `experimental__woocommerce_blocks-cart-add-item` event like so:

```js
wp.hooks.addAction(
  'experimental__woocommerce_blocks-cart-add-item',
  'my-namespace',
  ( args ) => { /* some functionality */ }
)
```

However, on the Product Collection block this isn't firing - [the actions for the button](https://github.com/woocommerce/woocommerce/blob/9e9f0341e28abb9d405b6c761502eb199407f24b/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/button/frontend.tsx#L135) don't seem to include anything about dispatching the event. 

To reproduce:

1. Open the site and go to a page showing the Product Collection block
2. Open your JS console and add:
```js
wp.hooks.addAction(
  'experimental__woocommerce_blocks-cart-add-item',
  'my-namespace',
  ( args ) => { console.log( 'item added to cart' ); }
)
```
3. Add an item to your cart and notice that no message was shown in the console.

**Comment by Aljullu** [comment]
Heads-up that I'm reopening this issue as we reverted https://github.com/woocommerce/woocommerce/pull/42946 in https://github.com/woocommerce/woocommerce/pull/43177.

**Comment by kmanijak** [comment]
Tech note: API is experimental and event payload is not documented. Still, it should be considered a public API and align with the payload provided in other places (All Products, AbstractProductGrid) as extensions rely on it.

**Comment by kmanijak** [comment]
As per @gigitux's comment in discussion (https://github.com/woocommerce/woocommerce/discussions/48814):

> The Product Button used in the Product Collection is powered by the Interacitity API. In the [addToCart function](https://github.com/woocommerce/woocommerce/blob/f64f44908edeb0f922c478ad71ae41886f33f84e/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/button/frontend.tsx/#L135-L148), addItemToCart is invoked that trigger two custom native JS events:

> `wc-blocks_adding_to_cart` -> https://github.com/woocommerce/woocommerce/blob/f64f44908edeb0f922c478ad71ae41886f33f84e/plugins/woocommerce-blocks/assets/js/data/cart/actions.ts/#L281-L282
> `wc-blocks_added_to_cart` -> https://github.com/woocommerce/woocommerce/blob/f64f44908edeb0f922c478ad71ae41886f33f84e/plugins/woocommerce-blocks/assets/js/data/cart/actions.ts/#L292-L293

That means there's an alternative to the action mentioned in this issue.

**Comment by kmanijak** [comment]
Based on the discussion: https://github.com/woocommerce/woocommerce/discussions/48814, we decided the users of Product Collection block should rely on JS events:
- `wc-blocks_adding_to_cart` -> https://github.com/woocommerce/woocommerce/blob/f64f44908edeb0f922c478ad71ae41886f33f84e/plugins/woocommerce-blocks/assets/js/data/cart/actions.ts/#L281-L282
- `wc-blocks_added_to_cart` -> https://github.com/woocommerce/woocommerce/blob/f64f44908edeb0f922c478ad71ae41886f33f84e/plugins/woocommerce-blocks/assets/js/data/cart/actions.ts/#L292-L293

In addition, the complementary events will be created:
- `wc-blocks_viewed_product` instead of `experimental__woocommerce_blocks-product-view-link`
- `wc-blocks_product_list_rendered` instead of `experimental__woocommerce_blocks-product-list-render`

I'm closing this issue as not planned.
