### ISSUE TITLE
[Output] Externalize embeddings service

### ISSUE THREAD

**Issue by joelclimbsthings** [woothemes/woocommerce#42935]
We'll see some benefits in production if we externalize the embeddings as a separate service as per the comment p1702886781345669/1702766361.393019-slack-C05DJ3J7D3Q.

And this one: p1702946828761489/1702766361.393019-slack-C05DJ3J7D3Q

> For the embedding model, it would be beneficial for both your project and GPU resource allocation if you switched to using the existing [BGE embedding model service](https://github.com/Automattic/ai-services/tree/trunk/embeddings/bge).  It ranks higher than gte-large on [the MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard), has the same dimensions and sequence length, and is already up and running in production. Would you mind going this route?

**Comment by joelclimbsthings** [comment]
Just a follow-up, David p1703728766772189/1702766361.393019-slack-C05DJ3J7D3Q the following:
> I'll look at a deploying a GTE-Large service that you can use via REST API to embed documents in batches.

Which would be a dependency on this issue, so we'll want to reach out to him to understand how to integrate with this service.

**Comment by nima-karimi** [comment]
Based on my recent discussion with David (1707854566741089/1707253826-slack-C05DJ3J7D3Q/p1707854566741089), we decided to reduce the priority of this issue. So we'll keep this in the backlog and work on it as an improvement in the next iterations. Since we're only running the report a few times a month, this is no longer a priority.
