### ISSUE TITLE
WORDPRESS ISSUE PLEASE SOLVE

### ISSUE THREAD

**Issue by Dhiraj1190121** [woothemes/woocommerce#43187]
![wp problem.jpg](https://github.com/woocommerce/woocommerce/assets/155291033/51089ecd-b2c7-4040-87a9-87f055bce3e1)

Not able to do the website full screen and uploading the drive link also
 Drive link: https://drive.google.com/file/d/1ELcvM_7ZPZxU9V7WG6lnh5byrltWMD5N/view?usp=drivesdk

**Comment by bunpot** [comment]
What theme do you use?

**Comment by Dhiraj1190121** [comment]
Astra theme

**Comment by Dhiraj1190121** [comment]
Please leave your email id i need your help

**Comment by nielslange** [comment]
Hello @Dhiraj1190121 👋

Thanks for reaching out. Your issue description refers to _"WordPress issue"_ and you mentioned that you're using [the Astra theme](https://wordpress.org/themes/astra/). May I ask why you created the issue here? Are you using WooCommerce as well? As for the current issue, I suggest that you [execute a plugins and theme conflict test](https://woo.com/document/how-to-test-for-conflicts/), to find out what's causing this issue.

**Comment by Dhiraj1190121** [comment]
Yes i am using woo commerce here in yhe astra theme in wordpress

**Comment by nielslange** [comment]
Thanks for clarifying this, @Dhiraj1190121. It's possible that the [Astra theme](https://wordpress.org/themes/astra/) needs to be set up in a certain way. I suggest starting at https://wpastra.com/docs/, to get more familiar with setting up this particular theme.

**Comment by Dhiraj1190121** [comment]
Okay  thank you so much for the information.

**Comment by nielslange** [comment]
You're very welcome, @Dhiraj1190121. I'll mark this issue as resolved now. But if you have more questions or suggestions, please don't hesitate to create a new issue.

**Comment by Dhiraj1190121** [comment]
Okay
