### ISSUE TITLE
DEV: watch commands not working for SCSS files

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#43289]
Currently working on Blocks with SCSS files using either `pnpm --filter=@woocommerce/plugin-woocommerce watch:build` or `pnpm --filter='@woocommerce/block-library' watch:build` does not actually rebuild the styles file. When changing and saving, you do indeed see a compile message via Webpack in the CLI but nothing is actually rebuilt.

The work around is to re-run the above commands for any changes to be reflected.

**Comment by ralucaStan** [comment]
This bug has had an impact on a developer's productivity. Could we prioritize it?

**Comment by rrennick** [comment]
@roykho Were you able to resolve this in your dev environment?

**Comment by kmanijak** [comment]
I can reproduce it - I need to restart the build process for styles to be picked up.

**Comment by roykho** [comment]
This is still an issue for me.

**Comment by ralucaStan** [comment]
@tarunvijwani has also been struggling with this

**Comment by rrennick** [comment]
@roykho As an interim work around to having to restart the watch you can run `pnpm --filter=@woocommerce/plugin-woocommerce build:project:copy-assets` in another terminal tab after you see the webpack build log instead of restarting the watch.

I've tracked down why the files aren't getting copied but haven't sorted out a fix yet.
