### ISSUE TITLE
Changelog automation: the message about automatic change file generation is confusing if you don't need an entry

### ISSUE THREAD

**Issue by jonathansadowski** [woothemes/woocommerce#43431]
When a change file is automatically generated, it's possible to skip a changelog entry by selecting "patch", omitting a message, and adding a comment. This process is confusing. We should either improve the messaging, or replace the current process with two options, one to automatically create a changelog entry, and another that says a changelog entry isn't required (and requiring a comment as to why).

p1704821344554139-slack-C03CPM3UXDJ

**Comment by ObliviousHarmony** [comment]
For the "I don't need a changelog entry" option, use verbiage that clearly indicates when it is and isn't okay to have no entry. Something like "These changes have no impact on the user or extension/theme developer experience." This way people aren't making a decision about the necessity of a changelog themselves but rather are pushed towards one we want them to make.

My main thing is that GitHub's PR templates are awful for this purpose in the first place. We've got a bunch of strange checkboxes (that you fill out when you make the issue so you don't even check anything, you write an X in the brackets lol) and two fields that require at least one to be filled out but you don't really know that until the CI check yells at you. Any steps we can take towards simplifying and streamlining the template are great. The less fields to enter the better!

**Comment by opr** [comment]
In the case of skipping a changelog entry, I think requiring a comment as to _why_ it's being skipped should be mandatory.

1. It prevents folks accidentally skipping it (assuming it would fail if a comment wasn't provided)
2. It would encourage more discussion about whether something deserves a changelog entry or not. If reviewers feel the justification for skipping the changelog isn't good enough they could encourage one to be added. Ultimately this leads to better communication in our changelog.

I would also say that the comment should not be hidden in a collapsible section because then it adds friction for reviewers trying to see why a changelog wasn't added. I think it would be better if the comment were left in the open.
