### ISSUE TITLE
Order fields search filter has a few UI quirks

### ISSUE THREAD

**Issue by jorgeatorres** [woothemes/woocommerce#44129]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There are a few things that could be improved regarding the UI of the new search filters introduced in https://github.com/woocommerce/woocommerce/pull/43356:

- Search fields don't seem to be properly aligned (like the other filters):
   ![image](https://github.com/woocommerce/woocommerce/assets/184724/d4afa5e8-6a8c-4d4c-953b-d7a5bdc69851)
- The new filter is not responsive, which can be seen when reducing the window size:
   ![image](https://github.com/woocommerce/woocommerce/assets/184724/43b6335d-8e5f-4c82-a93f-669d37f6fd94)
- The other dropdowns we have on this screen do a better job at indicating what they are for. Maybe we could reword the options in this new filter, so that "All" instead becomes "All fields" or "Whole order". Open to suggestions here.

**Comment by kingyyyyyy** [comment]
![desktop](https://github.com/woocommerce/woocommerce/assets/54516457/2da69951-dc1a-45fd-a198-18bc9aefbab1)

![mobile-port](https://github.com/woocommerce/woocommerce/assets/54516457/756ef0aa-967a-442b-afd4-0a5a9edf6029)

![mobile-land](https://github.com/woocommerce/woocommerce/assets/54516457/58bab38c-08a0-4278-90ec-d6d35969c293)

How it looks like for us. Desktop, mobile device portrait and mobile landscape. (Chrome)

As you can see, on mobile portrait it is tiny, so we can't really type - only paste.

**Comment by kingyyyyyy** [comment]
We'd like to add, as you can see on mobile view the text box is super small so we don't even see one letter/number when input.

Furthermore, if we were to type or paste in to the search box, for example, "55772" (order number), and click Search orders, it would search as "27755" - completely mirrored for some reason.

This only happens when we are logged into the backend on a mobile device, and happens on 8.7 and 8.8.2 - as we forgot to mentioned this during our previous reply. It does not happen on desktop.

This is another bug that we believe that should be looked into.
