### ISSUE TITLE
Create JSON schema test suite for testing API endpoint output

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#44262]
### Issue description

Project thread: pdibGW-2Mv-p2

Discussion: pdibGW-2Mv-p2#comment-2071

Create a suite of tests for JSON schema.

These tests should test:

1. Validity of JSON structure
2. Validity of all transformers
3. Validity of all rules

### Acceptance criteria

1. A JSON schema-based test suite that validates any remote endpoint JSON output
1. Add CI in WCCOM to run tests against remote endpoints JSON output

**Comment by psealock** [comment]
>Create a composer package

@ilyasfoo Composer only allows one package per repo because it needs `composer.json` at the project root. Apparently, you can do this with Private Packagist, but not our current open source setup. - https://blog.packagist.com/installing-composer-packages-from-monorepos/

There has been lots of talk about creating distribution read-only repos that house production releases of plugins and packages, but there hasn't been any movement so far.

I'm wondering if there is another way? Alternatively, we could just build that out specifically for php packages, considering there are zero php packages being developed.

**Comment by moon0326** [comment]
> I'm wondering if there is another way?

We could also make a new repo in automattic org github to make things simpler. I don't think this has to live in our monorepo.

**Comment by ilyasfoo** [comment]
Thanks for investigating @psealock!

> I'm wondering if there is another way? Alternatively, we could just build that out specifically for php packages, considering there are zero php packages being developed.

Sorry I don't understand what you meant here 🙏 

> We could also make a new repo in automattic org github to make things simpler. I don't think this has to live in our monorepo.

@moon0326 Makes sense, but I wonder how the DevEx would be to develop the tests in another repo? Would we be able to symlink, would we have access to all the imports required?

**Comment by moon0326** [comment]
> Makes sense, but I wonder how the DevEx would be to develop the tests in another repo? Would we be able to symlink, would we have access to all the imports required?

That's a good question. To be honest, I don't have a reason why it has to be in a private repo since it's just a JSON schema (We'll most likely use open-sourced JSON validator). Private repo can also be used if it has to live in automattic org. See: https://getcomposer.org/doc/articles/handling-private-packages.md

**Comment by moon0326** [comment]
Is anyone interested in picking up this issue?

I'm a porter this week, but I would like to work on JSON schema for RIN. May be we can split this issue into two? 

1. Build JSON schema
2. Make composer package that validates an endpoint or JSON string with a given JSON schema

**Comment by psealock** [comment]
>Is anyone interested in picking up this issue?

Yes, I'm interested but to be honest I'm not grasping how this comes together. I can work on 2) and figure out how to publish a PHP package to composer. 

>I don't think this has to live in our monorepo.

This type of package is exactly why we have a monorepo. It doesn't need to be in the monorepo to work, but this is a problem that needs to be solved anyways.

**Comment by ilyasfoo** [comment]
> I'm a porter this week, but I would like to work on JSON schema for RIN. May be we can split this issue into two?

Sounds great! I'll create another issue for publishing PHP package.

> Yes, I'm interested but to be honest I'm not grasping how this comes together. I can work on 2) and figure out how to publish a PHP package to composer.

Awesome, thanks!

**Comment by ilyasfoo** [comment]
I've split the packagist parts into https://github.com/woocommerce/woocommerce/issues/44417

**Comment by ilyasfoo** [comment]
@psealock I'm not sure if the acceptance criteria is accurate, if you're keen to pick it up, feel free to modify as needed

**Comment by moon0326** [comment]
Closed with https://github.com/woocommerce/woocommerce/pull/44419

**Comment by ilyasfoo** [comment]
Hey, @moon0326! Would you like to work on importing the tests package in WooCommerce.com and create test classes? Otherwise, I'll create a follow-up issue
