### ISSUE TITLE
[Enhancement]: Add Cart link in Checkout template header

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#44837]
As part of our ongoing efforts to pdFofs-1Pu-p2, we have identified the following opportunities as quick win UX improvements. cc: @pmcpinto 

### Add Cart link in heading (handled in this ticket)
Users needs to have an easy access to cart from checkout. We will add this new element as part of the minimized heading component in checkout 2JyXNimI4oGeJZhgQNZE9V-fi-2072%3A31996

![CleanShot 2024-02-21 at 11 28 03@2x](https://github.com/woocommerce/woocommerce/assets/99638528/e831ee0a-e4fe-4964-a90a-afcdae049b5a)

### Expected result
- Create a new block "Return to cart" block which contains the cart link + icon; Follow the Mini cart approach on these two components regarding color, inheritance from Global Styles and customization options
- Include an icon selection toggle as part of this block. For now we aren't going to sync to sync this option with the other Mini cart blocks from the store; We can inform merchants this isn't synced in the block despription.
- Insert this block as part of the distraction-free checkout header template

**Comment by pmcpinto** [comment]
Additional notes:
- The goal is to improve the existing Checkout header we include as a template part.
- It would be helpful to reevaluate if we can release this header as the default for new stores with a block theme. IIRC we don't have the Checkout header as the default due to potential conflicts.

**Comment by ralucaStan** [comment]
I recommend splitting this ticket into 2 separate issues. 

@nikkivias For the `Add Cart link in heading`, the team is concerned that the users might expect the Mini Cart block to open. Should we be explicit about the intention of that link by using a label like `Go to Cart`?

**Comment by dominique-vias** [comment]
Hmmm interesting. I think there is enough precedent through other online stores that the Cart link in both cart and checkout will not open up the Mini cart, as it is usually a means to navigate to both pages.

On Baymard, there no requirement for explicit text and the word `Cart` is enough along with the icon. What we can do to prevent any confusion is to add a tooltip on hover.

![CleanShot 2024-04-18 at 22 05 06@2x](https://github.com/woocommerce/woocommerce/assets/99638528/15279772-fc24-432c-af2d-86601d6fe018)

Apart from that, we can also implement an exit intent popup, which can be triggered not only when clicking `Cart`, but any other link that will cause exit.

![CleanShot 2024-04-18 at 22 14 40@2x](https://github.com/woocommerce/woocommerce/assets/99638528/feb6b004-62d4-4b90-bd65-543e309fad39)

**Comment by pmcpinto** [comment]
> On Baymard, there no requirement for explicit text and the word Cart is enough along with the icon. What we can do to prevent any confusion is to add a tooltip on hover.

@nikkivias what are the drawbacks of having the "Return to cart" copy?

> Apart from that, we can also implement an exit intent popup, which can be triggered not only when clicking Cart, but any other link that will cause exit.

Is this a common pattern? I wasn't able to find anything about this in the Baymard research.

**Comment by ralucaStan** [comment]
If we change the copy then somebody trying to get back to the cart will get there via 1 click; If we introduce a confirmation window they will get there via 2 clicks; So I think it makes sense to just change the copy

**Comment by pmcpinto** [comment]
@nikkivias can you check my questions above? Thanks

**Comment by dominique-vias** [comment]
> On Baymard, there no requirement for explicit text and the word Cart is enough along with the icon. What we can do to prevent any confusion is to add a tooltip on hover.
> 
> @nikkivias what are the drawbacks of having the "Return to cart" copy?

@pmcpinto I have no strong objections. I am only trying to limit the text as much as possible, also considering internationalisation. [Baymard places more emphasis](https://baymard.com/premium/guideline-collections/58zheo/607) on having both an icon and label, than what the text says.

> _Place the link to the cart in the upper-right-hand corner of the sitewide page header; use a clear icon or button with sufficient size, color, contrast, and surrounding white space; and avoid text-only links._

<img width="1457" alt="Group 1000007171" src="https://github.com/woocommerce/woocommerce/assets/99638528/882d7dc9-16b7-4b43-9bc1-c7bf3fdf1a68">
<br>
<br/>

> Apart from that, we can also implement an exit intent popup, which can be triggered not only when clicking Cart, but any other link that will cause exit.
> 
> Is this a common pattern? I wasn't able to find anything about this in the Baymard research.

I found the Baymard guideline on this ([Check strategy #2](https://baymard.com/blog/handling-accidental-taps-on-touch-devices)) and this is mostly applicable to touch devices where there are higher chances of accidental tapping. The modal uses the mobile OS component. However, there is a trade-off of the modal being intrusive.

**Comment by pmcpinto** [comment]
@nikkivias thanks for sharing some examples. i18n is an important factor.

I think we shouldn't implement the modal and go with the icon + Cart copy. The text should be editable - users can always tweak it to make it more explicit. Does that sound good?

**Comment by pmcpinto** [comment]
@nikkivias can you confirm that you agree with the icon + Cart copy option?

**Comment by dominique-vias** [comment]
@pmcpinto Sorry for the late reply. Yes, let's go with `Icon + Cart`

**Comment by mikejolley** [comment]
Including the _Icon + Text + Link_ via a new block would be ideal because we need to have some inline options. I'm not sure if it was considered, but I would like to draw attention to the mini-cart block which has options to select the icon:

![Screenshot 2024-06-13 at 13 30 25](https://github.com/woocommerce/woocommerce/assets/90977/e5364e57-e815-4cca-9647-59c02718f9f3)

If we went with a fixed icon here, there would be some inconsistency. 

I think the tasks needed here are:

1. Create a new block which contains the cart link + icon (this needs a name)
2. Include an icon selection toggle as part of this block **and/or** find a way to sync this option with the mini cart block
3. Insert this block as part of the distraction free checkout header template

What are everyones thoughts on this? If adding a custom icon is too complex or out of scope, should we do a text only link?

@nikkivias @pmcpinto @ralucaStan

**Comment by dominique-vias** [comment]
That makes sense @mikejolley thanks for bringing this to our attention.

I think having a toggle in two places may also cause inconsistency, so syncing the icon with the mini cart block makes sense. The mini cart block should be the primary location because it has more visibility.

Do we need to inform the user that the cart icon in checkout is not editable, and they need to do it via the mini cart? I am not familiar with ways of working on the editor side.

**Comment by mikejolley** [comment]
@nikkivias Since a user could technically have several instances of mini-cart active, all with different icon selections, I'm not sure there would be a single source of truth for this. Likewise editing the header template without access to that control could be pretty annoying. Do we need a synced global setting or something? cc @ralucaStan

**Comment by pmcpinto** [comment]
Thanks, Mike. The potential connection to the mini-cart is an important point that we should have considered.

> Insert this block as part of the distraction free checkout header template

Introducing this in the distraction free header should definitely be part of the scope.

> Create a new block which contains the cart link + icon (this needs a name)

"Return to cart" block?

> Include an icon selection toggle as part of this block and/or find a way to sync this option with the mini cart block

> Since a user could technically have several instances of mini-cart active, all with different icon selections, I'm not sure there would be a single source of truth for this. Likewise editing the header template without access to that control could be pretty annoying. Do we need a synced global setting or something?

If syncing adds some issues, I think we should go with a selection toggle, and inform users that this isn't synced with the "mini-cart" block.

We have this open issue (#42352), where some users think we should allow shoppers to interact with the mini-cart in the checkout. I'm not confident that we should allow shoppers to open the drawer in the checkout, but I wonder if we should revisit the mini-cart settings and use this block here rather than creating a new one. On the other hand, I'm afraid that we end up trying to cover too many use cases with the mini-cart block. What do you think?

**Comment by pmcpinto** [comment]
@wavvves @nikkivias I'm reviewing this issue. Is there anything blocking this from being completed and released? Thanks

**Comment by wavvves** [comment]
> [@wavvves](https://github.com/wavvves) [@nikkivias](https://github.com/nikkivias) I'm reviewing this issue. Is there anything blocking this from being completed and released? Thanks

hi Pedro, sorry for the late reply. I started a PR for this, unfortunately it was trampled by SIRTs and AFK. While we were in the DM @mikejolley took over (kudos), and submitted a PR we're reviewing right now https://github.com/woocommerce/woocommerce/pull/51948
