### ISSUE TITLE
[Enhancement]: Order summary fixes in Block-Based checkout

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#44839]
### Describe the solution you'd like

As part of our ongoing efforts to [improve the block-based checkout](https://woocheckout.wordpress.com/2024/02/14/block-based-checkout-ux-optimization-phased-implementation-overview/), we have identified the following opportunities as quick win UX improvements. cc: @pmcpinto

- [ ] Add an allover border to visually contain the Order summary
- [x] "Order summary" heading style change to Medium weight
- [x] Removed border separators between order items
- [ ] Grouped together "before total items" for enhanced readability (Subtotal, Shipping, Discount, Taxes, etc)
- [ ] Moved down Coupon and Gift card elements before total
- [x] Style "Add a coupon" the same as Gift card (accordion)
- [x] Remove product descriptions in product meta data. This info clutters the UI and provides little info about the item attributes

[Figma](https://www.figma.com/file/2JyXNimI4oGeJZhgQNZE9V/Checkout-Blocks-Optimization-(Shopper-UX)?type=design&node-id=2072%3A31996&mode=design&t=CrAuqoHYv50DYVz0-1)

![CleanShot 2024-03-04 at 15 15 32@2x](https://github.com/woocommerce/woocommerce/assets/99638528/c4d18006-ea22-48b3-aa7b-704772539793)

| Before | After |
|-----------------|-----------------|
| ![CleanShot 2024-02-21 at 11 45 23@2x](https://github.com/woocommerce/woocommerce/assets/99638528/19ba1373-7026-4184-829e-e07eb7664e41) | ![CleanShot 2024-02-21 at 11 44 29@2x](https://github.com/woocommerce/woocommerce/assets/99638528/6b010214-c6d3-427b-a9bd-ae28d33e588a) |

## Mobile

- [ ] Add a borderline after Total

| Before | After |
|-----------------|-----------------|
| ![CleanShot 2024-02-21 at 11 52 20@2x](https://github.com/woocommerce/woocommerce/assets/99638528/18580f78-9d5b-48d0-8c57-45be320d6c47) | ![CleanShot 2024-02-21 at 11 50 47@2x](https://github.com/woocommerce/woocommerce/assets/99638528/f86d5512-05ea-4c67-8f0a-d1b10be0ac21) |

**Comment by pmcpinto** [comment]
> Grouped together "before total items" for enhanced readability (Subtotal, Shipping, Discount, Taxes, etc)
> Moved down Coupon and Gift card elements before total

Users can reorder these elements in the editor, so I think it's safer to only apply these changes to brand-new stores.

**Comment by ResponsiveFlow** [comment]
On mobile, all the stuff between order summary block and order total is too tall, preventing shoppers to see the first fields unless they scroll down.

This is how it compares to Shopify Checkout. Now, I'm not saying to copy their Checkout, which by the way doesn't look that good compared to Woo's, but they managed to squeeze all those info in a single accordion.

| New Checkout Block | Shopify Checkout |
|--------|--------|
| <img width="394" alt="306594956-f86d5512-05ea-4c67-8f0a-d1b10be0ac21" src="https://github.com/woocommerce/woocommerce/assets/47855768/8cf78c61-d929-46ee-b8f6-71e689b248c0"> | <img width="297" alt="Screenshot 2024-02-27 at 11 05 19 AM" src="https://github.com/woocommerce/woocommerce/assets/47855768/709dabf0-49a4-4857-92b1-8ce50d264cc9"> | 

I think it's important to have some checkout fields "above the fold", because older or less tech-savvy shoppers may not understand that they have to scroll down to show shipping fields.
Consider that the first visible checkout field is below the express payments block, which may contain 2 or more express payment options.

**Comment by dominique-vias** [comment]
@tomxygen thanks for your input, agreed and we are looking to improve this in following iterations.

**Comment by alexflorisca** [comment]
Just about to start work on this. ~~I wanted to state that the same order summary block is used on the Cart block too. I'm assuming these changes apply there as well but wanted to double check?~~ Technically they are different blocks, but they are pretty much identical bar a few contextual differences. SO the question stands, should these be applied across Cart & Checkout blocks or just the Checkout? @pmcpinto @nikkivias

**Comment by dominique-vias** [comment]
Hi @alexflorisca yes the same principles should apply. Here is a Figma mockup of [how it might look like in Cart](https://www.figma.com/file/2JyXNimI4oGeJZhgQNZE9V/Block-based-Checkout-(Shopper-UX)?type=design&node-id=2790%3A20411&mode=design&t=Xa1RAewK5JtL3O58-1)

<img width="1456" alt="Cart" src="https://github.com/woocommerce/woocommerce/assets/99638528/ed02e733-32e7-4a49-83e7-cf66015606d8">

(I tested BNPL messaging as well)

Do let me know if you encounter anything that might cause a conflict in Cart :) thank you!

**Comment by alexflorisca** [comment]
@nikkivias there's a small inconsistency between the cart & checkout designs. The border goes around the heading on checkout, but not on Cart. Is that intentional? From a technical perspective, it makes things significantly more difficult to have the heading outside of the bordered box. The reason being that everything in rendered inside the side box. So it's very easy to add a border around the whole box, but otherwise it would add significant complexity to this. Could we do that as first pass at least? Here's a screenshot of how this will look

![Image](https://github.com/woocommerce/woocommerce/assets/3966773/aa1a548e-6382-4f51-8a9f-7283cdbb1ea3)

**Comment by dominique-vias** [comment]
@alexflorisca thanks for the explanation. Yes it was intentional because we are aligning the top of the cart summary to the lines on the left side. In this case, I would prefer we removed the 'Cart total'. We can live without it.

**Comment by alexflorisca** [comment]
Hi @nikkivias, having moved the Apply Coupon form down as per your designs, I'd like to point something out and maybe push back on this change a little. There's a few reasons for this. 

1. When a user enters a coupon, the totals are updated and the discount is shown. If the coupon form is above the totals, this flows more naturally. I apply my coupon, then I scan the totals to make sure it all looks ok. If the coupon form is below the totals, I look at my totals, apply the coupon then  double check the totals have updated. 
2. The UX also becomes less smooth when the user has to scroll up to check the totals after applying the discount. This might happen depending on what's displayed above it, screen size, etc.
3. You would also get a bit of divergence between new and existing stores. As this change requires updating the order the blocks are rendered, only new stores would have this change apply. Or more specifically, when a Cart or Checkout block is newly inserted after this change goes live. While it's not a big change, it may cause a bit of confusion with users. 
4. Users can move the order summary blocks around, so this change would also not be locked for everyone.

https://github.com/woocommerce/woocommerce/assets/3966773/62ea25e2-efe0-4377-9feb-d0ec0b78c89f

Given the above, I'd suggest, at least for this iteration, leaving the coupon form above the subtotals. I'm also having a discussion with my team about wether we should lock those order summary blocks so that users cannot re-arrange them. Let me know what you think.

**Comment by alexflorisca** [comment]
I also realised that combining the subtotal, discount, fees, shipping and taxes while possible for the default configuration, won't hold if the user moves things around. It becomes very messy technically as you'd have to have css rules for each position in the list and each possible item.

The question here is wether to combine all of these totals into a single block, which would solve the problem. I will raise an RFC to get some feedback on this and wether we should disable moving of the blocks inside the order summary

**Comment by dominique-vias** [comment]
@alexflorisca thanks for bringing this to our attention. you are quite right that it creates a stumble in the experience. I will give this some thought, in the mean time I'm definitely okay for us to stick with the Add coupon and Gift card blocks to be above the subtotals.

I created [updated screens here](https://www.figma.com/file/2JyXNimI4oGeJZhgQNZE9V/Block-based-Checkout-(Shopper-UX)?type=design&node-id=2847%3A8345&mode=design&t=MYPVzCGfYC9Fg7M1-1) for you to reference if helpful.

> You would also get a bit of divergence between new and existing stores. As this change requires updating the order the blocks are rendered, only new stores would have this change apply.

Yes this is the plan is to only apply it to new stores, or new insertions of the blocks. Our optimized design will be the default experience.

> Users can move the order summary blocks around, so this change would also not be locked for everyone.

I understand we want to keep flexibility, but IMO there are items that should stay in their place (e.g. Order summary title should always be on top, Subtotal should always be after item list, etc.) And perhaps they can reorder anything between Subtotals and Totals. What are your thoughts? @pmcpinto

**Comment by alexflorisca** [comment]
Thanks for your comments @nikkivias. I created an RFC(pdFofs-1Yh-p2) that expands on these comments. Would you mind sharing your thoughts there? I think it would be really valuable to have your input

**Comment by alexflorisca** [comment]
In order to move forward with the design changes in this issue, I created a https://github.com/woocommerce/woocommerce/issues/46018 which needs to be addressed firs. This is a refactor of some of the order summary inner blocks.

**Comment by nikkivias** [comment]
Should this still be blocked?

**Comment by ollima** [comment]
Hi @alexflorisca @nikkivias 
This thread is closed but this is the only thread I could find that discusses the Checkout blocks and Order summary in particular.
My question: Why is the coupon field locked inside the Order Summary?

We use different coupons frequently. Our customers are old.
The block Checkout is fine in desktop view BUT **in mobile the coupon field is hidden inside the Order summary accordion that the user must click to open**.
Hiding the coupon field creates an extra step that the customer might not realize to do.

Sugestion: there should be an option to move the coupon field outside the Order summary, at least in mobile.
This is an issue that is keeping us from updating to the new block checkout.

Also I'm seeing the accordion Order summary on the top of the page and another open Order Summary above the Order button.
I don't see any way of hiding this second Order summary except to use CSS.
I tested with Astra, Blocksy and Storefront themes.

I'm using Wordpress 6.7.2 and WooCommerce 9.8.2.
