### ISSUE TITLE
[Enhancement]: Support for dynamic properties on class objects

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#45286]
### Describe the solution you'd like

Since directly accessing undeclared properties in objects (ie: `$product->my_variable`) is going away in PHP 8.3, plugins who use that to set certain run-time only flags (for me it's to make it do something different via filter), need to prepare alternative solutions.

Bundles, Composites, and All Products for Woo Subscriptions have been [building their own system](https://developer.woo.com/2024/02/28/product-bundles-7-0-0-woocommerce-composite-products-9-0-0-and-all-products-for-woo-subscriptions-5-0-0-updates-adding-php-8-3-support-and-properties-controller-changes/) . And their work is excellent! But I was thinking, that's 3 plugins right there and I have 2 more and so every plugin that needs this now has to duplicate their effort... this is a lot of redundancy across the woo ecosystem.

What if instead, WC core introduced something that paralleled `get|set_prop()` and provided a single, centralized system for setting dynamic properties in a PHP 8.3 friendly way. Since they are run-time only they don't need to be connected to the data stores at all. At first glance, they don't seem like they've have a heavy footprint, nor should they create any backcompat issues. 

Opening for discussion as suggested in the [reply to my comment](https://developer.woo.com/2024/02/28/product-bundles-7-0-0-woocommerce-composite-products-9-0-0-and-all-products-for-woo-subscriptions-5-0-0-updates-adding-php-8-3-support-and-properties-controller-changes/#comment-12401) on the developer blog. 

### Describe alternatives you've considered

Duplicating the Product Bundles approach.

**Comment by barryhughes** [comment]
If this reads like I'm opposing the idea, I'm not ... but I did want to talk it out a little and consider alternatives 🙌🏼 

I personally like the fact that PHP is discouraging dynamic properties and, though I understand the motivation behind the request, I wonder if it's trying to replicate the very thing that we are trending away from.

If you need to maintain some ephemeral data (ephemeral in the sense it will never be persisted to the database) in relation to products, orders, or something else, why not create well-defined methods with appropriate safety checks backed by a [WeakMap](https://www.php.net/manual/en/class.weakmap.php) (perhaps falling back on [SplObjectStorage](https://www.php.net/manual/en/class.splobjectstorage.php) or something else for older PHP versions)?



I'm just a little leery of adding yet more general purpose functionality to our own core objects.

**Comment by helgatheviking** [comment]
Hi barry... no worries. I get where you're coming from. But I am thinking there's gotta be some way to do this that's standardized so all the plugins that need ephemeral data can have it without everybody reinventing the wheel.

**Comment by helgatheviking** [comment]
@barryhughes Just nudging you again... has the team given this any additional thought?

**Comment by barryhughes** [comment]
Thanks for the nudge: yes, we will aim to provide a utility to help with this. Some quick notes:

- Our concern with doing this is that a tool for working with dynamic properties (in a world where PHP discourages doing so) is that it doesn't feel like something WooCommerce should really be responsible for.
- Balancing the above, our feeling is it may nonetheless be smart for us to provide a default mechanism for this, rather than see a proliferation of different techniques.
- Our solution will *probably* take the form of a very minimal wrapper around a `WeakMap`, falling back either on a polyfill or else `SplObjectStorage` (for PHP 7.x), as outlined in an earlier comment, and it will be possible to use it with all objects, not just products or orders.

**Comment by helgatheviking** [comment]
Thanks Barry. I started taking a look at implementing this unilaterally by borrowing (downright copying 😅) from product bundles. They have a [data class](https://github.com/woocommerce/woocommerce-product-bundles/blob/trunk/includes/class-wc-pb-product-data.php) with splobjectstorage and a few getters/setters. Perhaps we could port that to core?

Granted that is going to require some compat/version checking on my end to know which version of woo I'm working with, but I already have architecture for that.

do you know why php is discouraging this now? There are definitely use cases at least in the woo world.

**Comment by barryhughes** [comment]
> Perhaps we could port that to core?

Thanks for flagging—we can definitely take a look at that. For reasons of memory efficiency, I think we'll want to use weak maps when available (PHP 8+), but that may otherwise be close to what we'd do ourselves.

> Do you know why php is discouraging this now?

I think at least part of the reason is to reduce the potential for unintentional mistakes. For instance:

```php
class Foo {
	public $foobar = 0;
}

$foo = new Foo;
$foo->foober = 2; // ← Probably a mistake (a typo), so PHP flags it.
```

Beyond promoting correctness, there may be performance gains and other benefits to discouraging and ultimately disallowing dynamic properties. There is quite a good write-up here, especially in the closing thoughts:

https://stitcher.io/blog/deprecated-dynamic-properties-in-php-82#closing-thoughts

**Comment by helgatheviking** [comment]
I was working on this in the morning and I'm not longer sure it's going to reduce my amount of code at all. If you host the weakmap/helper in Woo I'll need to version check if it's available before I can use it. Same if you introduced some getters/setters to the `WC_Data` class. At that point I may as well provide my own solution that I know exists. So I'm a little less convinced now this should be in core.

**Comment by barryhughes** [comment]
Given the last comment, and the lack of other interest in this (plus, the ability to create low-overhead solutions as outlined earlier in this thread), going to close.
