### ISSUE TITLE
[Enhancement]: Block-based checkout: Collapsed order summary on mobile

### ISSUE THREAD

**Issue by nikivias** [woothemes/woocommerce#45285]
### Describe the solution you'd like

The current checkout experience where the Order summary is concerned needs improvement. We want to investigate if the following proposed solutions are feasible.

## On mobile

Upon entering checkout the order summary takes up much of the space above the fold that it often pushes down the first actionable item on the page (e.g. Contact). Furthermore, when scrolling down to the end of the page, there is no access to the order summary unless the user scrolls all the way back up.

### 💡 Proposed solution
Implement an order summary that is:

- collapsed by default
- expands as an overlay
- hides/shows depending on scroll direction so it can be out of the way as they accomplish the page (video example below)
- add a final Order summary before `Place order` button

_Collapsed on default, overlay when expanded_

![CleanShot 2024-03-04 at 16 05 11](https://github.com/woocommerce/woocommerce/assets/99638528/86b1b9b8-6323-485e-a7b7-5e6b9ff148b7)

_Final order summary section (sticky summary is hidden in this view)_

![CleanShot 2024-03-04 at 16 09 17@2x](https://github.com/woocommerce/woocommerce/assets/99638528/f25f7f55-a83e-4f23-8889-8b61ae78f033)

_Example of scroll interaction behaviour:_

https://github.com/woocommerce/woocommerce/assets/99638528/33ef7c60-c2cd-4a53-b2f8-0ef8c71106b5

cc: @pmcpinto

**Comment by pmcpinto** [comment]
Two notes for the engineering team:
- The mobile and desktop flows don't need to be implemented in tandem. We can sequence them and implement them separately. 
- Both are good a/b testing candidates, so that we can measure the impact of these changes.

**Comment by senadir** [comment]
Hey @nikkivias @pmcpinto I removed the sticky on desktop part of this issue, as those are 2 different things with different scope.

Sticky one is already requested here https://github.com/woocommerce/woocommerce/issues/42230

**Comment by senadir** [comment]
@nikkivias just to confirm:

- You want the exact same order summary in 2 places, at the top of the page, and before the place order button.
- I'm not sure I understand the scroll effect you're looking for, does it mean it shows the sidebar if you're scrolling back up, but hides it if you're scrolling down?

**Comment by senadir** [comment]
I wanted to pick this next, but I'm porter next week, if I'm not the one picking this up, a suggestion to whoever is picking this up, instead of replicating the order summary component, touching the editor component, or the structure, just use a slotfill, inside the sidebar and above the place order button. You'd have 2 slots and 1 fill.

Ideally the top order summary is the current one in its placement, and the one above the button is the slotted one.

**Comment by opr** [comment]
@senadir the slots we add would be for internal use only, correct?

**Comment by senadir** [comment]
Yes, ideally. Any concerns there? I still think slots have a place in extensibility.

**Comment by opr** [comment]
No concerns, just checking. Yes they do have a place in extensibility but I don't think we should expose these publicly until we see a solid use case for it, outside of this one.

**Comment by dominique-vias** [comment]
Updating this issue with the latest [mock up](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=620-5004&t=SqLQNkiTDqqZbuir-1) and [prototype](https://www.figma.com/proto/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?page-id=224%3A2680&node-id=620-3300&viewport=705%2C2178%2C0.5&t=ka9BLIu10yhTvEP8-1&scaling=scale-down&starting-point-node-id=620%3A3300)

**Comment by pmcpinto** [comment]
@senadir @nikkivias is there anything blocking this work?

**Comment by samueljseay** [comment]
So there turned out to be some details missing from the design concept here and also both @opr and I agree that stickyness is not a great approach for the order summary header especially when trying to make something theme and layout agnostic for a few reasons.

It's difficult to explain in text what's missing and the issues but I'll do my best here:

Regarding the design details what's missing is that in the provided designs the order summary header is by default not sticky but then there is a question of how it should behave when you open it. The design shows an overlay for the content, if you are not in a position where the summary is sticky then opening it will supposedly still be an overlay but the position of the overlay content will be below the summary header.

Yet when you do a scroll up / scroll down, we will fix the summary header to the top of the screen then open it as an overlay. Having these 2 behaviours will be quite complex. I had an idea that we could animate the header to the top of screen and always have the content fixed position from the top. After thinking about this though, I felt the sticky header is very heavy handed for a default design and the design assumes a very simple layout situation, it would be very easy for the sticky header or the overlay to reduce usability in any custom design, it could easily obfuscate other information the store might want to present.

Also when you consider that we now present the order summary in 2 places with not a lot of vertical scrolling left to do (now that order summary is collapsed) there really isn't any inconvenience in finding the order summary information at any stage of the checkout process.

What I think we should implement instead (at least as a first iteration) is:

1. Order summary collapsed by default
2. Order summary also rendered at bottom of page
3. Design refreshes from the [mockup](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic%5D-Cart-%26-Checkout-Blocks?node-id=620-5004&node-type=frame&t=n2O9BXS2uLX5nmuS-0)

This imo is not only a lot simpler but also a lot safer for a variety of stores and still achieves key goals like reducing vertical space taken up by the summary and making summary information more accessible than before.

**Comment by pmcpinto** [comment]
@samueljseay thanks for outlining the challenges of implementing what was designed initially. What you proposed is a sound solution. Let me know when it's ready to be tested. Thanks

**Comment by pmcpinto** [comment]
Btw, I'll remove the blocked and needs:design label, as I don't think it's blocked anymore.

**Comment by ResponsiveFlow** [comment]
I tested the PR and it works great.
how about adding a gray bg to visually separate it from the other items?
![Image](https://github.com/user-attachments/assets/0cee2755-f05c-4d0b-bec1-f8de31386550)

**Comment by opr** [comment]
@tomxygen thanks for your comment. It would be helpful if you could add this on #52253 as well. I don't know how a grey background would work on dark themes, but I do like the idea of differentiating it from the rest of the content.

**Comment by pmcpinto** [comment]
@samueljseay can we close this issue? The implementation will be released in 9.5, correct?

**Comment by samueljseay** [comment]
Whoops seems that this didn't auto close with the PR. Yep it will be in 9.5
