### ISSUE TITLE
[CYS on Core] Make sure the pre-loader is triggered right after the user clicks on the opt in modal.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45476]
**Issue Description:**

Whenever the store owner did not give us consent and has the latest version of WP/GB installed, the following message is displayed on the sidebar:

<img width="1999" alt="screenshot-2024-03-04-at-20 50 30" src="https://github.com/woocommerce/woocommerce/assets/15730971/c09191df-2880-4fac-bc1b-7f4a2c3a5bfd">

To reproduce, make sure Gutenberg is enabled and/or your version of WordPress is 6.5 (if already available). Also, ensure you did not allow tracking by unchecking the usage tracking box on WooCommerce > Settings > Advanced > Woo.com.

Whenever clicking on the “usage tracking” link, the following modal should open:

<img width="1998" alt="screenshot-2024-03-04-at-20 51 47" src="https://github.com/woocommerce/woocommerce/assets/15730971/f4d14cb6-a880-4c0e-b52f-a99e6cf49002">

Whenever usage tracking is allowed, the page reloads, fonts are installed, and all relevant font pairings are displayed. The problem in this case is that the preloader is being added a bit later in the process, so the user can briefly visualize the fonts cards that are about to be installed when they shouldn't: 

https://github.com/woocommerce/woocommerce/assets/15730971/20439294-860b-42ac-aa91-0b00f483ac69

To improve user experience, let's ensure the pre-loader is triggered right after the user clicks on the opt-in modal so the fonts on the sidebar are visible only after they were downloaded.

**Comment by gigitux** [comment]
> Whenever usage tracking is allowed, the page reloads, fonts are installed, and all relevant font pairings are displayed

We can't rely on the async job. This latter can start later or be slower. Consequently, there's a risk that after refreshing the page, the fonts might not be installed. A potential solution involves installing the fonts on the client side. However, this method presents a challenge: it requires UI blocking (like loading screen) until all fonts are installed, which could lead to extended wait times (btw not the best UX).

The best solution is to provide an async client process so the user can continue to use the Assembler and notify it when the fonts are ready to be used, but I don't think that there is enough time for this kind of experience (also, is it worth investing time on it?)

As the first version, we could redirect the user to the settings page of WooCommerce, and after that, the user will have to restart the process from scratch. I know that it is not an optimal solution, but it is something that we could consider. 

Otherwise, we have to find a UI that shows the user that fonts are being installed, but the user can't use the Assembler (like a big loading screen).


This is a video that shows the issue:


https://github.com/woocommerce/woocommerce/assets/4463174/561b3ec4-7ae2-4a8e-8cca-8eadb0d6c396

Thoughts?

cc @albarin @nefeline @verofasulo

**Comment by nefeline** [comment]
Thanks for your input @gigitux !

> We can't rely on the async job.

We are not relying on the async job in this case: by triggering the loading screen whenever the "Opt in" button is clicked, we should trigger the validation that ensures all relevant fonts are in place and were successfully installed. - If for some reason these fonts are not available, trigger the fonts installation on the JS side so the store owner have them all available by the time they reach the Assembler. This was in the original scope of implementation as described here: https://github.com/woocommerce/woocommerce/issues/44257

Are you implying this hasn't been implemented?

**Comment by gigitux** [comment]
> Thanks for your input @gigitux !
> 
> > We can't rely on the async job.
> 
> We are not relying on the async job in this case: by triggering the loading screen whenever the "Opt in" button is clicked, we should trigger the validation that ensures all relevant fonts are in place and were successfully installed. - If for some reason these fonts are not available, trigger the fonts installation on the JS side so the store owner have them all available by the time they reach the Assembler. This was in the original scope of implementation as described here: #44257
> 
> Are you implying this hasn't been implemented?

It has been implemented and we can re-use the same function. Just to clarify:

> To improve user experience, let's ensure the pre-loader is triggered right after the user clicks on the opt-in modal so the fonts on the sidebar are visible only after they were downloaded.

With the `pre-loader is triggered´, are you referring to this preload screen?
![image](https://github.com/woocommerce/woocommerce/assets/4463174/cd91abf3-9333-461a-b59d-14492e1a698a)

**Comment by gigitux** [comment]
This is a quick implementation. Are we aiming an experience like this, right?

https://github.com/woocommerce/woocommerce/assets/4463174/9008c89f-85de-4fba-ae8d-4b7155da6dd9

**Comment by nefeline** [comment]
> This is a quick implementation. Are we aiming an experience like this, right?

It could be like this, yes!

Currently, the Opt-in modal is directing users directly to `${ ADMIN_URL }admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub`, but we could update that to `${ ADMIN_URL }admin.php?page=wc-admin&path=%2Fcustomize-store%2Fdesign` without any problems (while the first is just a regular preloader, the second is the default loading screen we have in the CYS). 

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-typography.tsx#L215

Either way, the most important thing is to ensure that this is triggered: https://github.com/woocommerce/woocommerce/blob/69728b70e98f25db90e313e9cf62da69077f30ae/plugins/woocommerce-admin/client/customize-store/design-without-ai/state-machine.tsx#L163

And that the loading screen is displayed immediately after the user clicked on "Opt in", without any delays (this is the main goal of this issue!)
