### ISSUE TITLE
[Analytics] Error showing deleted product in Analytics

### ISSUE THREAD

**Issue by octaedro** [woothemes/woocommerce#45637]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After creating a variable product and a few orders containing it. When that product is deleted (permanently), the first product variation name is shown in the table instead of showing the product name.

![Screenshot 2024-03-15 at 4 40 39 PM](https://github.com/woocommerce/woocommerce/assets/1314156/39a72901-9244-4fe7-a424-c1f94974931d)

### Expected behavior

We should show the parent product name instead of the name of the first product variation.

### Steps to reproduce

1. Create a product with a few variations.
2. Create a few orders with those variations.
3. Delete the parent product permanently
4. Go to Analytics > Products
5. You will see `[Product name] - [first variation name] (Deleted)`.

**Comment by puntope** [comment]
Hi @octaedro I cannot reproduce the issue. So I bet its already solved at some point. Otherwise please feel free to re-open the issue ;)

<img width="1532" alt="Screenshot 2024-07-11 at 21 24 18" src="https://github.com/woocommerce/woocommerce/assets/5908855/1803e022-b2f4-4381-958d-f8113972fe6f">

<img width="1501" alt="Screenshot 2024-07-11 at 21 24 09" src="https://github.com/woocommerce/woocommerce/assets/5908855/e591ae6b-ca88-4fe5-b10d-244ab5e909ad">
