### ISSUE TITLE
Investigate opportunities to optimize WC Blocks Webpack builds

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#45680]
While @samueljseay was investigating upgrading `@wordpress/components` he discovered that the WC Blocks webpack builds appeared to be duplicating some vendor dependencies in every entry point making the bundle sizes bigger than they need to be.

To satisfy this issue we can investigate and document why this is happening as well as document any potential solutions for later implementation.

**Comment by samueljseay** [comment]
There is another thing I noticed we can do, but I won't do as part of this task, which is, we can update the wordpress polyfill. In recent month's it's been updated to be significantly smaller for the narrower browser support that's needed since dropping old browsers. Since it's used duplicated in many places  I expect it would have some noticeable impact on payload size.

Another small saving: we could remove our dependency on the old reakit version of Ariakit. It's used in one component that isn't used, so either we remove that component or update it to Ariakit as part of the migration to Ariakit.
