### ISSUE TITLE
CYS > Patterns Migration: Ensure all WooCommerce patterns are migrated to the PTK

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45835]
Ensure all WooCommerce patterns are migrated to the WP.com's PTK. 

## Managing categories

Instead of registering the patterns within the same pre-existing WP.com categories, in this first moment, we should create `_woo_*` categories instead and register them via WooCommerce plugin to the matching categories accordingly. For example:

- Fetch the `_woo_about` category from WP.com's PTK.
- Register all patterns from this category under the `about` category within our codebase.

Why follow this path? We don't have an elegant solution to ensure that whenever a site fetches patterns from the PTK, the WooCommerce plugin is enabled. This means that if we automatically registered our patterns in the pre-existing `about` category, all consumers of this API would see block errors in the editor whenever attempting to insert any of those Woo patterns and not having Woo installed on their sites.

Why prefixing with underscore? Because the PTK has a system in place that ignores categories in the editor and the public library when they use a slug that starts with an underscore. This way we can delegate the registration entirely to Woo.

## Managing categories

All patterns that are in use within the CYS should be migrated to the categories @verofasulo highlighted in the Figma file: FlPl7fHaGv9mpu8Nfl0joH-fi-2792_124404

All patterns not part of the CYS should be migrated to our pre-existing WooCommerce category, At least at this moment, until @jarekmorawski and/or @verofasulo have the time available to prioritize classifying these patterns accordingly.

**Comment by albarin** [comment]
All the patterns in WC have been created in https://wooblockpatterns.wpcomstaging.com/ under 6 different categories prefixed by `_woo_`.

I have not created the following patterns 👇 since I was in doubt if it made sense for different reasons (some are not visible on the inserted, some were created for the LYS project, etc):
- Coming soon
- Coming soon entire site
- Coming soon store only
- Product filters
- No products found
- No products found - Clear filters
- Product search
- Related products
