### ISSUE TITLE
[Enhancement]: Make the Legacy REST API plugin HPOS compatible

### ISSUE THREAD

**Issue by ryanr14** [woothemes/woocommerce#45833]
### Describe the solution you'd like

We're going to be force installing the Legacy REST API plugin when folks still using said API update to WooCommerce 9.0. 

The issue is if they are already using High Performance Order Storage (HPOS) they will start getting notices from that system that parts of their site aren't compatible with WooCommerce features, and they should deactivate this plugin.

Only come to find out it's a plugin we forced upon their site. :)

<img width="1387" alt="Screenshot 2024-03-21 at 12 49 16 PM" src="https://github.com/woocommerce/woocommerce/assets/867748/6af22c0d-9121-40ee-8a6c-ad8ee212287e">

You can imagine that being odd and unexpected for a lot of merchants. I assume most won't necessarily be aware this plugin was added, and then would be super confused when we recommend deactivating the plugin we added because it's not compatible with the latest and greatest HPOS in WooCommerce.

They also then may ultimately deactivate it and inadvertently turn off their legacy REST API integrations after all, which is the point of us force installing and activating the plugin in the first place.

### Describe alternatives you've considered

None that we should consider, I don't know if there's a limitation to making this new plugin HPOS compatible? It didn't have issues with HPOS when built into WooCommerce, right?

**Comment by ryanr14** [comment]
Just noting that that's all the support forums for this plugin on WordPress.org highlight as well.

https://wordpress.org/support/plugin/woocommerce-legacy-rest-api/

**Comment by barryhughes** [comment]
Thanks for flagging! We've seen some of that feedback and have had a couple of discussions about this already.

> I don't know if there's a limitation to making this new plugin HPOS compatible? It didn't have issues with HPOS when built into WooCommerce, right?

In fact, this was already a problem: the Legacy REST API was never compatible with HPOS.

Extracting it into its own plugin just has the side effect of highlighting the problem and, on balance, we think that is the preferred course of action (as opposed to potentially letting things silently fail in potentially non-obvious ways).

Theoretically, we could make it compatible: but this is long-deprecated functionality that we are removing. The best and preferred course of action is to migrate to supported versions of the API.

> You can imagine that being odd and unexpected for a lot of merchants. I assume most won't necessarily be aware this plugin was added, and then would be super confused when we recommend deactivating the plugin we added because it's not compatible with the latest and greatest HPOS in WooCommerce.

It could be a little confusing, yes. The general direction it is providing though is broadly accurate:

- We want users (and service providers) to move away from the Legacy REST API as soon as reasonably possible.
- If they absolutely need to keep using it, this extension is recommended (and is intended as a short-term solution—we don't plan on maintaining it indefinitely).
- It also is not compatible with HPOS and so, if that feature is enabled, we warn the merchant just as we do for any other WooCommerce extensions that are not HPOS-compatible.

Some possible compromises:

- We could soften the wording we use in the feature compatibility warning. Instead of, *"It shouldn't be activated,"* we could write, *"Use with caution."*
- We can add a sticky post to the [Legacy REST API forum](https://wordpress.org/support/plugin/woocommerce-legacy-rest-api/), to echo information we've shared in  other channels.
