### ISSUE TITLE
[Enhancement]: FSE themes to be able to show subcategories on category pages

### ISSUE THREAD

**Issue by carolframen** [woothemes/woocommerce#45866]
### Describe the solution you'd like

On classic themes, you can go on the customizer and choose to show the subcategories (if any) instead of the products on the category pages. 

On FSE themes, changing this on the customizer does not affect it and on the editor, the template for it is "product by category" and it is not possible to change it to show subcategories instead.

### Additional context

![image](https://github.com/woocommerce/woocommerce/assets/119800062/56e1d6ba-115a-41ca-8b6a-748d275c4748)
Clothing category page on Storefront.

![image](https://github.com/woocommerce/woocommerce/assets/119800062/b60a4df1-358e-44f5-9420-05f7282215bb)
Clothing category page on Twenty Twenty-Four.

This was reported by an user here: https://wordpress.org/support/topic/fse-theme-sub-categories-not-showing-on-category-page/

**Comment by imanish003** [comment]
Hey @carolframen,

You may use `Product Categories List` block in “Products by Category” template. There is the following setting that can be used to show sub-categories:



<img src="https://github.com/woocommerce/woocommerce/assets/16707866/424df9bc-b36a-4e85-9679-da9f7db24c2f" width="200">


Here is how it will look on Frontend: 

<img src="https://github.com/woocommerce/woocommerce/assets/16707866/6db3d7bd-fb3b-482e-95a3-017953e75094">


Soon, We will start working on the “Category Collection” block, which will be like the “Product Collection” block with lots of controls/settings. That will allow merchants to show any kind of Category List UI. 

I hope this information is helpful. Please feel free to ask any follow-up questions. I am closing this issue because there is a way to display subcategories on category pages. However, I am more than happy to reopen it if there is a valid reason to do so.

**Comment by 7onc1** [comment]
Hi, any news on this? I want to be able to show the subcategories and then the products

**Comment by imanish003** [comment]
Hi @7onc1,

I'm sorry, but I'm having trouble understanding your question. Can you please give me more details? 🙂

Wasn't the explanation I provided in [this comment](https://github.com/woocommerce/woocommerce/issues/45866#issuecomment-2024810762) helpful for you? I was referring to using the "Product Categories List" block in the "Products by Category" template.

As for the "Category Collection" block, we have not started working on it yet. It's a high priority for us, and we will begin working on it very soon, but it's difficult to provide an ETA at this time.

CC: JFYI @manospsyx @sunyatasattva

**Comment by BManThere** [comment]
The option for "Only show children of current category" seems to be missing from the block options when using WordPress 6.7.2 with the Twenty Twenty-Five theme. (Apologies in advance if I am overlooking something)

![Image](https://github.com/user-attachments/assets/1244b1c8-33e8-402c-9709-021061f9ca97)

**Comment by imanish003** [comment]
@BManThere Just to clarify - did you try adding this option while creating a new post?

The "Only show children of current category" option is specifically designed for the "Products by Category" template. Could you please verify if you can see this option when editing the "Products by Category" template instead?

CC: JFYI @gigitux @WunderBart
