### ISSUE TITLE
Maybe deprecate the `/reports` endpoints

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#45898]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

The REST API `/reports/**` [endpoints](https://woocommerce.github.io/woocommerce-rest-api-docs/#reports) originally served a specific UI in the WooCommerce back-end that has since been deprecated in favor of the new analytics reports. This issue serves as a tracking issue to help us understand whether these endpoints should also be deprecated -- like the UI they were serving -- or whether we should keep supporting them. 

A few notes:

- The new analytics use endpoints that are not versioned and as such should not be considered public, i.e., we don't have a proper replace for the `/reports` endpoints. 
- Is the code that these endpoints are being generated from deprecated? Then we should figure out how to deprecate the endpoints, too. 
- Is anyone using these endpoints? Should they be? 
- REST API docs website still shows reports endpoints – there’s no indication that they’re deprecated, even though the UI has long been deprecated. Maybe a good first step, when deciding to deprecate the endpoints, would be to remove them from the public API documentation. 
- We could also consider sending a header and / or log something and / or create an admin notice if we decide to deprecate.

**Comment by joshuatf** [comment]
My 2 cents is that while we should move towards deprecating these endpoints, we need to move towards making the newer ones public (admin-facing and not internal) since they can and probably are used by some developers.

Currently the newer endpoints do have hooks inside them making them extensible, but the endpoints themselves have not yet been labeled for public use.

>Is anyone using these endpoints? Should they be?

I'm not sure off the top of my head if anyone is using the endpoints, though I know a number of extensions added to the legacy reports and some store owners were continuing to rely on them.

>Maybe a good first step, when deciding to deprecate the endpoints, would be to remove them from the public API documentation.

Agreed.  Also providing a 2 year deprecation window for developers to move to the new endpoints or make feature requests around those endpoints to meet extension requirements.

Hopefully anyone relying on those endpoints will also chime in here to let us know which, if any, features or stats might be missing in the new endpoints for proper extensibility.

**Comment by barryhughes** [comment]
I think there may be another thread or discussion about this, but to bring things up-to-date here with my own understanding:

> The REST API /reports/** [endpoints](https://woocommerce.github.io/woocommerce-rest-api-docs/#reports) originally served a specific UI in the WooCommerce back-end

I'm not sure this is accurate or, at the very least, I think we can say that the legacy reports do not currently use these endpoints. So I think we should regard them as two different things (to that end, I have removed the `focus: legacy reports` label from any related bug reports).

> Is anyone using these endpoints? Should they be?

Bug reports relating to these endpoints (and emoji reactions) suggest they are actively being used by some. If we have a reason to deprecate, I think a [public discussion](https://github.com/woocommerce/woocommerce/discussions) may be the preferred starting point (and we could close this issue).

wdyt @lsinger: shall we close this issue, or prefer to keep it open?

**Comment by coreymckrill** [comment]
For now, there's no plan to deprecate these endpoints.

Additional context: pfKYZu-Do-p2
