### ISSUE TITLE
Changing the customer of an order doesn't update all tables

### ISSUE THREAD

**Issue by dademaru** [woothemes/woocommerce#45899]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When **changing the customer** of an **order**, the previous **customer_id** remains in some WooCommerce tables (__wc_order_product_lookup_, __wc_order_stats_).

### Expected behavior

Context: there may be a need to combine multiple user accounts (maybe created over time) into one account, and then (re)assign the various orders to that one account.

When changing the customer in order edit page I expect it to be updated on all occurrences, to avoid potential issues.

### Actual behavior

If using _WordPress posts storage_ (legacy) for orders, in __postmeta_ table the **_customer_user** meta is updated with the new user ID.
If using _High-performance order storage_, in __wc_orders_ the **customer_id** value is updated with the new user ID.

But in __wc_order_product_lookup_ and __wc_order_stats_ tables, the **customer_id** value still contains the old customer ID.

– question: why in the new (HPOS) orders table does the **customer_id** column contain the _user_id_ (0 if guest) while in the other tables it always contains the _customer_id_? –

### Steps to reproduce

1. Go to Order edit page
2. Select another customer for that order.
3. Click update button to save Order
4. Click the edit icon near billing & shipping address, then click 'Load billing address'.
5. Click update button to save Order

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.7.0
REST API Version: 8.7.0
Action Scheduler Version: 3.7.2
WP Version: 6.4.3
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dademaru** [comment]
Hello, I need to delete duplicated accounts for hundreds of customers (created over time using _WooCommerce Social Login_ extension) and reassign orders to the unique account they want to keep.
Currently I can't proceed since reassigning order user/customer doesn't update correctly all the occurrences in DB, as I tried to report.
I understand it's not a priority but seeing no response 1 month later I would like to know if anyone had been able to reproduce/test the problem and if there is any patch to apply while waiting for it to be fixed.
Meanwhile thanks.

**Comment by jorgeatorres** [comment]
Hi @dademaru,

Thanks for reaching out and apologies for the delay here. I tried to reproduce the issue but couldn't: when I change the customer on the admin (with HPOS), it's properly updated in the orders table but also in the order product lookup and stats tables, once the relevant scheduled job has been executed. 

> But in _wc_order_product_lookup and _wc_order_stats tables, the customer_id value still contains the old customer ID.

Apologies if I'm reiterating something that you're already aware of, but the `customer_id` in these tables is not the same as the user ID (from the users table). Instead, it refers to the customer ID from the `wc_customer_lookup` table, which also has a reference to the proper user ID (if it exists).

There might be a delay between you making an update and the values being changed in the lookup tables because that info is processed via an A-S job.

By going to Tools > Scheduled Actions > Pending, you can confirm that after any order update you should see a job `wc-admin_import_orders` which receives the modified order ID as argument. After that actions runs, all the lookup tables should be updated too.

Is this not working for you? Are you maybe having issues with Action Scheduler on your site?

> question: why in the new (HPOS) orders table does the customer_id column contain the user_id (0 if guest) while in the other tables it always contains the customer_id?

I understand why the naming might be confusing, but the `customer_id` in the HPOS tables is backwards compatible with the `_customer_user` meta from the posts order storage, and thus it points to the actual user ID and not the `customer_id` from the lookup tables.

Also, while very useful, lookup tables are not considered the authoritative version of the order information, and so are actually _generated_ from other data (by an scheduled job, as explained above).

* * * *

With the above in mind, could you please try this again and see if it is still a problem? If so, could you please expand on the testing instructions (particularly around what you expect to see vs what you're seeing).

Looking forward to hearing back from you. Thanks again!

**Comment by dademaru** [comment]
Hi @jorgeatorres,
Thank you for trying to reproduce the problem and for the very detailed response.
Indeed there was a problem with Cron Jobs (they are disabled via `'DISABLE_WP_CRON'` and enabled via server Linux `cron` service).
I saved again the order and searched `wc-admin_import_orders` in Tools > Scheduled Actions > Pending and I saw that it always resulted pending. I clicked 'run' and it updated the `customer_id` in the tables I mentioned.
Thanks again!
