### ISSUE TITLE
What is the point of using JSON.parse and decodeURIComponent?

### ISSUE THREAD

**Issue by edo888** [woothemes/woocommerce#45902]
Hi,

I have noticed this code ( https://github.com/woocommerce/woocommerce/blob/f325727a7fd39a5708fe09e00aaa5f46f79c82e7/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php#L396 ) and have no clue why you just do not do the following instead:

`$wc_settings_script            = "var wcSettings = wcSettings || " . wp_json_encode( $this->data );`

I would understand the use of JSON.parse only, since it will give you a little speedup during parsing, since JSON syntax is easier to parse than javascript syntax, but for me it does not make sense to see decodeURIComponent.

Thanks!

**Comment by opr** [comment]
Hi, it's because `esc_js` is escaping the JS, and turns quotes into `&quot;` symbols, therefore we need to encode this and then decode it on the front end.

In your example you removed `esc_js` which means that potentially harmful text could be output onto the page.

Hopefully this helps answer your question! Since there's nothing actionable here I'll go ahead and close it, but please feel free to reply or reopen it if you believe there's something we should change.

Thanks!

**Comment by edo888** [comment]
What is the point to do esc_js on $data which is already rawurlencode-ed?

Are you saying that you do not already escape properly $this->data fields with esc_js which can contain javascript?

I think wp_json_encode is safe to be placed inside script tags.

Can you provide a minimal example which can cause issue without rawurlencode and esc_js?

Thanks!
