### ISSUE TITLE
Simplify the Images empty state

### ISSUE THREAD

**Issue by j111q** [woothemes/woocommerce#45920]
Through our user research, we uncovered some confusion about the Images empty state. The current design gives the impression that these specific four types of images are required, or that there are actually four specific image "slots" for different image types. This isn't true.

So as a solution, we want to simplify the empty state.
This change should be applied across all templates (Standard, Grouped, Affiliate) and Variations.

Mock-up:

<img width="634" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/5329b8c5-6325-472e-bde3-b971c735f4ee">

**Comment by pmcpinto** [comment]
@j111q, the empty state you're proposing is quite similar to the original one. :) Some context: We've changed the empty state and shown more than one placeholder image because we received feedback that users assumed it was only possible to add one image. The approach with some placeholder images also creates confusion, so I wonder if there's a middle ground between them. An alternative is to use implement this placeholder but update the section title to make it more explicit that it includes the product image and the product gallery.

**Comment by j111q** [comment]
@pmcpinto What do you think about this instead? 

<img width="713" alt="image" src="https://github.com/woocommerce/woocommerce/assets/65582817/46989ee9-1d25-4a66-a160-152fd027b9ad">

[Figma link](https://www.figma.com/design/vhp1LFki2xHqjck6UegZJT/Product-Form-2.0-Working-FIle?node-id=853%3A40200&t=DCuiBf1cooFCm6S6-1) for ref.

**Comment by pmcpinto** [comment]
I think it's a good middle ground. Nice work 🙌

**Comment by j111q** [comment]
Cool, let's see what it does in the numbers! 👀 
Exported the [asset in SVG here](https://www.dropbox.com/scl/fi/q6zkm324iskdkgeq4vi6w/asset_images.svg?rlkey=vlt74tv9xh4vvfi6ua4em4dm1&dl=0).

**Comment by mdperez86** [comment]
@pmcpinto @j111q currently a product variation does not support multiple images yet, so since this component is being used for it as well it could cause some confusion too. So we could think about changing this placeholder to be perceived as a single image or let the user upload more than one.
I consider that this should not be part of this issue so we should create a new one to tackle whatever will be your decision on this.

**Comment by pmcpinto** [comment]
@mdperez86 thanks for the heads up. Do we need to use the same component in both areas (simple and product variation)?

**Comment by mdperez86** [comment]
> @mdperez86 thanks for the heads up. Do we need to use the same component in both areas (simple and product variation)?

@pmcpinto @j111q That's is the idea behind components, they should be reusable. In this case the component does understand when to upload just one or multiple images, but we don't have yet an empty state for just one image. It will be not hard to add the just one image placeholder to the same component and only show it once we are editing a variation. But for that we do need the empty state.

**Comment by pmcpinto** [comment]
@mdperez86 thanks for the clarification. I'll create a separate issue for the variations image.
