### ISSUE TITLE
Address line 2 settings no more available with FSE themes

### ISSUE THREAD

**Issue by wpchannel** [woothemes/woocommerce#45980]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The address line 2 field could be a required one. The setting to manage this is accessible by using Customizer. The Customizer is no more accessible with FSE themes. You have to know this URL to change this setting. This way, a customer can edit his address in his account without line 2 as a required field.
When using checkout based on blocks, the option provided is not linked with the old adress endpoint in My Account.

### Expected behavior

This setting should be available without Customizer or synced with checkout block.

### Actual behavior

There is now way to set address line 2 as required or not with FSE themes.

### Steps to reproduce

1. Go to My Account > Details > Add address
2. Try to fill an address without line 2 and get the notice
3. Adjust setting in checkout block and try again: no change
4. Go to https://example.com/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php and adjust ;
5. Try again to change address in your account without providing line 2: it works

### WordPress Environment

WordPress 6.4 and Woo 8.7.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Thanks for reaching out, @wpchannel.

Your first step to reproduce indicates navigating to `My Account > Details > Add address`, but on my end, I only see an `Addresses` section where I can edit my addresses. Here's a screenshot of how the My Account page looks on my end:

<img width="1352" alt="Screenshot 2024-04-03 at 14 18 54" src="https://github.com/woocommerce/woocommerce/assets/3323310/cf63768a-a919-4e5f-9e6c-4acf3646eaf4">

Your fourth step mentions adjusting settings via `https://example.com/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php`. Could you specify what adjustments are to be made there?

Based on your description, it seems there are two main concerns:

1. The `Address 2` field settings are not accessible when using a block theme.
2. Consequently, addresses can be added with an empty `Address 2` field.

Can you confirm if these are the issues you're experiencing?

**Comment by wpchannel** [comment]
@nielslange can you add your screenshot?

When you don't have an address set, the Edit link is an Add link.

You're right my concern is only with block based theme. You don't have access to the Customizer when Site Editor is available. As a consequence, you can't choose which fields are mandatory or optional. The only to do this is by using a hook or knowing the mentioned URL.

**Comment by nielslange** [comment]
> @nielslange can you add your screenshot?

My bad. I just added the screenshot in https://github.com/woocommerce/woocommerce/issues/45980#issuecomment-2029519898.

> You're right my concern is only with block based theme. You don't have access to the Customizer when Site Editor is available. As a consequence, you can't choose which fields are mandatory or optional. The only to do this is by using a hook or knowing the mentioned URL.

Thanks for confirming this. Since WooCommerce 6.9, we're no longer showing the link to Customizer in WP Admin. You can find further information about this in https://github.com/woocommerce/woocommerce/issues/34430 and https://developer.woo.com/2022/08/11/stop-registering-customizer-options-for-block-themes/. 

It's possible to make the Customizer visible again by adding the following snippet to your site, e.g. using [the Code Snippets plugin](https://wordpress.org/plugins/code-snippets/):

```php
add_action( 'woocommerce_init', function () {
  if ( wc_current_theme_is_fse_theme() ) {
    new WC_Shop_Customizer();
  }
} );
```

However, you also mentioned the Checkout block. This makes me wonder if you're trying to adjust the `Address 2` setting in the Customizer when using the Checkout block. I'm asking as the Customizer settings have no impact on the Checkout block. Settings for the Checkout block have to be applied directly within the editor. Here's a screenshot that shows the `Address 2` settings of the Checkout block:

<img width="1352" alt="Screenshot 2024-04-03 at 15 07 30" src="https://github.com/woocommerce/woocommerce/assets/3323310/e1b5584d-4fa4-480f-b8b7-a07418f7df44">

That said, when using the Checkout block, the `Address 2` field cannot be set as a required field. I assume that's because not every buyer might be able to provide an apartment, suite, etc. Making this field required would prevent buyers, that cannot provide that date, from placing an order in the store.

Was your initial issue related to not being able to see the Customizer when using a block theme and the Checkout block, or was it related to not being able to make the `Adress 2` field required?

**Comment by wpchannel** [comment]
@nielslange I totally agree with your answer. It's not an issue with the block used in Checkout page.

Since you can't access Customizer anymore, you can't set `Adress 2` as optional or not for **My Account > Addresses**.

**Comment by nielslange** [comment]
Thanks for your promt reply, @wpchannel, and clarifying this. May I ask why making the `Address 2` field required is important for you? I'm asking as some sellers might not have an apartment or suite number, causing the risk that they're unable to update their addresses because of being unable to fill out the `Address 2` field.

**Comment by wpchannel** [comment]
@nielslange you're welcome. In my case, this field was set as required instead of optional. I was unable to change it to optional.

**Comment by nielslange** [comment]
Ah, I see the issue now. Thanks for patiently explaining it to me. To make the `Address 2` fields optional instead of required, you could apply the following steps:

1. Create a separate page and add the checkout shortcode to it.

```
[woocommerce_checkout]
```

2. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced`.
3. Define the page with the checkout shortcode as the "Checkout page".
4. Go to `/wp-admin/customize.php`.
5. Select `WooCommerce` and then `Checkout`.
6. Change the option of the `Address line 2 field` field.
7. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced`.
8. Reset the "Checkout page" to the page that contains the Checkout block.
9. Delete the temporary page that contained the checkout shortcode.

I'm closing this issue for now, as there are no action points for us. But feel free to reopen it again, if there's another problem related to this issue. And thanks again for reaching out in the first place.

**Comment by wpchannel** [comment]
@nielslange of course I know this kind of workaround. I was just reporting this issue, because it's a real issue for user experience if these kind of settings are no more available from the user interface don't you think?

**Comment by nielslange** [comment]
I see what you mean, @wpchannel. We've discussed this issue internally, and it turned out that this is a regression. I've created #46335, to allow making the `address_2` field optional resp. required when using the Checkout block. The address forms within the My Account section will respect the settings of the Checkout block.

**Comment by wpchannel** [comment]
Thanks a lot! In the same time, it should be great to test others fields too. I did not test the behavior.

**Comment by nielslange** [comment]
Absolutely. When we'll work on the other issue, we'll not only test the `address_2` field, but all fields. Whichever field is marked as required in the Checkout block, should appear as required within the My Account section.
