### ISSUE TITLE
[Enhancement]: Block-based checkout - Shipping section changes

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#46013]
This is a subticket of https://github.com/woocommerce/woocommerce/issues/44835, which has more context on the changes

- [x] Rename `Shipping method` to `Delivery`, see 2JyXNimI4oGeJZhgQNZE9V-fi-2957_13784

![CleanShot 2024-03-04 at 14 55 02@2x](https://github.com/woocommerce/woocommerce/assets/99638528/9273fbd8-af77-49d5-96f7-3b34e6f4d6c9)

- [x] Restyle and rename tabs from “Shipping” and “Local pickup” to “Ship” & “Pickup” (picture above)

- [ ] ~"Country" field should be first in the address form. This is especially important if geolocation is off. Many fields in checkout country specific conditions (picture above again)~ → moved to #46513

- [ ] ~Hide address line 2 behind a link. [This is a Baymard recommendation](https://baymard.com/blog/address-line-2) to hide optional and infrequently used fields~ → moved to #46512

![CleanShot 2024-03-04 at 14 55 40@2x](https://github.com/woocommerce/woocommerce/assets/99638528/ddfb588c-ad86-48cc-ac41-b3e8f3dd889c)

**Comment by ralucaStan** [comment]
>  "Country" field should be first in the address form. This is especially important if geolocation is off. Many fields in checkout country specific conditions (picture above again)

@nikkivias we can't control the display of this in the Checkout block. It's the localization service that controls the order of the fields based on the country format.

I suggest we drop this point

**Comment by nielslange** [comment]
@nikkivias Your screenshot shows no prices for Ship and Pickup. Is that intentional and do you want me to remove that option or shall we keep it? The price display can be toggled in the editor:

<img width="1275" alt="Screenshot 2024-03-28 at 20 30 08" src="https://github.com/woocommerce/woocommerce/assets/3323310/7ea7ae75-aac1-4fe8-9d78-ab25557b7ac3">

This is how this section would look like in the frontend:

<img width="646" alt="Screenshot 2024-03-28 at 20 31 46" src="https://github.com/woocommerce/woocommerce/assets/3323310/84be3e85-d0b6-4ace-b9d3-8eb672190b97">

---

As for renaming the main section to `Delivery`, in the Figma design, I see that the sections changed as follows:

<img width="1211" alt="Screenshot 2024-03-29 at 13 44 01" src="https://github.com/woocommerce/woocommerce/assets/3323310/b33417f7-debf-4211-a927-d93b05f8e7c6">

This would require a bigger afford, as we'd need to restructure many of the inner blocks and potentially create additional wrapper blocks. Based on the expected afford, I would not consider this as a quick win. IMO, such a change requires careful planning and execution to avoid that we're introducing regressions. 

@ralucaStan and @pmcpinto What are your thoughts on this?

**Comment by ralucaStan** [comment]
My understanding is that the goal of this ticket is to rename to use the general term "Delivery" for the main section whether or not pickup is active or not. 

This means: 
1. When Local pickup is enabled the Section tile on the `Shipping Method` section should be `Delivery`
<img width="428" alt="Screenshot 2024-03-29 at 09 27 21" src="https://github.com/woocommerce/woocommerce/assets/1628454/7b60c472-66c7-4e57-9637-270f1eb040b1">

2. When pickup is disabled, per @nikkivias 's request the `Shipping Address` section's title should also be `Delivery`.
My concern is here that the text under the title should also be updated.
Another concern is that this section should change back it's title to Shipping Address when Local Pickup is enabled. Because it's something visible when the shopper selects `Ship`.
@nikkivias it looks to me like this change should only apply to the `Shipping Method` section

<img width="431" alt="Screenshot 2024-03-29 at 09 31 07" src="https://github.com/woocommerce/woocommerce/assets/1628454/3271b4c1-dd10-4443-8aba-04dd675be86a">

 
@nielslange do you have any concerns with the things I've outlined above?

--
> This would require a bigger afford, as we'd need to restructure many of the inner blocks and potentially create additional wrapper blocks. 

The diagram is not part of this ticket; if we need to bring in new changes to the block's structure those should be surfaced first in a P2 before moving to development.

**Comment by ralucaStan** [comment]
I've updated my comment with some concerns about renaming the `Shipping Address` section.

**Comment by nielslange** [comment]
> @nielslange do you have any concerns with the things I've outlined above?

Thanks for clarifying this, @ralucaStan. Based on the initial description, it wasn't clear to me that this is the expected outcome.

> The diagram is not part of this ticket; if we need to bring in new changes to the block's structure those should be surfaced first in a P2 before moving to development.

I'm glad to hear that. I just wanted to ensure that I understand the scope of this issue correct.

**Comment by nielslange** [comment]
@ralucaStan I just noticed that you applied the `status: blocked` label to this issue. Is the reason behind that to clarify the textual adjustments, which you mentioned in https://github.com/woocommerce/woocommerce/issues/46013#issuecomment-2026882587:
> When pickup is disabled, per @nikkivias 's request the Shipping Address section's title should also be Delivery.
My concern is here that the text under the title should also be updated.
Another concern is that this section should change back it's title to Shipping Address when Local Pickup is enabled. Because it's something visible when the shopper selects Ship.
@nikkivias it looks to me like this change should only apply to the Shipping Method section

**Comment by ralucaStan** [comment]
Yes

**Comment by opr** [comment]
> @nikkivias we can't control the display of this in the Checkout block. It's the localization service that controls the order of the fields based on the country format.

I think we can override the locale setting for country field if we want to be opinionated about where it appears (which I think we do, I agree with @nikkivias opinion here that country should be first).

I'd suggest doing it in PHP so the priority for the country field is set so it appears first. If this isn't possible then overriding it in JS to re-order the address fields array and bump `country` into the first position should be fine.

For merchants who don't want this we could provide a filter that lets them opt out.

We could also check if the merchant has already applied a custom ordering to their fields (i.e. by [using this filter](https://rudrastyh.com/woocommerce/reorder-checkout-fields.html)), and if so we could leave the order alone and let the merchant's choices remain.

**Comment by pmcpinto** [comment]
> My understanding is that the goal of this ticket is to rename to use the general term "Delivery" for the main section whether or not pickup is active or not.

Correct. The structural changes (eg: moving billing to payments) will be part of a separate effort. 
@nikkivias considering that we have up to 3 sections and different combinations (shipping method, shipping address, shipping options, local pickup options, billing address), I wonder whether we should rename the main section as Delivery after introducing the subsections. 

> @nikkivias Your screenshot shows no prices for Ship and Pickup. Is that intentional and do you want me to remove that option or shall we keep it? The price display can be toggled in the editor:

@nikkivias I think we should keep the "show costs" setting but disable it by default. WDYT?

**Comment by pmcpinto** [comment]
> @nikkivias we can't control the display of this in the Checkout block. It's the localization service that controls the order of the fields based on the country format.

Can you share more details about how the localization service controls the order?

**Comment by opr** [comment]
> Can you share more details about how the localization service controls the order?

In WC Core, the current country has a "locale", the locale contains some of the address fields (e.g. first name, last name etc.) and within those fields there is an option called `priority`. The priority determines what order the fields show in on the shortcode and blocks checkouts.

Developers can control this with a filter such as:

```php
add_filter('woocommerce_get_country_locale', function($locale) {
	$locale['CA']['postcode']['priority'] = 1;
	return $locale;
} );
```
which results in the postcode moving to first place:

![image](https://github.com/woocommerce/woocommerce/assets/5656702/404ac922-8ebe-4141-a486-80bb37bb414d)

Changing the priority to a higher number moves it down (Priority changed to 2000 here):

<img width="609" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/a5fc0f98-aead-4abf-b2a4-c36aa92ef8fc">

**Comment by dominique-vias** [comment]
Hi team, I appreciate the discussion that went on here. Sorry for the confusion! I might have linked this issue to the 'future state' screens that shows the `Delivery` title _and_ the new structure, of which the latter is out of scope. Thanks for clarifying. But also, confirming that your understanding of the new structure is correct!

[I created a separate file](https://www.figma.com/file/2JyXNimI4oGeJZhgQNZE9V/Block-based-Checkout-(Shopper-UX)?type=design&node-id=2957%3A13784&mode=design&t=ETomttaUCTxjRp9A-1) to show the correct screens

I'll answer anything else left unresolved point by point. 

> we can't control the display of this in the Checkout block. It's the localization service that controls the order of the fields based on the country format. I suggest we drop this point

Isn’t the country setting the trigger that would dictate the order of the remaining address fields? For context, this is one of the high-priority issues that was flagged during Baymard QA when geolocation is not available.

> Your screenshot shows no prices for Ship and Pickup. Is that intentional and do you want me to remove that option or shall we keep it? The price display can be toggled in the editor

@nielslange Yes, thanks for catching that. I missed to add that in the to-dos. Agree with @pmcpinto 's comment below— we can turn it off by default. Sometimes shipping prices can change based on location, so it's best not to display any minimums since they haven't entered their address yet at this point. Merchants can toggle it on if their shipping options are simpler.

> it looks to me like this change should only apply to the Shipping Method section

 @raluca thinking about it now, you’re right— we _could_ apply the title change to `Shipping method` only for now, if pickup is not activated.

| Shipping only | With pickup |
| ------------- | ------------- |
| ![Checkout-01](https://github.com/woocommerce/woocommerce/assets/99638528/a46fcb26-19d6-4190-b367-545b7a72f080) | ![Checkout-02](https://github.com/woocommerce/woocommerce/assets/99638528/805c473b-84cd-4601-99d1-842df32deefa)
 
One of the reasons behind the new title is to keep the 1st shipping related section title consistent in all use cases. That being said, if and when we do restructure the blocks to show "subsections" in the future, `Delivery` will be a more appropriate top-level title than `Shipping address`. (see mockups) Thoughts?

| Shipping Address as header 👎🏽  | Delivery as header 👍🏽 |
| ------------- | ------------- |
|  ![01](https://github.com/woocommerce/woocommerce/assets/99638528/a7c005da-1967-4fcd-94ca-e64f1e4a221d) | ![02](https://github.com/woocommerce/woocommerce/assets/99638528/c0516e91-b477-49af-becf-f9010f8aea50)

> My concern is here that the text under the title should also be updated.

Thanks also for pointing this out. One of the changes we proposed but was delayed is to **turn off the section subtexts by default** to make the UI look less busy. The only exception is for Delivery when pickup is activated (see mockup) @pmcpinto is this something we can possibly include sooner if we are only turning off and not removing?

![CleanShot 2024-04-03 at 22 23 45@2x](https://github.com/woocommerce/woocommerce/assets/99638528/3be75d73-faf4-4525-bb02-a35c2e8b5197)

**Comment by nielslange** [comment]
> @nielslange Yes, thanks for catching that. I missed to add that in the to-dos. Agree with @pmcpinto 's comment below— we can turn it off by default. Sometimes shipping prices can change based on location, so it's best not to display any minimums since they haven't entered their address yet at this point. Merchants can toggle it on if their shipping options are simpler.

Thanks for confirming this, @nikkivias, and thanks for providing [updated designs](https://github.com/woocommerce/woocommerce/issues/46013#:~:text=I%20created%20a%20separate%20file).

**Comment by pmcpinto** [comment]
> @nielslange Yes, thanks for catching that. I missed to add that in the to-dos. Agree with @pmcpinto 's comment below— we can turn it off by default. Sometimes shipping prices can change based on location, so it's best not to display any minimums since they haven't entered their address yet at this point. Merchants can toggle it on if their shipping options are simpler.

👍 let's keep the setting, but disabled by default.

> Thanks also for pointing this out. One of the changes we proposed but was delayed is to turn off the section subtexts by default to make the UI look less busy. The only exception is for Delivery when pickup is activated (see mockup) @pmcpinto is this something we can possibly include sooner if we are only turning off and not removing?

I'm still not 100% confident that we should remove the subtext, as it can be useful to provide more context. So, I think we should keep it for now. I don't want to rush this change. Sounds good?

> thinking about it now, you’re right— we could apply the title change to Shipping method only for now, if pickup is not activated.

Why don't we just apply the title change when local pickup is available? IIUC we don't need to change subtexts if we do this.

> Isn’t the country setting the trigger that would dictate the order of the remaining address fields? For context, this is one of the high-priority issues that was flagged during Baymard QA when geolocation is not available.

based on @opr comments, it looks like it's possible to move the country to the top. This will also be useful in the future, if we introduce an address autocomplete feature.

**Comment by dominique-vias** [comment]
> Why don't we just apply the title change when local pickup is available? IIUC we don't need to change subtexts if we do this.

Sorry @pmcpinto that's what I meant. Use `Delivery` when Pickup is activated

**Comment by pmcpinto** [comment]
> Sorry @pmcpinto that's what I meant. Use Delivery when Pickup is activated

@nikkivias thanks for the clarification. So, it looks like we're aligned on the best path forward, right?

**Comment by ralucaStan** [comment]
It was surfaced in  https://github.com/woocommerce/woocommerce/issues/46335 that the secondary address field can also be required. So we are going to pause for now this part of the ticket until we gain more clarity of the impact of the change.

> Hide address line 2 behind a link. [This is a Baymard recommendation](https://baymard.com/blog/address-line-2) to hide optional and infrequently used fields

@nielslange I know you already made some progress there, so maybe it's worth stashing that work, but for now it's safer not to continue working on it. Thank you so much for surfacing #46335
