### ISSUE TITLE
Remove `SelectControl` dependency from blocks

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#46061]
~We need to replace `SelectControl` component using the [ariakit equivalent](https://ariakit.org/components/select).~

`SelectControl` happens to be only used in one place in a deprecated/no longer used block. So once we have removed that block we will also have removed the dependency on `SelectControl` in the project

That will be achieved once https://github.com/woocommerce/woocommerce/issues/44503 is complete.

**Comment by roykho** [comment]
Hi @opr - I am curious if these should be done upstream in Gutenberg instead or am I missing something?

**Comment by opr** [comment]
@roykho as I understand it the Gutenberg components are in the process of being re-written to use Ariakit, however we want to remove the front-end dependency on `@wordpress/components` in WC as that package is designed for use in the editor only, not on the front end, it brings in additional dependencies etc.

We also face the problem that updating `@wordpress/components` in our project may introduce new DOM structures, or class name changes, so keeping our packages up to date could potentially bring breaking changes to third party devs using these.

**Comment by samueljseay** [comment]
@opr I was investigating this today and I don't think we need to do this one specifically, but keen for someone else to validate if I missed anything.

The only use of `SelectControl` I can find is here: https://github.com/woocommerce/woocommerce/blob/06780e4c3b297efcfa280349dc7b6525ac49a6b8/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/variation-attributes/attribute-select-control.tsx#L6

(We only care about imports via the `wordpress-components` alias which is the package used on the front-end).

This block actually had an [attempt to be removed](https://github.com/woocommerce/woocommerce-blocks/pull/11948). It seems it caused [some kind of bug](https://github.com/woocommerce/woocommerce-blocks/pull/12033) that wasn't investigated due to time constraints and so the removal was reverted but the block is still legacy to be removed. We could explore cleaning up the technical debt and seeing if this block could be removed again (investigate further what caused [the bug](https://github.com/woocommerce/woocommerce-blocks/pull/12033) ). That would allow us to remove reference to the old package so it could still be worth doing, but I want to validate that with you first.

But otherwise I wouldn't want to bother re-implementing SelectControl here because the block appears to be legacy and unused.
