### ISSUE TITLE
What is the point to do esc_js on $data which is already rawurlencode-ed?

### ISSUE THREAD

**Issue by edo888** [woothemes/woocommerce#46233]
Hi,

Re-opening as new issue as I do not understand the code complication you use.

What is the point to do esc_js on $data which is already rawurlencode-ed?

Are you saying that you do not already escape properly $this->data fields with esc_js which can contain javascript?

I think wp_json_encode is safe to be placed inside script tags.

Can you provide a minimal example which can cause issue without rawurlencode and esc_js?

Thanks!

_Originally posted by @edo888 in https://github.com/woocommerce/woocommerce/issues/45902#issuecomment-2024185510_

**Comment by senadir** [comment]
It's not clear to me if you're running into an actual issue here with the that code or are you looking to enhance it? I do agree that it can be enhanced and that the `rawurlencode` is probably just extra caution, regardless, it needs to be tested, however, I'd like to understand the driving reason here?

**Comment by edo888** [comment]
Hi,

I'm the developer of [GTranslate](https://wordpress.org/plugins/gtranslate/) plugin for WordPress.

We are parsing JSON objects inside javascript code and translate some of the fields.

Currently I see non-standard code for WooCommerce plugin, so I'm pointing out to you in hopes you can change it back to regular JSON object without the unnecessary complications. I believe wp_json_encode is safe to be used in script tag as pointed earlier in the initial issue description.

Obviously we can add an exception in our code to discover rawurlencoded JSON objects for WooCommerce, but decided to give it a try to point it out to you in hopes that you will simplify your code, so we do not have to code anything special about it.

Thanks!

**Comment by wavvves** [comment]
Hi @edo888, thanks for reaching out.

`wp_json_encode()` in WordPress is primarily designed for encoding data as JSON, not for outputting HTML hence the need to pair it with escaping utilities. This helps mitigate the risk of XSS attacks.

Since this would be best suited for a GitHub discussion and not an issue per se, do you mind [opening one](https://github.com/woocommerce/woocommerce/discussions/new/choose), complete with code references and alternative examples?

I'm closing this issue in the meantime.
