### ISSUE TITLE
Template overrides in block themes

### ISSUE THREAD

**Issue by jonesjayjones** [woothemes/woocommerce#46310]
## Description of the Document Requested

> Provide a detailed description of the topic you'd like to see documented.

How to use Woo Template overrides in block themes

## Why is this Document Important?

> Explain why this topic is crucial and how it can benefit the WooCommerce community.

Using classic override technique does not work

## Potential Content

> If you have an idea about what the new document should cover, list the points or sub-topics here.

Just a simple "how-to"

## Additional Context

> Add any other context, references, or information that can help in the creation of this new document.

**Comment by gigitux** [comment]
Hi! It seems you might be interested in overriding WooCommerce block templates with your custom block theme. If that's correct, you can achieve this by placing your custom versions of the WooCommerce templates within your theme's templates directory. For instance, the aino-theme overrides the default WooCommerce template: https://github.com/elmastudio/aino-theme/blob/6c8eb10a2801c59e353f7e48832a0fd08aabbf0a/templates/single-product.html


In the `templates` folder of the linked theme, you can find:
- single-product.html
- archive-product
- taxonomy-product_cat.html
- taxonomy-product_tag.html


This is the way how to override all the templates with block themes. [Here, you can find the list of all templates that WooCommerce ships](https://github.com/woocommerce/woocommerce/tree/70f49bb389ac9397c09a3fd5e95a446ac374f91f/plugins/woocommerce/templates/templates/blockified). You can read more details in the [WordPress documentation](https://developer.wordpress.org/themes/templates/templates/#how-do-templates-work).

This approach is mentioned in the [WooCommerce documentation ](https://woocommerce.com/document/woocommerce-store-editing/#section-11): do you think that we should improve it?

**Comment by Aljullu** [comment]
Some ideas to improve the documentation (thanks @gigitux for sharing most of them):

* Adding the file names next to the template title.
* Mentioning that: `If your theme comes with any of the above templates, they will automatically override the WooCommerce default ones. For more details, check WordPress documentation.`.
* :point_up_2: and link to the WordPress documentation about it.
* Adding docs about registering specific product/taxonomy templates. Ie: `single-product-cap.html` or `taxonomy-product_cat-clothing.html`.

For now, we won't be adding any documentation related to:

1. Templates hierarchy.
2. For plugins, registering additional templates to the default ones provided by WooCommerce.

That's because we are working on making changes upstream to make those things easier, as currently there is no easy way for plugins or themes to do that.

**Comment by Brianmitchtay** [comment]
In collaboration with @Aljullu I went ahead and added a developer notice to the [Store Editing Doc's WooCommerce Templates section](https://woocommerce.com/document/woocommerce-store-editing/#woocommerce-templates) 

I added the following notice:

> **Developers!** If you’d like to override the default WooCommerce block templates in your custom block theme. You can achieve this by placing your customized versions of the WooCommerce templates within your theme’s `/templates` directory. See all the [block template files that ship with WooCommerce here on Github](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/templates/templates/blockified). Read more details in the [WordPress documentation](https://developer.wordpress.org/themes/templates/templates/#how-do-templates-work).

Generally we try to get information like this in the developer docs at [developer.woocommerce.com/docs](developer.woocommerce.com/docs), so down the line we'll likely still want to add a page there that covers this information in more detail, since developers are more likely to be looking for that information in the dev docs as opposed to the merchant docs. Once that's in place the notice can be updated to point to the dev docs.

As far as dev docs go, the [Template Structure](https://github.com/woocommerce/woocommerce/blob/trunk/docs/theme-development/template-structure.md) doc could be updated with this information about blocks, additionally we could consider an intro doc to go along with the [Classic Theme Developer Handbook](https://github.com/woocommerce/woocommerce/blob/trunk/docs/theme-development/classic-theme-developer-handbook.md) doc.

**Comment by Aljullu** [comment]
Awesome, thank you @Brianmitchtay! I opened a PR adding some docs for theming block themes: https://github.com/woocommerce/woocommerce/pull/48247 and would love if you can take a look. They are under the `plugins/woocommerce-blocks/docs/` folder, so won't be automatically published into developer.woocommerce.com/docs right now, but they will eventually in the future.

**Comment by Aljullu** [comment]
I'm going to close this issue now that #48427 has been merged and the updated docs are public:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/designers/theming/README.md#block-templates

Thanks for all the feedback and contributions!
