### ISSUE TITLE
[New E2E Test]: Verify the page title of the Shop page

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#46431]
### Describe the solution you'd like

In p1712762933174399/1712740857.054269-slack-C7YPW6K40, Atomic shared a list of assertions from their smoke tests that need to be added to our E2E tests. 

For example, Atomic tests for the page title of the `/shop` page below:
```php
$this->deploy_checks['pool1']['https://xxxxxx.xxxxx.yyyyy/shop/'] = array(
    sprintf( '/%s/', preg_quote( '<title>Shop &#8211; Site Title</title>', '/' ) ),
    <h2\s+[^>]*class="woocommerce-loop-category__title"[^>]*>\s*Clothing/i'
```
☝️ This could be added to the `plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-checkout-calculate-tax.spec.js` E2E test. Currently, this test does not check for the Shop page title.

**Comment by juliaamosova** [comment]
The new tests must also cover the specific scenario that is described in this bug: https://github.com/woocommerce/woocommerce/pull/46429

- Using a classic theme, go to Pages and send the Shop page to the Trash.
- Visit the shop in the frontend (ie: /shop).
- Verify the page title is Shop instead of Products or something similar. Important, check the title of the page that is in the <title> tags, that means the title that appears in the tab bar.
