### ISSUE TITLE
Create e2e for coming soon and live modes

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#46568]
## Issue Description

Establish e2e tests for Launch Your Store.

## Acceptance Criteria

- Check live mode / coming soon settings have correct front-end rendering for non-logged in users.
- Check admin users see a banner.

**Comment by psealock** [comment]
Some relevant discussion in p1714449074301459-slack-team-vortex

**Comment by psealock** [comment]
@adrianduffell I just want to confirm one thing: These e2e tests won't be testing the initial setup of the options behind Coming soon / Live and Store only / Entire site. Is that right?

The unit tests in https://github.com/woocommerce/woocommerce/pull/45306 cover this use case and avoiding testing the option setup reduces complexity in the e2e tests because we'd need to either make assumptions about the freshness of the site or ensure `fresh_site` option is set to a particular value. What do you think?

**Comment by adrianduffell** [comment]
> I just want to confirm one thing: These e2e tests won't be testing the initial setup of the options behind Coming soon / Live and Store only / Entire site. Is that right?

@psealock Good callout! It sounds ok not to test the initial setup, as you mention we can't guarantee the initial freshness. I think it would be fine to set the various coming soon settings and check the front-end behaves as expected.
