### ISSUE TITLE
Store Api, OrderSchema returns incorrect "totals"

### ISSUE THREAD

**Issue by thongdoan** [woothemes/woocommerce#46577]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Dear Woocommerce,

When woocommerce_price_num_decimals != 2, i see that all properties in "totals" object incorrect, i think it look like you forget pass wc_get_price_decimals() to all calls of prepare_money_response in get_totals
(In StoreApi/Schemas/V1/OrderSchema->get_totals method (line 338))

### Expected behavior

All properties in "totals" object correct when "woocommerce_price_num_decimals != 2"

### Actual behavior

All properties in "totals" object incorrect when "woocommerce_price_num_decimals != 2"

### Steps to reproduce

Call: /wp-json/wc/store/v1/order/{ORDER_ID}

### WordPress Environment

Woocomerce  8.6.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
That's a good catch, thank you! I did manage to reproduce and yeah `wc_get_price_decimals()` needs to be passed.

It seems that `MoneyFormatter::format` does indeed defaults to `wc_get_price_decimals` when no value is passed, but we're defaulting to 2 always, passing `null` doesn't work as well because in `prepare_money_response` we're always passing `decimals` and it will always override.

Shifting `fromat` to this fixes it and allows up to remove plenty of of `wc_get_price_decimals()` calls, as well as making it easy for people to use it without knowing they need to apss `wc_get_price_decimals`.

```php
$options = [
	'decimals'      => $options['decimals'] ?? wc_get_price_decimals(),
	'rounding_mode' => $options['rounding_mode'] ?? PHP_ROUND_HALF_UP,
];
```

**Comment by thongdoan** [comment]
Thanks you, by the way, I also found another issue, CartSchema generate tax_line.name = tax.label, but in OrderSchema generate tax_line.name = tax.name. (I think tax.label is more useful, tax.name = uppercase(tax.label) )

**Comment by senadir** [comment]
Thanks~ This raises the issue that we should probably unify `get_totals` between Cart and Order endpoints.

**Comment by hsingyuc** [comment]
Could you share how to reproduce the issue?  I tried WooCommerce->Settings->Number of decimals but seem to be getting the correct response.
I'm seeing below if set number of decimals to 3 and the subtotal is 40:
```
 "totals": {
                "line_subtotal": "40000",
                "line_subtotal_tax": "3100",
                "line_total": "40000",
                "line_total_tax": "3100",
```
