### ISSUE TITLE
Blocks: Flaky single product block registration

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#46781]
During the patterns workshop on the meet-up we discovered a bug where blocks would randomly be unregistered. For example when inserting the Single Product block some of its inner blocks wouldn't be registered so it would appear broken upon insertion, or the Product Gallery (Beta) block wouldn't be available for insertion.

I think this is down to [the method we use to contextually register these blocks](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts) and was breaking because we had a slow connection at the time which I don't think would be unusual for merchants.

<img width="447" alt="Screenshot 2024-04-19 at 10 54 51" src="https://github.com/woocommerce/woocommerce/assets/8639742/02597f31-62a5-4053-a3bb-0825a2cab756">

I think best next steps would be to debug these conditional registration methods and try to replicate this with a throttled connection.

Cc @nefeline who helped discover this issue.

**Comment by thealexandrelara** [comment]
Luigi just made me aware of this issue. I was working on a solution for the Product Gallery block that's implemented in this pull request: https://github.com/woocommerce/woocommerce/pull/47636 and it could have the same cause.

The issue is caused by the core/edit-site and core/edit-post stores that we subscribe to not updating their state correctly when you revisit a template without a full page reload. Because of that, the registration method we were using to register this block dynamically wasn't being triggered, and the block wasn't being registered.

The inner blocks of the Single Product block use the `registerBlockSingleProductTemplate` method, which conditionally registers/unregisters blocks based on whether they're inside the Single Product template. The problem is that this isn't very performant because we rely on the WP Data stores, which trigger dozens of times unnecessarily. So, I just [created an issue](https://github.com/woocommerce/woocommerce/issues/47736) to investigate further. Likely, the solution would be to change the logic to match the one used for the Product Gallery block (it uses a "template change detector" to register/unregister dynamic blocks only when triggered). This approach is both more performant and, with the changes in the PR above, more reliable.

**Comment by nefeline** [comment]
@thealexandrelara nice investigation! Sounds like you already did a lot of digging here & I don't wanna step on your toes, so I'm reassigning the issue to you, if you don't mind :) Feel free to progress the work here ;)

**Comment by nefeline** [comment]
> I was working on a solution for the Product Gallery block that's implemented in this pull request: https://github.com/woocommerce/woocommerce-blocks/issues and it could have the same cause.

@thealexandrelara FYI, the link you shared doesn't point to any PR.

**Comment by tjcafferkey** [comment]
Thank you @thealexandrelara and @gigitux. Looking forward to this improvement!

**Comment by thealexandrelara** [comment]
> @thealexandrelara FYI, the link you shared doesn't point to any PR.

Thank you for pointing this out! I just fixed it!

**Comment by tjcafferkey** [comment]
@thealexandrelara wondering how you got on with https://github.com/woocommerce/woocommerce/pull/47636/ was it the same issue as the one described in this issue?

**Comment by thealexandrelara** [comment]
> @thealexandrelara wondering how you got on with #47636 was it the same issue as the one described in this issue?

I'm sorry, Tom. I just saw your comment. Yeah, it seems to be the same issue because the template/post ID is not being updated correctly when relying on the WP Data Stores, which affects basically all blocks using the `registerBlockSingleProductTemplate.`

**Comment by kmanijak** [comment]
Fixed in
- WooCommerce 9.5 - https://github.com/woocommerce/woocommerce/pull/53077
- `trunk` - https://github.com/woocommerce/woocommerce/pull/53108
