### ISSUE TITLE
Possible slow query in AI pattern fetching method

### ISSUE THREAD

**Issue by danielwrobert** [woothemes/woocommerce#46988]
There is a possible slow query coming from the AI pattern fetching method in PatternsHelper.

You can find the initial report here: p7bje6-5L7-p2#comment-8727 (internal), which points to [this method in the archived Woo Blocks repo](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/Patterns/PatternsHelper.php#L78-L95).

Since the monorepo merge, the code [can now be located here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/AIContent/PatternsHelper.php#L32-L49).

Some initial thoughts - I see we're using `WP_Query` and `get_posts()` together:

```php
$query = new \WP_Query( $arg );

$posts = $query->get_posts();
return $posts[0] ?? null;
``` 

Would it be better to forego instantiating the `WP_Query` class and passing the `$arg` array directly to `get_posts()` instead?

```php
$posts = get_posts( $arg );
return $posts[0] ?? null;
```

**Comment by nefeline** [comment]
Opened #46999 to solve this.

A few details: on the linked P2, @vedanshujain mentioned that:

> [https://github.com/woocommerce/woocommerce-blocks/blob/03c7cfacb225be345ab30240ef483476c080bae8/src/Patterns/PatternsHelper.php#L82](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/blob/03c7cfacb225be345ab30240ef483476c080bae8/src/Patterns/PatternsHelper.php#L82):
Query from this function also got triggered on order completion or on the first page load after order creation so I added return null; to the start of function

This happens because `get_patterns_ai_data_post` is triggered on pattern registration (which is hooked on `init`):

<img width="1237" alt="Screenshot 2024-04-27 at 12 19 04" src="https://github.com/woocommerce/woocommerce/assets/15730971/5e9512c1-ee4b-4c78-9bf7-c2594660452c">

@danielwrobert regarding:

> Would it be better to forego instantiating the WP_Query class and passing the $arg array directly to get_posts() instead?

Yes, I agree! When we instantiate `\WP_Query`, we create a full query object that allows us to use various methods and properties, making it ideal for more complex queries and scenarios where we need to access multiple aspects of the query after it has run.
This method is slightly heavier when compared with `get_posts` because it involves creating an object that can handle pagination, multiple loops, and more detailed condition checks. 

get_posts() is typically lighter and faster for straightforward scenarios where we only need to retrieve posts without further manipulation of the query object (which is the case here).

With that said, I've updated the `get_patterns_ai_data_post` method to rely on `get_posts` instead.

Additionally, since we are now relying on the `'woocommerce_blocks_allow_ai_connection'` option to conditionally fetch the ai_data_post, I've enabled autoload for this option, since it is very small and triggered on `init`, loading into memory can help us improve performance.
