### ISSUE TITLE
Update the `pnpm clean` command to not include the `pnpm i` step

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#47028]
The `pnpm clean` command was introduced to help with node_modules corruption and avoid fresh clone. see  https://github.com/woocommerce/woocommerce/pull/36302 

## Problem
It includes the in the `pnpm i`  command:  `rimraf -g '**/node_modules' '**/.wireit' && pnpm store prune && pnpm i`;  

## Expected result
This install part of the command is not an expected part of a clean command and it should be run separately. 

It’s a common expectation to  install dependencies and then build a project as separate steps.

**Comment by ObliviousHarmony** [comment]
It's worth noting too that our `clean` script doesn't remove build artifacts. Instead of adding a more aggressive `rimraf` I would suggest we add a `clean` to every project. This script would remove `node_modules`, `.wireit`, and any artifacts, build or otherwise, created by that project. This lets us define what each project needs to clean very granularly and even clean them individually if necessary. We can then replace the top-level `clean` with one that calls it recursively on all of the children.
