### ISSUE TITLE
Publish dropdown and switch to draft: add Tracks events

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#47221]
**Description:** we have the instrumentation to understand when a product is scheduled, copied, or moved to the trash. However, we don't know how many users interact with the dropdown. We should track this interaction to have a full picture of the flow.  

I've also noticed that we don't track when the user switches a product to a draft.

**Acceptance criteria:**
- [ ] Add a new event that fires when the user interacts with the publish dropdown: 
Event name: `wcadmin_product_publish_dropdown_click`
Event property: `option`: schedule | duplicate | trash
- [ ] Add a new event that fires when the user clicks "Switch to draft": `wcadmin_product_switch_draft`

**Comment by octaedro** [comment]
Hi @pmcpinto,

I'm currently working on this issue and wanted to confirm the events we need to track with you. We are currently recording the following events:

- When the user selects `Copy to a new draft` -> Event: `product_copied_to_draft` 
- When the user selects `Move to trash` -> Event: `product_delete` 
- When the user selects Schedule product (we are not recording that selection); we record the event `product_schedule` after the user chooses a DateTime.

Should we also record when the user clicks the arrow to open the dropdown? And should we track when `Schedule product` is selected in the dropdown, before a date is picked?

Additionally, we don't have an event for _Switch to draft_. I will add this. We are already recording the event `wcadmin_product_edit` when we save the product, but if you think it's worth it, I can also add an event for pressing `Save draft`.

**Comment by pmcpinto** [comment]
Hey Fernando,

> Should we also record when the user clicks the arrow to open the dropdown? 

`wcadmin_product_publish_dropdown_click` should fire when the user selects one of the dropdown options

<img width="473" alt="Captura de ecrã 2024-05-09, às 15 18 29" src="https://github.com/woocommerce/woocommerce/assets/3380168/735aaf23-ff3f-445b-8afc-ebd1054cddff">

Adding a `wcadmin_product_publish_dropdown_open` makes sense to track when the user opens the dropdown.

> And should we track when Schedule product is selected in the dropdown, before a date is picked?

Can you elaborate on this? It should be covered by `wcadmin_product_publish_dropdown_click` option: schedule, right?

> We are already recording the event wcadmin_product_edit when we save the product, but if you think it's worth it, I can also add an event for pressing Save draft.

I think that makes sense, as the edit event is fired in other situations. Thanks.

**Comment by octaedro** [comment]
Hello @pmcpinto,

> `wcadmin_product_publish_dropdown_click` should fire when the user selects one of the dropdown options.

We were recording the events [I mentioned](https://github.com/woocommerce/woocommerce/issues/47221#issuecomment-2102663692) in my comment and sending some properties with product data, instead of the selected `option`. I will change the code to only send the event name `wcadmin_product_publish_dropdown_click`, with the property: `option` (schedule | duplicate | trash). It will be triggered after selecting an option in the dropdown.

> Adding a `wcadmin_product_publish_dropdown_open` makes sense to track when the user opens the dropdown.

I will add it!

> Can you elaborate on this? It should be covered by wcadmin_product_publish_dropdown_click option: schedule, right?

We are currently opening a `Schedule product` date picker (like below) and recording the event after pressing the `Schedule` button.

![Screenshot 2024-05-09 at 1 51 10 PM](https://github.com/woocommerce/woocommerce/assets/1314156/2c87cde7-f7c9-43b6-893c-3f3b03aa822f)

If it ok with you I'm going to keep that event (triggered after pressing the `Schedule` button) and I'll record a new one after selecting `Schedule publish` in the `Publish` dropdown.

**Comment by pmcpinto** [comment]
@octaedro sorry, I took a 2nd look at this request. Let's do this:

- We keep `wcadmin_product_copied_to_draft` and `wcadmin_product_delete`.
- We add `wcadmin_product_schedule_publish` to track when the user selects the dropdown option.
- We add `wcadmin_product_publish_dropdown_open` to track when the user opens the dropdown.

Let me know if you agree with this and I'll update the AC.
