### ISSUE TITLE
Add disabled state to save button on all settings tabs

### ISSUE THREAD

**Issue by adrianduffell** [woothemes/woocommerce#47393]
In https://github.com/woocommerce/woocommerce/pull/47316, we disable the save button on the site visibility tab until a change is made. This is a follow-up to apply the same behavior to all settings tabs.

## Acceptance Criteria

* If the tab has a "Save changes" button, disable on initial page load.
* When a field changes, the button should cease being disabled.
* Create a GitHub Discussion to advise about the behavior change.
* Create an internal call for testing.
* Add a developer advisory about the change for the WooCommerce release

**Comment by adrianduffell** [comment]
> When a field changes, the button should cease being disabled.

I think we could use a variation of the [logic to show the exit confirmation](https://github.com/woocommerce/woocommerce/blob/db804f4193559aa5a4379ce9a6c501a4ff3a3675/plugins/woocommerce/client/legacy/js/admin/settings.js#L93-L122) (seen in https://github.com/woocommerce/woocommerce/issues/46573). However, we'll need to ensure custom input UIs also trigger a change. 

The shipping settings seems to already have this behavior already, however the local pickup settings is missing it:

https://github.com/woocommerce/woocommerce/assets/9312929/cb16c705-8733-4967-8b7b-ce62b3b15a45

**Comment by psealock** [comment]
@adrianduffell Here is an interesting case. On the Payments screen, you can toggle on/off various payment options. This interaction kicks off an Ajax request where the setting is saved. Technically, once toggled there is no need to click Save. However, we are introducing a weird concept here because the merchant may not know that and the Save button is disabled. I suppose this issue existed already, but now may be more apparent if merchant believe they can't save. I suppose we could enable the Save button on toggle interaction, but now we are suggesting the merchant needs to click Save. What do you reckon?

<img width="863" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/d0ad5f07-df13-4c3a-8d2e-32cb66dd4953">

**Comment by adrianduffell** [comment]
> Here is an interesting case.

@psealock Hmm, that's a tricky one 🤔 I wonder if it is viable to remove the save button on this altogether? I feel like the presence of it makes the ajax save unexpected. However, it looks like the save button is still needed to persist the changes to the sort order (made using drag and drop). If the save button is removed, there would need to be an ajax save for this too.

Perhaps the solution is to disable the save button, but show a snackbar when a payment option is toggled. It could say `<payment option> successfully <enabled / disabled>`, e.g. `Cash on delivery disabled successfully`. Hopefully that would help to inform the user about the ajax saves and clue them in why the save button is still disabled?

**Comment by adrianduffell** [comment]
> show a snackbar when a payment option is toggled

Thinking about it more, it's probably difficult to use the gutenberg snackbar component from jQuery 🫠  As an alternative, a regular notice could maybe do the trick. Something like:

<img width="1792" alt="payments toggle feedback" src="https://github.com/woocommerce/woocommerce/assets/9312929/40927cac-d670-4eb9-a3d8-5047c156845b">

**Comment by psealock** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/47444
