### ISSUE TITLE
Remove feature flagging of 'experimental block styling' options that were behind isFeaturePlugin

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#47693]
**Issue Description:**

~Right now we use [isFeaturePlugin](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/button/index.tsx#L17) to determine if blocks should enable experimental support for block styling. Because of the merge to the monorepo and change of how we handle `WOOCOMMERCE_BLOCKS_PHASE`, these features cannot be used right now.~

~As part of the goal of https://github.com/woocommerce/woocommerce/issues/43073 to remove `WOOCOMMERCE_BLOCKS_PHASE` this task is to migrate this experimental block styling to use a setting in `FeaturesController` to determine if it can be used.~

After some investigation @gigitux found that the experimental properties we're using either:

1. Have a stable version we can migrate to
2. Will be made stable very soon
3. Are used already in blocks shipped with Gutenberg so can be considered stable enough anyway

On the basis of that, and also because we discovered these features had already been inadvertently enabled in production for a while now, we decided a better approach would be to remove `isFeaturePlugin` altogether because it is not actually doing anything (it's always true) and because we don't need to gate these features any more anyway.

**Comment by kmanijak** [comment]
A side quest of this issue could be to verify how many of the "Feature Plugin" features are still experimental and should be behind the flag. The initial reason they were hidden behind the flag was some features/selectors were experimental. My impression is there may be a bunch that are stable already and could be safely exposed to users.

EDIT: I went ahead and created a cooldown issue: https://github.com/woocommerce/woocommerce/issues/47698

**Comment by samueljseay** [comment]
@kmanijak do you think it's still worth having the concept of an experimental setting for this? I'd be tempted not to implement this for example, if none of them needed to be behind a flag.

I notice some of the block styling settings pass in some kind of property prefixed with `__experimental` would that be considered enough to keep it behind an experimental setting?

**Comment by kmanijak** [comment]
> I notice some of the block styling settings pass in some kind of property prefixed with __experimental would that be considered enough to keep it behind an experimental setting?

@samueljseay , that's the case. Some of the properties are/were experimental in Gutenberg and as they were potentially subject to change, we only used them (and exposed them to users) as plugin features. I think that as long as they're still experimental in Gutenberg they may change and hence exposing them directly in Core is potentially fragile.

Another case is some styling features are stable but we use `__experimentalSelector`. Example: [`woocommerce/product-button`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/button/index.tsx#L48C3-L48C25). I don't remember exact details (I think @Aljullu knows more details) but because of the experimental selector the whole `supports` section is behind feature flag and unless `__experimentalSelector` has been stabilized in Gutenberg I think we should keep it behind some sort of flag.

> @kmanijak do you think it's still worth having the concept of an experimental setting for this? I'd be tempted not to implement this for example, if none of them needed to be behind a flag.

I agree! If only the features are stable in Gutenberg I'd remove the flags completely! Unless you mean something else?

**Comment by Aljullu** [comment]
> @samueljseay , that's the case. Some of the properties are/were experimental in Gutenberg and as they were potentially subject to change, we only used them (and exposed them to users) as plugin features. I think that as long as they're still experimental in Gutenberg they may change and hence exposing them directly in Core is potentially fragile.
> 
> Another case is some styling features are stable but we use `__experimentalSelector`. Example: [`woocommerce/product-button`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/button/index.tsx#L48C3-L48C25). I don't remember exact details (I think @Aljullu knows more details) but because of the experimental selector the whole `supports` section is behind feature flag and unless `__experimentalSelector` has been stabilized in Gutenberg I think we should keep it behind some sort of flag.

Yup, I have little to add as it's exactly as you described. :smile: We were feature-gating those properties as they were relying on experimental APIs in Gutenberg, so we wanted to lean on the cautious side in WooCommerce core and not expose something that might break or we might need to stop supporting in the future.

Regarding `__experimentalSelector`, that impacts all other styling properties AFAIK as it changes which selector is used as the target for the styles, that's why using `__experimentalSelector` in a block means we needed to feature gate all styling properties.

**Comment by samueljseay** [comment]
@kmanijak @Aljullu thanks for the clarification, It sounds like the feature flag is still needed. I have a proposed solution to submit soon so I'll check through all the usages of the existing conditional at the same time and can pull y'all in for review 😄

**Comment by samueljseay** [comment]
Finished in https://github.com/woocommerce/woocommerce/pull/47866
