### ISSUE TITLE
Replace Country/State and custom field inputs with native select

### ISSUE THREAD

**Issue by opr** [woothemes/woocommerce#47757]
This issue is a blocker to https://github.com/woocommerce/woocommerce/issues/46357

Currently, these fields are rendered as a combobox, however it is unsuitable and keeps us on an old version of `@wordpress/components`.

The main reason we feel the combobox is not suitable for these fields is its unpredictability when it comes to handling user input and autocomplete. Address autocompletion is a very important thing to get right in the checkout flow and having a degraded experience is likely to harm conversion rates. The main issues with autocomplete are:

- Chrome autocomplete works differently to 1Password autocomplete
- There is no good way to check if a browser autocomplete is being used or if the user was typing
- When using autocomplete, this bug (https://github.com/woocommerce/woocommerce/issues/44653) occurs where United States addresses keep the dropdown list open, this is because there are two matches for United States (United States (US) and United States (US) Minor Outlying Islands)

A more suitable and accessible alternative is simply rendering a native `select` input for these fields.

**Comment by LordSimal** [comment]
Sooooo.... did this release with the just published 8.9.3 security update without any further notice?

Because all our checkout country select inputs look weird now (because select2 is not initialized/loaded anymore). Fortunately it still works and doesn't prevent users from checking out.

---

We fixed it ourself since we also had some other theme adjustments on our side. The problem here was the fact, that we already had 
```
wp_dequeue_style( 'select2' );
wp_dequeue_script( 'select2');
wp_dequeue_script( 'selectWoo' );
```
and it was missing
```
wp_deregister_script('selectWoo');
```

therefore the JS select replacement was "kind of" initialized but not really to 100%.

**Comment by samueljseay** [comment]
@LordSimal No we have not released anything to change select2, and this is for the block based cart and checkout. Also we won't release the work we're doing now in a patch or fix release. 

If you're seeing something breaking please open an issue :)

**Comment by kodomastro** [comment]
This is very important because current country/state select is very annoying and unpredictable. We have cases when customers abandon checkout because they are not able to select a proper country.
