### ISSUE TITLE
My website menu not working on mobile

### ISSUE THREAD

**Issue by thaheem110** [woothemes/woocommerce#47790]
I added cloudflare on [my webiste](https://3dversedesign.com/). Now navigation menu three dots not working.
what is this issue?

**Comment by nielslange** [comment]
Thanks for reaching out, @thaheem110. On my end, when looking up https://3dversedesign.com/ in the mobile view, I do see the mobile menu and it works as expected:

<table>
<tr>
<td valign="top">
<img width="367" alt="Screenshot 2024-05-24 at 15 16 56" src="https://github.com/woocommerce/woocommerce/assets/3323310/68a5198f-d5c5-4897-9c4c-c9a86c472024">
</td>
<td valign="top">
<img width="374" alt="Screenshot 2024-05-24 at 15 17 18" src="https://github.com/woocommerce/woocommerce/assets/3323310/4e1393b0-ae27-43cf-acb7-3faa96fa18a1">
</td>
<td valign="top">
<img width="368" alt="Screenshot 2024-05-24 at 15 17 40" src="https://github.com/woocommerce/woocommerce/assets/3323310/064c6d83-ef6f-49df-a3f5-073b628b02ac">
</td>
</table>

I do not see the three dots, but three lines. Have you applied any changes meanwhile and is the issue solved? I also wonder in how far this issue is related to WooCommerce. Could you clarify this, in case the issue still exists on your end?
