### ISSUE TITLE
Tweak the appearance of the 'Button only' style in the Product Search block

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47892]
The Product Search block has a 'Button only' style in the toolbar, which doesn't seem to work properly. When the block is selected, we still show the input field, but in an odd, minimized state. Ideally, the input wouldn't be shown at all.

<img width="381" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/bbea66fb-5147-4156-9864-dd9a05afe16a">

I also noticed a display issue on the front-end where the search button is cut off on the sides if the block's width isn't set to 100%.

<img width="153" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/e95fec96-695c-4749-8508-05a5a2d7bf20">

<img width="202" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/8d4c763f-9d5c-4f1d-b984-3cbf1305570b">

**Comment by octaedro** [comment]
Hi @jarekmorawski,

I have a couple of questions regarding these comments:

> The Product Search block has a 'Button only' style in the toolbar, which doesn't seem to work properly. When the block is selected, we still show the input field, but in an odd, minimized state. Ideally, the input wouldn't be shown at all.

Just to confirm, the suggestion here is to mimic the fronted behavior in the backend, right? In other words, to only show the input when clicking the button, not when the block is selected.

> I also noticed a display issue on the front-end where the search button is cut off on the sides if the block's width isn't set to 100%.

I couldn't reproduce that error. The button looks fine with widths smaller than 100%. As long as the width is greater than 10%, the icon displays properly.


https://github.com/user-attachments/assets/7bd808e1-02b7-4af6-af39-aad9c52bad75

However, when using the Search text and setting the width to 25%, the button looks odd when extended.

https://github.com/user-attachments/assets/d43f05f4-615a-499f-92e0-6570492cac99

I think this is expected, given that the button size is quite large for a width of 25%.

**Comment by j111q** [comment]
> the suggestion here is to mimic the fronted behavior in the backend, right? In other words, to only show the input when clicking the button, not when the block is selected.

Yes, this is also what I'd expect to see in the Site Editor. Input is hidden when the block is selected.

> when using the Search text and setting the width to 25%, the button looks odd when extended.

Hmmm yeah this is a tricky one. 🤔 
Can we set a min-width somehow? So that at it's absolute smallest, this is how it should appear?

<img width="474" alt="image" src="https://github.com/user-attachments/assets/cd5e5af9-cfc9-4502-8262-942b781c5209">

So the whole `Search` text can be seen, and the `Search products` text is cut off but there's text truncation with `...`. 

It might mean that, at certain widths, it's actually wider than 25%, but to me it makes sense that this has a min-width that takes precedence. What do you think though?

**Comment by octaedro** [comment]
This issue has been moved to the Gutenberg repo [#65344](https://github.com/WordPress/gutenberg/issues/65344).
