### ISSUE TITLE
Clean up the Product Search block's controls

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47890]
Most of the Product Search block's layout-related settings live in the toolbar, while there's nothing in the Inspector. The toolbar is supposed to house only the most commonly used tools and it's unexpected to see such options there. Let's move them to the Inspector and clean up the UI a bit to make designing the perfect product search field a bit easier.

<img width="747" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/08f15590-0963-4d3e-978b-090a0ff46609">

**Comment by octaedro** [comment]
Hi @j111q,

I'm working on this issue, and I have a couple of questions about the design:

![Screenshot 2024-09-10 at 2 12 04 PM](https://github.com/user-attachments/assets/33a19c67-82ee-4165-8690-4142afde443b)

- All the buttons I'm adding in the inspector refer to options in the toolbar. However, I couldn't find the `Button Style` options. Do you know what it's referring to? If it's a new option, I suggest tackling that in a follow-up PR.

- Should the `Button position` option be visible when the radio button `Button only` is selected? Looking at the design, I see it is visible, but I think it shouldn't because it's not an option that affects anything related to the `Button only`.

**Comment by octaedro** [comment]
@j111q  There is another problem related to the designs since it is not possible to add the controls at the beginning of the `Styles` tab.
Is it ok if we add them at the end? They would look like this
![Screenshot 2024-09-10 at 5 13 57 PM](https://github.com/user-attachments/assets/6f68c547-be3e-41c6-8017-d2bfaddcfde2)

**Comment by j111q** [comment]
Hi @octaedro  😊  thanks for the ping

> All the buttons I'm adding in the inspector refer to options in the toolbar. However, I couldn't find the Button Style options. Do you know what it's referring to? If it's a new option, I suggest tackling that in a follow-up PR.

Hmm yes I don't think it is an option in the toolbar, I think it's just to align with the existing Fill/Outline style option that exists for the regular `Button` block in Core. Follow up PR sounds good to me 👍 

> Should the Button position option be visible when the radio button Button only is selected?

Good catch, I agree with you - it shouldn't be visible when `Button only` is selected.

> Is it ok if we add them at the end? They would look like this

Yeah I think that's fine too 👍
