### ISSUE TITLE
Add a proper configuration for the e2e tests with different envs

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#48140]
The daily e2e tests were migrated from the old workflows with https://github.com/woocommerce/woocommerce/pull/48101. 
They are now configured with the new CI setup, in `packages.json` and running via the generic `ci.yml`.
The proper configuration for each environment was not completed though. Example: the tests project with woocommerce-payments plugin installed only includes the `basic.spec.js`. We need to configure the relevant tests to run on these.

More specifically, go through each `playwright.config.js` in `tests/e2e-pw/envs/*` and configure the  `testMatch` or `testIgnore` property in the project.

**Comment by lanej0** [comment]
Bit of a long comment, because I'll try to hit each of the different envs:

## Default

Keep running everything

## Gutenberg nightly, stable

- basic.spec.js
- customize-store/*
- merchant/products/*
- merchant/create-cart-block
- merchant/create-checkout-block
- merchant/creat-page
- merchant/create-post
- merchant/create-woocommerce-blocks
- merchant/create-woocommerce-patterns
- merchant/launch-your-store
- merchant/page-loads
- merchant/product-*
- shopper/wordpress-post.spec.js

## WooCommerce Payments, PayPal Payments

- basic.spec.js
- admin-analytics/*
- merchant/customer-payment-page
- merchant/order-refund
- shopper/*

(We might need to do some changes here to make some of the tests compatible with multiple payment options)

## WooCommerce Services (Shipping & Tax)

- basic.spec.js
- admin-analytics/*
- merchant/* (except settings-shipping, settings-tax, create-shipping-zones, create-shipping-classes
- shopper/*

**Comment by veljkho** [comment]
I would do this with tags as a new feature in PW. Simplest solution
