### ISSUE TITLE
[CYS] Avoid to use `edit-site` CSS classes

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#48377]
> It's unfortunate that the Customize Store UI is using these `edit-site` CSS classes, as they are not a part of the `edit-site` public API and can change. I'm testing the Woo plugin on a plain WP 6.5.4 site, without the latest Gutenberg, and see two bugs:
> - the slide-from-left and slide-from-right animations don't work
>- when the browser window has low height, the sidebar should be scrollable, but it isn't. Here I can't scroll to "Choose your footer" and beyond:

><img width="799" alt="Screenshot 2024-06-10 at 18 50 55" src="https://github.com/woocommerce/woocommerce/assets/664258/7977acad-f8f4-4edd-a030-0e44c3ed612c">

>The reason is that WP 6.5.4 doesn't yet have the `edit-site-sidebar__*` CSS changes from https://github.com/WordPress/gutenberg/pull/60849.

> I think it's better to define your own classes. Or reuse something from WP Components if possible.

_Originally posted by @jsnajdr in https://github.com/woocommerce/woocommerce/pull/48312#discussion_r1633556578_

As @jsnajdr mentioned, we should avoid to use `edit-site` CSS classes given that they are not part of the `edit-site` public API

**Comment by Aljullu** [comment]
@gigitux if I'm understanding it right, we are using `.edit-site-` classes in three places:

* Customize Your Store
* Launch Your Store (thanks for pointing it out to me! 😄)
* The new product list

As part of this issue, should we work towards stopping to use them in all these places? Or should the changes be limitted to CYS and LYS?

I'm also a bit confused about the duplication of components. Ie, we have a [`SiteHub` component](https://github.com/woocommerce/woocommerce/blob/8de9cd3b360a6b533ed70da1141adbd3ba8b8b25/plugins/woocommerce/client/admin/client/customize-store/assembler-hub/site-hub.tsx) which apparently is used by CYS and LYS, and another [`SiteHub` component](https://github.com/woocommerce/woocommerce/blob/8de9cd3b360a6b533ed70da1141adbd3ba8b8b25/packages/js/product-editor/src/products-app/site-hub/index.tsx) which is used by the new product list. They are similar but not exactly the same. So my question/suggestion is:

1. If we want them to have the same features, could we consolidate those components into one?
2. If not, does it sound good to name them differently and use different class names?

**Comment by gigitux** [comment]
> The new product list

The new product list is only an experimental way to test the dataviews in WooCommerce. The code isn't for production purpose, so I would not focus on this.

> Or should the changes be limitted to CYS and LYS?

As I aforementioned, I think that we should focus only on CYS and LYS.

> If we want them to have the same features, could we consolidate those components into one?

This is a good idea. I would search all the components that we shared across the two projects and create a dedicated issue for tackling this work. For instance, `ResizableFrame` is another component that it is shared across the two projects:


https://github.com/woocommerce/woocommerce/blob/bc14b89882c15229088c86c888fecc248683440e/plugins/woocommerce/client/admin/client/launch-your-store/hub/main-content/pages/site-preview.tsx#L18-L19


I don't know if there are others or no.

**Comment by Aljullu** [comment]
> As I aforementioned, I think that we should focus only on CYS and LYS.

Thanks, it makes sense, @gigitux!

---

As I get deeper into this, I'm facing some challenges. Every time I rename a class, the layout breaks and I need to investigate which CSS rule from that element or any of its descendants is causing the layout break, then copy-and-paste the required CSS rules from the Gutenberg CSS file into ours with the new class name. After spending several hours on this (https://github.com/woocommerce/woocommerce/pull/52324/)... I'm not sure this is the way to go. 😓 

My understanding of the current situation is that:

1. We copy-and-pasted some components from Gutenberg into our codebase.
2. However, we didn't copy-and-paste the associated CSS files. So the components are generated from our JSX code which is "locked" to the version of the component we copy-and-pasted, but we rely on the CSS from Gutenberg, which will update in each new version. (That's why we want to move away from the CSS classes from core, right?)
3. We also wrote some CSS rules that override some of the CSS rules from the Gutenberg files.

If that's the case, I'm thinking of taking a different approach:

1. I will copy-and-paste the CSS from core.
2. I will make it so we only load our copy of the CSS instead of the one from core.
3. Then, if I'm not missing anything, it should be easy to rename the CSS classes as it will simply be a matter of search & replace. This will also make it so there are no conflicts.
4. Finally, we could eventually unify the original CSS with our overrides.

That means our components will completely diverge from the ones from Gutenberg. As long as they aren't published and we can't safely use them, I think that's the only way to make them future-proof so they don't break with new updates.

@gigitux I would appreciate your feedback to make sure that (1) I understand the problem right and (2) my proposed approach makes sense. Thanks again for your help! 🙏 

cc @mdperez86 in case you have some thoughts on this as well.

**Comment by gigitux** [comment]
@Aljullu you got the issue! 

Your approach seems effective; however, before proceeding, I recommend double-checking the CSS loading method. Currently, it appears to be loaded from the WordPress Core, but we might consider importing the stylesheet directly from the npm package installed here: [WooCommerce package.json](https://github.com/woocommerce/woocommerce/blob/0535d366aca8bad933e0cfad572783f135077495/package.json#L80).

WDYT?

**Comment by Aljullu** [comment]
> Your approach seems effective; however, before proceeding, I recommend double-checking the CSS loading method. Currently, it appears to be loaded from the WordPress Core, but we might consider importing the stylesheet directly from the npm package installed here: [WooCommerce package.json](https://github.com/woocommerce/woocommerce/blob/0535d366aca8bad933e0cfad572783f135077495/package.json#L80).

If we import the CSS file from the NPM package, we will solve the issue of breakages on updates (because we control when the package gets updated). But it will still use the `.edit-site` class names, which might cause collisions in the future if the Gutenberg CSS file gets loaded on the screen for any reason.

So I lean towards copy-and-pasting it and replacing the class names in the CSS file and our components. I'm thinking maybe simply adding a prefix before the class name (ie: `.woocommerce-edit-site`) to avoid conflicts, but so it's easy to understand the relation with the original CSS. Does that sound like a good plan?

**Comment by gigitux** [comment]
> If we import the CSS file from the NPM package, we will solve the issue of breakages on updates (because we control when the package gets updated). But it will still use the .edit-site class names, which might cause collisions in the future if the Gutenberg CSS file gets loaded on the screen for any reason.

True! Great observation! 

> So I lean towards copy-and-pasting it and replacing the class names in the CSS file and our components. I'm thinking maybe simply adding a prefix before the class name (ie: .woocommerce-edit-site) to avoid conflicts, but so it's easy to understand the relation with the original CSS. Does that sound like a good plan?

It makes sense! 🚀
