### ISSUE TITLE
[Enhancement]: Make WC_Logger_Interface a Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by axi** [woothemes/woocommerce#48582]
### Describe the solution you'd like

Existing `WC_Logger_Interface` is already compatible with `Psr\Log\LoggerInterface`.
Making `WC_Logger_Interface` extend `Psr\Log\LoggerInterface` would allow `WC_Logger` to be used in other libraries that follow [PSR-3](https://www.php-fig.org/psr/psr-3/).

The one I have in mind in this case is PHPMailer. It makes a good candidat to explain my case because it's included in WordPress :-)
```php
class PHPMailer
{
    /**
     *
     * @var string|callable|\Psr\Log\LoggerInterface
     */
    public $Debugoutput = 'echo';
}
```
But that could apply to all libraries.

I don't think about any counter-argument against that but I'm interested in knowing if there's one.

I could work on a PR if needed. Wouldn't that be nice ?
```php
use  Psr\Log\LoggerInterface;

interface WC_Logger_Interface extends LoggerInterface {
    ....
}
```

**Comment by coreymckrill** [comment]
Hi @axi, it's an interesting idea!

> I could work on a PR if needed. Wouldn't that be nice ?

We'd be happy to take a look at a PR for this. I think that would give us a better idea of the potential pros/cons.

Of note, in the case of PHPMailer anyway, is that you can pass in [a callable](https://github.com/WordPress/WordPress/blob/95971e18b13c178017dde638824da04d2b082f93/wp-includes/PHPMailer/PHPMailer.php#L418-L422) too, and although `WC_Logger->log()` has the parameters swapped (level first instead of string), you could pass in a wrapper function.

**Comment by axi** [comment]
@coreymckrill 
Yes, I realised that :-)
```
            $phpmailer->Debugoutput = static function (string $string, int $debugOutputMode): void
            {
                wc_get_logger()->debug(
                    $string,
                    ['source' => 'mail_logger']
                );
            };
```

I'll try a PR

**Comment by axi** [comment]
Hum,

thinking about the PR, I was first trying to add it in /lib/packages but I realised those packages are handled by mozart and prefixed, meaning it won't be a `Psr\Log\LoggerInterface` but a `Automattic\WooCommerce\Vendor\Psr\Log\LoggerInterface` which doesn't fulfill the idea of this PR.

But if we don't prefix it, we will face conflicts with other plugins/packages that might use a different version of the package.

Any direction ?

**Comment by Konamiman** [comment]
In order to keep things as simple and non-disruptive possible, and although it's not the most "elegant" solution, I think that extensions willing to use WooCommerce's logger under the `Psr\Log\LoggerInterface` interface are better off writing their own wrapper class, like this:

```php
use Psr\Log\LoggerInterface;

class PsrLoggerWrapper implements LoggerInterface
{
	private $logger;

	function __construct(WC_Logger_Interface $logger = null)
	{
		$this->logger = $logger ?? wc_get_logger();
	}

	public function error(string $message, array $context = []): void {
		$this->logger->error($message, $context);
	}

	//...and similarly for the other methods.
}

```

...then `$logger = new PsrLoggerWrapper();` or `$logger = new PsrLoggerWrapper($my_woo_logger);`.

**Comment by axi** [comment]
I think you're right @Konamiman .
Here is a gist https://gist.github.com/axi/779b9892aaeab204699c4f01946bf35b
