### ISSUE TITLE
[Enhancement]: Add fields in checkout page

### ISSUE THREAD

**Issue by Davide2892** [woothemes/woocommerce#48617]
### Describe the solution you'd like

Possibility to extend the form on the checkout page with additional fields also displayed in the order summary email and in the order card in the backend.

**Comment by senadir** [comment]
This is currently doable via code, do you want to do it via UI?

**Comment by Davide2892** [comment]
HI,

after adding the comment I found how to do it via code.

But for those who are not familiar with the code it might be useful to have this feature directly on the UI.

**Comment by mikejolley** [comment]
Hi @Davide2892 Glad you solved this.

For anyone else stumbling across this ticket, the documentation for extending block checkout fields can be found here:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/additional-checkout-fields.md

This is a developer facing API. Its likely that once this matures a UI for doing this will be added to the Checkout Field Editor extension. 

I will close this issue since there is nothing actionable right now. Thanks
