### ISSUE TITLE
[DOC-REQ] Migration Docs for Input Overriding like in Classic WooCommerce Checkout

### ISSUE THREAD

**Issue by benyaminl** [woothemes/woocommerce#48864]
## Description of the Document Requested

Hello, I'm a user of Woongkir https://github.com/sofyansitorus/Woongkir, and impacted by the migration of woocommerce guttenberg. For now, I still can revert using classic checkout, but I think the plugins need to migrated to support the new guttenberg approach. The problem is I don't know where to start, I only know that there are some hooks that I need to change https://github.com/sofyansitorus/Woongkir/blob/master/assets/src/js/frontend.js#L103-L128 and acoomodate the hooks that happen using `window.wc_checkout_params`. 

But I can't find any documentation regarding it. 

## Why is this Document Important?

It will help old classic plugins that a lot of user rely on so we can move to new and powerfull guttenberg

## Potential Content

It should cover regarding the hooks of the JS, or at least what type of the hooks are and what we as developer could do about it

## Additional Context

For now none, I just know about the WooCommerce guttenberg after 1-2 years not deploying any new SMEs commerce using woocommerce 

related to https://woocommerce.com/document/cart-checkout-blocks-status/#reverting-to-shortcodes-with-woocommerce-8-3

Any help or pointer is really appreciated. Thank you

**Comment by mikejolley** [comment]
Hi @benyaminl 

Could you give an overview of some of the functionality you're wanting to port over to blocks? The JavaScript code you referenced isn't using hooks or a WooCommerce API and is manipulating the DOM directly. If we can understand your requirements better we may be able to recommend a different API or doc starting point.

Thanks

**Comment by benyaminl** [comment]
> Hi @benyaminl
> 
> Could you give an overview of some of the functionality you're wanting to port over to blocks? The JavaScript code you referenced isn't using hooks or a WooCommerce API and is manipulating the DOM directly. If we can understand your requirements better we may be able to recommend a different API or doc starting point.
> 
> Thanks


I want to make WooOngkir works on top the new block builder, that can hook on the change of the country, state, city, and subdistrict, like at the old classic woocommerce checkout page. 

Is there any documentation regarding the JS Hook available for it? 

Thank you

**Comment by mikejolley** [comment]
For the rates themselves, nothing should change on the server side. Rates are returned via the API but the underlying system in the same as the classic checkout.

For the checkout form, what I can tell your plugin is manipulating fields when Indonesia is selected as a country. You cannot change the DOM in this way with React components, but you can add new fields. This is covered in:

https://github.com/woocommerce/woocommerce/blob/f6035610a69083f5e1ffe3bf3cec530a46eb3309/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/additional-checkout-fields.md 

Custom field values are POSTed to the server at which point a shipping plugin could use those values to provide correct rates.

I'm going to close this issue for now as no action is required on our side, but if what you're attempting is not possible with additional fields I'd encourage you to open a new issue with a more specific request for change. e.g. If a specific field such as postcode needs special handling for Indonesia, provide the details in a new issue so that specific use-case can be accounted for, where possible. 

Thanks for your feedback.
