### ISSUE TITLE
Express Checkout box is always visible, even if there are no Express Payment Methods

### ISSUE THREAD

**Issue by Aljullu** [woothemes/woocommerce#50353]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Express Checkout box is always rendered in the Checkout block even when there are no Express Payment methods available:

![image](https://github.com/user-attachments/assets/8f1e3d6a-1795-43cf-b0a1-2a4380b995f7)

It requires having WooPayments enabled, so I don't know if the issue is in WooCommerce core or WooPayments itself.

### Expected behavior

If no Express Payment methods are available, the Express Checkout box shouldn't be rendered.

### Actual behavior

The Express Checkout box is rendered even though there are no Express Payment methods available.

### Steps to reproduce

1. Create a new site and install WooCommerce and WooPayments.
2. Set up both plugins and import some products.
3. In the frontend, add a product to your cart and go to the Checkout.
4. As long as your browser doesn't support any of the Express Payment methods, you will see the Express Checkout box is rendered on top of the Checkout block without any contents. In the Cart block, you will also see the `OR` line above the _Proceed to Checkout_ block, which feels confusing.

![image](https://github.com/user-attachments/assets/5103ff3f-017a-4b38-9efa-7fbaa646d696)

### WordPress Environment

Tested with WC 9.1.4 and 9.2 beta with several browsers and two different stores, all of them using WP 6.6.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment]
I do have express buttons rendered for me, how did you get them not to render?

**Comment by senadir** [comment]
When disabling the buttons, no box is shown.

**Comment by Aljullu** [comment]
> I do have express buttons rendered for me, how did you get them not to render?

I don't really know what's the logic behind them appearing or not. I guess Apple Pay only appears on Mac and Google Pay on Chrome/Android? :thinking:

**Comment by Aljullu** [comment]
Sharing a jurassic.ninja site where I can reproduce this constantly: https://satisfied-civet.jurassic.ninja/checkout/.

I simply: 

1. Installed WC and WooPayments.
2. Imported some products.
3. Set up WooPayments.
4. Changed the store visibility to _Live_.

I can reproduce the issue in any device I use:

Chrome on Linux | Firefox on Linux | Firefox on Android
--- | --- | ---
![image](https://github.com/user-attachments/assets/3041c9b7-e370-4916-a345-2b257f6c5dda) | ![image](https://github.com/user-attachments/assets/7da89ef0-5a18-405e-a327-92a9092e8110) | ![IMG_20240814_143028](https://github.com/user-attachments/assets/53825654-d14b-4420-bc05-731a97a4e011)

Using BrowserStack I can reproduce it in other environments as well:

Chrome on Windows | Firefox on Mac
--- | ---
![imatge](https://github.com/user-attachments/assets/6cb716fe-fe3c-4ac6-8396-1c64ac8130c5) | ![imatge](https://github.com/user-attachments/assets/0b4b991f-03b6-4125-8c37-ca9ef782b219)

---

This is the markup of the _Express Checkout_ section:

![image](https://github.com/user-attachments/assets/9bf6bfbd-3f86-4adf-ae52-14a1832face4)

The first thing that confuses me is that `#express-payment-method-woocommerce_payments_express_checkout_applePay` is rendered on the page but has `display: none;`. :confused:

**Comment by mikejolley** [comment]
> The first thing that confuses me is that #express-payment-method-woocommerce_payments_express_checkout_applePay is rendered on the page but has display: none;

This element is coming from woocommerce-payments. 

@senadir Should we reassign this or do you think the problem is our side? I am thinking that if an element is rendered with display none, its probably the fault of that rather than Checkout Blocks?

**Comment by senadir** [comment]
Yes but we can probably be a little be better on our side to detect that no element is visible and hide the whole container instead of this.

**Comment by asumaran** [comment]
Was the Express Checkout button size set to ‘Large’? If so, this should be resolved by PR: Automattic/woocommerce-payments#9327

**Comment by asumaran** [comment]
The button size doesn't necessarily have to be set to "Large". However, in [PR #9327](https://github.com/Automattic/woocommerce-payments/pull/9327), I’m restoring the container that defined the minimum height for the Express Checkout button. I’ve encountered this issue before, and that fix resolved it. I’m reintroducing it now because the same bug seems to have resurfaced

**Comment by mikejolley** [comment]
@asumaran I was able to reproduce and I don't think its related to size. See below:

![Screenshot 2024-08-28 at 14 25 37](https://github.com/user-attachments/assets/bcaab930-e541-4321-ae02-971329f4e562)

To replicate this you need to setup woo payments in dev mode, then in dev tools "Force the platform_checkout_eligible flag (aka WooPay eligible) in the account cache to be false". This disables the Woo Pay button but leaves Google/Apple Pay active. 

Then go to checkout in a browser which has no payment methods setup! In my case I tested with Firefox. This showed the issue.

I believe this is an issue in Woo Pay returning content when the payment buttons are not active.

**Comment by asumaran** [comment]
@mikejolley I misunderstood the issue, thinking it was related to Automattic/woocommerce-payments#9327.

However, after reviewing it, I can confirm that the bug exists. I noticed that the bug doesn’t occur with Payment Request Buttons (PRBs); it’s only happening when the Express Checkout Element is enabled (which is now active by default). This suggests that the issue was introduced recently.

After some digging I figured it out. We need to improve how we determine whether a payment method can process a payment. [In the case of PRBs](https://github.com/Automattic/woocommerce-payments/blob/0dd2726095b6b8e73848a9c703b4318355fc310a/client/payment-request/blocks/index.js#L38-L50), we load Stripe and let Stripe tell us if the payment element can handle payments using the `.canMakePayment()` [method](https://docs.stripe.com/js/payment_request/can_make_payment). However, with ECE, we [only](https://github.com/Automattic/woocommerce-payments/blob/0dd2726095b6b8e73848a9c703b4318355fc310a/client/express-checkout/blocks/index.js#L21) [rely](https://github.com/Automattic/woocommerce-payments/blob/0dd2726095b6b8e73848a9c703b4318355fc310a/client/express-checkout/blocks/index.js#L43) on the existence of a variable in the frontend. That's why it fails on Firefox, the variable is there but ECE is not available. 

This bug belongs to [WooPayments](https://github.com/Automattic/woocommerce-payments) cc @pierorocca @bborman22.

**Comment by pierorocca** [comment]
Thanks @asumaran. Opened an issue in the WooPayments repository and triaged it as high priority. Hopefully this is the last ECE related issue, expected after a change like this. https://github.com/Automattic/woocommerce-payments/issues/9365

**Comment by pierorocca** [comment]
@bborman22 flagging as a high urgency fix we'll want to prioritize to make it into the next release, maybe sooner as this would impact all sites with no buttons enabled. @c-shultz for awareness.
