### ISSUE TITLE
Customer New Account - Password Reset Key

### ISSUE THREAD

**Issue by NancyLussier** [woothemes/woocommerce#50502]
Performing a validation if **is_enabled()** at the beginning of the function will prevent doing code for nothing and won't call **get_password_reset_key()** function, as it invalidate the key we generate ourselves. There's no way to block the **woocommerce_created_customer_notification** action in **wp-content/plugins/woocommerce/src/Blocks/Domain/Services/CreateAccount.php**, so it will be greatly appreciated.

https://github.com/woocommerce/woocommerce/blob/b01aabef29551b98a27229e088e546077166475c/plugins/woocommerce/src/Blocks/Domain/Services/Email/CustomerNewAccount.php#L112

**Comment by NancyLussier** [comment]
The same applies to **wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-new-account.php**

Thank you for addressing this.

**Comment by barryhughes** [comment]
In both cases, moving the call to `$this->is_enabled()` to the start of the method could present backwards-compatibility issues (since the result of that method is filterable, and filter functions may wish to inspect the various fields that are initialized before it is called).

Are there other ways for you to work around the problem with reset keys? Can you override the email classes, for instance, and the `trigger` methods specifically?

**Comment by NancyLussier** [comment]
I don't see how I can override theses classes (there's no "if ( !defined(...) ). And there are no ways to block woocommerce_created_customer_notification action in plugins/woocommerce/src/Blocks/Domain/Services/CreateAccount.php (it's removed and added again with the same name). Maybe generate_key() only if enabled and filter functions won't be impacted?

**Comment by barryhughes** [comment]
> I don't see how I can override theses classes (there's no "if ( !defined(...) ).

Thinking specifically of the `WC_Email_Customer_New_Account` class, you can use the [`woocommerce_email_classes`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-emails.php#L225-L237) hook to register your alternative implementation (which might inherit from the original class, if useful).

Or, use the later action [`woocommerce_init`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-emails.php#L215) (which is in fact how the `CustomerNewAccount` email class is registered, I believe, so you could probably use it for both cases).

> And there are no ways to block woocommerce_created_customer_notification action in plugins/woocommerce/src/Blocks/Domain/Services/CreateAccount.php (it's removed and added again with the same name).

The use of an anonymous function [over here](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/src/Blocks/Domain/Services/CreateAccount.php#L39-L50) may make this a little harder (though it is still possible). We can label this issue so the relevant team can take a look and consider alternatives.

**Comment by barryhughes** [comment]
If I mislabelled, please do forward to the correct team (I was just a little unsure who was best).

**Comment by NancyLussier** [comment]
Thank you very much Barry! I'll give it a shot and tell you how it goes :)

**Comment by wavvves** [comment]
Hi @NancyLussier thank you for reporting this. Can you tell us a bit more about your use case here?

>We override the wp_new_user_notification_email() function in order to send a custom email.

Why overriding the template in `woocommerce/templates/emails/customer-new-account.php` is not a viable solution?

By the way, can you complete this issue description to include the current behaviour, expected behaviour and some testing steps? (ideally use one of the templates presented when clicking new issue).

**Comment by NancyLussier** [comment]
Hi,

There's no very other options, so that's what I finally did. Thank you all for your time!
