### ISSUE TITLE
CYS: Survey answer FSOR

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#50594]
Although I implemented the integration with FSOR ([PR #50196](https://github.com/woocommerce/woocommerce/pull/50196) and [PR #50354](#50354)), the answers are not currently being imported. 

We should investigate why the import isn't functioning as expected.

**Comment by tjcafferkey** [comment]
There's some existing discussion and context on this issue here p1723454738870929-slack-C053716F2H2

**Comment by mdperez86** [comment]
As part of an internal investigation, we found that the events are correctly tracked and stored in FSOR. But the reason why we see a low amount of user's feedbacks is because the majority of the users submitted the Survey Form without comments which is the metric used to show the feedbacks in FSOR Dashboard.

See this post pdnLyh-7CU-p2 for more details.
