### ISSUE TITLE
Trigger "cancelled order" email if status changes from "pending payment" to "cancelled"

### ISSUE THREAD

**Issue by orschiro** [woothemes/woocommerce#50650]
Hi team, 

Currently, the cancelled order email only triggers if the status changes from "processing" or "on-hold" to "cancelled".

In my opinion, we are missing the important change from "pending payment" to "cancelled", meaning a customer actually never ended up paying.

Can this please be implemented?

Thank you!

<img width="356" alt="image" src="https://github.com/user-attachments/assets/b9eab52d-783d-40e3-a62a-6c2871d82c4e">

**Comment by orschiro** [comment]
https://stackoverflow.com/questions/45732404/send-an-email-notification-when-order-status-change-from-pending-to-cancelled

This code still works and does the job perfectly, but apparently got removed from the code base. Why?

**Comment by jorgeatorres** [comment]
Hi @orschiro!

Thanks for reaching out. This has been discussed before. See https://github.com/woocommerce/woocommerce/issues/15707, for example. The rationale is that a "pending payment" order can occur in cases like the one you described and precisely because it hasn't been paid, it's not necessary to notify anyone about it.

I understand that a pending order might not have the exact same meaning for everyone, but at least there's an easy way to bring back that functionality by using that snippet of code you've mentioned, so WC can accommodate other use cases too.

Please let us know if we have missed something. Thanks again!

**Comment by orschiro** [comment]
Understood, thanks!
