### ISSUE TITLE
Product Filters Redesign: Block structure for sharing and syncing filter blocks between main filter and overlay

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#50866]
Block structure needs a review and update to ensure smooth syncing between the main template part and Overlay. The issue and potential solution can be found at https://github.com/woocommerce/woocommerce/issues/49933.

Due to the length of back-and-forth convos, I decided not to copy it here, please refer to the issue, starting from [this comment](https://github.com/woocommerce/woocommerce/issues/49933#issuecomment-2259716877) for full context.

**Comment by j111q** [comment]
I clarified @dinhtungdu's proposal from #49933 and I'm okay with it as a general direction. I suggested some copy changes to the blocks and template parts so that there's some consistency and hopefully adds clarity to the user too. 

Here's a diagram showing the naming tweaks and expected behaviour:

![Frame 3](https://github.com/user-attachments/assets/4497466c-49aa-4e12-a94f-8495c9c468a9)

**Comment by dinhtungdu** [comment]
I'm closing this as we're changing the design direction on the overlay.
