### ISSUE TITLE
Prevent synchronous WCCOM API calls in admin apages

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#51082]
### Issue Description

Follow-up to #50543, @rjchow and I found two other endpoints that are running synchronously:

1. [OnboardingThemes.php](https://github.com/woocommerce/woocommerce/blob/20d89bae03397094eac80a5f24fedb3b48c95645/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingThemes.php#L104-L109) - originally reported in p1725007685579129-slack-C01SFMVEYAK, runs in `wc-admin` pages
2. [WCPayPromotion.php](https://github.com/woocommerce/woocommerce/blob/20d89bae03397094eac80a5f24fedb3b48c95645/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php#L167), runs in all `wp-admin` pages

#### To reproduce:

1. Ensure your site has marketing suggestion enabled in `WooCommerce > Settings > Advanced > WooCommerce.com`
2. In your environment, add `throw new \Exception();` the code mentioned above
3. Delete transients by running `wp transient delete --all && wp cache flush`
4. Go to Homescreen
5. Observe fatal error occurs

### Acceptance criteria

1. For `OnboardingThemes.php`, I recommend to remove the API call (a [separate issue](https://github.com/woocommerce/woocommerce/issues/50624)), but I'm unsure if there are parts of WooCommerce which uses it in `wc.wcSettings.allSettings.admin.onboarding.themes`. Alternatively, we could make it such that the API call is run async.
2. For `WCPayPromotion.php`, we could make it only call the cached specs similar to what we did in [this PR](https://github.com/woocommerce/woocommerce/pull/50674/files#diff-bad8bffd72b825a2a6fae278ab9399e504efd4c444c4204ea9f572d01a6c4026R134-R150).

**Comment by chihsuan** [comment]
> For OnboardingThemes.php, I recommend to remove the API call (a https://github.com/woocommerce/woocommerce/issues/50624), but I'm unsure if there are parts of WooCommerce which uses it in wc.wcSettings.allSettings.admin.onboarding.themes. Alternatively, we could make it such that the API call is run async.

I think we can deprecate/remove the `OnboardingThemes` since it's under an internal namespace. Other plugins or themes shouldn't use it. I'll do some research to make sure it's safe to remove it.

> For WCPayPromotion.php, we could make it only call the cached specs similar to what we did in [this PR](https://github.com/woocommerce/woocommerce/pull/50674/files#diff-bad8bffd72b825a2a6fae278ab9399e504efd4c444c4204ea9f572d01a6c4026R134-R150).

@ilyasfoo Unlike `PaymentGatewaySuggestions,` we don't fetch `WCPayPromotion` data asynchronously somewhere else, so we need to call it asynchronously somewhere. However, I suspect that we don't really need to run it in all wp-admin pages. It was changed in https://github.com/woocommerce/woocommerce-admin/pull/7965/commits/27f153a462fabd64928241b2df92ebfabfbb771f#diff-69694a4ba88839539fd7cbb854ee2ca5b4cb5174a9251ae64cf5728678bb68d5, it looks like it was an unintentional change.


https://github.com/woocommerce/woocommerce/blob/24403c244ee82e9c9a2868e7e41c78c03227c3ab/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php#L23-L25

I think it should only be run on the payment setting page. To prevent the page from crashing, we could add a try-catch block around the code that fetches the data and fall back to the default value if it fails. What do you think?

**Comment by ilyasfoo** [comment]
> I think we can deprecate/remove the OnboardingThemes since it's under an internal namespace. Other plugins or themes shouldn't use it. I'll do some research to make sure it's safe to remove it.

@chihsuan  Sounds good, thanks! I also think there are a couple of GitHub issues regarding removing/deprecating OnboardingThemes 😅 

> I think it should only be run on the payment setting page. To prevent the page from crashing, we could add a try-catch block around the code that fetches the data and fall back to the default value if it fails. What do you think?

I don't think we need to add another try-catch block since we already handle that with [RemoteSpecsEngine](https://github.com/woocommerce/woocommerce/blob/63424d3ef99a53a14fe74ecfb0cfc4ffc0290e0f/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php#L111-L136). IIRC this issue is to prevent any potential future breaks with related code affecting the entire wp-admin area, if we can reduce the impact to only payment settings, it should be good enough
