### ISSUE TITLE
[Flaky K6 test] My Account Open Order flaky test

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#51234]
K6 perf tests has been flaky in the last week. Example: https://github.com/woocommerce/woocommerce/actions/runs/10772857128/job/29871446358#step:9:1439

```
█ My Account Open Order
       ✓ is status 200
       ✗ title is: "My account – WooCommerce Core E2E Test Suite"
        ↳  66% — ✓ 2 / ✗ 1
       ✓ body contains: 
       ✓ footer contains: Built with WooCommerce
       ✓ body contains: 100
```

**Comment by veljkho** [comment]
The issue with this test is that the title should be  `Order #[id] - WooCommerce Core E2E Test Suite` and not `My account - ...`, because when you check the page with order ID e.g. `/my-account/view-order/[id]` the title is `Order #[id] - ...` so it looks to me that the test was not good from the beginning and passing the test skipped actually landing on proper page and verifying proper title.

I am working on it locally to fix it.

**Comment by adimoldovan** [comment]
> The issue with this test is that the title should be `Order #[id] - WooCommerce Core E2E Test Suite` and not `My account - ...`, because when you check the page with order ID e.g. `/my-account/view-order/[id]` the title is `Order #[id] - ...` so it looks to me that the test was not good from the beginning and passing the test skipped actually landing on proper page and verifying proper title.
> 
> I am working on it locally to fix it.

@veljkho I'm not sure I understand. Why was it passing in some cases? It's not failing on every run.

**Comment by veljkho** [comment]
> Why was it passing in some cases?

@adimoldovan I'm working on that to find out why and what's happening. It seems that no order ID was extracted as there was no order attached to the admin (user), so when accessing just the /view-order/, there will be the My Account title and, of course, the page with info that there is no order to see.

I need to make sure the order ID is extracted and the order is present because the title should be Order #123 - ... when accessing the page /view-order/123.

**Comment by veljkho** [comment]
When it was passing it was actually invalid test.
When it was failing, it might be that there was some order present for the user and then it was extracted properly, but I need to check if that was the case.

**Comment by veljkho** [comment]
My suspicions were confirmed that this was an inaccurate test.
