### ISSUE TITLE
[WC Payments NOX] Offline payment methods

### ISSUE THREAD

**Issue by vladolaru** [woothemes/woocommerce#51444]
### Description

Implement the offline payment methods UI.

### Acceptance criteria

* On list item click we open a sub-page with the three offline payment methods
* We can enable/disable each offline payment method
* We can manage each offline payment method via their separate settings pages.
* Only users with the required access level can manage offline payment methods

### Designs
Design post: pfHfG4-q7-p2
Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

### Dev notes
Reactifying the Payments settings page: pe4Hk0-1ly-p2
Populate react-powered main payments settings screen PR: https://github.com/woocommerce/woocommerce/pull/50825

### Additional context
PRD: 1wMfX8CAjDnOp24tcU-PADB0pOt3cz7mGdyZYeRBxx2Y-gdoc

**Comment by rjchow** [comment]
Hey @vladolaru! I'm looking into creating subtasks for this issue and I'd like some clarification on this point:
> We can manage each offline payment method via their separate settings pages.

Does this refer to the existing settings page for the offline payment methods? 

Or otherwise, where could I find the designs for each individual settings screens? I didn't manage to find them in the linked Figma: xO8YdpKfaVoP2d8NvweZ5I-fi-1428_21437

e.g:
Bank transfer: `./wp-admin/admin.php?page=wc-settings&tab=checkout&section=bacs`
![Image](https://github.com/user-attachments/assets/796b8b02-f146-43b1-b31a-4da73935ee50)

Check: `./admin.php?page=wc-settings&tab=checkout&section=cheque`
![Image](https://github.com/user-attachments/assets/211f6cd7-a681-4c64-becc-67a9e4d9f804)

Cash on delivery: `./wp-admin/admin.php?page=wc-settings&tab=checkout&section=cod`
![Image](https://github.com/user-attachments/assets/a37c9052-0129-466e-96ea-56ffe0d95e37)

**Comment by vladolaru** [comment]
Hi @rjchow! Thanks for taking on this work.

> Does this refer to the existing settings page for the offline payment methods?

Yes. For the MVP, we will not handle individual payment gateway settings, only link to the respective pages (the ones you mentioned) via the "Manage" buttons.

I know we have some special handling via the Payments task for offline payment methods, but that is something to be explored for the Payments settings page.

cc @timmy5685 @orcunomattic

**Comment by vladolaru** [comment]
@rjchow, thank you for working on this. With the merged PRs, there anything left that you want to tackle around this or we can close the issue?

**Comment by rjchow** [comment]
I believe it's all done!

**Comment by vladolaru** [comment]
Excellent! Thank you @rjchow
