### ISSUE TITLE
Product Collection: Add "Related by" setting to Related Products collection

### ISSUE THREAD

**Issue by kmanijak** [woothemes/woocommerce#52021]
**Background:**
Currently Related Products collection displays products related by category only. Add more options.

**Goal:**
Add "Related by" setting to Inspector Controls for Related Products collection:

![Image](https://github.com/user-attachments/assets/0b974365-e3ad-4949-a6d3-eb23a5f2c534)

It should be a multiple-choice with options Categories, Tags, and Attributes. Categories should be enabled by default (backward compatibility)

**Comment by ObliviousHarmony** [comment]
Just to share some rough thoughts:

- **Categories & Tags**: Fortunately, `wc_get_related_products()` [already contains support for selecting which of these to include](https://github.com/woocommerce/woocommerce/blob/292144b5be78b71800eca5ede37c33901bdb316d/plugins/woocommerce/includes/wc-product-functions.php#L1043-L1045). All we need to do is wrap the function call with add/remove filters based on the query attribute setting.
- **Attributes**: This one is trickier because there currently doesn't exist any method for filtering to attribute relationships. Assuming that we want to implement this feature I think we first need to take a look at what that actually even means!
