### ISSUE TITLE
[DOC-BUG] remote logging user data privacy

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#52037]
We have opted-in to WooCommerce analytics, which enables remote logging with 9.4

How can we make sure that no user data is sent to WooCommerce though? 
e.g. if a function param or exception/error message contains user data (e.g. email)

I saw that it will by default filter this out if it happens within WooCommerce, but what if:
- it's outside of Woocommerce (e.g. the stack trace contains non-woocommerce code with that data, or also vice versa: the error only is woocommerce in the stack trace but the error is not in woocommerce)
- the user data is in the URL (e.g. /author/Customer_Name/ or /some/url/?foo=some@email.com)

Can you please clarify this in the documentation that it will not send any end-user data in any circumstances?

**Comment by chihsuan** [comment]
Hey @kkmuffme Thanks for bringing this up and opting into WooCommerce analytics! We appreciate your feedback and concerns about user data privacy.

> How can we make sure that no user data is sent to WooCommerce though?

We have been very careful about user data privacy and have taken some steps to ensure that no user data is sent to WooCommerce. We have implemented a sanitization mechanism that cleans up the paths, query strings before sending them to our servers. See https://developer.woocommerce.com/2024/09/23/recent-updates-to-error-handling-and-optional-remote-error-logging/ for more details.

Even if the error occurs outside of WooCommerce (It's worth noting that we don't log errors that stack track doesn't contain WooCommerce code.), we still run the exact sanitization mechanism to ensure that no user data is sent to WooCommerce.

> Can you please clarify this in the documentation that it will not send any end-user data in any circumstances?

While we have taken steps to ensure user data privacy, unfortunately, we can't 100% guarantee that since there are always edge cases. I hope you understand that it's a complex problem to solve, and we are continuously working on improving our sanitization mechanism to ensure user data privacy. But other than that, we are committed to not using user data for any other purposes than debugging, and also, data is stored securely and will be removed after 30 days. We will update our documentation to reflect this information. Thanks for sharing your concerns! 🙏

If you have any other questions or suggestions, feel free to ask! We will take it into consideration.

**Comment by kkmuffme** [comment]
Thanks, what about e.g. API keys in function parameters?

The doc states that you log `request_uri`, which in many cases contains user data that doesn't seem to be scrubbed: e.g. `?some_field=user@email.com` in unsubscribe emails, which doesn't seem to get scrubbed?

>It's worth noting that we don't log errors that stack track doesn't contain WooCommerce code

This is where I see lots of issues arising: I checked the scrubbing code and this means that any plugin that uses woocommerce functions highly increases the risk of user data ending up in woocommerce logs, since the scrubbing is geared towards what/how woocommerce handles things.
I think this should be changed so only errors where the error is caused by woocommerce are logged - not all errors where the trace contains a woocommerce file.

Given the recent saga in WordPress core and Google fonts privacy baiting, this is begging for this to happen again.

**Comment by chihsuan** [comment]
> The doc states that you log request_uri, which in many cases contains user data that doesn't seem to be scrubbed: e.g. ?some_field=user@email.com in unsubscribe emails, which doesn't seem to get scrubbed?

We replaces all query parameters except for some whitelisted ones with 'xxxxxx' in the `request_uri` field. For example, if the request_uri is `https://example.com/?a=1&b=2`, we will log `https://example.com/?a=xxxxxx&b=xxxxxx` so that we can still see the structure of the URL without logging any sensitive data. Unfortunately, we don't scrub the paths such as `/author/Customer_Name/` because it would be too difficult to determine what is sensitive and what is not. If you have any suggestions on how we can improve this, please let me know!

> I think this should be changed so only errors where the error is caused by woocommerce are logged - not all errors where the trace contains a woocommerce file.

Thanks for the feedback! That's a good point. I agree that we should be more careful about what we log. 👍 
I'll make sure that we only log errors that are caused by WooCommerce.

**Comment by chihsuan** [comment]
We have updated the remote logging feature to only log errors that are caused by WooCommerce and have improved the sanitization mechanism to ensure that no sensitive data is sent to WooCommerce in https://github.com/woocommerce/woocommerce/pull/52321. I have also updated the [dev post](https://developer.woocommerce.com/2024/09/23/recent-updates-to-error-handling-and-optional-remote-error-logging/) to reflect these changes. 

I'm closing this issue now. If you have any other questions or concerns, feel free to ask! 🙏

Thanks again for providing feedback and helping us improve our product! 🚀
