### ISSUE TITLE
Cart block doesn't apply the min/max restrictions very thoroughly

### ISSUE THREAD

**Issue by peterfabian** [woothemes/woocommerce#52109]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It's rather easy to checkout with more than the maximum allowed number of products via StoreAPI/cart/checkout blocks.

### Expected behavior

Not being able to check out with quantity exceeding the number from `woocommerce_store_api_product_quantity_maximum`.

### Actual behavior

Checkout goes through.

### Steps to reproduce

1. Add a filter for `woocommerce_store_api_product_quantity_maximum` to only allow quantity <= 2 for each product, e.g. as below:
```
add_filter( 'woocommerce_store_api_product_quantity_maximum', 'filter_max_cart_item_qty', 10, 3 );

function filter_max_cart_item_qty( $value, $product, $cart_item ){
	return 2;
}
```
2. Open page with **simple product P**, add 5 to cart.
3. Go to cart, observe the quantity is 5.
4. Proceed to Checkout
6. Checkout loads with 5 items in order summary
7. Click Place Order/Pay Now 
8. See that you just bought 5 items. 

The limit gets applied when e.g. the shipping changes, but not when the cart gets reloaded (using the browser refresh button).

### WordPress Environment

Use only WC core and Storefront, no payment gateways or other plugins, otherwise something triggers a reload quite often.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
I've done a little digging and experimentation and found 3 main issues.

1. `notifyIfQuantityLimitsChanged` assumes the client will fix the problem. This is only the case in cart, not checkout.
2. No qty validation when validating cart items from the cart/checkout route. We should throw exception.
3. `QuantitySelector` component updates state on error, so there is no chance to view the error (this is why `notifyIfQuantityLimitsChanged`) exists.

I propose:

1. Exception from the API in the form of cart errors if something is wrong. This will result in something like:

![Image](https://github.com/user-attachments/assets/f3521e5a-c052-4bc1-bc94-846c1db7e81e)

2. Remove `notifyIfQuantityLimitsChanged`. "allow" invalid qty instead. See below.

3. `QuantitySelector` highlights amounts that are out of bounds instead of forcing the correct value. `aria-invalid` will be used to style the invalid input.
 
![Image](https://github.com/user-attachments/assets/239caaad-b0ef-46ac-814a-af61219048b8)

This will give the customer opportunity to see the error and resolve it. It will also block checkout if something is wrong.

Ideally we can also find a way to link back to cart from the error notice displayed on checkout but this is secondary objective.

@opr you've worked on this in the past. Does this sound like a good solution?

edit: I am investigating fixing violations automatically in the API.

**Comment by opr** [comment]
> @opr you've worked on this in the past. Does this sound like a good solution?

Yes, in theory it sounds great, but I also went down the route of allowing invalid quantities when I looked at this, can't remember why we went with `notifyIfQuantityLimitsChanged` in the end, but worth looking at again for sure.

You probably also want to skip sending to the API if the quantity is known to be invalid.

> Ideally we can also find a way to link back to cart from the error notice displayed on checkout but this is secondary objective.

Yup, would be good 👌🏼
