### ISSUE TITLE
Can’t Add shipping options in shipping zones

### ISSUE THREAD

**Issue by solerevival** [woothemes/woocommerce#52348]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello! Woocommerce will not allow me to add shipping options in shipping zones. Only displays options for “free shipping” and “Local pickup” I have shipping plugins “Woocommerce shipping” and “Shipstation” active and installed. I have troubleshooted every possible issue to my knowledge. 

### Expected behavior

Not sure 

### Actual behavior

Doesn’t allow adding alternate shipping options other than free shipping and local pickup

### Steps to reproduce

Go to Woocomerce settings>Shipping>shipping Zones> add shipping method. Only displays Free Shipping and Flat rate on my end 

### WordPress Environment

.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @solerevival this appears to be a support request rather than a bug report or enhancement request. Please use our support channels instead:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
- Post a question in the [WooCommerce Community Slack channel](https://woocommerce.com/community-slack/)

I'm closing this issue for now.
