### ISSUE TITLE
Fix 404 links from the Checkout Blocks documentation pages

### ISSUE THREAD

**Issue by ralucaStan** [woothemes/woocommerce#52587]
### Describe the bug

Some checkout-related documentation links throw 404.

### Expected behavior

Documentation links should work as expected.

### Actual behavior

In https://github.com/woocommerce/woocommerce/pull/49984 we moved some of our docs to map to the new docs platform. https://developer.woocommerce.com/docs/ 
In doing such we failed to check for other docs that referenced the moved files. 
We need to check the docs and update the 404 links for the moved files with the new path. 

### Steps to reproduce

For example, in the [Third-party developers](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/#third-party-developers) section on [WooCommerce Blocks](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/) documentation, the [Extensibility](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/README.md) doc and all docs under Checkout Payment Methods and Checkout Blocks return 404's.

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nielslange** [comment]
Back when WooCommerce Blocks were in a separate repo, we checked links of MD files using the [`markdown-link-check`](https://github.com/tcort/markdown-link-check) action. You can find the corresponding file [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/check-doc-links.yml). Rather than just fixing broken links, I propose we add the [`markdown-link-check`](https://github.com/tcort/markdown-link-check) action to automatically detect broken links in the future.

Whoever is working on this issue, running the following snippet in the root folder of this repo, lists all broken links:
```sh
find docs -name '*.md' -exec npx markdown-link-check {} \;                                      
```
