### ISSUE TITLE
tiktok for woocommerce php warning

### ISSUE THREAD

**Issue by betayazilim** [woothemes/woocommerce#52629]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I couldn't find repo for tiktok for woocommerce plugin.
I use latest versions of tiktok plugin, woocommerce and wordpress.

Warning: Array to string conversion in /wp-content/plugins/tiktok-for-woocommerce/catalog/Tt4b_Catalog_Class.php on line 246

### Expected behavior

no error

### Actual behavior

Warning: Array to string conversion in /wp-content/plugins/tiktok-for-woocommerce/catalog/Tt4b_Catalog_Class.php on line 246

### Steps to reproduce

install tiktok for woocommerce plugin and connect to tiktok

### WordPress Environment

Don't like to add

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Hi there @ned-bs - thanks for the Issue!

The repo for tiktok for woocommerce is private which is why you cannot find it.

If you have problems then you can go via support at https://woocommerce.com/contact-us/

On this occasion, I have created an issue in the private repo with the details above for the team to prioritize and I am closing this issue.

Thanks again
