### ISSUE TITLE
Amazon Fulfillment Issue

### ISSUE THREAD

**Issue by gw49z** [woothemes/woocommerce#52772]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Our customers are having issues with processing payments or orders saying the order didn’t push through even though the order was successful. This leads to the orders being duplicated. 

### Expected behavior

Our customers are having issues with processing payments or orders saying the order didn’t push through even though the order was successful. This leads to the orders being duplicated. 

### Actual behavior

Our customers are having issues with processing payments or orders saying the order didn’t push through even though the order was successful. This leads to the orders being duplicated. 

### Steps to reproduce

Our customers are having issues with processing payments or orders saying the order didn’t push through even though the order was successful. This leads to the orders being duplicated. 

### WordPress Environment

We have WooCommerce and MCF

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gw49z! Thank you for reporting the issue. It looks like it may be on the [Amazon Fulfillment (MCF) for WooCommerce](https://woocommerce.com/products/woocommerce-amazon-fulfillment/) side of things. This repository is for WooCommerce Core and issues related to it. In order for you to get help faster, please go through "Get support" flow on [Amazon Fulfillment (MCF) for WooCommerce](https://woocommerce.com/products/woocommerce-amazon-fulfillment/) page (link to "Get support" is on the sidebar). I am closing this issue since the fastest way to get help will be through MCF's support.
