### ISSUE TITLE
“Payments” menu after upgrading to 9.4.1 empty page

### ISSUE THREAD

**Issue by Martje65** [woothemes/woocommerce#52812]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since upgrading to 9.4.1, my site now display a “Payments” menu in the admin area, even my site don’t use WooPayments and there’s not a way to get rid of it.
If you don't have WooPayments go to the Paymants menu you will get an empty page.

wp-admin/admin.php?page=wc-admin&task=woocommerce-payments

![Image](https://github.com/user-attachments/assets/cc82c001-3c9c-4c34-aeb1-602956346f3c)

### Expected behavior

If you don't use WooPayments there must be no “Payments” menu.

### Actual behavior

If you don't have WooPayments go to the Paymants menu you will get an empty page.

### Steps to reproduce

Go to wp-admin/admin.php?page=wc-admin&task=woocommerce-payments

### WordPress Environment

WP 9.4.1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by maddisondesigns** [comment]
Seeing the exact same thing on multiple sites. [As mentioned in my comment here](https://github.com/woocommerce/woocommerce/pull/51541#issuecomment-2477801789) and shown in my short screencast, this new top-level menu item just appeared after the most recent update and it's always been showing a blank screen. There was no `No thanks` link to click on.

**A)** I'm not using WooCommerce Payments and so you shouldn't ever be showing this in the first place!
**B)** This should never have been a top-level menu item!

WooCommerce has only gotten worse and worse since Automattic bought it, with all the annoying dashboard ads, notifications and extra dashboard clutter like all the additional top-level menu items you've added and the recent `Live` site visibility tag in the WP Admin Bar that no-one asked for.

**Comment by Martje65** [comment]
Dear @vladolaru,

In Woocommerce 9.4.2 the top level menu item still presence. There is no reason for because its the same as for Dashboard / woocommerce settings / Payments Tab.

Please remove the top level Payments item.

**Comment by maddisondesigns** [comment]
@vladolaru If this issue has been supposedly fixed, why am I still seeing a Payments menu item in my dashboard, with WooCommerce 9.4.2? Instead of seeing a blank page when I click on it, it now just redirects me to the Payments Tab in the WC Settings.

Screencast: https://share.zight.com/P8uKZvOP

I'm seeing the same thing on multiple sites.
