### ISSUE TITLE
[Fatal] PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 12288 bytes) in /wordpress/plugins/woocommerce/9.3.3/src/Blocks/Utils/BlockTemplateUtils.php:223

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#52848]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3.

[Link to code](https://github.com/woocommerce/woocommerce/blob/e66ab452634da522af668779bf98cd1a8adbe354/plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php#L223).

```
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 12288 bytes) in /wordpress/plugins/woocommerce/9.3.3/src/Blocks/Utils/BlockTemplateUtils.php on line 223
```

### Expected behavior

Logs should be captured without exhausting available memory.

### Actual behavior

Running out of memory. 

### Steps to reproduce

We don't have steps to reproduce, but we observed 88 instances of this problem on Sat Nov 9, 0000 UTC to 2359 UTC across 2 sites. 

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
This line seems to be the issue:

https://github.com/woocommerce/woocommerce/blob/e66ab452634da522af668779bf98cd1a8adbe354/plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php#L223

It’s necessary because it reads and parses the file to a block template. This line is also present in the new WooCommerce version. The fatal error might be occurring due to poor hosting solution and long block templates.

I'm inclined to close this issue. What do you think?
