### ISSUE TITLE
Fatal error in `display_notice_for_merged_plugins`

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#53057]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A user shared some logs showing fatal errors in the plugins table. This traces back to `display_notice_for_merged_plugins` specifically:

```php
$columns_count = $wp_list_table->get_column_count();
```

https://github.com/woocommerce/woocommerce/blob/666ece52c2f884ca1d522096eeec954ec9e42c2c/plugins/woocommerce/src/Packages.php#L260

Stack trace:

<details>
```
2024-11-19T01:57:40+00:00 CRITICAL Uncaught Error: Call to a member function get_column_count() on null in /home/redacted/public_html/wp-content/plugins/woocommerce/src/Packages.php:260 CONTEXT: {"error":{"type":1,"file":"/home/redacted/public_html/wp-content/plugins/woocommerce/src/Packages.php","line":260},"remote-logging":true,"backtrace":["","#0 /home/redacted/public_html/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('forminator/form...')","#1 /home/redacted/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#2 /home/redacted/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#3 /home/redacted/public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'forminator/form...', Array, 'search')","#4 /home/redacted/public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)","#5 /home/redacted/public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()","#6 /home/redacted/public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()","#7 /home/redacted/public_html/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()","#8 /home/redacted/public_html/wp-includes/class-wp-hook.php(324): wp_ajax_search_plugins('')","#9 /home/redacted/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#10 /home/redacted/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#11 /home/redacted/public_html/wp-admin/admin-ajax.php(192): do_action('wp_ajax_search-...')","#12 {main}","thrown"]}
2024-11-19T01:57:41+00:00 CRITICAL Uncaught Error: Call to a member function get_column_count() on null in /home/redacted/public_html/wp-content/plugins/woocommerce/src/Packages.php:260 CONTEXT: {"error":{"type":1,"file":"/home/redacted/public_html/wp-content/plugins/woocommerce/src/Packages.php","line":260},"remote-logging":true,"backtrace":["","#0 /home/redacted/public_html/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('forminator/form...')","#1 /home/redacted/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#2 /home/redacted/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#3 /home/redacted/public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'forminator/form...', Array, 'search')","#4 /home/redacted/public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)","#5 /home/redacted/public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()","#6 /home/redacted/public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()","#7 /home/redacted/public_html/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()","#8 /home/redacted/public_html/wp-includes/class-wp-hook.php(324): wp_ajax_search_plugins('')","#9 /home/redacted/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#10 /home/redacted/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#11 /home/redacted/public_html/wp-admin/admin-ajax.php(192): do_action('wp_ajax_search-...')","#12 {main}","thrown"]}
```

</details>

### Expected behavior

We should harden this function to avoid the possibility of fatal errors.

### Actual behavior

We do not check `$wp_list_table` is of the expected type.

### Steps to reproduce

I was unable to replicate this, but the function can be hardened.

### WordPress Environment

See 9068286-zd-a8c

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by BusinessBloomer** [comment]
I have the same problem:

> Uncaught Error: Call to a member function get_column_count() on null in /var/---/wordpress/wp-content/plugins/woocommerce/src/Packages.php:260

By looking at the backtrace:

> "backtrace": [
>         "",
>         "#0 /var/-----/wordpress/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('**bbloomer-woocom**...')",
>         "#1 /var/----/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)",
>         "#2 /var/-----/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)",
>         "#3 /var/----/wordpress/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', '**bbloomer-woocom...**', Array, 'search')",
>         "#4 /var/----/wordpress/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)",
>         "#5 /var/-----/wordpress/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()",
>         "#6 /var/----/wordpress/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()",
>         "#7 /var/----/wordpress/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()",
>         "#8 /var/----/wordpress/wp-includes/class-wp-hook.php(324): wp_ajax_search_plugins('')",
>         "#9 /var/----/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)",
>         "#10 /var/----/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)",
>         "#11 /var/----/wordpress/wp-admin/admin-ajax.php(192): do_action('wp_ajax_search-...')",
>         "#12 {main}",
>         "thrown"
>     ] 

...it seems to be caused by one of my custom plugins (not sure why it truncates the name, you see it in bold above, I have like 30+ plugins starting with that same prefix - so it could be one of them or ALL of them).

The result of this bug: you can't search plugins in the WP backend. It's frozen:
![Image](https://github.com/user-attachments/assets/10693fdf-ee2a-4110-afe4-f291494f445d)

Are we meant to change something within the Plugin Header maybe to make this work? Not sure

**Comment by imhossen1** [comment]
The user is experiencing the same issue, likely caused by the CRON jobs running on the server instead of being managed by WordPress. As a potential fix, they identified rolling back to version 9.9.3 of the plugin or temporarily disabling the DISABLE_WP_CRON function in the **_wp-config.php_** file. 

REF: **_9056318-a8c-zd_**

<details>
An error of type E_ERROR occurred on line 260 of the file
/home/s/____________/____________//public_html/wp-content/plugins/woocommerce/src/Packages.php. Сообщение об ошибке: Uncaught Error: Call to a member function get_column_count() on null in /home/s/____________/____________//public_html/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 [internal function]: Automattic\WooCommerce\Packages::display_notice_for_merged_plugins(‘query-monitor/q…’)
#1 /home/s/____________/____________/public_html/wp-includes/class-wp-hook.php(326): call_user_func_array(Array, Array)
#2 /home/s/____________/____________/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(”, Array)
#3 /home/s/____________/____________/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action(‘after_plugin_ro…’, ‘query-monitor/q…’, Array, ‘search’)
#5 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)
#6 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()
#7 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#8 /home/s/____________/____________//public_html/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()
#9 [internal function]: wp_ajax_search_plugins(”)
#10 /home/s/____________/____________//public_html/wp-includes/class-wp-hook.php(324): call_user_func_array(‘wp_ajax_search_…’, Array)
#11 /home/s/____________/____________//public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(”, Array)
#12 /home/s/____________/____________//public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /home/s/____________/____________//public_html/wp-admin/admin-ajax.php(192): do_action(‘wp_ajax_search-…’)
#14 {main}
  thrown

</details>

**Comment by imhossen1** [comment]
The user is experiencing the same issue, likely caused by the CRON jobs running on the server instead of being managed by WordPress. As a temporary workaround, they identified rolling back to version **_9.3.3_** of the plugin or temporarily disabling the _**DISABLE_WP_CRON**_ function in the **_wp-config.php_** file. 

REF: **_9056318-a8c-zd_**

<details>
An error of type E_ERROR occurred on line 260 of the file
/home/s/____________/____________//public_html/wp-content/plugins/woocommerce/src/Packages.php. Сообщение об ошибке: Uncaught Error: Call to a member function get_column_count() on null in /home/s/____________/____________//public_html/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 [internal function]: Automattic\WooCommerce\Packages::display_notice_for_merged_plugins(‘query-monitor/q…’)
#1 /home/s/____________/____________/public_html/wp-includes/class-wp-hook.php(326): call_user_func_array(Array, Array)
#2 /home/s/____________/____________/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(”, Array)
#3 /home/s/____________/____________/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action(‘after_plugin_ro…’, ‘query-monitor/q…’, Array, ‘search’)
#5 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)
#6 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()
#7 /home/s/____________/____________//public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#8 /home/s/____________/____________//public_html/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()
#9 [internal function]: wp_ajax_search_plugins(”)
#10 /home/s/____________/____________//public_html/wp-includes/class-wp-hook.php(324): call_user_func_array(‘wp_ajax_search_…’, Array)
#11 /home/s/____________/____________//public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(”, Array)
#12 /home/s/____________/____________//public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /home/s/____________/____________//public_html/wp-admin/admin-ajax.php(192): do_action(‘wp_ajax_search-…’)
#14 {main}
  thrown

</details>

**Comment by ninetyninew** [comment]
We have received a report from an extension customer of this, they mention it occurs not just for our extension specifically but others as well.

>In the past few days, we have received several emails reporting the same fatal error, all related to different plugins. Typically, this error occurs shortly after a plugin is updated and tends to disappear after a couple of days, likely due to being resolved on its own. Despite these notifications, the site continues to function without any apparent issues.

I have let the customer know about this issue, they may add additional information here, I don't want to share their full debug log, but the start of it is:

```
{
"error": {
"type": 1,
"file": "/home/customer/www/[retracted]/public_html/wp-content/plugins/woocommerce/src/Packages.php](http://[retracted]/public_html/wp-content/plugins/woocommerce/src/Packages.php)",
"line": 260
},
```

**Comment by JosKlever** [comment]
I just had a client's site with the same error. This was apparently triggered by a search:
`/wp-admin/plugins.php?s=poly&pagenow=plugins&plugin_status=all&pll_ajax_backend=1`

**Comment by PanosSynetos** [comment]
@woocommerce/somewherewarm is working on a fix

**Comment by stevenolsthoorn** [comment]
I had the same issue, but was able to solve it by deactivating plugin Pixel Your Site. But that same plugin is working without issues on another website of ours, with the same theme and 80% of the same plugins.

Waiting for WooCommerce to release a fix..

**Comment by vapvarun** [comment]
We are also facing the same issue. 

```Error Details
=============
An error of type E_ERROR was caused in line 260 of the file /home/685604/pbthexbhxm/public_html/wp-content/plugins/woocommerce/src/Packages.php. Error message: Uncaught Error: Call to a member function get_column_count() on null in /home/685604/pbthexbhxm/public_html/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 /home/685604/pbthexbhxm/public_html/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins()
#1 /home/685604/pbthexbhxm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /home/685604/pbthexbhxm/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/685604/pbthexbhxm/public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action()
#4 /home/685604/pbthexbhxm/public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row()
#5 /home/685604/pbthexbhxm/public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()
#6 /home/685604/pbthexbhxm/public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#7 /home/685604/pbthexbhxm/public_html/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()
#8 /home/685604/pbthexbhxm/public_html/wp-includes/class-wp-hook.php(324): wp_ajax_search_plugins()
#9 /home/685604/pbthexbhxm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /home/685604/pbthexbhxm/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/685604/pbthexbhxm/public_html/wp-admin/admin-ajax.php(192): do_action()
#12 {main}```

**Comment by mnick73** [comment]
Hello,

Same issue.

Uncaught Error: Call to a member function get_column_count() on null in /public_html/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('woocommerce-lea...')
#1 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /public_html/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'woocommerce-lea...', Array, 'search')
#4 /public_html/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)
#5 /public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()
#6 /public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#7 /home/n

**Comment by ericfri** [comment]
9104802-zen

**Comment by rbgly** [comment]
9118011-zen

**Comment by ojosejefferson** [comment]
I have the same problem 

`An error of type E_ERROR was raised on line 260 of file /wp-content/plugins/woocommerce/src/Packages.php). Error message: Uncaught Error: Call to a member function get_column_count() on null in /wp-content/plugins/woocommerce/src/Packages.php:260](wp-content/plugins/woocommerce/src/Packages.php:260)
Stack trace:`

**Comment by charly06** [comment]
> I had the same issue, but was able to solve it by deactivating plugin Pixel Your Site. But that same plugin is working without issues on another website of ours, with the same theme and 80% of the same plugins.
> 
> Waiting for WooCommerce to release a fix..

Same issue here. I disabled the Pixel Your Site plugin, but the issue still exists, but thx for the potential hint.

**Comment by nathanss** [comment]
This is fixed by https://github.com/woocommerce/woocommerce/pull/53438 and will be released in 9.5.

**Comment by thisissandip** [comment]
9097194-zen

**Comment by thisissandip** [comment]
9148476-zen
