### ISSUE TITLE
[CFE]: Revert: Checkout: Add loading placeholder and payment method toggle

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#53088]
### Which release does this request apply to?

9.5

### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/53085

### Why do these PRs need to break the code freeze?

The impact is that the original feature might break the checkout process for payment methods that have a similar flow with Square, which programatically selects a payment method. As the PR collapses the list, when trying to select an element via JS, the element is no longer in the page. 

### What is the consequence if this exception does not get included?

This introduces shopper confusion, as it’s not straightforward to shoppers that they need to toggle the Payment options list and reselect the initial chosen payment, ultimately impacting the order placement. This will impact a crucial part of conversion for checkout which is why we think this is important.

### What is the plan should defects to be discovered in these PRs ahead of final release?

Reverting this PR is a possibility, but likely we'd need to explore a fix to this issue instead of reverting the original PR. I find this unlikely as long as we carefully apply a revert of the original functionality.

### How should this change be communicated in the release post on the public developer blog:

I don't think this will need to be communicated as it's a revert of changes that have not been released before.

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

Anyone from @woocommerce/rubik specifically @ralucaStan and @senadir have the best knowledge of the issue.

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk` when my request is approved

### Closing checklist for Solaris

- [x] Escape analysis completed
- [x] PR merged to target `release` branch
- [x] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [x] Followup issue if any

**Comment by ralucaStan** [comment]
Plugins like Square are performing unsupported DOM operations to select payment methods, which isn’t aligned with WooCommerce’s intended API usage.

A public API (__internalSetActivePaymentMethod) exists but is marked as internal and not documented for external use. Plugins should be encouraged to use this or similar data store mechanisms instead of DOM hacks.

The team agreed to revert the change for the sake of store stability, with plans to reintroduce it when we offer a public API to persist payment selection. 


Next Steps:
- Develop a mechanism for persisting payment selection. Remove the internal prefix from `__internalSetActivePaymentMethod` to make them officially available for external use. https://github.com/woocommerce/woocommerce/issues/53306
- Inform third-party developers of the changes through advisories and documentation updates.
- Add back the #52044 change
