### ISSUE TITLE
[Enhancement]: Notify the merchant when the page being edited is the default cart or chekout page

### ISSUE THREAD

**Issue by alexflorisca** [woothemes/woocommerce#53191]
### Describe the solution you'd like

This came from a comment in WC slack:

> If this is the answer, I feel like when a cart/checkout block is added to page, if that page isn't the one defined in Woo settings it should show a notice in the editor, this issue took me a good half day to figure out when it happened to me the first time :slightly_smiling_face:

I think this is a good idea and would help merchants and developers alike easily distinguish which page is the default cart or checkout page if there are multiple pages with the cart and checkout blocks

### Describe alternatives you've considered

not doing anything

**Comment by medavidallsop** [comment]
Just for clarity here, this came up because someone could be doing some custom PHP and using `is_cart()` or `is_checkout()` conditionals, and those failing in a cart block as using it on a page not defined as the cart in Woo settings (e.g. you are keeping the classic cart active while testing block cart on a new page)

**Comment by alexflorisca** [comment]
Closing this because a similar thing exists that was introduced in https://github.com/woocommerce/woocommerce-blocks/pull/6867/
