### ISSUE TITLE
Investigate cause of recently failing WC Shipping & Tax tests in daily runs

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#53371]
Our daily tests for WC Shipping & Tax had been failing since [Nov. 29th](https://woocommerce.github.io/woocommerce-test-reports/#/daily/20241129-trunk). The two failing tests are:

```
 merchant/create-restricted-coupons.spec.js#Restricted coupon management can create new excludeProductBrands coupon

merchant/page-loads.spec.js#WooCommerce Page Load > Load Marketing sub pages Can load Coupons
```

We should investigate if it's a valid bug, or if it just needs updating the tests.

Update: Seems to be related to https://github.com/woocommerce/woocommerce/pull/53176

**Comment by message-dimke** [comment]
### Restricted coupon management can create new excludeProductBrands coupon

The problem is with the test. When creating a coupon with a brand selected, the brand must pre-exist. There is no default brand like the 'Uncategorized' category.

Adjusting the test to pre-create a brand solves the issue.

### WooCommerce Page Load > Load Marketing sub pages Can load Coupons

Since it is still possible to create a coupon without any usage restrictions selected, the failing "excluded brand" coupon test was creating a coupon, making the Coupons page list it, and failing to assert it is empty. 

https://github.com/woocommerce/woocommerce/pull/53535
