### ISSUE TITLE
Unable to display complete order status summary

### ISSUE THREAD

**Issue by wangchengPPP** [woothemes/woocommerce#53632]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

![Image](https://github.com/user-attachments/assets/fed1b56f-0c27-4548-996e-80cb34d94d65)
this happenend after i imported the orders with the WebToffee lmport  Export (Basic) plugin. actually i have more than 1000 orders, but it only display the " ALL , Processing , Failed" . I did flush the buffering and exit the woocmmerce and sign in again ,no help. 

### Expected behavior

![Image](https://github.com/user-attachments/assets/fed1b56f-0c27-4548-996e-80cb34d94d65)
this happenend after i imported the orders with the WebToffee lmport  Export (Basic) plugin. actually i have more than 1000 orders, but it only display the " ALL , Processing , Failed" . I did flush the buffering and exit the woocmmerce and sign in again ,no help. 

### Actual behavior

![Image](https://github.com/user-attachments/assets/fed1b56f-0c27-4548-996e-80cb34d94d65)
this happenend after i imported the orders with the WebToffee lmport  Export (Basic) plugin. actually i have more than 1000 orders, but it only display the " ALL , Processing , Failed" . I did flush the buffering and exit the woocmmerce and sign in again ,no help. 

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/fed1b56f-0c27-4548-996e-80cb34d94d65)
this happenend after i imported the orders with the WebToffee lmport  Export (Basic) plugin. actually i have more than 1000 orders, but it only display the " ALL , Processing , Failed" . I did flush the buffering and exit the woocmmerce and sign in again ,no help. 

### WordPress Environment

![Image](https://github.com/user-attachments/assets/fed1b56f-0c27-4548-996e-80cb34d94d65)
this happenend after i imported the orders with the WebToffee lmport  Export (Basic) plugin. actually i have more than 1000 orders, but it only display the " ALL , Processing , Failed" . I did flush the buffering and exit the woocmmerce and sign in again ,no help. 

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @wangchengPPP! I am sorry to hear about the issue you are experiencing. Because the orders were imported using [Import Export Suite for WooCommerce by WebToffee](https://woocommerce.com/products/import-export-suite-for-woocommerce/), please contact our support that will help further with that plugin. This repository is for reporting issues related to WooCommrce directly. You can contact support by clicking on "Get support" on the right-hand sidebar on [Import Export Suite for WooCommerce by WebToffee](https://woocommerce.com/products/import-export-suite-for-woocommerce/) page. I am closing this issue since it is best to be resolved on the plugin side of things.
