### ISSUE TITLE
Blueprint: Import - Implement drag and drop uploader component, schema validation, and conflict check

### ISSUE THREAD

**Issue by moon0326** [woothemes/woocommerce#53679]
Figma:[Y5pUYSJPsGEud1vknUZhi8-fi-3814_18301](https://href.li/?https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/?node-id=3814-18301)

Requires https://github.com/woocommerce/woocommerce/issues/53803

While #53803 is in progress, we can use the following plugin to mock the endpoints:

Plugin: https://gist.github.com/moon0326/b52cd1aa534952af80f7361ba4492730

This plugin creates the following endpoints:

- POST /wp-json/wc-admin/blueprint/queue
- POST /wp-json/wc-admin/blueprint/process

Replace the current input loader with presented drag and drop uploader. 

## Acceptance Criteria

- Implement drag and drop upload.
- When a file is selected, upload it immediately to run validation and conflict check.
  - If any errors are detected, display them (Y5pUYSJPsGEud1vknUZhi8-fi-3814_17888).
  - If any conflicts are detected, set a state so that it can be used when the user clicks on `Import` button.

**Comment by rjchow** [comment]
@moon0326 I was looking at this issue and was wondering if there's a mismatch in API and the design -

My quick survey found that `/blueprints/import` [API](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/Blueprint/RestApi.php#L126) synchronously uploads and carries out the import step, whereas it looks like the Figma shows the upload and import as separate steps?

The Figma design implies that there's a need to persist the uploaded blueprint and return a reference to it so that the UI can execute the import step in a follow up API call

**Comment by moon0326** [comment]
@rjchow You're right. We need to update the API to support the new design. I'll make a new issue soon.
