### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught Exception: Invalid order. in | abstract-wc-order-data-store-cpt.php:105

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53732]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[link to code](https://github.com/woocommerce/woocommerce/blob/5f04212f8188e0f7b09f6375d1a6c610fac8a631/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php#L105)

```
PHP Fatal error:  Uncaught Exception: Invalid order. in /../wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:105
Stack trace:
#0 /../wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
#1 /../wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(114): WC_Data_Store->read(Object(WC_Order))
#2 /../wp-content/plugins/woo-razorpay/includes/razorpay-webhook.php(158): WC_Abstract_Order->__construct('3001011287')
#3 /../wp-content/plugins/woo-razorpay/includes/razorpay-webhook.php(103): RZP_Webhook->paymentAuthorized(Array)
#4 /../wp-content/plugins/woo-razorpay/woo-razorpay.php(986): RZP_Webhook->process()
#5 /../core/6.7.1/wp-includes/class-wp-hook.php(324): razorpay_webhook_init('')
#6 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#7 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /../core/6.7.1/wp-admin/admin-post.php(61): do_action('admin_post_nopr...')
#9 {main}
  thrown in /../wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 105
``` 

### Expected behavior

No fatal error

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don’t have steps to reproduce, but 829 Fatals of this type were observed on Fri Dec 6, 2024 across 4 sites.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
I'm going to close, but please shout out if anyone feels I'm mistaken.

> PHP Fatal error:  Uncaught Exception: Invalid order.

This is a likely outcome if you try to create an order object but supply an invalid ID. For example, using code like this:

```php
# Let's assume 99999 does not exist, or is not an order entity.
new WC_Order( 99999 );
```

You can see something similar to the above in [*earlier* versions of RazorPay](https://plugins.trac.wordpress.org/browser/woo-razorpay/tags/1.6.5/includes/razorpay-webhook.php#L136) (mentioning RazorPay, because we can see references to it in the stack trace). If third parties do this, it's up to them to be responsible and use a try/catch structure or some other method of handling this. Instead, it is generally preferred instead that they use `wc_get_order()`, like this:

```php
# Again, 99999 does not exist or is not an order entity.
wc_get_order( 99999 );
```

This is also what [recent versions of RazorPay do](https://plugins.trac.wordpress.org/browser/woo-razorpay/tags/4.6.9/includes/razorpay-webhook.php#L157), and it won't lead to an exception (at least, not in scenarios like this one). Other problems are still possible because they don't check if they are subsequently working with a valid order object, but we've [alerted them to this possibility](https://wordpress.org/support/topic/consider-defensive-coding-when-retrieving-order-objects/), and there isn't really much more that we can do about this on our side.

- I don't feel there is any further action for us to do here (in this case, throwing an exception when we do feels pretty reasonable and, as described, we provide a better path for 3PDs to follow in any case).
- Any impacted RazorPay users can probably just be encouraged to update their copy of that plugin.
