### ISSUE TITLE
[Enhancement]: checkout: Ability to set multiple addresses

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#53814]
### Describe the solution you'd like

Hi woocommerce team,

It would be great if users could add and edit their addresses on the checkout page. Alternatively, they can also manage their addresses in My Account > Address and edit or delete them if they wish.

### in Checkout
At checkout, users can add, delete and also edit their address.

![Image](https://github.com/user-attachments/assets/36c60dda-917c-4f58-aa31-782c14ec6779)

### in My Account > Address
An interesting feature here is that the user can choose their default address. For future purchases, the desired address will be selected as the default at checkout.

![Image](https://github.com/user-attachments/assets/6c372e41-f44a-4ce9-9369-49754cb224e9)

### Describe alternatives you've considered

I saw this on a dedicated website which was very efficient.

### Additional context

-

**Comment by natko1** [comment]
Exactly, more useful features for a change...

**Comment by wavvves** [comment]
Hi @79ho3ein thank you for opening the issue, indeed this is a common and useful feature nowadays. For now it is outside the plans to have this in core since there are already plugins offering it ([example](https://wordpress.org/plugins/themehigh-multiple-addresses/)), but we will be evaluating the compatibility with the new Checkout Blocks experience re-assessing what steps to take.
I'll close the issue for now.
