### ISSUE TITLE
Stock is not reduced when an item is added to the cart

### ISSUE THREAD

**Issue by michaelmcmillan** [woothemes/woocommerce#5966]
When an item is added to the cart the quantity stays the same. It's only when the payment has been successful that the stock is reduced. Consider this scenario: 

"User one" and "user two" have added the last available t-shirt to their carts. They proceed to place the order. At this point one of the two users are going to get [this](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L434-L437) error. 

From a users perspective this is pants-on-head retarded. Up to this point everything is filled out and ready to go - there's no indication that the product is unavailable, but the user is refused because someone else "beat them to the checkout". If you think of a real physical cart, this would never ever happen. When a product is placed in the cart it should always be available to the customer.

Let me be clear: The stock itself should not be altered with, but there should be some sort of flag that temporarily marks an item as reserved.  

This is, by a wide margin, the most noodle-bending counterintuitive thing I have ever seen. I sincerely hope I've missed something, even though I've been through your classes and settings several times.

**Comment by robsaa** [comment]
Im facing the same problem and I think this would be a nice option in the core.

**Comment by stevednm** [comment]
I agree with Michael McMillan's original comment.

In a real store, if someone takes the last item of a product off the shelf and places it in their cart, none of that item remain on the shelf for someone else to put in their cart. If the cart is abandoned for a time, a store clerk returns the unbought item to the shelf.

I believe that's the way woocommerce should handle stock management, by reducing the number of available items when someone places the items in their cart, instead of doing so only when the item is actually bought. Then a store owner can set a reasonable time-out for the cart after which items in the cart are returned to inventory.

Because WooCommerce manages stock by substracting from the available stock quantity only after a product is bought, it also negatively impacts store owners who prefer to merely authorize the payment transaction instead of completing the payment (sometimes store owners prefer to wait until they are ready to ship the item before completing the payment). For example, with the PayPal payment gateway, one can choose "authorize" rather than "capture." Authorize means that the store owner can review the order, sometimes days later, before capturing the payment (before actually moving the money from the customer's account to the store owner's account). However, because WooCommerce leaves the item in stock until it is actually bought (until the payment is "captured"), another person could conceivably buy the same item even if the previous item was the last one and there are technically none left or available.

I agree with others that WooCommerce should seriously consider managing stock by subtracting items from inventory as they are placed in a cart, and the store owner can determine how much time to give the customer to complete his shopping and proceed through the checkout process before the contents of his cart are returned to inventory. (2 hours seems like more than enough time to me personally, although others' cart-timeouts will of course vary).

**Comment by roykho** [comment]
@stevednm 

I believe stock should not reduce when it is merely added to the cart.  If you did it this way, you are prone to lose sales.  Although this is not to say some stores may want it this way but I don't believe it will be majority.

In addition, your statement about a transaction being "authorized" only, that is not correct.  It does reduce stock on an order that is only "authorized".

**Comment by stevednm** [comment]
@roykho says: "I believe stock should not reduce when it is merely added to the cart. If you did it this way, you are prone to lose sales." -- On the other hand, as an ecommerce store operator for 8 years, I know that there will be angry customers because often I have only one or 2 of a premium (much desired) item in stock. I would rather lose a few sales than deal with angry customers who were not able to purchase something they rightly considered to be in stock at the time they placed it in their cart. Just my opinion as a store owner.

**Comment by WordCommerce** [comment]
If stock reduced when an item added to the cart probably small store owners will lose customers due to lack of stock.

**Comment by michaelmcmillan** [comment]
So let it be an option then, I would never suggest to force this upon
anyone.
7. feb. 2015 23.33 skrev "WordCommerce" <notifications@github.com>:

**Comment by stevednm** [comment]
Perhaps the store operator should be allowed to choose which method of stock management he or she prefers, and be able to choose between the two.

**Comment by michaelmcmillan** [comment]
Yes, that is what I am suggesting.
7. feb. 2015 23.49 skrev "stevednm" <notifications@github.com>:

**Comment by stevednm** [comment]
The issue of cart-based stock management (rather than sale-based as in woocommerce, which can create customer-service problems) is important to me as an ecommerce store owner, so I am investigating alternatives to woocommerce, including wpecommerce. From the stock-management documentation at wpecommerce.org:

> The first step is to apply quantities to your products (see below on how to do this).
> As your buyers put products into their cart the stock level for this product will decrease,
> once checkout is successful and all products are paid for these stock levels will be
> deducted permanently. If a payment is unsuccessful or the buyer leaves your store
> (closes the browser) with products in their cart these quantities will be reset after an hour.

I believe that this is a better way to handle stock management from a store-owner's and customer's perspective, so despite an investment in woocommerce extensions, I may try wpecommerce, and I urge WooCommerce programmers to give stock management additional consideration. Thank you.

**Comment by Kenshino** [comment]
@stevednm WooCommerce already does this. You get to set a specific amount of time before cart quantities are returned.

**Comment by stevednm** [comment]
@kenshino Woocommerce (in my store, at least) does not deduct an item from stock when a person places it in their cart, or at least does not *display* the deducted quantity. For example, if I have 2 of a particular item in stock, and add 1 to my cart, the quantity listed in stock for that variation (it is a variable product) remains at 2. Why would this be so?

Are you saying that if I tried to add 2 more of the same item to the cart, based upon the quantity in stock displayed in the storefront, WooCommerce would issue a message saying that I could only add 1, or that there were not 2 in stock? If so, then indeed, WooCommerce deducts from stock when someone adds an item to the cart. But if that reduced stock number is not displayed to the customer (if the quantity displayed in the storefront for that product remains at 2 instead of 1 until the first of the 2 items of that product is actually purchased), then wouldn't you regard that as confusing to the customers?

I'm not sure I understand how WooCommerce is handling the stock management in the background, compared to the stock quantities that are displayed in the storefront. If I were to refresh the webpage, would the displayed stock quantity indicate the decrease (the reduced stock)? I think I'll test that right now. Thank you Kenshino for your comments.

**Comment by bluelotusworks** [comment]
This has been an interesting read as we face a problem similar to others in this thread. We're in the middle of developing a site for exhibitor space rentals where exhibitors will be able to choose their own exhibit space (think trade shows, festivals, horse shows, dog shows, etc). That means we'll be using variable products with potentially hundreds of variations, but all variations will have quantities of one. We run a very significant risk of angering a large number of customers clambering for "choice" spots at the time space rentals open because products aren't removed from inventory when added to a cart.

While we generally use WooCommerce for our eCommerce projects, we've struggled with this stock management issue and came upon this thread. For this project, and as noted above, WP eCommerce handles stock in a way that meets our requirements with no modification. Unless WooCommerce has an option to handle stock management in a similar manner by the end of this month, we'll have to change gears and do this project with WP eCommerce. A shame because we've identified several commercial extensions we need for this project. If WooThemes or one of its extension development partners can develop something quickly, we would really appreciate it so we don't have to move to WP eCommerce. We would even consider providing a reasonable level of sponsorship in exchange for a lifetime license. WisdmLabs is working on an extension (http://wisdmlabs.com/empty-cart-timer-woocommerce-plugin/) that appears to meet our needs, but they've missed their release date at least twice.

**Comment by jamesgol** [comment]
After reading about this issue it sounded like a fun project to tackle so I threw this code together into a free plugin.  

https://github.com/jamesgol/woocommerce-cart-stock-reducer

Send me any feedback direct or via github.

**Comment by stevednm** [comment]
@jamesgol -- Thank you so much for doing this, James. I can't test your extension right now because  I injured my left shoulder a few days ago and closed my ecommerce site until it heals. It's painful even to type this little bit of text. I will certainly test it when I reopen my website though, and I hope that others will test it and comment on it in the meantime.

Would you mind describing how your extension works, and how it interacts with WooCommerce's current default sale-based (rather than cart-based) stock management? I would very much like to know how the extension works even though I can't test it right now. Thank you very much.

**Comment by jamesgol** [comment]
@stevednm Hope your shoulder heals up soon!

I only have a few minutes right now, but basically my plugin doesn't actually adjust the inventory count in the database at all.  It hooks into a few places and makes the code think the inventory count is adjusted based on a count of items in all of the carts for items that are set as managed stock.

There are currently 2 configurable settings from the admin interface:
* Minimum Stock to Skip Check: If there are greater than this many items in inventory then it doesn't go searching the carts to update the quantity
* Pending Order Text: Text to be displayed instead of 'Out of Stock' when there are items in inventory but locked in someones cart

Still need to get variable products working and I've got a cool cart item expiration in progress, but everything else is very functional now.  Would love some more testers, feedback, and suggestions.

It's also available from wordpress.org now: https://wordpress.org/plugins/woocommerce-cart-stock-reducer/

**Comment by bluelotusworks** [comment]
@stevednm get well soon. This is an inspired solution! Adding the settings to the WooCommerce settings integration tab is a smart touch. We tested on the project that drove our interest in this issue last night. It's rock solid on simple product pages with no conflicts on a project with 30+ custom functions and 60+ plugins (yes they're all needed but we'll be converting small ones to custom functions). We need to test Add to Cart on category pages tonight. As @jamesgol said its not ready for variable products because this is what happens:

If you go to a product page and any variable is pending in another cart, you get the pending order text message and purchase is blocked for all variables. And, if its initially available, but its added to another cart first, you get the pending order text message and the product is still added to the cart, so it becomes a race to the checkout line...if inventory is only one it can still only be purchased once. After checkout, all variables with inventory are available again since the cart session is cleared.

Also, we tested with W3 Total Cache page caching off (we don't use database caching, no need with an SSD). We need to test further, but we think product page and category exclusions are probably a best practice for affected products if page and/or database caching are used.

**Comment by dafro2** [comment]
once this is ready for variable products it is exactly what we all needed!
Hope you can finish it soon, i will implement it then directly!

**Comment by stevednm** [comment]
@jamesgol -- James, because almost all of my products are variable products (I run an exotic plants nursery in which each plant is sold in 4 different sizes or maturity levels), I won't be able to adequately test the plugin right now, but am eager to test it when/if you are able to get it working with variable products, and will be happy to help sponsor (donate money toward) this development. Thank you so much for working on this issue.

**Comment by stevednm** [comment]
@aj-adl -- Alex wrote: "I can understand the valid use case for this, but (in my personal, relatively worthless opinion) I don't think this should be in core. A lot of edge cases ..."
---
Alex, I'm not sure I understand. If you don't mind, could you describe one of those possible edge cases in which sale-based stock management (as woocommerce currently defaults to) is preferable rather than cart based management (or a combination of the two, such as James's plugin)?

Thank you.

**Comment by jamesgol** [comment]
@stevednm / @dafro2: The variable product code is in and also cart expiration.  I pushed out version 0.5 to github and wordpress.org yesterday.  There are a couple of minor issues that @bluelotusworks helped uncover that I'll be fixing up today.

**Comment by dafro2** [comment]
the only argument against this function would be that once 2 People are trying to buy the same last Piece in stock and one of These 2 potential buyers blocks the last Piece with adding it to his/her cart the other potential buyer thinks it is sold out and will leave the shop. But if you actually manage to sell out that amount and have a few last pieces in stock + have 2 customers fighting over one piece you should not worry about the last piece because others will come and buy the returning product again. If we would imagine that 10 potential customers block 10 last pieces in qty and do not buy it in the end,it is a different matter but even then one could think about a cart timer which is very common on lots of pages and also myshopify works the same way. I would prefer a cart timer of 5 minutes. Awesome would be if this cart timer is refreshing everytime the one having the Piece in cart loads a new page from the same shop. If he leaves or has >5min the product in his cart without refreshing the page or going to a subpage of the shop it should time out, and the item should return to stock again.

i dont know why one could complain about this function if it would be optional???
be happy that someone took the time to put down a code and help us out with this matter.

**Comment by bluelotusworks** [comment]
Version 0.5 on the WordPress repository is pretty rock solid, including the cart expiration. Last night, I identified four UX issues with pending order text behavior that are outlined at https://github.com/jamesgol/woocommerce-cart-stock-reducer/issues/5. Those issues may be edge cases for some web sites, but they're part of "normal" expected user behavior for others. For now, I addressed the issue by changing the default pending order text to "This item is no longer available for purchase at this time due to pending orders. Pending orders include items added to your cart."

For everyone's benefit, I've added a few screenshots to this comment: the integration settings, a product page after an item is added to a cart, a product page when stock isn't available due to a pending order and an expired cart message. I've got to take time off testing until Sunday, but will be back at it then, including checking out the new cart timer commit made to the repository.

@jamesgol you're welcome to use these to cover the screenshot to do.

![wc-csr-integration](https://cloud.githubusercontent.com/assets/6967621/6313351/cd3cd5a0-b962-11e4-9ecc-422701f508e7.jpg)
![wc-csr-add-to-cart](https://cloud.githubusercontent.com/assets/6967621/6313349/cd251398-b962-11e4-9db2-f585d01f29d2.jpg)
![wc-csr-no-inventory-pending-orders](https://cloud.githubusercontent.com/assets/6967621/6313352/cd3e4e62-b962-11e4-9147-686c9db62619.jpg)
![wc-csr-expired-cart](https://cloud.githubusercontent.com/assets/6967621/6313350/cd3b3830-b962-11e4-9bb6-657f413f8fa2.jpg)

**Comment by mikejolley** [comment]
@BFTrick what are you thoughts on this item now, given there is a plugin outside of core? I will move out of the milestone until decided.

**Comment by BFTrick** [comment]
Well first I'm super happy @jamesgol wrote this plugin. Super helpful for people who need this functionality.

I think this is an edge case to start with. We'd had a support nightmare having to deal with two different inventory systems and all of the store owners who wouldn't understand the differences / finer points.

Luckily this plugin solves the issue so I don't think we need to do anything in core. I vote close.

**Comment by bluelotusworks** [comment]
I think this is much less of an edge case (i.e., a much bigger deal) than you think and a brilliant solution that doesn't affect WooCommerce core functionality as it currently exists. IMHO, it has applicability for any WooCommerce site that deals with limited quantity products and it isn't hard to use. As much as I'd like to see you give @jamesgol some kudos by integrating this into core, we all have our priorities. Since this functionality was important enough to include in a milestone, perhaps you could assign someone to help James with code maintenance, maybe even include it in the WooCommerce extensions listed at WooThemes.

FYI, I just gave it a thorough stress test in production with the launch of holdmyshowspace.com yesterday and it works flawlessly. Based on testing and user input, I've got a couple of simple UX changes to suggest as soon as I get a few spare moments...hopefully tonight.

@jamesgol, assuming you're following, thanks again!

**Comment by michaelmcmillan** [comment]
Not implementing this in core is just lazy.

tir. 24. mar. 2015, 23.10 skrev BlueLotusWorks (Bob De Young, CEO) <
notifications@github.com>:

**Comment by BFTrick** [comment]
I just processed a survey from 1,700+ users (including store owners, freelancers, and developers from larger firms) last week and not a single one mentioned this as a problem. Based on that data alone I can say that it _is_ an edge case.

In fact only 10 of them even mentioned the word `inventory` and it wasn't even related to this issue. I'd say our inventory system is pretty solid for right now.

The vocal minority does not outweigh the voice of 1,700+ users. When our users start complaining about this we'll be happy to reinvestigate.

**Comment by bluelotusworks** [comment]
Patrick, please don't view this as challenging the research per se. However, I know I didn't get asked to participate. And, if you didn't ask a pointed question regarding the value of a cart timer or alternate inventory reduction method, you can't rely on the survey to justify that it's not an issue. Users generally accept what's in the box until you show them what's outside of it.

**Comment by mikejolley** [comment]
Even though this is out of the milestone, I will place it on our roadmap board to keep a record and to get votes. We can revisit in the future if needed. https://trello.com/c/VGIXzv5s/65-cart-stock-reducer
