### ISSUE TITLE
Layered Nav: relation between attributes

### ISSUE THREAD

**Issue by jrusinek** [woothemes/woocommerce#6058]
WC Query is bugged, as well as the Layerd Nav widget.

I made a comment to the blamed commit: https://github.com/woothemes/woocommerce/commit/081bef7f6b9644e8080db772b53c24f1c28c7543#commitcomment-7453590

**Comment by ascottmccauley** [comment]
I'm late to the party, but I can't find anything else about this, here or on trello, but the layered nav really doesn't work like most e-commerce solutions.
And to piggy-back on this problem, it seems more like the layered nav should be treated as an exclusionary instead of inclusionary, since by default you start out showing all products, and then filter products out.
For example, if you load a store that has shirts that are {blue, red, green} and {S, M, L}, all possible combination of those are shown to start, and a user would expect that selecting (or de-selecting) "blue" would just leave all possible combinations of {red, green} and {S, M, L}.

Of course the only problem with this method is deciding if a product in that category with none of the possible attributes would show after deselecting a filter (bad store management).

(sorry if this is the wrong place for this)

**Comment by ascottmccauley** [comment]
Here is a quick stab at creating my own version of the layered nav that auto-populates with all relevant attributes, and excludes them as the user selects each one. The real difference is the `'operator' => 'NOT IN'` for the `tax_query`.
Sorry I don't have time to draw up a pull request right now.

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/7806
