### ISSUE TITLE
Excess post meta?

### ISSUE THREAD

**Issue by kieranbarnes** [woothemes/woocommerce#6394]
Two customer sites have a postsmeta table in excess of 600,000 records. 
Woo creates **lots** of post meta entries for each product, all the standard stuff; length, weight, height etc
Both customer sites don't use a lot of this meta, as I guess most other sites don't.

Queries on this table were slow due to the table size. (#6378) Clearing out the unused (empty) postmeta records was the difference between a 5 second page load and a 1 second page load.
Each query deleted about 250,000 records (This would depend on the product types for sale).

I ran ```DELETE FROM xx_postmeta WHERE `meta_value` = ''; ``` however I know Woo will add all the excess postmeta back in next time the product is updated. 

Do we need to save all this data by default when saving or editing? Can we not check if the values exist first?

I'm experiencing Woo being quite slow on large stores (#51 #6378 #5825 #5527 #5528 #4827), perhaps this is worth a look at?

**Comment by kieranbarnes** [comment]
A inelegant work around for now, deletes empty post meta nightly.
Probably slow if WP_Cron isn't offloaded to the system cron.

```
// comment out to delete event
//wp_clear_scheduled_hook('lwd_custom_postmeta_cleanup_event');

add_action('lwd_custom_postmeta_cleanup_event', 'lwd_custom_postmeta_cleanup');
function lwd_custom_postmeta_cleanup_activation() {
	if ( !wp_next_scheduled( 'lwd_custom_postmeta_cleanup_event' ) ) {
		wp_schedule_event( current_time( 'timestamp' ), 'daily', 'lwd_custom_postmeta_cleanup_event');
	}
}

add_action('wp', 'lwd_custom_postmeta_cleanup_activation');
function lwd_custom_postmeta_cleanup() {
	global $wpdb;

	$deleteEmptyPostMeta = $wpdb->delete( WP_TABLE_PREFIX.'_postmeta', array('meta_value' => '') );

}
```

**Comment by helgatheviking** [comment]
Similarly, I think checkboxes are also saved as 'yes' or 'no'... could they possibly be saved as 'yes' if checked and deleted otherwise?

**Comment by barrykooij** [comment]
The options are autoloaded so when updated to 'no' WP can do the check in PHP. If we delete the meta values it might be a query per check. I'm not 100% sure on this so I will run some tests on it.

**Comment by mikejolley** [comment]
Deleting ALL empty meta isn't something I'd like to include just yet - we can revisit this when we look at the data manipulation API we've been considering. The main reason is, some of the 'empty' meta has purpose. 

For example, _sale_price_dates_from/_sale_price_dates_to. Sure one of these data may be empty, but if you delete the meta, this will stop the database query which looks at these values from functioning, because one of the items of data won't exist.

Another example; _total_sales. Again, yes this can be 0 or empty, however, if you remove it, WP_Query will no longer be able to sort by that value for the sort order 'popularity'.

Other values a user may want to sort on; weight, sku etc etc. Delete those keys and this is no longer possible.

Core also cannot control what data extensions store for products. Core includes ~30 meta values for products itself.

If you deletion solution helps and has no side effects in your case, go for it. But I don't think we should force this upon all stores. Overhead of postmeta is something WP needs to tackle.

**Comment by MarcusFuto** [comment]
Would you please write an example of how to delete all the weights that don't have a value? 

Then it should be easy to replicate it for the others right? 

The ones that are excess: length, height, width, weight, downloadable, virtual, stock status, variation description.  

Do you guys know what the _edit_last entry is? Is it important? Otherwise that could go as well since I have tons of them.

I have the exact same problem, and I would definitely benefit from that 4 second decrease in page load time. 

Have searched for a long time so I am so happy to have found this thread.

I am very thankful for help!

**Comment by kieranbarnes** [comment]
@MarcusFuto You'd want to use this in my code above (untested)

```$delete_meta = $wpdb->delete( $wpdb->prefix.'postmeta', array('meta_value' => '_weight', ',meta_value' => '') );```

```_edit_last``` is the last time the item was edited.

**Comment by MarcusFuto** [comment]
Thanks a million for the reply!

I tried the one you sent and I tried to modify it as this(see wp_rings021postmeta):
$delete_meta = $wpdb->delete( $wpdb->prefix.'wp_rings021postmeta', array('meta_value' => '_weight', ',meta_value' => '') );

But I get this error message:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '$delete_meta = $wpdb->delete( $wpdb->prefix.'wp_rings021postmeta', array('meta_v' at line 1

What am I doing wrong? 

Best regards,

Marcus

**Comment by MarcusFuto** [comment]
I realised that it was within a php code to put in the functions.php

Here is a good thread if somebody needs it:

http://iftekhar.net/article/how-to-delete-unnecessary-post-metadata-from-wordpress/

nice! And thanx a lot everybody!

**Comment by surferking** [comment]
Personally I feel at least the following are options and belong in 'terms' table for minimising data duplication where null should not create unnecessary records:

_backorders
_downloadable
_manage_stock
_product_version
_sku
_sold_individually
_stock_status
_tax_class
_tax_status
_virtual

Although I see no reason why they can't all move to 'terms'.

**Comment by gine** [comment]
With this query you can verify what meta_key have the most unused rows:

`SELECT meta_key, COUNT(*) as num FROM `wp_postmeta` WHERE meta_value LIKE '' GROUP BY 
meta_key ORDER BY `num` DESC`

**Comment by designdolphin** [comment]
@mikejolley 
"Deleting ALL empty meta isn't something I'd like to include just yet - we can revisit this when we look at the data manipulation API we've been considering. The main reason is, some of the 'empty' meta has purpose." 

While I understand that, maybe we should reevaluate what some of the purpose of the empty meta is, and how it factors into performance? 

For example one area of improvement I can see is in the way fields are stored in the database:
For example the '_button_text' meta_key. Instead of adding it to every product. Have a standard button text, if that is used don't add the postmeta, only if the field is different from standard add the postmeta to the product post type. 

Pseudocode: 

`
// back end
$main_button_text = 'click me' 
$individual_product_button_text = 'click me instead'

if(!$individual_product_button_text) {
$button_text = $main_button_text;
}

if($individual_product_button_text) {
update_post_meta( $post_id, '_button_text' , $individual_product_button_text);
}

// template
if(!$individual_product_button_text) { 
echo $button_text;
}

if($individual_product_button_text) { 
$button_text = $product->_button_text;
echo $button_text;
}
`

The same/similar goes for some of the other fields like _product_url, weight_, length_

**Comment by thestick613** [comment]
What is the current take on fixing this? I'm seeing a shop with 5000 items having 100k wp_posts and 1.6M wp_postmeta, and the site is getting slower every day.

**Comment by peterfabian** [comment]
Hi @thestick613,

seems like there has been some improvements in this area delivered in 3.6. Is this perhaps something that might help you? 
https://github.com/woocommerce/woocommerce/pull/22773

Btw, do you mean that a shop has 5k products, but 100k posts? What are those other posts? Variations of products? Orders?

**Comment by thestick613** [comment]
They are product variations. Some products have ~100 variations; the prices are updated daily from multiple third parties.
