### ISSUE TITLE
WC_Cart::get_cart_from_session fires before all plugins have loaded

### ISSUE THREAD

**Issue by deltafactory** [woothemes/woocommerce#6873]
Similar to the timing situation reported in #6706, `WC_Cart::init()` fires at init priority 5 and calls `WC_Cart::get_cart_from_session()` - https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L118.

`WC_Cart::get_cart_from_session()` calls a number of filters - in my case, `woocommerce_get_price` which relies on custom taxonomies and more which don't execute until init priority 10.

I'd like to reiterate the importance of waiting until other plugins have been able to establish their hooks. This is the reason `init` exists. `wp_loaded` is the *correct* time for this to happen.

**Comment by barrykooij** [comment]
I think you are right that it should have been priority 10 but since it's priority 5 now and other code will be relying on this being priority 5 we can't just change this.

**Comment by mikejolley** [comment]
I agree with the logic around the change. It would make sense to ensure everything is loaded first. Looking through the code, there are a few dependencies on the cart being loaded at init, but those can also be pushed back to wp_loaded.

Extension wise, the only one I found initially with reliance on init was class-wc-subscriptions-cart.php in Subscriptions by @thenbrent. It has a:

`
add_action( 'init', __CLASS__ . '::get_cart_from_session', 6 );
`

This could potentially break, but I'm not 100% certain since it doesn't manipulate anything loaded in the cart class's get_cart_from_session() method.

Let me merge this in to 2.3 for testing - @claudiosmweb, @barrykooij @maxrice @thenbrent @justinstern @tamarazuk if you spot any issues with this please let me know - can revert if needed.

**Comment by thenbrent** [comment]
> Extension wise, the only one I found initially with reliance on init was class-wc-subscriptions-cart.php in Subscriptions

Always Subscriptions! haha

That's easy enough to change for compatibility and I agree with @deltafactory - having taxonomies setup will be valuable, so it's worth the breakage.

A new hook at the end of `WC_Cart::init()`, like `'woocommerce_cart_initialised'` or `'woocommerce_cart_loaded'` (to match `'woocommerce_loaded'`) would save needing to use the same WP hook and worrying about the priority of that hook.

**Comment by mikejolley** [comment]
@thenbrent there is a 'woocommerce_cart_loaded_from_session' and that seems to be what other extensions are using.

**Comment by thenbrent** [comment]
Thanks!
