### ISSUE TITLE
Bulk editing variable products does not update variations

### ISSUE THREAD

**Issue by DominoTree** [woothemes/woocommerce#6877]
When using the bulk editor, there are several fields that don't seem to update the variations on variable products, such as price and sale price, with no notice.

I'd expect them to update, perhaps with a warning about it potentially being resource-intensive and needing long session lengths to work properly or something.

**Comment by mikejolley** [comment]
So this is to bulk edit all variations of a product from the main screen?

**Comment by claudiosmweb** [comment]
I don't see it becoming possible.

Will make this list full of inputs and fields, and need to load all variations for all products...

**Comment by DominoTree** [comment]
It seems to me that it'd make sense to have it update every input for each variation with the fields already provided.  If you want fields for individual variations, that is easy enough from the product page.

If you fill in something there, it'd make sense to me to use those values for all the variations if you've selected a variable product.

**Comment by DominoTree** [comment]
At the very least, it should do *something* to alert you to its behavior if you are interacting with a variable product.

**Comment by davidamoros** [comment]
+1 on this; I am facing this problem too. On a 300+ product (and 4 variations per product) shop, it is simply unassumible to market a sales campaign from the ui.
Plus, as domino states, the ui seems inconsistent at this point; if I update the sales price by a 10%, and the products dont have really price (because only their variations do!) there's no point to tell that "all products are updated", because they are not really updated.
Also I don't see the field burden that claudios points, the ui could (and should) be the same. From the ui perspective, there's no difference from bulk updating; the output "is the same" - to update a mass of items, and their "children" (variations).

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/issues/6995
