### ISSUE TITLE
Completed order notification failing - Update Status API

### ISSUE THREAD

**Issue by frosty074** [woothemes/woocommerce#6910]
Will the next version of Woocommerce support email order status notifications when updating the status via API?

I have tried the v1 and v2 API. The status updates to 'completed' OK, but email notifications are not sent.
Emails are sent when the status is updated directly from Woocommerce.

Example v2 PUT body:
{"order":{ "status":"completed" }}

**Comment by claudiosmweb** [comment]
Works great for 2.3.

**Comment by mikenolimits** [comment]
I currently have 2.3 and it does not work as expected.

**Comment by maxrice** [comment]
sorry guys, fixed this in the PR referenced. Looks like it was quasi-typo :frog:

**Comment by mikenolimits** [comment]
Sweet, been waiting for this :). Do I need to git pull, or will this be in an upcoming update?

**Comment by mikenolimits** [comment]
Yeah, you may or may not need to adjust the accepted order_status's to included cancelled as well. Sometimes an order gets processed by paypal, and the order appears "cancelled", but the customer actually paid. There's a section in the abstract order class where I had to remove the if block for the order_status check because this random error. but may this pr fixes that too, will check :)

**Comment by maxrice** [comment]
@mikenolimits you'll need to pull from master once this is merged, it should go out in the 2.3 beta too :)

When editing the order there's a check to see if the order needs payment before allowing it to be marked as paid. You should still be able to cancel a paid order though.
