### ISSUE TITLE
WC_Cart tax methods/properties producing misleading results

### ISSUE THREAD

**Issue by leewillis77** [woothemes/woocommerce#6950]
With tax turned on, and product prices set to tax inclusive. I have a cart with a total value of £39.90, which includes £6.37 tax (19%).

The various tax functions in WC_Cart return "odd" results. 

*get_taxes()* - seems OK - returns array(1=>6.3706)
*get_tax_totals()* - seems OK - returns an array of various data, matching the tax calculated
*get_taxes_total()* - seems OK - returns 6.37

But...
*get_cart_tax()* - returns an empty string

The properties are also a bit inconsistent:

*cart_contents_tax* is set to 0
*tax_total* is also set to 0 

So - should get_cart_tax be removed or fixed? If so - what's it expected to return? It still seems to be used in a handful of places.

Should the properties also be fixed - or removed?

There's another possibility that these methods/properties are set under different tax scenarios - in which case it would be really helpful to get that in writing. Happy to pull together a PR if someone can provide a little direction.

**Comment by mikejolley** [comment]
get_cart_tax():

`
Gets the cart tax (after calculation).
`

This particular method/variables are only populated after calculation during checkout. From this code in the cart class:

`
// Only calculate the grand total + shipping if on the cart/checkout
if ( is_checkout() || is_cart() || defined('WOOCOMMERCE_CHECKOUT') || defined('WOOCOMMERCE_CART') ) {
`

I believe the main reason is so that shipping + fees are only calculated when needed (during checkout). https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L1288

Hope that explains it - if you think the methods need more inline info, or renaming etc please let me know or send a PR.
