### ISSUE TITLE
Ship to a Different Address Checkbox Logic

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce#7068]
The ship to a different address checkbox is setup for new customers, and it does it's job there well.

I think that it could be a lot clearer with a returning customer with an account, however. 

If I have a different address set than my billing address, it will use that default shipping address when the box is not checked. This can create confusion, as the box to ship to a different address is not checked, yet it ships to a different address than the billing. 

If the billing address and shipping address are the same, the checkbox is phrased perfectly.

I think that if the wording on the box were changed conditionally to when a customer has a differing billing and shipping address to say something like "Ship to a new address", then it would be much clearer for the customers.

**Comment by mikejolley** [comment]
I don't see how it could be confusing in the context - it's right next to a set of address fields just left of it. Any other address that are or are not on the account are irrelevant because they are not mentioned nor displayed. @jameskoster?

Conditional logic shouldn't be used here IMO. It's bloat and not all users are going to agree. If the label is 'confusing' change the label for all users so checkout is consistant.

**Comment by slash1andy** [comment]
The ticket is here, so you can see a bit more background: #247013 

Maybe conditional logic is not the way to go, but it is (to me) a really confusing way to state that we will use the address that they have on file. If I were checking out, I would assume that it would be sent to my billing address, not the shipping address that is on file (since it doesn't show any address on file).

**Comment by mikejolley** [comment]
I just read the ticket - leaving it unticked does not use an account on file - it copies the billing address to the shipping address. If its an issue, I certainly cannot replicate it on 2.3 or 2.2 :)
