### ISSUE TITLE
High Scale Read/Write Operations for Large WooCommerce Stores?

### ISSUE THREAD

**Issue by leokoo** [woothemes/woocommerce#7112]
Found this issue here below. While it isn't technical, is there anyway to fix the issue of read/write operations for WooCommerce? : http://codecanyon.net/forums/thread/how-large-store-can-woocommerce-handle/96047

If you’re actually measuring scale in eCommerce, the relevant metric is transactions/second. That is how many orders the DB can intake in a fixed period of 1 second. The number of SKUs is pretty irrelevant because DB reads are way faster than DB writes. And you can put a cache like Varnish in front of static pages to skip DB read all together.

This is where “fat” platforms like Magento will blow WordPress out of the water. WP is not engineered for high-scale write operations. It’s impossible for it to compete with a platform designed specifically for performing under this duress.

That may not be your exact concern, but the same principle applies to any discussion between WordPress add-ons for eCommerce and a single-purpose platform like Magento. Shipping, payments, taxes, inventory, wholesale, CRM, rewards, 3rd party integrations, APIs — everything a store needs out-of-box will be more mature on a native eCommerce platform.

**Comment by kloon** [comment]
I don't see how a db read/write in Magento is different then one in WordPress? Both is built on the same technology and uses the same language and database modules to interact with the db.

Perhaps WordPress need some attention around their database schema, but WooCommerce is already leveraging custom tables to work around some of these design flaws.

Personally I think saying "WP is not engineered for high-scale write operations." is hogwash, most of this boils down to your database infrastructure and how your database server/software is configured, heck most of the top news sites in the world are hosted on WordPress and perform exceptionally well.

Just my 2c.

**Comment by kieranbarnes** [comment]
That thread on codecanyon was started 2 years ago. 

I agree with @kloon, I can't see how Magento would blow WP out of the water. 
Engineer your hosting correctly and there is no reason why Woo/WP can't handle XX numbers of orders per second, or whatever any other metric there is.

There will always be a place for WooCommerce alongside Magento/DemandWare/any other platform that costs more than £1.

I've got real world experience of high volume Woo sites, high product count Woo sites, high transaction Woo sites. They all work flawlessly. Some have even been Magento sites in the past and have grown since moving to WooCommerce.

Hosting is the key.

**Comment by mikejolley** [comment]
Thanks for the comments. Closing this as it isn't an 'issue'.
