### ISSUE TITLE
2.3 Beta Quantity Suggestion

### ISSUE THREAD

**Issue by dovy** [woothemes/woocommerce#7172]
I know that you've removed the +/- buttons from the quantity fields in support of the "number" support being added to browsers. May I make a suggestion? Right now it's not wide spread, and you can VERY easily detect if a browser supports that property. Here's the code you'd just need to re-add to the front-end to be fully backwards compatible:

```
/**
 * WooCommerce Quanity buttons add-back
 */
jQuery( function( $ ) {
    var $testProp = $( 'div.quantity:not(.buttons_added), td.quantity:not(.buttons_added)' ).find('qty');
    if ($testProp && $testProp.prop('type') != 'date') {
        // Quantity buttons
        $( 'div.quantity:not(.buttons_added), td.quantity:not(.buttons_added)' ).addClass( 'buttons_added' ).append( '<input type="button" value="+" class="plus" />' ).prepend( '<input type="button" value="-" class="minus" />' );
 
        // Target quantity inputs on product pages
        $( 'input.qty:not(.product-quantity input.qty)' ).each( function() {
 
            var min = parseFloat( $( this ).attr( 'min' ) );
 
            if ( min && min > 0 && parseFloat( $( this ).val() ) < min ) {
                $( this ).val( min );
            }
        });
 
        $( document ).on( 'click', '.plus, .minus', function() {
 
            // Get values
            var $qty		= $( this ).closest( '.quantity' ).find( '.qty' ),
                currentVal	= parseFloat( $qty.val() ),
                max			= parseFloat( $qty.attr( 'max' ) ),
                min			= parseFloat( $qty.attr( 'min' ) ),
                step		= $qty.attr( 'step' );
 
            // Format values
            if ( ! currentVal || currentVal === '' || currentVal === 'NaN' ) currentVal = 0;
            if ( max === '' || max === 'NaN' ) max = '';
            if ( min === '' || min === 'NaN' ) min = 0;
            if ( step === 'any' || step === '' || step === undefined || parseFloat( step ) === 'NaN' ) step = 1;
 
            // Change the value
            if ( $( this ).is( '.plus' ) ) {
 
                if ( max && ( max == currentVal || currentVal > max ) ) {
                    $qty.val( max );
                } else {
                    $qty.val( currentVal + parseFloat( step ) );
                }
 
            } else {
 
                if ( min && ( min == currentVal || currentVal < min ) ) {
                    $qty.val( min );
                } else if ( currentVal > 0 ) {
                    $qty.val( currentVal - parseFloat( step ) );
                }
 
            }
 
            // Trigger change event
            $qty.trigger( 'change' );
        });
    }
});
```

I've added this to one of the themes I work on, but I'd rather it just be added back to the WooCommerce core. Thoughts?

**Comment by claudiosmweb** [comment]
We already have this plugin as a fallback: https://wordpress.org/plugins/woocommerce-quantity-increment/

**Comment by justnorris** [comment]
The fallback plugin breaks the layout that worked in version 2.2, because it doesn't respond to `unset( $enqueue_styles['woocommerce-general'] )`, I have to unset it separately.

It's ok, I'll roll my own before I ship my theme. 

By the way - "Most browsers support number type" is not a valid argument in the real world, where there is [IE9, IE10, IE11](http://caniuse.com/#feat=input-number) and notorious Windows users who refuse to use anything but IE while expecting the same level of functionality.

In addition - JavaScript version adds the ability to style those buttons, which is what I'm after in this case.

Anyway - I thought I'd post the heads up - the fallback isn't going to fully work for people who have custom themes that aren't updated for Woo 2.3. 

Cheers!

**Comment by jameskoster** [comment]
> "Most browsers support number type" is not a valid argument in the real world, where there is IE9, IE10, IE11 and notorious Windows users who refuse to use anything but IE while expecting the same level of functionality.

That's fine, you can add support back in via the plugin. We want to support the most modern tech in WooCommerce though, it's why we've dropped things like the `placeholder` polyfill from core in the past.

> Anyway - I thought I'd post the heads up - the fallback isn't going to fully work for people who have custom themes that aren't updated for Woo 2.3.

When people update to 2.3 those buttons will simply disappear. They can add them back with the plugin. If their theme doesn't style it nicely they can take that up with the theme author who can decide whether or not to support that feature.

**Comment by justnorris** [comment]
That's why ( as a Theme author ) I'm not too happy about the "they can take it up with the theme author" part :). Anyway - haven't built WooCommerce themes before, so it doesn't worry me much. At least I know the philosophy you guys have ahead of time. Now I know to expect more "polyfill drops" and not to rely that much on things that are built-in Woo. All is well :+1:
