### ISSUE TITLE
Don't initialize WC_Session during DOING_CRON

### ISSUE THREAD

**Issue by deltafactory** [woothemes/woocommerce#7183]
Unless I'm missing something, this should never be needed. It's a small optimization.

**Comment by peter-nl** [comment]
It seems to me that this change has caused cron job woocommerce_cleanup_session to stop working.

The function cleanup_sessions() is hooked to woocommerce_cleanup_session in WC_Session_Handler->_construct. Since the session handler is not loaded anymore while DOING_CRON, the reqular batch cleanup of sessions is skipped.

This has caused a large increase in the number of sessions rows in some of our options tables.

**Comment by deltafactory** [comment]
Makes sense.. @mikejolley would it work better to put the check in the session handler's constructor and conditionally skipping the session-getting tasks when DOING_CRON is true?

I'd prefer to skip loading/creating the session class at all, but I suppose it's a small savings for the occasional cron run.

**Comment by peter-nl** [comment]
Very quick resolved. Thanks!

**Comment by nathanielks** [comment]
Was about to report this. Glad to see it's already resolved!
