### ISSUE TITLE
Stock items sometimes reduced twice and stock amounts reduced below zero even back orders not enabled.

### ISSUE THREAD

**Issue by WordCommerce** [woothemes/woocommerce#7208]
WC: 2.2.10
WP: 4.1

![stock](https://cloud.githubusercontent.com/assets/9597926/5895930/d8045f7c-a534-11e4-8969-be2b2499ebc7.jpg)

**Comment by fkunz** [comment]
I have to dig this up, as #14790 is not taken seriously.
The commit 54e0259 by @mikejolley should have fixed my issue.
However i am running WP  4.8–de_DE with WooCommerce 3.1.1 and get stock reduction twice when a PayPal payment is processed with PDT and IPN.
In most cases payment is confirmed solely by PDT, which does not create a problem.
Locking at the PayPal Log(excerpt added below) i suspect the processing(stock management) of the IPN response is still running, when the PDT response arrives and triggers processing and stock reduction a second time. 
Could you be missing a Mutex, Lock or status check?
I am happy to provide more information in order to solve this issue. False Stock numbers are driving us mad. 
![google chrome003](https://user-images.githubusercontent.com/4262962/28814737-135f8928-769f-11e7-89ec-208388717b4b.png)

```
2017-08-01T08:23:03+00:00 INFO Checking IPN response is valid
2017-08-01T08:23:05+00:00 INFO IPN Request: Array
(
    [body] => Array
        (
            [mc_gross] => 91.45
            [invoice] => WHATEVER-8731
...
2017-08-01T08:23:05+00:00 INFO Received valid response from PayPal
2017-08-01T08:23:05+00:00 INFO Found order #8731
2017-08-01T08:23:05+00:00 INFO Payment status: completed
2017-08-01T08:23:06+00:00 INFO PDT Transaction Result: Array
(
    [SUCCESS] => 
    [mc_gross] => 91.45
    [invoice] => WHATEVER-8731
```
