### ISSUE TITLE
Fix meta ordering with multiple same keys

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7210]
In reference of #6468 the issue has been fixed everywhere, but on the emails the order is still wrong and shows the fileds by alphabetical order instead of the real order of them.

**Comment by claudiosmweb** [comment]
@SiR-DanieL Tested with the master?

Because @mikejolley fixed the `WC_Order_Item_Meta::get_formatted()`.
This is used in `WC_Order_Item_Meta::display()`. https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-order-item-meta.php#L40-L77

We use this in the emails too: 

https://github.com/woothemes/woocommerce/blob/master/templates/emails/email-order-items.php#L16

https://github.com/woothemes/woocommerce/blob/master/templates/emails/email-order-items.php#L40-L42

**Comment by SiR-DanieL** [comment]
Not yet @claudiosmweb , will check soon!

**Comment by mikejolley** [comment]
Reopen if still busted in master.

**Comment by SiR-DanieL** [comment]
Yes it's still wrong in beta-2

Email: http://cld.wthms.co/tdV2
Order Received: http://cld.wthms.co/1dMGL
Order Admin (this one is correct and should look like this everywhere): http://cld.wthms.co/19S7J

**Comment by mikejolley** [comment]
This happens when meta keys are the same - get_metadata groups them. So in your example the two 'age' keys get grouped together.

Would have to write custom query to get values in the same order and avoid key conflict.
