### ISSUE TITLE
Payment actions executing multiple times

### ISSUE THREAD

**Issue by aprea** [woothemes/woocommerce#7226]
The file `/templates/checkout/payment.php` has two actions at the top and bottom of the file respectively.

```php
do_action( 'woocommerce_review_order_before_payment' );
do_action( 'woocommerce_review_order_after_payment' );
```

It appears that these actions are unexpectedly executing **twice**.

I included the following in a MU plugin, headed to the checkout page and am seeing the output of that function **twice** at the bottom of the payment methods.

```php
add_action( 'woocommerce_review_order_after_payment', function() {
	echo 'hello!';
} );
```

Please note that I'm testing this on the `2.3-beta-2` tag and that this problem did not occur on 2.2.

**Edit:** Appears to be an JS/AJAX issue. This problem goes away if I disable JS in my browser. Additionally, using the example above, I can produce several additional "hello!" outputs if I continually toggle the "Ship to a Different Address?" checkbox.

**Comment by claudiosmweb** [comment]
@mikejolley 2e398a3a791ceb62efe2eeaefc646e08eb7fe5cc

**Comment by thenbrent** [comment]
I spent most of yesterday dealing with the breaking changes SHA: 2e398a3 introduces, so can help here.

@aprea prior to SHA: 2e398a3, [all output from callbacks attached to `'woocommerce_checkout_order_review'`](https://github.com/woothemes/woocommerce/commit/2e398a3a791ceb62efe2eeaefc646e08eb7fe5cc#diff-133db5662c51f5686d87611121a05a3bL256) was buffered and printed within in the `#order_review` section of checkout. So you could safely `echo` anything you wanted and it would be displayed when the checkout page was loaded and updated.

WC 2.3 has introduced a ["fragments" system](https://github.com/woothemes/woocommerce/commit/2e398a3a791ceb62efe2eeaefc646e08eb7fe5cc#diff-133db5662c51f5686d87611121a05a3bR272), meaning you can't simply echo things any more unless it's on hooks within the `.woocommerce-checkout-payment` or `. woocommerce-checkout-review-order-table` elements. To update things outside those elements, you now need to use the `'woocommerce_update_order_review_fragments'` hook.

So this isn't a bug in WC 2.3 so much as just a breaking change.

With WC 2.3, you need to either use a hook within `.woocommerce-checkout-payment`, like `'woocommerce_review_order_after_submit'`, or:

1. use the `'woocommerce_review_order_before_payment'` to display the content when the order review table is first loaded (but not on Ajax requests)
1. use `'woocommerce_update_order_review_fragments'` to _update_ that content whenever an Ajax request is triggered to update the checkout fields

In my opinion, although the new system introduced in SHA: 2e398a3 gives finer grained control over content, it:

1. is more brittle than the old system
2. imposes a larger burden on developers than the old system because they need to hand initial page display and Ajax updates separately
3. completely breaks backward compatibility because `'woocommerce_checkout_order_review'` is no longer triggered on Ajax requests and plenty of other hooks, like `'woocommerce_review_order_before_payment'` no longer have their output buffered.

Worse still, I also don't think any of these breaking changes were necessary to achieve the original goal of decoupling the order table section from payment fields.

All that said, I actually hope it's not changed now as I've already spent a day updating code to be compatible with it.

**Comment by mikejolley** [comment]
@thenbrent what did this break in subs? Got an issue #?

**Comment by thenbrent** [comment]
@mikejolley not Subs, One Page Checkout, which was using `'woocommerce_checkout_order_review'` to display a custom order table.

Discussion here should cover it: https://github.com/Prospress/woocommerce-one-page-checkout/pull/157 (you'll need to accept the invite I just sent you to join that repo).

**Comment by aprea** [comment]
@thenbrent yo brent, thanks for the tips, very helpful stuff.

I ended up adding:

```php
if ( is_ajax() ) {
	return;
}
```

To the top of the hooked function to prevent the duplicate output (i.e. your first suggestion) and it seems to work fine.

I can see these actions being really confusing for developers in the future, they're essentially going to have the same problem I did and not understand why they're seeing duplicate output. This also breaks themes/plugins developed prior to 2.3 where these actions worked correctly and only fired once per page render.
