### ISSUE TITLE
wc_get_order memory leak

### ISSUE THREAD

**Issue by omarabid** [woothemes/woocommerce#7310]
The function wc_get_order is leaking memory in a "for" loop.

Here is the code in question:

```
for( $i = 0, $n = count( $orders ); $i < $n; $i++ ) {	
    $woo_order = wc_get_order( $orders[$i] );
}
```
Memory consumed after 100 iterations: 1,217,344
Memory consumed after 1000 iterations: 32,547,720
Memory consumed after 2000 iterations: 67,670,304
Memory consumed after 3000 iterations: 102,565,848

It seems that the leak stops after a large number of iterations, but 32MB for 1000 iterations seems like a lot for me. It means for 10,000 iterations, I'll need around 300MB.

This is the amount of memory consumed by the PHP loop only. It's also worth mentioning that if the memory is limited (like 128MB) this will cause the script to stop, so it's not a result of having too much memory and PHP is waiting for garbage collection.

**Comment by kloon** [comment]
PHP handles memory freeing, the reason you may see it decrease only after a while is because PHP's garbage collector will only kick in once there are free CPU cycles available, which could only be after an for loop.

Also you might think that because you are setting the same var over and over it would automatically free the memory, but as mentioned above it is waiting for the garbage collector to kick in, that old order object is still sitting in memory, you are just pointing it to a new object, even using unset will not immediately free the memory.

The order object contains quite an amount of data so it could add up quickly if you do a 1000 new order objects.

**Comment by omarabid** [comment]
@kloon I don't think so, otherwise it'd free memory if it was limited? My point is that the memory consumption is way too huge if you want to scale past a few thousands. I'm tracing the leak to the WordPress function "get_post". Will report here my findings.

Thanks for the fast answer!

**Comment by omarabid** [comment]
The memory leak seems to be coming from WordPress functions (get_post and get_post_meta). This doesn't happen when I loop for other content, so it is a bit weird.

I defaulted to using Raw Mysql queries.

**Comment by bdares** [comment]
"I wrote raw sql queries" doesn't sound like the issue's been resolved.  I am also seeing this behavior, in my case in connection to [Order/Customer CSV Exporter](http://docs.woothemes.com/document/ordercustomer-csv-exporter/).

**Comment by omarabid** [comment]
@bdares I've done much more deeper analysis on this. The leak is coming from WordPress code itself, but it's not clear what "trigger" this leak. Maybe the guys here have something?

**Comment by maxrice** [comment]
@bdares can you submit a ticket and request that SkyVerge be CC'd on it? While I don't think the exporter itself is responsible here, I'm curious if there's improvements we can make, particularly when exporting thousands of orders at once.

**Comment by bdares** [comment]
Not sure what's going on, because as far as I can tell:

* `wc_get_order()` (in wp-content/plugins/woocommerce/includes/wc-order-functions.php) just calls `WC()->order_factory->get_order()`
* `WC_Order_Factory` (in wp-content/plugins/woocommerce/includes/class-wc-order-factory.php) calls `get_post()` then instantiates a `WC_Order` with it
* `get_post()` (in wp-includes/post.php) invokes `WP_Post::get_instance()`
* `WP_Post::get_instance()` (in same file) calls `$wpdb->get_row()` with a prepared query
* `wpdb` looks like a wrapper that ultimately just calls `mysql_query` (or `mysqli_query`).  

I'm not familiar enough with PHP to speculate as to where the memory leak is occurring.  It all looks all right to me.

**Comment by bdares** [comment]
Main culprit seems to be `wp_cache_add()` in `WP_Post::get_instance()`.  Periodically calling `wp_cache_flush()` while looping over records will prevent memory use from growing while looping over many records.

**Comment by mikejolley** [comment]
Thanks for investigating.

**Comment by acuk97** [comment]
@bdares Thank you!!! Your comment on the wp_cache_flush() just solved an issue I've been having for days. I'm on WP 4.7.4, PHP 5.6 and was getting the slow/almost seemingly random leak leading to an out of memory error on a long running script. Adding a periodic call to that function makes it sort it's shit out!

**Comment by shendriksza** [comment]
Saved my life. Thank you so much
