### ISSUE TITLE
Please add translation to transiflex: Informal German ("Du") next to formal "Sie" variant

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7312]
I'd like to add a translation for the informal german language variant. According to [the latest survey from 2009](http://blog.wpde.org//2009/08/04/ergebnisse-der-umfrage-zur-sprachdatei.html) most users prefer the german "Du" variant (65 %) over the formal "Sie" variant (30 %):  

The [german wordpress portal](http://wpde.org/download/) also offers the "Du" by default, using "Sie" needs some extra steps.

According to [this Stackoverflow question](http://stackoverflow.com/questions/28329453/is-there-a-locale-code-for-informal-german-de-de-informal) the right code for this would be: `de_DE-x-informal` 

However, https://www.transifex.com/projects/p/woocommerce/ does not allow me to add this language. Can you do this? I'd like to add this before the 2.3 release if possible. 

PS Other projects, e.g. [owncloud](https://www.transifex.com/projects/p/owncloud/) have a workaround by using [de](https://www.transifex.com/projects/p/owncloud/language/de/) and [de_DE](https://www.transifex.com/projects/p/owncloud/language/de_DE/). One is formal ("Sie"), the other is informal ("Du") variant. I think `de_DE-x-informal` locale code is more appropriate than this.

**Comment by mikejolley** [comment]
How does WP core handle these two variants?

**Comment by jnachtigall** [comment]
At http://wpcentral.io/internationalization/de/ you can get a `de_DE` version (which is the informal "Du"). This is also shipped as the default german version.

As said at http://wpde.org/ you also only get the informal ("Du") by default. At http://wpde.org/download/sprachdateien/ you can download informal and formal. The formal one is just call `de_DE_Sie.zip` but contains the same file names (still `de_DE.po`) but with "formal" translations.

So by default informal is shipped as de_DE. If one wants, one can manually download translation files with the same de_DE but for formal.

**Comment by mikejolley** [comment]
Transifex has no support for custom language codes - what you're asking for cannot be done. You'd have to use DE and add a note that its Sie if you needed it hosted on TX.

**Comment by jnachtigall** [comment]
If I go to https://www.transifex.com/projects/p/woocommerce/ and click on "Request Language" (while being locked in) I cannot add "DE". It is simply not availalbe. 

Probably one must be admin to "pre-select" it, so that "translators" like me are able to add. Can you do this and add it? 

Until then this ticket should remain open. Situation is very strange now: Core Wordpress comes with informal "Du" wheres WC comes with formal "Sie" translation. I want to add "Du" to WC, too.

**Comment by mikejolley** [comment]
TBH I think WC should have the same variant as WP, but I don't know German so I cannot get involved with your politics :)

On transifex, search for 'german' in the language box, its there.

**Comment by jnachtigall** [comment]
Never mind, it just takes a few years to learn the language ;)

Back to the topics: I cannot add it, really! See this screenshot:

![wc_transiflex](https://cloud.githubusercontent.com/assets/3307404/6128314/d8974ede-b134-11e4-9ec5-ccd06b02463b.png)

Addable languages are only `de_AT` (German as spoken in Austria), `nds` (a regional dialect spoken in northern Germany) and `pfl` (a regional dialect spoken in south-western Germany).

At the bottom there is the already available formal "Sie" form `de_DE`.

**Comment by mikejolley** [comment]
What is your username

**Comment by jnachtigall** [comment]
At transiflex it is nachtigall

**Comment by mikejolley** [comment]
@jnachtigall I've added you to both. Can you see them?

**Comment by jnachtigall** [comment]
Yes, seems to be working. Thank you!

Only thing is that I do not see how I can add a note or description to https://www.transifex.com/projects/p/woocommerce/language/de/ to let people know that this is the informal "Du" version (whereas https://www.transifex.com/projects/p/woocommerce/language/de_DE/ is formal "Sie")

**Comment by mikejolley** [comment]
Doesn't look possible to add notes.

You mentioned WP uses du, so I'd be open to having that as the main version. Depends what German users want though..

@BFTrick survey?

**Comment by BFTrick** [comment]
Looking through the WooCommerce 2014 Survey I could reach out directly to 17 people who live in Germany who left their email address. It's not a ton of people but it could give us an idea. Maybe supplement that with some social media surveys? Not sure how many people we would get in the end.

I'm a fan of using whatever WordPress core uses. Maybe reach out to a few people to confirm?

I'd be curious what @deckerweb thinks of this.

**Comment by deckerweb** [comment]
The majority of businesses in Germany use formal version everywhere, including for web sites / shops! Of course, there are shops who prefer to use informal version, for serious reasons!

However, based on feedback since 2011 for my WC language plugin I can clearly say, that the formal version is the most used!

Therefore, I have always suggested to make the formal version the default language version, and make a way to easily use - update-safe without overriding files! - the informal version for users/ shops who need that. My plugin supports such a setting - it's really painless.

It's an ongoing battle since the first days of WooCommerce in 2011. One day the "informal fans" request their's to be default, then the formal, and so on.

It doesn't matter what users want in the end or how WordPress ships its default language, what matters most in the end, are the shop owners and their day to day business usage.

99% of my customers only want formal translations -- for everything!

If you would change the default shipment to informal version in WC - you could do that, but it would be a big mistake in my opinion, you will end up with numerous requests for the formal version...

The real cause for this "issue" is the non-existing management of language variants in WordPress core and all its language / translation functions. That is a big mistake! The German community is begging Nacin and Otto and other devs for years to make something in this area but still there seems nothing be happening in that case... sadly.

So leave the formal version as default - to serve the majority of businesses - and offer an easy way to use informal - or whatever other language variant.

This whole topic applies also to other languages that have strong formal/ informal usages, however, I guess Germany is one of the strongest with actual business usage (of the formal one).

Hope that helps as background information.

**Comment by jnachtigall** [comment]
I mostly agree with @deckerweb  It's ok to leave the informal "Du" version (that still needs to be translated) as it is now as an alternative that people can grab from transiflex. 

Changing the default variant would indeed cause a big "surprise" when formal shops all of a sudden come with more informal wordings. This would really be a bigger step that needs to be carefully thought through and needs communication.

It very much depends on the shop, its products and its audience. In our case formal is not an option, so we have informal (still private, but I'll make it public now).

An easier way to switch languages would be very good, but that would be – also technically at github – be another issue IMO.

**Comment by franticpsyx** [comment]
>If you would change the default shipment to informal version in WC - you could do that, but it would be a big mistake in my opinion, you will end up with numerous requests for the formal version...

:+1:

**Comment by krautnerds** [comment]
I would really like to use and contribute to the informal German translation on transifex but unfortunately cant see it in the overview https://www.transifex.com/projects/p/woocommerce/

Or did I miss something?

**Comment by krautnerds** [comment]
By the way: @deckerweb: Is it still necessary to have an own plugin for woocommerce translation into German or are all portions translatable via transifex by now? I just ask because there were no updates in the the past for your plugin and I wondered if I can just switch to the standard translation files in woocommerce?

**Comment by deckerweb** [comment]
@krautnerds Yes it is necessary for various reasons! An update will come soon. You can switch if you want of course.

**Comment by jnachtigall** [comment]
@deckerweb I think it would be great if both woocommerce upstream translations and woocommerce-de plugin could share the same po files, that is translations, as a common basis. That is, maybe if you could share your work into the transiflex translations and then maybe fork from there whatever you think should be only in the woocommerce-de plugin.

Technically, it does not seem to be easiy to integrate an informal de_DE@informal because transiflex as well as wordpress do not really play well with [language variants](http://stackoverflow.com/questions/28329453/is-there-a-locale-code-for-informal-german-de-de-informal). So that's definitely a point (besides others?!) for having a plugin. But there is now [de_DE](https://www.transifex.com/projects/p/woocommerce/language/de_DE/) for formal Sie variant on transiflex, and [de](https://www.transifex.com/projects/p/woocommerce/language/de) for informal Du variant. Using these as a common basis would reduce the work for everybody. The (de_DE for frontend)[https://www.transifex.com/projects/p/woocommerce/translate/#de_DE/woocommerce-pot] is already in a better shape now and could be used as a starting point for informal de. Still work is necessary for the backend part.

**Comment by krautnerds** [comment]
@jnachtigall I would support your approach to work together with @deckerweb on the german transiflex translation to achieve a high quality translation and also we should support the woocommerce team to eliminate last not translatable peaces which are translated by @deckerweb by string swaps at the moment. So it would be possible to use the core translation functiontality and it would not be necessary to use a stand alone plugin anymore because this also a performance overhead (at least in our case)

By the way: @deckerweb: Do you allow to import the informal translation of your plugin into the new transiflex informal project? I could help you with that.

@jnachtigall Thanks for the link to the informal project

**Comment by jnachtigall** [comment]
@krautnerds I've already fixed quite a few things on the frontend resource for formal de_DE. Probably not too much work to go all over it, change Du to Sie etc and then upload it to informal de resource on transiflex. I just wanted to finish on the admin resource before doing so. (Not sure if it's a good idea to just take and import all of woocommerce-de translations, doing a diff/compare and conditional merge would be more appropriate I assume - in case that's allowed)

**Comment by jnachtigall** [comment]
@krautnerds Just a quick update: The German translations are now complete on transifex. There is also an [informal Du variant](https://www.transifex.com/projects/p/woocommerce/language/de/) next to the [official formal Sie version](https://www.transifex.com/projects/p/woocommerce/language/de_DE/), which can be installed by following the [howto here](http://docs.woothemes.com/document/woocommerce-localization/#section-7).
