### ISSUE TITLE
How to disable enhanced select boxes in 2.3

### ISSUE THREAD

**Issue by jtimar** [woothemes/woocommerce#7351]
Please, please tell me it's possible. The removal of this option is causing me a huge headache.

**Comment by claudiosmweb** [comment]
Frontend?

**Comment by jtimar** [comment]
Yes, on the front end. I figured out how to disable the script, but honestly baffled why anyone thinks it's a good idea to just remove a key setting like this. Just dumb.

**Comment by mikejolley** [comment]
Themes can de-queue select2. Why have an option there to confuse users who don't even know what chosen/select2 is, when themes can disable it with 1 line of code. Thats dumb.

**Comment by blazes** [comment]
hi @mikejolley could you please explain how to do this with a filter? i have been scouring for hours and i can't seem to work it out.

**Comment by mikejolley** [comment]
http://codex.wordpress.org/Function_Reference/wp_dequeue_script

**Comment by arkonlabs** [comment]
Could someone provide step by step instructions on how to "de-queue" the select2 script? 

The theme I use does not do this for me, and while this feature works perfectly on desktop browsers, my customers are having issues when checking out using iOS or Android, as they are presented with the enhanced select box which does not fit on screen instead of a simple drop down list (which is rendered by the OS' browser). 

Thanks.

**Comment by arkonlabs** [comment]
I think I figured it out. I used this:

add_action( 'wp_enqueue_scripts', 'agentwp_dequeue_stylesandscripts', 100 );

function agentwp_dequeue_stylesandscripts() {
if ( class_exists( 'woocommerce' ) ) {
wp_dequeue_style( 'select2' );
wp_deregister_style( 'select2' );

wp_dequeue_script( 'select2');
wp_deregister_script('select2');

} 
}
