### ISSUE TITLE
Cannot filter Orders by Order Status using WP_Query and custom Post Status

### ISSUE THREAD

**Issue by visser** [woothemes/woocommerce#7408]
Hi Woo, running WC 2.3.3, when using WP_Query from the storefront to fetch a list of Order ID's and filtering them by Order Status (using custom Post Status) WordPress won't tack on the WHERE post_status to the SQL query, this is with and without the supress_filters flag set to false. This only affects the storefront (hooked onto init action with default priority) and not WP_Query calls made within the WordPress Administration where Order Status is filtered as expected.

$post_type = 'shop_order';
$post_status = array( 'wc-processing', 'wc-completed' )
$args = array(
	'post_type' => $post_type,
	'post_status' => $post_status,
	'fields' => 'ids',
	'suppress_filters' => false
);
$order_ids = new WP_Query( $args );
...

**Comment by mikejolley** [comment]
> post_status (string / array) - use post status. Retrieves posts by Post Status. Default value is 'publish', but if the user is logged in, 'private' is added. And if the query is run in an admin context (administration area or AJAX call), protected statuses are added too. By default protected statuses are 'future', 'draft' and 'pending'.

May be a limitation - I found it would only respect my post_status if I passed in a WP status such as private too in admin, otherwise it did no filtering.

Use get_posts() - its more reliable and easier to get the results (it returns an array of ids and none of the other stuff WP_Query does). Tested this works as intended.
