### ISSUE TITLE
Related products, ORDER BY RAND(), is super slow

### ISSUE THREAD

**Issue by jdluzen** [woothemes/woocommerce#7436]
The speed of ordering by the SQL RAND() function is directly linked to the count of query results. I have over 95k records in wp_posts, and it takes 3-4 seconds to complete. I've been looking at alternatives, so far I'm unsuccessful. As a workaround, I could disable related products.

**Comment by roykho** [comment]
Yes I would agree, using order by rand() in a query has a performance hit.  I propose we randomize the array after the fact instead.

**Comment by mikejolley** [comment]
@roykho Issue with this is you'll only get a random LIMIT of products. Same ones every time, right?

**Comment by roykho** [comment]
@mikejolley - when you use order by rand(), mysql actually has to re-query each row of the table to assign it random number IDs and then give you back the results again.

**Comment by mikejolley** [comment]
@Royho so how about offsetting the first result by a random number so you at least get a different result set each time?

**Comment by roykho** [comment]
@mikejolley possible, let me do a test to see the query time.

**Comment by roykho** [comment]
@mikejolley after thinking about it, offset will not be good because if say you had 500 records and offset is 495 say and you want to return 10 records, you will end up with only 5 record.  Not to mention using offset will require 2 queries.

So far I have not seen a better solution than to use PHP.  By removing order by rand() and replace with shuffle, in my benchmark, it had a 50% increase in performance.  And that is just with limit of 2.

I am keen to see if there is a pure mysql way to do this efficiently however.

**Comment by shivapoudel** [comment]
In this opinion ordering with MySQL is faster than with PHP, and the extra PHP code required would be an extra bloat. MySQL is very efficient, so do the heavier things in that. After all, it's a server devoted to data handling!

 * If you do RAND() in mysql, it can get a bit slow.
 * If you do shuffle() in php is just stupid, since your have to transfer all your data, then order it.

**Comment by roykho** [comment]
@shivapoudel extra bloat?  How much of a bloat do you think it is? :)  Do you have a better solution?

**Comment by roykho** [comment]
Here is the benchmark data.

0.192124843597 <- with order by rand
0.098138830185 <- shuffle

So in this case @shivapoudel how is mysql faster?

**Comment by shivapoudel** [comment]
@roykho I am impressed with `shuffle()` as I have performed test and happy with the faster result xD

**Comment by mikejolley** [comment]
Try that @roykho 

The max rows transient should be much faster than ORDER BY RAND(), and it means you get random result set each time, rather than the same result set shuffled.
