### ISSUE TITLE
Spaces in simple Download URL's gets removed  [%20]

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7442]
Hi Mike/Andrew

When we  enter the dropbox download url within the "File URL" field in the "Downloadable Files"  section as in: ![](http://cld.wthms.co/IvIO+)  Clicking "Update", this URL:

`https://www.dropbox.com/s/krzl03ryij8gbuo/Getting%20Started.rtf?dl=0`

gets updated to:

`https://www.dropbox.com/s/krzl03ryij8gbuo/GettingStarted.rtf?dl=0`

thus rendering a 404 to any attempt to download the file upon its purchase.  @mikejolley @ChromeOrange @seanreloaded

**Comment by kloon** [comment]
This will break the Amazon extension as well.

**Comment by andrewfitz** [comment]
Could be same issue as #7474

**Comment by SiR-DanieL** [comment]
@mikejolley this needs to be reopened.

`esc_url_raw` does not preserve spaces, it still removes `%20` from the URL.

A quick test with

```
echo esc_url_raw( 'http://google.com/This is a file.mp3' );
```

Will print

```
http://google.com/Thisisafile.mp3
```

**Comment by mikejolley** [comment]
@SiR-DanieL The original report was for URLs with encoded spaces being removed. Real spaces are not valid in URLs.

**Comment by SiR-DanieL** [comment]
Yes, shouldn't we encode them to `%20`?

**Comment by mikejolley** [comment]
No, we should not re-encode what we're given IMO. @SiR-DanieL

**Comment by justinshreve** [comment]
Maybe it would help to add a clarifying comment to the help question mark above it that we expect already encoded URLs? I can do a quick PR for that if it makes sense.

**Comment by SiR-DanieL** [comment]
it works for me @justinshreve

**Comment by whoishack** [comment]
I can chime in here as it seems it was reopened from a ticket started by me. We had a large database imported for products and it seems the imported product URLs didn't get properly encoded - whether it be  an issue on WC or the importer itself but nonetheless in the end it was esc_url_raw that was messing up the URLs. Upon disabling that function, everything worked perfectly fine. 
Maybe a failsafe could be added as I'm sure I'm not the only one who's ever imported data in for products.

**Comment by melior88** [comment]
I'm having this same problem with encoded spaces with %20 in the Amazon S3 Extension.
For example [amazon_s3 bucket=bucket object=test%20file.jpg] is stored as [amazon_s3 bucket=bucket object=testfile.jpg]. On the other hand [amazon_s3 bucket=bucket object=test file.jpg] is stored with the space but breaks the Amazon S3 shortcode.

**Comment by justinshreve** [comment]
@melior88 I've notified the extension team of the Amazon S3 issue.

**Comment by swaldner** [comment]
@justinshreve what is the reasoning behind sanitizing downloadable product shortcodes with the heavy-handed _ws_clean_ and stripping out the octets? The shortcodes are most certainly going to contain some form of url or path which can legitimately have octets in them. Stripping octets in this case seems like the wrong thing to do.

@melior88 I have a workaround for you if you don't mind making two small changes to the S3 plugin. I have also requested through Woocommerce support that these changes be made permanent. No guarantee that will happen though.

The workaround allows the use of a plus-sign for spaces in the amazon_s3 object shortcode argument rather than %20.

### Code Changes in WooCommerce Amazon S3 Storage (version 2.1.3)
In amazon-s3-storage.php: add code after line 620:

```
if ( ! empty( $bucket ) && ! empty( $object ) ) {  // line 620
					
    $object = str_replace('+', '%20', $object);
```

In amazon-s3-api.php change line 63:
`		$this->object = str_replace('+', '%20', $object);`
