### ISSUE TITLE
All Coupon codes treated as recurring discount

### ISSUE THREAD

**Issue by JoseRaffucci** [woothemes/woocommerce#7482]
All coupons treated as recurring discount coupons.  This seems to be a new problem as it did not seem to be happening in previous version of woocommerce.

**Comment by michaeltieso** [comment]
Is this occurring through WooCommerce Subscriptions? Do you have the latest version of WooCommerce and Subscriptions installed?

**Comment by JoseRaffucci** [comment]
Yes the latest Woocommerce (Version 2.3.4) and WooSubscriptions (Version 1.5.17) are installed.  We tried creating new coupons that only do cart discount but all coupons we create or created are being treated as recurring discounts.

**Comment by michaeltieso** [comment]
I'm sorry for the issue here. This is a bug in Subscriptions I'm afraid. If you reach out to us in support with a link to this issue, we'll be happy to send you a fix for it. We'll have a fix for this coming out sometime next week in a official release for Subscriptions. For future reference if you have issues with any of our other extensions, please create a support ticket [here](https://support.woothemes.com/).

**Comment by JoseRaffucci** [comment]
Thank you for your follow up and support. I appreciate the directions and will post on the support site for subscriptions.  Thank you again in advance.

**Comment by thenbrent** [comment]
@JoseRaffucci we were made aware of this issue with Subscriptions yesterday and have since diagnosed/fixed it.

If you open a support ticket with WooThemes (at https://support.woothemes.com/), the team member can provide you with a fix immediately, otherwise the fix will be released with Subscriptions v1.5.18 within the next week. Sorry for the trouble.

**Comment by JoseRaffucci** [comment]
@thenbrent 
Thank you for the information, I have submitted a ticket and will wait for a response.  Thank you for taking the time to respond and giving us a fix soon.  

Let us know if you need any additional information.

**Comment by JoseRaffucci** [comment]
@thenbrent , @michaeltieso  I submitted a ticket 2 days ago and have not received a response or any fix for my issue.  Could you please look into this.  Thank you.

**Comment by michaeltieso** [comment]
@JoseRaffucci Sorry for the delay. I just provided @WillBrubaker with what's needed

**Comment by Honeylou** [comment]
Hi.
Can someone help me. I am encountering this problem. I have set up coupon type as cart discount but it was treated as recurring % discount :( can someone help me?
