### ISSUE TITLE
woocommerce tax calculation for one item

### ISSUE THREAD

**Issue by catlilli** [woothemes/woocommerce#7517]
WooCommerce is calculating the tax perfectly for >1 items, but not for a single item.  Our tax rate is set at 5.3%, and we set the shipping tax rate to 0%.  For a single item, it mistakenly also taxes the shipping.  How can we stop this?

**Comment by mikejolley** [comment]
You cannot have separate tax rates for shipping unless this is set: https://dl.dropboxusercontent.com/s/g4j1taxbohhggdh/2015-02-23%20at%2011.08%202x.png?dl=0

If shipping is 0% tax, just uncheck the 'shipping' box on the tax rate. No need to set the above or have its own rate.

There are no bugs in core regarding taxes for items and single items use same logic as multiple items. Please check your maths, especially if you have tax inclusive prices.

Closing due to lack of details in the report.
