### ISSUE TITLE
Add Antilliaanse Gulden  Currency [ANG] to WooCommerce

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7530]
Please add the Antilliaanse Gulden [ANG]  Currency support to WooCommerce

**Comment by barrykooij** [comment]
Please note that on Curaçao and Sint Maarten, the Netherlands Antillean guilder will soon be replaced by the newly created Caribbean guilder. I'm not sure if they're are any islands left using the ANG after that change since it appears Aruba is using the Aruban florin (AWG) and Bonaire, Saba and Sint Eustatius are using USD.

**Comment by mikejolley** [comment]
I don't think WC core needs to support small island currencies, esp given the above. Use a snippet.
