### ISSUE TITLE
There are no shipping methods available. Please double check your address, or contact us if you need any help.

### ISSUE THREAD

**Issue by aneeshjajodia** [woothemes/woocommerce#7538]
I'm facing this issue on my website www.creativecases.in, There are no shipping methods available. Please double check your address, or contact us if you need any help.

Please help.

**Comment by claudiosmweb** [comment]
This is happening because: "There are no shipping methods available."!
Maybe you have not set any shipping method or maybe you filled out the wrong address.

Anyway it's not a bug in WooCommerce and therefore should not have been posted here.

Please don't use our issue tracker for support requests, but for core WooCommerce issues only. Support can take place in the appropriate channels:
 
* The [public support forums](http://wordpress.org/support/plugin/woocommerce) on WordPress.org, where the community can help each other out.
* The [WooThemes premium support portal](http://support.woothemes.com/) for customers who have purchased themes or extensions.

**Comment by buckneri** [comment]
well since the response was no help ill post the same thing since it is happening on my site currently WITH flat shipping enabled AND a valid address entered.

so can we now start a discussion and find the problem?

**Comment by buckneri** [comment]
thanks for the help though. youtube solved it.. the default settings in woocommerce DO NOT HAVE A price set in the shipping method. Setting it to at least 0 solves the BUG.  you're welcome.
