### ISSUE TITLE
Rest API No SSL

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#7540]
Hi,

I have a client who needs to use the REST API without the SSL certificate, due to an issue with the cert not working properly:

http://stackoverflow.com/questions/28650477/windows-azure-cloud-app-could-not-create-ssl-tls-secure-channel

I would prefer not to use OAuth, since that would require several coding changes on my part. Is there a coding change I can make to bypass the SSL cert? I am using the consumer key and secret. What files and what code needs to be changed?

**Comment by bryceadams** [comment]
I think OAUTH would be the only way, like how it was handled in here - https://github.com/kloon/WooCommerce-REST-API-Client-Library

I believe the issue is on the installation side, where it will return an error if you **don't** use OAUTH but it doesn't have SSL. In the `WC_API_Authentication` class, the `authenticate` method checks if the installation is using SSL with the `is_ssl` function. Now that function checks if `$_SERVER['HTTPS']` isset, so you *could* use something like: `$_SERVER['HTTPS'] = 'on';` on the client site force that, thus tricking the site that `is_ssl` is true, then tricking the API that it can proceed with the `perform_ssl_authentication` method.

Now I *think* that will work, so try it out :)

**Comment by bryceadams** [comment]
PS. As @claudiosmweb pointed out, you *shouldn't* do this for obvious security reasons (disclaimer).

**Comment by claudiosmweb** [comment]
Great!
Ignore SSL certificate and will put your client at risk!

If only works with SSL is because there is a reason, Basic Auth should not function without SSL, is totally a risk to anyone, you can steal their keys and your customer at great risk!

I recommend you do not try to put your client at risk in this way and use oAuth or install a SSL certificate.

Your chance to learn a little:
https://en.wikipedia.org/wiki/Basic_access_authentication#Security
https://en.wikipedia.org/wiki/OAuth
