### ISSUE TITLE
Image meta data isn't saved when meta box woocommerce-product-data is removed

### ISSUE THREAD

**Issue by osadi** [woothemes/woocommerce#7638]
If you remove the meta box `woocommerce-product-data` but keep the `woocommerce-product-images` images added to the gallery aren't saved.

The `woocommerce-product-images` save action fails on the nonce check. Adding `wp_nonce_field( 'woocommerce_save_data', 'woocommerce_meta_nonce' );` to the `WC_Meta_Box_Product_Images::output()` solves the issue without any obvious side effects. Still works when the product-data box is added again.
But, there might be a reason for not having the nonce in the images meta..

**Comment by mikejolley** [comment]
I understand the issue, but what use case would justify removing the product data box? Thats pretty much essential to the entire plugin.

**Comment by osadi** [comment]
Yeah I agree.
I just happened to do some customizations for a client that wanted to have the product data in ACF instead. They are using it mostly as a catalog, and didn't use many of the fields in the data box, and I couldn't find any way to manipulate (filter) the data in each of the tabs.
Also, they didn't like the way that box worked, although I tried to convince them otherwise. So ACF it was, but we kept the gallery meta box.

Thought I should report it anyways. Maybe the nonce was missing from that meta box, maybe it can be added without anything breaking, or maybe you don't want it there.

**Comment by mikejolley** [comment]
Looked into this - it's partly the nonce, but the gallery saves on the hook:

`woocommerce_process_product_meta`

This hook is only ran if the nonce check succeeds.

This hook is actually also used by add-ons for woocommerce, so your change would also affect extensions saving their data too. In order to maintain compatibility you may just want to 'hide' the meta box and run your ACF save logic later.
