### ISSUE TITLE
Shipment Tracking extension - support for REST API tracking updates

### ISSUE THREAD

**Issue by euan-am** [woothemes/woocommerce#7674]
We attempted to use the Woocommerce Shipment Tracking extension to provide shipment information for an order once an order has been fulfilled through the REST API. We were unable to use the REST API to update the meta fields used by this extension as it makes use of the following private order meta fields:

‘_tracking_provider’
‘_custom_tracking_provider’
‘_tracking_number’
‘_custom_tracking_link’
‘_date_shipped’

as documented on this page:

http://docs.woothemes.com/document/shipment-tracking/

We found that we were unable to add private meta through the REST API. We were able to add regular meta through the REST API. Is there perhaps an alternate method to update these fields, or would a change be required to allow updates through the REST API?

I have discussed this briefly with @mattyza. It would be very useful to allow updates for this type of information through the REST API. I guess the alternative would be to develop a custom extension, which we would like to avoid.

**Comment by mattyza** [comment]
@mikejolley I assume this is related to the WC API not supporting the addition of private meta keys.

@maxrice @claudiosmweb is this intentional, for security purposes?

**Comment by mikejolley** [comment]
You need to be authenticated to change this data, so I see no reason why we cannot support non-core meta keys. Think we should add this into the next version of API, with 2.4

**Comment by claudiosmweb** [comment]
For me this need to be changed/included in the http://docs.woothemes.com/document/shipment-tracking/.
We can use the `woocommerce_api_create_order` and `woocommerce_api_edit_order` actions for allow and save this fields.

@mikejolley allow any field can lead to problems. E.g. in your API we have fields just for read, like price_html. So people can start send price_html and it will save in the database, but don't will return in the API.
Additionally save anything that the API receive will not provide proper validation or sanitization.
For example I can send:

```json
{
  "tracking_provider': true
  "custom_tracking_provider": true
  "tracking_number": true
  "custom_tracking_link": true
  "date_shipped": true
}
```

It will not have any warning me that for example `date_shipped` need to be a valid date.

**Comment by maxrice** [comment]
This was a design choice, because as @claudiosmweb sanitizing or validating protected meta is very challenging. The best approach is to have individual extensions add their own endpoints (e.g. `POST /orders/123/tracking`) and handle validation/sanitization.

That said, I can definitely see use cases where setting protected meta would be valuable. It might be possible to instead reject "WC protected" meta, like `_order_total`, etc. but allow custom protected meta. The downside here of course is that we'd have to define and maintain that blacklist. I'd probably vote for this option rather than wholesale allowing any protected meta to be set.

Certainly this data can always be changed server-side with custom code, but for someone working exclusively with the API, they might not understand why they should use the create/update methods provided rather than directly setting something like `_order_total`.

For reference the code that sets order meta is [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-orders.php#L758-L776) and displays it [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-resource.php#L272). Currently you can neither set or see protected order meta.

**Comment by claudiosmweb** [comment]
I do not know, especially in this case would be the best idea have an endpoint or treat custom fields within Shipment Tracking.
It would be better to add the data and also to recover them.

**Comment by mikejolley** [comment]
Moved to roadmap - some way to extend this would be useful https://trello.com/c/uyzaHUVi/63-rest-api-ability-for-plugins-to-extend-and-validate-extra-object-data

**Comment by diyontheweb** [comment]
Any update on whether this will be implemented? Thanks

**Comment by fabianhenzler** [comment]
@mikejolley any update on this? Using WooCommerce Subscriptions 1.5.30 with the WC-API to create orders therefore is impossible. So I can't use my AngularJS FrontEnd to post orders ;(

Please help :)

**Comment by claudiosmweb** [comment]
@fabianhenzler what update?
Each plugin needs to have its own API.
Subscriptions 2.0 have an API ;)
