### ISSUE TITLE
Orders created in Admin Panel activates Order.Update on Webhooks

### ISSUE THREAD

**Issue by debone** [woothemes/woocommerce#7684]
Hi,
I created two webhooks, one for Order.Created and the other for Order.Update.
When I create an order direct in the admin panel it activates the Order.Update Webhook when it should activate the Order.Created. If you try to buy something direct in the shop, it activates the right one, Order.Created.

Tested in two different setups and they behaved the same. I couldn't find any clues other than the [same action being added to both webhooks](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-webhook.php#L557-L565)

**Comment by claudiosmweb** [comment]
It's not exactly how it happens...
Because when you click in the "Add order button" the WordPress create an post/order empty.
When you finish to create the order it will just update.

So the problem is that when WordPress is a blank order, has no order data and because it we use `woocommerce_process_shop_order_meta`.
