### ISSUE TITLE
Itemprop Price Conversion Issue

### ISSUE THREAD

**Issue by michaelbroper** [woothemes/woocommerce#7761]
I detailed this here about a month ago but I believe the edit so old nobody saw it: https://github.com/woothemes/woocommerce/commit/8c57fce84d026242e170447b3794b516c56b598e#commitcomment-9844450

I had to fix this issue again on Woo 2.3. It's easy but I shouldn't have to fix this on every single upgrade.

I believe an appropriate solution would be to have a radio button option on WooCommerce' settings. 

Rich Snippet Display Price: Regular | Sale

And by default, have it set to regular price so it doesn't kill websites' conversion.

**Comment by mikejolley** [comment]
I think for the majority of stores, @sjeden argument should hold true. The advertised price on google should match the price you're actually selling the product at. Sale price if set. I feel this is important when you're selling something vs other vendors with 'lower' prices on google.

If you have a market with metrics proving otherwise, great - you can override the template file and show whatever you want. http://docs.woothemes.com/document/template-structure/ No need to edit core.
