### ISSUE TITLE
CSS conflict regarding select2.js

### ISSUE THREAD

**Issue by zaantar** [woothemes/woocommerce#7773]
Hi, I've discovered that WooCommerce makes it's own modification to select2 styles, and in one particular case this causes a conflict with the Views plugin.

Long story short: Would it be possible to use a more specific selector instead of `.select2-drop` to set the `z-index` to higher value than is the default (`9999`) provided by select2 library?

Thank you in advance for a reply :-)

**Comment by jameskoster** [comment]
Can't you just set the z-index in Views?

**Comment by decodekult** [comment]
Hi there . This is Views lead developer here.

Views is using the styles shipped with select2 and does not have any problem on its own. The issue is on a WooCommerce dropdown which custom styles get overriden by the native ones. So this is not a real compatibility problem with Views, but with any other plugin that could load the native select2 stylesheet.

As it is WooCommerce the one needing to override the native styles, it seems fair that it adds a more specific selector to do so.

Thanks in advance.

**Comment by jameskoster** [comment]
OK makes sense. So what is the actual issue? I don't really want to wrap all of our select2 styles unless absolutely necessary. If it's just a z-index style on one element I can probably tweak that.

**Comment by decodekult** [comment]
Hi James, sorry for the late reply. I did some debugging and here are my findings:
* WooCommerce (WC) is shipping with select2 3.5.2, both the js and css files.
* There are some differences between the native select2.css (found here: https://github.com/select2/select2/blob/3.5.2/select2.css) and the one included with WC. I did not do a complete diff, but I noticed that .select2-highlighted is getting a completely different set of styles (color hex fff  and background hex 3875d7 on the native styles, color hex 000 and background hex f1f1f1 on the WC version), to override the blue-ish background on highlighted items.
* The select2.css file shipped with WC keeps the z-index of 9999 to .select2-drop, as in the native one. But later on admin.css, WC overrides that z-index to 999999, I assume that is because of a nasty problem with modals which is reported all over the place on the select2 github and also on other projects, like ColorBox.

So WC is shipping a modified version of the native styles, and also it adds further modifications later on.

After all those point, the following facts:
* WC is enqueuing its admin.css styles at priority 10 on the admin_enqueue_scripts hook. Any other plugin enqueuing after it or with a priority over 10, with a copy of the native select2.css stylesheet is going to override the changes introduced by WC. For example, this is what is happening here.
* If I move WC enqueue to later, say at priority 99, then it forces all its changes, not just the z-index one, and we end up with the select2 dropdown being visible, but highlighted elements are in displayed in white on white.

So we do have issues no mater whether WC forces its styles (white on white text) or is being overriden by native styles (invisible dropdown on modals).

Now, the solutions. select2, at least in 3.5.2, provides a constructor parameter perfect for this job (http://select2.github.io/select2/): dropdownCssClass. This one lets you modify the select2-drop classname causing problems here. If WC needs specific styles on specific dropdowns, it should be applying its own classname and styling that instead. That sould solve the z-index issue and also provide a path to safely override also the .select2-highlighted styles as WC wants to do.

With select2 maybe coming to WordPress core, it also seems the wiser thing to do.

Hope it helps :-)

**Comment by jameskoster** [comment]
As a quick and easy solution, couldn't we just use an !important declaration for the z-index rules in our admin styles? Then any plugin enqueuing the native styles after should work fine, with our z-index fix intact?

I'm hesitant to spend a lot of time on this with select2 4.0 right around the corner.

**Comment by decodekult** [comment]
We could, but the best way to know it actually trying. Can you create a patch against the current version here so I can apply and test?

**Comment by jameskoster** [comment]
I just created the select2-admin branch - https://github.com/woothemes/woocommerce/tree/select2-admin please give that a try.

**Comment by decodekult** [comment]
Tested and it works as it whould now :-)

Thanks a lot.

**Comment by jameskoster** [comment]
Sweet! I'll merge that then.
