### ISSUE TITLE
Issue on sale_products shortcode

### ISSUE THREAD

**Issue by rusuandreirobert** [woothemes/woocommerce#7796]
I've found an issue on sale_products that is generating an huge mySQL query.
Out of curiosity, does that shortcode have pagination integrated in some way ? Because I'd like to fix the error I've found.

**Comment by rusuandreirobert** [comment]
I'll put in a few details. The WP_Query was receiving this kind of query params : http://codepad.org/MMlF0Xj6 . Over 5000 post__in when there were only 12 entries displayed on the page, even if I added an "hack" filter to limit the maximum filtered entries to 1000 . http://codepad.org/owLIc8H3 . Because it had posts_per_page 12 with no pagination.

**Comment by mikejolley** [comment]
The sale product ids are stored in a cached (transient) array which is passed to this shortcode's query.

So there are two choices here and nether are ideal;

1. Continue with the cached list of sale products and you work out why WPE won't query (SQL_BIG_SELECTS?)
2. Do more joins and do it in one query

Due to the WP schema, 2 will likely be worse for the majority of users as it would require 2 additional meta table joins to compare sale price to price. If you have millions of postmeta rows you can see the kind of overhead this would add.

cc @barrykooij @claudiosmweb
