### ISSUE TITLE
Layered Nav Refactoring

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#7806]
- [x] Optimise or find alternative to get_products_in_view https://github.com/woothemes/woocommerce/issues/7664
- ~~Add relation options between separate layered nav widgets https://github.com/woothemes/woocommerce/issues/6058~~ Too query intensive when mixing filter types. Staying as 'and'.
- [x] Avoid all layered nav logic when not using layered nav widgets
- [x] Slugs instead of IDs https://github.com/woothemes/woocommerce/issues/7892
- [x] Filter by rating

**Comment by ibndawood** [comment]
Hello @mikejolley , I'd like to try filter by rating. Can I go ahead ?

**Comment by mikejolley** [comment]
Sure @ibndawood

**Comment by ibndawood** [comment]
Thanks ! I've started working on Filter by rating. Will submit a PR as soon as I can.

**Comment by ibndawood** [comment]
@mikejolley, I have a question regarding Filter by rating : 

Do we need an amazon style filter which says 1 star & up, 2 star & up, etc like this : 
![image](https://cloud.githubusercontent.com/assets/179533/11092824/2cd21d2c-88ac-11e5-95c4-9c95a402e110.png)

or a layered nav style rating something like this : 
![image](https://cloud.githubusercontent.com/assets/179533/11092867/94789b68-88ac-11e5-8117-15860e36f420.png)

Let me know your thoughts.

**Comment by mikejolley** [comment]
Personally, I think Amazon style is way more useful. No one searches in real life for 3 star products only, but may want 3+. I think that makes the most sense.

**Comment by ibndawood** [comment]
Thanks for the inputs @mikejolley

**Comment by ibndawood** [comment]
Hello @mikejolley, here is the PR for filter by rating : https://github.com/woothemes/woocommerce/issues/9594

**Comment by ibndawood** [comment]
Hello @mikejolley , I'd also like to try "Slugs instead of IDs". Can I go ahead ?

**Comment by ibndawood** [comment]
Hey @mikejolley , any word on the PR I submitted for filter by rating ?

**Comment by mikejolley** [comment]
@ibndawood not had to time review it yet as I'm on support rotation. Will try to look early next week.

**Comment by nickkuijpers** [comment]
Hi Mike,

I've been strugglin with the speed of the layered nav for some time now and i've programmed some things in Laravel. I've came to the conclusion that all things about generating filters has the take place in the database instead of in PHP. I've had php data management to get all unique filters and counts of the amount products in a filter but the load time was 120 seconds for 250k products with 5.5m attributes. I've got it up to 300 ms with a nice mysql query. Isn't this the solutions for the performance in WooCommerce Layered Nav's also? 

My query gets all products of a certain category, for each result it gets all the attribute filters, in the query add the amount of active filters so you can distinct count the unique attribute names and only return the filters which have products and matches the amount of active filters.

**Comment by mikejolley** [comment]
@nickkuijpers We also have to consider the display of counts, not just the actual filtering. If you have a code proposal feel free to submit as a PR for feedback.

**Comment by nickkuijpers** [comment]
Okay nice, will do. Just gotta make some time for that. The count is possible, i haven't got it in my code right now in Laravel but i can make that work as a test. If that works i will try to integrate it in WooCommerce and see what the performance is. You'll hear from me.

**Comment by nickkuijpers** [comment]
@mikejolley 

Got some progress on my side project where i am creating the filters. Tested the count of products in filters and got it working with a very nice performance. See; http://koophetzelf.sageinku/verlichting/lichtbronnen/compactfluorescentielampen/spaarlamp or search for 'aa' or something in the search bar on top. Will check this out soon in WooCommerce to see if i can optimize it.

**Comment by mikejolley** [comment]
@claudiosmweb existing PRs can be reviewed for 2.6, but main effort pushing back to 2.7 as 2.6 scope is large enough.

**Comment by ibndawood** [comment]
@mikejolley :+1:
