### ISSUE TITLE
Product Categories Not Showing Products

### ISSUE THREAD

**Issue by dropsprops** [woothemes/woocommerce#7810]
Please help! My customers cannot see my products!

When you select a product category, you get a blank page!

Tried disabling all plugins and changing the theme so neither of those is the problem.

NEED HELP ASAP!!

**Comment by mikejolley** [comment]
This is not a support area - github is for bug reporting only. 

Read here: https://wordpress.org/support/topic/how-to-debug-issues-after-updates?replies=1 WP_DEBUG will tell you what the issue is.

If after doing that you need help and you're a WooThemes customer, you should raise a ticket here: support.woothemes.com
