### ISSUE TITLE
Discounting with coupons calculated incorrectly?

### ISSUE THREAD

**Issue by joshcanhelp** [woothemes/woocommerce#7837]
I'm working with a client that is saving their order totals to another system for reporting. This process runs after an order is complete so it does not affect any core WooCommerce processing. 

I was testing an order today and noticed that the total price on the reporting side was $0.01 off from what was charged. I thought maybe I was calculating the discount improperly on my side but I don't think that's the case. 

The cart total is $153. There is a 25% off coupon applied as well as a $50 store credit (using Smart Coupons). $153 * 0.75 - $50 = $64.75 as the total, $88.25 as the discount, as I calculate it. But the discount was $88.26 on the order and the total is $64.74:

![screenshot 2015-03-27 11 13 17](https://cloud.githubusercontent.com/assets/855223/6874223/dae971b0-d472-11e4-934b-e750d8e0ecae.png)

I tried looking at the order detail page but the calculation was confusing:

![screenshot 2015-03-27 11 13 27](https://cloud.githubusercontent.com/assets/855223/6874230/e31b7216-d472-11e4-8562-d07041136128.png)

$67.50 * 0.75 - $25 = ~ $25.63 ... not what is shown
$67.50 - ( ( $153 * 0.25 + $50 ) / 2 ) = $23.38 ... also not what is shown 

I'm wondering if $0.005 is being rounded up to $0.01 per item, giving slightly more of a discount than it should.

**Comment by mikejolley** [comment]
Discounts are stored applied to the line. In the above screenshot:

Line 1 discount = 67.50 - 28.56 = 38.94
Line 2 discount = 85.50 - 36.18 = 49.32
Total = 38.94 + 49.32 = 88.26

This matches the totals shown.

For the calculation, I would need to see this without store credit applied (just dynamic pricing) to see where the rounding occurs, but I'd imagine its per line.

As for store credit, its credit, so should be applied after tax. I cannot tell if this is the case above - it looks to have been done before tax which is wrong. Raise a ticket on support if you're using latest versions so that can be rectified - thats your biggest issue right now IMO
