### ISSUE TITLE
Restock cancelled order

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7848]
Is there a way to add a "Restock items" like we do for refunds, but when the admin cancel an order?
For example when a customer choose to pay with BACS but never pay you would cancel the order and restock the item.

**Comment by BFTrick** [comment]
What if it was part of the refund process? Like a popup that prompts you during the refund process?

**Comment by SiR-DanieL** [comment]
It's not always a refund.
I can cancel an order without refunding it.

**Comment by BFTrick** [comment]
Hmmm true. I can definitely see a use case for this if we can fit it in.

@jameskoster what do you think of this?

**Comment by a1ur3l** [comment]
Can be added a check box for restock. When we need to restock, just check it and automatically restock them.

**Comment by jameskoster** [comment]
You can already do this by increasing the stock for each line item before (or after) cancelling the order, right?

Generally speaking though, should stock always be restocked for cancelled orders? It's not like a refund where an item might be sent back as faulty, unable to be resold. So shouldn't we just make this happen automatically when an order is cancelled?

**Comment by SiR-DanieL** [comment]
> You can already do this by increasing the stock for each line item before (or after) cancelling the order, right?

Also if you can, we should have something better to handle this.

> Generally speaking though, should stock always be restocked for cancelled orders?

Yeah, probably. I can't think of any case where you should cancel an order without restocking.

**Comment by jameskoster** [comment]
OK so making it restock automatically probably makes sense... but I don't want to disrupt peoples workflows. Maybe float the idea amongst some power users @BFTrick ?

Should be in 2.4 if we decide to do it.

**Comment by BFTrick** [comment]
Alright. Talked to a few store owners about this. In short, for businesses that sell products as opposed to event tickets or something like that many times you cancel or refund an order because something went wrong. A product was broken, the shipment never arrives, or something like that. For cases like this we don't want to replenish the inventory.

In certain cases like when you sell event tickets where the product is almost virtual you _always_ want to restore inventory so that someone else can get the limited product.

**Many of our stores sell physical products so we should default to _not_ replenishing inventory**. We still need to make it easy for stores that need to replenish inventory. I think we should add a checkbox near the refund button or during the refund process that a store owner has to check to replenish the inventory.

I don't think we need a button (why would we let someone press it multiple times?)

**Comment by jameskoster** [comment]
A checkbox might not work. What if there's multiple items on the order and you only want to restock some of them?

I feel like this is pretty niche. Isn't being able to restock line items adequate?

**Comment by BFTrick** [comment]
What do you mean restock line items?

**Comment by jameskoster** [comment]
On the order screen, select a product the perform the "Increase line item stock" action. http://cl.ly/image/0K351T0H3x2w

**Comment by BFTrick** [comment]
I didn't even know that was there. Was that introduced in 2.3? I don't think this is a major issue and people who are refunding often will probably look for buttons (which I skipped over) to do this for them.

Up to you James.

**Comment by jameskoster** [comment]
It's been there a while I think xD tbh, I think it's adequate.
