### ISSUE TITLE
Flat Rate Shipping - Bug with Additional Costs

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#7851]
For Flat Rate Shipping, if the "Costs Added" section is set to either Per Item or Per Class, and the fields/rows under it are left empty, then the flat rate shipping option never gets returned at checkout: http://cld.wthms.co/1bnKz

This is pretty self-explanatory for reproducing: 

1. Activate Flat Rate
2. Set a Cost per Order
3. Test on checkout
4. Go back and change "Costs Added" to Per Item
5. Test on checkout

So essentially, it depends on the Costs Added to be set to "Per Order", else it checks for a value in the Costs section, and returns void if it is empty.

@ChromeOrange

**Comment by jj43116** [comment]
I am also experiencing what I think is the exact same issue but I want to elaborate to be sure.  

1) Flat Rate Shipping is activated with base cost per order of $5.
2) I added 2 add-on rates:
2-Day Shipping | 5.00 | Order
Overnight Shipping | 10.00 | Order
*Everything works at this point
3) Then, I created a shipping class, assigned it to one product and went back to flat rate options and added the shipping class as an additional cost "Per Item" with a $4 cost
4) Now, anytime I have a product with that shipping class in the cart, my shipping options are all correct (even if other products without the shipping class are in the cart in addition to the shipping class product).  

If none of the products in my cart are within that shipping class, I am left with only two shipping options, the 2-day priced at $5 (instead of the correct amount of $10) and Overnight shipping at $10 instead of $15.  The base flat rate shipping method and its $5 cost is completely disregarded.

**Comment by roykho** [comment]
@jj43116 can you please post a screenshot of your settings so I can more clearly see?

**Comment by jj43116** [comment]
These are the settings:
![screen shot 2015-04-07 at 12 37 11 pm](https://cloud.githubusercontent.com/assets/11823789/7030583/dfc77778-dd22-11e4-8726-bdb4ee8b4060.png)
![screen shot 2015-04-07 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/11823789/7030582/dfc34f36-dd22-11e4-9bae-a4f32df21e55.png)

These are the incorrect shipping options that show up during checkout when a product from the "Drill Shipping Class" is NOT added to the cart:
![screen shot 2015-04-07 at 12 38 08 pm](https://cloud.githubusercontent.com/assets/11823789/7030637/2b9e8452-dd23-11e4-8da9-9b0edf5e7f19.png)

These are the correct shipping options when at least one or more of the products with the "Drill Shipping Class" are in the cart:
![screen shot 2015-04-07 at 12 41 15 pm](https://cloud.githubusercontent.com/assets/11823789/7030697/6ef13a42-dd23-11e4-9324-6e118ba57c71.png)

**Comment by roykho** [comment]
@jj43116 please apply the fix in the patch I've created and see if that resolves your issue.  If not, then your issue is not related to the OP.

**Comment by jj43116** [comment]
It worked!  You are truly a man among boys.  When do you think this fix will be added to a WooCommerce update?

**Comment by jj43116** [comment]
@roykho Do you know when this fix will be added to a WooCommerce update?
