### ISSUE TITLE
Infinite Recursion / Memory Exhausted when calling WC_Cart::get_cart() before wp_loaded

### ISSUE THREAD

**Issue by om4james** [woothemes/woocommerce#7852]
If a plugin or extension calls `WC_Cart::get_cart()` too early, WooCommerce 2.3.x can encounter an infinite recursion error, resulting in memory exhausted errors and HTTP 500 errors.

WooCommerce 2.2.x did not have this problem.

In my opinion, this is a bug/regression introduced in WooCommerce 2.3 via this commit: fb8f5fc750baa772fa057731479fad74a20d33aa (as part of #6873).

Previously discussed here: https://github.com/woothemes/woocommerce/commit/fb8f5fc750baa772fa057731479fad74a20d33aa#commitcomment-10459566

cc: @daigo75, @mikejolley, @ChromeOrange 

There's at least 3 WooThemes tickets that I know of that are affected by this problem:

272262, 268454, 271293

I understand that plugins/extensions aren't supposed to call `WC_Cart::get_cart()` prior to `wp_loaded` (the `_doing_it_wrong()` warning was added in WC 2.3), however I think WooCommerce should be improved so that the infinite recursion error is not possible at all.

Here's a relevant stack trace that occurs when WooCommerce Zapier, Groups and Groups WooCommerce are activated together.

These plugins worked without any errors in WC 2.2, but as of WC 2.3 an infinite loop occurs causing memory exhausted issues.

**Comment by om4james** [comment]
cc @itthinx

**Comment by daigo75** [comment]
For reference, I patched a couple of sites with my proposed fix and they all work correctly now.

--- Original Message ---

**Comment by itthinx** [comment]
@om4james Thanks for all the info provided, very useful. I've checked Groups WooCommerce to see in which case we could be calling `WC_Cart::get_cart()` before `wp_loaded`.

The plugin adds two filters on the options `woocommerce_enable_guest_checkout` and `woocommerce_enable_signup_and_login_from_checkout`. While these would not be triggered with WooCommerce & Groups WooCommerce alone, I can imagine that it could happen when the options are required in another plugin. This should be fixed in Groups WooCommerce so that it doesn't even call `WC_Cart::get_cart()` unless 'wp_loaded' was done.

**Comment by daigo75** [comment]
@itthinx The bug still stands, though, and it should be fixed in WooCommerce.

The call to `WC_Cart::get_cart()` is not the issue by itself and, as pointed out by @om4james, it worked whether `wp_loaded` was executed or not in WC2.2 and earlier. From my perspective, it should work in 2.3+ as well (I don't see why not, it's a breaking change that doesn't seem to have a clear reason).

The core issue is that just checking if an event was executed before performing an operation is insufficient, and the solution is not to "**just stop calling `get_cart()` at that stage**". There may be a reason for this new check, but, again, it worked fine until now, I don't see why that should change.

What the bugged code does
--
1. `WC_Cart::get_cart()` is called.
2. Was wp_loaded called? No.
3. Ok, I will load the cart and inform the users.
4. Loading the cart triggers event that plugins may use to get the cart.
5. `WC_Cart::get_cart()` is called. Back to #1 and infinite recursion.

What the code should do
--
1. `WC_Cart::get_cart()` is called.
2. Was the cart loaded already? No.
3. Was wp_loaded called? No.
4. Ok, I will load the cart and inform the user.
5. Loading the cart triggers event that plugins may use to get the cart.
6. `WC_Cart::get_cart()` is called. 
7. Have I loaded the cart already? **Yes**. Just return its content.

**Comment by om4james** [comment]
I agree @daigo75 - this is a regression/bug that was introduced in WC 2.3. It wasn't an issue in WC 2.2.x.

It's a pretty big deal if WooCommerce sites are crashing / white screening because of this, so it would be good if WooCommerce core devs could investigate and implement a fix for this.

Unfortunately I'm not very familiar with the reasoning/changes in fb8f5fc / #6873, so I'm not sure what the best fix is.

**Comment by om4james** [comment]
Thanks for this @mikejolley, your solution in 1f3365f looks good to me  :+1: 

Do you think this fix should be included in the next 2.3.x release as well, given that it was a bug introduced in 2.3?
