### ISSUE TITLE
Incorrect Coupon Calculation

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#7853]
Steps to Replicate:

1. Create product costing $3.50 and add 20 of that product to the cart, i.e total cart value is $65 ![](http://cld.wthms.co/J9Sd+)
2. Create a coupon that offers a 'Cart % Discount' of 10. ![](http://cld.wthms.co/CGxv+)
3. Now apply the coupon on the above cart, 10% off on $65 total should be $6.50 and not $6.60 ![](http://cld.wthms.co/10jH+)

https://woothemes.zendesk.com/agent/tickets/276639
@seanreloaded @ChromeOrange @mikejolley

**Comment by underwd** [comment]
Note that this is a rounding-up error for products that end in an odd integer, so the coupon discount must be being applied to each product instead of the cart subtotal.  When I posted this issue to WC support I also stated that shipping and tax functionalities were disabled, as we don't use either.  Thank you.

**Comment by greguly** [comment]
https://github.com/woothemes/woocommerce/pull/6317

**Comment by mikejolley** [comment]
This was broken here: https://github.com/woothemes/woocommerce/pull/4602

**Comment by mikejolley** [comment]
https://github.com/woothemes/woocommerce/commit/2d99e060a1bd5a347ed141d66bc186ca2941d3de
