### ISSUE TITLE
UX: Better error message on (accidentically) wrong coupon name

### ISSUE THREAD

**Issue by jnachtigall** [woothemes/woocommerce#7870]
When a customer enters a coupon name and mistypes, then the error message is:
```
'Coupon does not exist!'
```

So the customer does not know if the coupon does really not exist, or if there was a typo in coupon name... and types in again (possibly several times)...

I think this should be changed to 
```
'Coupon <the-coupon-name-as-typed-in-by-the-customer> does not exist!'
```

I search for the string in the [code](https://github.com/woothemes/woocommerce/blob/65bc9db76360c7ff7738f0320cb734134e50e8ea/includes/class-wc-coupon.php#L714) and it seems there are even more coupon related messages that should also include the passed coupon name.

Just a small detail but all these small details together make up a great product (also from an UX perspective) :-)

**Comment by WPprodigy** [comment]
I think all the other error messages all suggest that the coupon message was once a valid coupon, but then state why it is not valid at the moment. So a typo is not as likely in those situations. However, in the one you mentioned, there is a typo chance. 

So it could be improving the UX by letting them see what it is they typed in, rather than making them have to try the same code again.
