### ISSUE TITLE
Conflict with Yummly Plugin

### ISSUE THREAD

**Issue by kdub1312** [woothemes/woocommerce#7881]
Hello,

There is some sort of conflict between the Woocommerce and Yummly plugins. Based on the comment thread below, it's on your end, specifically the get_the_title() function call:

https://wordpress.org/support/topic/compabitility-issues-with-woocommerce?replies=7

It's my understanding Yummly is built on Zip Recipe, so I believe the problem is the same for both.

The problem manifests itself in the Edit Post area, when I click on the 'yum' icon the Yummly editing lightbox appears but there is no content. 

Has this problem come up before? Is there a work-around?

Regards,

Kevin

**Comment by kdub1312** [comment]
has anybody seen this? any idea what could be going on?

**Comment by mikejolley** [comment]
I think its because get_the_title is being used in admin in this case. Easy to work around.

By the way, when testing I got these which need patching their side https://dl.dropboxusercontent.com/s/s7lylcj92i942qp/2015-04-10%20at%2016.16%202x.png?dl=0

And these https://dl.dropboxusercontent.com/s/ikpdsnbj94vyjtq/2015-04-10%20at%2016.19%202x.png?dl=0

Notices everywhere.
