### ISSUE TITLE
Google indexing prices before taxes

### ISSUE THREAD

**Issue by l3hworks** [woothemes/woocommerce#7895]
Hello, I recently started a woocommerce site and I've noticed that google is indexing products with the prices before taxes. So any potential client is seeing the wrong price in the description snippet.

We've selected the options to put our prices before taxes, but to show the prices after taxes in public (obviously), then we're wondering how's google getting that wrong when is visible only with taxes..

Edit: I *think* found the culprit in meta itemprop="price" content="21.446", that is the price before taxes, not final public price.

Any way (or built in option) to get the price after tax would be a good thing imo.

Edit 2: Changed the "content" value to <?php echo $product->get_price_including_tax(); ?> in price.php , line 21, seems to do the trick.

**Comment by DeboMediaGroup** [comment]
For reference, what was the value set to before you made the change?

**Comment by l3hworks** [comment]
Original line:
<meta itemprop="price" content="<?php echo $product->get_price(); ?>" />

Changed to:
<meta itemprop="price" content="<?php echo $product->get_price_including_tax(); ?>" />

**Comment by mikejolley** [comment]
This solution won't work for all users. "Tax" is based on the user location - Google can only index one value. So what is correct for one user, may be completely wrong for another. Therefore IMO its best to use get_price() - this will use an exclusive of tax price if prices do not include tax, or tax for the location of the store if prices are inclusive of tax.

Hope that makes sense.

**Comment by l3hworks** [comment]
Actually nevermind, this change of code I put didn't do anything, dunno why I got that impression. The actual "culprit" is the geolocation, it takes into account whatever ip google spiders use, and its logic. So... No issue here.

**Comment by Christian747** [comment]
Hi Mike,

I would like to reopen the debate regarding this issue. Particulary because Google threatens to suspend my account in the Google Merchant Center permanently. Reason for this is because produ t prices (which are vat inclusive) in the Google product data feed do not match product prices in the WooCommerce shop. Somehow Google is only able to detect prices exclusive of vat in the WC shop.

In the Google Merchant Center:
Google product data feed contains prices incl vat (in compliance to my country's vat which is Belgium)
The data feed is set for my country (Belgium)
The location of my shop is set to my country (Belgium)

In the WooCommerce shop: 
Product prices are calculated excl vat
My country's vat has been set (Belgium)
Product pages display prices incl vat (Belgium)
Calculation of tax is based on my shop base address (Belgium)

Now, Google is very serious about this, hence the fact that I'm facing permanent account suspension.

Any ideas on how to fix this?

Thank you in advance.

**Comment by mikejolley** [comment]
More recent thread here https://github.com/woocommerce/woocommerce/issues/18852
