### ISSUE TITLE
Inclusive Tax Pricing not properly displaying at Checkout

### ISSUE THREAD

**Issue by tommyshellberg** [woothemes/woocommerce#7903]
I'm getting different prices for products depending on the billing location, even though pricing is set inclusive of tax.

Settings:

(http://cld.wthms.co/17P89)
(http://cld.wthms.co/1gUSm)

Working properly with CO as state:

(http://cld.wthms.co/18ErS)

Change the state:

(http://cld.wthms.co/171S0)

UK as country:

(http://cld.wthms.co/ckQ)

The product price is set at $88, it should always be $88 regardless of the amount of tax, correct?

**Comment by tommyshellberg** [comment]
@ChromeOrange are you able to reproduce this?

**Comment by ChromeOrange** [comment]
@tommyshellberg 

>are you able to reproduce this?

Yes. That's how it should work. 

Imagine a tax rate of 20% for Ohio and a tax inclusive price of $120. If the tax rate in Colorado is 10% then the product price will change to $110 because the tax inclusive price includes 20% tax for Ohio customers and 10% tax for Colorado based customers. The base product price doesn't change, but the tax amount does.

In the US you don't use tax inclusive pricing.
