### ISSUE TITLE
Variation Image Flashes Original Image

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce#7904]
So currently if you have your default attribute set to something other than the original, when the single product page loads, it will flash the original variation image/main image first and then it will display the featured image for the default selected variation.

![](http://cld.wthms.co/1dzrz+)

For slower sites, the original image will stay on the screen longer and looks quite unprofessional.

We need to check for what the default attribute is set to and display the image for that right off the bat so we don't get a flash of original image.  I can think of a couple ways of doing this but would like to you guys thoughts on this.  @mikejolley @claudiosmweb @barrykooij

**Comment by mikejolley** [comment]
I think this may have implications, such as when you 'reset' it needs to revert to the default product image. If this is a major issue due to speed, perhaps those speed issues would be better looked at as those IMO would have a larger impact on professionalism. This shouldn't be a problem for most sites.

**Comment by roykho** [comment]
This is on my localhost http://cld.wthms.co/1f0f3 See the flicker.

**Comment by roykho** [comment]
I propose we just load the correct image on first load instead of using JS to swap it out.

**Comment by mikejolley** [comment]
Plan: Fade in gallery/image if defaults are set.
