### ISSUE TITLE
Please add email confirmation in billing form

### ISSUE THREAD

**Issue by Tigzy** [woothemes/woocommerce#7984]
about 5% of my customers misspell their own email address, resulting on the invoice being sent to another (existing or not) email. Having a "Enter your email again" field, with copy/paste forbidden would be a plus.

Thanks in advance.

**Comment by Kenshino** [comment]
The longer the check out process, the more likely carts get abandoned.

The form should be as short as possible, it does not make sense eg in your case, to make 95% of your customers do extra work because 5% of them type it wrong.

In any case, such a thing is already do-able yourself - http://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/

**Comment by Tigzy** [comment]
Well, extra work is for me here :)
Thanks for the link.

**Comment by mikejolley** [comment]
https://wordpress.org/plugins/woocommerce-email-validation/
