### ISSUE TITLE
Allow duplicate SKUs when subscriptions come into play

### ISSUE THREAD

**Issue by majemedia** [woothemes/woocommerce#7992]
Because simple/variable and subscription based products can't be combined into one product there could potentially be a need to have duplicate SKUs across those two.

### Example:
A company selling a packaged food product wants to be able sell a one-off purchase of a product and also a subscription to that product.

Using the current rules in place the requirement that each SKU be unique between the subscription product and the simple/variable product.

I understand that in #5712 the decision was made to enforce unique skus across the entire platform. This could be a potential reason to allow for a setting to let WooCommerce in general and even WooCommerce + WooCommerce Subscriptions be even more flexible.

**Comment by panploenes** [comment]
Did you ever consider that a one-off purchase is actually a different "product" then a subscription?

Of course in your example they are both the same physical product, but they are different services.

If i take your example and say want to look at my sells of the last year, i want there to be two different SKUs. 
I want to know how many people bought only a one off and how many went for the subscription.

Maybe i misunderstood you....

**Comment by majemedia** [comment]
@panploenes I completely agree with you in the context of a contained system (one that only has outlets via WooCommerce). I disagree with you in the context of a more segmented distribution of products.

Which is why I suggested possibly having a setting (that by default is on) to allow duplicate skus.

**Comment by mikejolley** [comment]
It was actually decided since day 1, but #5712 was a bug. I agree with this comment: https://github.com/woothemes/woocommerce/issues/5712#issuecomment-46751657

SKUs need to be unique; making them not so could have consequences, such as no longer being able to determine product ID from SKU. 

I believe you can filter this to prevent the check https://github.com/woothemes/woocommerce/blob/5a765aa4ef24e5706c23af9c867e02ce61dfb952/includes/wc-product-functions.php#L536 but I don't feel we should support in core. You could log this on ideas.woothemes.com if you wanted and if many store owners need it, we can reconsider.

**Comment by majemedia** [comment]
@mikejolley thanks for the pointer in the code. Looks like that specific filter hasn't yet been made available as of 2.3.8. I'll wait until a version is released that has the new filter on it.
