### ISSUE TITLE
Backwards incompatible template change in 2.3.8 

### ISSUE THREAD

**Issue by coenjacobs** [woothemes/woocommerce#7994]
This behaviour was introduced in [this commit](https://github.com/woothemes/woocommerce/commit/c52a117117597f8e6edc8bb4189b60cfbd560372). The function call in the template got removed, added back via an action. Every theme overwriting this template will still have the original function call, as well as the function added via the action and therefore will show the cart totals twice.

This shouldn't be pushed in a fix release like this, in my humble opinion. I now just want to make sure this is intentional, so we don't revert it in a couple days when everyone has fixed this in their themes.

FYI: I provided a [quick fix for users](https://wordpress.org/support/topic/cart-sum-two-times?replies=10#post-6846946), as it got reported on the .org support forums already.

**Comment by jameskoster** [comment]
It's intentional. In hindsight we could have left this for a later release, I didn't expect so many themes to be overwriting that template. I should probably know better by now though...

Let's monitor this, if the outcry gets worse we can revert and add this to 2.4. I'd prefer that folks spoke to their theme authors for a fix though as it's a very simple tweak.

**Comment by coenjacobs** [comment]
I agree with you. Except for this:
> I'd prefer that folks spoke to their theme authors for a fix though as it's a very simple tweak.

That's not true for fix releases like this. You should be able to run those without having to worry about breaking things (unless your theme does really weird things, which, imho, template overrides are not).

**Comment by jameskoster** [comment]
I agree. I just meant that I'd prefer themes to be updated rather than reverting the change, even if it's not really best practise. Especially now that you've posted suggesting people to remove the call to `woocommerce_cart_totals()` on .org. If people do that in their theme, then we revert, they're going to have no totals at all which is much worse than having it duplicated imo :p

If worst comes to worst I suppose we can just add a new hook for the totals which would achieve the desired result without breaking backwards compatibility.

**Comment by glueckpress** [comment]
> I'd prefer that folks spoke to their theme authors for a fix though

You bet they are, and a template change like this still shouldn’t go in a fix release for the reasons outlined by @coenjacobs. If it does, please post a note in advanced on the dev blog. Imo that’s the least one could expect when templates are changed significantly in a minor release. 

Maybe keep in mind that [this](https://twitter.com/glueckpress/status/590424948641955840) isn’t trivial. It is a real business challenge for smaller theme shops. In order to _not_ run into a situation like today where we have 1 plugin and 4 themes broken more or less out of the blue, we would literally have to hire someone to analyze what you guys are doing in this repo day by day and whether it has impact on our products. We _are_ following the dev blog and will read notifications from here even more careful now, and there’s no need to remind us of that responsibility. I’m just saying there’s something you guys could do, as well, and that would be to think twice about the implications of a “fix” like the one discussed here.

And, please, _don’t_ revert. :) It’ll make everything even worse.

**Comment by andyexeter** [comment]
Obligatory link to http://semver.org/

Please, please stop pushing backwards incompatible changes in patch releases

**Comment by jameskoster** [comment]
Going to close this. We're leaving the change as it is. Fixing any issues is a very simple process and reverting would just cause more headaches. Apologies for anyone affected by this, we'll be extra careful with these changes in future.

**Comment by glueckpress** [comment]
Apologies accepted. :)
