### ISSUE TITLE
Improve Refund Reporting

### ISSUE THREAD

**Issue by mikejolley** [woothemes/woocommerce#8028]
- Refunds need to be shown in the month they are performed
- Currently, changing order status tor refunded will remove the order from the reports from its order date
- A refunded order is allowed to contain partial refunds, but is still considered fully refunded so this makes it more complex

Plan:
- When fully refunding by changing order status, create a refund line item
- Include refunded orders in the reports

**Comment by mikejolley** [comment]
@barrykooij @claudiosmweb @roykho I've done some work on this in the above branch. I've tried to make it work so that if you refund in one month, the totals are adjusted for that month only. Previous months are unaffected. Thoughts?

@kloon Would be good to get your feedback as we use stats on woo.com. Will also need some feedback on an upgrade routine (to ensure there are line item level refunds on all refunded orders)

**Comment by angelleye** [comment]
I'm noticing something that I'm a little confused about, and I'm wondering if it has something to do with changes here..??

In our payment gateway extension for WooCommerce we added the refund capability when it was introduced in WooCommerce.  We have a line where we are updating the order status to refunded when the refund occurs, of course.

I've been testing adjustments we've made since the WC 2.4 release, and I noticed that for some reason when I would issue a partial refund through the WC order page using our gateway, the API request for our gateway was correct and issued the partial amount we entered, however, the WooCommerce order got updated to reflect that the entire amount had been refunded.

When we removed the line of code that updates the order status this stopped happening and WC would correctly reflect the partial amount that was refunded.

Then I checked what would happen if I manually update the order status to Refunded, and sure enough, the order's refund amount was automatically set to the full order amount, so it seems that this is what's happening when we do that via code, too, regardless of the actual order amount that was entered into the refund tool.  

Is this expected behavior?  Was this something that was changed in 2.4 causing this?  Any info on that would be greatly appreciated.  Thanks!

**Comment by mikejolley** [comment]
@angelleye Your gateway should handle the refund calls only - it should not touch the order data or order status. let WC handle that.

**Comment by angelleye** [comment]
@mikejolley Thanks for the reply, but I guess I'm a little confused.

When we do nothing but process the refund then the WC order status remains on "Processing" or whatever it was prior to the refund.  That is why we were updating the status to Refunded.  

Now, though, any time the status gets updated it automatically sets the refund amount to the total amount of the order instead of the amount entered into the refund field.  So again, if I remove that update the order updates correctly as far as the amounts go, but then the status gets left alone and doesn't update to Refunded.

**Comment by angelleye** [comment]
Sorry to keep bothering about this, but I'm getting the same experience with built in gateways, not just my own.  

For example, if I checkout with COD for $100 and then do a partial refund of $50, it correctly reflects that $50 has been refunded, the partial email goes out, etc.  The status of the order is still Processing, though.  There is no "partially refunded" status available, and as a seller I don't just want to leave it as Processing, so setting it to Refunded seems logical.  When I do this, though, the order now reflects that the entire amount of $100 was refunded, not just $50.  

Am I missing something?

**Comment by angelleye** [comment]
I guess as opposed to Refunded, an order with a partial refund would be Completed..??  Then it would hold the partially refunded amount correctly.

**Comment by mikejolley** [comment]
@angelleye Refunded status is for fully refunded orders. Partially refunded orders should not change the status.

**Comment by angelleye** [comment]
@mikejolley Thanks for the clarification.  Just FYI, from the testing I've done the Woo system does not update the order status to Refunded even if I do a full refund.  I have to do that manually.  Is that intended?  I went ahead and added logic to our gateway so that if the refund is a full refund it will go ahead and update the status to refunded.  If not we're leaving it alone.  Do you see anything wrong with that?

**Comment by mikejolley** [comment]
You should leave it for WC. It's checks for more than order total, it checks for line item qtys too. Otherwise 'free' products in orders would also be 'refunded'.
