### ISSUE TITLE
VAT rounding should be done Unit wise

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce#8047]
Create a product for £1.66 and calculate a VAT of 20% on it while adding 36 items of this into the cart, Now the order has been broken down to have £11.95 VAT where as  it should have been £11.88. This is because WooCommerce doesn't round VAT per unit so instead of 20% of £1.66 being 33p, WooCommerce takes it as 33.1944.

Is there a way that the rounding per unit can be done for VAT calculations?

https://woothemes.zendesk.com/agent/tickets/285479
@ABDpromotions @mikejolley @ChromeOrange

**Comment by mikejolley** [comment]
Per line is how we do it and is perfectly acceptable as long as you are consistent.

> Either way is acceptible to HMRC. For example, Sage 50 Accounts does it on a line by line basis, Sage 200 Accounts does it on the total.
> http://www.ukbusinessforums.co.uk/threads/vat-round-up-or-down.164941/

1.99 inc vat product x 36 = 71.64
71.64 - ( 71.64 / 1.2 ) = 11.94 Tax

I don't think there have been any other requests for per-item rounding, and I'm not sure on the legalities of such an option, but it should be logged on http://ideas.woothemes.com/ if needed or built custom.

**Comment by batesy87** [comment]
@mikejolley - sorry to comment on such an old issue but it's the only one I have found that states "Per line is how we do it" in regards to rounding tax.

I have a similar issue to OP but I have 17 different items all with the same price (so 17 lines)

Item(s) price £1.49
VAT @ 20%
Prices entered inclusive of VAT

if VAT were rounded per line, each line would have £0.25 VAT, however the total VAT is £4.22 and not £4.25

My companies financial software rounds VAT per line also but it gets £4.25 so there is a discrepancy

I've tried changing the setting "Round tax at subtotal level, instead of rounding per line" but it seems to have no effect on this

![www heartandhome com-en-gb-basket--removed_item 1](https://user-images.githubusercontent.com/1161433/28883608-f3dbc3b0-77a6-11e7-9eea-c377b724e546.png)

**Comment by ChromeOrange** [comment]
@mikejolley Gotta love taxes ;)

12 products

![](https://dl.dropboxusercontent.com/s/2klch6o5khdez27/2017-08-03%20at%2009.43.png)

vat inclusive price is £1.49
exclusive price is (according to WC) £1.24 (1.49/1.2 = £1.242)
£1.49 - £1.24 = £0.25
£0.25 x 12 = £3.00

£1.24 x 0.2 = £0.248 VAT
£0.248 x 12 = £2.976, rounded to £2.98 

maybe it's time for a round up/down option which will probably break £9.99 products.

Alternatively, for inclusive prices, calculate the tax based on the Inc price - displayed ex price?
