### ISSUE TITLE
Reviews reveal author emails in page source

### ISSUE THREAD

**Issue by axcho** [woothemes/woocommerce#8152]
When a user posts a review, they expect their email to be hidden from other users and search engines. However, the alt text of the gravatar icon is the user's email, which serves no functional purpose, and is a breach in privacy. I was alerted to this problem on my own WooCommerce site by one of my own customers, who was not particularly happy about this discovery.

This can easily be fixed by modifying this line:
https://github.com/woothemes/woocommerce/blob/master/templates/single-product/review.php#L23

    <?php echo get_avatar( $comment, apply_filters( 'woocommerce_review_gravatar_size', '60' ), '', get_comment_author_email( $comment->comment_ID ) ); ?>

And changing it to:

    <?php echo get_avatar( $comment, apply_filters( 'woocommerce_review_gravatar_size', '60' ) ); ?>

It would be great if this could be fixed before the next major WooCommerce update! Thanks.

**Comment by SiR-DanieL** [comment]
We can't use `get_gravatar` that way. It would retrieve the wrong gravatar if the user has been created originally by an author and then assigned to another one.

**Comment by FlixFlix** [comment]
The last parameter is simply an optional alt tag for the returned image; it contributes nothing to its retrieval. [Source](https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-includes/pluggable.php#L2130). To avoid the reassignment situation you're describing, use the email address as the first parameter instead of the comment object. The line will then become:

`echo get_avatar( get_comment_author_email( $comment->comment_ID ), apply_filters( 'woocommerce_review_gravatar_size', '60' ), '', false );`

**Comment by SiR-DanieL** [comment]
Oh yeah sorry, you are right!
