### ISSUE TITLE
Tax Calculate Incorrectly - WooCommerce

### ISSUE THREAD

**Issue by jigneshkailam** [woothemes/woocommerce#8226]
All I am running the WordPress 4.2.2 with the WooCommerce 2.3.9, as of this writing.

![incorrect_total](https://cloud.githubusercontent.com/assets/3218310/7809143/d4032efa-03b5-11e5-831d-245aac0890fc.png)

SUBTOTAL	$75.00
----------------------------------------------------
SHIPPING        Flat Rate: $10.11
-------------------------------------------------------
TAX                $4.88
----------------------------------------------
TOTAL          $89.98

Total should be 75 + 10.11 + 4.88 = 89.99 insted of 89.98
display less .1 in total price

please review it and let me know if query.

**Comment by mikejolley** [comment]
If you're using tax inclusive prices, and totals are .5 there can be a small discrepancy due to rounding mode. To avoid this (and seeing as you're using $ which probably means US?) use tax exclusive pricing. This will avoid any rounding issues. Configure this in WC > Settings > Tax

I cannot replicate the above without knowing the specific tax settings + rates FYI
