### ISSUE TITLE
Social Security number in checkout.

### ISSUE THREAD

**Issue by Oskyldig** [woothemes/woocommerce#8258]
Hi. 
About every online-shop in Sweden needs a field for your Social security number or as we call it "Personnummer".

This is something every shop needs to add manually. Could this be an option to implement?
In Sweden the pattern for the number is "YYYYMMDD-XXXX" but the pattern doesnt need to be specific. Or maybe add a regex setting.

We would like some input on the matter. Thanks for an awesome plugin! :)

**Comment by mikejolley** [comment]
Hey @Oskyldig. Fields such as these vary from country to country, e.g. Italy has something similar for VAT. However, since these fields do not apply worldwide it's not something we want to add an option to core for.

That said, adding a field is pretty easy via the API, so it could be a good opportunity for someone (preferably Swedish who understands the requirements) to create a simple plugin on WordPress.org :)

**Comment by Oskyldig** [comment]
Hey @mikejolley . Thanks for the reply!
Yes, It's great how easy it is to add custom fields. But I wanted some official input on the matter, because 3rd parties that develop plugins are not going to add support for the fields if they're not in the WooCommerce standard. But thanks again! :)

**Comment by mikejolley** [comment]
@Oskyldig not necessarily true. We add an EU VAT field via plugins, and others, such as Invoice plugins, support this :)
