### ISSUE TITLE
Bump version number in all templates.

### ISSUE THREAD

**Issue by marcinant** [woothemes/woocommerce#8260]
Currently new version number after release is updated only in templates with changes.

In this way we got for example `archive-product.php` in version 2.0.0 while current version is 2.3.0.

When overriding it's hard to determine which templates are outdated and which are not.

I know that woocommerce generates report file. However it's pretty messy when you have different versions in template headers.

**Comment by mikejolley** [comment]
Versions are increased when breaking changes are introduced to template files. Increasing these per-version would be a nightmare for support given the volume of themes changing these files.

**Comment by pjv** [comment]
Sorry to update a closed issue, but i have a couple followup questions on this.

First, how do you determine what constitutes a "breaking change" in a template? -- I just discovered this issue when looking through my handful of overridden templates and finding that templates that I thought had not changed with WC updates (because the version number in the template stayed the same) had actually changed. Here is an example. This is a diff of  `/checkout/payment.php` between WC v. 2.3.13 and 2.4.3. In both cases the template is versioned at `2.3.0`

![2015-08-13 at 8 40 am](https://cloud.githubusercontent.com/assets/327716/9251161/6ecff624-4197-11e5-91ce-32a3c363cfed.png)

From the point of view of styling a template or working with the DOM via js, changing a `<p>` to a `<li>` could perhaps be considered a "breaking change". I could show you many other similar examples.

So second, I agree that changing the version of all the templates to match the release version of every WC upgrade would be counter-productive, but why not change the template version to match the WC release version if there are any changes in the diff of a given template? It seems to me that this would give a more valid and useful semantic meaning to the version numbers in the templates.
