### ISSUE TITLE
SSL for localhost

### ISSUE THREAD

**Issue by bigandy** [woothemes/woocommerce#8434]
I am developing a site with woocommerce locally http://site.dev but when I activated the plugin it forced https https://site.dev and kicked me out of the site admin with a white screen of death and "ERR_CONNECTION_REFUSED" in Chrome. 

Is there an option or a wp-config.php setting that I can enable to develop locally before putting the site on a server with ssl?

**Comment by mikejolley** [comment]
Are you sure its not a theme or WC plugin you're running alongside? There are no SSL redirects in WC I can see.

And is this 2.3 or master?

**Comment by bigandy** [comment]
Tried on a fresh install of WordPress 4.2.2 (en_GB) with the latest woocommerce 2.3.11 with the same plugins and theme, happens only on Chrome Canary (forces https://site.dev) whereas Chrome allows http://site.dev

**Comment by wonderyak** [comment]
I'm also experiencing this issue in latest Chrome builds. 

Fresh installation of WordPress, the only thing I've done is install and activate woocommerce:  http://literally.agency/ -- https://cloudup.com/cq7xTNu9-0m

Some assets begin loading over https: https://cloudup.com/cn-_2MAfYEv/f

**Comment by diggerau** [comment]
I'm getting this as well. 

![screenshot 2015-06-24 at 9 23 42 am](https://cloud.githubusercontent.com/assets/13018341/8319844/bd4b8e56-1a52-11e5-9284-90f51b695c80.png)

If I test on twenty15 theme with all plugins disabled except woocommerce site forces https and site is useable. Disable woocommerce and I can access backend and site works properly, except I need woo enabled.

**Comment by ryross** [comment]
I can also reproduce this. When running WP 4.2.2 and WooCommerce 2.3.11 and using Chrome version 45.0.2438.3 dev I get redirected to https even though the site doesn't have an ssl cert installed yet. The site works fine in with Chrome 43.0.2357.124

**Comment by mikejolley** [comment]
If you're all using chrome beta builds, is it not likely this is just a browser bug? I'm using stable 43.0.2357.124 without issue.

**Comment by diggerau** [comment]
I've gone back to stable, and it works no worries. I had my suspicions all along it was the browser as it happened right after the latest update. In fact, I sent google a report about it a couple of days ago.

**Comment by bigandy** [comment]
I have tested the latest master branch on Canary and it works. So must be an issue on the 2.3 branch.

**Comment by mikejolley** [comment]
@bigandy I don't think its worth debugging an issue in 1 beta browser, for something which will likely be fixed by the chrome team seeing as stable is fine..? Seems to be a few hits on google about similar issues, unrelated to wc too https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=chrome+redirect+to+ssl+localhost

**Comment by bigandy** [comment]
@mikejolley yes, fair enough. Close this issue.

**Comment by tmugford** [comment]
The Chrome SSL issue (also described in #8461) has now made its way in to the Chrome 44 stable release, though some initial testing suggests that it’s been fixed in 2.3.13, presumably via the removal of `fix_server_vars`.

https://github.com/woothemes/woocommerce/compare/2.3.11...2.3.13#diff-355207be481b8c53c1d92f0c86ab1086L376

More information on why that change fixes it is [available here](https://ma.ttias.be/chrome-44-sending-https-header-by-mistake-breaking-web-applications-everywhere/)

**Comment by tmugford** [comment]
Confirmed fix via #8479.
