### ISSUE TITLE
wc_customer_bought_product function slowing down site

### ISSUE THREAD

**Issue by jprummer** [woothemes/woocommerce#8458]
Yesterday a site I manage had a large traffic spike that was causing 504 errors all over the place. The site is hosted on WP Engine and they helped me identify the query from the wc_customer_bought_product function (includes/wc-user-funcitons.php) as the primary culprit. I disabled the calls to that function on product reviews and server load dropped 40% within minutes. Is anyone aware of this issue? Is there anyway I can help in testing and optimizing this function?

**Comment by memtoko** [comment]
I think we should store that informations in a new mysql table, like say is user_bought or something like that, we just need write that table when order completed and delete when refunded, or anything order status that make sense. So when we need that info, we just have query that table with user info, like says the column is:

- id
- user_id
- product_id
- order_id

we dont have to check the order status when we use that table, but just make sure the data correct when write, editing and delete that table.

**Comment by jprummer** [comment]
I'm not sure if this is actually more efficient, but one thought I had was to run a check to see which products the user has purchased when they first hit the site and then store that in the transient's API to check against the products as they're visited by the user on the front-end.

**Comment by douglsmith** [comment]
I was just dealing with this issue so here is what I've learned as another data point…

I'm seeing long page loads on any products that have many reviews because of this. For example, on a product with 70 reviews the visitor is presented with 40 to 50 seconds of white screen before anything appears. As soon as I turn the `Show ‘verified owner’ label for customer reviews` option off the page load drops to 1 to 2 seconds.

Using the [Query Monitor plugin](https://wordpress.org/plugins/query-monitor/), I can see that there is this slow query for each review on the page:

````
SELECT COUNT( i.order_item_id )
FROM wp_posts AS p 
INNER JOIN wp_postmeta AS pm
ON p.ID = pm.post_id 
INNER JOIN wp_woocommerce_order_items AS i
ON p.ID = i.order_id 
INNER JOIN wp_woocommerce_order_itemmeta AS im
ON i.order_item_id = im.order_item_id 
WHERE p.post_status IN ( 'wc-completed', 'wc-processing' ) 
AND pm.meta_key IN ( '_billing_email', '_customer_user' ) 
AND im.meta_key IN ( '_product_id', '_variation_id' ) 
AND im.meta_value = 99 
AND pm.meta_value IN ( 'example@example.com' )
````

It's taking .5 to .8 seconds per review so it really adds up with 70 reviews on the page.

@jprummer, I'd sort of hate to see WC add even more transients because I'm also battling my options table overfilling with WC transients as it is.

**Comment by jprummer** [comment]
@douglsmith That's exactly what was causing my problem as well. Excellent point about transients. That's an issue for me too.
