### ISSUE TITLE
Everything trying to load with SSL (HTTPS) on Chrome 44+

### ISSUE THREAD

**Issue by grantsdale** [woothemes/woocommerce#8461]
1) I'm not trying to load SSL. 
2) I'm not using HTTPS intentionally.
3) WooCommerce 2.3.11, Wordpress 4.2.2.

I have a couple of WooCommerce sites with this problem currently. One of them is herojiujitsu.com.

If you try to go to the site in Chrome 44+, you get an un-styled page because its trying to load the stylesheet through HTTPS. 

If you try to login via wp-login.php through Chrome 44+, you get an SSL cert error. 

The site works fine in any other browser I've tested including Chrome 43. The site also works fine the second WooCommerce is disabled. Disabling all other plugins makes no difference.

**Comment by panploenes** [comment]
Chrome 44 is beta and the problem with SSL is well known for 44.
Just google for it. No issue here

**Comment by grantsdale** [comment]
You can say that - but heres the thing: 

I don't have SSL on the site. At all. WooCommerce is forcing it on somewhere. If I disable Woo, it loads fine.

**Comment by panploenes** [comment]
Similar issues from other CMS that only occur when using the Chrome 44 beta lead me to say its not a specific woocommerce/wordpress issue.

It is completly irrelevant if you have SSL activated or not. My guess is some browser metric is causing chome beta to try to load css/js from https source.
Still since its a BETA browser release nothing concerning in my opinion. Just wait and see...

**Comment by claudiosmweb** [comment]
@panploenes thanks :)
