### ISSUE TITLE
Checkout page: Information dont get updated when you select a state from the dropdown

### ISSUE THREAD

**Issue by panbill** [woothemes/woocommerce#8469]
Checkout page: Information dont get updated when you select a state from the dropdown
Here is how you can reproduce that issue.
1) Go to the checkout page (http://demo2.woothemes.com/storefront/checkout/)
2) Choose USA as country (The issue happens when a country has a dropdown list in states, and not text input.)
3)Leaving everything else blank try to choose a state. You will notice that the information on the right side dont get updated like for example when you enter your address.

*This also can be a very serious issue for those that use the plugin that calculates the shipping cost according to the state

**Comment by mikejolley** [comment]
@panbill The checkout will update ONLY after all shipping fields are filled out. Country, State, Zip etc

**Comment by panbill** [comment]
I knew that already. 
But this should not happening. If you choose a country without dropdown states like UK it does update even if you leave everything else blank!!

**Comment by mikejolley** [comment]
@panbill you've just reported the same thing which is unnecessary.

**The totals area will only update on-change of a state once those fields are all populated in version 2.3.11**. This is to put less load on the server. Once the user puts in those details, your area will recalculate, **as will the shipping in your case**. So while I can see the issue you speak of, its not really an issue because the entire set of address data is required prior to form submission.

To see this, go to checkout and fill out the entire form, then switch state. Checkout totals will update.

In 2.4, this logic has further been changed to do the same for the country, state, zip fields. So if you change 1 of those fields whilst leaving the others blank, no update will take place.

2.4 will be out within around a month.

Do not open duplicate tickets (#8481) please. We can see replies.
