### ISSUE TITLE
Woo kills $_POST

### ISSUE THREAD

**Issue by efes-s** [woothemes/woocommerce#8524]
I try to use custom parameters for my needs in Product.

But...
Please, add to Cart Test product here:
http://test17.tested-ok.ru/?product=test-product
and view Cart
http://test17.tested-ok.ru/?page_id=8

Here you can see standart Cart page and $_POST variable.
Do you see $_POST['cart']['blablabla']['qty'] ?
It's OK. These are Quantity field name and value. When I use my fields we could see its name and value in $_POST too.

But now...

If we change Test product Quantity and update Cart, we couldn't see nor Quantity nor any fields in $_POST.

You see that any time when we change quantity and update cart.

This is V4.2 Wordpress and V2.3.11 Woocommerce

**Comment by mikejolley** [comment]
It does not 'kill $_POST' - there is a redirect back to the referring page after the cart is updated. So when you're back at the page, the POST data is no longer there. This is to stop people refreshing and resubmitting the form. https://github.com/woothemes/woocommerce/blob/5d4ea2433d8b1c2c12e95e10ea5fafb5eda84999/includes/class-wc-form-handler.php#L460

**Comment by northstjarna** [comment]
Hi There,

I had a similar issue to this...
I have written something to set a global booking session in functions.php but it doesn't even get there because sometimes it re-directs.

I think you have to somehow hook in your function before the cart handler function fires... before init.
ie on plugins_loaded...

Here is mine which does not always work...



add_action('init','db_update_booking_session');

function db_update_booking_session() {
	
	if(!isset($_POST) || !isset($_POST['db_bookings_start_date_day']) ) {
		return false;	
	}
	
	/// date now
	$date_now = new DateTime();
	$date_now_int = (int) $date_now->getTimestamp();
	/// Yes you need these as seperate objects...
	$start_date = DateTime::createFromFormat('d/m/Y', $_POST['db_bookings_start_date_day']);
	$date_to_alter = DateTime::createFromFormat('d/m/Y', $_POST['db_bookings_start_date_day']);
	
	$start_date_int = (int) $start_date->getTimestamp();
	$duration = ((isset($_POST['db_bookings_field_duration']) ) ? $_POST['db_bookings_field_duration'] : 1);
	$end_date = db_calculate_end_date($date_to_alter,$duration);
	
	$end_date_int = (int) $end_date->getTimestamp();
	
	
	if($start_date_int <= $date_now_int) {
		$_SESSION['db_bookings_data_to_append']['db_error'] = 'You Must Select a date in the future';
	}
	
	$_SESSION['db_bookings_data_to_append'] = array(
		'start_date_str' => $start_date->format('YmdHis'),
		'start_date' => $start_date->format('d/m/Y'),
		'duration' => $duration,
		'end_date' => $end_date->format('d/m/Y'),
		'end_date_str' => $end_date->format('YmdHis'),
		'db_error' => false
	);
	
}

function db_calculate_end_date($date_to_alter, $duration) {
	/// convert to strings and add time on
	$end_date = $date_to_alter->modify('+' . $duration . ' day');
	return $end_date;	
	
}

Also the bespoke filter hook for the cart handler is inside some checks which can be ignored:
// Update Cart - checks apply_coupon too because they are in the same form
		if ( ( ! empty( $_POST['apply_coupon'] ) || ! empty( $_POST['update_cart'] ) || ! empty( $_POST['proceed'] ) ) && isset( $_POST['_wpnonce'] ) && wp_verify_nonce( $_POST['_wpnonce'], 'woocommerce-cart' ) ) { ....


// Trigger action - let 3rd parties update the cart if they need to and update the $cart_updated variable
			$cart_updated = apply_filters( 'woocommerce_update_cart_action_cart_updated', $cart_updated );

}

**Comment by northstjarna** [comment]
In-fact I put this in functions.php without wrappers...
var_dump($_POST);

and get array(0) { }

so that re-direct is not good for us on update cart button when reviewing the order just before checkout.

**Comment by northstjarna** [comment]
To confirm again...
There is an issue.

In the file woocommerce/includes/class-wc-form-hanndler.php line 364... 
I put this in as a test... and this is wayt before lines 455 wp_safe_redirect( WC()->cart->get_checkout_url() ); and line 460 wp_safe_redirect( $referer ); of this function

/**
	 * Remove from cart/update.
	 */
	public static function update_cart_action() {
		var_dump($_POST);die('where is the post???');



I got a blank screen with this


array(0) { } where is the post???

**Comment by mikejolley** [comment]
@northstjarna do you see woo setting $_POST anyway? Nope because it doesn't :) I'm certain it's the redirects.

**Comment by northstjarna** [comment]
OK so is it supposed redirects prior to calling your function in your plugin the one in form handler...

public static function update_cart_action() 

This is called after pressing update cart button.
If you look at that function it is also supposed to check for other posts such as if you have selected coupon etc.

Line 369 check will be ignored in such cases

// Add Discount
		if ( ! empty( $_POST['apply_coupon'] ) && ! empty( $_POST['coupon_code'] ) ) {
			WC()->cart->add_discount( sanitize_text_field( $_POST['coupon_code'] ) );
		}

the ! empty( $_POST['apply_coupon'] )  means it is looking for something but if there is never a post at all... then there is nothing to check

Doing a var_dump on $_REQUEST will of course output nothing so how is this funciton supposed to check anything?

Thanks

Andi

**Comment by northstjarna** [comment]
In other-words its redirecting prior to this method being called. Therefor there are no POST variables available within this function when it is called.

**Comment by mikejolley** [comment]
If there were never POST at all, you wouldn't be able to apply coupons to your cart. That functionality works, so that cannot be true.

**Comment by northstjarna** [comment]
Hi there, ok well maybe you want to do a var_dump on $_POST and test that out in that functions, as doing a dump at the top that function output NULL for me.

I created a work-around to hook this into a custom function outside this, actually on the calulate_totals was better because I wanted to apply a booking date cart-wide not product wide, and I did this by creating some some sessions to call something like checkout type.

I do have another issue with programically adding a variable item to a cart it doubles the cart count.
this I believe happens when I add additional data to the variation.

I believe I am not doing this correctly.

$cart_item_data = array(
							'product_id' => 123,
							'variation_id' => 456,
							'variation' => array(
								'file' => 'not a variation in the DB, but needed'
								'print_type' => 'variation-with-price-attached'
								'color_spec' => 'variation-option2',
								'proof_size' => 'varation-option3',
								
							),
							'quantity' => 1,
							'data'=> array(
								'id' => 123,
								'price' => 33.33,
								'product_type' => 'product',
								'manage_stock' => 'no',
								'stock_status' => 'instock'
								),
							'line_total'=> 33.33,
							'line_subtotal' => 33.33,
						
						);
Now when I run this:
WC()->cart->add_to_cart(123, 1, 456, $cart_item_data['variation'], $cart_item_data['data']);

it gives me cart count of 2 (not one) near the shopping cart icon. An output of cart shows qty 1??
this is the only thing left that I have to solve. Maybe I am not creating the variation correctly.

**Comment by northstjarna** [comment]
Ok Figured this out...
If you are goign to handle adding items to WC via a form (say for services) - set it up as a vaiable product and set your form to react on template_redirect hook and not wp_loaded or the calculate_totals funciton and hooks will run twice...

Now the cart count is how it should be for our bespoke ordering service and alternative rentals.

Thanks for your help Mike. If this information is of any use to anyone else make sure you are creating orders on add_action('template_redirect', array($this, 'db_file_upload_create_order'), 20);

Then you can check for a POST or a GET etc.
