### ISSUE TITLE
Remove `a` tag from the markup of `templates/content-product.php`

### ISSUE THREAD

**Issue by juanfraa** [woothemes/woocommerce#8575]
Hey there WooMatticians!

I'm just wondering what's the point of having the `<a>` tag directly in the content of `templates/content-product.php`, because once a developer start playing around with the different actions in order to customize the products grid, then the tag remains there wrapping everything else. 

And, if there's another `<a>` tag inside (let's imagine moving the add_to_cart button to another position), then it end up generating invalid HTML.

For instance, the following example will alter the contents inside each item in the loop, and at the same time it'll end up generating invalid HTML:

```php
remove_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_show_product_loop_sale_flash', 10 );
remove_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 10 );
remove_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_loop_add_to_cart', 10 );

add_action( 'woocommerce_before_shop_loop_item_title', 'i_prefer_a_different_markup' );

function i_prefer_a_different_markup() {

	?>
	<div class="i-like-to-modify-stuff" >
		<?php
			do_action( 'my_own_grid_element' );
		?>
	</div>
	<?php

}

add_action( 'my_own_grid_element', 'woocommerce_show_product_loop_sale_flash', 10 );
add_action( 'my_own_grid_element', 'woocommerce_template_loop_product_thumbnail', 10 );
add_action( 'my_own_grid_element', 'woocommerce_template_loop_add_to_cart', 10 );
```

Wouldn't be better to include the opening and closing tags in two other actions hooked over `woocommerce_before_shop_loop_item` and `woocommerce_after_shop_loop_item` by default?

That way, developers could get rid of these without having to stay in the loop of updates regarding default templates.

It's just a suggestion.

The same with having `the_title()` over there. I can't see the point of having hooks if the developer can partially change stuff.

Thanks for your time,
Juan.

**Comment by jameskoster** [comment]
Yeah this is one of those things we've considered a few times now but never got around to actually changing. Reason being that this could break any third party theme which over-rides that template (many, many do).

I would like to address this though, it's been like this since 1.0!

We can create a new hook for the title, that's fine. For the anchor, there's two options I can think of;

* hook the opening/closing tags into `woocommerce_before_shop_loop_item_title` and `woocommerce_after_shop_loop_item_title` respectively like you say. This is neatest. But because those hooks should also exist in template over-rides we'll get a nesting effect on the same anchor. Not sure what kind of problems that would cause (it's invalid html which I can live with until folks update their themes, but if it breaks the actual link it's a no-no). Extensions use these hooks too, so we'd need to be cautious with the priorities we set.
* Create two new hooks. This would be the most backwards compatible/safest, but feels dirty. We have to be mindful that once a hook has been added, we cannot remove it.

I'd probably lean towards the second option. It's dirty, but we're already using 4 hooks where 1 would suffice, another 3 probably wouldn't hurt so much in that respect.

**Comment by juanfraa** [comment]
Hey James,

Thanks for writing back. Great job you've done guys!

With regards to the patch, actually the third party themes which override the template will continue working the same way, as they are overriding the template. I mean, my suggestion was to keep those elements, but just having the option to take them away without being in the need of touching the template, by removing the action.

If you want, once you decide the names for the hooks, I can take an eye at it.

Cheers,
Juan.

**Comment by jameskoster** [comment]
> With regards to the patch, actually the third party themes which override the template will continue working the same way, as they are overriding the template.

That's not true if we hook the anchor into `woocommerce_before_shop_loop_item_title` and `woocommerce_after_shop_loop_item_title`. The template overrides would still have the inline anchors, but as they also have the actions the anchors will be hooked in _as well_. So you'd get the same anchor nested within itself. I think new hooks is the way to go.

**Comment by juanfraa** [comment]
Yeah, I meant that. Agree.

**Comment by kevinmamaqi** [comment]
Hello, I'm comming from this WP topic: https://wordpress.org/support/topic/make-product-thumbnails-link-to-the-product

I'm trying to get the following structure:
*Product Thumbnail -> Link to product
*Product Category -> Just name
*Product Title -> Link to product

I've rewrote the content_product.php template to: `<a href="<?php the_permalink(); ?>"> <h3 class="producto-titulo"><?php the_title(); ?></h3></a>` and hooked the category name before the title, but I can't figure out how to link the image to the product.

I think that If I follow your advise, you're suggesting that the best solution would be to remove the post thumbnail from the `woocommerce_before_shop_loop_item_title` create a new hook, and then wrap the new one with the link. Am I right?

**Comment by juanfraa** [comment]
Hey Kevin,

Unfortunately this place is open just to discuss the issue, and not a support forum. 

I'd recommend you to post a new support thread on the forums at https://wordpress.org/support/plugin/woocommerce or over at the WooThemes website https://support.woothemes.com/hc/en-us

Cheers.

**Comment by mikejolley** [comment]
@juanfraa @kevinmamaqi correct. I just referred to this topic because it was related to what you're trying to do.

**Comment by jameskoster** [comment]
So nested anchors aren't a huge issue. Tested in IE6 and they work even there, so we can just add the new functions to the existing hooks.

**Comment by scottmcdhome** [comment]
These nested <a tags appear to be an issue on HTML syntax validators. Please advise.
