### ISSUE TITLE
Сart always says empty

### ISSUE THREAD

**Issue by WallDenn** [woothemes/woocommerce#8668]
Hi, I got the problem that when I click add-to-cart as guest customer, the cart always says empty
but it's all fine with when I'm login as admin. I have not connected the plugin cache. How can I fix it ?

**Comment by mikejolley** [comment]
Please don't post support requests on github; this is not a [bug report](https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md).

Your problem is caching related. It may not be a caching plugin, but caching on the server. Cart/checkout and POST requests needs to be excluded from cache or guests won't be able to checkout.
