### ISSUE TITLE
Bug in stock check in get_children() in WC_Product_Variable [2.4]

### ISSUE THREAD

**Issue by davey-w** [woothemes/woocommerce#8687]
I have updated a shop (WC 2.3) to WooCommerce 2.4 Beta 4 and noticed the get_variation_price('min') method in WC_Product_Variable returned 0 instead of the minumum price for a variable product.

Apparently in the WC_Product_Variable class, the get_children() method doesn't check the _manage_stock post meta anymore (when $visible is true), so only children with post meta '_stock_status = instock' are returned. If you never had stock management enabled for this variable product, no children are returned.

So this is either a bug, or the data updater didn't set the _stock_status for those products.

**Comment by mikejolley** [comment]
@davey-w _stock_status  should be used since its much faster to query. _stock_status should however be in sync, and manage_stock should be set.

WC Core keeps _stock_status in sync whenever stock levels change. However, people importing data for example may break this. We added these functions to 2.4 to stop this happening in future. https://github.com/woothemes/woocommerce/commit/794af1c0133fcddbc266991bb61c0665e682f244

Manage stock for variations was changed and upgraded via a routine in 2.2 here https://github.com/woothemes/woocommerce/blob/master/includes/updates/woocommerce-update-2.2.php#L127

Did you perhaps import these variations/products using an import plugin?

**Comment by davey-w** [comment]
No, i didn't import the variations/products using a plugin (at least not after I updated to WC 2.4 Beta).

I did a quick check in the postmeta table in the database:

My variable product has ID 236. A random variation (child) of this product has ID 261.

#236:
_manage_stock: no
_stock_status: instock

#261:
_manage_stock: no

For ID 261 (child) the _stock_status is missing in the postmeta table, therefore the child can't be found. Any idea why this is missing for this variation?

**Comment by mikejolley** [comment]
Sorry which field is missing?

**Comment by davey-w** [comment]
The '_stock_status' post meta key for the variations (childs).

**Comment by mikejolley** [comment]
I assume it comes back after saving then?

**Comment by davey-w** [comment]
Only when you check the 'Manage stock' checkbox on variation level.

**Comment by mikejolley** [comment]
For me its there always https://dl.dropboxusercontent.com/s/okf64l2f7v3bdz3/2015-07-30%20at%2015.13.png?dl=0

**Comment by davey-w** [comment]
Now set that option to 'Out of stock', save it and disable stock management in WC settings:

![screen](https://cloud.githubusercontent.com/assets/6419634/8985254/9619b3da-36d6-11e5-827a-21796ccbdc61.png)

The _stock_status for this variation stays 'outofstock'.

Now add a new variable product with variations (with stock management still disabled). These new variations don't have a '_stock_status' post meta field at all.
