### ISSUE TITLE
Edit Product: Variations - Sorted in Reverse Order?

### ISSUE THREAD

**Issue by rtddev** [woothemes/woocommerce#8690]
Doing some testing on 2.4.0-beta-4.

Noticed in the Variation Editor our variations are now in reverse order, and you can't seem to re-order them.

![image](https://cloud.githubusercontent.com/assets/1872898/8994141/6ad99810-36be-11e5-8165-849b5ad3161b.png)

When we created them, we started with S, M, L, XL, 2XL. Now they are in opposite order which makes editing them un-intuitive.

Any thoughts?

**Comment by mikejolley** [comment]
If you add a new variation, it kinda needs to be on page 1... @claudiosmweb  ?

**Comment by rtddev** [comment]
@mikejolley @claudiosmweb Actually, that's not true in all cases. Managing variations is ideally based on how a store owner logically thinks about them, and not necessarily how or in what order they were entered.

**Comment by claudiosmweb** [comment]
The ordering will be for ID, especially now that have pagination.
In future versions we plan to create some filters so we can put something to sort, but for now this wroks great.

But I'll add a new filter, so you can change it.

**Comment by claudiosmweb** [comment]
Now you can change it:

```php
function my_custom_wc_get_variations_args( $args ) {
    $args['order'] = 'ASC';

    return $args;
}

add_filter( 'woocommerce_ajax_admin_get_variations_args', 'my_custom_wc_get_variations_args' );
```

**Comment by mikejolley** [comment]
@rtddev if you inserted a new one in any other place it would be confusing.

**Comment by rtddev** [comment]
@mikejolley I'm a shop owner and generally have a good idea what would be confusing for us. 

In my scenario if I started a product with sizes S, M, L, XL, then wanted to add XS or 2XL at some point later on, if they weren't in progressive order XS, S, M, L, XL, 2XL -- that would be confusing. 

For sizing, having the order you want is very important because otherwise you could mess up when editing items and stock very easily.

I'm sure there are other variation cases where this wouldn't be as much of an issue, but for clothing and progressive sizes, order them from smallest size to largest is generally how we manage everything.

**Comment by bekarice** [comment]
@rtddev I don't doubt that a clothing store would need this displayed in that particular order, but there are millions of WooCommerce stores, each using variations in a different way, that this would not be an ideal change for. 

When a user creates something, that "something" should be visible so they can take the next steps with it (e.g., adding prices). If you were new to WooCommerce, and the item you just added didn't actually appear to be added (because it's on a different page), you'd be extremely confused. You may even keep creating variations, wondering why they won't show up. This is why new variations need to stay on the first page when added.

If you'd like to change the default order for your use case, the snippet that Claudio provided can do that, or you can drag and drop your variations into the order you choose easily. You'll also be able to determine how many variations per page you want shown (if different from 10) by [using this snippet](https://gist.github.com/claudiosmweb/bc1190cdc0ac535931a3#file-functions-php).

**Comment by rtddev** [comment]
@bekarice thanks for that info. 

couple quick things:

1. i wasn't trying to infer how WC was supposed to behave, but rather providing an opinion of our preferred behavior based on our usage

2. i actually tried reordering them manually using drag & drop before I submitted this issue, but that did not work -- is that supposed to work natively without Claudio's snippet of code or yours? Or do I need to add Claudio's snippet to enable that?

Oh, and I 100% agree with you that after creation a shop owner should see what they just created.

I think if manual reordering actually works, that would be perfectly fine for us.

**Comment by bekarice** [comment]
> i actually tried reordering them manually using drag & drop before I submitted this issue, but that did not work

I see what you're saying, I was originally in my WC2.3 test shop for this (which allows drag and drop), looks like I can't do so in WC 2.4 either. @mikejolley @claudiosmweb still seeing the "drag / drop" icon on variations but not able to move them as in WC 2.3. Intentional or issue?

**Comment by claudiosmweb** [comment]
@bekarice Yes intentional and we removed the cursor too xD
Now with the pagination does not make much sense to drag n drop. People will get used to it and new users will not have missed too.

**Comment by rtddev** [comment]
@claudiosmweb so without drag & drop, will there be no way for us to order the variations the way we logically work? 

Why not just offer a view (outside of pagination) where people can do drag and drop? Maybe at a certain number of variations it doesn't make sense, but I think the store owner could determine that out if there was a configuration to allow it.

Looking at variations in non-progressive order will get tiresome very quickly for anyone who has a shop utilizing sizes (shirt, pants, dresses, blouses, hats, socks, etc.)

For us right now, we could use the code snippet you provided to put stuff in asc order, but that will immediately become obsolete when we add additional sizes.

Also, I don't think it's a good position to take to say that store owners will just have to "get used to it". That seems very customer non-centric.

**Comment by claudiosmweb** [comment]
@rtddev yes have, just set the order using the `woocommerce_ajax_admin_get_variations_args` filter.

> Why not just offer a view (outside of pagination) where people can do drag and drop? Maybe at a certain number of variations it doesn't make sense, but I think the store owner could determine that out if there was a configuration to allow it.

Feel free to create a plugin for it, because now with this new filter is possible.

**Comment by claudiosmweb** [comment]
And as I said, new versions will have filters and a search box for it too.
https://github.com/woothemes/woocommerce/issues/8537
https://github.com/woothemes/woocommerce/issues/7926

**Comment by rtddev** [comment]
@claudiosmweb got it. Thx.

May create a plugin for this too.

**Comment by maxrice** [comment]
IMO this is going to cause an issue for a lot of merchants who'll want to be able to control the order of the variations that are displayed on the frontend. It doesn't seem all too reasonable to ask them to install a plugin to do so, since previous versions of WC have done this out of the box.

**Comment by mikejolley** [comment]
Max, variations have never been ordered on the frontend. It's the attributes which are displayed/ordered.

**Comment by BFTrick** [comment]
A couple of things bug me about this. The position of the draggable icon on the right. Normally those are on the left and I think we should keep ours there. Somewhere near the ID would be good.

<img width="638" alt="screen_shot_2015-07-31_at_9_36_27_am" src="https://cloud.githubusercontent.com/assets/1065372/9011016/d867a742-3767-11e5-93ee-b9d7b749c540.png">

The functionality to click the draggable icon to set the position is totally hidden. There's no indication that you can click that icon and something will happen. I only clicked it because I saw there was code that did something. I don't think we should have functionality that's this hidden. I'd prefer we took this out - get some feedback from users and tweak the functionality in a point release or include it in the next feature release.

<img width="692" alt="edit_product_ _woocommerce_ _wordpress" src="https://cloud.githubusercontent.com/assets/1065372/9011068/321ab4f0-3768-11e5-80e1-8b42414d8097.png">

The only thing that didn't really work was moving a variation between different pages. That's probably why the feature above exists but it's really hard to use. I would love if there was a way to drag up and go to a previous page of variations. Or drag down and go to the next page of variations. I'm sure that would be complex to do though...

Any chance we could do something like that and push it out in a point release?

**Comment by rtddev** [comment]
@BFTrick what version are you running on? I'm using the beta tester plugin & running 2.4.0-beta-4, but I don't see that control that you pointed to.

**Comment by BFTrick** [comment]
I'm running the bleeding edge of WooCommerce. That included the last changed @mikejolley added. FYI he just put out the first release candidate. You can download that and it has those changes: https://github.com/woothemes/woocommerce/releases/tag/2.4.0-RC1

**Comment by rtddev** [comment]
Thanks for the clarification @BFTrick. 

Will the beta tester plugin detect the release candidates too? That tool makes it really easy to update to the latest non-production releases, but my system isn't prompting me to download anything new.

**Comment by neotropic2023** [comment]
2+ years later.... If I add a bunch of products in Alphabetical order in Attributes. They should be added in that very same order in Variations. Not backwards. I should not have to try and order products that span over two pages (which is impossible if 'A' is on page 2, but needed on page 1) or spend 20+ min click each one to enter an order number. What kind of backwards logic is this?
