### ISSUE TITLE
Create product with categories Ids: inconsistent behavior with documentation

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/woocommerce#8734]
I am using the NodeJS SDK to create products against WooCommerce. As per the documentation (http://woothemes.github.io/woocommerce-rest-api-docs/?javascript#products-properties), when you are in write-mode, you should pass the categories ids to the post method.

*categories	array	List of product categories names (string). In write-mode need to pass a array of categories IDs (integer) (uses wp_set_object_terms())*

When I do this, WooCommerce creates brand-new categories, whose names are the string equivalents of the category ids I passed to the method.

The end result I want to achieve is to create a new product and assign existing categories to it. I managed to do this by passing the categories names (instead of their ids). So it seems to me the documentation is inconsistent with the actual behavior of the system.

**Comment by claudiosmweb** [comment]
See the `wp_set_object_terms()` docs:
http://codex.wordpress.org/Function_Reference/wp_set_object_terms#Parameters

By default it is impossible to happen what you're saying.
If you are sending the IDs, you can't create new categories based on old categories.

Review your steps and test everything you are doing.
Because there is no problem here.
