### ISSUE TITLE
2.4.1 Products availability major bug

### ISSUE THREAD

**Issue by blaircomm** [woothemes/woocommerce#8784]
After WooCommerce updated to version 2.4.1, our ecommerce site in development has a sudden problem with the store. All variable products are showing up as not available with this error message: “Sorry, this product is unavailable. Please choose a different combination,” and not showing the designated image for the color variation. This has effectively broken the store completely.

Everything was working perfectly without any changes on my part at all.

I have gone over all WooCommerce product and attribute setups and settings—for hours, and all are set up correctly. I have tried everything, but nothing changes the issue. There are several other reports of this issue on the Enfold forum.

I have now set up a mirrored commerce site on a new subdirectory migrating from backup files. It is running WooCommerce Version 2.3.13 and again works perfectly. It will remain Version 2.3.13 as that is the last version of WooCommerce that works for us so far.

We are too far into development to go for another platform and this is a major issue that is bringing down our's and other's online stores.

**Comment by mikejolley** [comment]
> There are several other reports of this issue on the Enfold forum.

It is likely that Enfold is bundling an outdated add-to-cart template for variable products. Switching themes can confirm this..

**Comment by blaircomm** [comment]
Enfold does not bundle WooCommerce. It is compatible. WooCommerce is installed as its own plugin.

Upgraded to Version 2.4.2. This did not fix the issue, it did nothing. All products still shown as unavailable. 

This software no longer works for us for ecommerce. There are many others with this same issue. This update did not address the issue at all for us and the store is still broken.

**Comment by claudiosmweb** [comment]
>Switching themes can confirm this..

**Comment by ryanmorse** [comment]
We're having the same problem. We have some attributes that are used for selections but don't actually change the pricing at all. In order to have less variations to fill out, I mark the attributes that do affect pricing as "used for variations" on the attributes tab. After I "create variations for all attributes" I go back and mark the rest of the attributes that I want to show up as options as "used for variations" and they show up in the variations area, with "Any xxxxx" defaulted to. This worked fine previously on 2.3.13 but seems to be causing the "Sorry, no products matched your selection. Please choose a different combination." problem on 2.4.x (I've updated to 2.4.2 and still have the problem.) Unmarking the "used for variations" box on attributes that I didn't specifically create variations for solves the problem and the price then shows up on the front end again.

Thanks for looking into this! I've added the system report below in case you need it.



### WordPress Environment ###

Home URL: http://comp.local:5757
Site URL: http://comp.local:5757
WC Version: 2.4.2
Log Directory Writable: ✔ /xxxx
WP Version: 4.2.4
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_fastcgi/2.4.6 mod_wsgi/3.4 Python/2.7.8 PHP/5.6.2 mod_ssl/2.2.29 OpenSSL/0.9.8zf DAV/2 mod_perl/2.0.8 Perl/v5.20.0
PHP Version: 5.6.2
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.2
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (7) ###

Preserved HTML Editor Markup: by Marcus E. Pope
marcuspope – 1.5

Rich Tax Description Editor: by Davit Barbakadze – 1.2.4
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.4.2
WooCommerce UPS Shipping: by WooThemes – 3.1.1
WooCommerce TM Extra Product Options: by themecomplete – 3.0.9
WooCommerce: by WooThemes – 2.4.2
WooThemes Helper: by WooThemes – 1.5.9

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: 
Version: 
Author URL: 
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: Not Declared

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
@Blaircomm I said bundling TEMPLATES not WooCommerce itself.

**Comment by blaircomm** [comment]
OK. Got it. I searched the root directories and could not find that Enfold has included "yourtheme/woocommerce/single-product/add-to-cart/variable.php", but I have sent this information to Enfold support to see what they say. I am going to continue development on version 2.3.13. I have a separate mirror site to test upgrades, (so far no luck with 2.4.2,) and will make a 3rd mirrored site to test WooCommerce with other themes to see if it is Enfold. However, the update did break the store and 2.3.13 works perfectly. I hope it will all work out.

**Comment by mikejolley** [comment]
I don't have a copy of Enfold to verify unfortunately.

**Comment by blaircomm** [comment]
I have done extensive testing and have narrowed down the issue to a plugin. Magic Zoom Plus, which interfere somehow with the variable product on the single product page—consequently WooCommerce marks it as unavailable and displays the error message. The product variations can be navigates and the selected image for each color comes up properly within a "Quick View" plus can be ordered and added to the cart in this way. So, the basic functions of WooCommerce seem to be working and the Magic Zoom Plus plugin is incompatible

I have the issue into the plugin author to see if he will issue an update to handle the incompatibility, if not I will go to another solution and test it again.

I wanted to give you the data for resolution—the themes I have tried are all compatible and all react in the same way to this plugin.

Thank you.

**Comment by mikejolley** [comment]
This is the one I saw earlier. It is doing some funky stuff to variation data on the page and will need to update itself.

**Comment by blaircomm** [comment]
This issue has been fixed with the latest version of Magic Zoom Plus plugin v5.12.34. All current versions working now.
