### ISSUE TITLE
Some Variations working others are not

### ISSUE THREAD

**Issue by serveds** [woothemes/woocommerce#8801]
Hi,

Since the update I have some variations working and others not.  

I am getting either: "Sorry, no products matched your selection. Please choose a different combination"

or I am getting no options to choose in a drop down.

the issue seems to be happening with products that where put up back March 8, 2013 or older.

All variations from then on seem to be working fine.  I have added new products with variations today with no issues.

Justin

**Comment by greguly** [comment]
Hi, 

Did you run the data updater routine?

Cheers,
Gabriel

**Comment by serveds** [comment]
Hi Gabriel,

I did.   

Running 2.4.3 WC Database Version

Justin

**Comment by SaraAinscow** [comment]
I'm having this same issue. Have tried running the updater with no luck in it fixing the problem and have also tried disabling some other plugins thinking that there may be a conflict, but nothing is working to fix it.

Does anyone have a solution yet? Otherwise I'm going to have to go back to the old version of Woocommerce in the meantime. :-(

**Comment by mikejolley** [comment]
It's likely this https://github.com/woothemes/woocommerce/commit/a52619c34455c3a478e03c8ad157d215e3749361

Will be pushing these updates out later today. Thanks

**Comment by mikejolley** [comment]
Related, there was also a case with attributes containing quotes.

**Comment by SaraAinscow** [comment]
Hi Mike

 

Thanks for the prompt response :)

 

Coding and me are NOT friends lol. If I’m understanding correctly, you have found the problem, fixed it and are going to be updating the plugins shortly to send this “fix” through to the likes of little old me. Is this correct?

 

Kind Regards

 

Sara Ainscow

MUGGLES

 

Tel:                  021 559-1749

Cell:                 084 493-0588

Email:             info@muggles.co.za <mailto:info@muggles.co.za> 

Website:       www.muggles.co.za <http://www.muggles.co.za/> 

Facebook:    http://www.facebook.com/mugglesandmore

 



 

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL - THANK YOU.

**Comment by ChromeOrange** [comment]
@SaraAinscow WooCommerce 2.4.4 will be released later today, it will contain the updates you need

**Comment by SaraAinscow** [comment]
You guys are super stars! Thank you sooooooo much :-D

 

Kind Regards

 

Sara Ainscow

MUGGLES

 

Tel:                  021 559-1749

Cell:                 084 493-0588

Email:             info@muggles.co.za <mailto:info@muggles.co.za> 

Website:       www.muggles.co.za <http://www.muggles.co.za/> 

Facebook:    http://www.facebook.com/mugglesandmore

 



 

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL - THANK YOU.

**Comment by serveds** [comment]
Hi,

Update 2.4.4 fixed one of the issue we are having where there was no options in the drop down.

The other issue with : "Sorry, no products matched your selection. Please choose a different combination." 

Is still occurring and like I mentioned before it is only happening with older products - March 8, 2013 or older.  I have tried duplicating a product to see if that would work but still the same issue.

Anything else that this could be?

Thanks,
Justin

**Comment by mikejolley** [comment]
The last thing to check is that the actual variations are assigned to the attributes correctly, each has a price, and each is in stock. 

Also save the product to clear caches. Children are stored in a transient...

**Comment by SaraAinscow** [comment]
Ok, I think I might have the answer here. I'm also still having the same problem that serveds is having, but when I went on I noticed that I hadn't set a default product for the variations. Once I did this, everything worked fine. Great that it stops the error message but I didn't actually want to set a default product as I wanted my clients to have to choose a specific mug for the design they want. Is there going to be another fix coming out to rectify this or am I going to have to go and set default products for all my stock items?

**Comment by greguly** [comment]
Hi serveds,

How many variations do you have on the old products? 

Maybe this could help: https://gist.github.com/claudiosmweb/6f91ad228c2176b986b2 

Change 10 to your max number of variations.

Cheers,
Gabriel

**Comment by serveds** [comment]
Hi,

What Sara said if I select a default variation I get it work.

All the attributes are connected with SKU, Weights, price and in stock.  The variations are set to enabled.

I have already tried re-saving (first thing I tried)

between 15 - 30 variations per product

I only have 10 max variations set in the admin

Justin

**Comment by greguly** [comment]
Hmm, ok. 

So seems to exist an issue with variations without a default value....

**Comment by serveds** [comment]
It is a little weird and only for those older products.  These variations where working prior to the update.

**Comment by SaraAinscow** [comment]
Glad it solves your problem as well serveds.

Can the necessary people please let us know asap if there will be an update that will fix this?

Thanks so much :-)

**Comment by serveds** [comment]
Hi Sara,

Do you have any special characters (slashes, quotation marks, etc) in your attributes?  If so this might be the reason.  Way back ...I think version 2.0 (I can't remember exactly), but I think it was a sanitize  issue where I ran into something similar.  I went back to these old ones removed the html for quotation = &quot; and now it works properly.

Justin

**Comment by SaraAinscow** [comment]
Hey Justin, sorry for the late reply, I only just saw your response. my attributes do have a hyphen in them and in some cases slashes, e.g.:

AA02 - Standard White Mug | AC07 - Travel Mug S/Steel | AG10 - Handle, Inside Colour Mug - Red

You can see the full list on:  www.muggles.co.za (just go to any of the products and click on the drop-down - Of course it doesn't work at the moment because I haven't set the default products yet because I'm still waiting for an answer as to whether the powers that be are going to fix this with an update, but the list is there nonetheless).

I have approximately 33 variations per design and there are approximately 150+ designs which I'm adding to all the time. Also the variations are going to increase soon as I have a new mug range that we will be adding to our products. To give you an idea of the size of what I'm working with, I recently realised that I didn't have the SKU's listed per product and I had to go and insert them. Approx 5200 SKU's later.... I don't think I need to finish that sentence lol and as I said I'm adding all the time.

What annoys me is that in the old version of Woocommerce I did not have a problem with any of this at all. Everything worked fine. I can appreciate that times change and things need to be updated, but then don't mess up what is working in the process.

I now have another problem because by choosing a default product, instead of it coming up with the design picture, it comes up with the variation picture (which should only be appearing once a variation is selected). This is because I have variation images set on all products. This means that I'm now either going to have to have clients bouncing between products and designs to see what the products look like or I will have to try and educate them somehow to change the dropdown for variations to "Choose Option" in order to see the design - Not cool :-(

For an example of this see:  http://www.muggles.co.za/shop/design-categories/animal/ani001/ and change the dropdown for variations to "Choose Option"

In my opinion (not that I would have any clue how to do this from a coding standpoint), what needs to happen is that whoever designs Woocommerce needs to look at the default form value section for variation products as something is not working properly there, which is why it won't allow you to leave it unselected so that clients can choose for themselves.

I've tried loading a new product (with the exact variations options I listed above) and then, as you stated previously, everything works, but I really don't have the time or inclination to go and reload the number of products and variations that I have on this site. If it was something that I did wrong then fair enough I would have to take the time and redo everything, but this is not something that I have done wrong and is something that is affecting other people as well.  The Woocommerce team need to fix this!  Instead, as far as I can see, all they have done is close this topic!

Not happy at all...

Regards.
Sara.

**Comment by serveds** [comment]
Hi Sara,

I was lucky that it was only 30 to 50 products that where affected.

I had someone manually got through them as I was not waiting for a fix.  In your case it might not be feasible only suggestion would be to use the import/export plugin and change the attributes that way.

Justin

**Comment by wizard247** [comment]
Not sure if you still need this:

If you have over 30 variations, you need to increased the number of allowed variations in your functions.php:

    /**
     * Ensure variation combinations are working properly - standard limit is 30
     * 
     */

    function woo_custom_ajax_variation_threshold( $qty, $product ) {
        return 50;
    }       
    add_filter( 'woocommerce_ajax_variation_threshold', 'woo_custom_ajax_variation_threshold', 10, 2 );
