### ISSUE TITLE
WC_Abstract_Order->get_item_meta_array() adds significant load time

### ISSUE THREAD

**Issue by micagroup** [woothemes/woocommerce#8810]
Hi guys,

We are seeing an almost 300 query increase from ~650 to ~950 qeuries just because of WC_Abstract_Order->get_item_meta_array()

It's affecting load time pretty significantly.

**Comment by mikejolley** [comment]
Where abouts?

This should only be used when getting all items in an order. It gets meta data.

**Comment by micagroup** [comment]
/wp-admin/edit.php?post_type=shop_order

**Comment by mikejolley** [comment]
And how many items in that order?

**Comment by micagroup** [comment]
It's not a specific order. It's the overview you get when you click Woocommerce > Orders
It has about 6500 orders total.

**Comment by micagroup** [comment]
Any update on this? You want to check it out?

**Comment by jeffstieler** [comment]
It looks like this will get kicked off for every order shown on `edit.php` here: https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L639

The problem is that `WC_Abstract_Order::get_item_meta_array()` doesn't have any caching around the query it's running. If we're to address this, it makes sense to me to start there.

@micagroup just curious - is your "Number of items per page:" set to 300?

**Comment by micagroup** [comment]
Hi Jef,




No it's not. Just the std 20z






—
