### ISSUE TITLE
[API] Category/Tags POST/PUT/DELETE endpoints

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#8879]
Create interface to manipulate categories and tags.

**Comment by geesen** [comment]
+1
I had in mind that this would be part of 2.4 (afair I read about that in the blog) and I was looking forward to see the 2.4 release. I would be very interested in such an interface since I use it to synchronize products and categories from an ERP system!

**Comment by Zmash** [comment]
So there is no way to create product categories in 2.4?
Is the opportunity to write the name of the category into the request also disabled?

**Comment by mikejolley** [comment]
Not via the API.

**Comment by geesen** [comment]
Since I really need that, I started to extend the API. 
I added POST and DELETE for now, PUT is in work.
Since I'm not really familar with Woocommerce internals, I had to search and lookup a lot of things. Although it seems to work, I don't know if I missed something?
https://gist.github.com/geesen/683f578878905a2043cd

**Comment by carpe171** [comment]
+1.  Also an endpoint for all available shipping classes would be useful.

**Comment by mikejolley** [comment]
@gedex might be a nice one to dive into if you like APIs :) Make sure its branched so we can merge to 2.5 when ready. cc @claudiosmweb

**Comment by pereiradiogo** [comment]
I can't call this method in v2. why?

**Comment by gedex** [comment]
This change is not released yet, should be shipped with 2.5. However, you could try it in `master` branch.
