### ISSUE TITLE
Total refund not triggered

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#8899]
If i refund the whole order but manually adding the prices and not changing the product quantity, WooCommerce thinks it's a partial refund, not a full refund and leaves the order status to Processing and sends the wrong email for the refund.

![](http://cld.wthms.co/VY0u/4BULyDYk+)

![](http://cld.wthms.co/12Lx8/4fk22Eqi+)

If i use the quantity buttons to refund items, the order status changes to Refunded and the correct email is sent.

I refunded via Stripe, not manually, not sure if it's important or not.

**Comment by mikejolley** [comment]
This was an intended change; Gerhard noticed that if you had a 'free' line item in a paid order, and refunded the money, the free item would also be 'refunded'.

The check for full refund is now based on item qty and full amount.

**Comment by slash1andy** [comment]
I think that this is kind of confusing, and we have had some tickets on it lately.

Here is how I would process a refund: ![](http://cld.wthms.co/11cv0/37VI9xTo+)

I would expect it to do a few things at this point:
* Change the order status to Refunded
* Send the Complete Refund email

Here's why I think it should not send the partial refund email, or leave the order in whatever state it currently is in:
* Refunds are completely separate of returning items to stock (i.e. an item was DOA, and the merchant just refunds the price rather than spending money to return broken merch)
* All the money was refunded, so it makes sense that that Full Refund email is sent. 

Here are the tickets that are asking about this: #351536 #354156

CC: @BFTrick

**Comment by BFTrick** [comment]
Gotta concur with @slash1andy here. Refunds aren't connected to stock. If you refund someone 100% of the money it's a full refund no matter what happens to the stock.

**Comment by mikejolley** [comment]
@BFTrick I think you need to talk to @kloon. The issue is when you have a paid order with free items inside. If you refund the money, the order is refunded, and any 'free' access to plugins is lost. Those free items are deemed 'refunded'.

2.5 already has an additional check to only implement this behaviour if the order contains a free item. If it doesn't, 100% refunded will change the status. @MindyPostoff was going to document this.
