### ISSUE TITLE
Add title attribute to tables for responsive tables

### ISSUE THREAD

**Issue by drrobotnik** [woothemes/woocommerce#9015]
File this under idea, but in order to make the cart layout better on mobile, we should add the title attribute to the td cells, and with css use the attr() pseudo element to modify the content. In html5 the title tag is valid on any html element, and all browsers support attr(). Adding the title won't break any validators, so I see no harm in adding it. Currently there is no way for a developer to add this without modifying a template directly, which breaks future changes.
    
    td:before {
        content: attr(title)": ";
    }

![Example](https://cldup.com/UQXlTmwJQy.png)

Here is the CSS I used to apply to woocommerce:
https://gist.github.com/14d2a213a42740f8a73f

References:
http://caniuse.com/#feat=css-gencontent
http://codepen.io/geoffyuen/pen/FCBEg

**Comment by jameskoster** [comment]
Yup, this is how the tables that are responsive are handled. The CSS already exists in core we just need to 'turn it on' on the cart.

We'll do this in 2.5.

**Comment by jameskoster** [comment]
Been scratching my head about this one today. Looks like somewhere along the road our responsive table styling stopped working in Chrome. Still works fine in Firefox and IE though.

Seems that WebKit is simply ignoring the `display: block` declaration on the `td`s. Some sources suggest that's due to not having a doctype declared but that's theme dependent and this always worked just fine in default themes.

It has been reported here: https://bugs.webkit.org/show_bug.cgi?id=38527 but is pretty old.

We might need to just add the attributes to the markup and then let themes handle the responsive styling themselves.
