### ISSUE TITLE
Bulk edit product category

### ISSUE THREAD

**Issue by caygri** [woothemes/woocommerce#9035]
HI! 

I see it's impossible deselect bulk product category.

SCENARIO:

I have White Shirt in Shirt category but I like to move with other Shirts in T-shirt Category and deselect Shirt category, actually I can't do it.

**Comment by WPprodigy** [comment]
Hi @caygri,

I'm not seeing the issue here? First, filter the product category you want: http://cld.wthms.co/D56S/5QjeTVG7

Then bulk edit that category: http://cld.wthms.co/D56S/5QjeTVG7

If you want to exclude a certain category from your bulk edit, then you will need to just bulk edit each child category that you want edited. This is a WordPress feature, and in no way a WooCommerce / WordPress bug.

**Comment by caygri** [comment]
I think I expose bad. 

I select 10 product in 1st Category, and I like to move in 2nd categoryand remove to select 1st category. In your way don't work

**Comment by WPprodigy** [comment]
Yea, I'm not sure I am understanding. 

But either way, this is a backend WordPress feature and doesn't have much to do with WooCommerce.
