### ISSUE TITLE
Coupon logic with restricted categories and products seems to be wrong

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9042]
1. I created a Coupon for product % discount. 
2. excluded On Sale products. 
3. Specified some Products that the coupon should apply to and also some categories. (the products specified are not in these categories... they are totally different).

It looks like they need to be overlapping... the products have to be in these categories.

Ref ticket: #330114

**Comment by mikejolley** [comment]
Correct; remember each rule is independent. Logic would be:

1. Is product on sale? Return false if it is.
2. Is product in IDs? Return false if not.
3. Is product in cat IDs? Return false if not.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-coupon.php#L500

I think its best to leave rules independent. If you try to make them overlap, users may expect things to 'act' in different ways based on their own selfish needs, just like we see with bookings availability rules.

They could possibly create a new category for this situation for these promo items. Or exclude rather than include.
