### ISSUE TITLE
Log test fails

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9110]
![](http://cld.wthms.co/1iFXI/2zo6lTul+)

I wrote this test, and I know it could fail sometimes if there is a delay.
The problem is that I can't think to a better way to test that method.

**Comment by mikejolley** [comment]
@gedex This is part of our unit tests. Ideas on a solution?

**Comment by gedex** [comment]
Instead of asserting equality we could assert the log line format using [assertStringMatchesFormat](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertStringMatchesFormat) and the log message itself using [assertStringEndsWith](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertStringEndsWith).

First, test the format of log line:

~~~php
$this->assertStringMatchesFormat( '%d-%d-%d @ %d:%d:%d - %s', $this->read_content( 'unit-tests' ) );
~~~

and then the log message:

~~~php
$this->assertStringEndsWith( ' - this is a message' . PHP_EOL, $this->read_content( 'unit-tests' ) );
~~~

I'll issue a PR for this later.

I took a look at [monolog](https://github.com/Seldaek/monolog/blob/master/tests/Monolog/TestCase.php#L49-L57) test case and basically they mock the formatter to ignore the timestamp information. So, I guess this is the right approach.
