### ISSUE TITLE
Help Tips do not work inside variation panels

### ISSUE THREAD

**Issue by Biont** [woothemes/woocommerce#9151]
If you hook into ```woocommerce_product_after_variable_attributes``` and add a ```.help_tip``` element there, it will not work because the tipTip component is not reinitialized for ajax'd content. 
[It is loaded only once when the page is loaded](https://github.com/woothemes/woocommerce/blob/0c56fe0844f1533dbd54a342949026cc1ff94a06/assets/js/admin/woocommerce_admin.js#L85-L91)

The workaround for a plugin developer would be to add this JS on the admin page:
```
	$( '#woocommerce-product-data' ).on( 'woocommerce_variations_loaded',function(e){
		var tiptip_args = {
			'attribute': 'data-tip',
			'fadeIn': 50,
			'fadeOut': 50,
			'delay': 200
		};
		$( '.tips, .help_tip' ).tipTip( tiptip_args );
	} );
```

But it would make sense to fix this in the core :)

**Comment by claudiosmweb** [comment]
Works fine:

![screenshot from 2015-09-17 14 33 13](https://cloud.githubusercontent.com/assets/1264099/9941036/36c344b6-5d49-11e5-9a3f-5b3e2ea43820.png)

About: https://github.com/woothemes/woocommerce/blob/0c56fe0844f1533dbd54a342949026cc1ff94a06/assets/js/admin/woocommerce_admin.js#L85-L91

This load one time when the page is loaded, but not for variations, because we don't have any variation loaded at this time. Variations are loaded just when you click in the "Variations" tab... and then we run TipTip: 

https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/meta-boxes-product-variation.js#L109-L117

**Comment by Biont** [comment]
Hi! Thanks for your reply.
The code you linked specifically re-initializes ```.tips``` elements. I was talking about the ```.help_tip``` element *(with the little (?)- icon graphic)*

![](https://biont.ursa.uberspace.de/sharex/bilder/2015-09-22_09-37-46.png)

This will **not** work inside variations, unless I initialize tipTip on ```.help_tip``` myself.

**Comment by claudiosmweb** [comment]
@Biont on WooCommerce core we don't have any `.help_tip` on variations tab.
It seems that you are using a plugin that has not been updated yet.
I will write some code to make it compatible.
