### ISSUE TITLE
Only a subset of categories displaying on /shop page

### ISSUE THREAD

**Issue by SRD75** [woothemes/woocommerce#9230]
Our store has about 14 categories, all of which contain products, but only 2 categories are displayed on the shop page: http://www.tempertemper.com.au/test/shop/

This occurs with all plugins deactivated, and Twenty Fifteen theme activated.

WooCommerce Version 2.4.7
Wordpress Version 4.3.1

**Comment by WPprodigy** [comment]
Hi @SRD75,

This is likely not a WooCommerce issue, since there are not thousands of more reports for this. So there must be a conflict or a setting that needs to be different on your site.

First, check that all of the other categories have visible products in them (i.e. they aren't drafts and they aren't hidden). 

If that isn't the case, then you should open up a support ticket here: https://woothemes.com/my-account/create-a-ticket/ 

In the future, note that this is not a place to get support.
