### ISSUE TITLE
Attributes: Default sort order, PHP Error

### ISSUE THREAD

**Issue by StewieGm** [woothemes/woocommerce#9234]
Having a dot in a numeric value causes a PHP error in the product page when using Default sort order - "Name (numeric)" for an attribute. This causes the whole page execution to stop.

Example values in the attribute which caused the issue:
* 7
* 7.5
* 8
* 8.5
* 9
* 10

So actually 7.5 and 8.5 are the "issue" here. They are valid numeric values, but somehow there's an issue here.

The PHP error shown in the product page is:
Catchable fatal error: Object of class stdClass could not be converted to string in /WPPATH/wp-content/plugins/woocommerce/templates/single-product/product-attributes.php on line 56

I have the latest WooCommerce 2.4.7.

**Comment by gedex** [comment]
@StewieGm I couldn't reproduce your issue here with `2.4.7`. [Line 56](https://github.com/woothemes/woocommerce/blob/2.4.7/templates/single-product/product-attributes.php#L56) refers to `woocommerce_attribute` filter. I suspect something (maybe other plugins or theme) is filtering the value and does string operation. Could you try deactivate plugin one by one and switch to standard theme.

**Comment by mikejolley** [comment]
Agreed. Would be caused by something filtering on 'woocommerce_attribute' hook.
