### ISSUE TITLE
Add js validation for product quick edit

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce#9259]

**Comment by nishitlangaliya** [comment]
I was able to produce this case and fixed this issue in my local server. and tried to create issue from master branch but was not able to create issue branch from it. can you please guide me how I can push my code to issue branch.

Also this issue is not assigned to milestone so can you please assign it to milestone so that I can push into that milestone.

**Comment by nishitlangaliya** [comment]
As per above fixes ref # 02e2f2b the changes will look like below attached images :

1. For Regular Price Quick Edit:
![quckedit_regularprice](https://cloud.githubusercontent.com/assets/11435772/10338580/772e7cce-6d24-11e5-906a-ad13f4a63b51.png)

2. For Sale Price Quick Edit:
![quckedit_saleprice](https://cloud.githubusercontent.com/assets/11435772/10338615/9daffeae-6d24-11e5-9d1a-596c4d338bcc.png)
