### ISSUE TITLE
$0 flat rate shipping class bug

### ISSUE THREAD

**Issue by DanielMarquard** [woothemes/woocommerce#9270]
I created a shipping class called "Free Shipping" with a flat rate of 0 and applied it to a few products. At checkout, there are no shipping options available, only the text "There are no shipping methods available. Please double check your address, or contact us if you need any help."

Using a value of zero for this shipping option does not work, but when I use the value "1-1" to achieve the same result, WooCommerce properly displays the shipping option with the price of "Free".

**Comment by WPprodigy** [comment]
I was able to replicate this with these settings: http://cld.wthms.co/197yL/4hv8px4e

If you add "0" to the default costs though, then the calculation will work: http://cld.wthms.co/116mV/3YligwB2

**Comment by WPprodigy** [comment]
Ahh, maybe this check is failing because '0' also acts as 'false' in this situation? - https://github.com/woothemes/woocommerce/blob/master/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php#L154

Soz, get_option returns false, and sets the default to ' '. By removing that default, it should work itself out.

**Comment by DanielMarquard** [comment]
Seems so, since "1-1" processes as 0.00 so the field itself doesn't validate as false. We were luckily able to work around this quickly, now on to dealing with a subscription shipping bug... :persevere:
