### ISSUE TITLE
Standard tax rates wont display in admin

### ISSUE THREAD

**Issue by FreelanceCreatief** [woothemes/woocommerce#9299]
Hi there,
I just cant get the standard tax rates rows to diplay.
It saves but doesnt show the rows.
I already deleted all taxes and added tables to phpmyadmin.
Regards,
Jasper.

**Comment by WPprodigy** [comment]
Sounds like you have done some hackety hackety stuff to the database? I'm not exactly sure what your issue is that you are trying to describe. Are the tax rates not showing/saving in the admin, or are they not loading/calculating at checkout?

Is this what is not working for you: http://cld.wthms.co/12HWS/2Tb1WzEy ?

Since it works for me, and all other sites out there, you likely have a conflict or have done something to interfere with the process. Try installing a new installation of WordPress/WooCommerce and see if it works.

This isn't a place to get support, but rather a place for reporting bugs. So feel free to open up an issue if you find a bug, but this seems more like an error causes by you or a plugin/theme conflict.

**Comment by FreelanceCreatief** [comment]
Thanx for your reply. I tried installing several times. The rows dont show up. But I guess its some kind of conflict. Thought it was a bug.
