### ISSUE TITLE
Related posts are not random anymore

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#9302]
This bug has been introduced in WC 2.3 by this commit:
https://github.com/woothemes/woocommerce/commit/28d838c5cdf0cb8daf3ad1d180d00da6dd115087#commitcomment-13453096

There's also a comment which reports the error. Was that intended or not?
There's no way to get random products now, it always shows the same products just randomizing their order.

**Comment by mikejolley** [comment]
Look at the commit notes. It's not a bug - its intentional.

**Comment by SiR-DanieL** [comment]
Oh ok, sorry, I missed that.

**Comment by halabuda** [comment]
i still maintain that there is a bug here. i understand the cost of query issue and introducing the transient cache to address it, but the transient cache contents should still be randomized to some extent when they are initially seeded. as it stands now the function is just caching multiple instances of the same 3 products.

**Comment by SiR-DanieL** [comment]
There's a filter `woocommerce_product_related_posts_query` to add `ORDER BY RAND()` in the query. You could use a code like

```php
add_filter( 'woocommerce_product_related_posts_query', 'edit_related_products_query' );
function edit_related_products_query( $query ) {
  $query['limit'] = ' ORDER BY RAND() ' . $query['limit'];
  return $query;
} 
```

**Comment by halabuda** [comment]
@SiR-DanieL thanks for getting back to me and thanks for the suggestion. using the filter is exactly the solution i have implemented on my own site to workaround this issue, but it still seems to me that this related products feature is flawed in the way that it is creating its transient caches. i understand that the real randomized query is heavy thus the need for the cache, but when that cache instance per limit value and product ID is initially created, that first query should still use real randomness. otherwise you end up shuffling only the first few products from the results and never seeing any products beyond those initial few which effectively negates the usefulness of the feature altogether. certainly one randomized query per product per 30 days is affordable, don't you think?

**Comment by mikejolley** [comment]
@halabuda Like I've said in other tickets, unless a customer refreshes the same product page again and again they will never notice its not random. A heavy query just for that is overkill. Replace the area with your own if you want true randomness.

**Comment by halabuda** [comment]
@mikejolley thanks for the reply. i'm not talking about refreshing a product page. this doesn't affect the randomness or perceived randomness of a SINGLE product page, but potentially large groups of products that share categories/tags. so a customer browsing a store within a category navigating through a large selection of products will only see the same stagnant few related products. i would be glad to show you a live demonstration if that helps.
