### ISSUE TITLE
no select2 dropdowns in the cart Shipping Calculator?

### ISSUE THREAD

**Issue by timkirtley** [woothemes/woocommerce#9304]
Hi,

The dropdowns for Country and State in the Shipping Calculator in my cart dont use select2, instead they are standard system dropdowns.

In the checkout they do use select2.

Is this correct?

I've seen in /includes/class-we-frontend-scripts.php the conditional on line 137 the conditional for enquing select2 only looks for 'is_checkout' or 'woocommerce_myaccount_page_id'...   

if I add 'is_cart()' to that conditional, then select2 is used on the cart page, but doesnt work 100% correctly - If I change the country from UK to US and then back again both the state and country dropdowns are removed..

Is that the reason select2 isn't loaded on the cart or should it work?

**Comment by claudiosmweb** [comment]
The expected behavior is not to have Select2 in the cart.

**Comment by 5tormTrooper** [comment]
I had this issue too, and I don't think @claudiosmweb's answer provides enough reason. The expected behaviour for who? I think user's fully expect the dropdowns to behave in a similar manner on the cart and checkout pages. So why don't they?

Anyway, @timkirtley, modifying the class-we-frontend-scripts.php is not recommended. In my functions.php, where I enqueue my other scripts and styles, I added the enqueue script for Select2 to the cart page using the following code:
`
if ( is_cart() ) {
		$woo_assets_path = str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() ) . '/assets/';
		wp_register_script( 'select2', $woo_assets_path . 'js/select2/select2.js', array( 'jquery' ), '', true );
		wp_enqueue_script( 'select2' );
		wp_enqueue_style( 'select2', $assets_path . 'css/select2.css' );
	}

`
Then all you need to do is call the plugin for those `select`s in your JS:
`$('#calc_shipping_country, #calc_shipping_state').select2();`

That worked for me, even when switching back and forth between countries.

Issue replies should be more descriptive, or at least helpful.

**Comment by roykho** [comment]
So the purpose of using Select2 is when the list of options gets too big, Select2 enhances the experience by adding a search and window aware scrolling... etc  When the list is short, there is no need for Select2.  Select2 is expensive to use thus when it is not needed, we try not to add it.

**Comment by mikeyrayvon** [comment]
@roykho but that doesn't add up, seeing as how Select2 is used for the Country select on Checkout but not on Cart.
