### ISSUE TITLE
Show variation add to cart button, Award winning example

### ISSUE THREAD

**Issue by yratof** [woothemes/woocommerce#9331]
I'm just going to bring this up once more. Referencing #9190 #9200 #1984 

As this site is a site chosen by woothemes and won an award for being a great woocommerce store: http://www.woothemes.com/2014/08/case-study-o-v-e-r-clothing/

I'd like to highlight that this site is riddled with variable products, yet the variation button does not hide: https://overclothing.com/product/over-heatwave-men-shirt-black/

Now for a site that is, in woocommerces eyes, award winning, does this not help my cause for not hiding the add-to-cart section when you haven't got anything selected?

**Comment by forsvunnet** [comment]
I would like to tune in here too. Having the add to cart button pop up out of thin air is quite an annoying feature to deal with on every new website we put up stores for clients. It would be much better if it was always visible.

**Comment by jameskoster** [comment]
This one again :-)

Obviously this can be achieved via customisation / plugin. But I'm still waiting for a really compelling reason to make this the default behaviour. Just because it makes sense for some sites, that doesn't mean it makes sense for all. In my mind there are valid arguments for and against both solutions, but in our experience, changing things like this generally causes more trouble than it's worth. Which is why, as long as it's possible via customisation I'd prefer to leave it.

**Comment by greguly** [comment]
@yratof and @forsvunnet, why don't you consider the customisation / plugin a differentiation service that you can provide to your clients and charge more for that? ;-)

**Comment by mikejolley** [comment]
Stick it on ideas.woothemes.com IMO so it can be voted on, rather than coming here every few weeks without data to back the idea up.

**Comment by lukecav** [comment]
Seems like there should be a solution for this already.

**Comment by jameskoster** [comment]
@lukecav there probably is a solution if you google around. 

If you'd like to see this in core please create and/or vote on the idea in our ideasboard as Mike suggested so that we can gauge genuine interest.
