### ISSUE TITLE
Checkout Error

### ISSUE THREAD

**Issue by Macuzzin** [woothemes/woocommerce#9358]
Hi,

I'm Using WooCommerce 2.4.7 at http://www.noonoopie.co.za/. I know this issue has been covered extensively and I 've tried everything suggested under the sun. I'm getting the following error when placing an order from checkout: 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I contacted support for our gateway plugin and this was their response: 

"With reference to the WooCommerce knowledge base article you will note that this bug is unrelated to the our plugin but as a result of changes made by Wordpress to their API hooks. This change has not only affected the WooCommerce plugin but multiple other Wordpress plugins and the themes that they have implemented."

Does this mean that the issue could be theme incompatability with WordPress? I find that hard to believe.

I would really appreciate it if someone could shed some light on this issue.

Many thanks

**Comment by mikejolley** [comment]
Something is outputting garbage and invalidate the JSON response. Might be a plugin or gateway.

**Comment by vasilestefirta** [comment]
Hi,
I have the same issue, but only for WooCommerce Subscriptions products. It looks like the subscription order goes in successfully, but WooCommerce can't redirect the user to the "Order Placed" page, because of an error caused by the WooCommerce USPS plugin (see screenshot). USPS plugin generates an error "Packing error: No items to pack!" for some reason. But, regardless of this, the subscription is still successfully placed. Any ideas how can I fix this?
WooCommerce - v 2.4.8
WooCommerce Subscriptions - v 2.0.3
WooCommerce USPS Shipping - v 4.2.12

Any help will be much appreciated!

![screen shot 2015-10-28 at 5 10 07 pm_](https://cloud.githubusercontent.com/assets/6243883/10807669/4de92af4-7d9f-11e5-9ef9-b2755c4dd59d.png)

**Comment by titocalabrese** [comment]
has anybody found a solution to this "Packing error: No items to pack!" error?
