### ISSUE TITLE
Tax applying to coupon values

### ISSUE THREAD

**Issue by Einkoro** [woothemes/woocommerce#9393]
When using "Display Prices During Cart and Checkout" set to "Including tax" coupon discounts are displayed with tax applied to them.

![Screenshot of coupon options] 
(https://www.dropbox.com/s/7q343h7txeutgag/Screenshot%202015-10-20%2014.27.23.png?raw=1)

![Screenshot of tax options]
(https://www.dropbox.com/s/8zugty98m3klhv6/Screenshot%202015-10-20%2014.30.38.png?raw=1)

![Screenshot of cart totals]
(https://www.dropbox.com/s/cir2lm2tbvxekpm/Screenshot%202015-10-20%2014.38.00.png?raw=1)

Setting it to "Excluding tax" results in the correct -$99.00 expected.

WC Version: 2.4.7
WP Version: 4.3.1

**Comment by WPprodigy** [comment]
I was able to replicate this issue as well.

This is the line getting executed in the scenario: https://github.com/woothemes/woocommerce/blob/f7ea1d4c6a1f3751b80e807ef89b2968cb25c6e0/includes/class-wc-coupon.php#L659

**Comment by mikejolley** [comment]
You're changing the calculation - thats worse. The above screenshot is correct - 599.50 - 107.91 = 491.59

The discount is 99, but that cancels out some of the taxes (because less tax is taken). Remember taxes are always calculated after discount.

Leaving it displayed as -99 will mean the totals don't 'add up' and will look worse than changing the discounted amount.
