### ISSUE TITLE
Website URL Change - Pull Orders

### ISSUE THREAD

**Issue by jmawebtech** [woothemes/woocommerce#9415]
Hi,

I am trying to pull orders from a WooCommerce website, but I cannot find them:

Request

https://blackmp.tech/wc-api/v2/orders?filter%5Bcreated_at_min%5D=2015-10-1T00:00:00Z&filter%5Bcreated_at_max%5D=2015-10-28T23:59:00Z&consumer_key=XX&consumer_secret=XX&page=1&filter%5Blimit%5D=100&filter%5Bmeta%5D=false

Response

{
"orders": []
}

The website says there are several orders in this period:

![woo_orders](https://cloud.githubusercontent.com/assets/1679993/10676985/b7400da0-78d7-11e5-8c74-340254c2efc4.jpg)

My customer changed the website's URL, which I believe is causing the problem. Visiting blackmp.tech redirects to blackmp.net.

**Comment by claudiosmweb** [comment]
Well, `2015-10-1T00:00:00Z` is not a valid date format, should be `2015-10-01T00:00:00Z`...
The default value for `filter[meta]` is `false`, so you don't need to set it.

Changing the URL does not seem a problem, since the API is returning messages. Anyway make sure everything was changed correctly.
