### ISSUE TITLE
Woocommerce : The cart is not getting cleared even after logged out

### ISSUE THREAD

**Issue by riyanusa** [woothemes/woocommerce#9473]
Hello,

The cart is not getting cleared even after logged out from the account. Please check the steps to recreate the issue for more details.

Steps to recreate the issue: 
1. Log in as any user. 
2. Add to cart any product 
3. Now, log out from the account 
4. Check the quantity near to the cart image 
5. Now, log in as any other user 
6. Add to cart any product 
7. Check the cart page 
The cart page is not getting cleared even after the user logged out from the account.

WooCommerce Version 2.4.7 
Wordpress Version 4.3.1
Site : https://bobcares.com/

What could possibly be the problem? Hope to hear from you soon. 
Thank you.

**Comment by WPprodigy** [comment]
Are you wanting the customer's cart to be cleared if they log out and forever gone even if they log back in? Or when they log back in, do you want the items to still be available?

I wasn't able to replicate any issue with this process. I logged in and added two items to the cart. Logged out, items were gone. Logged into a new account, added two different items. Logged out, items were gone. Logged back into first account and the original two items were there.

**Comment by helgatheviking** [comment]
The cart isn't meant to get cleared on logout. It gets stored in the user meta under the `'_woocommerce_persistent_cart'` key precisely so that it is available when the user comes back. I bought some things online today that had been hanging out in my cart, so it seems like a useful feature to me. 

If you are bound and determined to clear the carts on logout then you can run the `wc_empty_cart()` function on logout:

```
add_action( 'wp_logout', 'kia_destroy_persistent_cart' );
function kia_destroy_persistent_cart(){
	if(function_exists('wc_empty_cart')){
		wc_empty_cart()
	}
}
```

**Comment by mikejolley** [comment]
Thanks @helgatheviking

**Comment by user55777** [comment]
I have added the following to my functions.php and the cart is not being cleared:

add_action( 'wp_logout', 'kia_destroy_persistent_cart' );
function kia_destroy_persistent_cart(){
    if(function_exists('wc_empty_cart')){
        wc_empty_cart();
    }
}

I am "bound and determined to clear the carts on logout" so that when a user logs back in there is nothing in their cart so they can start fresh.

Please help, thank you!
