### ISSUE TITLE
Woocommerce 'add to cart'

### ISSUE THREAD

**Issue by shanghaishannon** [woothemes/woocommerce#9483]
Woocommerce "add to cart" function is broken. It's fine when logged in as an admin, but not as a usual visitor.. The cart icon in the menu will show a total, but you're directed to your "cart" page which shows "cart empty."My client just emailed me about it. Is this due to an update?

http://www.shinyhappyspirithouse.com

**Comment by WPprodigy** [comment]
Hi shanghaishannon,

This is usually caused by caching. If you have a caching plugin set up or if your server has caching, you need to exclude the cart page from being cached: https://docs.woothemes.com/document/configuring-caching-plugins/

This is not and issue with WooCommerce, and this is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.
