### ISSUE TITLE
Cross-Sells don't show "Search" only items - intended feature?

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/woocommerce#9518]
Hey guys,

Just checking to see if this is intentional - I can see some situations where a user may want to have the cross-sells be specific items related to the product, such as spare parts for a machine, that they wouldn't want to sell on their own.

An example - I have a Starfleet-issue Red Shirt with a cross sell item: 

![http://cld.wthms.co/18Jo1/2nsLfIWq](http://cld.wthms.co/18Jo1/2nsLfIWq+) 

When the First Aid Kit is set to appear in the Catalog/Search, then things look fine:

![http://cld.wthms.co/1avUH/4uL0YmSe](http://cld.wthms.co/1avUH/4uL0YmSe+) 

But if it's search only:

![http://cld.wthms.co/1cmai/440NuH2O](http://cld.wthms.co/1cmai/440NuH2O+) 

Settings I'm talking about: 

![http://cld.wthms.co/18Gtk/4CiUmRbV](http://cld.wthms.co/18Gtk/4CiUmRbV+) 

Is there a way we can make that section display the item regardless of it's visibility (unless of course it's hidden entirely)?

Related ticket (for my own info so I can keep them posted, but nothing new there): https://woothemes.zendesk.com/agent/tickets/345428

**Comment by mikejolley** [comment]
This is intended as there is no dedicated visibility setting for just cross sells.

> I can see some situations where a user may want to have the cross-sells be specific items related to the product, such as spare parts for a machine, that they wouldn't want to sell on their own.

Remember that visibility does not prevent purchase - you can see find product pages, and/or add to cart and remove the other items in your cart. 

If this needs changing for a user, there are 2 places which need customisation.

1. woocommerce_product_is_visible filter needs to return true on the cart page.
2. this line needs removing https://github.com/woothemes/woocommerce/blob/master/templates/cart/cross-sells.php#L37

The above can be used. I don't want to change the core behaviour because what works for this user, may break expectations for others.

**Comment by sallygny** [comment]
I don't really understand how to use this ... I want for example to have an otherwise hidden product show as cross-sell visible in cart only. How can I achieve that ?!!? 
Thx!

**Comment by DanielSantoro** [comment]
@sallygny That's what we were discussing in the thread above - it's not possible to do this without customization.
As outlined in our [Support Policy](http://www.woothemes.com/support-policy), we can't help, but one of the following services might:

* [WooExperts](https://www.woothemes.com/wooexperts/)
* [Codeable](http://codeable.io/?utm_source=ZenDesk&utm_medium=ticket-reply&utm_campaign=Custom%20Referral)
