### ISSUE TITLE
CSV Export on Reports screen hidden by default on Safari

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/woocommerce#9520]
For some reason, the Export CSV button on the Reports screen has an inline CSS style of `display: none;` when using Safari. Recorded screencast: http://recordit.co/xvJoANRc38

This is not the case using Chrome: http://cld.wthms.co/1lj4s/db9hqHmU

**Comment by gedex** [comment]
This is caused by [download attribute](https://github.com/woothemes/woocommerce/blob/master/assets/js/admin/reports.js#L128-L130) which is not supported on recent Safari and IE, see http://caniuse.com/#feat=download.

Since we're building CSV data with JS, the solution to support unsupported browsers would be to provide CSV data in the backend. Or, we should wait these browsers to support the feature, as download attribute is [HTML5 spec](http://updates.html5rocks.com/2011/08/Downloading-resources-in-HTML5-a-download).

**Comment by mikejolley** [comment]
> Or, we should wait these browsers to support the feature, as download attribute is part of HTML5 spec.

That was the plan - doing it with JS is much more lightweight than a PHP based exporter.
