### ISSUE TITLE
Sorting array parameters too, for OAuth signature check

### ISSUE THREAD

**Issue by norbert-sebok** [woothemes/woocommerce#9639]
I had a problem with wc-api-python related to the order of parameters: https://github.com/woothemes/wc-api-python/issues/8

The wc-api-python sorts all of the parameters but [the check_oauth_signature function](https://github.com/woothemes/woocommerce/blob/4595befb76262cc5279693205ad2c10825c1c47a/includes/api/class-wc-api-authentication.php#L224) doesn't sort the array parameters. Like filter[created_at_max], filter[limit], etc. For example the order in the $string_to_sign is filter[limit] followed by filter[created_at_min]. Not sorted.

[The documentation](http://woothemes.github.io/woocommerce-rest-api-docs/#authentication) says: `4) Sort the parameters in byte-order (uksort( $params, 'strcmp' ) in PHP)`. It's language specific. PHP collects [*] parameters as arrays, while Python doesn't have this concept and simply sorts all params.

The array parameters can be sorted easily: https://github.com/norbert-sebok/woocommerce/commit/bbdc4e60ef789f8ad037151b04a8c4ae020d131b I'm not perfectly sure if it breaks other API libraries or not. Maybe other libraries implemented the same method and doesn't sort the array params for the signature. 

So, can we sort the array parameters without breaking anything?

Or do we have to change wc-api-python to not sort array params?

**Comment by mikejolley** [comment]
This should be in the python bug tracker. I've reopened the other issue for Claudio to review.

**Comment by PauloOneSaas** [comment]
Hi @mikejolley, 

I seem to be hitting exactly the same issue as the OP here but I get it when using the PHP API. Every time I add the 'filter[updated_at_min]' I get an un-authorized error.

Here is the final string that I am using before I create the auth signature with the consumer secret:

```
GET&http%3A%2F%2Fxtesting.onesaas.com%2Fwordpress441%2Fwc-api%2Fv3%2Forders&filter%5Bupdated_at_min%5D%3D2016-03-21%26oauth_consumer_key%3DconsumerKey%26oauth_nonce%3DHnCnfmAMtYgfmKVVNUXDKseyn9Ss8Zr7%26oauth_signature_method%3DHMAC-SHA256%26oauth_timestamp%3D1458607273%26page%3D1
```

with the full request being:
```
http://xtesting.onesaas.com/wordpress441/wc-api/v3/orders?oauth_consumer_key=consumerKey&oauth_timestamp=1458607273&oauth_signature_method=HMAC-SHA256&oauth_nonce=HnCnfmAMtYgfmKVVNUXDKseyn9Ss8Zr7&page=1&filter%5bupdated_at_min%5d=2016-03-21&oauth_signature=C8ZGdlcZvG%2baw%2blbHgQWXjhf1UxV7ySzWU5Zj7NoCtc%3d
```

I have a feeling that it has to do with the square brackets around the 'updated_at_min' because when I use filters like "status=completed", "order=asc", "fields=id" the call is successful. I have also tried with "filter[created_at_min]" and get the same unauthenticated error.

Should I create a new Issue?

Cheers,
Paulo

**Comment by norbert-sebok** [comment]
Hi @PauloOneSaas,

It's not exactly the same issue. The Python client worked perfectly if I used only one `filter[*]` parameter. It returned "Invalid Signature" authentication error only if I sent more than one `filter[*]` parameters. See https://github.com/woothemes/wc-api-python/issues/8

So I would suggest creating a new issue.
