### ISSUE TITLE
WooCommerce update changed all refunds

### ISSUE THREAD

**Issue by iamswain** [woothemes/woocommerce#9699]
The latest WooCommerce update seems to have screwed over all the previous existing (partial) refunds by making the refund the total amount of the order.

**Example:**
Client A ordered Product A and Product B.
Product A costs $10, and Product B costs $20.

Client A decides that he's not happy with the quality of Product A, ships it back and gets a refund of $10.

Refunded amount: $10

The update changed this refund to a refunded amount of $30. Client A received an email from this change.

**Comment by mikejolley** [comment]
There was upgrade logic for FULLY refunded orders:

https://github.com/woothemes/woocommerce/blob/master/includes/updates/woocommerce-update-2.4.php#L142-L177

If this affected your partial refunds it would mean you set 'refunded' status for your order when it shouldn't have been.

Fully refunded orders are marked with refunded status.

Partially refunded orders are left as is (completed in most cases). Otherwise it screws with reporting.

**Comment by iamswain** [comment]
Thanks Mike, for the quick reply.

I understand now why it broke. Is there a way to give partially refunded orders a status such as "Partially refunded"? Or how else is it possible to find partially refunded orders?

**Comment by mikejolley** [comment]
Orders with refunds should show up in the order list with the order total striked through. Having a dedicated status would break functionality, such as allowing downloads for completed orders.
