### ISSUE TITLE
2.4.8+: $woocommerce_loop has become unpredictable

### ISSUE THREAD

**Issue by lkraav** [woothemes/woocommerce#9700]
I can't pinpoint the exact 2.4 point release where this became a problem, but I'm now seeing `$woocommerce_loop` having different values based on whether the user is logged in or not.

Up until recently, checking `$woocommerce_loop` for NULL used to be enough. As of 2.4.8+ something changed where the only way to understand whether you're in the loop is to check if `$woocommerce_loop["columns"]` is empty. I initially thought it was a change by design, but now it looks like it may be a bug. I can't find a single recent commit doing anything with `$woocommerce_loop` based on `git log -G woocommerce_loop`, which adds to my confusion.

Here's the test results for the very same page:

Logged in:

```
[25-Nov-2015 10:29:25 UTC] Array
(
    [columns] => 
    [loop] => 
)
```

Logged out:

    [25-Nov-2015 10:29:35 UTC] NULL

**Comment by mikejolley** [comment]
@lkraav where are you var dumping woocommerce_loop? It's a global - so when you output it makes a massive difference.

**Comment by lkraav** [comment]
I'm outputting it from the top of the `content-product.php` template. `global $woocommerce_loop` is there at the very top.

**Comment by mikejolley** [comment]
Echo in the 'li' to make it clearer: https://dl.dropboxusercontent.com/s/bj1l9wcbsxrnkpd/2015-11-30%20at%2011.19.png?dl=0

The first 'loop' will be empty because the 'columns' value is not set right away. It is first set here on first loop: https://github.com/woothemes/woocommerce/blob/master/templates/content-product.php#L31

You may be seeing differences because admin/logged in users may 'see' non visible products which will be skipped here, or even other loops on the page:

https://github.com/woothemes/woocommerce/blob/master/templates/content-product.php#L36

For me I had the same values regardless, NULL on first loop. Values on subsequent.

**Comment by lkraav** [comment]
Thanks. I will investigate further. My main concern is that this behavior suddenly changed and I'm not able to pinpoint any recent WC commit that has changed how `$woocommerce_loop` operates. Previous mode of operation ran stable for months (shop was launched in the summer). Is it possible that a change was done somewhere in nearby code, where "`$woocommerce_loop`" doesn't reach the diff context for matching a `git log -G` query? Doesn't sound plausible..
