### ISSUE TITLE
Product Categories With Same Name

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/woocommerce#9705]
If a user has two different sub[categories with the same name, all items appear when viewing that sub-category.

This screenshot makes more sense:
<img width="1435" alt="winter___product_categories___bikebonk" src="https://cloud.githubusercontent.com/assets/2293077/11406521/a84223a6-937b-11e5-8545-52b1d931fbe8.png">

This is a sample setup where there is a category for clothing and one for shoes. If you view the URL for what should be winter shoes, you see anything with a winter category.

**Comment by mikejolley** [comment]
Tested this and didn't occur. Slugs were different because WP cannot reuse slugs:

![2015-11-30 at 11 36](https://cloud.githubusercontent.com/assets/90977/11470557/aa6a110a-9756-11e5-96cf-388d4384e7e9.png)

Both showed 1 product only. Only conclusions I can make from your screenshot is either that the products have both sub-categories set, a plugin is changing the WP queries on the frontend, or somehow both sub-categories have the same slug due to botched import. Doesn't appear to be a core issue after testing.

**Comment by DustinHartzler** [comment]
After following up to get more information, here's what the user said:

> I set up the whole shop automatically via scripting, using a mixed approach between WooCommerce API calls and direct DB operations (WooCommerce API is lacking some stuff unfortunately).

> And the category module creates duplicates slugs, since it does not take into consideration parent categories when creating category slugs ;-(

I'll troubleshoot and test more before opening new tickets :)
