### ISSUE TITLE
Add Gmail action tags to emails

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce#9745]
When sending out emails to customers and store owners, it could be useful to include action tags. For example, if an order has a shipment tracking number, we could add a "Track your order" action button to emails sent to Gmail, or a "view this order" button for store owner emails of new orders.

Developer reference: https://developers.google.com/gmail/markup/reference/go-to-action

cc @beaulebens @mikejolley

**Comment by mountainviper** [comment]
Good idea!

**Comment by reigelgallarde** [comment]
This is a great idea.

But be reminded that email address' must be registered with Google. Without registering, action tags just works when you send the email to the same email (sample x@gmail.com to x@gmail.com).

https://developers.google.com/gmail/markup/registering-with-google

**Comment by jonkoops** [comment]
I'd be willing to implement this feature. I've got the next couple of days off and I have been looking for something to do. The inline microdata seems to be the easiest to implement for the emails as it is just some sugar around the existing HTML content. 

There is a specific [`Order`](https://schema.org/Order) type we can use for order confirmation emails, it should look something like this when the user receives the email:

![inbox_order](https://cloud.githubusercontent.com/assets/695720/12071365/e9bac712-b0a8-11e5-80f2-fb1144cd26f7.png)

For the shipping I can implement the [`ParcelDelivery`](https://schema.org/ParcelDelivery) type, which gives the user a nice overview of the status:

![inbox_package](https://cloud.githubusercontent.com/assets/695720/12071378/c030a67c-b0a9-11e5-9f68-72daa9203c71.png)

These seem to include the before mentioned 'View Order' and 'Track Package' call-to-action buttons.

**Comment by jonkoops** [comment]
On further inspection I think that inline microdata isn't the way to go as it would most likely require that the email templates be modified in a non-backwards compatible way. I am also afraid to modify the existing email templates by inserting a bunch of tags that various e-mail clients might misinterpret and subsequently break the layout.

JSON-LD also makes it significantly easier to work with since the information is in a single place (a script tag with some JSON). So I think that would be a better way forward.

**Comment by bentasm1** [comment]
Good luck getting Google to approve you.  They only approve very high volume sites, and even with the few I operate doing a few million a year in sales, they still wont approve me.  Great feature request, still should be implemented at some point, but the priority surely is low since Gmail is silly for restricting who can add the data.

Might even be better for 3rd party plugin territory, it's just a few lines of text and the hooks can handle that.

**Comment by jonkoops** [comment]
I've opened up a pull request with a very crude implementation. I'd love to have some feedback on how it could be improved and what is missing.

**Comment by bentasm1** [comment]
#10432 Looks great!  As gmail is starting to open this more to regular stores should be a good merge.

**Comment by mikejolley** [comment]
Moving discussion to #10432
