### ISSUE TITLE
PayPal Standard and Pro Plugin sending shipping charges as a line item to PayPal

### ISSUE THREAD

**Issue by bplabz** [woothemes/woocommerce#9852]
Greetings, we use PayPal's IPN to push order data into Teapplix which manages our shipping. It has been working well prior to cart implementation using woocommerce. 

PayPal Standard order payments include the shipping data as a line item within the order. Since Teapplix sees shipping as an item, it gets printed onto customs forms and causes a host of other problems. 

We also purchased the PayPal Pro Plugin and noticed that with "Send order data as line items" checked the same thing happens. We cannot uncheck that option because we need the item details sent to PayPal.

![woocom](https://cloud.githubusercontent.com/assets/16310948/11822482/4ce78276-a334-11e5-8690-680d994c0312.jpg)

Is there a way to pass the shipping charges as actual shipping charges to PayPal with both implementations?
1. PayPal Standard (included with Woocommerce)
2. PayPal Pro (additional purchased plugin)

**Comment by mikejolley** [comment]
We don't pass this as a shipping line because of limitations in the PayPal API.

https://github.com/woothemes/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L175

> For shipping, we longer use shipping_1 because paypal ignores it if *any* shipping rules are within paypal, and paypal ignores anything over 5 digits (999.99 is the max).

This was causing issues with users who had rules setup paypal side, or combined shipping costs greater than the max.
