### ISSUE TITLE
Use of UK vs GB

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/woocommerce#9872]
For the most part, people use the terms interchangeably, though there is a difference since UK also refers to Northern Ireland.

"GB" is used as the official country code, despite also have the name "United Kingdom": https://github.com/woothemes/woocommerce/blob/master/i18n/countries.php#L248

For the most part there isn't a problem with this in shipping, since the customer chooses United Kingdom, but then GB is chosen in the backend. An issue occurs when there are user entered values though like in Per Product Shipping: http://cld.wthms.co/1cHUE/2WG1Qjzo. In this instance, "UK" will just not work.

With a quick look in ZD, I found over 30 tickets with this exact issue, where they needed to change UK to GB.

Thoughts on having some type of backend conversion in core for this?

**Comment by mikejolley** [comment]
The only place core has a country code input I believe is tax, and we handle that https://dl.dropboxusercontent.com/s/5dumcns556duc6v/2015-12-17%20at%2015.58.png?dl=0 Shouldn't this go in PP shipping?

**Comment by roykho** [comment]
I think @WPprodigy is referring to this https://github.com/woothemes/woocommerce/blob/master/i18n/countries.php#L248

So anything entered with UK would not match GB.

**Comment by mikejolley** [comment]
The logic for mapping UK to GB would have to go in whatever plugin using the country code. E.g. per product shipping would need to map them because core wouldn't touch said logic when querying the rates, and core cannot send 2 country codes for a package (each package has one destination country).

In tax settings as I pointed out, we will input GB if they select UK when inputting the code.

GB is the country code, which I would have thought to be common knowledge here. I mean, for example, when you go abroad, the sticker on your car is GB not UK. ¯\_(ツ)_/¯
