### ISSUE TITLE
Disable wc_lostpassword_url

### ISSUE THREAD

**Issue by enricodeleo** [woothemes/woocommerce#9896]
Triggering the filter `wc_lostpassword_url` causes an error with WP-API and Basic Authentication.

The error is `BadMethodCallException: Call to a member function get_page_permastruct() on a non-object (NULL)`

Is it possible to completely remove this filter? I tried with 

```
function remove_filter_lostpassword() {
  remove_filter( 'lostpassword_url', 'wc_lostpassword_url', 10 );
}
add_action( 'init', 'remove_filter_lostpassword' );
```

But it doesn't work. 

I get this stacktrace:

```
/web/wp/wp-includes/
link-template.php(314): _get_page_link()
/web/wp/wp-includes/
link-template.php(143): get_page_link()
/web/app/plugins/woocommerce/includes/
wc-page-functions.php(72): get_permalink()
/web/app/plugins/woocommerce/includes/
wc-page-functions.php(139): wc_get_page_permalink()
/web/wp/wp-includes/
plugin.php(235): wc_lostpassword_url()
/web/wp/wp-includes/
general-template.php(523): apply_filters()
/web/wp/wp-includes/user.php(141): wp_lostpassword_url()
/web/wp/wp-includes/
plugin.php(235): wp_authenticate_username_password()
/web/wp/wp-includes/
pluggable.php(587): apply_filters()
/web/app/plugins/verticomics-basic-auth/
basic-auth.php(31): wp_authenticate()
/web/wp/wp-includes/
plugin.php(235): JSON_Basic_Auth::json_basic_auth_handler()
[ ... ]
```

Any idea?

**Comment by mikejolley** [comment]
Thanks for the stack trace, so whats the actual error you're seeing :)

**Comment by enricodeleo** [comment]
@mikejolley sorry I forgot to paste the error itself :D `BadMethodCallException: Call to a member function get_page_permastruct() on a non-object (NULL)`

**Comment by mikejolley** [comment]
verticomics-basic-auth? The error is coming because our function uses get_permalink. WordPress throws the error because for some reason, $wp_rewrite may not exist yet. Not really sure what you or that plugin is doing there tbh but I'm guessing its running before 'init' because your code above would work in normal circumstances.

Try using plugins_loaded instead of init. If that fails, I'd look deeper into why your plugin(s) run before init and why.
